### ISSUE TITLE
Cannot set EasyEffects spectrum analyzer to 60fps

### ISSUE THREAD

**Issue by minecraft2048** [wwmm/easyeffects#1001]
In PulseEffects 5.0.4-1 I can set the spectrum analyzer to update at very smooth 60fps. In easyeffects-git-6.0.0.r6.g476cdfb9-1 from easyeffects-git there is no way to set the update rate:

![image](https://user-images.githubusercontent.com/2445636/124873578-000bcc00-e00a-11eb-8409-dfddb0c31603.png)

Here is the spectrum analyzer setting in PulseEffects:

![image](https://user-images.githubusercontent.com/2445636/124873740-347f8800-e00a-11eb-88bb-255ef07def02.png)

It looks very laggy to me

**Comment by wwmm** [comment]
Although the move from GStreamer to native PipeWire filters has brought us many benefits there were small disadvantages too. The spectrum plugin used before is a built-in GStreamer plugin that I could not reuse inside a PipeWire filter. So I had to write my own simple spectrum plugin and it has some limitations at this moment.

The frequency of updates is tied to how often PipeWire sends us a new audio buffer. And this depends on the current server latency. When only a high latency app like Spotify is running Pipewire latency is high . And we recevei few buffers per second. When a low latency app is running we receve more buffers per second and the spectrum will be updated more frequently as a result.

Honestly I am not sure about how to handle this situation. I will need some time reading other spectrum codes to learn how people deal with this.

**Comment by halfrafu** [comment]
@wwmm I've got an idea on how you could do this, hope you'll find it useful.
Instead of calculating spectrum for a whole sample do it several times for (audio sampling)/(spectrum sampling) samples (800 samples with PipeWire's default 48kHz audio sampling and 60Hz spectrum sampling) and keep them in memory as "spectrum frames". There might be some samples left and these should be included in next spectrum calculation.
I think the only problem is that 800 samples at 48kHz audio sampling can be too little to properly measure low frequencies but you can include earlier and/or later samples in each spectrum frame.

**Comment by wwmm** [comment]
>I think the only problem is that 800 samples at 48kHz audio sampling can be too little to properly measure low frequencies but you can include earlier and/or later samples in each spectrum frame.

It definitely is. At this moment I am doing the calculation with 4096 bands in order to have better resolutions at the lowest frequencies. But as was also forcing a high number of bands in the GStreamer pluguin I imagine that they have overcome this difficulty somehow. I think I will have to find some free time to read its source code and see what they did.

**Comment by tleb** [comment]
I don't believe much can be done to solve this, apart from asking for a lower quantum on the easyeffects sink node when the spectrum analyzer is displayed. Splitting the buffers in blocks that get displayed over time would increase latency, which isn't ideal for audio visualisation.

Should this be an option (can impact performance/battery life)? What would be a good value? 512/48000 looks OK to me (experimented using `pw-metadata -n settings 0 clock.force-quantum 512`). It seems like the limit becomes the block size, as transients aren't really shown. Is it frequent to do FFT on 2 different block sizes? It would allow displaying low frequencies with a big block and fast transients on higher up frequencies with a smaller block.

Also, shouldn't the block size used for the visualisation depend on the rate? eg if 96kHz => twice as many samples as 48kHz, to be able to grasp the same low frequencies.

**Comment by wwmm** [comment]
>apart from asking for a lower quantum on the easyeffects sink node when the spectrum analyzer is displayed

I am not sure this is possible to do at runtime without destroying the sink and recreating it. What would cause some undesirable side effects.

>Should this be an option (can impact performance/battery life)?

The lower the latency, the more CPU power is going to be used. So yes. It will impact battery life.

>What would be a good value? 512/48000 looks OK to me 

I haven't tested this in a long time but I remember that the results may change a lot with sampling rate. I don't know if it is still the case.

>Also, shouldn't the block size used for the visualisation depend on the rate? eg if 96kHz => twice as many samples as 48kHz, to be able to grasp the same low frequencies.

We have no control over which is the rate or size of the buffer we receive at a given time. In the filter callback PipeWire just says "for this buffer this is the rate and size". It is totally up to it to decide the values. The filter has to find a way to work with whatever is coming. And we can't assume things will remain the same when the next buffer comes. Rate and buffer size may have totally different values from one filter callback call to another. It is the price to pay for dynamic latency and sampling rate.

**Comment by wwmm** [comment]
>experimented using pw-metadata -n settings 0 clock.force-quantum 512
>I am not sure this is possible to do at runtime without destroying the sink and recreating it.

Let me explain things better. `pw-metada` will obviously work at runtime. But this is an external tool that is forcing the whole server and all the audio clients to use a fixed latency. What may not be what the user wants. I was thinking about a solution that can be done at runtime in EasyEffects code. This does to seem viable.

**Comment by wwmm** [comment]
>The solution to update the graph's latency as you wish would be to set the PW_KEY_NODE_LATENCY property (on the sink node) to the wanted latency; using metadata should only be for global runtime changes. This node.latency property only affects the monitored subsection of the graph. I just tested with a dumb pw_filter, changing the latency using pw_filter_update_properties does work as expected.

Interesting. I imagine that there is a way to restore the dynamic switching by setting it to null or something similar. 

>Sorry my sentence wasn't clear, the question part was if it should be an option. :)

Definitely an option. By default we won't be forcing fixed latency. Specially because the spectrum is useless once we close the window. So sacrificing dynamic sampling rate switching because of the spectrum and level meters is not worth it.

>You could ask PW to do resampling for you if the rate is a real issue

Is there a way to ask it to do resampling before and after a given `pw_filter`? That would be nice. 

>or the block sizes could be adapted dynamically to handle the latest rate.

Maybe in the spectrum plugin. On the others it is probably better and easier to just use whatever pipewire is giving.

>In practice things won't change at every cycle.

Unfortunately audio clients are not always so nice (I am looking at you `Audacity` :smile: ).

**Comment by wwmm** [comment]
>About resampling, it's a feature provided to pw_stream, not pw_filter which is DSP-oriented. Streams are geared towards "standard" apps that might want to provide/use format negotiation and have PW adapt the format to the stream's request (hence resampling, channel mixing, format conversion).

This is sad. We will still have to do resampling on our own for plugins that work only with a specific sampling rate...

>What's Audacity behavior? :)

Hahaha. For some weird reason Audacity's backend probes the server for all possible combinations of audio formats and rate. I imagine its developers have their reasons for doing so but they do it in the worse possible manner. When Audacity starts it creates/destroys an insane amount of streams. A huge number of them in sequence. Each with a different configuration. Based on whether or not the attempt failed they assume if the audio format and rate is supported or not. Super annoying... I had to change our code a few times in the past do deal with Audacity's aggressive behavior.

Discord's app is another offender but for different reasons. I do not know what it was done in its code but most of the times people experience crackling in EasyEffects they are using Discord...

**Comment by lilxandrias** [comment]
This should be solved.

**Comment by wwmm** [comment]
I have made some changes to the spectrum plugin update rate. I think that now different sampling rates finally feel the same visually. But as the solution is a little tricky this has to be tested on other systems besides mine.

**Comment by wwmm** [comment]
I think it is as good as it can be considering the current limitations. Let's close this issue.
