### ISSUE TITLE
Can't find a way to toggle an individual effect

### ISSUE THREAD

**Issue by AlexFolland** [wwmm/easyeffects#1004]
In PulseEffects, I could toggle an individual effect with a toggle switch.

In EasyEffects, I can only trash an effect so that it gets removed completely, or bypass all effects at once, but I have not found a simple way to toggle a single effect.

Is this possible and I'm missing it?  Thanks for EasyEffects.  It's awesome.

**Comment by wwmm** [comment]
It is a little different now. In order to make the plugins name list cleaner that toggle button from the old versions became the `bypass` button you will find next to the plugin parameters controls.

**Comment by wwmm** [comment]
This is an example
![Screenshot from 2021-07-09 21-27-20](https://user-images.githubusercontent.com/16225172/125146503-7ab51400-e0fc-11eb-91cc-b826e2727ddd.png)
Each plugin has a `Bypass` button like this one at the top. In some cases that button is in a little different position but all plugins have one if I am not mistaken.

**Comment by AlexFolland** [comment]
Okay, I see that "Bypass" button here now.  I wasn't really looking all the way over here.  I understand.  Thanks!  We can close this.

![image](https://user-images.githubusercontent.com/601517/125146559-39f8d300-e0db-11eb-8a34-77bbf5b6c31e.png)
