### ISSUE TITLE
Unable to set realtime priorities

### ISSUE THREAD

**Issue by mikoxyz** [wwmm/easyeffects#1008]
Hi!

I upgraded to EasyEffects, and I noticed that the latency was noticeably higher than with PulseEffects + the realtime priorities. I snooped around the settings a bit, and I noticed that there wasn't a setting to adjust the priorities; where did this go?

Apologies for the brevity; I need to go in a bit

--
~miko

**Comment by wwmm** [comment]
The plugins are already using Realtime priorities. Pipewire is the one handling this so we do not have that setting anymore.

The difference in latency probably comes from the fact that PulseEffects was forcing the server to always be in "low latency" even when it was not necessary. Now that we are using native PipeWire filters we follow the dynamic latency change done by the server. So if the latency is high the most likely reason is that the audio app you are using requests high latency. You can see it running `pw-top`.

For example Spotify requests high latency. When a web browser is playing something the requested latency is a lot smaller and PipeWire dynamic adjusts the whole graph latency to this new lower value. EasyEffects is just following the flow. Most of our filters change the audio buffer in-place and do not even add latency.

**Comment by wwmm** [comment]
One way to mimic the old behavior would be to edit PipeWire's configuration files and force a small `quantum` value. But this will waste cpu power in situations where using high latency is fine. Another solution would be to launch only the app you are using with an environment variable that overwrites its latency request. I do not remember the variable name now but there is one that allows this to be done. This way PipeWire will put that particular app in low latency. And once you are not using it anymore the server will be free to choose a higher value again.

**Comment by wwmm** [comment]
>Most of our filters change the audio buffer in-place and do not even add latency.

Same thing with our virtual devices. They do not add latency. That latency setting in  PulseEffects is related to the buffering done inside the GStreamer pipeline. As the default latency request for this was is lower than the latency requested by most apps Pipewire was all the time in a low latency value. Even if the audio app itself had no need for this. What PulseEffects does is not nice to cpu power usage.

**Comment by mikoxyz** [comment]
> The filters thread is already using Realtime priorities. PipeWire is the one handling this so we do not have that setting anymore.
> 
> The difference in latency probably comes from the fact that PulseEffects was forcing the server to always be in "low latency" even when it was not necessary. Now that we are using native PipeWire filters we follow the dynamic latency changes done by the server. So if the latency is high the most likely reason is that the audio app you are using requests high latency. You can see it running `pw-top`.
> 
> For example Spotify requests high latency. When a web browser is playing something the requested latency is a lot smaller and PipeWire dynamically adjusts the whole graph latency to this new lower value. EasyEffects is just following the flow. Most of our filters change the audio buffer in-place and do not even add latency.

Oh! I actually didn't know that! My limited testing yesterday was entirely based on pausing and unpausing in mpd, which I assume requests high latency; after actually using EasyEffects for a bit, I can confirm that the latency isn't high at all in applications that request low latency. Sorry about that ^^:
