### ISSUE TITLE
Crash with Gdk:ERROR (gtk/gdk/x11/gdkglcontext-x11.c gdk_x11_gl_context_end_frame)

### ISSUE THREAD

**Issue by AlexWayfer** [wwmm/easyeffects#1009]
Just basic setup after PE v5 replacement on Arch Linux, only Bass Enchancer enabled. Crashed after a menu button click, I guess, but not the first: I was in the menu a few times. Spectrum was enabled by default.

```
(easyeffects:6181): easyeffects-DEBUG: 01:15:50.447: new default output device: alsa_output.usb-ASUS_Xonar_U7_MKII-00.analog-stereo
(easyeffects:6181): easyeffects-DEBUG: 01:15:50.450: new default input device: alsa_input.usb-ASUS_Xonar_U7_MKII-00.analog-stereo
(easyeffects:6181): easyeffects-DEBUG: 01:15:50.451: application: device alsa_card.usb-ASUS_Xonar_U7_MKII-00 has changed profile to: output:analog-stereo+input:analog-stereo
(easyeffects:6181): easyeffects-DEBUG: 01:15:50.451: application: device alsa_card.pci-0000_08_00.1 has changed profile to: output:hdmi-stereo
(easyeffects:6181): easyeffects-DEBUG: 01:15:50.451: application: device alsa_card.usb-046d_Logitech_Webcam_C925e_33B17ADF-02 has changed profile to: input:analog-stereo
(easyeffects:6181): easyeffects-DEBUG: 01:15:50.451: application: device alsa_card.pci-0000_0a_00.4 has changed profile to: output:iec958-stereo
(easyeffects:6181): easyeffects-DEBUG: 01:16:17.043: soe: output_level: new PipeWire blocksize: 1024
(easyeffects:6181): easyeffects-DEBUG: 01:16:47.177: soe: pipeline latency: 0.000000 ms
(easyeffects:6181): easyeffects-DEBUG: 01:17:16.456: pipe_manager: Stream/Output/Audio 343 Google Chrome was added
(easyeffects:6181): easyeffects-DEBUG: 01:17:16.457: pipe_manager: new metadata property: 343, target.node, Spa:Id, 76
(easyeffects:6181): easyeffects-DEBUG: 01:17:16.457: pipe_manager: Google Chrome port 342 is connected to easyeffects_sink port 75
(easyeffects:6181): easyeffects-DEBUG: 01:17:16.457: pipe_manager: Google Chrome port 341 is connected to easyeffects_sink port 79
(easyeffects:6181): easyeffects-DEBUG: 01:19:19.314: pipe_manager: Stream/Output/Audio 351 Google Chrome was added
(easyeffects:6181): easyeffects-DEBUG: 01:19:19.314: pipe_manager: new metadata property: 351, target.node, Spa:Id, 76
(easyeffects:6181): easyeffects-DEBUG: 01:19:19.315: pipe_manager: Google Chrome port 352 is connected to easyeffects_sink port 75
(easyeffects:6181): easyeffects-DEBUG: 01:19:19.315: pipe_manager: Google Chrome port 353 is connected to easyeffects_sink port 79
(easyeffects:6181): easyeffects-DEBUG: 01:19:24.345: pipe_manager: Stream/Output/Audio Google Chrome was removed
**
Gdk:ERROR:../gtk/gdk/x11/gdkglcontext-x11.c:189:gdk_x11_gl_context_end_frame: assertion failed: (context_x11->frame_fence == 0)
Bail out! Gdk:ERROR:../gtk/gdk/x11/gdkglcontext-x11.c:189:gdk_x11_gl_context_end_frame: assertion failed: (context_x11->frame_fence == 0)
fish: Job 1, 'env G_MESSAGES_DEBUG=easyeffect…' terminated by signal SIGABRT (Abort)
```

**Comment by wwmm** [comment]
It is the first time I see an error like that. We do not even call this function. My guess is that this is an gtk4 bug. Which desktop are you using? Are you using wayland or Xorg? Based on the error it seems to be Xorg. 

I did all the tests while running Wayland on GNOME. I wonder if gtk4 has some weird bug in Xorg...

**Comment by AlexWayfer** [comment]
> Which desktop are you using? Are you using Wayland or Xorg? Based on the error it seems to be Xorg.

Yep, X11 as I know.



> I wonder if gtk4 has some weird bug in Xorg...

I found only this: https://gitlab.gnome.org/GNOME/gtk/-/issues/2902

Should I create a similar issue for Gtk repo?

**Comment by wwmm** [comment]
>Should I create a similar issue for Gtk repo?

Eventually yes. I do not see how I could fix this on my side. But first it is better to find a way of reliably reproducing it. Otherwise the chances of getting gtk folks to fix this will be low. I did a few tests in GNOME while running a Xorg session and I could not trigger the crash. Do you remember which button did you click?

**Comment by AlexWayfer** [comment]
> Do you remember which button did you click?

I wrote in the issue's description: the menu button (hamburger button, 3 stripes button) in the top right corner. But, as also I wrote, not each and not every click, just around 5th. So, I didn't get for now a reproducible scenario, will try later or close it.

**Comment by wwmm** [comment]
I clicked on the setting menu button a few times. Nothing happened. That what this button does is showing a popover menu it is possible that the issue is not with the button click but with the operations gtk does under the hoods to show a popover menu.

**Comment by AlexWayfer** [comment]
But dude, this popup is very laggy… haha! I don't know which issues are these, but anyway I don't want to blame someone.

Starting from checkboxes (toggles), where behavior is not too intuitive and they don't toggle each time, through color select, which doesn't close the menu popup and you have to click on a color modal window to close menu popup before the actual color selecting, and finishing with… haha, how to describe this:

![image](https://user-images.githubusercontent.com/6510020/125178369-f2fb0280-e1ec-11eb-8edf-64116d3e4b5d.png)

I just can't close this popup now. At all. It's over system and I guess I have to reload my whole shell.

No, it didn't help. So, I guess, then I have to restart the EE and it can be its issue. 😅

**Comment by wwmm** [comment]
At some point I will have to open an issue in the gtk page. Sometimes unexpected things happens with popover menus. I have noticed problems when trying to close them in some occasions. I have already read the documentation many times. I do not see how I could fix this. 

Another weird bug is when you move to another virtual desktop while a popover menu is open. The menu goes to the other desktop with you while the window stays in the same place. This did not happen in gtk3...

**Comment by AlexWayfer** [comment]
Oh, the bright future is not too bright with Gtk4… but, at least, bright enough with PipeWire! OK, let's see, I'll test a few more days.

**Comment by AlexWayfer** [comment]
I've got a scenario for this crash, but pretty phantom anyway.

1. Open menu.
2. Click on another tab (Switch between "General" and "Spectrum").
3. Close menu.
4. Repeat.

Around after 10–20 attempts I can get a crash, around 2 per a few minutes.

Maybe there is an easier scenario, I'm not sure.

I've testes two more scenarios:
1. Just open and close, without tab switching — there are other bugs (it does not always open), but I didn't got a crash.
2. I was repeating described scenario slow and got a crash so I've removed words about "do it fast". There are just around 20 attempts, as I wrote.

**Comment by wwmm** [comment]
>Maybe there is an easier scenario, I'm not sure.

I hope there is because this method may be a little tiring :smile: So far nothing

**Comment by wwmm** [comment]
I wonder if this crash still happens.

**Comment by AlexWayfer** [comment]
> I wonder if this crash still happens.

I've tested by my own scenario and saw no crashes.

Also EE has moved to GTK 4, so I believe we can close this.

Thank you.
