### ISSUE TITLE
changing equalizer # bands crash

### ISSUE THREAD

**Issue by HarHarLinks** [wwmm/easyeffects#1010]
1. enable eq
2. play music
3. change # of bands from 32 -> 16
4. apphang
5. journal spammed with `easyeffects[6556]: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed`

Version         : 6.0.1-1 (archlinux)

**Comment by wwmm** [comment]
>change # of bands from 32 -> 16

Nothing unusual happened here. And no messages on the system log because of that. Kill the current instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see what is going on in your computer when you change the number of bands.

**Comment by HarHarLinks** [comment]
might have been a one-off
