### ISSUE TITLE
EasyEffects - How to copy my former equalizer settings from PulseEffects?

### ISSUE THREAD

**Issue by ratcheer** [wwmm/easyeffects#1013]
I looked through the .config directories and copied the *.json files from .config/pulseeffects/output to .config/easyeffects/output

EasyEffects "sees" these files and offers a Load button for them, but clicking that button does not apply my settings; nothing changes. So, I'm apparently not doing this, correctly. How should I do it? Is it even possible?

**Comment by wwmm** [comment]
At some point in EasyEffects development I had to do a tough call. The library I was using before(c++ Boost) to handle json files was a source of headaches to many package maintainers. But when I finally found a better replacement I realized that it saved json files using a different convention that is incompatible with the old library. 

As in a way EasyEffects is a "new application" I decided that if we were ever going to move to another library there would be no better moment than this. But now we have to deal with this preset incompatibility problem somehow. The main issue is on how the old library saved numbers. Instead of writing something like `"pi": 3.14159265359` what it did was `"pi": "3.14159265359"`. All the numbers are surrounded by quotes. That is not what other c++ libraries for json do.

Same problem with boolean. Instead of writing `"enable": true` the old library did `"enable": "true"`. Hopefully in the future someone will figure out how to write a script that does the conversion. For now what you can do is using this site https://csvjson.com/json_beautifier and checking the option to remove quotes on numbers. It is on the panel at the right side. Where the processed output will be displayed. But unfortunately ti does not remove quotes from boolean variables. So that ones will have ot be fixed manually.

**Comment by Mlocik97** [comment]
I can create website that will remove quotes on both number and booleans.

**Comment by wwmm** [comment]
>I can create website that will remove quotes on both number and booleans.

That would be very helpful. While we could try to have a converter embedded in EasyEffects the more people decide to have a "fresh start" in EasyEffects the less useful this code will become. And we already have too much code for the amount of people actually taking care of it.

**Comment by Mlocik97** [comment]
At least I know JavaScript so... I already started working on it.

**Comment by ratcheer** [comment]
Thank you, wwmm. I hand copied (on paper) my PulseEffects settings and recreated them in EasyEffects. They are loading, now.

However, my output volume is now much too low. I have to turn it up to +23 dB to get anything like what I was getting with PulseEffects. I have verified that the volumes are correctly set in pavucontrol and EasyEffects - all at 100%. I will open a new Issue on this, if you want.

**Comment by wwmm** [comment]
>However, my output volume is now much too low. I have to turn it up to +23 dB to get anything like what I was getting with PulseEffects. I have verified that the volumes are correctly set in pavucontrol and EasyEffects - all at 100%. I will open a new Issue on this, if you want.

It is probably better to open a new issue for this. When you do that kill the current instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see what is going on. THere should not be much different in volume between EasyEffects and PulseEffects.

**Comment by ratcheer** [comment]
Will do. Thank you.

**Comment by Mlocik97** [comment]
![Snímka obrazovky z 2021-07-11 18-31-41](https://user-images.githubusercontent.com/34808350/125202924-449b9f80-e276-11eb-8587-53355e98ec10.png)

it seems to work little, it contains bug, downloading doesn't work yet, and uploading too. But converting is working.

**Comment by wwmm** [comment]
I think it will be a good idea to create a section in the wiki for this site.

**Comment by Mlocik97** [comment]
![Snímka obrazovky z 2021-07-11 19-09-31](https://user-images.githubusercontent.com/34808350/125204048-8ed34f80-e27b-11eb-8fea-02072dd1cdf2.png)

I think it's working fine, Now I need only to fix few things and it will be complete.

**Comment by Mlocik97** [comment]
So it's working, also file upload, and file download... ofc, I still didn't fix some problems and mainly I'm not checking type of input file, so You can upload even .png file to it, it will just crash. But with correct inputs it works.

**Comment by Mlocik97** [comment]
https://pe-to-ee-preset-converter.herokuapp.com/

**Comment by Mlocik97** [comment]
Added to Wiki

**Comment by wwmm** [comment]
>Added to Wiki

Thanks! :-)

**Comment by bphd** [comment]
> https://pe-to-ee-preset-converter.herokuapp.com/
> 
> @wwmm

Thanks for your dedication

I tested it and

![Screenshot_20210712_095034](https://user-images.githubusercontent.com/10251866/125250590-b6b3c900-e2f6-11eb-8a69-5c828fdda81e.png)

**Comment by Mlocik97** [comment]
```
And applying Mlocik97's correction doesn't change anything.
```

So converted JSON doesn't load? Is there something else that changed in JSON structure?
The best would be having same JSON for both EE and PE so I can compare what it changed... by what was said there, the only thing I'm now doing in converter is changing data type of numeric strings to numbers and booleanish strings to booleans.

About testing does it has some other problems?

**Comment by Mlocik97** [comment]
I just put @Digitalone1 's presets to Diff, and I see new preset contain blacklist property, is it required now by EE? Also I see properties state are removed, instead plugin_order contain only active plugins.

**Comment by bphd** [comment]
> > And applying Mlocik97's correction doesn't change anything.
> 
> So converted JSON doesn't load? 

> Mine works OOB

**Comment by Mlocik97** [comment]
```
The best would be having same JSON for both EE and PE so I can compare what it changed...
```

Sry for misunderstanding, I was talking about presets not from my converter but about two working samples from application from PE version and from EE version.

**Comment by bphd** [comment]
> > The best would be having same JSON for both EE and PE so I can compare what it changed...
> 
> Sry for misunderstanding, I was talking about presets not from my converter but about two working samples from application from PE version and from EE version. So I can see what changed in structure and update my converter as needed. This is more question to @wwmm .

Sure, I didn't understand for 2 minutes but soon after I edited to correct my words

**Comment by Mlocik97** [comment]
My bad English doesn't help...

so what I see, is that my converter is working as it should, but somehow EasyEffects still doesn't load converted presets.

**Comment by Mlocik97** [comment]
I just in 10 minutes added 2 new features to converter... Now You can change JSON even after it was uploaded. It also add blocklist property to structure...

When I will have time, I will also convert "state" if plugin is active, and add feature to upload multiple files and download multiple files at once.

**Comment by wwmm** [comment]
While Boost saved empty blocklist as `"blocklist": ""` instead of `"blocklist": []` as the new library I do not see yet a reason why this should be breaking the whole conversion process. Strange... 

>When I will have time, I will also convert "state" if plugin is active, and add feature to upload multiple files and download multiple files at once.

The state variable is not used. anymore. EasyEffects should just ignore it. But it may still be useful for the preset converter. In EasyEffects the `plugins_order` parameter has only the plugins that the user mnually added in EasyEffects window and not all the available plugins like it was in PulseEffects. Maybe the converter can use the value of the state variable to decide which names have to be in the plugins_order array.

**Comment by bphd** [comment]
It's very difficult without PE/EE to have a big audio system in a quiet environment, any sound change in a video/song makes my audio bang, and it's very uncomfortable for the people around. I hope the soft will work soon

**Comment by wwmm** [comment]
>I hope the soft will work soon

I am not sure I understand. The application is not working in your computer? I know that the old presets cannot "just be used" in EasyEffects. But the application itself should be working and it should be possible to manually set the parameters.

**Comment by bphd** [comment]
> > I hope the soft will work soon
> 
> I am not sure I understand. The application is not working in your computer? I know that the old presets cannot "just be used" in EasyEffects. But the application itself should be working and it should be possible to manually set the parameters.

I don't really set manually my parameters, I haven't made years of studies in audio for that
(manner of speaking, but you understand)

**Comment by wwmm** [comment]
Ok. No problems :-). But as I did not do many tests trying to force an PulseEffects preset to be loaded in EasyEffects it is possible that some side effects were caused that we are not aware of yet. When you test the application again try to reset it first from our settings menu or from the command line `easyeffects -r`.

**Comment by Mlocik97** [comment]
New version of converter should also convert state of plugin.

**Comment by Mlocik97** [comment]
Can someone try to convert PulseEffects preset and use it for EasyEffects if it will work now? I don't see what else should change in preset.

**Comment by wwmm** [comment]
I did a quick test now and it was fine. I see no issues so far.

**Comment by Mlocik97** [comment]
I see only one problem, and that's Heroku,... when web app is inactive, server goes to sleep mode after 30 minutes (in free plan), and when someone open web app, it takes little more time to load,... maybe I can create server-side script that will ping it's server every x minutes so server doesn't go to sleep mode.

**Comment by wwmm** [comment]
>maybe I can create server-side script that will ping it's server every x minutes so server doesn't go to sleep mode

Honestly I think you could just add a note to the wiki warning users about the page loading time. It is not the end of the world waiting a little longer for it to load.

**Comment by Mlocik97** [comment]
I think I solved performance problem. I was also thinking to migrate it to another PaaS/IaaS service or to Github Pages,...

**Comment by AbsurdlySuspicious** [comment]
Simple script to convert everyting

```bash
#!/usr/bin/env bash

# Replace with 'input' if you want to convert input preset
section='output'

# Convert boolean and numeric strings + replace invalid empty blocklist
perl -i -pe 's/"(true|false|[\d\.-]+)"/$1/g; s/(?<="blocklist": )""/[]/g' "$@"

# Fix plugins order using v5 state field (you set up plugin order is preserved)
for f in "$@"; do

  # Extract active plugins in right order
  po_src=$(jq ".$section"' | . as $out | .plugins_order | .[] | . as $pn | select($out | to_entries | .[] | .key as $key | select(["blocklist", "plugins_order"] | any(. == $key) | not) | select(.value.state != false) | .key == $pn)' "$f" -r)

  # Replace order array in config with new onw
  jq --arg po "$po_src" '($po | split("\n")) as $poa | '".$section.plugins_order"' = $poa' "$f" >tmp
  mv tmp "$f"
done
```

Use it like this: `bash convert.sh *.json`  
Requires jq and perl installed

**Comment by Mlocik97** [comment]
@AbsurdlySuspicious Can I include Your script on my website and to wiki?

**Comment by AbsurdlySuspicious** [comment]
Yeah, sure, assume its licensed under CC0 :D

**Comment by Mlocik97** [comment]
Script is avaiable for download on website.

**Comment by radimsuckr** [comment]
@wwmm it'd be good if this was highlighted somewhere in the readme. I spent a few weeks without easyeffects because I didn't have time to dive into the issue and as it turned out, it's actually quite easy and took me around 30 seconds to resolve with this thread. :pray:

**Comment by Mlocik97** [comment]
This was mentoyed in Changelog, in Wiki and in pinned issue. I think it's visible enough.

**Comment by wwmm** [comment]
>This was mentioned in Changelog, in Wiki and in pinned issue.

It is true. But I don't mind having this information in the readme. Eventually the pinned issue will be replaced by another. And as most distribution will take a lot of time until they have the required dependencies to move from PulseEffects to EasyEffects by the time some people are able to install EasyEffects they may have forgotten that the wiki has the guide to convert presets.

**Comment by radimsuckr** [comment]
Yeah it definitely is documented but I suspect I'm not the only busy (lazy) one. And for us it'd be useful to see it on the main page of the repository. :grin: Especially when the migration process is so simple.
