### ISSUE TITLE
EasyEffects output volume much too low

### ISSUE THREAD

**Issue by ratcheer** [wwmm/easyeffects#1015]
My output volume is now much too low. I have to turn it up to +23 dB to get anything like what I was getting with PulseEffects. I have verified that the volumes are correctly set in pavucontrol and EasyEffects - all at 100%. I will open a new Issue on this, if you want.

_Originally posted by @ratcheer in https://github.com/wwmm/easyeffects/issues/1013#issuecomment-877813149_

**Comment by ratcheer** [comment]
G_MESSAGES_DEBUG=easyeffects easyeffects
(process:6500): easyeffects-DEBUG: 10:19:37.185: main: locale directory: /usr/share/locale
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.207: presets_manager: system input presets directory: "/etc/easyeffects/input";
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.207: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input";
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.207: presets_manager: system output presets directory: "/etc/easyeffects/output";
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.207: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output";
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.208: presets_manager: user presets directory already exists: /home/tim/.config/easyeffec
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.208: presets_manager: user presets directory already exists: /home/tim/.config/easyeffec
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.208: presets_manager: user presets directory already exists: /home/tim/.config/easyeffec
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.208: presets_manager: user presets directory already exists: /home/tim/.config/easyeffec
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.208: presets_manager: user presets directory already exists: /home/tim/.config/easyeffec
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.223: application: easyeffects version: 6.0.1
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.224: pipe_manager: compiled with pipewire: 0.3.31
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.224: pipe_manager: linked to pipewire: 0.3.31
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: core version: 0.3.31
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: core name: pipewire-0
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: found metadata: settings
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: found metadata: default
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: found metadata: route-settings
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: Audio/Sink 40 alsa_output.pci-0000_0b_00.4.iec958-stereo was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: Stream/Output/Audio 363 spotify was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: Audio/Sink 161 alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_Fii
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: spotify port 255 is connected to alsa_output.usb-GuangZhou_FiiO_Elect
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: spotify port 346 is connected to alsa_output.usb-GuangZhou_FiiO_Elect
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: Audio/Sink 135 easyeffects_sink was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: Audio/Source/Virtual 51 easyeffects_source was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "nam
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "n
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.226: pipe_manager: new metadata property: 363, target.node, Spa:Id, 196
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.227: pipe_manager: spotify port 346 is connected to easyeffects_sink port 257
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.227: pipe_manager: spotify port 316 is connected to easyeffects_sink port 169
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.227: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "n
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.228: pipe_manager: Filter pe_soe_autogain, id = 318, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.230: pipe_manager: Filter pe_soe_bass_enhancer, id = 256, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.236: pipe_manager: Filter pe_soe_compressor, id = 355, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.242: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.242: pipe_manager: Filter pe_soe_convolver, id = 104, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.245: pipe_manager: Filter pe_soe_crossfeed, id = 179, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.248: pipe_manager: Filter pe_soe_crystalizer, id = 106, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.250: pipe_manager: Filter pe_soe_deesser, id = 97, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.257: pipe_manager: Filter pe_soe_delay, id = 126, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.262: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.263: pipe_manager: Filter pe_soe_echo_canceller, id = 310, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.265: pipe_manager: Filter pe_soe_equalizer, id = 55, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.298: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.304: pipe_manager: Filter pe_soe_exciter, id = 148, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.310: pipe_manager: Filter pe_soe_filter, id = 136, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.316: pipe_manager: Filter pe_soe_gate, id = 142, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.321: pipe_manager: Filter pe_soe_limiter, id = 167, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.327: pipe_manager: Filter pe_soe_loudness, id = 52, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.332: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.332: pipe_manager: Filter pe_soe_maximizer, id = 139, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.337: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.337: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/opti
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.337: pipe_manager: Filter pe_soe_multiband_compressor, id = 175, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.344: pipe_manager: Filter pe_soe_multiband_gate, id = 65, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.350: pipe_manager: Filter pe_soe_output_level, id = 62, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.353: pipe_manager: Filter pe_soe_pitch, id = 174, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.355: pipe_manager: Filter pe_soe_reverb, id = 63, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.361: pipe_manager: Filter pe_soe_rnnoise, id = 84, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.364: pipe_manager: Filter pe_soe_spectrum, id = 81, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.368: pipe_manager: Filter pe_soe_stereo_tools, id = 94, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.424: pipe_manager: Filter pe_sie_autogain, id = 360, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.427: pipe_manager: Filter pe_sie_bass_enhancer, id = 303, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.436: pipe_manager: Filter pe_sie_compressor, id = 283, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.443: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.462: pipe_manager: Filter pe_sie_convolver, id = 273, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.466: pipe_manager: Filter pe_sie_crossfeed, id = 203, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.471: soe: equalizer latency: 0.128000 s
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.471: pipe_manager: Filter pe_sie_crystalizer, id = 197, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.472: soe: loudness latency: 0.085333 s
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.473: soe: maximizer latency: 0.010000 s
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.473: soe: output_level: new PipeWire blocksize: 1024
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.474: pipe_manager: Filter pe_sie_deesser, id = 336, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.480: pipe_manager: Filter pe_sie_delay, id = 237, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.488: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.489: pipe_manager: Filter pe_sie_echo_canceller, id = 232, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.491: pipe_manager: Filter pe_sie_equalizer, id = 211, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.520: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.525: pipe_manager: Filter pe_sie_exciter, id = 190, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.531: pipe_manager: Filter pe_sie_filter, id = 402, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.536: pipe_manager: Filter pe_sie_gate, id = 392, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.542: pipe_manager: Filter pe_sie_limiter, id = 387, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.548: pipe_manager: Filter pe_sie_loudness, id = 382, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.552: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.553: pipe_manager: Filter pe_sie_maximizer, id = 372, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.558: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.558: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/opti
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.559: pipe_manager: Filter pe_sie_multiband_compressor, id = 370, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.566: pipe_manager: Filter pe_sie_multiband_gate, id = 409, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.572: pipe_manager: Filter pe_sie_output_level, id = 313, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.575: pipe_manager: Filter pe_sie_pitch, id = 297, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.577: pipe_manager: Filter pe_sie_reverb, id = 292, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.583: pipe_manager: Filter pe_sie_rnnoise, id = 287, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.586: pipe_manager: Filter pe_sie_spectrum, id = 241, was added
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.589: pipe_manager: Filter pe_sie_stereo_tools, id = 220, was added
easyeffects-INFO: 10:19:37.594: application: disabling global bypass
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.608: sie: output_level: new PipeWire blocksize: 1024
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.686: convolver_ui: irs directory already exists: /home/tim/.config/easyeffects/irs
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.686: convolver_ui: reading the impulse file:
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.889: new default output device: alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.944: application: device alsa_card.pci-0000_09_00.1 has changed profile to: off
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.944: application: device alsa_card.pci-0000_0b_00.4 has changed profile to: output:iec958-stereo
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.944: application: device alsa_card.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FiiO_Q5_FA500396-00 has changed profile to: output:analog-stereo

(easyeffects:6500): easyeffects-WARNING **: 10:19:37.944: soe: convolver: irs file does not exists or it is empty:

(easyeffects:6500): easyeffects-WARNING **: 10:19:37.944: soe: convolver: Entering passthrough mode...
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.981: soe: pipeline latency: 128.000000 ms
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.981: soe: pipeline latency: 213.333344 ms
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.981: soe: pipeline latency: 223.333344 ms

**Comment by ratcheer** [comment]
It looks like I may need several more plugins. Please advise. Thanks.

**Comment by wwmm** [comment]
>It looks like I may need several more plugins. Please advise. Thanks.

They are there. This is what may not be right
```
(easyeffects:6500): easyeffects-WARNING **: 10:19:37.944: soe: convolver: irs file does not exists or it is empty:

(easyeffects:6500): easyeffects-WARNING **: 10:19:37.944: soe: convolver: Entering passthrough mode...
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.981: soe: pipeline latency: 128.000000 ms
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.981: soe: pipeline latency: 213.333344 ms
(easyeffects:6500): easyeffects-DEBUG: 10:19:37.981: soe: pipeline latency: 223.333344 ms
```
The convolver was not able to load the irs file. Is there one set in its window? In any case I do not see a reason why the latency would jump to so high values just because the convolver entered in passthrough mode. Strange... What happens if you do not add the convolver to the list?

**Comment by wwmm** [comment]
Also try to see if there isn't any `input gain` or `output gain` slide value that you were using before and that you forgot to reset when moving the values to EasyEffects. That could explain the volume difference.

**Comment by ratcheer** [comment]
I am only intentionally using the equalizer module. Does it require convolver? I didn't think it does. I'll see what I can figure out. At this point, I don't even know what an irs file is.

My input and output sliders in the equalizer settings are the same as I had them in PulseEffects. Input is -7.2 db to prevent clipping, my bass band is +7.2 DB, and output was 0, except when I put it up +23 to hear any output. In the main EasyEffects volume setting, it  is set at 100%. In pavucontrol, all of the volume sliders are set at 100%.

I am mildly annoyed. PulseEffects had been working perfectly for me, and now all of this. But I know we'll get it worked out

**Comment by ratcheer** [comment]
I went to the convolver plugin in EasyEffects, and clicked "Bypass". It did **not** help. The output volume is still faint.

The convolver says it is using zita-plugin.

**Comment by ratcheer** [comment]
Ok, I have discovered this - 

First, there is an Autogain module that was enabled and set to -23 dB. Bypassing it, I get good output volume. I have never clicked on that module, before.

So, second, it seems that every plugin is enabled by default in my upgrade from PulseEffects to EasyEffects. I do not expect any of them to be enabled unless I specifically enable them. And, as far as I know, that's how PulseEffects had been working.

How can I set EasyEffects to work like PulseEffects did? It seems that if I bypass a module and exit EasyEffects, it is not bypassed the next time I start it.

**Comment by wwmm** [comment]
Oh! I see... As you were trying to reuse your old presets maybe you added all the plugins to the list. Things are a little different in EasyEffects. Now the user is able to actually remove the plugin from the list at the right panel. IF you want only the equalizer it should look like this
![Screenshot from 2021-07-11 15-59-34](https://user-images.githubusercontent.com/16225172/125207155-08117900-e261-11eb-8455-552ad30b43bc.png)
The only entry in the list is the equalizer. If you add more these additional plugins will be active unless you click on the bypass button.

**Comment by josefandersson** [comment]
Was just about to post an issue about my problem but reading your last comment here fixed my problem, thanks!

When I first started easyeffects yesterday my startup script was attempting to run my old presets as usual—which enabled a bunch of plugins with very odd settings that completely stopped the sound (really, no output). After that it didn't help to remove the presets and whatnot because I suspect the plugins had already been enabled. Your comment made me realize that the list of plugins in the Plugins tab are all enabled plugins, unlike Pulseeffects where they where in the list even when disabled.

**Comment by wwmm** [comment]
Yes. The problem with PulseEffects approach is that the user was forced to always see in the plugins list plugins he/she did not wanted. Now you have to add only the ones you want.

**Comment by ratcheer** [comment]
Ok, I will remove all modules except the equalizer. But, again, I did not have to do that in PulseEffects.

**Comment by josefandersson** [comment]
@wwmm Yep yep, makes sense. Wasn't very clear that was the case when there was a bunch of plugins in the list when I first started the program though 😅

**Comment by wwmm** [comment]
>Wasn't very clear that was the case when there was a bunch of plugins in the list when I first started the program though

A side effect of trying to reuse the old presets without converting them. By the default that list is empty in a fresh start.

**Comment by josefandersson** [comment]
@wwmm Yeah I get that, but I'm using `easyeffects -l <preset>` at startup so I never saw the empty list 🤣 Maybe not a lot of people use it like me, but maybe worth having an entry in FAQ to suggest removing all plugins from the list in Plugins tab if sound doesn't work? Either way, you're a freaking legend for making this program dude, seriously thanks. I couldn't stand not having it.

**Comment by ratcheer** [comment]
PS - I try to send regular donations. I will check the status. I appreciate your help, and this is one of my favorite applications. Thank You!

**Comment by wwmm** [comment]
>but maybe worth having an entry in FAQ to suggest removing all plugins from the list in Plugins tab if sound doesn't work?

It is a good idea. 

>PS - I try to send regular donations. I will check the status. I appreciate your help, and this is one of my favorite applications. Thank You!

Thanks!
