### ISSUE TITLE
There's no system tray icon in KDE Plasma. 

### ISSUE THREAD

**Issue by honoris99** [wwmm/easyeffects#1022]
The program runs in the background, it working well but there is no system tray icon. Can you make a update about "show in system tray icon". Thanks and have a nice day.

**Comment by wwmm** [comment]
Hi! Gtk4 does not support tray icons. It is their design choice. I can not change that.

**Comment by honoris99** [comment]
okay i got it, thank you, beautiful program btw, have a nice day.
