### ISSUE TITLE
Error building on Fedora

### ISSUE THREAD

**Issue by Msouza91** [wwmm/easyeffects#1027]
So dnf builddeps pulseeffects didn't pull the correct packages or the dependencies are just considering arch, meson version on F34 repos is still 0.56, but I can install a newer one from pip, glibmm on the other hand requires 2.68, the repos only have 2.66, haven't been able to find a reliable source to install glibmm in this version, tried editing meson.build to require the lower version on the assumption that it wouldn't be that big of a deal since it is a minor version, but it seems to be linked somewhere else or it is not being recognized, despite the package being installed.
![image](https://user-images.githubusercontent.com/19522556/125672911-171c3d55-5735-47d2-ae69-5d42a401065b.png)

**Comment by wwmm** [comment]
At the end of the day Meson uses pkgconfig to find the dependencies. The pkgconfig names do not change with distribution. If it did not find the library it is because it is not installed. Or the package maintainers put the library pkgconfig files in a separated package.

**Comment by wwmm** [comment]
I looked at the glibmm versions I have installed here on Arch Linux and glibmm-2.66 is for gtk3 and not gtk4. It is not going to work.

**Comment by Msouza91** [comment]
To add insult to injury, after this failed attempt, now the application is getting killed if it loses focus or is minimised after is start playing anything.

**Comment by wwmm** [comment]
>now the application is getting killed if it loses focus or is minimized after is start playing anything

Is realtime priorities enabled in our settings menu? If yes disable it. I am not sure why but this became a problem. Fortunately in EasyEffects PipeWire is now the one handling realtime priorities and this is not a problem anymore.

**Comment by Msouza91** [comment]
I had just enabled because I saw it being recommend as a palliative to the Race condition problem when audio is paused or at boot.
Can't wait for the EasyEffects update tho!
