### ISSUE TITLE
Missing Compressor Boost Amount/Threshold Spinbuttons

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1029]
A new "Boosting" mode was added to the Sidechain Compressor, but I see from plugin parameters and official LSP GUI that a boost knob is missing in EE.

Then I found out that 2 boost parameters are available. "Boost Amount" and "Boost Threshold". The first is related to Boosting mode, the second to Upward mode. This means the other one is ignored when switching between Boosting and Upward. Besides both are ignored in Downward mode (this is clear switching all modes in LSP official GUI).

So, two new gsettings have to be added:

```
        <key name="boost-amount" type="d">
            <range min="0.0" max="72.0" />
            <default>6.0</default>
        </key>
        <key name="boost-threshold" type="d">
            <range min="-60.0" max="-120.0" />
            <default>-72.0</default>
        </key>
``` 

Then two new spinbuttons Boost Amount and Boost Threshold to Compressor UI. Or only one Boost, switching between Amount and Threshold one when the mode is changed, but this is difficult. I say just show both of them and then write in the documentation their meaning.

**Comment by Digitalone1** [comment]
My mistake, Boost Threshold spinbutton is present, I didn't notice it. It's only Boost Amount for Boosting Mode missing

**Comment by Digitalone1** [comment]
Maybe it's better to distinguish them naming Upward Boost and Boosting Threshold

**Comment by wwmm** [comment]
>Maybe it's better to distinguish them naming Upward Boost and Boosting Threshold

I agree. In the window i is better to rename like this. LSP choice of words was confusing. But under the hoods it will be better to keep following it.

**Comment by wwmm** [comment]
>Then I found out that 2 boost parameters are available. "Boost Amount" and "Boost Threshold". The first is related to Boosting mode, the second to Upward mode. This means the other one is ignored when switching between Boosting and Upward. Besides both are ignored in Downward mode (this is clear switching all modes in LSP official GUI).

Ok. I will add some code to hide these spinbuttons depending on the mode value selected in the dropdown.

**Comment by Digitalone1** [comment]
> > Then I found out that 2 boost parameters are available. "Boost Amount" and "Boost Threshold". The first is related to Boosting mode, the second to Upward mode. This means the other one is ignored when switching between Boosting and Upward. Besides both are ignored in Downward mode (this is clear switching all modes in LSP official GUI).
> 
> Ok. I will add some code to hide these spinbuttons depending on the mode value selected in the dropdown.

Do not do it. You will have to do it 8 times for Multiband Compressor also since they're also there.

**Comment by wwmm** [comment]
>Do not do it. You will have to do it 8 times for Multiband Compressor also since they're also there.

No necessarily. It will depend on how the multiband will be handled. I think that it is unavoidable to take the same approach as the one done to the equalizer bands. The 8 compressor bands will have to be handled by for loops both in the pipewire filter as in the compressor interface. Only in the schemas there is no way other than writing everything by hand.

**Comment by wwmm** [comment]
For now it is like this
![Screenshot from 2021-07-17 12-20-09](https://user-images.githubusercontent.com/16225172/126041571-0883fdd9-de4f-4f47-a9e0-5093a392e0bc.png)
Both controls are shown all the time. If people complain this is confusing because they aren't actually doing something all the time then I will bother with changing their `sensitive` property to reflect this.

**Comment by wwmm** [comment]
I decided to keep the original names. Replacing `amount` by `threshold` did not seem right after thinking a little about it.

**Comment by Digitalone1** [comment]
> Both controls are shown all the time. If people complain this is confusing because they aren't actually doing something all the time then I will bother with changing their `sensitive` property to reflect this.

Or that can be written in the documentation. Some time it will have to be updated...

**Comment by Digitalone1** [comment]
Solved.
