### ISSUE TITLE
can we use easy effect in voip programs such as google meet,discord,Teams etc....

### ISSUE THREAD

**Issue by 7549brijesh** [wwmm/easyeffects#1035]
I am searching for the AI powered noise suppression in linux there are very little and working like rnnoise,NoiseTorch,cadmus When I used Noisetorch it say my device is (?incompatible) I am finding cadmus a little complex now I am having a very little hope with easy effects

If there is any way to use easy effect in voip programs please let me know

**Comment by Mlocik97** [comment]
This should be in Discussions, not in issue...

To answer, yes, easyeffects is possible to use with any programs, voip included.

**Comment by 7549brijesh** [comment]
> This should be in Discussions, not in issue...
> 
> To answer, yes, easyeffects is possible to use with any programs, voip included. (I myself use it with Discord)

thanks for the reply I will repost in discussion
