### ISSUE TITLE
Cannot find help articles

### ISSUE THREAD

**Issue by jrpear** [wwmm/easyeffects#1044]
I remember there being some excellent help articles built into pulseeffects, but I recently looked for them and was unable to find them, although I see the source for them is still in the master tree under the `help` dir. I'm not sure if this was intentional or not.

I apologize if they're actually still in the app somewhere and I'm just daft.

**Comment by wwmm** [comment]
You can get to them by pressing the key `F1`. The reason why the help is "hidden" is that it needs a major update. And I am not sure when I will be able to do that

**Comment by jrpear** [comment]
Ah alright, makes sense.

Thanks for all the great work you've put into this program so far!

**Comment by wwmm** [comment]
We can close this issue.
