### ISSUE TITLE
Plugins "puzzle piece" icon not visible on KDE

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1050]
I had some issues with icons and text not displaying while testing the Flatpak on KDE.
The majority of these were solved for the Flatpak by installing `xdg-desktop-portal-gtk` on the host system.

However one issue seems to remain for both the Arch package and the Flatpak:

Arch package:
![image](https://user-images.githubusercontent.com/38842733/127287672-9877bc38-9b7a-4848-9abd-d3be98893ba5.png)

Flatpak:
![image](https://user-images.githubusercontent.com/38842733/127289361-32572426-fe23-4a81-a079-7f0b11355710.png)

The plugin "puzzle piece" icon isn't visible in the bottom center. This doesn't occur for me on GNOME:
![image](https://user-images.githubusercontent.com/38842733/127289710-dc670a3e-a8c3-48a6-a224-92f2a442271c.png)

Sidenote about theming in general:
Do you prefer the app to follow the Adwaita theme everywhere by default? Currently there doesn't seem to be much support for GTK 4 themes integrated in Flatpak yet, so by default on KDE the Flatpak will look as shown.

However, by workarounding with `sudo flatpak override --filesystem=~/.themes` all Flatpaks are given access to the system themes, so the [Flatpak looks identical to the Arch package](https://user-images.githubusercontent.com/38842733/127287795-141e53d7-85b5-4a51-975b-97d796a89cd4.png). This particular puzzle piece icon issue occurs either way though.

Edit: somehow I took all these screenshots without realizing there's a black bar where actual info should be. I guess that's a bug too. I'll try to figure that out later. Edit: that's just because I haven't started playing audio yet.

**Comment by polygonalenippel** [comment]
Quickly hijacking this thread: now that you mention it I noticed this icon bug in KDE as well:
![image](https://user-images.githubusercontent.com/29197220/127388475-5de8108d-0d91-4eaa-ac8a-d0798bd514a4.png)
Looks like opacity is lacking in bottom right corner.

**Comment by vchernin** [comment]
> Quickly hijacking this thread: now that you mention it I noticed this icon bug in KDE as well:
> 
> ![image](https://user-images.githubusercontent.com/29197220/127388475-5de8108d-0d91-4eaa-ac8a-d0798bd514a4.png)
> 
> Looks like opacity is lacking in bottom right corner.

See https://github.com/wwmm/easyeffects/issues/867

**Comment by wwmm** [comment]
>Do you prefer the app to follow the Adwaita theme everywhere by default?

I do not know how to handle this situation. When I started this project I thought that there was a standard icon themes followed for icon names. But that is clearly not the case. Maybe the only way to fix this kind of problem is to embed the icons in our executable like I did in the past for custom icons.

**Comment by vchernin** [comment]
> I do not know how to handle this situation. When I started this project I thought that there was a standard icon themes followed for icon names. But that is clearly not the case. Maybe the only way to fix this kind of problem is to embed the icons in our executable like I did in the past for custom icons.

So these are all "standard icons" then, and not explictly bundled? I'm not an expert, but I can see why that assumption would cause issues if icons aren't guaranteed to be available on the host.

To add to the confusion, the Flatpaks theming wildly changes based off of the presence of `xdg-desktop-portal-gtk` on the host. For the most part I don't think this is EasyEffects' responsibility though, it's just a note on theming in general.

On KDE:
Without:
![Flatpak without portal-gtk](https://user-images.githubusercontent.com/38842733/127601126-f7a5f3ad-fd34-44e2-855a-f13b3994fcf5.png)

With:
![Flatpak but with portal-gtk installed](https://user-images.githubusercontent.com/38842733/127601118-1a142c95-1304-4d02-b844-823b47d28c31.png)

There are some issues that are fixed with the x-d-p-g's inclusion, and some things that aren't fixed. Also some things, like the hamburger menu get a worse icon than on GNOME, and the close button looks out of place as well. You can enable the Breeze theme for it but [then it doesn't look perfect either](https://user-images.githubusercontent.com/38842733/127601811-d3c3e3b6-91f6-49fd-acd3-8369e0ca36cb.png), and then the included dark theme button doesn't work.

I feel like GTK4 in general on KDE needs some work, what EasyEffects should do I'm not sure.

**Comment by wwmm** [comment]
>So these are all "standard icons" then, and not explictly bundled?

Yes. We just tell gtk the name of the icon. It then searches for the icon in the system path. I can also embed the icons in the executable and tell gtk to search in this place too. It will require more steps but it is probably the only solution that will be reliable for people without the adwaita theme.

**Comment by Digitalone1** [comment]
This is with Breeze icon theme. PR is coming.

![Schermata del 2021-09-08 15-45-32](https://user-images.githubusercontent.com/25790525/132521479-c79cc9a9-6fa0-4dcb-afc4-ba060a1a4169.png)
