### ISSUE TITLE
Easyeffects bug: inactive EQ bands

### ISSUE THREAD

**Issue by DanMan** [wwmm/easyeffects#1055]
Example: If you decrease the bands from 32 to 10, and then raise them to 16 again, the 6 highest bands will be disabled. You have to restart the program for all sliders to become enabled.

**Comment by wwmm** [comment]
The sliders are enabled again once the band type is set to something that is different from `off`. When we hide a band by reducing the number of bands we set the band to off so it does not do any kind of processing the user is not aware of. What is happening isn't a bug in the usual sense. The the band type is being set to Off when adding more. Maybe `Bell` is a better default in this case.

**Comment by wwmm** [comment]
I updated the master branch now chaging the default type. If you are on Arch Linux you can test it with the AUR package

**Comment by DanMan** [comment]
Alright, not a bug but really confusing behaviour, if I may say so. Cheers.
