### ISSUE TITLE
Output of "pulseeffects -b 3" is sent to stderr

### ISSUE THREAD

**Issue by have-a-boy** [wwmm/easyeffects#1057]
Am I making this up or is the output of `pulseeffects -b 3` sent to stderr? If that is actually the case, what is the reasoning behind this instead of just sending it to stdout? It seems weird from a user perspective, since this is the intended effect of `-b 3`.

I was trying to make a very simple bash script to toggle global bypass, but couldn't figure out why it wasn't possible to pipe the output to other commands.

**Comment by wwmm** [comment]
Could it be because I used `std::clog` https://github.com/wwmm/easyeffects/blob/13b0ab00657f2e369920a4bdbe6b71ce17aa74ba/src/application.cpp#L338 ? Honestly I do not remember why I used it. But at least on my computer the output is printed as usual
```
wallace@wwmm ~/myfiles/code/cpp/easyeffects/_build/src $ easyeffects -b 3
0
```
Or do things happen differently when parsing this output in a script?

**Comment by X-m7** [comment]
In the terminal stderr is also printed just like stdout, however if stderr is redirected elsewhere then there is no output. In scripts only stdout is used normally, so I had to redirect stderr to stdout (so like `easyeffects -b 3 2>&1`). Here's what it looks like for me at the moment with EasyEffects 6.2.3:

```
➜  ~ easyeffects -b 3

(easyeffects:69102): GLib-GIO-CRITICAL **: 11:57:01.040: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed

(easyeffects:69102): GLib-CRITICAL **: 11:57:01.040: g_variant_get_type: assertion 'value != NULL' failed

(easyeffects:69102): GLib-CRITICAL **: 11:57:01.040: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(easyeffects:69102): GLib-CRITICAL **: 11:57:01.040: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(easyeffects:69102): GLib-CRITICAL **: 11:57:01.040: g_variant_unref: assertion 'value != NULL' failed
0
➜  ~ easyeffects -b 3 2>err.txt
➜  ~ cat err.txt

(easyeffects:69113): GLib-GIO-CRITICAL **: 11:57:18.911: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed

(easyeffects:69113): GLib-CRITICAL **: 11:57:18.911: g_variant_get_type: assertion 'value != NULL' failed

(easyeffects:69113): GLib-CRITICAL **: 11:57:18.911: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(easyeffects:69113): GLib-CRITICAL **: 11:57:18.911: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(easyeffects:69113): GLib-CRITICAL **: 11:57:18.911: g_variant_unref: assertion 'value != NULL' failed
0
```

**Comment by X-m7** [comment]
Forgot to mention that the output of `easyeffects -b 3` now works with my bypass toggle shell script using the master branch without having to redirect stderr to stdout or any other tricks, so I think this issue can be closed now, thanks for the fix!
