### ISSUE TITLE
Executing pulseaudio-legacy branch dies with error

### ISSUE THREAD

**Issue by addeps3** [wwmm/easyeffects#1061]
Hi. I have compiled this branch with these instructions: 
https://github.com/wwmm/easyeffects/tree/pulseaudio-legacy

```
cd easyeffects-pulseaudio-legacy
mkdir /tmp/pe
meson _build --prefix=/tmp/pe
cd _build
ninja install
```
Everything compiles fine, but when running `./_build/src/pulseeffects` it crashes with: 

```
./pulseeffects

(pulseeffects:65235): GLib-GIO-ERROR **: 16:49:45.562: Settings schema 'com.github.wwmm.pulseeffects.sinkinputs' does not contain a key named 'buffer-pulsesrc'
Trace/breakpoint trap (core dumped)

```

**Comment by wwmm** [comment]
When running from a custom path you have to tell gsettings where our schema is. Inside the source code folder compile our schema `glib-compile-schemas data/schemas/`. It is not necessary to run this every time you launch pulseeffects. Only when the keys define in our gsettings database changes. What is not going to happen to the legacy branch. After that the easiest thing to do is
```
cd _build
cd src
source ../../util/environmental_variables.sh
./pulseeffects
```
`environmental_variables.sh` will set the gsettigns database path

**Comment by addeps3** [comment]
Been away, back now. 

Just tried this hack but am having no joy =/  

`./pulseeffects 
(process:3132): pulseeffects-DEBUG: 16:59:33.924: main: locale directory: /tmp/pe/share/locale
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/input
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/output
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.938: presets_manager: user presets directory already exists: /home/adam/.config/PulseEffects/autoload
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.964: application: PE version: 4.8.5
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.964: pulse_manager: context is connecting
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.964: pulse_manager: context is authorizing
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: context is setting name
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: context is ready
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: protocol version: 34
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: Pulseaudio version: 14.2-rebootstrapped
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: default pulseaudio source: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.965: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.981: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:3132): pulseeffects-DEBUG: 16:59:33.981: sie: using output device: alsa_output.pci-0000_00_1b.0.analog-stereo

(pulseeffects:3132): GLib-GIO-ERROR **: 16:59:33.981: Settings schema 'com.github.wwmm.pulseeffects.sinkinputs' does not contain a key named 'buffer-pulsesrc'
Trace/breakpoint trap (core dumped)
`

`dnf` lists all pipewire/pipewire-pulseaudio packages as not installed, and pulseaudio as installed.

**Comment by addeps3** [comment]
Recompiled, and it's working
