### ISSUE TITLE
Calf and MDA plugins not working

### ISSUE THREAD

**Issue by SilentVOEZ** [wwmm/easyeffects#1067]
Hello,

After doing a fresh install of Arch Linux into my system and installing easyeffects (making sure the dependencies are also installed), it seems that some plugins does not work (Bass Enhancer and Limiter). It only affects some which is again Calf and MDA.

I have the logs for easyeffects below and it shows something about "cannot open shared object file". I checked the path of this "library" and it exist on the system. But I don't know what's happening to this. I also have this [pw-dump.txt](https://github.com/wwmm/easyeffects/files/6923169/pw-dump.txt) just in case.

**My system**

- OS: Arch Linux
- Kernel: 5.13.6-arch1-1
- DE: GNOME 40.3.0
- Plugins I use: Equalizer, Bass Enhancer, Limiter

<details>
<summary> easyeffects </summary>

```
(easyeffects:4565): easyeffects-WARNING **: 17:40:25.660: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.660: soe: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.660: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.660: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.660: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.858: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.858: sie: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.858: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.858: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.858: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
lilv_lib_open(): error: Failed to open library /usr/lib/lv2/calf.lv2/calf.so (libfluidsynth.so.3: cannot open shared object file: No such file or directory)

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.863: lv2_wrapper: failed to instantiate http://calf.sourceforge.net/plugins/BassEnhancer
lilv_lib_open(): error: Failed to open library /usr/lib/lv2/calf.lv2/calf.so (libfluidsynth.so.3: cannot open shared object file: No such file or directory)

(easyeffects:4565): easyeffects-WARNING **: 17:40:25.864: lv2_wrapper: failed to instantiate http://calf.sourceforge.net/plugins/Limiter
```

</details>

**Comment by wwmm** [comment]
Strange. I also use Arch and I do not have these errors. Is the package `fluidsynth` installed? Calf has it as dependency. The MDA plugins are in the package `mda.lv2`

**Comment by wwmm** [comment]
>I checked the path of this "library" and it exist on the system.

So it is installed. That is weird...

**Comment by SilentVOEZ** [comment]
> Strange. I also use Arch and I do not have these errors. Is the package `fluidsynth` installed? Calf has it as dependency.

Oh, that fixed the Calf plugins. No wonder my pacman didn't installed for some reason. I also saw on the Arch Linux package website that it depends on `fluidsynth` too.

> The MDA plugins are in the package `mda.lv2`

This is something I didn't saw on easyeffect's dependencies on the Arch Linux package website. And it also fixed MDA plugins too.

Thank you for the replies. I'm closing this now.
