### ISSUE TITLE
Crystalizer extreme clipping (v6)

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [wwmm/easyeffects#1076]
Crystalizer in v6 sounds significantly different than v5. I've captured multiple samples from output monitor:

[Audacity screenshot (labeled)](https://user-images.githubusercontent.com/46577212/128618772-f3e40912-0d56-4182-bc14-cc95d797327f.png)  (1.5M pic)
[v5 settings](https://user-images.githubusercontent.com/46577212/128618781-62f0bd59-e51f-4e9c-aa47-9208a3f2c748.png)  
[v6 settings](https://user-images.githubusercontent.com/46577212/128618785-8634c7d5-0321-47da-a4b5-e48206ff599c.png)  

I've tried to set most neutral settings for this test, they're not exactly no-op, but still

**Comment by wwmm** [comment]
I will check if there is something unusual in the code. But from my personal experience so far the output gain slider can be used to decrease the level and avoid the clipping. I usually keep mine at `- 5 dB` but that value has to be customized depending on the input level of the signal you being sent to the plugin input as well as on how the crystalizer sliders are configured.

**Comment by AbsurdlySuspicious** [comment]
I've managed to get rid of clipping by tuning output gain, but it still sounds flawed, I can't really describe it, but difference is visible on spectrogram. Also v5 crystalizer never significantly amplified the signal no matter what settings you set (given that gain sliders are set to zero), and v6 does it to the point of clipping right off the bat, it certainly seems strange

[Audacity](https://user-images.githubusercontent.com/46577212/128622589-5cfc0a5d-37ae-4ae0-832b-49b084f03048.png) (top - v5, bottom - v6, both are stereo contrary to the first screenshot)  
[v5 settings](https://user-images.githubusercontent.com/46577212/128622696-0a9f7dad-a597-4abd-9f5b-e039761d36c1.png)  
[v6 settings](https://user-images.githubusercontent.com/46577212/128622706-286e524d-c436-44d8-9c70-0ab0cdf395bc.png) (same, but with -7 output gain)

**Comment by wwmm** [comment]
Something is broken in the band splitting. It is almost like all the bands are acting on the same frequencies. I will investigate. When moving away from the Boost library I had to do some changes in the bands filters. Something clearly went wrong in this process.

**Comment by wwmm** [comment]
I have updated the master branch with some changes to how each frequency band is split. The signal level seems more reasonable now. I still have the feeling that the frequency separation could be better. I am not sure how yet. Splitting frequencies in bands and regrouping them after is tough.

If you are on Arch Linux try to test the new code through the AUR package.

**Comment by wwmm** [comment]
I have been using the plugin for some time and so far the extreme clipping seems to be fixed. I will close this issue.

**Comment by AbsurdlySuspicious** [comment]
Sorry for delay. Yeah, latest master sounds extremely close to v5 crystalizer and amplification issues are all gone. Thanks
