### ISSUE TITLE
Left channel stops working when easyeffects is running

### ISSUE THREAD

**Issue by DaLukasDev** [wwmm/easyeffects#1077]
When I start easyeffects or have it running, only my right channel of my headset is working.
I have a "logitech g pro x wireless lightspeed gaming headset" if that maters.
Using latest version on a fresh Arch install.
If I completely close easyeffects my left channel works as it should do.
Any idea what's causing this behavior?

**Comment by wwmm** [comment]
It seems the same problem as #1024

**Comment by DaLukasTI** [comment]
I went over that issue and build straight from the master, my issue still persists.
I didn't even enable any plugins, however enabling doesn't fix the issue.
I'm using GNOME and the others were having problems with KDE.
I did check the debug logs and saw nothing weird there.

Dumps if useful:

[pw-dot](https://pastebin.com/9HJvcpqq)
[pw-dump](https://pastebin.com/HREzZbG7)

**Comment by Digitalone1** [comment]
Pipewire has to keep the link alive and, if the link can't be established, it has to tell us something went wrong. If these things don't happen, we are going to have always troubles.

**Comment by DaLukasTI** [comment]
However when I'am not using easyeffects my stereo works fine, do you think its rather Pipewire related than Easyeffects related?

**Comment by wwmm** [comment]
@DaLukasTI I see in your pw-dot that you are using Gnome Settings to configure your audio. Although it may not be the source of your problem this program is known for breaking custom audio routing and GNOME developers decided to just ignore the issue. So I really recommend you use something else like Pavucontrol to set default devices. 

The master branch was updated with more log messages that may help to find out why you still have this problem. Please recompile your AUR package.

**Comment by wwmm** [comment]
>do you think its rather Pipewire related than Easyeffects related?

Although it is possible I think there may be still issues on our side like. At least the one I explained in the issue I linked is fixed.

**Comment by wwmm** [comment]
The pw-dump file is not available. It would also be good to see EE logs. Kill the current instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`

**Comment by wwmm** [comment]
Master branch updated again with more changes that may help to fix this issue.

**Comment by DaLukasTI** [comment]
Okay I'll try all that and report back!

**Comment by DaLukasTI** [comment]
I pulled changes from master and rebuild install. 
Here are up to date logs with the new build
[EE-LOG](https://pastebin.com/rnMUJ20D)
[PW-DUMP](https://pastebin.com/rWUFAnhJ)
[PW-DOT](https://pastebin.com/qa51YED7)

**Comment by wwmm** [comment]
No messages like `link from node ** to node ** failed` in our logs... The check I added before was not as useful as I was hoping...

**Comment by wwmm** [comment]
Are you sure there is still a problem? pw-dot output shows that the links are there
![Screenshot from 2021-08-08 17-44-05](https://user-images.githubusercontent.com/16225172/128645212-eaaded5e-ceb3-4c65-9908-01ba4268a0e4.png)
Pavucontrol makes the image a little harder to understand because of its probes. But the links from the `WebRTC` app to our virtual device are there. As well as the links from our virtual device to the spectrum and output level filters down to your sound card. Which plugin did you try to add to the plugins list?

**Comment by wwmm** [comment]
Could it be that Something muted the left channel of our virtual device? Recently a user had a problem like this. After making Pavucontrol show volume per channel he saw that this happened. The reason why was not clear.

**Comment by Digitalone1** [comment]
Maybe it's the plasma-pa widget muting one only channel.

**Comment by wwmm** [comment]
>Maybe it's the plasma-pa widget muting one only channel.

In this case the desktop is GNOME.

**Comment by lasnevadas** [comment]
i had this on Gnome last night with bluetooth earbuds, not left channel but right channel and not muted but very low. 
had to go to Gnome Settings, and move the balance slider to the other side, and then back to center, it was fixed doing that.

Alas last night was the last time the bluetooth buds worked with the Easyeffects sink. now it simply refuses to play anything BUT the system sounds over the headphones.  (switching the sound source to the bluetooth buds via pavucontrol make the sound play on them but obviously that bypasses easyeffects)

**Comment by wwmm** [comment]
>i had this on Gnome last night with bluetooth earbuds, not left channel but right channel and not muted but very low.
had to go to Gnome Settings, and move the balance slider to the other side, and then back to center, it was fixed doing that.

This could be a bug in PipeWire when saving volumes. We do not even try to set this kind of thing on our devices.

For the other problem it may be good to open a new issue attaching logs. Take a look at the messages in this issue. The usual steps to get logs are already described here.

**Comment by lasnevadas** [comment]
> For the other problem it may be good to open a new issue attaching logs. Take a look at the messages in this issue. The usual steps to get logs are already described here.

i believe its pipewire not playing nice with my headphones. as i have issues even without EasyEffects installed.

  I have rolled back to legacy and pulse for the moment, because of this, and well, theres the thing with the all-white skin Easy now has which clashes with my dark theme (theres a Dark Theme toggle but strangely does nothing).  and the equalizer maxing out my CPU. which doesnt happen on legacy PE

finally, and its purely subjective, but i believe the interface of legacy looks a lot better than the current Easy has.

**Comment by wwmm** [comment]
>theres a Dark Theme toggle but strangely does nothing

That switch only asks gtk to use the available dark theme. For that to actually do something on other desktop besides GNOME the corresponding theme integration for gtk4 has to be working.

>especially the latency diagram, that was something i always liked to see

This is something that is handled in a totally different way by PipeWire. A one to one mapping from that diagram was no possible so it was better to remove it.

**Comment by lasnevadas** [comment]
>That switch only asks gtk to use the available dark theme. For that to actually do something on other desktop besides GNOME the corresponding theme integration for gtk4 has to be working.

im on gnome 40 tho.

**Comment by wwmm** [comment]
Strange. This is what I get on Gnome 40
![Screenshot from 2021-08-12 00-12-27](https://user-images.githubusercontent.com/16225172/129132819-177f908b-fdb9-4b22-af44-3815cc910f84.png)
Personally I think it is too dark so I do not use it. But it works. All I did was to turn the switch on.

**Comment by wwmm** [comment]
This is a PipeWire bug that has taken different forms along the years. Keeping this issue opened is not going to help anymore. The discussion has to be done on PipeWire's page.
