### ISSUE TITLE
How to record the output of easyeffects

### ISSUE THREAD

**Issue by sfmth** [wwmm/easyeffects#1084]
`How` do I record the output of  easyeffects source in like audacity or arecord? It doesn't show up as a device
```
$ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pipewire
    PipeWire Sound Server
pulse
    PulseAudio Sound Server
speex
    Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
default
    Default ALSA Output (currently PipeWire Media Server)
sysdefault:CARD=PCH
    HDA Intel PCH, ALC236 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC236 Analog
    Front output / input
usbstream:CARD=PCH
    HDA Intel PCH
    USB Stream Output
'''
```

**Comment by wwmm** [comment]
>How do I record the output of easyeffects source in like audacity or arecord? It doesn't show up as a device

Do you mean recording from this device?
![Screenshot from 2021-08-10 14-52-14](https://user-images.githubusercontent.com/16225172/128910003-e22176eb-742d-458d-969c-da0bde0aa0b7.png)

**Comment by sfmth** [comment]
> If yes the problem is that these apps can only see ALSA devices. You will need to configure PipeWire or Pulseaudio in a way that they expose their devices to ALSA programs somehow. I never tried to do that.

Oh alright then, FFmpeg can easily capture PulseAudio devices.
