### ISSUE TITLE
Streams created with module-remap-sink are captured as well

### ISSUE THREAD

**Issue by SebiderSushi** [wwmm/easyeffects#1088]
For some use cases it can be useful to remap sinks using the `module-remap-sink`. When launching, pulseeffects captures all streams and routes them through itself. This captures remapped sinks as well and effectively destroys the user-set mappings.

**Comment by SebiderSushi** [comment]
sorry this refers to version 4.8.4 i assume this is vastly outdated now.

**Comment by wwmm** [comment]
No problems. This could happen in PipeWire too. It will depend on whether it creates these streams with the `media class` property set to `Stream/Output/Audio` or not. But if that is the case there is not much that can be done other than trying to blocklist these streams. You can try that in 4.8.4 too.

**Comment by SebiderSushi** [comment]
I am using PulseAudio.

Adding my remapped stream to the blocklist works thank you very much!
Does the `media class` property refer to PipeWire? Is it possible to automatically detect remap streams in PulseAudio? As far as i understand the concept, streams created by the `module-remap-sink` are all not meant to be consumed in a way like PulseEffects does but rather plugged into.

**Comment by wwmm** [comment]
>Does the media class property refer to PipeWire?

The property I talked about before is from PipeWire. I think Pulseaudio has a tag like that too. But the problem both in Pulseaudio and PipeWire is that ordinary audio apps set that property to the same value.

**Comment by SebiderSushi** [comment]
okay thank you.
