### ISSUE TITLE
Disabling Bass Enhancer while in "listen" mode has made PulseEffects 4.8.4 cease to play sound

### ISSUE THREAD

**Issue by Slapbox** [wwmm/easyeffects#1090]
I had been experimenting with Bass Enhancer and I clicked "Listen" to see what effect it had. I then decided I didn't need it, so I disabled Bass Enhancer. Unfortunately, now no sound comes out through PulseEffects. I've tried toggling the global toggle, restarting the app, toggling app bypasses on/off, toggling default audio devices, restoring a preset, using "reset" under Settings, and restarting the machine. I also tried fixing it via the same way I triggered it. Uninstall/reinstall didn't help either. 

Any advice? Thanks!

**Comment by Slapbox** [comment]
Disabling a specific app restores its audio, but the global toggle switch has no effect. 

I just found this app today and have been amazed. Now I'm lamenting going even a few hours without it. Thank you for the amazing work!

**Comment by Slapbox** [comment]
From looking through other issues, in case these help, though I'm not sure they matter for this version:

- `pw-dot`: No output
- [`pw-dump`](https://pastebin.com/5RTBf1w3)

OS: Kubuntu 21.04

**Comment by vchernin** [comment]
> From looking through other issues, in case these help, though I'm not sure they matter for this version:
> 
>     * `pw-dot`: No output
> 
>     * [`pw-dump`](https://pastebin.com/5RTBf1w3)
> 
> 
> OS: Kubuntu 21.04

Those logs are for PipeWire which aren't very relevant to PulseEffects (uses PulseAudio per the name).

EasyEffects is the succesor to PulseEffects, and only supports PipeWire. I'd suggest trying EasyEffects instead of PulseEffects as PulseEffects is under maintenance mode, and EasyEffects is more actively deveoped.

However, for EasyEffects you will likely need to install a newer version of PipeWire, you have 0.3.24 EasyEffects usually needs >0.3.31. [You may try this PPA out](https://pipewire-debian.github.io/pipewire-debian/), but please note it is not officially supported by Kubuntu. You would also need to find a package compatible with your distro, you could try the [hopefully officially released soon Flatpak](https://github.com/flathub/flathub/pull/2429).

**Comment by wwmm** [comment]
If you are on Pulseaudio I really recommend upgrading from 4.8.4 to `4.8.5`. On systems with `dconf 0.40` or higher 4.8.4 will be broken.

**Comment by Slapbox** [comment]
I looked and looked but couldn't find binaries for `4.8.5` version. Maybe I overlooked some obvious source.

BUT, using the Flatpak @vchernin linked I was able to get things working! Just for anyone else who might come across this, the PPA was indeed required, Pipewire 0.3.24 did nothing for me.

Thank you both very much. @wwmm this is amazing work!

**Comment by Slapbox** [comment]
Uh-oh. Signing off for the night, but it looks like the same issue has reappeared for me, even with EasyEffects. Nothing I did provoked it this time, but I am running an unsupported version of PipeWire, so...

Any advice is welcome though!

**Comment by Slapbox** [comment]
Good news! It turns out this time that, somehow, EasyEffects sink got muted. The problem with PulseEffects was somewhere outside of user control, but this time it was as simple as unmuting! Hooray!

**Comment by wwmm** [comment]
>Good news! It turns out this time that, somehow, EasyEffects sink got muted.

I think that the latest PipeWire update may have a bug in its volume restoration routine. You are not the only one reporting that our sink has been mysteriously muted. We do not even try to change its volume or mute state.

**Comment by Slapbox** [comment]
I'm not sure, but I'm thinking that in my case it was related to HDMI input being connected/disconnected using the <kbd>WinKey+P</kbd>.

**Comment by wwmm** [comment]
>I'm not sure, but I'm thinking that in my case it was related to HDMI input being connected/disconnected using the WinKey+P.

What sounds like a PipeWire issue. I have seen it muting or setting volumes to 100% when we connect or disconnect a device.

**Comment by wwmm** [comment]
It is a little random when this happens or not. But definitely a PipeWire issue.

**Comment by Slapbox** [comment]
Whatever the exact cause, definitely a PipeWire issue, I agree. If I see it happening more I'll try to figure out why and file a bug with them.

**Comment by vchernin** [comment]
> I looked and looked but couldn't find binaries for `4.8.5` version. Maybe I overlooked some obvious source.

It wasn't available then, but for the future the PulseEffects Flatpak should imminently (3-4 hours from writing) [have 4.8.5](https://github.com/flathub/com.github.wwmm.pulseeffects/pull/55).
