### ISSUE TITLE
Strange UI lagging 

### ISSUE THREAD

**Issue by mthqwork** [wwmm/easyeffects#1092]
Hi, 

I have a strange issue. Easyeffects UI response sometimes slow down to around 1-2 FPS. 
If I open pavucontrol (Volume Control), it works (with fast refresh rate) as long as i keep the volume control open.
When I close it, FPS/refresh will collapse.
Latest version of Easyeffects, from Arch repo.

See the video about it [here](https://www.youtube.com/watch?v=JIP4h1wmHvk)

**Comment by wwmm** [comment]
It is not a lag in the usual meaning of the word but it is still something that has to be improved. I just do not know how yet...

PipeWire adjusts its latency dynamically. What means that sometimes the audio buffer is big and we receive it less often. But when an audio app starts and requests a small latency the audio buffer gets small and we receive them more often. That is the reason why the update frequency of the spectrum and level meters changes. At this moment that frequency is tied to the frequency PipeWire sends buffers to us. And this changes with the current latency.

I did not have time yet to research the topic and see how people deal with this.

**Comment by mthqwork** [comment]
Thanks for clarifying it. It'd be great to improve this :)

**Comment by wwmm** [comment]
I have also made some changes to the spectrum plugin update rate. I think that now different sampling rates finally feel the same visually. But as the solution is a little tricky this has to be tested on other systems besides mine.

**Comment by mthqwork** [comment]
I went back to pulseaudio/legacy pulseeffects, but I'm ready to install pipewire to test it. :)

**Comment by wwmm** [comment]
I think it is as good as it can be considering the current limitations. Let's close this issue.
