### ISSUE TITLE
Removing and re-adding bands in the equalizer plugin leaves band disabled

### ISSUE THREAD

**Issue by gunslingerfry** [wwmm/easyeffects#1097]
Not sure this is a bug, close if this is intended behavior. 

When a band is removed and re-added, it keeps its frequency info but it is 'off' type. Either it should be entirely reset to empty or it should keep its type set.

**Comment by wwmm** [comment]
It will be fixed in the next release #1055. For now manually switch it to something like Bell or the desired mode.

**Comment by gunslingerfry** [comment]
Ah, sorry. Didn't see the other issue. Thanks!
