### ISSUE TITLE
No dark theme in easyeffects on openSUSE Tumbleweed.

### ISSUE THREAD

**Issue by genes1122** [wwmm/easyeffects#1106]
I'm using easyeffects version 6.0.3+0~git.35c27c34-2.1 from the openSUSE repos with pipewire.  When I switch to the dark theme, I still have the light theme.  I checked with dconf editor, and the value toggles in dconf, but the GUI theme doesn't change.  Is this a known issue, or is something wrong with the openSUSE build?  This used to work with earlier versions both with pulseaudio and with pipewire.

Thanks,

Gene

**Comment by vchernin** [comment]
Are you on GNOME or KDE (or something else)? I have noticed theming doesn't work great on KDE currently. I think dconf is a GNOME thing, but I wanted to make sure.

When you say earlier versions do you mean PulseEffects 4.x or 5.x? Those are both GTK 3 IIRC. Did the dark theme work in previous 6.0.x EasyEffects builds?

I haven't noticed this issue on Fedora 34 Silverblue (GNOME) with the [Flatpak build](https://github.com/flathub/flathub/pull/2429).

**Comment by genes1122** [comment]
I'm on MATE.  I ran 4.x with pulseaudio, then switched to 4.x from a user repo with pipewire.  When I found out easyeffects was in the openSUSE repo, I switched to 6.x.  The dark theme has never worked with 6.0.x EasyEffects.  I was unaware of the switch to GTK4.  Are there any GTK4 packages I should be checking on my Tumbleweed installation?

Gene

**Comment by wwmm** [comment]
>Are there any GTK4 packages I should be checking on my Tumbleweed installation?

I think the problem is at a lower level. For each desktop there are libraries doing the gtk theme integration. They probably were not updated for gtk4 yet.

**Comment by vchernin** [comment]
> I think the problem is at a lower level. For each desktop there are libraries doing the gtk theme integration. They probably were not updated for gtk4 yet.

Agreed this is most likely the the case. I looked for related gtk issues and couldn't find anything so it's probably a distro packaging issue.

Could you test the Flatpak build and see if dark mode works there on MATE? If Flatpak works but OpenSUSE's build doesn't I'd suggest reporting it to OpenSUSE's EasyEffects maintainer.

**Comment by wwmm** [comment]
>I looked for related gtk issues and couldn't find anything so it's probably a distro packaging issue.

I wonder who is responsible for this integration. Is gtk providing what is necessary for every desktop or do they let this task to the desktop developers? I have no idea.

**Comment by genes1122** [comment]
I noticed that the only installed gtk4 package on my system was gtk4-schema.  I've installed the gtk4 packages that matched my gtk3 packages, but no luck yet.  Is there a list of gtk4 packages required by easyeffects?

Thanks,
Gene

**Comment by vchernin** [comment]
I am really not sure honestly what packages are needed for full featured GTK4.

I'd suggest troubleshooting by trying other GTK4 apps with dark mode ([eg. Clapper](https://github.com/Rafostar/clapper#debian-fedora--opensuse)) or try EasyEffects Flatpak.

**Comment by wwmm** [comment]
>Is there a list of gtk4 packages required by easyeffects?

At least on Arch Linux only the package `gtk4` and the package with its C++ language wrapper `gtkmm-4.0`. Based on what I remember from the years I used KDE this integration is not done by gtk. The desktop is the one doing there. Assuming that is the case the question is if `MATE` has any integration for gtk4 in place.

**Comment by genes1122** [comment]
Thanks, I'll check out MATE and gtk4.

**Comment by genes1122** [comment]
Searching for gtk4 on the MATE web site returned zero results, but gtk3 returned a lot.  Aparently, MATE doesn't support gtk4 yet.  Does this mean that easyeffects may be unstable on MATE?  There is a user supported gtk3 pulseeffects package that works with pipewire.  I can switch back to it if necessary.

**Comment by vchernin** [comment]
Yes, you may have luck with PulseEffects 5.0.x as that uses PipeWire but not GTK4. I am still unsure whether there is anything the openSUSE packagers could do, or if the Flatpak would help.

EasyEffects shouldn't really be "unstable" on MATE, it makes sense things like theming or other integration might be broken but I don't see why the core app functionality would be affected by it. The audio stuff should still work I think.

**Comment by genes1122** [comment]
Thanks for the input.  It does appear to be working correctly, so for now, I'll just put up with the light theme.  I did open a bug against easyeffects from the openSUSE repos.  They're version recommends ladspa-zam-plugins, which don't load with easyeffects.  I removed the ladspa-zam-plugins and installed lv2-zam-plugins, and now everything seems to be working except for the dark theme.

Thanks again,
Gene

**Comment by vchernin** [comment]
> Thanks for the input. It does appear to be working correctly, so for now, I'll just put up with the light theme. I did open a bug against easyeffects from the openSUSE repos. They're version recommends ladspa-zam-plugins, which don't load with easyeffects. I removed the ladspa-zam-plugins and installed lv2-zam-plugins, and now everything seems to be working except for the dark theme.

Thanks for opening an openSUSE bug, could also you link it here for future readers?

**Comment by wwmm** [comment]
>Does this mean that easyeffects may be unstable on MATE?

No. The issue with the dark theme not work is of no concern for the rest of the application. It is possible that other problems may happen. A user on `sway` reported some things that do not happen in any of the other desktops as far as I know. But that was a corner case that I doubt would happen on MATE.

This dark theme activation corresponds to only one line of code on our side https://github.com/wwmm/easyeffects/blob/4f075fbc3946297316e45ccc18d26f76d22e1c78/src/application_ui.cpp#L75. We just ask gtk4 to use a dark theme. Maybe outside of gnome gtk4 is not being able to find the theme files. Honestly I can't understand why it even makes a difference being on other desktop. I think that gtk should make this just work. The Adwaita theme is the default gtk theme and it has a dark variant that is probably already installed in your computer. It should be using it like it does on GNOME. I wonder why it doesn't....

>They're version recommends ladspa-zam-plugins, which don't load with easyeffects. I removed the ladspa-zam-plugins and installed lv2-zam-plugins, and now everything seems to be working except for the dark theme.

Our older releases based on GStreamer needed the ZAMAUDIO package with its plugins built for ladspa. When I moved to native PipeWire filters I had to write my own wrapper for LV2 plugins. And in this wrapper I added supported for the host features the LV2 release of the ZAMAUDIO plugins needed and that GStreamer did not have. So now we use the LV2 format. The package maintainers probably did not notice that change.

**Comment by vchernin** [comment]
> So now we use the LV2 format. The package maintainers probably did not notice that change.

Ah, so there is no LADSPA support anymore in EasyEffects then? I guess I should remove it from the Flatpak.

**Comment by wwmm** [comment]
>Ah, so there is no LADSPA support anymore in EasyEffects then? I guess I should remove it from the Flatpak.
Or am I jumping ahead, and that's only for the ZamAudio plugin?

You can remove anything related to ladspa from the dependencies. Almost all of the plugins we use are in the LV2 format. And the few that aren't are plugins I have written myself using PipeWire filters.

**Comment by genes1122** [comment]
Here's the zam-plugin bug link:  https://bugzilla.opensuse.org/show_bug.cgi?id=1189542

**Comment by kevinlekiller** [comment]
Using OpenSuse here, I was already using the Adwaita-dark GTK theme, so maybe that's why easyeffects was already dark, all I did was install easyeffects:

https://i.imgur.com/69uEwH0.png

**Comment by genes1122** [comment]
Thanks!  All I had to do was switch from BlackMATE to Adwaita-dark and I got the dark theme!

Gene

**Comment by vchernin** [comment]
Most likely the BlackMate theme doesn't support GTK4 yet. If you'd like you could report it there.

**Comment by genes1122** [comment]
I did, https://github.com/mate-desktop/mate-desktop/issues/476

Gene

**Comment by genes1122** [comment]
Thanks for all the help, all is well now.
