### ISSUE TITLE
What to do with documentation? 

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1108]
With the new multiband compressor and limiter, there's a need to update the documentation. Besides, Markus guide for laptop should be adapted to the new plugins and there are other things to fix for other plugins. 

Anyway new updates should be also translated. Honestly, I'd like to update the main English one, but if I think I have also to translate the Italian one, I'm not motivated to do it.

Unfortunately the documentation is important, but also boring to deal with and the most boring part is the translation. Then, let's be honest, most of the available translations are partially completed and will never be completed. Therefore I suggest to remove translations and leave only the English one, kept 100% updated.

It's not only because I'm not motivated to translate it, but primarily because documentation is too important for this application and we should put all the effort in keeping it updated rather than working on translations which will never be 100% updated and partially translated ones are a big downside because they are more confusing to the user. Obviously this argument does not apply to user interface translation. 

Considering that plugin official documentations are only in English and in our documentation we refer to them, I recommend to keep the documentation really updated removing all the translations, so we have a unique place, same for all locales, easier for us to maintain and without misleading information.

What do you think?

**Comment by wwmm** [comment]
>Anyway new updates should be also translated. Honestly, I'd like to update the main English one, but if I think I have also to translate the Italian one, I'm not motivated to do it.

I have the same feeling about the pt_BR translations. I stopped doing them a long time ago. Even for the window labels...

>Unfortunately the documentation is important, but also boring to deal with and the most boring part is the translation.

I agree. It is really boring. Any free time I have available for this project always goes to the code.

>What do you think?

It is a hard decision to make. But I think we could remove the translations for the documentation and see how people react. Considering how rare is to receive pull requests updating the documentation translations(or the documentation) I think that most people won't even notice they were removed.

**Comment by servimo** [comment]
I could try to translate to "pt_BR" , but I will use a lot of Google Translate.

**Comment by servimo** [comment]
Some words translated to portuguese-BR looks strange when is about some things like: Gate,  Low-Pass, High-Shelf, Slope, Sidechain, Threshold, Knee, Default

**Comment by Digitalone1** [comment]
@wwmm do you plan to make a new release soon? I'm updating the documentation only in English and I think it will be ready in the next week.

It could be implemented in the next release.

**Comment by wwmm** [comment]
>do you plan to make a new release soon?

It does not have to be soon. So far we have only new features and changes for potential bugs that could happen in very specific situations. So the next release can wait for the documentation update.

**Comment by Digitalone1** [comment]
So the up to date documentation has been merged.

Some parameters are difficult to understand, but I reported the definition of the original Calf/LSP manual.

Anyway `Pitch Faster` option is completely missing. @wwmm do you have any clue what it is doing?

Then I found the definition for `Release Threshold` and `Sidechain Reactivity`, but I still didn't get them at all. I'd like to go on LSP issue page asking for a clarification.

It's weird that most of the compressors have the Threshold, but the LSP one name it as the Attack Threshold and the Release Threshold is relative, but it's not well explained and changing its value I don't see/hear any difference.

**Comment by wwmm** [comment]
There is an explanation for the `faster` option in the Rubberband source code https://github.com/breakfastquay/rubberband/blob/2472213d731527a2fadbc56c83a8490ed7e3d78d/rubberband/RubberBandStretcher.h#L261

The reactivity is something I never fully understood. The release threshold I imagine it is related to the signal level where the compressor will remove completely the attenuation. By relative they probably mean that the reference level is a certain amount below the level set in the attack threshold. But it is definitely better to ask sadko about this in LSP page.

**Comment by Digitalone1** [comment]
> Use a method with a CPU cost  that is relatively moderate and predictable.

Okay, it's a mode less CPU intensive. And I see it. With only the Pitch and the Limiter on my system, I get cracking sound at +2 octaves and even worse at +3.

Enabling Faster options goes smooth.

> This is the default.

But not for us. @wwmm Maybe we should make it the default as well? What do you think?

**Comment by wwmm** [comment]
>Maybe we should make it the default as well? What do you think?

I do not see any problem. In the past I favored quality over speed for the default because I did not have any performance issue. But I understand that the Ryzen 3700x isn't the kind of cpu most users will have.

**Comment by Digitalone1** [comment]
Oh, now I understand why that user complained about the poor quality of our Pitch, we never selected the `OptionPitchHigh`.

**Comment by wwmm** [comment]
I think we can close this.
