### ISSUE TITLE
Some issues in EasyEffects

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1110]
I'm working on the code doing some optimizations and discovered a few issues.

- [x] When an app is removed from the blocklist, it's previous state is not restored, so if I had it enabled, I have to enable the app manually. This was happening also in PulseEffects more than a year ago, then state restoration was implemented, but that has not been ported in EasyEffects.
- [x] When an app is removed from the blocklist, sometimes it's item in the list gets updated showing an ugly icon. To restore the correct icon the app has to be reenabled. This has to be worked around and I was also thinking to set the icon with opacity 0 as default and set it to 1 when a correct icon is available, so when an app does not have an icon, that ugly one is not showed.
- [x] When a rnnoise model is deleted from the list, the item on top of the list can't be selected. The only way to resolve this issue is to reset the plugin.
- [x] Adding an autoloading preset to a device already present in the list does not update the item of that device inside the list. The preset is correctly updated in the settings, but the change is not reflected in the UI and the item can't even be deleted.
- [x] Modifying a preset manually in a text editor causes the same preset to be showed multiple times in the preset list. 

I almost resolved the first issue that partially worked around on the second. Maybe I will be ready to make a merge request tomorrow.

**Comment by wwmm** [comment]
>Adding an autoloading preset to a device already present in the list does not update the item of that device inside the list. The preset is correctly updated in the settings, but the change is not reflected in the UI and the item can't even be deleted.

Maybe that part has to listen to a different signal from the filesystem monitor.

>When a rnnoise model is deleted from the list, the item on top of the list can't be selected. The only way to resolve this issue is to reset the plugin.

I could not reproduce that. Maybe the position of the deleted item is relevant to trigger the problem.

>When an app is removed from the blocklist, sometimes it's item in the list gets updated showing an ugly icon. To restore the correct icon the app has to be reenabled. This has to be worked around and I was also thinking to set the icon with opacity 0 as default and set it to 1 when a correct icon is available, so when an app does not have an icon, that ugly one is not showed.

At least with mpv I did not see that yet. I removed and added it to the blocklist a few times but the icons was always the same. But that is probably dependent on how often the app makes PipeWire to send us state changed signals.

**Comment by Digitalone1** [comment]
> I could not reproduce that. Maybe the position of the deleted item is relevant to trigger the problem.

How many items do you have in the list? It happens to me with two items. Select the first on top, delete it, then the remaining standard can't be selected.

If you have three items, select the first, delete it, the one on top can't be selected, but if I select the second, then I can select the first.

> At least with mpv I did not see that yet. I removed and added it to the blocklist a few times but the icons was always the same. But that is probably dependent on how often the app makes PipeWire to send us state changed signals.

It happens to me at the first try with Celuloid. Just add the enabled app to the blocklist, then remove it from the blocklist, it remains disabled and the icon disappear:

![Schermata del 2021-08-21 09-33-29](https://user-images.githubusercontent.com/25790525/130314515-d1a1fb59-c244-4f0c-9f31-54342c8af562.png)

I forgot to report another issue. Added to the tasks.

**Comment by vchernin** [comment]
> This has to be worked around and I was also thinking to set the icon with opacity 0 as default and set it to 1 when a correct icon is available, so when an app does not have an icon, that ugly one is not showed.

This sounds like it would also workaround https://github.com/wwmm/easyeffects/issues/1047

**Comment by Digitalone1** [comment]
> This sounds like it would also workaround #1047

Do you know the name of that icon? If I knew it, I could add a check to not show it.

Or I could add a debug message reporting the icon name so you can run the compiled master branch and take not of its name.

**Comment by vchernin** [comment]
> Do you know the name of that icon? If I knew it, I could add a check to not show it.
> 
> Or I could add a debug message reporting the icon name so you can run the compiled master branch and take not of its name.

For #1047 there's no singular icon name I can point to. The issue is that EasyEffects cannot find the icon of other  applications installed as Flatpak. Both the Flatpak and Arch build of EasyEffects experience this. The solution seems to be to teach EasyEffects where Flatpak puts other application's icons. It doesn't make sense to add specific checks here since any audio playing Flatpak app will experience this--and there's a lot of those.

However, https://github.com/wwmm/easyeffects/issues/1050 might be good for a specific check, it's only one icon that's broken here.

**Comment by vchernin** [comment]
> Or I could add a debug message reporting the icon name so you can run the compiled master branch and take not of its name.

Also I think here one can just use GTK's debugger and "inspect" the icon to find its properties, including its name.

**Comment by Digitalone1** [comment]
If I'm not wrong, Flatpak apps have special names, so maybe those names won't help in finding the icon under `/usr/share/icon` path. I don't know if it's a good idea telling the app where the icons are located. That should be a task left to GTK.

If Flatpak apps have names different than native apps, can you tell me how they are composed?

**Comment by Digitalone1** [comment]
This is what is used: https://docs.gtk.org/gtk4/method.Image.set_from_icon_name.html

```
Sets a GtkImage to show a named icon.
```

The problem is if Pipewire is providing a name not included in the icon theme, the icon is not showed.

**Comment by Digitalone1** [comment]
@wwmm another case the app icon is not showing.

Start an app, blocklist it and deselect "show blocklisted apps". Close the app, restart it and select "show blocklisted apps". The icon is not showing. Removing from the blocklist and enabling the app will show the icon correctly.

It's weird because through debug util I see the icon name is correctly provided, but it's now showing. Anyway I see that connection_info lambda function is invoked several times on enable switch while on show blocklisted apps only one time.

**Comment by wwmm** [comment]
>How many items do you have in the list? It happens to me with two items. Select the first on top, delete it, then the remaining standard can't be selected.
>If you have three items, select the first, delete it, the one on top can't be selected, but if I select the second, then I can select the first.

With only one item besides the standard entry in the list what happened after deleting the entry was an automatic selection of the standard model entry. Same thing when there was only 2 imported models besides the standard. After deleting the first entry while it was selected the second entry was automatically selected. Somehow I could not trigger the problem.

**Comment by Digitalone1** [comment]
> > How many items do you have in the list? It happens to me with two items. Select the first on top, delete it, then the remaining standard can't be selected.
> > If you have three items, select the first, delete it, the one on top can't be selected, but if I select the second, then I can select the first.
> 
> With only one item besides the standard entry in the list what happened after deleting the entry was an automatic selection of the standard model entry. Same thing when there was only 2 imported models besides the standard. After deleting the first entry while it was selected the second entry was automatically selected. Somehow I could not trigger the problem.

That's weird. I'll try to investigate.

**Comment by wwmm** [comment]
I think that now I see the problem. The entry is selected in the list but the name of the active model displayed in the label below is not being updated. Sounds like we may have to listen to another signal.

**Comment by wwmm** [comment]
For some reason gtk does not seem to call `listview->get_model()->signal_selection_changed()` in this situation. I wonder why.

**Comment by Digitalone1** [comment]
> For some reason gtk does not seem to call `listview->get_model()->signal_selection_changed()` in this situation. I wonder why.

Because I think it's not selected by the user, maybe it should be called manually after the deletion.

**Comment by wwmm** [comment]
>Because I think it's not selected by the user

It seems so but gtk docs only say `Emitted when the selection state of some of the items in model changes`. And that is happening.

**Comment by Digitalone1** [comment]
Unfortunately the documentation is not always clear.

And when adding a file to the list, I would add a check if the item is already present in the list because when the preset is changed manually with a text editor, it's added multiple times in the preset list.

**Comment by wwmm** [comment]
>maybe it should be called manually after the deletion.

I will do that now and see what happens.

**Comment by wwmm** [comment]
That workaround seems to have fixed the listview issue in the rnnoise ui. Master branch updated.

**Comment by wwmm** [comment]
>And when adding a file to the list, I would add a check if the item is already present in the list because when the preset is changed manually with a text editor, it's added multiple times in the preset list.

For reasons I do not understand `Gio::FileMonitor::Event::CREATED` is triggered by file changes too instead of only creation...

**Comment by wwmm** [comment]
Maybe the text editor destroys and recreates the file when saving it. I will see what is easier. Listening to another signal or checking if the name is already there.

**Comment by Digitalone1** [comment]
Checking the name already present should be safer.

**Comment by wwmm** [comment]
>Checking the name already present should be safer.

Although there are other signals that could be interesting in some situations none of them will do what we need while being triggered only when a file is actually being created. So checking will be the only option. I will do some tests here on my computer.

**Comment by wwmm** [comment]
Master branch updated again. The duplicated entries issue should be fixed.

**Comment by wwmm** [comment]
New update to the master branch fixing the issue about the autoloading profiles.

**Comment by vchernin** [comment]
> If I'm not wrong, Flatpak apps have special names, so maybe those names won't help in finding the icon under `/usr/share/icon` path. I don't know if it's a good idea telling the app where the icons are located. That should be a task left to GTK.

I agree it should be a task left to GTK, it is definitely a bit odd it's happening even on GTK4. There is some more info and links about Flatpak's directories in https://github.com/wwmm/easyeffects/issues/1047#issuecomment-887742273, it can be a bit confusing though...

> If Flatpak apps have names different than native apps, can you tell me how they are composed?

For example, EasyEffects' Flatpak app ID is: `com.github.wwmm.easyeffects`. It's reverse-DNS style, and is pretty much mandatory for Flatpak apps.

As far as I could tell EasyEffects finds the correct app ID for other apps, but it just doesn't know where the icon is. Which as above, is strange.

**Comment by Digitalone1** [comment]
> For example, EasyEffects' Flatpak app ID is: `com.github.wwmm.easyeffects`. It's reverse-DNS style, and is pretty much mandatory for Flatpak apps.
> 
> As far as I could tell EasyEffects finds the correct app ID for other apps, but it just doesn't know where the icon is. Which as above, is strange.

Which is your icon theme and are you sure you have an icon named `com.github.wwmm.easyeffects` on your system?

I have [kora icon theme](https://github.com/bikass/kora) and that icon is installed in [/usr/share/icons/kora/apps/scalable/com.github.wwmm.easyeffects.svg](https://github.com/bikass/kora/blob/master/kora/apps/scalable/com.github.wwmm.easyeffects.svg). I can't test with Flatpak, but you can try to install kora and see if it's showing.

**Comment by vchernin** [comment]
> Which is your icon theme and are you sure you have an icon named com.github.wwmm.easyeffects on your system?

The issue isn't with EasyEffects' icon, but other apps who play audio and therefore show up in EasyEffects. I just gave an example using EasyEffects' app ID name. Another example is `io.mpv.Mpv` for the `mpv` media player, or `org.chromium.Chromium` for `chromium`. Both of those won't show their icon in EasyEffects properly.

For reference I use the default GNOME Adwaita theme on Fedora 34/35.

**Comment by Digitalone1** [comment]
Adwaita doesn't have those two icons. Kora has them both. I think you can resolve installing an icon them with lots of app icons bundled. Try kora.

**Comment by vchernin** [comment]
> Try kora and enable it as default icon theme.

Thanks, I'll try that later if #1047 can't be solved otherwise.

**Comment by Digitalone1** [comment]
Finally I found out why the icon is not updating under certain situations.

When state is `PW_NODE_STATE_CREATING` Pipewire provides in NodeInfo an empty string in `app_icon_name`, `media_icon_name` and `i.name`, but for reasons that I don't know, the `empty()` check on them does not work and they are set anyway giving us an ugly icon. Maybe because those empty strings are not really empty containing some space character.

This is the screenshot of the test updating only the state:

![Schermata del 2021-08-31 17-45-01](https://user-images.githubusercontent.com/25790525/131535500-d5cd4578-f21d-4df8-adfd-1e1937bcc938.png)

In PHP I would use trim() to let empty() work, but I think it's better and faster in this case to skip only the icon update on that specific state. It's resolved, can be closed. The fix will be part of the next MR.
