### ISSUE TITLE
Arch Linux KDE Multiple Monitor Strange Issue

### ISSUE THREAD

**Issue by Onur-Cansever** [wwmm/easyeffects#1112]
1. Arch Linux KDE Desktop Environment(plasma 5.22.4)
2. I installed easyeffects from arch linux community pacman repo.
3.  G_MESSAGES_DEBUG=easyeffects easyeffects  command's output: https://pastebin.com/3NY8YYz0
4. pw-dump output: https://pastebin.com/tdERkyjZ

    Firstly i have to say that program is working well, and i have obstacle from my ears that means i have to use mono sound and thanks to you very much i can do it your program easily just a few clicks.

    I opened "Start service at login." option from top right settings button, then i  am reopening my machine. Here's is the problem: I have a dual monitor system setup. In my main monitor i cannot add new plugin,  i cannot go into settings menu. Settings menu button and add plugin button are not working. In my second monitor i can press all buttons in program, there is no any problem. Is it KDE issue or maybe program issue ? Have a nice day.

**Comment by wwmm** [comment]
>Is it KDE issue or maybe program issue ? 

Considering that the menus are the ones not working as intended my first impression is this a GTK4 bug. There isn't really much done in the application side. Multiple monitors are handled by the graphical toolkit (GTK4) and the desktop (KDE4). Somewhere along the way it seems there is an incompatibility between them.

**Comment by Onur-Cansever** [comment]
Okay thank you very much. I just wanted to report it just in case.
