### ISSUE TITLE
Easier per device EQing?

### ISSUE THREAD

**Issue by Netherquark** [wwmm/easyeffects#1119]
Hey. I must admit, EasyEffects' UI is one of the reasons I love it. Its SO much more intuitive than say, EqualiserAPO. But one thing I found missing, which would fit in well, was proper per device presetting. Like, at the moment, you can set a preset to load whenever you connect a device, or set it as the default audio out, but I was thinking something like this would be awesome:

![image](https://user-images.githubusercontent.com/65618735/131127933-9acbe5e2-3d05-49d9-9782-eff3668af430.png)

What I mean is, device exclusive profiles which can easily be managed. Excuse my shoddy "concept art" I'm not really the artistic type. But I hope you get my point.

**Comment by wwmm** [comment]
I am not sure about the advantages. Unless I misunderstood something the idea is filtering presets based on the device. But as the presets menu already has a built-in search this can be done by adding the device name to the preset name. As you seem to be already doing. I understand that there is some manual management involved in this approach. But it does not seem we have room in our interface to dedicate to this kind of alternative grouping you are thinking about.

**Comment by Netherquark** [comment]
okay then
