### ISSUE TITLE
Migrating PulseEffects (5.x PipeWire) users to EasyEffects

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1120]
Now that EasyEffects is released and is available in package formats that reach most distros, I wonder if users using PulseEffects (5.x PipeWire branch) should be thoughtfully migrated to EasyEffects.

Are there users who will want to use the PulseEffects 5.x PipeWire branch over EasyEffects? I'm sure there are minor things that have changed that might irratate some users, but are there major reasons to use PulseEffects 5.x over EasyEffects?

I think ideally distros should keep PulseEffects as the 4.x branch, and just not ship the 5.x branch for simplicity's sake. Thoughts on this? From [a quick glance](https://pkgs.org/search/?q=pulseeffects) it seems the only distros shipping PulseEffects 5.x are Fedora 34 and Arch, so there isn't a huge issue here just keeping PulseEffects as the 4.x branch for simplicity in my view.

I am also considering whether users on the [PulseEffects flathub-beta branch](https://github.com/flathub/com.github.wwmm.pulseeffects/tree/beta) (5.x) should be migrated to EasyEffects Flatpak. Flathub does have an [EOL mechanism](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life). However, from what I can tell it does not allow us to only EOL one branch, and since both PulseEffects 4.x and 5.x are in the same repo, it is problematic since we want PulseEffects 4.x to continue to be available on Flathub. However one could just use a warning dialog similar [to here](https://github.com/flathub/com.github.wwmm.easyeffects/pull/2).

**Comment by wwmm** [comment]
I can not think on any advantage the 5.x releases could have. I keep the 5.x branch here only as a means to quickly take a look at the old code in case I create another project in the future that need to use gstreamer and PipeWire. I have no intention at all of updating it and making new 5.x releases.

In my opinion people should not be using it anymore now that the flatpak package was released. Before that some people could argue that they have to use PipeWire but the other packages needed by EasyEffects are not available. But now it is better to use EasyEffects on flatpak than staying on 5.x.

**Comment by vchernin** [comment]
I've opened https://github.com/flathub/com.github.wwmm.pulseeffects/pull/57 to EOL the 5.x Flathub-beta branch, I'll merge it in a few days if no one objects.

Keep in mind you should be able to ignore the EOL warning, so if you really want to you can still install it from flathub-beta. You could also always built it yourself with `flatpak-builder`.

**Comment by vchernin** [comment]
Ok, so I realized the Arch repos don't even carry [PulseEffects](https://archlinux.org/packages/?sort=&q=pulseeffects&maintainer=&flagged=) anymore. Only the AUR has it, so I think that is fine.

So as far as I can tell the only distro shipping PulseEffects 5.x is [Fedora 34, 35 and Rawhide](https://src.fedoraproject.org/rpms/pulseeffects). @Vascom any thoughts on reverting Fedora's `pulseeffects` package to 4.x to make distro PulseEffects packages univerally the PulseAudio version? Furthermore, I see @godsic has updated their COPR repo (#1072) to 6.1.0, any idea when it might make it to the repos?

I see there's [a bug open](https://bugzilla.redhat.com/show_bug.cgi?id=1980111) to rename the Fedora PulseEffects (5.x) package to EasyEffects and seemingly just drop the PulseEffects package (4.x and 5.x). Maybe that's the best option considering it's not like Fedora will ever be "upgrading" to PulseAudio...

**Comment by Vascom** [comment]
I can add something like pulseeffects4 but I think it is not good idea since 4.x and 5.x no longer supported by upstream.

**Comment by vchernin** [comment]
> I can add something like pulseeffects4 but I think it is not good idea since 4.x and 5.x no longer supported by upstream.

Yeah, I don't think it is very useful or necessary for Fedora to package 4.x or 5.x.

I think just renaming the package to EasyEffects and dropping 4.x and 5.x is best. If someone really wants PulseEffects 4.x or 5.x on Fedora I guess they could build the older RPM or try Flatpak.

**Comment by vchernin** [comment]
Ok, I think this is basically mostly addressed. The flathub-beta PulseEffects branch will shortly [tell users to migrate to EasyEffects](https://github.com/flathub/com.github.wwmm.pulseeffects/pull/57). The only remaining step is to get the Fedora package updated, but that is best discussed in https://github.com/wwmm/easyeffects/issues/1072 or elsewhere I think.
