### ISSUE TITLE
Apps for GNOME and GNOME Circle

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1122]
I saw this new website the other day: [apps.gnome.org](https://apps.gnome.org/). Basically it acts as a hub/overview of sorts for notable GNOME apps. It's meant for discoverability among other things.

One section of apps are the ones in [GNOME Circle](https://circle.gnome.org/), which is basically a way for apps that use GNOME-related tools (notably GTK) to be recognized for that. I think EasyEffects could conceivably be part of that. The main benefit from what I can tell is more users might learn about EasyEffects.

What do you think about applying? From a glance I don't see [anything in the requirements](https://gitlab.gnome.org/Teams/Circle/-/blob/master/README.md#who-can-apply) that would be too concerning. However, if you're serious about applying perhaps it might be worth waiting for the main Flatpak-related issues to be fixed (you can probably expect whoever's reviewing would use Flatpak).

**Comment by wwmm** [comment]
>What do you think about applying?

As long as we do not have to follow GNOME update scheduling I do not see any problem.

>you can probably expect whoever's reviewing would use Flatpak

I agree. That is probably one of the reasons why they are requiring a Flatpak package. So we have to wait at least for the issue about the icons to be fixed.

**Comment by vchernin** [comment]
> As long as we do not have to follow GNOME update scheduling I do not see any problem.

I didn't even see update or release scheduling even mentioned in the pages I read, so it's likely there's no problem here. Also some of the apps like [Kooha](https://flathub.org/apps/details/io.github.seadve.Kooha) that are in Circle aren't following GNOME's release schedule/conventions at all. It's something that can be easily asked anyhow.

> So we have to wait at least for the issue about the icons to be fixed.

Yeah agreed.

**Comment by vchernin** [comment]
@wwmm, now that the main Flatpak issues are solved, would you like to open an application? I can fill out the form if that's helpful, but this might be a thing best for you to do.

**Comment by wwmm** [comment]
>would you like to open an application?

I can try and see what happens. I am not sure when yet as I have to finish some other things at my work first. But I will keep this marked on my to do list.

**Comment by wwmm** [comment]
@vchernin and @Digitalone1 they gave some feedback https://gitlab.gnome.org/Teams/Circle/-/issues/96#note_1304845. I have to find some time to see how annoying it will be to make libadwaita to work with gtkmm4. Now that libadwaita had mroe time to mature it may make sense to put some energy on this.

**Comment by Digitalone1** [comment]
I don't think this have a big priority. If I have time next weeks, I'd like to work on improving the Pitch plugin.

**Comment by wwmm** [comment]
Definitely not a big priority. And base on what I have seen so far in Gnome System Monitor's source code libadwaita will require too much use of C code...

**Comment by vchernin** [comment]
@wwmm as discussed in that thread, do you have a preferred spot to put a flatpak manifest? I think I got it mostly working now, after I discovered even though flatpak supports yaml, gnome builder does not...

Keep in mind this repo would also need to contain a git submodule since we use things in https://github.com/flathub/shared-modules/.

**Comment by wwmm** [comment]
>Keep in mind this repo would also need to contain a git submodule

I don't know... Adding a submodule only because of a manifest sounds like a huge overkill. I has no purpose outside of Flatpak.

**Comment by vchernin** [comment]
I'll try to workaround it then by copying the needed parts, it shouldn't be big issue.

Is `util/flatpak/` a good spot to put the manifest? Are you interested in having it in the first place?

**Comment by wwmm** [comment]
>Is util/flatpak/ a good spot to put the manifest?

It can be in this folder. We already have scripts for flatpak things there.

>Are you interested in having it in the first place?

I do not see any problems in having the manifest. We already have files for Debian, Arch Linux and Flatpak. Having a submodule only for the manifest that would be weird.

**Comment by wwmm** [comment]
Well... They did not accept the submission and I do not think it is worth trying to do the latest suggestions. In any case it was an to see some feedback that is entirely focused on the UI.

**Comment by Digitalone1** [comment]
The tips in the latest post of the request ticket are very interesting. I'd like to talk about them in the plans for EE 7.0 (#1316).

**Comment by wwmm** [comment]
>The tips in the latest post of the request ticket are very interesting.

I did not like the idea of moving things that are easy to access to a dialog. For things like general preferences that you do not have to change frequently dialogs are fine. But presets are things we use all the time. Having them hidden in a dialog won't be productive in my opinion. Maybe more elegant from an ui point of view. But not practical.
