### ISSUE TITLE
Issues with global bypass, gain scales and levelbars

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1124]
I'm working on the code and discovered other issues.

- [x] Global bypass is not followed when a plugin is added to the list or their order is changed. The button stays toggled even if the plugins are operating.
- [x] Input and output gains of Autogain and Maximizer are not working. I'm shocked that I only found out this now.

Some levelbar have issues:  Detected in Deesser and Armonics in Bass Enhancer and Exciter. The level goes out of the range on certain parameters. Maybe also the one in Stereo Tools has to be checked, it stays to 0 all the time. Don't know if It's broken or I'm not able to find a combination of parameters to make it move.  

@wwmm since I made lots of changes, it's better if the fixes are applied on top on my commits. I have not finished yet because I'm trying to improve the blocklist management that still fails in some situations.  So if you have any hint, let me know how I can fix the issues above. Then I'll apply the merge request which surely will be the biggest I ever made.

**Comment by Digitalone1** [comment]
OK, the input/output gain can be fixed later.

> I see the global bypass as a temporary action meant to see how much change to the sound the effects are doing. That is how this is usually used in audio plugins hosts. But some users seem to expect this to work like the other permanent settings. I do not see the need to add complexity to this functionality. But I am not against improving it of course.

It's OK, but at least the global bypass button has to be deactivated when the pipeline is reactivated, otherwise this leads confusion to the user.

**Comment by wwmm** [comment]
The signal `settings->signal_changed("plugins")` is activated whenever a plugin is added, removed or put i another position. I think we can put more conde inside bindings like https://github.com/wwmm/easyeffects/blob/616644ea8b780442667572997e46790cd5e1e514/src/stream_output_effects.cpp#L85 that set the bypass switch state to off whenever we change the pipeline.

**Comment by wwmm** [comment]
>But for what I want to do, a single connection have to be made for every app in the app list to check if holder info name is present in the blocklist.

Humm... I haven't looked at the blocklist code in a while but gtk4 listview itens lifetime is something that can change even when scrolling throught it if the item gets out of the user vision. So some care is necessary. This binding may have to be tracked and destroyed in a similar way as this one https://github.com/wwmm/easyeffects/blob/616644ea8b780442667572997e46790cd5e1e514/src/effects_base_ui.cpp#L982. It will depending on what you are trying to do and on where the binding is being made.

About the bypass button a binding between it and the a key with the same name is done in our gsettings database https://github.com/wwmm/easyeffects/blob/616644ea8b780442667572997e46790cd5e1e514/src/application_ui.cpp#L76. If we set this key to off after changes to the `plugins` array it should be enough.
