### ISSUE TITLE
Dot files location?

### ISSUE THREAD

**Issue by tgharib** [wwmm/easyeffects#1125]
Might be a bit of a dumb question but I can't seem to find where the dot files are stored. I'm aware of `~/.config/easyeffects` but that seems to only save the presets whereas I am looking for where the default preset is stored (or which preset to load by default).

**Comment by wwmm** [comment]
If you are searching for our settings location they are saved in a gsettings database and not to an text file. There are a few ways to view our settings. The easiest is probably using `dconf-editor`
![Screenshot from 2021-09-02 01-46-49](https://user-images.githubusercontent.com/16225172/131783341-b15d3db9-bcbd-491b-aeae-756e733bf610.png)

Usually when I think about "dot files" I mean the ones that are used by `graphviz`. If that is what you are thinking about we do not generate such files.

**Comment by tgharib** [comment]
> If you are searching for our settings location they are saved in a gsettings database and not to a text file. There are a few ways to view our settings. The easiest is probably using `dconf-editor`

Thanks, that was what I was looking for! I guess I should explain why I was inquiring: I'm using NixOS to store my configuration declaratively so that I have the same easyeffects configuration on any machine I use.
