### ISSUE TITLE
easyeffect creating 100 icons

### ISSUE THREAD

**Issue by Sabering1** [wwmm/easyeffects#1147]
After installing easyeffect on Arch Linux ill get 100+ icons on my desktop
Im using Gnome 40.4 on X11, Linux Zen kernel
Is this an glitch with easyeffect or something else

**Comment by vchernin** [comment]
#1070

**Comment by wwmm** [comment]
Closing as there is already an issue about this and the source of the problem is in the distribution packages for Linux Studio Plugins.
