### ISSUE TITLE
[Preset EasyEffect] OpenEQ

### ISSUE THREAD

**Issue by EvoXCX** [wwmm/easyeffects#1148]
Hey,
I come to purpose my EQ on EasyEffect only here is the repository 

https://github.com/EvoXCX/EasyEffect-Preset

**Comment by wwmm** [comment]
Feel free to add a link to your repository in our wiki https://github.com/wwmm/easyeffects/wiki/Community-Presets. As we are not providing built-in presets in the equalizer anymore it is the better way to give visibility to your work.
