### ISSUE TITLE
(KDE) Can't see up/down arrow buttons to change the order of effects which are mentioned in README ("use the up/down arrows next to the plugin label at the left side")

### ISSUE THREAD

**Issue by magicgoose** [wwmm/easyeffects#1157]
![image](https://user-images.githubusercontent.com/1442206/133889947-0e486b48-436b-48c9-b2d2-6677484b276f.png)

This is how it looks on my system.

**Comment by wwmm** [comment]
Which version are you using? The one released yesterday `6.1.1`?

**Comment by magicgoose** [comment]
> Which version are you using? The one released yesterday `6.1.1`?

Yes. But I had this problem with all versions since the migration to GTK 4, new name, etc.

**Comment by wwmm** [comment]
That is unfortunate. The latest release has some improvements that should have helped. @Digitalone1 with which themes did you test the new icons?

**Comment by Digitalone1** [comment]
@wwmm Adwaita, Breeze (KDE) and Kora/Papirus.

@magicgoose please run `easyeffects -q` and post the output of `G_MESSAGES_DEBUG=easyeffects easyeffects`

**Comment by Digitalone1** [comment]
This is breeze icon theme on my system.

![Schermata del 2021-09-18 17-44-56](https://user-images.githubusercontent.com/25790525/133894502-5d8320e3-2b2c-44ad-ab89-a22c34da8315.png)

**Comment by Digitalone1** [comment]
The up/down arrows have been removed from EasyEffects, they used to be in PulseEffects. Now you have to drag the plugin to change the position.

Anyway we still have issues with the plugin icon. @magicgoose post the output, which icon theme are you using?

**Comment by magicgoose** [comment]
Oh I see, I was looking for buttons, but apparently the README is outdated, there are no buttons, instead I need to use drag&drop using this 9-dots thing that appears to the right from the effect item, right? And there is nothing wrong with my screenshot, too?

Anyways, if I launch with that option, I get some output and the interesting part is probably this:
```
(easyeffects:4670): Gtk-WARNING **: 16:43:08.577: Unknown key gtk-button-images in /home/user/.config/gtk-4.0/settings.ini

(easyeffects:4670): Gtk-WARNING **: 16:43:08.577: Unknown key gtk-menu-images in /home/user/.config/gtk-4.0/settings.ini

(easyeffects:4670): Gtk-WARNING **: 16:43:08.577: Unknown key gtk-toolbar-style in /home/user/.config/gtk-4.0/settings.ini
```

**Comment by magicgoose** [comment]
> The up/down arrows have been removed from EasyEffects, they used to be in PulseEffects. Now you have to drag the plugin to change the position.

Then everything is OK, sorry for false bug report.

**Comment by Digitalone1** [comment]
> And there is nothing wrong with my screenshot, too?

Yes, please reopen the issue, run `easyeffects -q` and post the output of `G_MESSAGES_DEBUG=easyeffects easyeffects`

**Comment by magicgoose** [comment]
> > And there is nothing wrong with my screenshot, too?
> 
> Yes, please reopen the issue, run `easyeffects -q` and post the output of `G_MESSAGES_DEBUG=easyeffects easyeffects`

https://gist.github.com/magicgoose/ff3336b056190fe9814d42e12a545f0c

**Comment by Digitalone1** [comment]
Can you please tell me if you have `extension-symbolic.svg` in `/usr/share/icons/breeze-dark/actions/symbolic`?

**Comment by magicgoose** [comment]
Yes, I have it, this is the content:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
  <defs id="defs3051">
    <style type="text/css" id="current-color-scheme">
      .ColorScheme-Text {
        color:#eff0f1;
      }
      </style>
  </defs>
 <path 
     style="fill:currentColor;fill-opacity:1;stroke:none" 
     d="m4 3v1h-2v9h12v-9h-2v-1h-3v1h-2v-1zm-1 2h10v7h-10z"
     class="ColorScheme-Text"/>
</svg>
```

**Comment by Digitalone1** [comment]
You should be able to see the toggle plugins icon. Look in KDE system settings the theme related to GTK applications. Did you install `breeze-gtk`?

**Comment by magicgoose** [comment]
> You should be able to see the toggle plugins icon. Look in KDE system settings the theme related to GTK applications. Did you install `breeze-gtk`?

Sorry I'm not following, which icon should I see? I compared our screenshots by eye and looks like they contain the same set of UI pieces.

**Comment by Digitalone1** [comment]
@magicgoose the icon near Plugins button on the bottom bar.

**Comment by magicgoose** [comment]
> @magicgoose the icon near Plugins button on the bottom bar.

Oh I see. In the actual UI, it looks different now (correctly displaying the icon, as on this screenshot), in comparison to my original screenshot. I've rebooted since then, maybe this is the reason.  
So it must have been some temporary glitch. I'm not sure, is it worth debugging this situation?
![Screenshot_20210918_222836](https://user-images.githubusercontent.com/1442206/133909003-74a28434-a6e3-4405-b3f6-d14606a0abed.png)

**Comment by wwmm** [comment]
If a reboot fixed the icon I do not think there is the need for more investigation. I will close this issue. If the icon somehow gets broken again feel free to reopen it.
