### ISSUE TITLE
Changing Spectrum maximum frequency to a value bellow minimum crashes

### ISSUE THREAD

**Issue by w4ll3** [wwmm/easyeffects#1162]
Changing Spectrum maximum frequency to a value bellow minimum causes the GUI to always crash, took me some time to find the where the configs are stored to reset the config (I did that by accident).

**Comment by vchernin** [comment]
FYI at least with Flatpak you can reset configs with `flatpak remove com.github.wwmm.easyeffects --delete-data`

**Comment by w4ll3** [comment]
Daaam, it took me actually more time because I used `flatpak` and `dconf-editor` couldn't find (they are stored at `~/.var/app/com.github.wwmm.easyeffects/config/glib-2.0/settings/keyfile`) so I manually edited that. Just thought it might be useful if someone makes that mistake.

**Comment by Digitalone1** [comment]
You can't set the value below minimum through GUI. Who did you set it?

**Comment by w4ll3** [comment]
It seems it was not bellow, but the same, these are the Spectrum values that make EasyEffects to crash
![image](https://user-images.githubusercontent.com/8595904/134193516-ee3837a7-21ae-495d-a138-02a690e800e6.png)

```
[com/github/wwmm/easyeffects/spectrum]
type='Lines'
color=[0.96078431606292725, 0.7607843279838562, 0.066666670143604279, 1.0]
color-axis-labels=[0.92941176891326904, 0.20000000298023224, 0.23137255012989044, 1.0]
show-bar-border=true
n-points=1000
height=185
line-width=0.10000000000000001
minimum-frequency=20
maximum-frequency=20
```

**Comment by w4ll3** [comment]
> OK, I can reproduce on my system. Thanks to report it @w4ll3.

You're welcome! Congrats for the application as well, I've been enjoying it for 3 days now.

**Comment by wwmm** [comment]
>wwmm my idea is to patch the code to keep a gap between frequencies of minimum 100 Hz. What do you think?

It could be. There isn't a rigid guideline for this. When a sampling rate of 48000 Hz is used the current spectrum resolution is around `0.5 * 48000 / 4096 = 5.9 Hz` where 4096 is the number of FFT  bands. So definitely it does not make sense to have a gap too close to his value.
