### ISSUE TITLE
EasyEffects won't run on Linux Mint 20

### ISSUE THREAD

**Issue by phongvu99** [wwmm/easyeffects#1165]
I followed the instruction and installed the latest version available on Flathub. At first, the PipeWire version was not recent enough, so I upgraded PipeWire, which was the only time EasyEffects showed up with an error message. Since then, there's nothing when I tried to run EasyEffects (no log whatsoever).

What I've tried:
- Upgrade PipeWire
- Disable and Mask the PulseAudio service as instructed [here](https://pipewire-debian.github.io/pipewire-debian/)
- Reboot

Fyi, I'm still keeping the old PulseEffects, so any chance of conflicts?

**Comment by vchernin** [comment]
Have you explicitly enabled the PipeWire services?

`systemctl --user --now enable pipewire{,-pulse}.{socket,service} pipewire-media-session.service`

From that page.

**Comment by phongvu99** [comment]
> Have you explicitly enabled the PipeWire services?
> 
> `systemctl --user --now enable pipewire{,-pulse}.{socket,service} pipewire-media-session.service`
> 
> From that page.

Thanks for the reply. I forgot to do that but still no luck even after explicitly enabling the service.

**Comment by vchernin** [comment]
Do other apps play audio currently? Can you confirm you haven't missed any other steps? Maybe try another reboot after enabling the service.

**Comment by phongvu99** [comment]
> Do other apps play audio currently?

The only apps I used for audio right now are my browser, and Spotify. But right now, none of them are playing anything.

> Can you confirm you haven't missed any other steps? 

- sudo apt install libfdk-aac2 libldacbt-{abr,enc}2 libopenaptx0
- sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}
- systemctl --user --now disable  pulseaudio.{socket,service}
- systemctl --user mask pulseaudio
- systemctl --user --now enable pipewire{,-pulse}.{socket,service} pipewire-media-session.service

Here are the steps that I followed so far. 

> Maybe try another reboot after enabling the service.

I did reboot after enabling the service

**Comment by vchernin** [comment]
Please confirm [PipeWire is actually running](https://github.com/pipewire-debian/pipewire-debian/wiki/Troubleshooting#if-there-is-no-sound-comming-from-your-headsetspeaker).

Most likely you've just missed a step or just done something in the incorrect order.

I'd recommend perhaps reading [this guide](https://www.reddit.com/r/pop_os/comments/ofdalv/comment/h4c5p6u/) which is the same steps except hopefully easier to understand.

**Comment by phongvu99** [comment]
> Please confirm PipeWire is actually running.

`pactl info | grep "^Server"`

I tried the above command but to no success. It just timed out after a while.

Anyway, here the's PipeWire services status.

Sep 24 16:32:04 home-G551JW pipewire[61560]: context0x55acc2aaa9d0: no modules loaded from context.modules
This line caught my attention but I'm not sure it has anything to do with EE failed to start.

● pipewire.socket - Multimedia System
     Loaded: loaded (/usr/lib/systemd/user/pipewire.socket; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-24 16:32:04 +07; 8min ago
   Triggers: ● pipewire.service
     Listen: /run/user/1000/pipewire-0 (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/pipewire.socket

Sep 24 16:32:04 home-G551JW systemd[5404]: Listening on Multimedia System.

● pipewire.service - Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-24 16:32:04 +07; 8min ago
TriggeredBy: ● pipewire.socket
   Main PID: 61560 (pipewire)
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─61560 /usr/bin/pipewire

Sep 24 16:32:04 home-G551JW systemd[5404]: Started Multimedia Service.
Sep 24 16:32:04 home-G551JW pipewire[61560]: context0x55acc2aaa9d0: no modules loaded from context.modules

● pipewire-pulse.socket - PipeWire PulseAudio
     Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.socket; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-24 16:32:04 +07; 8min ago
   Triggers: ● pipewire-pulse.service
     Listen: /run/user/1000/pulse/native (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/pipewire-pulse.socket

Sep 24 16:32:04 home-G551JW systemd[5404]: Listening on PipeWire PulseAudio.

● pipewire-pulse.service - PipeWire PulseAudio
     Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-24 16:32:04 +07; 8min ago
TriggeredBy: ● pipewire-pulse.socket
   Main PID: 61562 (pipewire-pulse)
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire-pulse.service
             └─61562 /usr/bin/pipewire-pulse

Sep 24 16:32:04 home-G551JW systemd[5404]: Started PipeWire PulseAudio.

● pipewire-media-session.service - Multimedia Service Session Manager
     Loaded: loaded (/usr/lib/systemd/user/pipewire-media-session.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-24 16:32:04 +07; 8min ago
   Main PID: 61561 (pipewire-media-)
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire-media-session.service
             └─61561 /usr/bin/pipewire-media-session

Sep 24 16:32:04 home-G551JW systemd[5404]: Started Multimedia Service Session Manager.

**Comment by phongvu99** [comment]
Is there any way to make Easy Effects display the log? 
Also, I've tried the instruction in the Reddit link but to no avail.

**Comment by wwmm** [comment]
>I tried the above command but to no success. It just timed out after a while.

If pactl is not working your PipeWire installation is missing something. Is Firefox o Spotify working when EasyEffects is not running?

>Is there any way to make Easy Effects display the log?

Try `G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.pulseeffects`. But remember to kill any EasyEffects instance you may have running before trying this command.

**Comment by phongvu99** [comment]
A simple apt purge and reinstall resolved the issue. But the app is somewhat unstable, every operation regarding the File Manager (Import Impulse, Import Presets, etc...) caused the app to "hang". Technically, it's still running and processing but I can't close, or do anything with the File Manager window it opened.

**Comment by vchernin** [comment]
I don't experience no such hanging in Fedora 35 with GNOME.

I wonder if the hanging you're finding with the file chooser is due to using an older Mint 20. They will be using Ubuntu 20.04 with older packages, notably xdg-desktop-portal and xdg-desktop-portal-gtk. Those are what provide the file chooser implementation with the Flatpak.

It's possible there was just a bug fix there at some point that never made it to Ubuntu 20.04. It's also possible Mint needs to improve their integration with xdg-desktop-portal somehow.

**Comment by vchernin** [comment]
For completeness could you try [Clapper](https://flathub.org/apps/details/com.github.rafostar.Clapper) (another GTK4 + Flatpak app) and see if you can reproduce that issue?

**Comment by phongvu99** [comment]
> For completeness could you try [Clapper](https://flathub.org/apps/details/com.github.rafostar.Clapper) (another GTK4 + Flatpak app) and see if you can reproduce that issue?

Clapper File Chooser works seamlessly. So maybe it's a EE issue?

Btw, where's the config folder for Easy Effects? I don't see it in the ~/.config folder like Pulse Effect.

**Comment by vchernin** [comment]
With Flatpak it probably is: `~/.var/app/com.github.wwmm.easyeffects/config`

**Comment by vchernin** [comment]
Also what desktop environment are you running? That might effect the file chooser issue.

**Comment by wwmm** [comment]
>Clapper File Chooser works seamlessly. So maybe it's a EE issue?

Probably not. There isn't much that is done on the application side when it comes to file choosers. In order to improve compatibility with flatpak we use `Gtk::FileChooserNative` to show file choosers. Maybe Clapper is using one of the other functions that are available for this. In any case it would be a gtk4 or may a gtkmm4 problem if one of the methods to select files are failing.

>Also what desktop environment are you running? That might affect the file chooser issue.

I agree. I have no problem importing files on GNOME. But I am using Arch Linux. What means every package is on their latest versions. So you may be seeing a a gtk or desktop environment bug that has already been fixed.

**Comment by phongvu99** [comment]
> Also what desktop environment are you running? That might affect the file chooser issue.

I'm using GNOME 3.36.8

**Comment by wwmm** [comment]
>Btw, where's the config folder for Easy Effects? I don't see it in the ~/.config folder like Pulse Effect.

`~/.config/easyeffects/` has only a few things like the users presets and impulse files. Our configuration is handled by a gsettings database. You can see it in dconf editor
![Screenshot from 2021-09-24 14-28-20](https://user-images.githubusercontent.com/16225172/134716493-1a172c71-c3e8-4942-bb98-a58d28b9ce71.png)

**Comment by vchernin** [comment]
Wait you're on Linux Mint with GNOME? I didn't think that was an option, and it's certainly not on linuxmint.com.

**Comment by wwmm** [comment]
>I'm using GNOME 3.36.8.

I do not remember which gnome version I was when I started to use gtk4 in EasyEffects. Now I am on gnome 40. Maybe older gome versions have problems interacting with some programs written in gtk4. Or the issue is specific to the `Gtk::FileChooserNative` call I talked about before. But it does not look like recent desktop environments have problems with it.

**Comment by phongvu99** [comment]
> Wait you're on Linux Mint with GNOME? I didn't think that was an option, and it's certainly not on https://linuxmint.com.

One of the GTK-based application that I'm using, DBeaver, has a UI glitch on the default DE Cinnamon. That's why I've switched to GNOME since I don't see the problem happening on my office desktop, which runs pure Ubuntu 20.04. But it didn't solve the issue, and I have to upgrade my Mint from 19.3 to 20 fix it.

**Comment by vchernin** [comment]
So you've installed GNOME on Linux Mint then? Well I can understand why you'd want to do so, but I'd generally not really recommend doing so. Adding a desktop environment to a distro that almost certainly doesn't officially support it can be problematic... I wonder if the file chooser issue occurs on Ubuntu 20.04.

**Comment by phongvu99** [comment]
> So you've installed GNOME on Linux Mint then? Well I can understand why you'd want to do so, but I'd generally not really recommend doing so. Adding a desktop environment to a distro that almost certainly doesn't officially support it can be problematic... I wonder if the file chooser issue occurs on Ubuntu 20.04.

On the Cinnamon DE right now, but the issue still occurs. At this point, I don't know if I should upgrade my Mint to the latest version 🙂

**Comment by wwmm** [comment]
Which gtk4 and gtkmm4 versions do you have installed? Maybe that is the problem.

**Comment by vchernin** [comment]
Are you already on Mint 20.x? If so I doubt updating will change much since they're still using the same Ubuntu 20.04 base. But as a Fedora user I do like keeping things up to date :)

**Comment by vchernin** [comment]
> Which gtk4 and gtkmm4 versions do you have installed?

This isn't very relevant for Flatpak. They could have no GTK4 installed (and they probably don't) but it will work thanks to GTK4 being in the GNOME runtime and to bundling gtkmm. Those things should be precisely the same version for every Flatpak installation.

What is potentially a source of problems is the `flatpak`, `xdg-desktop-portal`, `xdg-desktop-portal-gtk` and `pipewire` packages. Those are things a Flatpak app can't itself provide or update as they're provided by the host distro.

**Comment by phongvu99** [comment]
Anyway, thanks for the support! And best to create a new issue regarding the file chooser? I should close this to avoid cluttering the issue section.

**Comment by wwmm** [comment]
>This isn't very relevant for Flatpak.

Ok. I always forget about that. In that case I am more inclined to believe `Gtk::FileChooserNative` may be related. But if I am not mistaken we started to use it exactly because it was better for the flatpak package.

**Comment by wwmm** [comment]
>best to create a new issue regarding the file chooser?

Probably.

**Comment by vchernin** [comment]
> But if I am not mistaken we started to use it exactly because it was better for the flatpak package.

Yeah it is better for the Flatpak package, and I think it's generally recomended by GTK anyways these days. The older one will probably be deprecated at some point anyhow.

**Comment by wwmm** [comment]
I wonder which one Clapper is using.

**Comment by vchernin** [comment]
Without even looking at the source I'm sure it's `GTK::FileChooserNative`, since that once correctly interacts with the portal. So I can pick any file on my system even though Clapper has limited access. There are a few other GTK4 apps on Flathub to try to reproduce this with still.

**Comment by databoose** [comment]
All of this was working when this project was pulseeffects, now easyeffects is trying to force pipewire and without any actual clear explanation on how it set it up, so sad to see such a great program not be usable anymore.

Does anyone know of a fork of PulseEffects by chance?
