### ISSUE TITLE
Allow to completely disable output processing

### ISSUE THREAD

**Issue by Riesi** [wwmm/easyeffects#1166]
Would it be possible to completely disable the output audio processing and hooking?
Currently EasyEffects automatically grabs applications that havent been disabled once and pipes it through the output processing configuration. I have "Process All Outputs" disabled.

I only need the input processing features.

Kind regards,
Riesi

**Comment by Digitalone1** [comment]
Hello @Riesi  

If you have `Process All Outputs` disabled, EasyEffects won't grab anything, but it's Pipewire redirecting the stream to EE sink if it was previously used by the application. It's an intended feature to "remember" last device.

If you don't need to process anithing, just save an empty profile, so if Pipewire still redirect the application to EE sink, nothing it's done. Or you can disable the application so the next time it won't be redirected to EE sink. Or, as last option, you can blocklist the application and save the profile with the blocklist updated.

**Comment by Riesi** [comment]
Hmmm so Pipewire redirects the app to EE even though the app was never used with EE before.
Quite annoying.

Would it be possible to somehow set a general priority to prevent this? EE output isnt my default sink
Its quite bothersome to remove every new app by hand.

**Comment by Digitalone1** [comment]
> Hmmm so Pipewire redirects the app to EE even though the app was never used with EE before.
> Quite annoying.

No, it should not redirect the app to EE if the app was never enabled. Are you sure you never enabled an output app? Try to set your output speaker as default sink in system settings.

> Would it be possible to somehow set a general priority to prevent this? EE output isnt my default sink
> Its quite bothersome to remove every new app by hand.

Yes, disable `Process All Output`. Or, as I already said, save an output profile with 0 plugins in the stack (in that case, the EE sink just redirects the stream to the output device, but this should not occur if you disabled the app or never enabled it).

**Comment by Riesi** [comment]
> No, it should not redirect the app to EE if the app was never enabled. Are you sure you never enabled an output app? Try to set your output speaker as default sink in system settings.
Yes I am 100% sure the application was never enabled in EE before, because I havent used it for over two years. And it happend to multiple apps. My output speaker is set as the default sink.

Could this happen due to pipewire and EE both not having seen the app before? But the processing being enabled by default with "Process All Output" disabled is still strange. 

Thanks for the fast replies btw! :beers:

**Comment by Digitalone1** [comment]
> Yes I am 100% sure the application was never enabled in EE before, because I havent used it **for over two years**. And it happend to multiple apps. My output speaker is set as the default sink.

Over two years? EE came out the last July.

Anyway I don't know, in theory Pipewire should not redirect to EE if it was never done before.

Setting an empty profile should be enough to not use any output plugin in case EE sink is picked, even if a limiter to 0 db is always recommended to protect the speakers from clipping.

**Comment by Riesi** [comment]
alright. 
Maybe I will stumble upon more things and get a better idea whats wrong as a whole

Thanks.
I will close this.

**Comment by wwmm** [comment]
When EasyEffects is configured to automatically start in the user login it may happen in some systems that our virtual devices are initialized by PipeWire before the real devices(sound card). It depends on the time the user sound card needs to be initialized. Only PipeWire developers can give a good explanation for this. But the result is that our virtual devices will be automatically selected by PipeWire as default devices because they are the only ones available. PipeWire should switch to the real devices once they are initialized. Assuming it does not have a bug in this process...

**Comment by wwmm** [comment]
Usually this time window is very small. So apps manually started by the user once the login is finished should not see our virtual devices as default. But it is possible PipeWire has some kind of bug where our sink could have stayed as default in some occasions. This could explain why it is automatically moving apps to our sink even if you never did this yourself.
