### ISSUE TITLE
After switch to GTK4, window is double scaled on Plasma

### ISSUE THREAD

**Issue by elman22** [wwmm/easyeffects#1167]
I use Plasma on 4K display with scaling set to 200 %. PulseEffects worked fine, however now with EasyEffects installed, window is double scaled e.g. it is shown with scaling of 400 %. I tried running EasyEffects with variables GDK_SCALE and GDK_DPI_SCALE, but it doesn't seem to have any effect. So I was wondering whether is it problem with EasyEffects or with Plasma itself.

I'm on Manjaro testing, EasyEffects 6.1.2, X11 and scaling set to 200 %.

**Comment by wwmm** [comment]
>So I was wondering whether is it problem with EasyEffects or with Plasma itself.

There is another variable to be considered: GTK4. PulseEffects used gtk3. My guess is that either gtk4 has a bug or plasma needs some kind of fix to play nice with gtk4. In any case there is nothing that can be done on the application side when it comes to monitor scaling. This is handled by the graphical toolkit (gtk4) and the desktop (plasma).

Try to see if other gtk4 apps have the same problem. At least Arch Linux has a package named `gtk4-demos` that provides the executable `gtk4-demo`. It should help to test.

**Comment by elman22** [comment]
Thank you for the info and quick reply. I just checked `gtk4-demo` and it has the same problem. So obviously this is not an issue with EasyEffects.
