### ISSUE TITLE
EasyEffects crashes on startup after first launch

### ISSUE THREAD

**Issue by danshat** [wwmm/easyeffects#1174]
Apparently after EasyEffects runs for the first time and closes fine, it cannot start afterwards - main window pops up for like 200 ms and then it crashes. To fix this I had to remove ~/.var config files and reinstall EasyEffects from Flatpak.

1. Running KDE 5.21.4 on Kubuntu 21.04. 
2. Flatpak installation
3. Here are the last few lines from debug: 
<details>
<summary>Logs</summary>

```
(easyeffects:2): easyeffects-WARNING **: 13:56:27.239: effects_base_ui: webrtc voiceengine icon name not installed in the breeze icon theme in use. The application icon has been hidden.
(easyeffects:2): easyeffects-DEBUG: 13:56:27.239: sie: pipeline latency: 7.125000 ms
(easyeffects:2): easyeffects-WARNING **: 13:56:27.240: sie: convolver: irs file path is null. Entering passthrough mode...
(easyeffects:2): easyeffects-DEBUG: 13:56:27.240: sie: crystalizer blocksize: 1024
(easyeffects:2): easyeffects-DEBUG: 13:56:27.251: sie: pipeline latency: 9.791667 ms
(easyeffects:2): easyeffects-DEBUG: 13:56:27.254: sie: crystalizer latency: 0.000021 s
(easyeffects:2): Gtk-CRITICAL **: 13:56:27.275: gtk_widget_get_first_child: assertion 'GTK_IS_WIDGET (widget)' failed
qrc:/plasma/plasmoids/org.kde.plasma.volume/contents/ui/ListItemBase.qml:153: TypeError: Value is undefined and could not be converted to an object

```
</details>

4. https://pastebin.com/BMeV1rwm
5. 
![image](https://user-images.githubusercontent.com/13084473/135256920-0ea3a334-6e80-4419-89aa-08d83baa836f.png)
![image](https://user-images.githubusercontent.com/13084473/135256948-4752c8a8-ef15-47ae-a32d-4affe7899d65.png)
![image](https://user-images.githubusercontent.com/13084473/135256970-3e60e911-96fe-4b08-bed2-cd44826271be.png)
![image](https://user-images.githubusercontent.com/13084473/135256990-e895cee3-ced9-4a99-9205-d3af6a370b76.png)
![image](https://user-images.githubusercontent.com/13084473/135257003-9711a6be-b11e-49bb-b461-cf2952f4d51b.png)

**Comment by wwmm** [comment]
You can try to pass the option `-r` to reset our settings instead of reinstalling it. Once it is running again try to see if the crash happens with any plugin or only with one of them.

**Comment by wwmm** [comment]
The full log may also help to understand what is happening.

**Comment by danshat** [comment]
`-r` option neither seems to reset configuration nor fix the crash: https://pastebin.com/cHgYF1qE
Although (I think?) after a reboot I launched it like usual and it was fine for a few minutes, then I manually closed it, and got the same very crash again:
https://pastebin.com/tPgNp3su
Again, `-r` does nothing this time and the log is similar to first link.

**Comment by wwmm** [comment]
Oh... Now I remember the reset does not work in the Flatpak package...

@vchernin considering flatpak is being used do you have any thoughts about how to debug this issue?

**Comment by danshat** [comment]
I would happily build it myself, except that somehow `debuild` doesn't see `meson` installed from pip3, and `meson` from Ubuntu repositories is outdated (but atleast `debuild` knows about it).

**Comment by vchernin** [comment]
So some information:

Debian builds will are still in progress, see #1000.

You can clear EasyEffects's cache and configuration with:
```bash
flatpak remove com.github.wwmm.easyeffects --delete-data
```

Indeed the reset button is broken in Flatpak, that's https://github.com/flathub/com.github.wwmm.easyeffects/issues/4

Things to debug:

1. Is the "Shutdown on window close" option being used? (It's off by default). Can you test with and without that option enabled the first time you run EasyEffects?

2. Please try even without any plugins. So:
   1. Start a fresh EasyEffects. 
   2. Close it (with or without "Shutdown on window close")
   3. Run it again and see what happens.

3. If you don't learn anything from step 1 and 2 can try getting more logs, or even a stack trace (don't know how useful that is here though).
```bash
sudo apt install libflatpak-dev
flatpak install com.github.wwmm.easyeffects.Debug//stable
flatpak install org.gnome.Sdk//41
flatpak install org.gnome.Sdk.Debug//41
```
```bash
flatpak-coredumpctl com.github.wwmm.easyeffects
```

**Comment by danshat** [comment]
Issue is related to Discord. 

With Discord launched, and after our familiar crash, I can spam the same `flatpak run` command, and I have to run it a few times (usually 2-3, but sometimes a bit more, around 7-8 times) getting same crashes and then all of a sudden EasyEffects starts just like normal. That is all without any plugins enabled. [This](https://pastebin.com/yUzcQEHt) is our usual crash and [this](https://pastebin.com/sc2RsN4c) or [this](https://pastebin.com/iBpfbuPf) are both successful runs afterwards the initial crash, and [this](https://pastebin.com/z4DscC1z) is another crash after some successful runs.
Shutdown on window close, turned off or on, changes nothing.
With Discord on, not even the first clean run always works. Crashes don't seem time dependant, nor they depend on if EasyEffects device is selected as input device in Discord, and it eventually starts fine one way or another. Eventually.


That's what `flatpak-coredumpctl` returns (sorry, have no idea how to fix):
```
danshat@danshat-H310M:~$ flatpak-coredumpctl com.github.wwmm.easyeffects
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 44, in run
    subprocess.check_call(["coredumpctl", "dump"] + shlex.split(self.coredumpctl_matches),
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['coredumpctl', 'dump']' returned non-zero exit status 1.
```
With Discord off, there are no crashes altogether, and [this](https://pastebin.com/i79YNJgC) would be the log.

**Comment by danshat** [comment]
Initiating microphone device selection dialogue in Firefox leads to similar behaviour. I guess it is directly related to programs scanning for audio devices, since I don't have to record from EasyEffects Source to get a crash next time I launch EasyEffects, but having in some list is enough already.

**Comment by wwmm** [comment]
Is this still a problem? At least on my computer Discords mic test does not cause a crash. As I do not use discord I don't know if the rest of its functionality can lead to a crash.
