### ISSUE TITLE
New installation & the audio sounds horrible. 

### ISSUE THREAD

**Issue by Taihouu** [wwmm/easyeffects#1177]
On a fresh install of Archcraft. Installed Easyeffects via AUR and Flatpak; both result in audio sounding terrible: there's an echo and it sounds as if it's coming out of a can. I've installed Pipewire; Pipewire-pulse and Pipewire-alsa. Tried running it with no plugins enabled and it had the same result, but just to confirm perhaps someone else can load [my config](https://pastebin.com/yqew3Fmq) and tell me if it sounds fine (I've had it running on previous installations and have made no edit to it since so it shouldn't be the config). Audio sounds fine without Easyeffects loaded. Any ideas?

**Comment by Digitalone1** [comment]
You seem to have too much plugins enabled.

Try some of the community presets [here](https://github.com/wwmm/easyeffects/wiki/Community-presets).

**Comment by wwmm** [comment]
>Tried running it with no plugins enabled and it had the same result

Without any plugins EasyEffects just passthrough audio without altering it. This together with the fact you hear echo make me believe something is very wrong in your configuration. Install the package from AUR and make sure no instance is running `easyeffects -q`. After that start it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see if there is something in its output that may help.
