### ISSUE TITLE
Auto disabling effects for headphones [Feature request]

### ISSUE THREAD

**Issue by frusanov** [wwmm/easyeffects#1178]
### EasyEffects Version

6.1.2

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 34

### Expected Behavior

Detect when I insert headphones on headset jack into my laptop and change preset or enable global bypass

### Actual Behavior

Nothing changes

### Additional Information

I use EasyEffects for better sound on my laptop speakers, but it's very annoying to manually toggling global bypass when I want switch from speakers to headphones or back

**Comment by wwmm** [comment]
Preset autoloading is supported. Is it not working? Or do you have an autoload profile for when the headphone is plugged but you want to revert the effects once it is not plugged anymore? In this case what you have to do is define a profile that will disable the filers once the headphone is not plugged.

**Comment by frusanov** [comment]
@wwmm Thanks for quick response! I managed to setup profile autoload. But it's very unintuitive. For different audio device profiles I need create preset association when device is in specific profile. I think add dropdown with device profiles in presets autoloading section is must have.

**Comment by wwmm** [comment]
This is something I talked about before https://github.com/wwmm/easyeffects/issues/1051#issuecomment-914613564. It may seem simple when thinking about a computer that has only one simple soundcard. But in general it is really hard to get this "dropdown solution" right. And as I said in the comment I linked in most cases the user will be required to have some level of understanding about how Linux audio is handled by the audio servers that most people do not have. The current solution isn't intuitive. I totally agree. But showing a dropdown with many possible profiles  for each supported sound card mode (digital or analogical) is not going to make things better for the non advanced user. We will replace one problem with another.

**Comment by NickColley** [comment]
If other people run into this and are confused why they dont see multiple options for both their laptop's speakers and the headphone, they're considered the same 'Device' but when you add the autoloader it'll set it to the correct option automatically.

So in other words:
Unplug your headphones, and set the auto loader you'll notice it'll set the profile to "analog-output-speaker".
Then plug your headphones in and set a different preset, you'll notice it'll have the profile of "analog-output-headphones".

If it's possible to change the interface to make this more obvious it may help people, either by making it possible to select these different profiles or by letting users know this behaviour somehow.

**Comment by wwmm** [comment]
>either by making it possible to select these different profiles

I think I considered this possibility a long time ago. The problem is that we have no control over the availability of a profile. It may or not be valid depending on which kind of hardware is plugged and on how they are configured.

And to make things worse sometimes these profiles have names that aren't very intuitive. So the user may have no idea about which profile is the one needed.
