### ISSUE TITLE
EasyEffects (as a background service) gets killed shortly after login

### ISSUE THREAD

**Issue by crxssrazr93** [wwmm/easyeffects#1186]
### EasyEffects Version

6.1.2

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 21.04 x86_64

### Describe the bug

Running EasyEffects via Flatpak.

It is configured to autostart as a background service & persist on login.

See here:

![image](https://user-images.githubusercontent.com/38873931/135763045-c0a6bcc2-70c0-4eb1-b9c1-b0796609725e.png)

This is what the .desktop config file looks like;

```
[Desktop Entry]
Type=Application
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=EasyEffects
Name=EasyEffects
Comment[en_US]=EasyEffects Service
Comment=EasyEffects Service
```

While it does launches on login & works, it doesn't persist. It gets killed a minute or so upon log in.

### Expected Behavior

EasyEffects launch on login as a background service. (Pass)

EasyEffects is able to process audio as a background service. (Pass)

EasyEffects continues to function as intended; i.e a background service. (Fail)

**Comment by vchernin** [comment]
Please run `flatpak permission-reset com.github.wwmm.easyeffects`

After running the command please try reboot and test it out again.

From experience I think it's likely xdg-desktop-portal is killing EasyEffects because at some point you've told your system to not let EasyEffects run in the background.

**Comment by crxssrazr93** [comment]
You were right. That did the trick.

Thank you.

Closing this issue.
