### ISSUE TITLE
Issue with spectrum frequency axis on default value

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1195]
### EasyEffects Version

6.1.3

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch

### Describe the bug

The spectrum horizontal axis is not rendered good at the default value 20 kHz.

![Schermata del 2021-10-09 20-20-48](https://user-images.githubusercontent.com/25790525/136670011-13c9b32b-361b-4901-8bdf-d617575aa29b.png)

The final part misses the frequency.

### Expected Behavior

The axis is rendered better at the maximum value 22 kHz.

![Schermata del 2021-10-09 20-21-29](https://user-images.githubusercontent.com/25790525/136670056-03a4688d-f618-4f77-86f0-5e62d3014ea4.png)

### Additional Information

Maybe we should consider to change the default value to 22 kHz so the user sees a better rendering at the default. The window was maximized on a 1366x768 px display, pretty common on laptops.

**Comment by vchernin** [comment]
Is something where the GTK theme matters?

For me on Adwaita with 20 Hz min value.
![image](https://user-images.githubusercontent.com/38842733/136670279-dd4634a9-2d6f-412d-a275-da3f1573dfe3.png)

Switching to 22 Hz:
![image](https://user-images.githubusercontent.com/38842733/136670289-120f6d2b-2aca-43b6-ae1e-c3b766a789f8.png)

My setup is a HiDPI one with a 4k monitor. For me the axis adjusts reasonably well resizing the window in my opinion. Maybe a video would make things more clear.

**Comment by Digitalone1** [comment]
Okay, I understood why. It's the `points` value. I set it at 300. At the default 100 is good. 400 also is good.

@wwmm you can close this if you want.
