### ISSUE TITLE
Spectrum still in use in background, even when disabled

### ISSUE THREAD

**Issue by ShaneTRS** [wwmm/easyeffects#1202]
### EasyEffects Version

6.1.3

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

The "spectrum" device doesn't go away or even get taken out of the chain of devices when the spectrum is disabled in EasyEffects.

Here's a screenshot of my audio arrangement with spectrum disabled:
![image](https://user-images.githubusercontent.com/80662335/136983458-ede22110-d447-488d-90ce-b38f4134255c.png)

### Expected Behavior

I expect the "spectrum" device to either vanish entirely, or just get taken out of the chain.
Here's an example screenshot where I've done so manually:
![image](https://user-images.githubusercontent.com/80662335/136983562-fcabcede-8a84-4f78-a95b-e2e883af096f.png)

### Additional Information

Screenshots are taken of Helvum

**Comment by wwmm** [comment]
I have updated our master branch with some changes that make the spectrum enter in the passthrough mode also when we just hide it while keeping the main window opened. From a performance point of view this should be enough. 

Have in mind that its node will still be in the pipeline. The pipeline is a critical part of our code and it is already more complicated than I would like. Trying to actually remove the spectrum node from the graph will make things even more complicated. And the last time we tried to dynamically adding/removing nodes from the graph all we got were applications freezes. There process involved to get this right is not trivial. It is far easier and safer to load the filters once and keep them there.
