### ISSUE TITLE
Usability: indicate plugin stack order

### ISSUE THREAD

**Issue by DanMan** [wwmm/easyeffects#1204]
It's currently not clear in which order the plugins are applied: top to bottom or reverse? So it'd be good, if there was some sort of indication. Maybe instead of using the ⚙️ icon next to the plugin name use something that indicates direction, like ↧ or ↥ Or maybe enumerate them 1, 2, 3, …

**Comment by wwmm** [comment]
As I was expecting they changed the way symbolic icons are created in gtk4 https://wiki.gnome.org/HowDoI/CreateSymbolicIconsThatChangeColorAccordingToTheme. This explains why the ones I used in gtk3 were not changing colors automatically when I started the gtk4 port. In any case the steps still seem to be simple.

**Comment by wwmm** [comment]
I will save the following links here as a reference not only for one of the approaches we may eventually take to fix this issue but for the future also
https://gitlab.gnome.org/GNOME/gtk/-/issues/4105
https://docs.gtk.org/gtk4/method.IconTheme.set_resource_path.html

Although I have to agree with the gtk4 developers that their docs talk about that I think this kind of thing should be in more obvious place in their documentation...

**Comment by wwmm** [comment]
I am playing a little with the idea of having numbers but so far it not looking amazing
![Screenshot from 2021-10-13 16-45-05](https://user-images.githubusercontent.com/16225172/137202513-85f83c33-51d5-447a-a5ee-a0b1b178bd19.png)
![Screenshot from 2021-10-13 16-45-17](https://user-images.githubusercontent.com/16225172/137202519-aaa12231-dd01-4831-a5ca-9f6856a35704.png)
Having the numbers inside a circle to give them a more distinctive look is not viable. Too little space there for the icon to grow enough for the numbers to look good. So the icons will probably have only the number. They look better than an ordinary text but it may be possible to get something similar adding another label object and setting it to bold...

There is the other option of adding another entry at the start or the end related to mic/speakers... But I am not sure I like it either. And from an implementation point of view there are some annoyances in that approach like has already been said by Digitalone1...

In any case I do not think we have to rush this decision. This is the kind of issue we can keep open for a while and see which kind of ideas come with time.

**Comment by wwmm** [comment]
Maybe the arrow in front of the plugins names is the way to go. I don't think any solution will be simpler to implement than that. And it should be enough to give people an idea of where the signal is going to.

**Comment by servimo** [comment]
For me is logic that the order of the plugins are from up to down.

**Comment by wwmm** [comment]
Implemented on `6.1.4`

**Comment by Digitalone1** [comment]
> Downside is that, if you only have 2 plugins out, they both just have a box, so it's not clear which one is applied 1st. Just sayin'

Maybe it's better to show only the final point when the plugins are only two.
