### ISSUE TITLE
Don't change volume with scrolling

### ISSUE THREAD

**Issue by Elendil211** [wwmm/easyeffects#1211]
**EasyEffects Version**
6.1.3

**What package are you using?**
Arch Official (easyeffects)

**Distribution**
Arch Linux

**Describe the bug**
When scrolling through the list of different players/recorders (by using the mouse wheel), and you end with your mouse cursor on the volume bar of one player/recorder, the next mouse wheel movement does not result in scrolling the list, but instead in the volume being changed.

**Expected Behavior**
Scrolling should not affect the volume. Scrolling should just scroll through the list.

**Solution**
Make the volume bar insensible to scrolling.

**Comment by wwmm** [comment]
>Perhaps there is a way to disable mouse wheel scrolling for those sliders

Not that I remember. But even if there is a way to do that most of the time I change sliders positions through the mouse scroll. So I do not think that disabling it is the best solution.

**Comment by saivert** [comment]
You would have a variable that is set to 1 when a scrolling event starts on the container widget and will be reset to 0 when any mouse movement occurs. This would avoid the issue where you scroll, then stop for a bit and continue scrolling and now it adjusts volume on something instead of continuing scrolling.

**Comment by jannuary** [comment]
```
noëlle: is there away for a gtkscale to ignore the scrollwheel?
Alexander Mikhaylenko: noëlle: add your own event controller (probably with a capture phase) and stop events there```

**Comment by wwmm** [comment]
>add your own event controller (probably with a capture phase) and stop events there```

I tried to add an event controller but the scale still got scroll events anyway. Maybe the controller has to be added in a very specific and non obvious way.

**Comment by wwmm** [comment]
I will try again to add a controller. Maybe I did not test all the possible flags the last time I tried.

**Comment by wwmm** [comment]
Adding a controller created as `gtk_event_controller_scroll_new(GTK_EVENT_CONTROLLER_SCROLL_NONE);`. Does nothing. The scale still gets scroll events. Same thing with `GTK_EVENT_CONTROLLER_SCROLL_HORIZONTAL`. Last time I looked at the `GtkScale` sources it seemed to have the scroll events hardcoded. Adding an event controller only seems to allow additional event handling. It does not override the ones that are hardcoded.

**Comment by wwmm** [comment]
>probably with a capture phase

I wonder what he meant by `capture phase`.

**Comment by wwmm** [comment]
Oh! Maybe I have to actually set a callback ignoring the events from the controller. I will try that. I was just trying to set the controller.

**Comment by wwmm** [comment]
Now that I am trying to hook a callback I see that gtk is ignoring my controller. Maybe it is that moment at which I am trying to add it. Weird.

**Comment by wwmm** [comment]
I understood why gtk was ignoring my event callback. Although our scale is on the horizontal orientation the event is still emitted as `GTK_EVENT_CONTROLLER_SCROLL_VERTICAL`... I was not expecting that. Using `GTK_EVENT_CONTROLLER_SCROLL_BOTH_AXES` is probably a safer option in this case.

With this I could make the GtkScale ignore the scroll event in the sense that its value does not change. But there is still a problem @jannuary. Although the scale does not move with the scroll events anymore it still "eats events" and does not allow the scroll to actually act on the list. 

So what the custom controller is doing is avoiding the scale value to be changed on scroll events. The scale widget still catches the scroll events and does not let them act on the `GtkScrolledWindow` instead.

**Comment by wwmm** [comment]
For future reference this is what I did
```
auto* controller = gtk_event_controller_scroll_new(GTK_EVENT_CONTROLLER_SCROLL_BOTH_AXES);

  g_signal_connect(
      controller, "scroll",
      G_CALLBACK(+[](GtkEventControllerScroll* controller, gdouble dx, gdouble dy, AppInfo* self) { return 1; }), self);

  gtk_widget_add_controller(GTK_WIDGET(self->volume), controller);
```

**Comment by wwmm** [comment]
As the volume scale is not used anymore we can close this issue. Believe it or not this was the only way to fix the problem...
