### ISSUE TITLE
Music flow interruption with Firefox and Spotify

### ISSUE THREAD

**Issue by bhack** [wwmm/easyeffects#1213]
### EasyEffects Version

Easyeffect 6.1.3

### What package are you using?

Other (specify below)

### Distribution

Debian

### Describe the bug

Using Spotify with the EasyEffects equalizer and filter type `FIR` `FFT` and `SPM` I hear multiple interruptions in the sound flow every time a new Firefox player join.  As many pages nowdays have multiple players it is very annoying as the music has continuous holes when scrolling these web pages.

What I see with pw-top and scrolling on a webpage with embedded videos (e.g. like twitter) is that Firefox clients constantly join end exit as you scroll or mouse over on a new video with a QUANT of 3308 where spotify has fixed QUANT at 43218

P.s.
This ticket was forked from https://github.com/wwmm/easyeffects/issues/1117#issuecomment-929607992

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
As I am not sure when or if we will ever have a solution to this problem I suggest you tell PipeWire to use a fixed latency https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#latency-quantum-settings. It is the only solution that can be done at this moment.

**Comment by wwmm** [comment]
>Do we have a solution to ignore the latency event if the app that requested the new latency it is in the easyeffect excluded list?

No, we can not ignore the latency change. When PipeWire changes latency the size of the buffer given to all active audio clients is changed too. We have to work with the new buffer. No escaping that. It is complicate to explain the whole process with words but it is more or less like this

- Let's consider that spotify is the only one playing and that the buffer size is 4096. This means that our filters have to read arrays with 4096 elements and write data to arrays of the same size.
- If we start a Firefox playback stream and it requests a latency that corresponds to a buffer size of 2048 the buffer of all audio  clients have their size adjusted to this new value. The same happens to our filters.
- Depending on the filter it may or may not have data accumulated inside of it when all this process happens. How much it will have depends on how the filter works. In other words on its latency. Not necessarily it would be 4096 data elements. The value can be higher or lower.
- If we just save the buffer for the next round we will have an old buffer with 4096 elements but the destination arrays have space only for 2048 in the example above. So the final array will have to be filled with half the data on the old array and the last half as well as the new 2048 elements will have to be scheduled to the next iteration. Depending on the new and current latency values the final array may have to be partially filled with old and new data at the same time part of the new data is saved for use in the next filter iteration. It is super annoying to deal with this.

>As the problem happen also just scrolling the page not only when you really want to play a video in the page.

If the latency was changed the browser has already initialized a playback stream. From this point on it does not matter if it is playing silence or paused. The stream has already requested a latency to the server.

**Comment by bhack** [comment]
> f we just save the buffer for the next round we will have an old buffer with 4096 elements but the destination arrays have space only for 2048 in the example above. So the final array will have to be filled with half the data on the old array and the last half as well as the new 2048 elements will have to be scheduled for the next iteration. Depending on the new and current latency values the final array may have to be partially filled with old and new data at the same time part of the new data is saved for use in the next filter iteration. It is super annoying to deal with this.

Can we just allocate the new 2048 vector in parallel and consume the last 4096 buffer so that we consume the 2048 buffer in the next iteration or we are going to introduce a latency the we will never recover?

**Comment by bhack** [comment]
> If the latency was changed the browser has already initialized a playback stream. From this point on it does not matter if it is playing silence or paused. The stream has already requested a latency to the server.

Yes the problem is that many of these could start in autoplay or they just appear when scrolling, on mouseover events etc...

**Comment by wwmm** [comment]
>Can we just allocate the new 2048 vector in parallel and consume the last 4096 buffer so that we consume the 2048 buffer in the next iteration or are we going to introduce a latency the we will never recover?

No. It will never be recovered without discarding data. The array we read audio data from and the one we have to write to are allocated by PipeWire with a size that corresponds to the current latency. All we can do is using them. Changing their size is out of our reach. From the moment we let data to be processed later we have to delay all of them. This is where latency will be introduced. Think of the audio buffer as a line of people waiting to get inside a bus and that initially we have to put inside the bus packages full with 4096 people. Suddenly we can only put inside the bus packages full with 2048 and the current iteration where we discover this fact already has such a package waiting to be processed besides te one we saved for later. Either we send away the last 4096 people from the package that was saved for later and take the package already full with 2048 people or we delay everybody so everyone in the package with 4096 is put inside in 2 iterations of 2048. The problem can happen the other away around too. We may start with 2048 and then having to put 4096 at once and so on.

**Comment by bhack** [comment]
OK so the problem is that we are constrained immediaty to where at the new size.

Instead what do you think about my previous comment on the default Alsa latency?

**Comment by wwmm** [comment]
`8192` is the maximum possible buffer size. Even if an application requests a ridiculously high latency of one second like spotify does. So there is an upper bound on the maximum possible latency. Something similar to what you saw with Gnome settings also happens with Pavucontrol. It must have initialized some kind of volume level monitor stream or something similar that requested a latency whose buffer size corresponds to 1024. If no other audio app requests a lower latency the buffer size will remain at 1024 while the application that requested it is running.

**Comment by bhack** [comment]
So the point is that if the output buffer is already smaller (at `1024`) and we don't have this issue.. e.g. at QUANT 1024 we don't have any problem as Firefox join and exit at `QUANT` 3308 and so it requires Alsa at QUANT `2048`. As `2048>1024` so we don't any latency change that affect Easyeffects filters.

So it seems that the only workaround currently is to have a default latency lower than Firefox to avoid its latency change requests?

**Comment by bhack** [comment]
Ok thanks.
/cc @wtay just in the case he his interested to track this topic on the Pipewire side.

**Comment by bhack** [comment]
Just a side note, with the convolver the situation is also worse as in the same scenario some buffer bypassed the filter not only silence interruption. 
So In the quite common case your apply a negative pre-amp you have a volume change/clipping that it is not pleasant especially when you are connected with headphones.

**Comment by bhack** [comment]
We could have a potential solution to test at https://github.com/wwmm/easyeffects/issues/1023#issuecomment-987453003

**Comment by bhack** [comment]
I suppose that we can close this and other related issues.
