### ISSUE TITLE
How to build a custom Upmixer and Downmixer

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1216]
Since we can't rely on Pipewire for this, if we want to perform downmixing and upmixing like the old PulseEffects (where this task was done by PulseAudio), we should setup our custom channel remapping configuration.

We failed with the loopback stream. The virtual sink never worked. The virtual source solution was working in August until a new Pipewire version came out and that does not work either. Anyway these methods expose a stream in Pavucontrol, which is not what we want.

So let's make an analysis of what we should handle taking the most advanced [7.1 system](https://en.wikipedia.org/wiki/7.1_surround_sound).

> 7.1 surround sound adds two additional speakers to the more conventional six-channel (5.1) audio configuration. As with 5.1 surround sound, 7.1 surround sound positional audio uses the standard **front left** and **right**, **center**, and **LFE** (subwoofer) speaker configuration. However, whereas a 5.1 surround sound system combines both surround and rear channel effects into two channels (commonly configured in home theatre set-ups as two rear surround speakers), a 7.1 surround system splits the **surround** and **rear** channel information into four distinct channels.

Then we have a stereo stream emitting on FL and FR ports of our output level meter node. How and where do we link them to output device?

* **Front Left** and **Front Right**

We already link them. Go ahead.

* **Surround Left** and **Rear Left**

The logic tells me that these two should receive what is coming from FL.

* **Surround Right** and **Rear Right**

Same logic as above, but these take FR

* **Front Center**

The question here starts to be tricky. This channel is generally used for voices only, but we have them mixed with music/effects and can't separate them.

The first solution that came to my mind is to link both FL and FR, but this seems wrong because summing the two streams would lead to clipping most of the time. I wonder how Pipewire is mixing multiple streams to an output device to avoid clipping. Maybe they already do something to prevent it. Honestly I never tested, I don't know.

Otherwise, if they don't prevent it, we have to sum the half of both channels: `(FL * 0.5) + (FR * 0.5)`. Anyway this will lead to silence in extreme cases where the two signals are _anticorrelated_ like explained [here](https://matthewvaneerde.wordpress.com/2010/12/07/downmixing-stereo-to-mono/) or, as it's commonly said in other articles, when they are completely out of phase.

This is rare and in the upmixing stage it's not a big issue since we still have output on the other channels, anyway a solution to avoid signal cancellation on the case above would be privileging a channel over another like `(FL * 0.6) + (FR * 0.4)`. 

* **Low-frequency effects**

From [Wikipedia](https://en.wikipedia.org/wiki/Low-frequency_effects): The LFE channel is a band-limited audio track that is used for reproducing deep and intense low-frequency sounds in the 3–120 Hz frequency range.

The only thing to do here seems to dowmix as stated above and apply a low-pass filter on the result.

* **Mono Downmix**

In this case we should apply the same concepts specified for the center channel, maybe having a look to avoid signal cancellation.

This also applies for other channels out of common configurations not specified above.

* **Conclusion**

The real issue in doing this task is summing two streams and splitting the low frequencies. If Pipewire is already correctly mixing multiple streams to avoid clipping, we could just link two streams to one port and we remain to solve the splitting with the low-pass filter, which should be something already done in the Crystalizer (or we can do it with an additional Calf Filter).

(related to #1142, #1126, #1104 and #1041)

**Comment by Digitalone1** [comment]
I made a test with this [1kHz sine wave](https://www.youtube.com/watch?v=2nRmPmG6Ncc) at 0 db. Reproduced with Firefox disabling the loudness normalization through _h264ify-enhanced_ extension I got 0 db on EE output level meter as expected.

Linking both FL and FR on a single input port of the EE sink, the level meter reports +6 db. 

In it's original configuration, disabling the extension, Firefox applies a loudness normalization outputting at -14 db, but linking both channels on one ports the level meter is -8 db, so always 6 db above the single link.

Reading the [article](https://matthewvaneerde.wordpress.com/2010/12/07/downmixing-stereo-to-mono/) posted above:

> Note that downmixing these two totally uncorrelated signals results in a loss of power of 3 dB FS; the power of the two-tone is **-6 dB FS**, 3 dB FS lower than each of the individual -3 dB FS signals that went into it.

Not sure if I understood totally, but it seems Pipewire know of this loss of power mixing 2 ports on a single one and restores it adding 6 db.

This causes clipping anyway, but it could be avoided just lowering both channels by 6 db prior to linking.

**Comment by wwmm** [comment]
If we wanted to do downmix from surround to stereo these would be the equations https://www.audiokinetic.com/library/edge/?source=Help&id=downmix_tables. What I was hooping to find is something like these but for the upmix. Maybe now that I know the AC3 standard has the downmix we can find how the upmix is supposed to be done. There are definitely many ways to do it and all those "Dolby whatever" surround modes are an example. But it is enough to support one mode.

The low-pass filter for the subwoofer channel should not be a big problem because we already have a low-pass filter implemented.

**Comment by Digitalone1** [comment]
I found some research paper in PDF explaining some modes, but they are too complex for us, we need something relatively simple.

The easier that I discovered was summing the left and right channels, then applied a filter to split voice on center and another filter to split bass on lfe. For surround channels, it got the difference of both channels, then implemented a time delay and a phase rotation. 

Can't post it now because I'm on phone, tomorrow I'll link it, but I think we need something easier.

**Comment by Digitalone1** [comment]
Okay.

**Comment by Digitalone1** [comment]
This will force ffmpeg dependency. I think mpv uses this filter for upmixing.

**Comment by wwmm** [comment]
>This will force ffmpeg dependency.

What I am thinking about is reading its source code and evaluate how hard it will be to write our own filter based on what is done there. Making ffmpeg a dependency only for one plugin is not worth it.

**Comment by Digitalone1** [comment]
In the Pipewire changelog I see latest versions introduced a "more advanced upmixing algorithm". Does this mean we can rely on it and close this issue?

**Comment by Digitalone1** [comment]
I saw more accurately. Pipewire introduced Passive Surround Decoding and [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/861) issue was closed. But it has to be enabled manually because the simple upmixing method is used by default.

I wonder if this somehow solves our issue. Currently I don't even remember which was the problem, lot of time passed.

**Comment by wwmm** [comment]
>I wonder if this somehow solves our issue. Currently I don't even remember which was the problem, lot of time passed.

I did not look in details but it seemed to me that the upmixing that PipeWire already did to streams was improved. What is good. But our problems was that it only did upmixing to links involving `streams` and done through the media session manager. In our case we have to do manual links that involve filters. It does not seem that this is being handled. So our original problem still stands.

The question now is if it is easier for the user to workaround this situation loading loopback devices.

**Comment by Digitalone1** [comment]
@capoei @MarcinW87 @susonthapa Can you test setting a lookback device and redirecting to the default output?

```
pw-loopback -m '[FL FR]' --capture-props='media.class=Audio/Sink node.name=my-sink'
```

These are the options to set for upmixing:
```
channelmix.upmix=true 
channelmix.stereo-widen=0.1 
channelmix.rear-delay=15 
channelmix.lfe-cutoff=120 
channelmix.fc-cutoff=8000.0 
channelmix.hilbert-taps=15
```

**Comment by capoei** [comment]
> @capoei @MarcinW87 @susonthapa Can you test setting a lookback device and redirecting to the default output?
> 
> ```
> pw-loopback -m '[FL FR]' --capture-props='media.class=Audio/Sink node.name=my-sink'
> ```
> 
> These are the options to set for upmixing:
> 
> ```
> channelmix.upmix=true 
> channelmix.stereo-widen=0.1 
> channelmix.rear-delay=15 
> channelmix.lfe-cutoff=120 
> channelmix.fc-cutoff=8000.0 
> channelmix.hilbert-taps=15
> ```

I'm sorry, I switched OS

**Comment by Digitalone1** [comment]
This could be closed since I don't think we have the effort to build an upmixer. Pipewire could just let us use their own for filters in the future.

A possible temporary workaround is reported in https://github.com/wwmm/easyeffects/issues/1126#issuecomment-1141315558

**Comment by rijnhard** [comment]
this is probably a naive comment, but if I have to think about my dream scenario for multi-channel audio handling, 

```
multi channel source
          --> (filter all channels) e.g. some funny bunch of filters I slap together for my own Dynamic Range Compression
          --> (start individual channel filters) 
                   | -> FR/FL  --> (2 chan filter) 
                   | -> Centre --> (1 chan filter)
                   | -> RL/RR  --> (2 chan filter)
          --> (end individual channel filters) 
          --> (filter all channels)
          --> FFmpeg encoding for output format
```
