### ISSUE TITLE
Unable to run easyeffects

### ISSUE THREAD

**Issue by TimB87** [wwmm/easyeffects#1217]
### EasyEffects Version

6.1.4

### What package are you using?

Other (specify below)

### Distribution

CRUX

### Describe the bug

This is happening for a few weeks now.

First I thought this is wireplumber related, but I just caught up with the issue tracker and it seems like you got it working everywhere else. I tested it with pipewire-media-session and thats a no fly either.
Checked on dependent ports but I found nothing out of place.

### Expected Behavior

easyeffects is executed and does its sweet magic :sparkles: 

### Debug Log

<details><summary>Debug Log</summary><br/>

```
❯ G_MESSAGES_DEBUG=easyeffects easyeffects
(process:8052): easyeffects-DEBUG: 10:39:43.505: main: locale directory: /usr/share/locale
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: user presets directory already exists: /home/tim/.config/easyeffects/
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: user presets directory already exists: /home/tim/.config/easyeffects/input
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: user presets directory already exists: /home/tim/.config/easyeffects/output
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: user presets directory already exists: /home/tim/.config/easyeffects/autoload/input
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.522: presets_manager: user presets directory already exists: /home/tim/.config/easyeffects/autoload/output
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.539: application: easyeffects version: 6.1.4
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.539: pipe_manager: compiled with PipeWire: 0.3.38
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.539: pipe_manager: linked to PipeWire: 0.3.38
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: core version: 0.3.38
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: core name: pipewire-0
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: found metadata: settings
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: found metadata: default
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: found metadata: route-settings
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: Audio/Sink 47 alsa_output.pci-0000_01_00.1.hdmi-stereo with timestamp 1634459983541945545 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.541: pipe_manager: Audio/Sink 48 alsa_output.usb-Logitech_G935_Gaming_Headset-00.analog-stereo with timestamp 1634459983541986753 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.542: pipe_manager: Audio/Source 49 alsa_input.usb-Logitech_G935_Gaming_Headset-00.mono-fallback with timestamp 1634459983542009383 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.542: pipe_manager: Audio/Source 50 alsa_input.usb-RODE_Microphones_RODE_NT-USB-00.analog-stereo with timestamp 1634459983542025753 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.542: pipe_manager: Audio/Sink 51 alsa_output.pci-0000_00_1b.0.analog-stereo with timestamp 1634459983542041852 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.542: pipe_manager: Audio/Sink 82 easyeffects_sink with timestamp 1634459983542204565 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.542: pipe_manager: Audio/Source/Virtual 79 easyeffects_source with timestamp 1634459983542222907 was added
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.547: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.usb-Logitech_G935_Gaming_Headset-00.analog-stereo" }
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.547: pipe_manager: new metadata property: 0, default.configured.audio.source, Spa:String:JSON, { "name": "alsa_input.usb-RODE_Microphones_RODE_NT-USB-00.analog-stereo" }
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.547: pipe_manager: new metadata property: 0, default.video.source, Spa:String:JSON, { "name": "v4l2_input.pci-0000_00_1a.0-usb-0_1.1.2_1.0" }
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.547: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.usb-Logitech_G935_Gaming_Headset-00.analog-stereo" }
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.547: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.usb-RODE_Microphones_RODE_NT-USB-00.analog-stereo" }
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.548: pipe_manager: easyeffects_sink node successfully retrieved with id 82 and timestamp 1634459983542204565
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.548: pipe_manager: easyeffects_source node successfully retrieved with id 79 and timestamp 1634459983542222907
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.599: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.632: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.675: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.740: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.755: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.769: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.769: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:8052): easyeffects-DEBUG: 10:39:43.793: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
zsh: illegal hardware instruction (core dumped)  G_MESSAGES_DEBUG=easyeffects easyeffects
```
</details>

### Additional Information

pipewire: 0.3.38
wireplumber: 0.4.4
easyeffects: since.. 6.1.2..?

Thanks for continuing with easyeffects on pipewire! :heart:

**Comment by wwmm** [comment]
>zsh: illegal hardware instruction

I think it is the first time I see that. What is the output of `sudo coredumpctl info` right after the crash?

**Comment by wwmm** [comment]
The only plugins using fftw directly or indirectly are the following `crystalizer, convolver, spectrum`. After resetting only the spectrum is left. But if you start easyeffects while no audio application is running the spectrum or the other filters code should not even be executed. Something else is going on. The fftw message may be misleading us.

**Comment by wwmm** [comment]
>but I can't bring the gui into foreground...

That is weird... I wonder if something is broken in your gtk4 install. Was there any update to its packages recently?

**Comment by TimB87** [comment]
```
(easyeffects:3): easyeffects-WARNING **: 16:49:27.866: portal: background request failed:GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.Background? on object at path /org/freedesktop/portal/desktop
```
If I'm not mistaken thats something thats in use with gnome-settings-daemon... which depends on elogind or sdbus features?
I substitute the latter [basu](https://sr.ht/~emersion/basu) but thats not good enough for gnome stuff last time I checked.. :/

**Comment by TimB87** [comment]
gtkmm is on `4.4.0` as well.

Ok! I didn't say this is on wayland with sway, I don't suppose this makes a difference since gtk4 supports wayland just fine but just in case.. I am clueless.

**Comment by wwmm** [comment]
What is weird is that the flatpak package is also having problems. Was there anything more in its logs?

**Comment by TimB87** [comment]
It's obviously working though, when I killed the process I had that short period where the music stopped because the sink was handed over..

**Comment by TimB87** [comment]
build with `--buildtype debug` and prevented stripping.. no further info than:
```
Thread 1 "easyeffects" received signal SIGILL, Illegal instruction.
0x00007ffff6956296 in fftwf_mkproblem_rdft2 () from /usr/lib/libfftw3f.so.3
```

**Comment by TimB87** [comment]
I might have an idea but that will take another hour or two in compile times.. 
Recently I updated glibc, although I have rebuilt all packages after that ~2 times, maybe I went lazy on it and forgot to do gcc-fortran for fftw..? I don't really think so but I guess it's worth a shot.

**Comment by TimB87** [comment]
Sadly, it doesn't :/

**Comment by TimB87** [comment]
Then I guess rebuilding fortran and dependent ports on that is a good guess. Now that I come to think about it, I had difficulties with ncmpcpp as well (also compiled against fftw...). I didn't dig that deep, there it helped to take a build from another machine of mine, that probably doesn't do fortran, fftw etc..

**Comment by vchernin** [comment]
Wait a minute...
You have a 3570K Ivy bridge cpu.

The cpu line was succeeded by Haswell. Haswell was the first cpu like [that supported avx 128 fma](https://en.m.wikipedia.org/wiki/FMA_instruction_set).

Flatpak fftw is explicit build with avx 128 fma.

**Comment by vchernin** [comment]
No idea why it partially works, it's probably due to how EasyEffects implements it...

If you'd like I can make a Flatpak test build with fftw without avx 128 fma. It's not too difficult to build yourself though, there's instructions in the wiki.

**Comment by vchernin** [comment]
> ```
> 
> (easyeffects:3): easyeffects-WARNING **: 16:49:27.866: portal: background request failed:GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.Background? on object at path /org/freedesktop/portal/desktop ```


Now I see this, do you have xdg-desktop-portal and xdg-desktop-portal-wlr installed? They are generally supposed to be present along with Flatpak.

**Comment by wwmm** [comment]
>No idea why it partially works, it's probably due to how EasyEffects implements it...

The native package build seems to be crashing when calling `fftwf_plan_dft_r2c_1d` to initialize fftw. This function just initialize the fast fourier transform plan. This isn't even the moment when fftw actually tries to compute the transform.

Something else is happening to the flatpak package. If it were the same thing it would have crashed. But instead of that it does not show the window

**Comment by vchernin** [comment]
> I have both of them installed for screensharing, yes, just not the gnome-portal since.. hard dependency on elogind/systemd..

I find it a bit concerning that you have the correct portal packages installed but this request does not work. I feel like this is another bug... If you want to debug this further there [is a portal test app on Flathub](https://flathub.org/apps/details/com.belmoussaoui.ashpd.demo). The background portal is the one EasyEffects uses. If it doesn't work there either then it's probably a xdg-desktop-portal-wlr bug.

> About the flatpak: thanks for the offer 🙏 But I'll first try to get it working without it. I might get back to it if I absolutely can't make it work, but I am hopeful that the toolchain fix might potentially unbreak that for me.

Hopefully it does, best of luck!

**Comment by TimB87** [comment]
Interesting test app there, didn't know that one and it certainly seems like I have something to fix for xdg-desktop-portal-wlr then :|
Thank you for your help!

**Comment by TimB87** [comment]
@wwmm Hey, litte ping from me, sorry for being silent so long on this. I have a paper to hand in next week, but I already have an updated toolchain prepared, I just don't want to risk having to do a recovery right now xD Will report back!

**Comment by wwmm** [comment]
No problems :-)

**Comment by TimB87** [comment]
Ok, this took a while longer.

Long story short, indeed our fftw port was missing openmpi support! I finally get to run easyeffects again!

Maybe this can be a check within the meson build? I can look into that later to maybe get a PR going :)

diff of files provided by fftw without and with openmpi:
```
--- /usr/ports/contrib-37/fftw/.footprint	2022-01-15 15:54:16.709849992 +0100
+++ /usr/ports/overlay/fftw/.footprint	2022-01-16 13:55:02.503049401 +0100
@@ -6,9 +6,12 @@
 -rwxr-xr-x	root/root	usr/bin/fftwl-wisdom
 -rwxr-xr-x	root/root	usr/bin/fftwq-wisdom
 drwxr-xr-x	root/root	usr/include/
+-rw-r--r--	root/root	usr/include/fftw3-mpi.f03
+-rw-r--r--	root/root	usr/include/fftw3-mpi.h
 -rw-r--r--	root/root	usr/include/fftw3.f
 -rw-r--r--	root/root	usr/include/fftw3.f03
 -rw-r--r--	root/root	usr/include/fftw3.h
+-rw-r--r--	root/root	usr/include/fftw3l-mpi.f03
 -rw-r--r--	root/root	usr/include/fftw3l.f03
 -rw-r--r--	root/root	usr/include/fftw3q.f03
 drwxr-xr-x	root/root	usr/lib/
@@ -27,6 +30,11 @@
 lrwxrwxrwx	root/root	usr/lib/libfftw3.so -> libfftw3.so.3.6.10
 lrwxrwxrwx	root/root	usr/lib/libfftw3.so.3 -> libfftw3.so.3.6.10
 -rwxr-xr-x	root/root	usr/lib/libfftw3.so.3.6.10
+-rw-r--r--	root/root	usr/lib/libfftw3_mpi.a
+-rwxr-xr-x	root/root	usr/lib/libfftw3_mpi.la
+lrwxrwxrwx	root/root	usr/lib/libfftw3_mpi.so -> libfftw3_mpi.so.3.6.10
+lrwxrwxrwx	root/root	usr/lib/libfftw3_mpi.so.3 -> libfftw3_mpi.so.3.6.10
+-rwxr-xr-x	root/root	usr/lib/libfftw3_mpi.so.3.6.10
 -rw-r--r--	root/root	usr/lib/libfftw3_omp.a
 -rwxr-xr-x	root/root	usr/lib/libfftw3_omp.la
 lrwxrwxrwx	root/root	usr/lib/libfftw3_omp.so -> libfftw3_omp.so.3.6.10
@@ -42,6 +50,11 @@
 lrwxrwxrwx	root/root	usr/lib/libfftw3f.so -> libfftw3f.so.3.6.10
 lrwxrwxrwx	root/root	usr/lib/libfftw3f.so.3 -> libfftw3f.so.3.6.10
 -rwxr-xr-x	root/root	usr/lib/libfftw3f.so.3.6.10
+-rw-r--r--	root/root	usr/lib/libfftw3f_mpi.a
+-rwxr-xr-x	root/root	usr/lib/libfftw3f_mpi.la
+lrwxrwxrwx	root/root	usr/lib/libfftw3f_mpi.so -> libfftw3f_mpi.so.3.6.10
+lrwxrwxrwx	root/root	usr/lib/libfftw3f_mpi.so.3 -> libfftw3f_mpi.so.3.6.10
+-rwxr-xr-x	root/root	usr/lib/libfftw3f_mpi.so.3.6.10
 -rw-r--r--	root/root	usr/lib/libfftw3f_omp.a
 -rwxr-xr-x	root/root	usr/lib/libfftw3f_omp.la
 lrwxrwxrwx	root/root	usr/lib/libfftw3f_omp.so -> libfftw3f_omp.so.3.6.10
@@ -57,6 +70,11 @@
 lrwxrwxrwx	root/root	usr/lib/libfftw3l.so -> libfftw3l.so.3.6.10
 lrwxrwxrwx	root/root	usr/lib/libfftw3l.so.3 -> libfftw3l.so.3.6.10
 -rwxr-xr-x	root/root	usr/lib/libfftw3l.so.3.6.10
+-rw-r--r--	root/root	usr/lib/libfftw3l_mpi.a
+-rwxr-xr-x	root/root	usr/lib/libfftw3l_mpi.la
+lrwxrwxrwx	root/root	usr/lib/libfftw3l_mpi.so -> libfftw3l_mpi.so.3.6.10
+lrwxrwxrwx	root/root	usr/lib/libfftw3l_mpi.so.3 -> libfftw3l_mpi.so.3.6.10
+-rwxr-xr-x	root/root	usr/lib/libfftw3l_mpi.so.3.6.10
 -rw-r--r--	root/root	usr/lib/libfftw3l_omp.a
 -rwxr-xr-x	root/root	usr/lib/libfftw3l_omp.la
 lrwxrwxrwx	root/root	usr/lib/libfftw3l_omp.so -> libfftw3l_omp.so.3.6.10
@@ -88,6 +106,10 @@
 -rw-r--r--	root/root	usr/lib/pkgconfig/fftw3l.pc
 -rw-r--r--	root/root	usr/lib/pkgconfig/fftw3q.pc
 drwxr-xr-x	root/root	usr/share/
+drwxr-xr-x	root/root	usr/share/info/
+-rw-r--r--	root/root	usr/share/info/fftw3.info
+-rw-r--r--	root/root	usr/share/info/fftw3.info-1
+-rw-r--r--	root/root	usr/share/info/fftw3.info-2
 drwxr-xr-x	root/root	usr/share/man/
 drwxr-xr-x	root/root	usr/share/man/man1/
 -rw-r--r--	root/root	usr/share/man/man1/fftw-wisdom-to-conf.1.gz
```

**Comment by wwmm** [comment]
>Maybe this can be a check within the meson build?

I have no idea. But I am not sure our Meson files would be the proper place. The reason is we do not ask fftw to do something with openmpi. It is something fftw is trying to use by itself under the hoods. So it feels like something that has to be fixed in its packages.

**Comment by TimB87** [comment]
I see, maybe it just feels the way because other software runs fine with fftw without openmpi (e.g. ncmpcpp). I am just surprised because nowhere the error I got indicated that fftw is "just missing" openmpi.

**Comment by wwmm** [comment]
I think we can close this.
