### ISSUE TITLE
Convolver UI frequency AXIS

### ISSUE THREAD

**Issue by bhack** [wwmm/easyeffects#1219]
### EasyEffects Version

6.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Debain

### Describe the bug

When I import the impulse response WAV in the convolver plugin and I click the spectrum button the frequency curve quite it seems strange:

![immagine](https://user-images.githubusercontent.com/1710528/137642738-33218f3e-c176-43e1-9397-8aac9db01f92.png)

Is it ok?

### Expected Behavior

I expect a curve more like:
https://github.com/jaakkopasanen/AutoEq#linux

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by bhack** [comment]
I think that importing  https://github.com/jaakkopasanen/AutoEq impulse responses it is really a quite frequent use case as it is also what they suggested to equalize vs importing APO in the equalizer plugin.

I suppose that visualizing this cure as we are doing now some users could have the feeling that something was gone wrong in the importing process and so the filter was not setup correctly.

**Comment by AndersenJ** [comment]
> I think that importing https://github.com/jaakkopasanen/AutoEq impulse responses it is really a quite frequent use case as it is also what they suggested to equalize vs importing APO in the equalizer plugin.
> 
> I suppose that visualizing this curve as we are doing now some users could have the feeling that something was gone wrong in the importing process and so that the filter was not setup correctly.

Can confirm, I'm a user who wasn't sure whether something had gone wrong in the importing process since the graph looked so odd to me (using either of the wav files here: https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Philips%20SHP9500).

**Comment by wwmm** [comment]
As a reference for myself this is how the `Philips SHP9500` impulse file looks like when no approximation is done
![Screenshot from 2021-11-05 17-15-28](https://user-images.githubusercontent.com/16225172/140573658-3857b2e6-1879-49c2-9e2e-6710741dce6b.png)
![Screenshot from 2021-11-05 17-15-39](https://user-images.githubusercontent.com/16225172/140573659-f4082170-fd6f-4383-9a5e-027fe0965a06.png)
Very sharp peaks both at the beginning and at the end of the spectrum. I have the feeling it is going to be tough to decimate the data in a way this kind of curve looks close to the original... And I have my doubts spline interpolation would look good on this too.

**Comment by wwmm** [comment]
Our current master branch is using the `GSL` library to do interpolation. I think that now that charts are as good as they can get when it comes to the tradeoff between resolution and performance. We can close this issue.
