### ISSUE TITLE
PulseEffects in separate repo?

### ISSUE THREAD

**Issue by y2kbadbug** [wwmm/easyeffects#1224]
Hello,

I still have people who wants to use PulseEffects, as I was managing the FreeBSD port.  Is it possible to put PulseEffects, at least the final version that ran for PulseAudio in a separate repo so people who still use PulseAudio can get it.

Thanks!

**Comment by wwmm** [comment]
>Is it not possible to use this branch? https://github.com/wwmm/easyeffects/tree/pulseaudio-legacy

It should be. This is the branch where I update PulseEffects when a fix for a critical bug is needed.
