### ISSUE TITLE
Applied Preset isn't easily visible

### ISSUE THREAD

**Issue by Netherquark** [wwmm/easyeffects#1229]
### EasyEffects Version

6.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 34

### Describe the bug

The current applied preset was visible in PulseEffects. It used to be a clickable element which displayed the applied preset, and you could click it to view other presets and manage/select them. In EasyEffects however, 
![image](https://user-images.githubusercontent.com/65618735/139528304-52df78fd-2c54-4e49-aff5-bc00b1cec610.png)

You can select presets, but its not easy to view what preset is already in use. 

### Expected Behavior

The applied preset is clearly visible to the user to increase ease of use.

**Comment by wwmm** [comment]
There is a way to know which was the last applied preset. It is shown at the bottom of the presets menu
![Screenshot from 2021-10-30 10-52-11](https://user-images.githubusercontent.com/16225172/139535680-99c0af31-ab41-4d5d-bcef-f8442519afcb.png)

The way this was handled in PulseEffects had serious flaws that could not be solved even after a long time talking about it in an issue that was open at the time. It may have seemed fine for people that do not apply effects for output and input devices at the same time. But for the ones that did, like myself, there was no way to know the last applied preset for both pipelines. Once you loaded a preset for input effects you did not have a way to know which was the last preset applied for output effects anymore. And vice versa. All the solutions proposed at the time required a space in the headerbar we can not afford. Another problem was handling long preset names. Some people needed them and there was also no space for this in the headerbar.

I understand the current way is not as straightforward as the one in used in the past. But at least it is consistent for everybody. Now we can always know which was the last preset applied for output and input effects. And people that need long preset names also can have them.
