### ISSUE TITLE
Some inputs don't work while in the preset selecting menu

### ISSUE THREAD

**Issue by Netherquark** [wwmm/easyeffects#1230]
### EasyEffects Version

6.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 34

### Describe the bug

While in the presets menu, I can't increase or decrease the volume by scrolling on this (top right corner Gnome 40):
![image](https://user-images.githubusercontent.com/65618735/139528422-d32a29cd-b69e-4876-ad24-8e970d5e7df9.png)
 Along with that, Super + scroll to switch between virtual desktops also doesn't work. 

### Expected Behavior

Maybe this is related to the scrolling input only, I'm not sure, but it breaks the seamlessness of the UI. Please fix this if possible.

**Comment by wwmm** [comment]
GTK4 popover menus behave differently https://gitlab.gnome.org/GNOME/gtk/-/issues/3130. And disabling autohide like it is suggested there has disadvantages. Sometimes users want the menu to be closed when clicking on other windows. 

As this is a new gtk4 behavior and not something I can fix on my side I will close this issue.

**Comment by wwmm** [comment]
I decided to reopen this issue. I am doing some tests with the `autohide` property disabled. It fixes this issue. The disadvantage is that the only way to close the menu is clicking on the menu button .It does not close when clicking on the other parts of the app window like it used to happen in gtk3. So I am not sure about what will be the better behavior...

**Comment by wwmm** [comment]
And disabling autohide fixes another gtk4 issue https://gitlab.gnome.org/GNOME/gtk/-/issues/4369... I think I will disable autohide on our popover menus and see how the users will react to that change.

**Comment by vchernin** [comment]
Indeed I think trying auto hide on all the menus is worth trying, hopefully that works out.

**Comment by wwmm** [comment]
>Indeed I think disabling auto hide on the popover menus is worth trying, hopefully that works out.

I have updated the master branch with autohide disabled on all menus. Let me know if something weird happens in the Flatpak build. So far the only annoyance is having to click on the menu button to close the popovers. But I think this is one of those cases where we won't be able to have everything. Being able to control other things while the menu is opened may be more useful than being able to close it by clicking anywhere.

**Comment by wwmm** [comment]
We did some tests with `autohide = false` and it is really annoying being forced to click on the menu button to close the menu. It is better to go back to the old behavior.
