### ISSUE TITLE
App switch doesn't work on latest WirePlumber

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1251]
### EasyEffects Version

6.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

App switch, e.g. for Firefox does not work on Fedora 35 with latest WirePlumber. I can disable the app but EasyEffects still processes the audio. It used to work, but I presume a WirePlumber update regressed it. media-session is fine.

### Expected Behavior

WirePlumber works as expected.

### Additional Information

I'll switch to older WirePlumber to find out what regressed this.

**Comment by wwmm** [comment]
> media-session is fine.

Then it is a sign we should report this to WirePlumber's developers just like the last time.

**Comment by vchernin** [comment]
I think I found the problem.

It works on the latest wireplumber, but the issue is that easyeffects sink is automatically set as the system sound output (i.e. in gnome settings) when easyeffects is opened. Older wireplumber builds did not do this. I am determining which version this was introduced in as it seems incorrect. I am not sure why you'd select the easyeffects sink as your output.

**Comment by vchernin** [comment]
`wireplumber-0.4.3-3.fc35.x86_64` was the last Fedora build where this worked normally.  `wireplumber-0.4.4-2.fc35.x86_64` was where this bug was introduced. I will report it.

**Comment by wwmm** [comment]
>the issue is that easyeffects sink is automatically set as the system sound output

I see. This has been an eternal problem... I will have to think about some kind of work around for this. At least in the cases where there is only one output device besides our own we can try to guess which output we should be suing instead of relying on the server default output device being the user hardware...

**Comment by vchernin** [comment]
Do you think I should report it to wireplumber regardless? Since there is a clear regression when switching wireplumber versions.

**Comment by wwmm** [comment]
>Do you think I should report it to wireplumber regardless?

Yes. Even if we can workaround this somehow it does not seem right that they select a virtual device as default when the hardware is there and the user is not forcing the virtual device to be the standard.

**Comment by wwmm** [comment]
Even if our virtual device is loaded before the user sound card device they should still favor the hardware when selection the default output. With the exception of the cases where the user is manually selecting the virtual device as default. If I remember well PipeWire's developer said something like that in the past. The hardware should have priority.

**Comment by vchernin** [comment]
https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/107

**Comment by vchernin** [comment]
As noted in the last comments in that bug, this might actually just be user error. Something set easyeffects sink as the default system output. It might have been me.

**Comment by vchernin** [comment]
Closing since there was never really a bug, and any relevant improvements belong in wireplumber anyway.
