### ISSUE TITLE
Does loudness plugin take system volume into account?

### ISSUE THREAD

**Issue by kkanungo17** [wwmm/easyeffects#1253]
Hi,

I'm currently using the loudness plugin, with output set to -12.4dB which then feeds into the EQ plugin. In this case, is the loudness plugin simply adjusting for the 12dB decrease or does it take into account system volume as well?

**Comment by wwmm** [comment]
>does it take into account system volume as well?

No. If I am not mistaken the best way to use this Linux Studio Plugins would be making its "Output Volume" control the system volume control. But I think that it will be impossible to do this kind of integration in the users system. The plugin is still useful in some specific situations. But for the use case you seem to have in mind it may be a little annoying to keep your your system volume fixed and using this plugin volume control as the system volume control.

**Comment by kkanungo17** [comment]
That's too bad. I guess the best way would be having pipewire itself implement this.

**Comment by kkanungo17** [comment]
I guess then the best way to have the EQ plugin first with the preamp adjustment set through the "input" slider and then have the resulting signal go into the loudness plugin whose "output volume" sets the final volume, keeping system volume at max?

**Comment by wwmm** [comment]
It always depends on the objective but it seems a good plan.
