### ISSUE TITLE
Equalizer has no input

### ISSUE THREAD

**Issue by hellkaim** [wwmm/easyeffects#1260]
Hi.
Am using easyeffects 6.1.5.r0.ge13f757d-1 on Arch and have an issue with Equalizer plugin.

Expected behavior:
Start EasyEffects, add Equalizer plugin to output, set EasyEffects Sink as default output in PulseAudio Volume Control.
Change any frequency in EQ. GUI should show output levels and Sound should change in the speakers accordingly.

Current behavior:
Start EasyEffects, add Equalizer plugin to output, set EasyEffects Sink as default output in PulseAudio Volume Control.
Change any frequency in EQ.
GUI shows 0 at levels in EQ and despite any changes sound stays the same.

Additional notes:
Bypass (global and for plugin) is unchecked.
Using Carla I can see that my sound source is connected correctly to EE and sound should pass to the default audio device after being processed by EE plugins.

System info:
System:
  Kernel: 5.14.16-artix1-1 x86_64 bits: 64 compiler: gcc v: 11.1.0
  parameters: BOOT_IMAGE=/boot/vmlinuz-linux
   acpi_osi=Linux   acpi_osi=Windows2012 i915.modeset=1 nouveau.modeset=0 net.ifnames=0 quiet splash
  rd.udev.log_priority=3 vt.global_cursor_default=0
  Desktop: Xfce 4.16.0 tk: Gtk 3.24.29 info: xfce4-panel wm: xfwm 4.16.1 vt: 7
  dm: LightDM 1.30.0 Distro: Artix Linux base: Arch Linux

Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio
  vendor: Dell XPS 15 9550 driver: snd_hda_intel v: kernel bus-ID: 00:1f.3
  chip-ID: 8086:a170 class-ID: 0403
  Sound Server-1: ALSA v: k5.14.16-artix1-1 running: yes
  Sound Server-2: JACK v: 1.9.19 running: no
  Sound Server-3: PulseAudio v: 15.0 running: no
  Sound Server-4: PipeWire v: 0.3.40 running: yes

I would appreciate any help or advice. I can share any additional info. Please see attached screenshot

![screenshot](https://user-images.githubusercontent.com/40304971/142396796-39234cd1-beed-48db-a072-e220923aad9b.png)

**Comment by wwmm** [comment]
>set EasyEffects Sink as default 

I do not think it is related to the current issue but unless you have to a strong reason to set our virtual devices as default do not do that. EasyEffects(and PulseEffects) is designed assuming your devices remain as default.

Kill the current instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`. I think you may not have `Linux Studio Plugins` installed.

**Comment by hellkaim** [comment]
@wwmm regarding "a strong reason to set our virtual devices as default"
If I am not setting it as a default device it seems EE does nothing. I can see that VLC is directly attached to Default sound card and sound seems to bypass EE. BUT I MAY BE WRONG!

Please see the log attached.
[EE_debug.log.zip](https://github.com/wwmm/easyeffects/files/7572905/EE_debug.log.zip)

**Comment by wwmm** [comment]
> I can see that VLC is directly attached to Default sound card

Enable `Process All Outputs` in our settings menu. EE will redirect the application to our virtual de vice. Unless the application asks the sound server to forbid that. This is the only situation where you may have to set our virtual devices as default.

**Comment by wwmm** [comment]
>lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr port symbol not found: ftl_0

Warnings like these mean that you do not have Linux Studio Plugins installed. The equalizer we use is from this package.

**Comment by hellkaim** [comment]
OK. yes it was lsp-plugins that were missing... my 50Mb of things...
I was confused as at the buttom right corner of EE is a string: using **Linux Studio Plugins**
I thought they are installed and are in use.

So we can close the issue: after installation it all worked as expected. THX for prompt reply and your time.

PS. May be add for arch users that they have to check if lsp-plugins are installed as EE from aur seems to forget about them (I will ping the author).

**Comment by hellkaim** [comment]
Final solution: check lsp-plugins are in the system.
