### ISSUE TITLE
Fails to launch with gtk-launch and wofi

### ISSUE THREAD

**Issue by l3s2d** [wwmm/easyeffects#1262]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Linux

### Describe the bug

The following command doesn't do anything:
`gtk-launch com.github.wwmm.easyeffects`

### Expected Behavior

EasyEffects should launch.

### Debug Log

```
env G_MESSAGES_DEBUG=all gtk-launch com.github.wwmm.easyeffects

(gtk-launch:672780): GLib-GIO-DEBUG: 10:36:48.840: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(gtk-launch:672780): dconf-DEBUG: 10:36:48.840: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.840: watch_fast: "/org/gnome/desktop/peripherals/mouse/" (establishing: 0, active: 0)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.840: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.840: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.840: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.840: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.841: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.841: watch_established: "/org/gnome/desktop/peripherals/mouse/" (establishing: 1)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.841: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.841: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.841: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
(gtk-launch:672780): dconf-DEBUG: 10:36:48.841: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
(gtk-launch:672780): Gdk-DEBUG: 10:36:48.844: Compositor prefers decoration mode 'server'
(gtk-launch:672780): GLib-DEBUG: 10:36:48.844: unsetenv() is not thread-safe and should not be used after threads are created
(gtk-launch:672780): GLib-GIO-DEBUG: 10:36:48.851: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
```

### Additional Information

gtk-launch works correctly with my other desktop files. The behavior is the same between the Flatpak version and the Arch Linux repo version.

Discussion of this bug on the wofi issue tracker: https://todo.sr.ht/~scoopta/wofi/45

**Comment by wwmm** [comment]
>The behavior is the same between the Flatpak version and the Arch Linux repo version.

I use Arch Linux and `gtk-launch` works fine here with the native package. But my Gnome installation uses Wayland. As I do not use flatpak I do not know about it. Can you test it @vchernin ?

**Comment by l3s2d** [comment]
Some more info:
- I'm running in sway (wayland)
- Removing `DBusActivatable=true` from the desktop file fixes the issue
- ` gtk-launch com.github.wwmm.easyeffects` works if `/usr/bin/easyeffects --gapplication-service` is already running

**Comment by vchernin** [comment]
`gtk-launch com.github.wwmm.easyeffects` works for me on Fedora 35 (Gnome Wayland) without any problems.

It works even if easyeffects is not already running.

**Comment by l3s2d** [comment]
Thank you @wwmm, @vchernin for confirming that it works in Gnome. Looks like `dbus-daemon` was missing some envvars in my setup. Adding the following to my sway config has fixed the issue:
```
exec hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
```


Some related links:
1. https://github.com/NixOS/nixpkgs/issues/138956
2. https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1353
3. https://askubuntu.com/questions/1374025/sudoku-does-not-launch-from-the-application-menu-invalid-desktop-entry-file
4. https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start
