### ISSUE TITLE
Crash when changing spectrum color twice. 

### ISSUE THREAD

**Issue by OctopusET** [wwmm/easyeffects#1263]
### EasyEffects Version

6.1.4

### What package are you using?

Arch Official (easyeffects)

### Distribution

Arch Linux

### Describe the bug

After changing color, when I click spectrum color button, this program crashes.

### Expected Behavior

No crash.

### Debug Log

<details><summary>Debug Log</summary><br/>

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.953: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335780d30' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.953: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335780d30' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.953: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335780fd0' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.953: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335780fd0' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.953: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335781270' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.953: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335781270' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.954: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335781510' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.954: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x565335781510' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.954: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x5653357817b0' of type 'GtkText'

(easyeffects:5799): GLib-GObject-WARNING **: 04:18:48.954: ../glib/gobject/gsignal.c:2614: signal 'button-press-event' is invalid for instance '0x5653357817b0' of type 'GtkText'

(easyeffects:5799): Gdk-WARNING **: 04:18:48.963: Compositor doesn't support moving popups, relying on remapping
Gdk-Message: 04:18:53.210: Lost connection to Wayland compositor.
</details>

### Additional Information

I'm using wayland with swaywm. As debug log says, I guess this is protocol error.

**Comment by vchernin** [comment]
https://github.com/wwmm/easyeffects/issues/1209 also exists, with phosh which also uses wlroots. So it sounds like a bug in wlroots. Or maybe it's a mesa bug as suggested in #1209.

**Comment by OctopusET** [comment]
@vchernin Seems like it's fixed, I can't reproduce this bug.
