### ISSUE TITLE
Q: auto-bypass plugins for given program based on output device

### ISSUE THREAD

**Issue by atomGit** [wwmm/easyeffects#1264]
confusing title, i'm sure, but it's a bit of a complex problem...

Audacity is my decoder - i also have a USB AMP/DAC - what i want to do is bypass all plugins when Audacity is playing and the AMP is off, but not bypass the plugs when the AMP is on

changing presets based on the output device is of course simple, but how to change them based on the output device AND the player?

**Comment by Digitalone1** [comment]
Hello. You can add a preset for AMP off with Audacity in the blocklist.

**Comment by atomGit** [comment]
i'm not understanding how that accomplishes what i want - i can add the preset as you say, with the amp off and audacity blacklisted, but how will easyeffects automatically pipe audacity through the plugins again as soon as i turn the amp on?

maybe this isn't possible because in easy -> pipewire i already have a couple presets that auto-load based on the output device (hdmi or the amp/dac) and if i add the preset as you recommended and then apply that to the hdmi output, it just overwrites the existing hdmi preset

**Comment by atomGit** [comment]
ok, it's been a long day ... that's my excuse

1. amp off
2. blacklist audacity
3. save the preset for the desired set of plugins
