### ISSUE TITLE
immediate force close

### ISSUE THREAD

**Issue by Hagendaz989** [wwmm/easyeffects#1265]
app is currently set to start services at startup, when attempting to play audio no sound until i revert back to standard speaker output. when attempting to open app it crashes. Fedora 34 HP envy x360 AMD ryzen7

**Comment by vchernin** [comment]
What are you using instead of standard speaker output? EasyEffects sink? Because from my understanding usually it’s recommended to use your default output.

**Comment by Hagendaz989** [comment]
Laptop Speakers are my output, is when I change to pulse audio sink all my sound goes away.

Thanks,

Steven Archibald
________________________________

**Comment by wwmm** [comment]
It would be good to see some logs. Kill EE `easyeffects -q` and restart is in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`. Let's see if something interesting is shown when your audio goes away.

**Comment by ren92** [comment]
I have a similar issue when I try to adjust some settings like 'presets' I always get the error:
free(): double free detected in tcache 2

**Comment by wwmm** [comment]
@ren92 get some logs as I explain in my last message. Lots of things have changed since this issue was opened. Depending on which version you are using that problem may have already been fixed.

**Comment by ren92** [comment]
I got the message `free(): double free detected in tcache 2` by running  `G_MESSAGES_DEBUG=easyeffects easyeffects`
Every button I press in the programm causes it to crash with this message. pacman tells me I'm on version 6.1.5-2

**Comment by wwmm** [comment]
>pacman tells me I'm on version 6.1.5-2

As you are using Arch Linux you can easily upgrade to the latest version `6.2.1` or use our master branch through an AUR package.

**Comment by ren92** [comment]
So this is new for me. I'm on manjaro linux. I think I found out, that they aren't finished testing your current version of pulseeffects.
So I'm stuck with 6.1.5 for now...
