### ISSUE TITLE
Test tone is (audibly) not stable.  

### ISSUE THREAD

**Issue by nocyber** [wwmm/easyeffects#1268]
### EasyEffects Version

6.1.2

### What package are you using?

Fedora

### Distribution

Fedora 35

### Describe the bug

When the test tone is set at 1000Hz, it either plays 953Hz, 1001Hz, or 1012Hz.
The note changes:
1) over time
2) by disabling and enabling the test tone feature
3) by changing channels or toggling the signal type.

For a tone of 3000Hz, the result I got while testing is 2864, 2982, 2998, 3015, 3101.

### Expected Behavior

The tone at 1000Hz should be within 1Hz from 1000Hz.
A tone at 10 000Hz should be within 5Hz from 10 000Hz.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Yes. The algorithm currently used is super unstable. I did not have time yet to find out a better one.

**Comment by nocyber** [comment]
Clearly not a priority, but a great feature and still useful as it is.  I will look into it if I have the time.

**Comment by wwmm** [comment]
After doing some changes it is a lot better. At least on my computer. I think we can close this.
