### ISSUE TITLE
Useless repetition of Hz in spectrum

### ISSUE THREAD

**Issue by Safari77** [wwmm/easyeffects#1269]
### EasyEffects Version

6.1.5

### What package are you using?

Fedora

### Distribution

Fedora 35

### Describe the bug

It is enough to have one Hz or no Hz text at all, I guess most of the people can guess the numbers represent Hz.

![Hz](https://user-images.githubusercontent.com/3876865/143482676-e131f095-e3b7-448e-b397-f25daecc831c.png)

### Expected Behavior

Would be nice if numbers were readable.

### Additional Information

4K display on Gnome Wayland.

**Comment by wwmm** [comment]
I did not know that was how it was looking in a 4k monitor. I do not have one. Yes, that will have to be improved somehow.

**Comment by wwmm** [comment]
In the last release we started to select the amount of labels dynamically based on the widget width. Maybe on 4k monitors something is different because of the scaling.

**Comment by wwmm** [comment]
Fixed in the latest master. And at least for now the number of labels is fixed at 10.
![Screenshot from 2021-12-18 12-19-59](https://user-images.githubusercontent.com/16225172/146646264-a349c9c7-f447-48e3-816b-c41af7d83043.png)
