### ISSUE TITLE
Opening "Presets" breaks gnome

### ISSUE THREAD

**Issue by EmmanuelMess** [wwmm/easyeffects#1270]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04

### Describe the bug

After opening presets doesn't let me click on anything of gnome, its like it eats up all the click events everywhere.

### Expected Behavior

I should be able to click anywhere else and the presets window should either close or stay open.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
There is a discussion about this on #1182 and #1179. It is a gtk4 bug that has already been reported to them. So far it seems to happen only to Xorg users.
