### ISSUE TITLE
APO import does not ignore commas in common generated APO files

### ISSUE THREAD

**Issue by garrett** [wwmm/easyeffects#1271]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

Importing APO files does not always work properly.

After playing around with the source APO to import, I realized the fields not importing properly all had commas. After removing the commas in the file, I could load it just fine. However, many distributed APO files have commas for some frequencies and these are expected to work by default.

### Expected Behavior

APO files to correct speakers and headphines from sources such as noaudiophile.com should work as-is.

### Additional Information

The file I've tried to import was for my AudioGalaxy A2 speakers. (They're not the A2+, but the speaker setup is the same.)

When loading this file, only half the bands show up, as commas are used for Hz:
http://noaudiophile.com/AudioEngine_A2_Plus/AudioEngine_A2_Plus.txt

The corrected file, with commas removed, is [AudioEngine_A2_Plus.txt](https://github.com/wwmm/easyeffects/files/7610167/AudioEngine_A2_Plus.txt) and looks like this after being imported:

![Screenshot from 2021-11-26 18-43-35](https://user-images.githubusercontent.com/10246/143616450-33f386f5-143e-4180-9835-52c04750b4e1.png)

Thanks so much for EasyEffects! It's awesome.

**Comment by Digitalone1** [comment]
I will update the regex to handle commas.
