### ISSUE TITLE
"Start service at login" does not work

### ISSUE THREAD

**Issue by forteller** [wwmm/easyeffects#1279]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 21.10

### Describe the bug

After turning on "Start service at login" in the hamburger menu the service does not start automatically on boot. But the slider still says that the setting is turned on.

At least I'm pretty sure about that since I can't set EE Source as my input device until I run EE manually after a reboot. I've tested many times.

### Expected Behavior

I should not have to run EasyEffects manually on each boot after turning on the setting "start service at login" for the service to run in the background and let me use the EasyEffects Source as input device.

### Debug Log

Sorry, I don't know how to launch EE from terminal. Typing easyeffects and pressing enter just gives me "command not found". So I don't know how to do this.

### Additional Information

Thank you so much for this fantastic service! The noise reduction is a lifesaver, and should be built in by default.

**Comment by vchernin** [comment]
> After turning on "Start service at login" in the hamburger menu the service does not start automatically on boot. But the slider still says that the setting is turned on.

Did you get a permission prompt asking if EasyEffects can run in the background?

**Comment by forteller** [comment]
No, I did not

**Comment by vchernin** [comment]
Can you run `flatpak permission-reset com.github.wwmm.easyeffects`, restart EasyEffects, and then try disable and enable the switch.

**Comment by forteller** [comment]
Ah, yes! Now I got the prompt (on turning off the switch, actually), and it did start up on reboot! Thank you!

I guess the real bug then is that the prompt doesn't always show up. I tried turning the setting off and on again multiple times, and the prompt never came until I did that permission-reset.

**Comment by vchernin** [comment]
> I guess the real bug then is that the prompt doesn't always show up.

Yeah, there are some rather confusing situations that happen currently. The switch should not be possible to have enabled if the permission isn't granted.

Some more sanity checks by EasyEffects will help, which is mostly what https://github.com/wwmm/easyeffects/issues/1249 is about, to ensure EasyEffects isn't assuming permissions incorrectly and showing incorrect settings to the user (i.e. saying autostart is enabled when it's not).

**Comment by forteller** [comment]
Ok, so you're already on it then, I see. That's great! Thanks a lot!
