### ISSUE TITLE
"Reset all settings" does nothing

### ISSUE THREAD

**Issue by forteller** [wwmm/easyeffects#1280]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 21.10

### Describe the bug

Clicking "Reset all settings" in the hamburger menu does nothing. I've tried changing all the settings, and no matter what, nothing changes when I press the button.

### Expected Behavior

All settings should be reset to default :)

### Debug Log

Still don't know how to do this :) I'm happy to add it if you need it and you tell me how.

### Additional Information

Thanks again!

**Comment by vchernin** [comment]
https://github.com/flathub/com.github.wwmm.easyeffects/issues/4

**Comment by forteller** [comment]
Ah, thanks!
