### ISSUE TITLE
Equalizer Issue: On Load APO Preset, if filter type not PK, filter type is set to PK and Q to zero

### ISSUE THREAD

**Issue by DePingus** [wwmm/easyeffects#1283]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

When loading an APO preset from a file, if the filter type is not PK, EasyEffects will make it PK and set Q to zero.

Here is an example APO where filter 1 and 10 are not PK:
```
Preamp: -5.0 dB
Filter 1: ON LS Fc 28 Hz Gain 5.0 dB Q 0.62
Filter 2: ON PK Fc 122 Hz Gain -2.1 dB Q 1.03
Filter 3: ON PK Fc 577 Hz Gain 1.3 dB Q 1.54
Filter 4: ON PK Fc 2131 Hz Gain 4.2 dB Q 3.56
Filter 5: ON PK Fc 2881 Hz Gain -0.9 dB Q 8.8
Filter 6: ON PK Fc 4070 Hz Gain -0.9 dB Q 8.03
Filter 7: ON PK Fc 5539 Hz Gain -6.8 dB Q 3.14
Filter 8: ON PK Fc 6883 Hz Gain 1.3 dB Q 5.6
Filter 9: ON PK Fc 7615 Hz Gain -1.0 dB Q 5.43
Filter 10: ON HS Fc 10894 Hz Gain -1.4 dB Q 4.0
```
If I load that preset, what I get in EasyEffects is:
```
Preamp: -5.0 dB
Filter 1: ON PK Fc 28 Hz Gain 5.0 dB Q 0.00
Filter 2: ON PK Fc 122 Hz Gain -2.1 dB Q 1.03
Filter 3: ON PK Fc 577 Hz Gain 1.3 dB Q 1.54
Filter 4: ON PK Fc 2131 Hz Gain 4.2 dB Q 3.56
Filter 5: ON PK Fc 2881 Hz Gain -0.9 dB Q 8.8
Filter 6: ON PK Fc 4070 Hz Gain -0.9 dB Q 8.03
Filter 7: ON PK Fc 5539 Hz Gain -6.8 dB Q 3.14
Filter 8: ON PK Fc 6883 Hz Gain 1.3 dB Q 5.6
Filter 9: ON PK Fc 7615 Hz Gain -1.0 dB Q 5.43
Filter 10: ON PK Fc 10894 Hz Gain -1.4 dB Q 0.00
```

### Expected Behavior

The filter type and Q value should be set to what the imported file states.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by bhack** [comment]
We have some issue in the regex for the filter type:

https://github.com/wwmm/easyeffects/blob/41e83c9ce40b5fae794c01c0b1b7589b53cc60b7/src/equalizer_ui.cpp#L619-L636

As the current regex will not match your case. 

I don't know if we want to be case insensitive with `std::regex_constants::icase` or change the current regex as I don't know if this format is standardized or not.

**Comment by bhack** [comment]
Sorry I see that `i = std::regex::icase` so we are already working with `icase`. The regex is correct

**Comment by bhack** [comment]
I don't know if I read this correctly just a give only an on the fly pass but it seems that in the loop we are putting the filter always type to `Bell`:

https://github.com/wwmm/easyeffects/blob/41e83c9ce40b5fae794c01c0b1b7589b53cc60b7/src/equalizer_ui.cpp#L742-L762

Also it  seems to me that we have `Q` to `0.0` as it is set only for `ALL_PASS` and `PEAK`

https://github.com/wwmm/easyeffects/blob/41e83c9ce40b5fae794c01c0b1b7589b53cc60b7/src/equalizer_ui.cpp#L685-L691

The label mapping is at:
https://github.com/wwmm/easyeffects/blob/41e83c9ce40b5fae794c01c0b1b7589b53cc60b7/include/equalizer_ui.hpp#L112-L117

**Comment by wwmm** [comment]
@Digitalone1 was the last one working on the regex and can explain it better. But have in mind that support for APO presets is severely limited. I doubt it will ever be 100% compatible. It is super annoying to parse its format. And as I do not use APO presets I can't offer much help.

**Comment by bhack** [comment]
Yes it is annoying but it is still a quite popular use case for Headphone users with https://github.com/jaakkopasanen/AutoEq

I think that the regex is ok. I've put some note in the previous comment.

**Comment by Digitalone1** [comment]
Yes, the filter is always set to Bell, I didn't notice it. 

The issue should be not saving the Q value when the filter is different than peak and allpass. 

@bhack I'm more into regex than APO equalizer, can you check if the filter map is correct? When I have time, I try to fix the code.

**Comment by wwmm** [comment]
The first issue about apo preset importing can be read in #588. The person who started this work also linked some apo documentation that may help https://sourceforge.net/p/equalizerapo/wiki/Configuration%20reference/#filter.

**Comment by bhack** [comment]
If we check again @wwmm soruceforge link to the filter table we can see that the simbol `O` means optional. 
So we need to take `Q` for all the filters but in some filter we could have the missing `Q` string as It Is optional.

**Comment by Digitalone1** [comment]
> If we check again @wwmm soruceforge link to the filter table we can see that the symbol `O` means optional. So we need to take `Q` for all the filters but in some filter we could have the missing `Q` string as It Is optional.

I see. I'ts only optional for some filters, but checking it against filters which requires it is overkill. I suggest parsing it, if we get the value, then we copy it, otherwise the default is used.

So I'd change the map as the following (with the corresponding gsettings key reported):

```
{"PK", FilterType::BELL} => Bell
{"MODAL", FilterType::BELL} => Bell
{"PEQ", FilterType::BELL} => Bell
{"LP", FilterType::LOW_PASS} => Lo-pass
{"LPQ", FilterType::LOW_PASS} => Lo-pass
{"HP", FilterType::HIGH_PASS} => Hi-pass
{"HPQ", FilterType::HIGH_PASS}  => Hi-pass
{"BP", FilterType::BAND_PASS} => ???
{"LS", FilterType::LOW_SHELF} => Lo-shelf
{"LSC", FilterType::LOW_SHELF} => Lo-shelf
{"HS", FilterType::HIGH_SHELF} => Hi-shelf
{"HSC", FilterType::HIGH_SHELF}  => Hi-shelf
{"NO", FilterType::NOTCH}  => Notch
{"AP", FilterType::ALL_PASS}} => Allpass
```

But does it seem band pass mode is missing on our side? Maybe it's **Resonance** on LSP Eq?

**Comment by wwmm** [comment]
>Maybe it's Resonance on LSP Eq?

It does not seem to be. According to its docs https://lsp-plug.in/?page=manuals&section=para_equalizer_x32_lr
```
Resonance filter with high Quality Factor can be good choice to cut annoying masking resonances from the original sound.

Resonance - Resonance filter wih sharp peak/recess.
```

It seems to be a filter to remove resonances from the audio content.  A band pass will just filter a frequency region between a min and a max value. We have one in the Calf filter plugin we already use but it does not look like there is one in the lsp equalizer.

**Comment by wwmm** [comment]
>It seems to be a filter to remove resonances from the audio content.

Or maybe also boost a narrow reagion https://www.youtube.com/watch?v=XA_WnyA7D6k. In any case it does not seem it can be used as a band-pass.

**Comment by bhack** [comment]
Is It this https://github.com/sadko4u/lsp-plugins/issues/75 ?

**Comment by wwmm** [comment]
>Is It this sadko4u/lsp-plugins#75 ?

This seems something specific to the sidechain filters used in some plugins. I would expect the equalizer docs to mention a band pass filter if it had one.

**Comment by bhack** [comment]
So I suppose It Is not available in the equalizer. /cc @sadko4u

**Comment by sadko4u** [comment]
LSP Plugins have their own mechanism of importing APO settings obtained from RoomEqWizard.
Here's the source:

https://github.com/sadko4u/lsp-plugins/blob/d78befc2faaa6de64050c3c4b662dea429e47c40/src/ui/plugins/para_equalizer_ui.cpp#L240-L355

You can refer this code when writing your own configuration file parser.

**Comment by bhack** [comment]
Thank you, also there we don't have the `BP` filter type in the case condition and It is going to skip all the filters not in the case list.

**Comment by Digitalone1** [comment]
That's nice @sadko4u, I'll try to do something similar, it shouldn't be so much difficult with the code we already have.

**Comment by Digitalone1** [comment]
I'm trying to improve the code. Unfortunately it's not quite good at the moment. In the past I didn't give so much look at it checking only the regexes.

The first thing I noticed is that we have the slope in the structure, we also parse the string line for it and eventually pick the value, but it's never applied. I think it's also useless since neither lsp parsing function is checking it, the value defaults at **x1** for all bands. We should do the same.

**Comment by Digitalone1** [comment]
Okay, I managed to do a better parser for applying the correct filters and the proper parameters as it's done in LSP code posted above.

In the next days I should be able to make the MR.

**Comment by wwmm** [comment]
>In the next days I should be able to make the MR.

Ok. If possible to the MR to the libadwaita branch. I have already removed gtkmm from the equalizer interface 
https://github.com/wwmm/easyeffects/blob/libadwaita/src/equalizer_ui.cpp. If not possible just wait a little more before doing the MR. There only 2 more plugins needing work in the libadwaita branch. The multiband compressor and the multiband gate. After that it will be just a matter of removing gtkmm from the dependencies and moving libadwaita to master.

**Comment by Digitalone1** [comment]
@wwmm Okay, I ported the changes into the libadwaita branch.

I will make the MR.

**Comment by Digitalone1** [comment]
So, I followed what is done here: https://github.com/sadko4u/lsp-plugins/blob/d78befc2faaa6de64050c3c4b662dea429e47c40/src/ui/plugins/para_equalizer_ui.cpp#L240-L355

First the quality defaults to `1/sqrt(2)`, then it's updated if it's specified in the APO config. An exception is done for `LS/HS 6db` filters which do not specify a quality, but LSP sets custom different values. 

Simple `LS/HS` filters could specify a quality value, but LSP ignores it setting another custom value. It's done also for `LSC/HSC` that seems not covered by LSP. Anyway I parsed the config for quality and overwrite it if there is the regex match, otherwise the LSP custom value is used.

About the frequency, it's interesting what happens to `LS/HS 6db/12db` filters. A new frequency is calculated taking the parsed frequency from the APO config. Don't know why, there should be a reason, anyway this could confuse some users since the frequency is different from the one specified inside the config file.

@sadko4u any thought or suggestion on this?

**Comment by bhack** [comment]
I don't know if `AutoEq` uses some of these uncovered APO features but @jaakkopasanen could be interested in this.

**Comment by Digitalone1** [comment]
Maybe the mode should be set as `APO` for all the selected bands during the import feature.

https://lsp-plug.in/?page=manuals&section=para_equalizer_x32_lr

> Mode APO - Digital biquad filters derived from canonic analog biquad prototypes digitalized through Bilinear transform. These are [textbook filters](https://shepazu.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html) which are implemented as in the [EqualizerAPO](https://equalizerapo.com/) software.

@wwmm what do you think?

**Comment by wwmm** [comment]
>what do you think?

Isn't this already done?

**Comment by wwmm** [comment]
I see. It used to be done in the past https://github.com/wwmm/easyeffects/blob/57cd192f7a09ed03daaa34c8493d13c1275777e7/src/equalizer_ui.cpp#L740 but it isn't in the latest import implementation. Yes, that has to be done.

**Comment by Digitalone1** [comment]
@wwmm No, I reset it for all bands. My mistake.

https://github.com/wwmm/easyeffects/blob/master/src/equalizer_ui.cpp#L336-L356

And I didn't notice this:

https://github.com/sadko4u/lsp-plugins/blob/d78befc2faaa6de64050c3c4b662dea429e47c40/src/ui/plugins/para_equalizer_ui.cpp#L255

Should be changed as

```c++
for (int n = 0, apo_bands = static_cast<int>(bands.size()); n < max_bands; n++) {
    for (auto* channel : settings_channels) {
      if (n < apo_bands) {
        g_settings_set_string(channel, band_type[n], bands[n].type.c_str());
        g_settings_set_string(channel, band_mode[n], "APO (DR)");
        g_settings_set_double(channel, band_frequency[n], bands[n].freq);
        g_settings_set_double(channel, band_gain[n], bands[n].gain);
        g_settings_set_double(channel, band_q[n], bands[n].quality);
      } else {
        g_settings_set_string(channel, band_type[n], "Off");
        g_settings_reset(channel, band_mode[n]);
        g_settings_reset(channel, band_frequency[n]);
        g_settings_reset(channel, band_gain[n]);
        g_settings_reset(channel, band_q[n]);
      }

      g_settings_reset(channel, band_slope[n]);
      g_settings_reset(channel, band_solo[n]);
      g_settings_reset(channel, band_mute[n]);
    }
  }
}
```

Can you do it when you can @wwmm?

**Comment by wwmm** [comment]
>Can you do it when you can?

Yes.

**Comment by polygonalenippel** [comment]
Hi, author of the first APO merge here.
I agree the regex was written to barely function with the output of AutoEQ, glad to see it is getting wider support.
Are there any updates?

**Comment by Digitalone1** [comment]
@polygonalenippel the latest was merged and released with 6.2.0

**Comment by bhack** [comment]
Can we close this?

**Comment by Digitalone1** [comment]
If there's nothing else to do, yes.
