### ISSUE TITLE
Open preset window prevents interacting with anything other than EasyEffects

### ISSUE THREAD

**Issue by iwishiwasaneagle** [wwmm/easyeffects#1287]
### EasyEffects Version

6.1.4

### What package are you using?

Arch Official (easyeffects)

### Distribution

Manjaro Linux

### Describe the bug

When the preset window is open and focused, if I click anywhere else then all interaction with any other windows are blocked. Hover animations only seem to work in EasyEffects, but even buttons within EE are blocked.

https://streamable.com/r9bcxn

### Expected Behavior

Preset window should close when other areas of the screen are clicked.

### Debug Log

Nothing to show

**Comment by wwmm** [comment]
It is a gtk4 bug that seems to affect everyone on Xorg but not people on Wayland. We are tracking it on #1179.
