### ISSUE TITLE
Effects spontaneously get disabled for a fraction of a second when starting or stopping any media in Firefox

### ISSUE THREAD

**Issue by magicgoose** [wwmm/easyeffects#1290]
### EasyEffects Version

6.1.5

### What package are you using?

Arch Official (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Often, when I play music from Strawberry player (a fork of Clementine), it would enter a state, when each media start/stop in Firefox would immediately cause easyeffects to bypass output effects for a fraction of a second. When it happens, it keeps being reproduceable 100% of times until I end the music playback session in Strawberry. Oddly, it doesn't matter if a tab is muted in Firefox -- it affects Easyeffects anyway.

I'm using the following effects:
* Convolver
* Limiter

### Expected Behavior

Easyeffects keep processing effects at all times when enabled

### Debug Log

<details><summary>Debug Log</summary><br/>
Will capture and add, if they can help in such a case
</details>

### Additional Information

DE is KDE
Using linux-zen kernel (because it glitches less often during heavy I/O background load)

**Comment by magicgoose** [comment]
Might be similar to https://github.com/wwmm/easyeffects/issues/1213

**Comment by magicgoose** [comment]
and https://github.com/wwmm/easyeffects/issues/1175
yeah, that must be it.
should I close this one, if you all don't see anything new in this report?

**Comment by magicgoose** [comment]
The workaround with fixed buffer size also seems to fix the problem:
```
pw-metadata -n settings 0 clock.force-quantum 4096
```
by the way, if I try the same with 8192, it's unusable -- skipping a lot -- while theoretically it should be even more stable? Not sure if it's related to easyeffects, and I guess I don't need it anyway, just an observation.

**Comment by wwmm** [comment]
>should I close this one, if you all don't see anything new in this report?

We can close this one. It is the same problem. It will be fixed for LV2 plugins in the next release but our convolver will reset its internal state when PipeWire switches latency. I am not sure about how to fix it there yet.

>by the way, if I try the same with 8192, it's unusable -- skipping a lot -- while theoretically it should be even more stable?

It is strange that it gets worse when the buffer size is forced to 4096. As long as the latency does not change it should not make a difference. Stability should be the same. Maybe something unusual is happening somewhere with 8192. But it is hard to say where. It may not even be on EasyEffects. I do not remember having problems when the buffer size is 8192.
