### ISSUE TITLE
Can't dismiss presets menu after opening emoji selector.

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1291]
### EasyEffects Version

6.1.5 (also libadwaita branch)

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

When entering text after opening the add presets menu, you are able to insert an emoji in either text field with the GTK emoji chooser. However, if you open and then dismiss the insert emoji panel, the menu will become locked up. You can't click on the application to dismiss it, unlike normally.

This does not require actually adding an emoji, just opening and closing the insert emoji menu while entering text.

![Screenshot from 2021-12-13 17-11-42](https://user-images.githubusercontent.com/38842733/145914802-5051c963-32a8-4905-8686-12cac8f03bc3.png)

### Expected Behavior

Behave correctly and not lock up, like it does without activing the insert emoji panel. This is on Wayland, so probably not the same as those Xorg bugs (but similar).

This is probably best forwarded to GTK, I haven't reproduced with another app, but it's probably related to the widget setup or something.

If you're wondering how I found this, I accidentally opened the emoij selector when clicking then tried to dismiss it.

### Additional Information

I find entering and closing the activities overview in gnome seems to dismiss this.

**Comment by wwmm** [comment]
>If you're wondering how I found this, I accidentally opened the emoij selector when clicking then tried to dismiss it.

I am still wondering because I do not know which program is this `emoji selector` :smile:. What I have on my computer is the `Characters` program and I did not see an "insert menu". I had to copy and paste the emoji
![Screenshot from 2021-12-14 10-56-49](https://user-images.githubusercontent.com/16225172/146012579-7cd7965e-6cd3-4361-bc02-ec65b6656513.png)
And as expected the menu did not get stuck. So the problem is not the emoji but how the program you are using is inserting it.

**Comment by wwmm** [comment]
>This is probably best forwarded to GTK

I agree. The most we could do would be trying to ignore emojis. Assuming that is even possible. But they are not the problem.

**Comment by vchernin** [comment]
Oh, I was referring to the built-in GTK insert emoji button, not a seperate application.

![Screenshot from 2021-12-14 18-25-29](https://user-images.githubusercontent.com/38842733/146111660-faabd1ed-1422-4d12-ad7d-e68f21875239.png)

If you are entering text you can show that menu by right clicking. Then you can open and close the insert emoji menu. Doing so causes the bug.

It happens regardless of entering emojis or not, it happens due to simply opening and closing the GTK emoji menu.

**Comment by wwmm** [comment]
This particular bug has already been reported to the gtk develoers by another person https://gitlab.gnome.org/GNOME/gtk/-/issues/4529

**Comment by vchernin** [comment]
Upstream issue so closing
