### ISSUE TITLE
Extend metainfo update script to add changelogs

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1295]
While browsing through the files I realized there's been a script to update metainfo/appdata for a while. https://github.com/wwmm/easyeffects/commit/04bd3e968f7e0ba79b9672882590affe445dc330

I'd like to extend this to also add the changelog to the metainfo file. This means users could see the changelog in gnome software, kde discover etc.

Not sure how easy it would be to parse the changelog markdown though, but it's hopefully reasonable. Other formats than markdown might be worth exploring.

Related https://blog.tenstral.net/2020/03/maintain-release-info-easily-in-metainfo-files.html

Edit: see also: https://gitlab.gnome.org/GNOME/gnome-break-timer/-/commit/fe967bbf7d9e8955c1d915c7df898d990e0cbaa8

**Comment by wwmm** [comment]
>Not sure how easy it would be to parse the changelog markdown though,

I think there is a change `appstreamcli` will be able to handle our changelog. Its structure is similar to the one mentioned in your link.

>Other formats than markdown might be worth exploring.

Maybe the yaml. But somehow the markdown seems visually better when looking at the changelog file.

**Comment by vchernin** [comment]
So it seems from testing the yaml release notes format doesn't currently support paragraphs with bullet points currently. But the news file seems to work.

I was thinking maybe a script could convert news to markdown (leaving news as the canonical format). It shouldn't be too difficult. 

But I had a different idea when I looked at the appstream release notes. The following which is generated in the appstream file by `appstreamcli news-to-metainfo`.
```
        <p>This release adds the following features:</p>
        <ul>
          <li>Now plays a "zap" sound on every character input</li>
          <li>new thing</li>
        </ul>
        <p>This release fixes the following bugs:</p>
        <ul>
          <li>The CPU no longer overheats when you hold down spacebar</li>
          <li>new fix </li>
        </ul>
```
Can be directly pasted into github which gives:

 <p>This release adds the following features:</p>
        <ul>
          <li>Now plays a "zap" sound on every character input</li>
          <li>new thing</li>
        </ul>
        <p>This release fixes the following bugs:</p>
        <ul>
          <li>The CPU no longer overheats when you hold down spacebar</li>
          <li>new fix </li>
        </ul>

So actually it sounds fairly doable to use news as the central information store, convert that to apptream and then create a markdown changelog file out of that, since the appstream is just a bunch of text tags. If you'd like I could try that (or maybe wait to see if the yaml format can be fixed).

**Comment by wwmm** [comment]
>So actually it sounds fairly doable to use news as the central information store, convert that to apptream and then create a markdown changelog file out of that, since the appstream is just a bunch of text tags. If you'd like I could try that

I am not sure I understand. Would our current changelog file stay as it is? Or would it have to be manually written as an html file?

**Comment by vchernin** [comment]
> I am not sure I understand. Would our current changelog file stay as it is? 

From users perspectives yes (mostly).

> Or would it have to be manually written as an html file

No, it's just auto converted from the news file by the script.

News is the only one you need to manually edit.

Both the markdown changelog file and metainfo file are generated from the news file. The markdown file does not look significantly different from before (see the PR diff).

The idea is every time one would make a release, you'd update both the changelog and metainfo file at once.

**Comment by wwmm** [comment]
>Both the markdown changelog file and metainfo file are generated from the news file. The markdown file does not look significantly different from before (see the PR diff).

Oh! Now I see. The NEWS file is really similar to the changelog we write by hand now. I guess it is fine to edit it manually and generate the others from it.
