### ISSUE TITLE
EasyEffects stops working after resuming from suspend

### ISSUE THREAD

**Issue by C43H66N12O12S2** [wwmm/easyeffects#1304]
### EasyEffects Version

6.1.5

### What package are you using?

Arch Official (easyeffects)

### Distribution

Arch Linux

### Describe the bug

EasyEffects completely stops working (but does not crash or stop running) after resuming from suspend. Restarting easyeffects fixes it. I'm using Pipewire and wireplumber.

`journalctl --user -b -u easyeffects` doesn't give anything useful.

Happy to provide any other information that could help with this. 

### Expected Behavior

EasyEffects to continue applying filters & effects after resume.

**Comment by wwmm** [comment]
Same thing as #1083. The cause is still unknown and there is a high chance fixes are needed on the audio server too. Since when we used Pulseaudio some people have problems with suspending. And to make things worse they do not happen on some computers like the one I have. So hardware seems to matter somehow.

I suggest you add a post on #1083 with the image generated by `pw-dot`. You can view the generated file with the command `xdot`. This way we will know if the links were broken after returning from suspending.

**Comment by C43H66N12O12S2** [comment]
I'm not sure if this is the same. People there report audio as missing, my audio works after resuming but EasyEffects filters don't apply. (so, audio is completely fine, but there's no EQ or pregain)

FWIW, when I used EasyEffects before on another install of Arch (3 months or so), I didn't have this issue, and my hardware & software is exactly the same between the two installs. The only difference is the newer kernel versions, and wireplumber instead of pipewire-media-session.

**Comment by wwmm** [comment]
>I'm not sure if this is the same. People there report audio as missing, my audio works after resuming but EasyEffects filters don't apply. (so, audio is completely fine, but there's no EQ or pregain)

So in your case is it like having a bypass turned on? In that cases it is different. Although I do not see how such a thing could be happening.

**Comment by wwmm** [comment]
Maybe a small video showing what is happening would help to clarify the situation. And the `pw-dot` image

**Comment by C43H66N12O12S2** [comment]
[pw.zip](https://github.com/wwmm/easyeffects/files/7775949/pw.zip)
I'm not sure what kind of video would be useful. There's nothing at all broken or different after resuming. It is truly like EasyEffects was never running in the first place after resuming.

One difference between when I didn't have this issue is that I'm using btrfs now. Seems like a reach to blame the fs, but one other user on the different issue reported the issue began with Fedora 33, when btrfs became default there, so maybe?

**Comment by wwmm** [comment]
So in your cases what is happening is that our links are not being remade after resuming
![Screenshot from 2021-12-25 12-07-41](https://user-images.githubusercontent.com/16225172/147387960-6f58ff8b-5ca7-4e05-854c-9d4e52319d0c.png)
I wonder if PipeWire is moving your applications away from our virtual device after resuming. This could explain why our filters and devices are loaded but there is no link between them. We only link our filters if something is playing to our virtual device.

**Comment by wwmm** [comment]
If you manually enable/disable the application switch in our `Players` tab do effects work again?

**Comment by wwmm** [comment]
> Seems like a reach to blame the fs, but one other user on the different issue reported the issue began with Fedora 33, when btrfs became default there, so maybe?

I am more inclined to believe that `Wireplumber` is the reason. At least on Arch Linux is easy to switch from WirePlumber to the built-in PipeWire media session. This is something you can try. WirePlumber still needs some polishing.

**Comment by C43H66N12O12S2** [comment]
Wireplumber was indeed the issue. I've tried pipewire-media-session and the issue is fixed. Thank you very much for your help.

Additional detail if it'll help the development process: With wireplumber, after resuming, the application switches would return as toggled off. I haven't noticed this until now due to using easyeffects with `--gapplication-service`.

**Comment by wwmm** [comment]
I suggest you open an issue at https://gitlab.com/pipewire/wireplumber. In almost all of the cases where something works with the built-in session manager but it doesn't with WirePlumber it is a WirePlumber bug. As WirePlumber is supposed to replace the built-in manager in the future these issues have to be reported to them so they are fixed.

**Comment by wwmm** [comment]
Wrong link. I think this is the correct one https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues

**Comment by 1player** [comment]
This is still happening for me on Fedora 35. I've opened a bug on wireplumber's bug tracker myself, I don't think @C43H66N12O12S2 did, or at least I could not find it.

https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/180

**Comment by HasinduLanka** [comment]
I solved this issue by creating file : `/lib/systemd/system-sleep/easyeffects`

with content : 

```sh
#!/bin/sh

# easyeffects - systemd suspend/resume hook

case $1 in
    pre)  pkill easyeffects ;;
    post) easyeffects --gapplication-service  ;;
esac
```

This will kill `easyeffects` process just before your laptop goes to sleep, and start it again when resuming from sleep.

My device info : 

```
Desktop: KDE Plasma 5.23.5 Distro: Manjaro Linux
Sound Server-1: ALSA v: k5.15.16-1-MANJARO running: yes
Sound Server-2: PipeWire v: 0.3.43 running: yes
```

**Comment by wwmm** [comment]
@HasinduLanka Which EE version are you using? Some of the problems a few users were having when suspending their computers were fixed in the latest EE reelase `6.2.3`

**Comment by HasinduLanka** [comment]
> @HasinduLanka Which EE version are you using? Some of the problems a few users were having when suspending their computers were fixed in the latest EE reelase `6.2.3`

I'm using EE `6.2.3` from AUR git package. I tried the official release too.
BTW, I'm using `Manjaro KDE + Wayland`

![2022-02-05_20-08](https://user-images.githubusercontent.com/35098511/152646432-d58aa9eb-b1b3-4c5e-9565-fab8bd56d6d2.png)

![2022-02-05_20-09](https://user-images.githubusercontent.com/35098511/152646435-621ab1b9-caf1-4149-ad46-cc536e146a07.png)

**Comment by emanuelserpa** [comment]
I'm having the same problem on Arch Linux too. I'm using 6.2.3. No Wireplumber.

**Comment by wwmm** [comment]
>After resuming, all applications change to "unknown source" instead of "EasyEffects Sink"

@emanuelserpa if our virtual sink is still loaded after resuming but the applications are associated to an `unknown source` it may be a PipeWire bug. In the cases where the problem seemed to be on our side that is not what happened.

**Comment by emanuelserpa** [comment]
Curious to know if @HasinduLanka is having the same problem. It's just changing "unknown source" to "EasyEffects Sink".

The problem is when I have too many apps using sound.
![image](https://user-images.githubusercontent.com/934124/152722188-ebfd551e-67ef-4743-8465-dd5d21407385.png)

**Comment by wwmm** [comment]
@emanuelserpa the next time this happens run `pw-dot`. The output file can be viewed with `xdot`.

**Comment by emanuelserpa** [comment]
> @emanuelserpa the next time this happens run `pw-dot`. The output file can be viewed with `xdot`.

Already did when it happened, but I don't know how to interpret it.

[pw.dot.txt](https://github.com/wwmm/easyeffects/files/8012385/pw.dot.txt)

**Comment by wwmm** [comment]
>Already did when it happened, but I don't know how to interpret it.

I forgot to tell you to put your audio player in the "playing state". In your current dot file there is no link between filters or between the audio player and a sink.

**Comment by emanuelserpa** [comment]
Seems like I found a pattern. When the app doesn't use native pipewire (and uses pulse compatibility mode) it can't "find" the way back to the sink and keeps with the `unknown source` and don't play anything.

Verified with MPV, it just didn't play after resume, but when I used the pipewire native output it just plays fine after doing it.

Here in this pw.dot, mpv and firefox can play sounds after the resume, but spotify (that uses pulse/alsa) can't "connect" with the output and I have to do it manually. Note that this only happens when EasyEffects is running, but I think that this is something with PW indeed.

[pw.dot.txt](https://github.com/wwmm/easyeffects/files/8012709/pw.dot.txt)

**Comment by wwmm** [comment]
The pw-dot output shows that mpv and firefox have links to our virtual device but Spotify does not have any link any all. That is the reason for the ` unknown source` in Pavucontrol. EasyEffects is able to move an app to its devices or move them back to the default. But destroying an applications links is something it can not do. We only do that to our filters links. Sounds like an unusual PipeWire behavior indeed.

**Comment by 1nikolas** [comment]
> I solved this issue by creating file : `/lib/systemd/system-sleep/easyeffects`
> 
> with content :
> 
> ```shell
> #!/bin/sh
> 
> # easyeffects - systemd suspend/resume hook
> 
> case $1 in
>     pre)  pkill easyeffects ;;
>     post) easyeffects --gapplication-service  ;;
> esac
> ```
> 
> This will kill `easyeffects` process just before your laptop goes to sleep, and start it again when resuming from sleep.
> 
> My device info :
> 
> ```
> Desktop: KDE Plasma 5.23.5 Distro: Manjaro Linux
> Sound Server-1: ALSA v: k5.15.16-1-MANJARO running: yes
> Sound Server-2: PipeWire v: 0.3.43 running: yes
> ```

Unfortunately this doesn't work because it tries to run easyeffects as root (which can't open gui apps)

```
Jul 26 02:34:24 archlinux systemd[1]: Starting System Suspend...
Jul 26 02:34:24 archlinux [80182]: /usr/lib/systemd/system-sleep/easyeffects terminated by signal TERM.
Jul 26 02:34:24 archlinux systemd-sleep[80181]: Entering sleep state 'suspend'...
Jul 26 02:34:31 archlinux systemd-sleep[80181]: System returned from sleep state.
Jul 26 02:34:31 archlinux easyeffects[80339]: cannot open display: 
Jul 26 02:34:31 archlinux [80328]: /usr/lib/systemd/system-sleep/easyeffects failed with exit status 1.
Jul 26 02:34:31 archlinux systemd[1]: systemd-suspend.service: Deactivated successfully.
```

And even if I use `su <username> -c "DISPLAY=:0 easyeffects --gapplication-service" ;;` I just get this error
```
Jul 26 02:42:11 archlinux easyeffects[81448]:         pipe_manager.cpp:1429        context connection failed
```

**Comment by 1player** [comment]
I honestly don't have this problem anymore on Fedora.

**Comment by chrisco23** [comment]
I know this is old but I switched from i3 / x11 to sway / Wayland in recent days and this is happening constantly to me since.  Was any progress ever made?

easyeffects 7.1.3-1
easyeffects-preset 0.3.0-1
arch linux 6.6.1-arch1-1
wireplumber
Compiled with libwireplumber 0.4.15
Linked with libwireplumber 0.4.15

**Comment by 1player** [comment]
Yes this has been happening to me this summer (I think I commented on another similar issue), then it got fixed, and I had it happen sporadically a couple times in the past week, but not always. Not sure what causes it.

I just got the latest pipewire update this morning, might be worth checking out if that fixes it.

**Comment by wwmm** [comment]
>Was any progress ever made?

Not from our side. I do not see what could be done in EasyEffects to change this. As long as PipeWire does not die during the process EasyEffects should be fine. But if pipewire is dying or being restarted during the computer suspension EasyEffects has to be manually restarted.

This feels like some kind of problem happening at the audio server or driver level. PulseEffects suffered from the same issue on Pulseaudio and its code is completely different from the one in EasyEffects. What is bizarre is how this bug is dependent on the hardware. I was never able to see it happening on my computers. Both on Pulseaudio and PipeWire.
