### ISSUE TITLE
EasyEffects 6.2.0 crashes with invalid pointer if equalizer Q is 0

### ISSUE THREAD

**Issue by Userwithaname** [wwmm/easyeffects#1314]
### EasyEffects Version

6.2.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

When setting a band's "Quality" value in the equalizer to 0, EasyEffects crashes (`munmap_chunk(): invalid pointer`).

When EasyEffects remembers the 0 Q value (reproducible by loading an affected preset file (see attachment)), the application crashes on startup, and the only way to fix it is by manually editing or removing the configuration file (`[...]/config/glib-2.0/settings/keyfile`).

Note that older versions are not affected by this issue.

[CausesCrash.json.txt](https://github.com/wwmm/easyeffects/files/7812018/CausesCrash.json.txt)

### Expected Behavior

EasyEffects either disallows setting Q to 0, or otherwise bypasses the crash

### Debug Log

<details><summary>Debug Log</summary><br/>

```
$ flatpak run com.github.wwmm.easyeffects 
You have PipeWire 0.3.40 installed
This is newer or the same as PipeWire 0.3.31 required to run EasyEffects

(easyeffects:2): GLib-CRITICAL **: 05:21:35.473: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(easyeffects:2): GLib-CRITICAL **: 05:21:35.488: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(easyeffects:2): GLib-CRITICAL **: 05:21:35.515: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(easyeffects:2): easyeffects-WARNING **: 05:21:35.571: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 05:21:35.571: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 05:21:35.571: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 05:21:35.571: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 05:21:36.676: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 05:21:36.676: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 05:21:36.676: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 05:21:36.676: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
munmap_chunk(): invalid pointer
```
</details>

**Comment by Digitalone1** [comment]
@wwmm Take a look at [this](https://stackoverflow.com/questions/32118545/munmap-chunk-invalid-pointer/32118638).

I think the issue could stay [here](https://github.com/wwmm/easyeffects/blob/e6acc3e94eb824e16bb63956c8f01f388335228e/src/equalizer_band_box.cpp#L83).

"Infinity" string in case of quality 0.0 is not duplicated like the other cases.

**Comment by wwmm** [comment]
When I saw this issue yesterday I did some tests and that is the problem. But it was already time to go to sleep when I saw this XD. In a few ours I will do a small bugfix release fixing this bug.

**Comment by Digitalone1** [comment]
Anyway I hope GTK frees the string somewhere, otherwise there will be memory leak. I don't know how GTK behaves in these cases.

**Comment by wwmm** [comment]
Valgrind did not complain about the other usages of `g_strdup`. In any case I will run it again to see what happens before making the commit.

**Comment by vchernin** [comment]
@wwmm the release notes for 6.2.1 have an empty line in them. Of course *some* AppStream implementations don't like that...

```
builddir/files/share/appdata/com.github.wwmm.easyeffects.appdata.xml: FAILED:
• style-invalid         : <li> is too short [-] minimum is 3 chars
• style-invalid         : <p> is too short [-]
```

I think it makes sense to automatically remove unused parts of the template anyhow. I can do that later when looking at improving the URL handling.

I will also make the AppStream linters as pedantic as possible so it won't catch us again :D

**Comment by wwmm** [comment]
Really?!? :smile:  I looked at those empty fields and I asked myself if something would happen because of them. But I did not think it would fail.
