### ISSUE TITLE
Enable Volume Normalization for specific Soundcard

### ISSUE THREAD

**Issue by solisinvictum** [wwmm/easyeffects#1319]
Hey Guys,
i have a Problem with Pipewire.
This problem could be solved, if i remove Pipewire and reinstall pulseaudio again, but i think thats isnt the best way to do.
Im honest, im to old to understand why even Pipewire is needed. But i dont understanded already decades ago why pulseaudio is needed. Everything worked fine only with ALSA. But that did SysVinit too… It seems the Guys from Systemd/Pulseaudio/various_other_software likes to develop Software just of boredom.

Just kiddin.

Nevermind, already with ALSA decades ago i set up a “virtual Soundcard” for volume normalization, because its annoys me that everything got another volume level on the internet. So i was everytime adjusting the volume if too loud/too quiet. Thats worked great.
Than pulseaudio became the standard. There i have done this the same.
But this time with some Plugins like i understand it.
For Pulseaudio it was enough, to install swh-plugins and configure pulseaudio accordingly:

```
.nofail
.include /etc/pulse/default.pa
load-module module-ladspa-sink sink_name=ladspa_sink plugin=sc4_1882 label=sc4 control=1,1.5,401,-12,20,5,12
load-module module-ladspa-sink sink_name=ladspa_normalized master=ladspa_sink plugin=fast_lookahead_limiter_1913 label=fastLookaheadLimiter control=10,-20,0.8
set-default-sink ladspa_normalized
```
With this the volume got on one level normalized. Quiet would be loader, load thinks quieter. Everything on one level.

And now i need the same, but with Pipewire  I already found out that Pipewire is totaly able to do that. But i didnt understand how to do that.
(And no. Simply install pulseaudio again beside pipewire is not a solution, why is pipewire then even needed?! (thats the suggestion i found in the internet from other guys where one guy had the same question))

**Comment by wwmm** [comment]
I have been using Linux since before Pulseaudio was created and "ALSA was enough" argument is super debatable. It was enough if we did not want to do what it was not capable of. But let's not go off topic :smile: 

There are different ways to achieve what you want. And not necessarily you need to use EasyEffects for this. If you want a static approach similar to the one you used on Pulseaudio you can use https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Filter-Chain. But if you want to do it in EasyEffects there are two possibilities

- Using a compressor 
- Using the Autogain plugin

The compressor will be more familiar to the approach you are currently using. The autogainhas less configuration options and it will normalize the volume based on "perceived" sound level. This is done through a library based on the `EBUR128` standar for loudness estimation.

**Comment by wwmm** [comment]
And there are also alternatives to EasyEffects in case you want to do it with other applications https://github.com/Audio4Linux/JDSP4Linux

**Comment by solisinvictum** [comment]
Hehe, i know this is debatable :D But i was only kiddin around.

I wanted to do it the same way like with Pulseaudio alone. And have a Thread over Pipewire: 

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1987

But it seems it is a bug. So i choosed your great Software and got it working now.

I wrote a Tutorial on EndeavourOS Forum:  https://forum.endeavouros.com/t/tutorial-volume-normalization-on-pipewire/22315

**Comment by wwmm** [comment]
I am glad at least one of the approaches is working. The disadvantage of using EasyEffects when that is the only thing you want to do with it is that the memory usage will be higher when compared to the filter chain approach. After all EasyEffects is just a gui application pretending to be a service running in the background. All those widgets in our interface can be very memory hungry in some cases.

**Comment by solisinvictum** [comment]
Yeah like said, im waiting for a "real" Solution on the official PipeWire Project Issues site. 

Sadly, i didnt know how to do it as Filter Chain, like you suggested. It sounds to be the best Solution. Maybe some on the PipeWire page hints me to the right direction.

**Comment by solisinvictum** [comment]
Just closin for you. Because i found a Solution like mentioned with EasyEffect :)

**Comment by vchernin** [comment]
@solisinvictum btw, I noticed a typo in your post (I dont have an endeavour account). For example `sudo pacman -S easyeffect` should be `sudo pacman -S easyeffects`

Also, the directory for the config folder for flatpak is different. See [the wiki](https://github.com/wwmm/easyeffects/wiki/Community-Presets#installation).

**Comment by solisinvictum** [comment]
@vchernin thanks! fixed it!

I know that for flatpak its a different one. But the guide let it install you with pacman :) 

If some one do it for himself with a different way, that person must than think about that :)
