### ISSUE TITLE
EE source not working how it should

### ISSUE THREAD

**Issue by DeeBeeDouble** [wwmm/easyeffects#1324]
### EasyEffects Version

6.2.1

### What package are you using?

Other (specify below)

### Distribution

Manjaro

### Describe the bug

Hey everyone,

So for a few days now, I have this issue where EE source doesn't let any audio through (that means I can't use EE to modify my mic). While the audio-animation in EE shows that EE receives audio from my mic, applications like discord or obs don't. As soon as I activate input filtering in EE, no audio goes to the application. I found a temporary fix, using Helvum. Every time I join a discord call, I can reroute the audio signal to bypass EE source, which is working and even all my EE plugins work with that method. Here is an example:

How it looks normally and how it worked before: ![Screenshot from 2022-01-09 00-59-23](https://user-images.githubusercontent.com/78625950/148671165-6040c231-5875-4b5c-b31c-93ecf81385d8.png)

My temporary fix (it works like that, but every time I for example join a new call it goes back to the broken state):
![Screenshot from 2022-01-09 01-00-00](https://user-images.githubusercontent.com/78625950/148671191-55f83243-2d5e-4874-8eed-6ea7684d6b20.png)

I tried reinstalling EE, Pipewire, re-enabling Pipewire and even downgrading EE, nothing worked. Trying to put another audio in EE source doesn't work either: 
![Screenshot from 2022-01-09 01-12-42](https://user-images.githubusercontent.com/78625950/148671444-e1f5e27c-1e80-4362-be68-ba11d8be7df8.png)
While without EE source, it works just fine:
![Screenshot from 2022-01-09 01-13-18](https://user-images.githubusercontent.com/78625950/148671457-13292b13-238b-44df-b276-3a56ca385325.png)

I thought that Helvum might be the problem, but uninstalling that and rebooting doesn't fix it either. All other EE things work just fine.

### Expected Behavior

EE source should let audio through and mic modifications should work without my workaround.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
STARTING EE:


(process:13813): easyeffects-DEBUG: 01:07:15.745: easyeffects version: 6.2.1
(process:13813): easyeffects-DEBUG: 01:07:15.748: main: locale directory: /usr/share/locale
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: user presets directory already exists: /home/juri/.config/easyeffects/
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: user presets directory already exists: /home/juri/.config/easyeffects/input
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: user presets directory already exists: /home/juri/.config/easyeffects/output
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: user presets directory already exists: /home/juri/.config/easyeffects/autoload/input
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.751: presets_manager: user presets directory already exists: /home/juri/.config/easyeffects/autoload/output

(easyeffects:13813): Gtk-WARNING **: 01:07:15.768: Unknown key gtk-button-images in /home/juri/.config/gtk-4.0/settings.ini

(easyeffects:13813): Gtk-WARNING **: 01:07:15.768: Unknown key gtk-menu-images in /home/juri/.config/gtk-4.0/settings.ini

(easyeffects:13813): Gtk-WARNING **: 01:07:15.769: Unknown key gtk-toolbar-style in /home/juri/.config/gtk-4.0/settings.ini

(easyeffects:13813): Gtk-WARNING **: 01:07:15.774: Theme parser error: gtk-dark.css:1911:3-9: No property named "height"

(easyeffects:13813): Gtk-WARNING **: 01:07:15.819: Theme directory 16@2x/apps of theme OneUI-dark has no size field


(easyeffects:13813): Adwaita-WARNING **: 01:07:15.907: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.947: pipe_manager: compiled with PipeWire: 0.3.42
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.947: pipe_manager: linked to PipeWire: 0.3.43
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: core version: 0.3.43
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: core name: pipewire-0
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: found metadata: settings
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: found metadata: default
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: found metadata: route-settings
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Audio/Sink 44 alsa_output.pci-0000_03_00.6.analog-stereo with timestamp 1641708435952418075 was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Audio/Source 45 alsa_input.pci-0000_03_00.6.analog-stereo with timestamp 1641708435952478559 was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Stream/Output/Audio 145 Firefox with timestamp 1641708435952572636 was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Firefox port 143 is connected to alsa_output.pci-0000_03_00.6.analog-stereo port 46
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Firefox port 100 is connected to alsa_output.pci-0000_03_00.6.analog-stereo port 48
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Audio/Sink 66 easyeffects_sink with timestamp 1641708435952697584 was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.952: pipe_manager: Audio/Source/Virtual 139 easyeffects_source with timestamp 1641708435952732435 was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "bluez_output.FC_58_FA_E7_59_C8.a2dp-sink" }
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_03_00.6.analog-stereo" }
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_03_00.6.analog-stereo" }
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: new metadata property: 0, default.video.source, Spa:String:JSON, { "name": "v4l2_input.pci-0000_03_00.3-usb-0_3_1.0" }
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: new metadata property: 145, target.node, Spa:Id, 58
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: easyeffects_sink node successfully retrieved with id 66 and timestamp 1641708435952697584
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.953: pipe_manager: easyeffects_source node successfully retrieved with id 139 and timestamp 1641708435952732435
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.959: pipe_manager: Firefox port 143 is connected to easyeffects_sink port 64
(easyeffects:13813): easyeffects-DEBUG: 01:07:15.959: pipe_manager: Firefox port 100 is connected to easyeffects_sink port 68

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.005: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.005: soe: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.005: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.005: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.005: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.032: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.086: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.172: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.293: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.319: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.343: lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.343: soe: urn:zamaudio:ZaMaximX2 is not installed

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.343: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.343: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.343: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: rel
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.388: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.448: soe: rnnoise using the default model
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.480: pipe_manager: Filter ee_soe_output_level, id = 69, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.480: soe: output_level successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.481: pipe_manager: Filter ee_soe_spectrum, id = 74, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.482: soe: spectrum successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.483: pipe_manager: Filter ee_soe_bass_enhancer, id = 79, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.484: soe: bass_enhancer successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.486: pipe_manager: Filter ee_soe_crystalizer, id = 94, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.487: soe: crystalizer successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.489: pipe_manager: Filter ee_soe_stereo_tools, id = 160, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.489: soe: stereo_tools successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.552: soe: output_level: new PipeWire blocksize: 512

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.592: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.592: sie: http://drobilla.net/plugins/mda/Loudness is not installed

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.592: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.592: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.592: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.620: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.674: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.760: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.882: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.908: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.932: lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.932: sie: urn:zamaudio:ZaMaximX2 is not installed

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.932: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.932: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:13813): easyeffects-WARNING **: 01:07:16.932: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: rel
(easyeffects:13813): easyeffects-DEBUG: 01:07:16.977: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.037: sie: rnnoise using the default model
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.064: pipe_manager: Filter ee_sie_output_level, id = 106, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.065: sie: output_level successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.066: pipe_manager: Filter ee_sie_spectrum, id = 111, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.067: sie: spectrum successfully connected to PipeWire graph
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.068: pipe_manager: Filter ee_sie_rnnoise, id = 90, was added
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.069: sie: rnnoise successfully connected to PipeWire graph
easyeffects-INFO: 01:07:17.091: application: disabling global bypass
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.137: application_ui: Icon Theme OneUI-dark detected

(easyeffects:13813): Gtk-WARNING **: 01:07:17.213: Theme directory 16@2x/apps of theme OneUI-dark has no size field

ATTENTION: default value of option mesa_glthread overridden by environment.
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.482: rnnoise_box: model directory already exists: /home/juri/.config/easyeffects/rnnoise
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.502: new default output device: alsa_output.pci-0000_03_00.6.analog-stereo
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.502: pipe_manager: new metadata property: 145, target.node, Spa:Id, 66
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.515: new default input device: alsa_input.pci-0000_03_00.6.analog-stereo
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.526: application: device alsa_card.pci-0000_03_00.6 has changed its input route to: analog-input-mic
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.526: application: device alsa_card.pci-0000_03_00.6 has changed its output route to: analog-output-headphones
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.527: soe: crystalizer blocksize: 512
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.545: soe: crystalizer latency: 0.000021 s
(easyeffects:13813): easyeffects-DEBUG: 01:07:17.673: soe: pipeline latency: 0.020833 ms



ENABELING MIC PROCESSING FOR DISCORD (here Brave) IN EE:


(easyeffects:13925): easyeffects-DEBUG: 01:55:30.708: pipe_manager: new metadata property: 151, target.node, Spa:Id, 67
(easyeffects:13925): easyeffects-DEBUG: 01:55:30.711: pipe_manager: easyeffects_source port 62 is connected to Brave input port 150
(easyeffects:13925): easyeffects-DEBUG: 01:55:30.711: pipe_manager: easyeffects_source port 137 is connected to Brave input port 99



DISABELING MIC PROCESSING FOR DISCORD (here Brave) IN EE:


(easyeffects:13925): easyeffects-DEBUG: 01:55:38.358: pipe_manager: new metadata property: 151, target.node, Spa:Id, 45
(easyeffects:13925): easyeffects-DEBUG: 01:55:38.361: pipe_manager: alsa_input.pci-0000_03_00.6.analog-stereo port 50 is connected to Brave input port 98
(easyeffects:13925): easyeffects-DEBUG: 01:55:38.361: pipe_manager: alsa_input.pci-0000_03_00.6.analog-stereo port 51 is connected to Brave input port 101
```
</details>

**Comment by wwmm** [comment]
That is weird. I am not sure about how to debug this because here on Arch Linux our virtual source is working. I am doing some tests with Discord's app mic test and OBS level meters show activity. But I did not try to actually create a video. The following command also records from our virtual source
```
gst-launch-1.0 pulsesrc ! queue ! pulsesink
```

Try to run `pw-dot`. It will show some information that Helvum does not show. Like the state of the links. Its output file can be viewed with `xdot`.

At this moment the only thing I can think of is that something is broken in your PipeWire installation. The reason is that differently from our filters our virtual source is created using a PipeWire null sink. In other words it foes not come from code I have written for EasyEffects. I am just using a module PipeWire offers.

**Comment by DeeBeeDouble** [comment]
Actually, now that you mention a Pipewire issue, I think on the day it broke, I executed two commands to restart pipewire. I went back in my zsh history and I think this is what I executed before it broke:
`systemctl --user restart pipewire pipewire-pulse and
systemctl --user daemon-reload`
But I am not 100% sure anymore that that was done just before it broke.

Here is the file that pw-dot geneerated:
[pw.zip](https://github.com/wwmm/easyeffects/files/7835370/pw.zip)
Looks all good to me.

**Comment by wwmm** [comment]
I agree. Nothing unusual in the links. But I have seen a random problem where PipeWire stays silent even when the links are active. So I am not sure... What is the output of `pw-cli info source_id` where `source_id` is the `EasyEffects Source` virtual device id. You can view it  in the pw-dot output or in EasyEffects logs. Have you rebooted your computer? Sometimes updates to the audio server require that.

**Comment by wwmm** [comment]
Is our virtual sink working? As the code that creates it is identical to the one that creates the source I would expect it to have problems too.

**Comment by wwmm** [comment]
Oh. And check if something did not mute our virtual source. Since when we were on Pulseaudio this kind of thing can happen for reasons I never could comprehend. Sometimes is like the audio server "goes crazy" and decides to mute it.

**Comment by DeeBeeDouble** [comment]
> I agree. Nothing unusual in the links. But I have seen a random problem where PipeWire stays silent even when the links are active. So I am not sure... What is the output of `pw-cli info source_id` where `source_id` is the `EasyEffects Source` virtual device id. You can view it in the pw-dot output or in EasyEffects logs. Have you rebooted your computer? Sometimes updates to the audio server require that.

So, this is the output of pw-cli info source_id:
```
pw-cli info 67                                                                        ✔ 
	id: 67
	permissions: rwxm
	type: PipeWire:Interface:Port/3
	direction: "output"
*	properties:
*		format.dsp = "32 bit float mono audio"
*		audio.channel = "FR"
*		port.monitor = "true"
*		port.id = "1"
*		object.path = "EasyEffects Source:capture_1"
*		port.name = "capture_FR"
*		port.alias = "EasyEffects Source:capture_FR"
*		port.direction = "out"
*		node.id = "85"
*		object.id = "67"
*		object.serial = "3134"
*	params: (6)
*	  3 (Spa:Enum:ParamId:EnumFormat) r-
*	  6 (Spa:Enum:ParamId:Meta) r-
*	  7 (Spa:Enum:ParamId:IO) r-
*	  4 (Spa:Enum:ParamId:Format) rw
*	  5 (Spa:Enum:ParamId:Buffers) r-
*	  15 (Spa:Enum:ParamId:Latency) rw
```
And yes, I rebooted my pc basically every time I made a change.

> Is our virtual sink working? As the code that creates it is identical to the one that creates the source I would expect it to have problems too.

Yes, EE sink is fully working.

**Comment by DeeBeeDouble** [comment]
> Oh, and check if something did not mute our virtual source. Since when we were on Pulseaudio this kind of thing can happen for reasons I never could comprehend. Sometimes is like the audio server "goes crazy" and decides to mute it.

Yes! This was the problem. EE source was muted! It looked like that:
![Screenshot from 2022-01-09 11-44-31](https://user-images.githubusercontent.com/78625950/148691927-eed83955-34f3-425c-a692-02e4f9b70ba5.png)

And after raising the volume, it is now indeed working. Maybe is there a way to force 100% volume on EE source so that things like that can not happen again?

**Comment by DeeBeeDouble** [comment]
Oh, and another question: Is there a way so that you can't see EE source and sink in the audio chooser? On kde it gets a little confusing having so many inputs and outputs for someone non-technical:
![Screenshot from 2022-01-09 12-02-48](https://user-images.githubusercontent.com/78625950/148692599-716c1571-1c2b-453a-bcce-cb5af934987b.png)
Can't they just be hidden? A user might mute EE source or sink on accident and then wonder why the mic or speaker is not working because they are not muted.

**Comment by wwmm** [comment]
>Maybe is there a way to force 100% volume on EE source so that things like that can not happen again?

I think there is but there is a catch. Some users have to set our virtual device as default. It is not what I recommend but in some cases people do not have a choice because they want to use audio applications that do not allow anything other than the default device to be used. If I force our volume to be reset to zero by default bad things can happen to the user hardware. I would have to think carefully about this...

>Can't they just be hidden?

As far as I know it can not be done. There was no way to do that in Pulseaudio and it does not seem there is one in PipeWire.

**Comment by wwmm** [comment]
>There was no way to do that in Pulseaudio and it does not seem there is one in PipeWire.

I think this task would have to be done by KDE. For example offering an option to hide virtual devices. I doubt this can be done from the server side. It is really easy for the software showing the devices to filter what has to be shown.

**Comment by vchernin** [comment]
Actually, I had an idea possibly wireplumber could handle something like that, EE virtual sinks could be marked as "app-created, don't touch" by EE, WirePlumber communicates that to the settings app, which then doesn't let the user control them. 

This would also help with the user issue I experienced in https://github.com/wwmm/easyeffects/issues/1251.

Although I am not sure how feasible that actually is, it is worth suggesting to [wireplumber here I think](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/107).

**Comment by DeeBeeDouble** [comment]
> > There was no way to do that in Pulseaudio and it does not seem there is one in PipeWire.
> 
> I think this task would have to be done by KDE. For example offering an option to hide virtual devices. I doubt this can be done from the server side. It is really easy for the software showing the devices to filter what has to be shown.

What about we ask the pipewire-developers to implement such a feature? Because yes, plasma could hide it, but then it would still be visible in apps like discord and confuse people. Really, I think it's important to hide them system-wide.

> > Maybe is there a way to force 100% volume on EE source so that things like that can not happen again?
> 
> I think there is but there is a catch. Some users have to set our virtual device as default. It is not what I recommend but in some cases people do not have a choice because they want to use audio applications that do not allow anything other than the default device to be used. If I force our volume to be reset to 100% by default bad things can happen to the user hardware. I would have to think carefully about this...
> 
> > Can't they just be hidden?
> 
> As far as I know it can not be done. There was no way to do that in Pulseaudio and it does not seem there is one in PipeWire.

What about a switch in EE that forces the source/sink volume to 100% ? It could be turned on by default to prevent issues like that and in case someone has to use them as the default the switch could be turned off.

**Comment by wwmm** [comment]
>What about we ask the pipewire-developers to implement such a feature? Because yes, plasma could hide it, but then it would still be visible in apps like discord and confuse people. Really, I think it's important to hide them system-wide.

The problem with this approach is that it assumes that there will never be a situation where it is actually needed to view virtual devices. But they do exist. Thinking about only EasyEffects users there are cases where it is needed to use the application device selection menu to select our devices because the application does not allow its stream to be moved. Hiding virtual sources blindly will not be good for everybody.

There are also the question about how to actually implement that. Audio managers like Pavucontrol, Helvum and similar are iterating over all the available nodes. In order to hide a few devices changing only the server side it would be needed to change functions that are already being used to get such information. By changing the server we can break applications that may not even care about such a feature or where it may not even be desirable. Honestly the easiest and safest thing to do is asking the applications to allow the user to select what he wants to see. Assuming no application will ever need this is not the best thing to do.

>What about a switch in EE that forces the source/sink volume to 100% ? It could be turned on by default to prevent issues like that and in case someone has to use them as the default the switch could be turned off.

I think it can be done. And I agree it is better to have a new issue for this.
