### ISSUE TITLE
Mini Version?

### ISSUE THREAD

**Issue by saaditory** [wwmm/easyeffects#1326]
What about having a cool mini version of the app, just like [Shortwave](https://gitlab.gnome.org/World/Shortwave)'s mini version, containing only spectrum widget & few controls may be?

Best of Luck!

**Comment by servimo** [comment]
I was thinking about an icon with a menu

**Comment by wwmm** [comment]
>What about having a cool mini version of the app, just like Shortwave's mini version, containing only spectrum widget & few controls may be?

Although I intend to make our interface more responsive where possible I have to be realist. We have way more controls to handle than any of the other applications used as showcase for libadwaita responsive widgets. And we need easy access to these controls. That is the whole point of using an app like EasyEffects. Hiding the widgets too much may make things unusable or too hard to use.

Consider for example that "Android back button" used at the top when the width is small. As much as I would like to have it here it just doesn't make sense. We have a top section for output effects, another for input effects and a third one with PipeWire things. It will be super confusing to do the same approach here. And more complicated to implement.

Now that we are using libadwaita we can make some parts of our window more friendly on small sizes. But the approach used on simpler applications is not going to work for us.

**Comment by wwmm** [comment]
>I was thinking about an icon with a menu of basic functions, like global bypass, preferences, plugins in use, exit

If you are thinking about something like a tray icon it is also not going to happen because gtk developers decided to not support this kind of thing anymore. And fighting against the toolkit is not productive.

**Comment by saaditory** [comment]
> Although I intend to make our interface more responsive where possible I have to be realist. We have way more controls to handle than any of the other applications used as showcase for libadwaita responsive widgets. And we need easy access to these controls. That is the whole point of using an app like EasyEffects. Hiding the widgets too much may make things unusable or too hard to use.

Makes sense. I do agree that easy access to control is required and to decide for which section from inputs and outputs will show its control or to combine in single mini window is not practical to some point. 

Although, It would be great, if we see more complex patterns get adopted in the mini version, for example, by using multiple pages in window like Carousel in AdwDemo App.
