### ISSUE TITLE
Change node description

### ISSUE THREAD

**Issue by Roger-Roger-debug** [wwmm/easyeffects#1332]
It appears that most jack/pipewire patchbays (Carla, qjackctl and soon helvum) use the node description as the name. However all effects have "easyeffects_filter" as their description and are therefor indistinguishable from each other.

I would like to set the description to the name of the nick or something that contains the name. What would be a good choice?
Also in pipe_manager the description gets compared to "easyeffects_filter". 
https://github.com/wwmm/easyeffects/blob/cdc89e8ce3138e752afbffd6630cd4a931f874ea/src/pipe_manager.cpp#L994-L998
What would I need to change there? Is that comparison even necessary?

**Comment by wwmm** [comment]
>What would be a good choice?

If the idea is to be able to recognize the node the approach will have to be similar to the one used in the `name` because the filer can be from the input or the output pipeline. So the respective tags, `sie` and `soe`, should be used too.

>What would I need to change there? Is that comparison even necessary?

At this moment that check is used only for debug purposes. The debug message could be printed without the check. The downside is that if in the future other applications are also using PipeWire filters our logs would show them too. What probably would be annoying.

**Comment by Roger-Roger-debug** [comment]
I'm sorry but I don't quite get what you mean. I would like the effects to be recognizable from their description. What does the input / output pipeline have to do with this? Wouldn't it suffice to do something like
```
const auto description = "easyeffects_" + name;
pw_properties_set(props_filter, PW_KEY_NODE_DESCRIPTION, description.c_str());
```
in https://github.com/wwmm/easyeffects/blob/cdc89e8ce3138e752afbffd6630cd4a931f874ea/src/plugin_base.cpp#L93?

Then you could still look for the `easyeffects` substring in pipe_manager.cpp

**Comment by wwmm** [comment]
Take a look at the output of `pw-cli list-objects Node` while EasyEffects is running. You will see things similar to
```
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_limiter"
 		node.nick = "limiter"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
```
If the user also has a limiter in the input pipeline there will be another entry almost identical to that but with `node.name = "ee_sie_limiter"`. If the idea is being able to recognize filters the description should also tell from which pipeline the filter. 

>Wouldn't it suffice to do something like

We can do only that. It will be more helpful for people than what we do now. But those that load a given filter in both pipelines will see 2 entries with the exact same description. If that is going to be a problem or not it is up to the user.
