### ISSUE TITLE
easyeffects does not follow changes of default devices.

### ISSUE THREAD

**Issue by primalmotion** [wwmm/easyeffects#1345]
### EasyEffects Version

master

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch

### Describe the bug

When the default device changes (like when a BT devices is connected), easyeffects does not follow. any application sending their sound stream to easyeffects will have no sound. I can bypass easyeffects from pavucontrol and it works great. I notice that the device is not even available in easyeffects config if I disable "Use Default". Restarting easyeffect service makes it work, until there is another device switch.

I'm using pipewire 0.3.43 with pulse module.

The exact same issue happens with the official Arch Linux package

### Expected Behavior

Easyeffect should follow the changes of default devices

**Comment by wwmm** [comment]
Kill easyeffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see some logs. I am slso on Arch Linux and so far I could not reproduce this issue with my 2 sound cards. When I change the one that is used as default the sound automatically goes to it.

**Comment by wwmm** [comment]
Also run `pw-dot` in the cases where there is no audio so we can see if the links are not being done. The output file can be viewed with `xdot`.

**Comment by primalmotion** [comment]
So I did more test, it's not that there is no audio, it's that the sink does not change. I tried with my laptop audio out and 2 BT speakers. Switching from laptop to one of the BT speakers works flawlessly. but switching to the other BT speaker does not change the output. Here's the log.

I run easyeffects as a service, so I have launched it with:

`G_MESSAGES_DEBUG=easyeffects easyeffects --gapplication-service`

```
## SWITCHING FROM ANALOG OUT TO BT 1

(easyeffects:1740438): easyeffects-DEBUG: 10:32:29.185: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "bluez_output.C0_28_8D_F6_95_0B.a2dp-sink" }
(easyeffects:1740438): easyeffects-DEBUG: 10:32:29.185: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "bluez_output.C0_28_8D_F6_95_0B.a2dp-sink" }
(easyeffects:1740438): easyeffects-DEBUG: 10:32:29.186: new default output device: bluez_output.C0_28_8D_F6_95_0B.a2dp-sink
(easyeffects:1740438): easyeffects-DEBUG: 10:32:29.187: presets_manager: autoloading preset default for device bluez_output.C0_28_8D_F6_95_0B.a2dp-sink
(easyeffects:1740438): easyeffects-DEBUG: 10:32:29.187: presets_manager: loaded preset: /home/antoine/.config/easyeffects/output/default.json

## SWITCHING BT 1 TO ANALOG OUT

(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.209: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.209: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.210: new default output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.213: presets_manager: autoloading preset librem14-eq-2.0 for device alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.214: soe: pipeline latency: 0.000000 ms
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.221: soe: equalizer successfully connected to PipeWire graph
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.225: soe: limiter successfully connected to PipeWire graph
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.229: soe: maximizer successfully connected to PipeWire graph


## SWITCHING BT 1 OR ANALOG OUT TO BT 2

(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.699: presets_manager: loaded preset: /home/antoine/.config/easyeffects/output/librem14-eq-2.0.json
(easyeffects:1740438): easyeffects-DEBUG: 10:32:33.725: soe: output_level: new PipeWire blocksize: 1024
(easyeffects:1740438): easyeffects-DEBUG: 10:32:36.992: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "easyeffects_sink" }
(easyeffects:1740438): easyeffects-DEBUG: 10:32:36.993: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "easyeffects_sink" }
```

**Comment by primalmotion** [comment]
I'll had this is kind of random. sometimes it woks perfecly for a while. until it does not. I'll try to get the pw-dot next time it happens, since I forgot :)

**Comment by primalmotion** [comment]
[pw.zip](https://github.com/wwmm/easyeffects/files/7884413/pw.zip)
Just happened. after waitking up.

Heres' the content of journalctl around the time that happened

```
Jan 17 12:03:39 axion easyeffects[1180]: soe:  link from node 65 to output device 43 failed
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:05 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:06 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:07 axion easyeffects[1180]: pipe_manager: Remote error res: No such file or directory
Jan 17 12:04:07 axion easyeffects[1180]: pipe_manager: Remote error message: unknown resource 19 op:1
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 109 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 104 failed
Jan 17 12:04:09 axion easyeffects[1180]: sie:  link from node 44 to node 56 failed
...
```
It's full of these

**Comment by wwmm** [comment]
>It's full of these

That is not good indeed. This week I am a little busy but I will try to take a look at this. In these tests the only thing you are doing is changing the default device in your audio manager?

**Comment by primalmotion** [comment]
not even that. Usually my BT adapter becomes available and bluez connects to it automatically

**Comment by wwmm** [comment]
>I notice that the device is not even available in easyeffects config if I disable "Use Default".

@primalmotion it would be good to see a full log.

**Comment by primalmotion** [comment]
I was not able to reproduce. I got an update for pipewire that may have fixed things, maybe? But I'm not sure. I'll continue to monitor

**Comment by primalmotion** [comment]
ok so it seems this is happening after a waking up from suspend state. Here are the logs
[easyeffect.log](https://github.com/wwmm/easyeffects/files/7915976/easyeffect.log)

**Comment by primalmotion** [comment]
I noticed this https://github.com/wwmm/easyeffects/issues/1350#issuecomment-1017446450 so I updated to lates master. but that did not fix the problem. Everytime I enter sleep, when I wake up and my bluetooth devices reconnect, there's no sound until I restart easyeffects

**Comment by wwmm** [comment]
I did a suspending test now with my 2 soundcards. Although the message about failed links appeared once as soon as Firefox started to play the youtube again EasyEffects made a new attempt to link its filters and audio worked.

I think that when PipeWire comes back from suspending there is a larger than usual time interval between its notification about a new device and the notification that gives the information about the device ports. As these operations are asynchronous we may be trying to relink the filters before the information about the device ports are delivered. And somehow this "timing problem" seems to get worse when bluetooth is used.

If that is indeed the case fixing this issue may be tougher than I thought =/

**Comment by wwmm** [comment]
I have to see if there is a way to get device and its ports information at once. Using some kind of loop to wait for the ports information in the same section where we have to do the links may be problematic.

**Comment by wwmm** [comment]
>I have to see if there is a way to get device and its ports information at once

As far as I can see there isn't. So I will have to inserting loops that will force the code that does the link to wait for the ports information. Hopefully there won't be cases where we get stuck waiting for an information that will never come...

**Comment by wwmm** [comment]
@primalmotion please test the master branch again. At least on my computer I do not have warnings about failed links anymore when suspending. But as I do not have a bluetooth device it is hard to say if it will make any difference in your case.

**Comment by primalmotion** [comment]
Ok I have updated to latest master. I'll monitor and report back. Thanks

**Comment by primalmotion** [comment]
It seems to work better. After waking up the laptop this morning everything worked as expected. I also noticed there's no more warnings (just one about a BT device that was gone, and that was true). I'll continue to monitor but it seems to have vastly improve the behavior. Thanks!

**Comment by primalmotion** [comment]
Seems to work now. Been 2 days without any unexpected behavior. I think we can close this now. Thanks!
