### ISSUE TITLE
Equalizer presets are not appearing.

### ISSUE THREAD

**Issue by asadlittleflower** [wwmm/easyeffects#1346]
**EasyEffects Version:**
Latest (Cannot check through terminal?)

**What package are you using?**
Rpm / easyeffects

**Distribution:**
Fedora 35, Gnome 41.3

**Describe the bug:**
Equalizer Presets do not show. Installed the community preset https://github.com/JackHack96/EasyEffects-Presets. 

**Debug Log**
_(Log from running G_MESSAGES_DEBUG=easyeffects easyeffects)_**:**
process:9876): easyeffects-DEBUG: 22:46:27.955: main: locale directory: /usr/share/locale
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.102: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: user presets directory already exists: /home/mil/.config/easyeffects/
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: user presets directory already exists: /home/mil/.config/easyeffects/input
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: user presets directory already exists: /home/mil/.config/easyeffects/output
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: user presets directory already exists: /home/mil/.config/easyeffects/autoload/input
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.103: presets_manager: user presets directory already exists: /home/mil/.config/easyeffects/autoload/output
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.601: application:  destroyed
(easyeffects:9876): easyeffects-DEBUG: 22:46:28.602: presets_manager: destroyed

**Additional Information:**
If its worth any mentioning, I had a dual boot and easyeffects worked. Meaning that the presets were shown and working. I apologize in advance for any mistakes or such, as I generally do not have any experience in reporting application issues.
Also here is the pw-dump 
https://pastebin.com/73RAK3bb

**Comment by wwmm** [comment]
>Equalizer Presets do not show. Installed the community preset https://github.com/JackHack96/EasyEffects-Presets.

I tried one of them and it is working. How did you "install" them? The easiest thing to o is using the import preset button in our Presets menu. It is the button besides the one with a "plus icon".

**Comment by asadlittleflower** [comment]
I curl-ed it like it suggested and simply ran the script. I get that I can Import it but which file would that be? As of this response I will manually install and if its alright post back here.

**Comment by wwmm** [comment]
No problems :-)
