### ISSUE TITLE
No sound output on soundcard restart (i.e. suspend) and bluetooth

### ISSUE THREAD

**Issue by gauravag99** [wwmm/easyeffects#1350]
### EasyEffects Version

6.2.1 (Flatpak and RPM tested) and 6.1.3 (RPM)

### What package are you using?

Fedora

### Distribution

Fedora 35

### Describe the bug

Easyeffect's output is failing to re-establish a connection to the speaker sink upon computer suspend or in the case of Bluetooth headphones, leaving them idle so that they go into power-saving mode.
A Helvum screenshot is attached below, NOTE no connection from output-fl to HDA Intel PCH
![image](https://user-images.githubusercontent.com/59108967/149980360-fdf5a418-3900-4985-bce8-28209cdde15d.png)

Steps to reproduce the problem:
1. Start any audio from a web browser. EasyEffects is working brilliantly.
2. Suspend the computer. Wake it up again.
3. Easyeffect spectrum is working, but no audio output.

Things tried:
- Since Fedora 35 shifted to Wireplumber, the first thing tried is ``sudo dnf swap wireplumber pipewire-media-session``. Switching to the media session manager and restarting did not do anything.
- Flatpak version : Tried Flatpak, same issue.
- Tried 'Process all inputs' checked and unchecked.
- Tried unchecking/checking 'Use Default Sink' in Pipewire tab.
- Removing all plugins/effects. Did not work.
- Restarting Easyeffects. Works temporarily. Have to restart after every suspend or whenever Bluetooth loses connection.
- Manually making the connection from output-fl to HDA Intel PCH works until the next suspend.

Audio software present: (On top of vanilla Fedora 35):
Pipewire version: 0.3.43-1
Wireplumber version: 0.4.7
pipewire-media-session version : 0.4.1
Helvum flatpak 0.3.2

In the log attached below, suspend happens at timestamp 22:00, Resume happens at 22:01 and further firefox initialisations are tabs being reloaded.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
~ ❯ G_MESSAGES_DEBUG=easyeffects easyeffects                                                                             2m 17s  base
(process:17646): easyeffects-DEBUG: 21:59:38.556: easyeffects version: 6.2.1
(process:17646): easyeffects-DEBUG: 21:59:38.556: main: locale directory: /usr/share/locale
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: user presets directory already exists: /home/gaurav/.config/easyeffects/
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: user presets directory already exists: /home/gaurav/.config/easyeffects/input
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: user presets directory already exists: /home/gaurav/.config/easyeffects/output
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: user presets directory already exists: /home/gaurav/.config/easyeffects/autoload/input
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.561: presets_manager: user presets directory already exists: /home/gaurav/.config/easyeffects/autoload/output
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.744: pipe_manager: compiled with PipeWire: 0.3.40
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.744: pipe_manager: linked to PipeWire: 0.3.43
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: core version: 0.3.43
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: core name: pipewire-0
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: found metadata: settings
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: found metadata: default
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: found metadata: route-settings
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: Audio/Sink 184 alsa_output.pci-0000_00_1f.3.analog-stereo with timestamp 1642523378766781405 was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.766: pipe_manager: Audio/Source 144 alsa_input.pci-0000_00_1f.3.analog-stereo with timestamp 1642523378766962536 was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.767: pipe_manager: Stream/Output/Audio 73 Firefox with timestamp 1642523378767206655 was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.767: pipe_manager: Firefox port 231 is connected to alsa_output.pci-0000_00_1f.3.analog-stereo port 132
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.767: pipe_manager: Firefox port 72 is connected to alsa_output.pci-0000_00_1f.3.analog-stereo port 218
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.767: pipe_manager: Audio/Sink 226 easyeffects_sink with timestamp 1642523378767540113 was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.767: pipe_manager: Audio/Source/Virtual 113 easyeffects_source with timestamp 1642523378767652317 was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.768: pipe_manager: easyeffects_sink node successfully retrieved with id 226 and timestamp 1642523378767540113
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.769: pipe_manager: easyeffects_source node successfully retrieved with id 113 and timestamp 1642523378767652317
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.769: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.769: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.769: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_1f.3.analog-stereo" }
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.769: pipe_manager: new metadata property: 0, default.video.source, Spa:String:JSON, { "name": "v4l2_input.pci-0000_00_14.0-usb-0_5_1.0" }
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.783: pipe_manager: Firefox port 231 is connected to easyeffects_sink port 77
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.783: pipe_manager: Firefox port 72 is connected to easyeffects_sink port 34
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.848: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.885: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:38.937: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.014: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.031: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.049: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.049: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.077: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.117: soe: rnnoise using the default model
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.137: pipe_manager: Filter ee_soe_output_level, id = 223, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.138: soe: output_level successfully connected to PipeWire graph
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.138: pipe_manager: Filter ee_soe_spectrum, id = 141, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.139: soe: spectrum successfully connected to PipeWire graph
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.140: pipe_manager: Filter ee_soe_autogain, id = 236, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.141: soe: autogain successfully connected to PipeWire graph
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.150: pipe_manager: Filter ee_soe_equalizer, id = 95, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.151: soe: equalizer successfully connected to PipeWire graph
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.217: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.253: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.304: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.383: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.400: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.417: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.417: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.445: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.485: sie: rnnoise using the default model
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.502: pipe_manager: Filter ee_sie_output_level, id = 135, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.503: sie: output_level successfully connected to PipeWire graph
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.504: pipe_manager: Filter ee_sie_spectrum, id = 252, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.505: sie: spectrum successfully connected to PipeWire graph
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.506: pipe_manager: Filter ee_sie_rnnoise, id = 80, was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.507: sie: rnnoise successfully connected to PipeWire graph
easyeffects-INFO: 21:59:39.523: application: disabling global bypass
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.551: application_ui: Icon Theme Tela-circle-blue detected
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.845: rnnoise_box: model directory already exists: /home/gaurav/.config/easyeffects/rnnoise
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.889: new default output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.889: presets_manager: autoloading preset Wiredheadphones for device alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.894: presets_manager: loaded preset: /home/gaurav/.config/easyeffects/output/Wiredheadphones.json
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.901: new default input device: alsa_input.pci-0000_00_1f.3.analog-stereo
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.907: application: device alsa_card.pci-0000_00_1f.3 has changed its input route to: analog-input-internal-mic
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.907: application: device alsa_card.pci-0000_00_1f.3 has changed its output route to: analog-output-headphones
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.907: presets_manager: autoloading preset Wiredheadphones for device alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:17646): easyeffects-DEBUG: 21:59:39.912: presets_manager: loaded preset: /home/gaurav/.config/easyeffects/output/Wiredheadphones.json
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.447: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.448: app_info: Firefox disposed
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.451: app_info: Firefox finalized
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.451: app_info: data struct destroyed
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.451: node holder: 73, Firefox finalized
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.580: pipe_manager: Stream/Output/Audio 73 Firefox with timestamp 1642523393580677921 was added
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.583: pipe_manager: Firefox port 72 is connected to easyeffects_sink port 77
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.583: pipe_manager: Firefox port 206 is connected to easyeffects_sink port 34
(easyeffects:17646): easyeffects-DEBUG: 21:59:53.907: soe: output_level: new PipeWire blocksize: 2048
(easyeffects:17646): easyeffects-DEBUG: 22:01:19.698: pipe_manager: Audio/Source alsa_input.pci-0000_00_1f.3.analog-stereo was removed
(easyeffects:17646): easyeffects-DEBUG: 22:01:19.700: pipe_manager: Audio/Sink alsa_output.pci-0000_00_1f.3.analog-stereo was removed

(easyeffects:17646): easyeffects-WARNING **: 22:01:19.703: pipe_manager: Remote error res: No such file or directory

(easyeffects:17646): easyeffects-WARNING **: 22:01:19.703: pipe_manager: Remote error message: unknown resource 30 op:2

(easyeffects:17646): easyeffects-WARNING **: 22:01:19.703: pipe_manager: Remote error res: No such file or directory

(easyeffects:17646): easyeffects-WARNING **: 22:01:19.703: pipe_manager: Remote error message: unknown resource 30 op:2
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.106: pipe_manager: found metadata: default
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.106: pipe_manager: found metadata: route-settings
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.244: pipe_manager: Audio/Sink 63 alsa_output.pci-0000_00_1f.3.analog-stereo with timestamp 1642523480244406764 was added
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.244: pipe_manager: Audio/Source 102 alsa_input.pci-0000_00_1f.3.analog-stereo with timestamp 1642523480244517039 was added
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.245: node holder: 184, alsa_output.pci-0000_00_1f.3.analog-stereo finalized
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.245: node holder: 144, alsa_input.pci-0000_00_1f.3.analog-stereo finalized
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.246: application: device alsa_card.pci-0000_00_1f.3 has changed its input route to: analog-input-internal-mic
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.246: application: device alsa_card.pci-0000_00_1f.3 has changed its output route to: analog-output-headphones
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.247: presets_manager: autoloading preset Wiredheadphones for device alsa_output.pci-0000_00_1f.3.analog-stereo
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.250: pipe_manager: Firefox port 206 is connected to easyeffects_sink port 230
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.250: pipe_manager: Firefox port 72 is connected to easyeffects_sink port 195
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.254: presets_manager: loaded preset: /home/gaurav/.config/easyeffects/output/Wiredheadphones.json
(easyeffects:17646): easyeffects-DEBUG: 22:01:20.257: pipe_manager: node 184 has no input ports yet. Aborting the link

(easyeffects:17646): easyeffects-WARNING **: 22:01:20.257: soe:  link from node 223 to output device 184 failed
 (easyeffects:17646): easyeffects-DEBUG: 22:01:44.406: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.408: app_info: Firefox disposed
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.411: app_info: Firefox finalized
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.411: app_info: data struct destroyed
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.411: node holder: 73, Firefox finalized
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.596: pipe_manager: Stream/Output/Audio 73 Firefox with timestamp 1642523504596442360 was added
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.599: pipe_manager: Firefox port 72 is connected to easyeffects_sink port 230
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.599: pipe_manager: Firefox port 256 is connected to easyeffects_sink port 195
(easyeffects:17646): easyeffects-DEBUG: 22:01:44.611: pipe_manager: node 184 has no input ports yet. Aborting the link

(easyeffects:17646): easyeffects-WARNING **: 22:01:44.611: soe:  link from node 223 to output device 184 failed
(easyeffects:17646): easyeffects-DEBUG: 22:01:45.945: pipe_manager: node 184 has no input ports yet. Aborting the link

(easyeffects:17646): easyeffects-WARNING **: 22:01:45.945: soe:  link from node 223 to output device 184 failed
(easyeffects:17646): easyeffects-DEBUG: 22:01:49.466: pipe_manager: Stream/Output/Audio Firefox was removed
(easyeffects:17646): easyeffects-DEBUG: 22:01:49.471: app_info: Firefox disposed
(easyeffects:17646): easyeffects-DEBUG: 22:01:49.472: app_info: Firefox finalized
(easyeffects:17646): easyeffects-DEBUG: 22:01:49.472: app_info: data struct destroyed
(easyeffects:17646): easyeffects-DEBUG: 22:01:49.472: node holder: 73, Firefox finalized
(easyeffects:17646): easyeffects-DEBUG: 22:01:52.528: pipe_manager: Stream/Output/Audio 73 Firefox with timestamp 1642523512528463359 was added
(easyeffects:17646): easyeffects-DEBUG: 22:01:52.535: pipe_manager: Firefox port 256 is connected to easyeffects_sink port 230
(easyeffects:17646): easyeffects-DEBUG: 22:01:52.536: pipe_manager: Firefox port 254 is connected to easyeffects_sink port 195
(easyeffects:17646): easyeffects-DEBUG: 22:01:52.560: pipe_manager: node 184 has no input ports yet. Aborting the link

(easyeffects:17646): easyeffects-WARNING **: 22:01:52.560: soe:  link from node 223 to output device 184 failed



```
</details>

**Comment by gauravag99** [comment]
Yep you're right. `HDA Intel PCH` node id changes on suspend:

Output of `pw-cli list-objects Node`:
<details><summary>Before suspend Log</summary><br/>
~ ❯ pw-cli list-objects Node                                              base
	id 28, type PipeWire:Interface:Node/3
 		object.serial = "27"
 		factory.id = "10"
 		priority.driver = "20000"
 		node.name = "Dummy-Driver"
	id 29, type PipeWire:Interface:Node/3
 		object.serial = "28"
 		factory.id = "10"
 		priority.driver = "19000"
 		node.name = "Freewheel-Driver"
	id 61, type PipeWire:Interface:Node/3
 		object.serial = "2713"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_output_level"
 		node.nick = "output_level"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 65, type PipeWire:Interface:Node/3
 		object.serial = "2784"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_test_signals"
 		media.type = "Audio"
 		media.category = "Source"
 		media.role = "DSP"
	id 86, type PipeWire:Interface:Node/3
 		object.serial = "2743"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_sie_output_level"
 		node.nick = "output_level"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 98, type PipeWire:Interface:Node/3
 		object.serial = "2651"
 		object.path = "alsa:pcm:0:front:0:capture"
 		factory.id = "18"
 		client.id = "217"
 		device.id = "63"
 		priority.session = "2009"
 		priority.driver = "2009"
 		node.description = "Built-in Audio Analog Stereo"
 		node.name = "alsa_input.pci-0000_00_1f.3.analog-stereo"
 		node.nick = "HDA Intel PCH"
 		media.class = "Audio/Source"
	id 99, type PipeWire:Interface:Node/3
 		object.serial = "2650"
 		object.path = "alsa:pcm:0:front:0:playback"
 		factory.id = "18"
 		client.id = "217"
 		device.id = "63"
 		priority.session = "1009"
 		priority.driver = "1009"
 		node.description = "Built-in Audio Analog Stereo"
 		node.name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
 		node.nick = "HDA Intel PCH"
 		media.class = "Audio/Sink"
	id 101, type PipeWire:Interface:Node/3
 		object.serial = "2730"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_equalizer"
 		node.nick = "equalizer"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 104, type PipeWire:Interface:Node/3
 		object.serial = "2644"
 		factory.id = "10"
 		client.id = "217"
 		node.name = "Midi-Bridge"
 		media.class = "Midi/Bridge"
	id 110, type PipeWire:Interface:Node/3
 		object.serial = "2648"
 		object.path = "v4l2:/dev/video0"
 		factory.id = "10"
 		client.id = "217"
 		device.id = "190"
 		node.description = "Video Capture 3"
 		node.name = "v4l2_input.pci-0000_00_14.0-usb-0_5_1.0"
 		media.class = "Video/Source"
 		media.role = "Camera"
	id 114, type PipeWire:Interface:Node/3
 		object.serial = "2718"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_spectrum"
 		node.nick = "spectrum"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 141, type PipeWire:Interface:Node/3
 		object.serial = "2723"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_autogain"
 		node.nick = "autogain"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 198, type PipeWire:Interface:Node/3
 		object.serial = "2690"
 		factory.id = "6"
 		client.id = "116"
 		application.name = "Firefox"
 		node.name = "Firefox"
 		media.class = "Stream/Output/Audio"
	id 213, type PipeWire:Interface:Node/3
 		object.serial = "2753"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_sie_rnnoise"
 		node.nick = "rnnoise"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 221, type PipeWire:Interface:Node/3
 		object.serial = "2698"
 		factory.id = "18"
 		client.id = "258"
 		node.description = "EasyEffects Source"
 		node.name = "easyeffects_source"
 		media.class = "Audio/Source/Virtual"
	id 226, type PipeWire:Interface:Node/3
 		object.serial = "2697"
 		factory.id = "18"
 		client.id = "258"
 		node.description = "EasyEffects Sink"
 		node.name = "easyeffects_sink"
 		media.class = "Audio/Sink"
	id 238, type PipeWire:Interface:Node/3
 		object.serial = "2748"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_sie_spectrum"
 		node.nick = "spectrum"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"

</details>

<details><summary>After suspend Log</summary><br/>
~ ❯ pw-cli list-objects Node                                              base
	id 28, type PipeWire:Interface:Node/3
 		object.serial = "27"
 		factory.id = "10"
 		priority.driver = "20000"
 		node.name = "Dummy-Driver"
	id 29, type PipeWire:Interface:Node/3
 		object.serial = "28"
 		factory.id = "10"
 		priority.driver = "19000"
 		node.name = "Freewheel-Driver"
	id 61, type PipeWire:Interface:Node/3
 		object.serial = "2713"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_output_level"
 		node.nick = "output_level"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 65, type PipeWire:Interface:Node/3
 		object.serial = "2784"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_test_signals"
 		media.type = "Audio"
 		media.category = "Source"
 		media.role = "DSP"
	id 78, type PipeWire:Interface:Node/3
 		object.serial = "2816"
 		object.path = "alsa:pcm:0:front:0:playback"
 		factory.id = "18"
 		client.id = "63"
 		device.id = "188"
 		priority.session = "1009"
 		priority.driver = "1009"
 		node.description = "Built-in Audio Analog Stereo"
 		node.name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
 		node.nick = "HDA Intel PCH"
 		media.class = "Audio/Sink"
	id 83, type PipeWire:Interface:Node/3
 		object.serial = "2817"
 		object.path = "alsa:pcm:0:front:0:capture"
 		factory.id = "18"
 		client.id = "63"
 		device.id = "188"
 		priority.session = "2009"
 		priority.driver = "2009"
 		node.description = "Built-in Audio Analog Stereo"
 		node.name = "alsa_input.pci-0000_00_1f.3.analog-stereo"
 		node.nick = "HDA Intel PCH"
 		media.class = "Audio/Source"
	id 86, type PipeWire:Interface:Node/3
 		object.serial = "2743"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_sie_output_level"
 		node.nick = "output_level"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 90, type PipeWire:Interface:Node/3
 		object.serial = "2814"
 		object.path = "v4l2:/dev/video0"
 		factory.id = "10"
 		client.id = "63"
 		device.id = "205"
 		node.description = "Video Capture 3"
 		node.name = "v4l2_input.pci-0000_00_14.0-usb-0_5_1.0"
 		media.class = "Video/Source"
 		media.role = "Camera"
	id 101, type PipeWire:Interface:Node/3
 		object.serial = "2730"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_equalizer"
 		node.nick = "equalizer"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 114, type PipeWire:Interface:Node/3
 		object.serial = "2718"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_spectrum"
 		node.nick = "spectrum"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 141, type PipeWire:Interface:Node/3
 		object.serial = "2723"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_soe_autogain"
 		node.nick = "autogain"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 198, type PipeWire:Interface:Node/3
 		object.serial = "2690"
 		factory.id = "6"
 		client.id = "116"
 		application.name = "Firefox"
 		node.name = "Firefox"
 		media.class = "Stream/Output/Audio"
	id 213, type PipeWire:Interface:Node/3
 		object.serial = "2753"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_sie_rnnoise"
 		node.nick = "rnnoise"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 217, type PipeWire:Interface:Node/3
 		object.serial = "2810"
 		factory.id = "10"
 		client.id = "63"
 		node.name = "Midi-Bridge"
 		media.class = "Midi/Bridge"
	id 221, type PipeWire:Interface:Node/3
 		object.serial = "2698"
 		factory.id = "18"
 		client.id = "258"
 		node.description = "EasyEffects Source"
 		node.name = "easyeffects_source"
 		media.class = "Audio/Source/Virtual"
	id 226, type PipeWire:Interface:Node/3
 		object.serial = "2697"
 		factory.id = "18"
 		client.id = "258"
 		node.description = "EasyEffects Sink"
 		node.name = "easyeffects_sink"
 		media.class = "Audio/Sink"
	id 238, type PipeWire:Interface:Node/3
 		object.serial = "2748"
 		client.id = "258"
 		node.description = "easyeffects_filter"
 		node.name = "ee_sie_spectrum"
 		node.nick = "spectrum"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"

</details>

Can also be seen in xdot. 
So this is a pipewire issue?

**Comment by wwmm** [comment]
>So this is a pipewire issue?

Not necessarily. When devices or streams are destroyed and recreated it is normal that a new id is given. But usually some signals about creation/destruction of nodes are emitted by PipeWire when this happens. At first site it seems this is not the case when suspending. Maybe it is a PipeWire bug. But it is also possible that there is something I could do in this situation. I will try to investigate when I have time.

**Comment by Digitalone1** [comment]
I wonder how this behavior could affect node management if we didn't switch to tracking `by timestamp`.

Every change could not be caught inside `on_node_info` because the id has changed. Besides we already update the device id [there](https://github.com/wwmm/easyeffects/blob/ad4695ae763ffefc642c4c3f0058e790a424cbd1/src/pipe_manager.cpp#L357).

Maybe we should also update it everytime in `on_node_event_param`?

I don't see a good solution to this. PipeWire should not change the id. Or at least it should notify when it's changed, otherwise it's overkill.

**Comment by wwmm** [comment]
>Or at least it should notify when it's changed

In the `Debug Log` provided by @gauravag99 I can see at the timestamp `22:01:20.244`
```
pipe_manager: Audio/Sink 63 alsa_output.pci-0000_00_1f.3.analog-stereo with timestamp 1642523480244406764 was added
```
According to the same log that device had the id `184` before the computer was suspended. So PipeWire is emitting the new device signal. But it does not emit again the `default device signal`. And at this moment we rely on that one.

In a way it makes sense PipeWire does not emit the new default device signal again because there was no default device change. It just decided to change the device id...

**Comment by wwmm** [comment]
I think we can work around that problem adding some checks in the callback signal we already have for new devices. It is annoying but I doubt PipeWire will go back to the old behavior of not changing the device id. They probably had a reason to do that.

**Comment by wwmm** [comment]
Wait... I am looking at the code and I have already added to the master branch some changes that may fix that issue. The intention was fixing #1333. It helped but it was not enough to fix the problem. But maybe for this particular case related to the suspending operation it is enough.

@gauravag99 I think our nightly flatpak builds https://github.com/wwmm/easyeffects/wiki/Package-Repositories#nightly-flatpak already have the patches in the master branch.

**Comment by gauravag99** [comment]
Just tried the nightly build and it works. Thanks a lot, I'll keep using this.
