### ISSUE TITLE
Weird bottom border on bottom bar

### ISSUE THREAD

**Issue by jannuary** [wwmm/easyeffects#1352]
### EasyEffects Version

6.2.1

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora Rawhide

### Describe the bug

The bottom bar has a barely noticable bottom border, which also overlaps with the window border in dark mode nastily:

![image](https://user-images.githubusercontent.com/27908024/150321641-5c7ad824-e691-4151-9391-539ca16c3c5b.png)

(HC for clarity, appears outside as well)

Probably has to do something with this being a headerbar, which is also kinda weird

**Comment by wwmm** [comment]
>Probably has to do something with this being a headerbar, which is also kinda weird

No other widget allowed me to do what I wanted in a straightforward way like the headerbar did. But I haven't looked at this in a while. Maybe there are other ways without using the headerbar.

**Comment by SeaDve** [comment]
I think it must be the headerbar since it uses box-shadow instead of an actual border style which offsets the "border" a bit.

You can maybe use something with `toolbar` class and with `CenterBox`

**Comment by wwmm** [comment]
>You can maybe use something with toolbar class and with CenterBox as a child

I wonder if a `toolbar` style class still exists. There are no toolbar widgets in gtk4.

**Comment by SeaDve** [comment]
It still does https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/style-classes.html#toolbars

**Comment by wwmm** [comment]
I imagine this has been solved.
