### ISSUE TITLE
GUI doesn't open

### ISSUE THREAD

**Issue by colourfuloctopus** [wwmm/easyeffects#1354]
### EasyEffects Version

6.2.1-1

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

I'm setting up a new Arch installation, and easyeffects launched fine the first time, but as I realized I had not enabled wireplumber and was missing pipewire-pulse, I sorted those and rebooted. Now the application doesn't open. Reverting did not fix it. I've tried both aur pkgs, as well as the flatpak version, and none of them show. 

I've tried to think back to what I could've missed, but nothing comes to mind. Other applications launch fine. Starting them via a terminal produces no output, and there's nothing - to me - obvious in the debug logs below (included both aur and flatpak logs). 

I'm using bspwm on Arch, start wireplumber with via systemctl, and easyeffects via `easyeffects --gapplication-service` in bspwmrc. 

I'll post the pw-dump if you need it, but as it seems to be ~8000 lines I'll refrain from doing so for now.

Any ideas?

### Expected Behavior

Application GUI opens

### Debug Log

<details><summary>Debug Log</summary><br/>

```

You have PipeWire 0.3.43 installed
This is newer or the same as PipeWire 0.3.31 required to run EasyEffects
(process:2): easyeffects-DEBUG: 15:51:21.861: easyeffects version: 6.2.1
(process:2): easyeffects-DEBUG: 15:51:21.862: main: locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 15:51:21.866: presets_manager: system input presets directory: "/app/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 15:51:21.866: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 15:51:21.866: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 15:51:21.866: presets_manager: system output presets directory: "/app/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 15:51:21.866: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 15:51:21.866: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 15:51:21.867: presets_manager: user presets directory already exists: /home/anchorage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 15:51:21.867: presets_manager: user presets directory already exists: /home/anchorage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 15:51:21.867: presets_manager: user presets directory already exists: /home/anchorage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 15:51:21.867: presets_manager: user presets directory already exists: /home/anchorage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 15:51:21.867: presets_manager: user presets directory already exists: /home/anchorage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 15:51:21.868: Exitting the main function with status: 1
```
</details>

<details><summary>Debug Log</summary><br/>

```

G_MESSAGES_DEBUG=easyeffects easyeffects
(process:18689): easyeffects-DEBUG: 15:52:41.331: easyeffects version: 6.2.1
(process:18689): easyeffects-DEBUG: 15:52:41.332: main: locale directory: /usr/share/locale
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: user presets directory already exists: /home/anchorage/.config/easyeffects/
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: user presets directory already exists: /home/anchorage/.config/easyeffects/input
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: user presets directory already exists: /home/anchorage/.config/easyeffects/output
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: user presets directory already exists: /home/anchorage/.config/easyeffects/autoload/input
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.333: presets_manager: user presets directory already exists: /home/anchorage/.config/easyeffects/autoload/output
(easyeffects:18689): easyeffects-DEBUG: 15:52:41.335: Exitting the main function with status: 1

```
</details>

**Comment by wwmm** [comment]
Kill EE `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see the full log.

**Comment by colourfuloctopus** [comment]
Killing EE and opening it, whether in debug mode or not, works. It opens as it should
Killing EE and manually starting it with easyeffects --gapplication-service, and then opening it via .desktop/terminal works.

However, once I reboot (and have bspwm start it with easyeffects --gapplication-service), the GUI does not open. What is the method to retrieve logs when running it with the --gapplication flag?

**Comment by wwmm** [comment]
>What is the method to retrieve logs when running it with the --gapplication flag?

This should work `G_MESSAGES_DEBUG=easyeffects easyeffects --gapplication`. I have never used `bspwm`. Is it making sure PipeWire is already running by the time EE is started?

**Comment by colourfuloctopus** [comment]
`G_MESSAGES_DEBUG=easyeffects easyeffects --gapplication` does not work, returns unknown option. 

More applications have started to misbehave now, though, so odds are the root cause of this issue has nothing to do with EE so I'll close this, and look for help elsewhere.

**Comment by wwmm** [comment]
>does not work, returns unknown option.

Sorry, it should have been `--gapplication-service`.
