### ISSUE TITLE
Mislabled Input type for Frequency in Filter

### ISSUE THREAD

**Issue by StripedMonkey** [wwmm/easyeffects#1360]
### EasyEffects Version

6.2.1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch

### Describe the bug

Easyeffects seems to be labeling the "Frequency" in a filter to be in dB, this should be in Hz unless I'm completely misunderstanding things. 2kdB sounds absurd in the first place.
![2022-01-22_20-01](https://user-images.githubusercontent.com/8009284/150660877-3c2bb175-ed05-4239-9f88-5f0590f16642.png)
https://github.com/wwmm/easyeffects/blob/master/src/filter_ui.cpp#L174

**Comment by Digitalone1** [comment]
Thank you @StripedMonkey, it has been fixed.
