### ISSUE TITLE
Start on login doesn't work

### ISSUE THREAD

**Issue by EmmanuelMess** [wwmm/easyeffects#1363]
### EasyEffects Version

6.2.1

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04

### Describe the bug

"Start at login" button doesn't work

### Expected Behavior

"Start at login" button activates after click

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Please run `flatpak run com.github.wwmm.easyeffects` and then watch the output when flipping the switch. It will tell you if it ran into a problem.

It's very likely easyeffects doesn't have permission to autostart, it was denied somehow.

At some point I will add a toast or something to make this more clear.

**Comment by vchernin** [comment]
Yeah, there are some unnecessary lv2 warnings. There should be around 10 or so, but it should be harmless.

Indeed as the warning says, run `flatpak permission-reset com.github.wwmm.easyeffects`

**Comment by EmmanuelMess** [comment]
Running `flatpak permission-reset com.github.wwmm.easyeffects` worked, I'll leave this open so that a toast is added.

**Comment by vchernin** [comment]
I think I’ll close this in favor of https://github.com/wwmm/easyeffects/issues/1249, since that already tracks the toast.

I am curious though, do you recall ever denying the background access after being asked?

**Comment by EmmanuelMess** [comment]
> I am curious though, do you recall ever denying the background access after being asked?}

Yes, it was a misclick, I realized after I reset the settings and saw the dialog.

**Comment by vchernin** [comment]
Thanks, that's good to know it wasn't denying it for no reason.

**Comment by dbkblk** [comment]
I'm sorry but it hasn't fixed the problem on my computer (Debian Testing).
`hadrien@H-FIXE:~$ flatpak permission-reset com.github.wwmm.easyeffects
hadrien@H-FIXE:~$ flatpak run com.github.wwmm.easyeffects
You have PipeWire 0.3.43 installed
This is newer or the same as PipeWire 0.3.31 required to run EasyEffects

(easyeffects:2): easyeffects-WARNING **: 14:08:53.538: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 14:08:53.538: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 14:08:53.538: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 14:08:53.538: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 14:08:54.578: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 14:08:54.578: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 14:08:54.578: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 14:08:54.578: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 14:09:01.642: portal: a background request failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L’interface « org.freedesktop.portal.Background » n’existe pas pour l’objet à l’emplacement /org/freedesktop/portal/desktop

(easyeffects:2): easyeffects-WARNING **: 14:09:01.642: portal: background portal access has likely been denied

(easyeffects:2): easyeffects-WARNING **: 14:09:01.642: portal: to let EasyEffects ask for the portal again, run flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 14:09:01.642: portal: setting autostart state and switch to false
`

**Comment by vchernin** [comment]
@dbkblk That error likely means you don't have the correct portal backend(s) installed on your system. That is usually the responsibility of the distro, it should be a hard dependency for Flatpak/xdg-desktop-portal.

What desktop environment/window manager are you using? Depending on that, make sure you have the correct packages with `apt`.

On Gnome you want:

```
xdg-desktop-portal
xdg-desktop-portal-gnome
xdg-desktop-portal-gtk
```

On KDE you want:

```
xdg-desktop-portal
xdg-desktop-portal-kde
xdg-desktop-portal-gtk
```

On wlroots you want:

```
xdg-desktop-portal
xdg-desktop-portal-wlroots
xdg-desktop-portal-gtk
```

In theory I might be able to catch this specific error and show a specific error message within EE. But likely many other apps using portals would be affected, and I doubt they would try to do that.

**Comment by dbkblk** [comment]
Thank you for the tips, but it still doesn't work.
I'm using XFCE and tried the following packages (in vain):
```
flatpak-xdg-utils
gir1.2-xdpgtk3-1.0
libportail-gtk3-1
xdg-desktop-portal (was already installed)
xdg-desktop-portal-gtk (was already installed)
```
I have no idea left.

Note: I will try to help with debian/ubuntu packaging if I find some more free time in the coming weeks.

**Comment by vchernin** [comment]
Unfortunately XFCE does not yet have a dedicated xdg-desktop-portal backend as far as I know, and the background portal backend in xdg-desktop-portal-gtk was disabled by default in Debian and upstream, since it depends on GNOME components.

https://salsa.debian.org/debian/xdg-desktop-portal-gtk/-/commits/debian/master/configure.ac

However, as a workaround xdg-desktop-portal-gnome on XFCE *might* work.

**Comment by dbkblk** [comment]
Thank you for this answer :)
I've tried on the VM and it worked.
I was worried to pull xdg-desktop-portal-gnome because it would pull gnome-shell, but without the recommended packages, it worked :)
The final solution for Debian XFCE is: `sudo apt install --no-install-recommends xdg-desktop-portal-gnome`

**Comment by vchernin** [comment]
Glad it worked :) It's not exactly ideal, eventually I imagine someone will make `xdg-desktop-portal-xfce`.

**Comment by RafaelKr** [comment]
I'm using Linux Mint 21 and run into this error

```
> flatpak run com.github.wwmm.easyeffects                                                                     
You have PipeWire 0.3.48 installed
This is newer or the same as PipeWire 0.3.41 required to run EasyEffects

(easyeffects:2): easyeffects-WARNING **: 11:55:06.133: 	preferences_general.cpp:76	portal: a background request failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Background” on object at path /org/freedesktop/portal/desktop

(easyeffects:2): easyeffects-WARNING **: 11:55:06.133: 	preferences_general.cpp:77	portal: background portal access has likely been denied

(easyeffects:2): easyeffects-WARNING **: 11:55:06.133: 	preferences_general.cpp:78	portal: to let EasyEffects ask for the portal again, run flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 11:55:06.189: 	preferences_general.cpp:99	portal: setting autostart state and switch to false
```

I completely closed easyeffects via System Monitor, ran `flatpak permission-reset com.github.wwmm.easyeffects` started it again but get the same error. I also tried to run `sudo apt install --no-install-recommends xdg-desktop-portal-gnome` and doing the same procedure afterwards without success.

Does anyone know what to do for LM 21?

**Comment by vchernin** [comment]
> sudo apt install --no-install-recommends xdg-desktop-portal-gnome

I personally always instal recommended packages, they usually provide major functionality. Could you please try install `xdg-desktop-portal-gtk` normally as `xdg-desktop-portal-gnome` is meant for gnome. What desktop are you using?

**Comment by RafaelKr** [comment]
> What desktop are you using?

I'm using Cinnamon 5.4 (on LM21)

> Do you have `xdg-desktop-portal` installed? What other `xdg-desktop-portal-*` packages for you have? Did you reboot after installing the new packages?

```
> dpkg -l | grep xdg-desktop-portal-    
ii  xdg-desktop-portal-gtk                     1.14.0-1build1                                         amd64        GTK+/GNOME portal backend for xdg-desktop-portal


> sudo apt install xdg-desktop-portal
[...]
xdg-desktop-portal is already the newest version (1.14.4-1ubuntu2~22.04.1).
```

**Comment by vchernin** [comment]
> Should I try using xdg-desktop-portal-gnome, reboot and then run the permission reset?

The permission reset won’t help if the interface simply doesn’t exist, so yeah try reboot and see what happens.

**Comment by RafaelKr** [comment]
Thanks! I did `sudo apt install --no-install-recommends xdg-desktop-portal-gnome`, rebooted, ran `flatpak permission-reset com.github.wwmm.easyeffects` and `flatpak run permission-reset com.github.wwmm.easyeffects`. Now it asked me after toggling the setting and it seems to work!

**Comment by jmaster92** [comment]
Great !!!! @RafaelKr  it works perfectly

**Comment by alexkuz** [comment]
I'm using LM 21.1, installing `xdg-desktop-portal-gnome` and resetting permissions didn't help, still getting the same error:

```
(easyeffects:2): easyeffects-DEBUG: 09:46:08.198: 	libportal.cpp:214	not doing portal sanity check, autostart switch should be disabled and shutdown switch should be enabled so no background portal access is needed
(easyeffects:2): easyeffects-DEBUG: 09:46:09.253: 	libportal.cpp:142	requesting autostart file since autostart is enabled
(easyeffects:2): easyeffects-DEBUG: 09:46:09.276: 	libportal.cpp:66	a background request failed: Background request canceled

(easyeffects:2): easyeffects-WARNING **: 09:46:09.276: 	libportal.cpp:68	Background access has been denied

(easyeffects:2): easyeffects-WARNING **: 09:46:09.276: 	libportal.cpp:69	Please allow Easy Effects to ask again with flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 09:46:09.297: 	libportal.cpp:82	due to error, setting autostart state and switch to false
```

Anything else I could do here?

**Comment by RafaelKr** [comment]
@alexkuz Did you reboot between installing `xdg-desktop-portal-gnome` and permission reset? This did the trick for me.

**Comment by alexkuz** [comment]
Yes I did.

**Comment by alexkuz** [comment]
I found out I can set background permissions manually via [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal).
Not sure why `flatpak permission-reset` thing didn't work.

**Comment by n1ckh3ll** [comment]
> Thanks! I did `sudo apt install --no-install-recommends xdg-desktop-portal-gnome`, rebooted, ran `flatpak permission-reset com.github.wwmm.easyeffects` and `flatpak run com.github.wwmm.easyeffects`. Now it asked me after toggling the setting and it seems to work!
> 
> Edit: Just tested it, EasyEffects is autostarting after a reboot 👌

Thanks from cinnamon 6.0.4  mint  21.3 in the future
