### ISSUE TITLE
Not all plugins works (pipewire)

### ISSUE THREAD

**Issue by timsofteng** [wwmm/easyeffects#1365]
### EasyEffects Version

6.1.0

### What package are you using?

Other (specify below)

### Distribution

Void linux

### Describe the bug

Not all plugins works.
E.g crossfeed works fine, but reverb, delay, eq don't.

![image](https://user-images.githubusercontent.com/51912173/151143714-ead30c41-3e8e-4025-a963-5fc672631fcb.png)
No signal.

### Expected Behavior

Plugins should work:)

**Comment by wwmm** [comment]
The reverb needs the package with Calf Studio Plugins and the delay needs the package with Linux Studio Plugins. You probably do not have them installed.

**Comment by timsofteng** [comment]
> The reverb needs the package with Calf Studio Plugins and the delay needs the package with Linux Studio Plugins. You probably do not have them installed.

Yep, you are totally right!
Thanks!
However cant find `linux studio plugins` in my repo...
How can I know which package should I install to make specific easyyeffect plugin work?

**Comment by wwmm** [comment]
>How can I know which package should I install to make specific easyyeffect plugin work?

The name of the package is something that changes in each distribution. I have no idea about how they are named on Void. But if you kill EE `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` you will see warnings about missing plugins. That should help a little.

**Comment by timsofteng** [comment]
If i can find repos for this softs it would be helpful.

**Comment by timsofteng** [comment]
Oh It is in .md
Close!
