### ISSUE TITLE
have to switch to easy effects sink output to hear the difference easy effects is making

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [wwmm/easyeffects#1369]
### EasyEffects Version

6.22

### What package are you using?

Arch (easyeffects)

### Distribution

arch linux

### Describe the bug

when using my regular device output, I don't hear any improvments in sound, but when switching to easy effects sink, I hear the sound change. 

### Expected Behavior

It should work with the regular device output. (aka your audio output, instead of easy effects sink)

### Debug Log

```
(easyeffects:7147): Gtk-WARNING **: 23:11:31.167: Unknown key gtk-button-images in /home/etaash/.config/gtk-4.0/settings.ini

(easyeffects:7147): Gtk-WARNING **: 23:11:31.167: Unknown key gtk-menu-images in /home/etaash/.config/gtk-4.0/settings.ini

(easyeffects:7147): Gtk-WARNING **: 23:11:31.167: Unknown key gtk-toolbar-style in /home/etaash/.config/gtk-4.0/settings.ini

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.267: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.268: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.268: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.268: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.407: lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.407: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.407: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.407: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: rel

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.533: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.533: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.533: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.533: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.673: lv2_wrapper: Could not find the plugin: urn:zamaudio:ZaMaximX2

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.673: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.674: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:7147): easyeffects-WARNING **: 23:11:31.674: lv2_wrapper: urn:zamaudio:ZaMaximX2 port symbol not found: rel

```
### Additional Information

restarting easy effects sometimes works, then it stops when I change the device output

**Comment by wwmm** [comment]
This is not a bug. It is how things work. Applications have to be redirected to our virtual devices.

**Comment by Etaash-mathamsetty** [comment]
> This is not a bug. It is how things work. Applications have to be redirected to our virtual devices.
I have been using easy effects for a while and things weren't like this

**Comment by wwmm** [comment]
>I have been using easy effects for a while and things weren't like this. 

Then I did not understand what you really meant. We redirect applications to our virtual devices since we were using Pulseaudio. You probably tried to say something else then.

**Comment by Etaash-mathamsetty** [comment]
> > I have been using easy effects for a while and things weren't like this.
> 
> Then I did not understand what you really meant. We redirect applications to our virtual devices since we were using Pulseaudio. You probably tried to say something else then.

so basically I easy effects used to work when I had an audio device selected in gnome settings.
Now it only works when I have easy effects sink selected in the gnome settings. Does this make sense?

**Comment by wwmm** [comment]
>Now it only works when I have easy effects sink selected in the gnome settings. Does this make sense?

No. It doesn't. The recommended way to use EasyEffects is setting your hardware as default device. With `Process All Outputs` or `Process All Inputs` enabled EasyEffects should automatically redirect applications to its virtual devices.

**Comment by Etaash-mathamsetty** [comment]
> > Now it only works when I have easy effects sink selected in the gnome settings. Does this make sense?
> 
> No. It doesn't. The recommended way to use EasyEffects is setting your hardware as default device. With `Process All Outputs` or `Process All Inputs` enabled EasyEffects should automatically redirect applications to its virtual devices.

it's really strange and nothing is reflected in the log and you haven't changed anything in your code to cause this behavior. (I am pretty sure). So this might be a regression in pipewire. (I had recently updated it)

**Comment by wwmm** [comment]
>So this might be a regression in pipewire.

Are you using `WirePlumber` or the built-in PipeWire media session manager? Maybe if you delete `~/.local/state/wireplumber/` or `~/.local/state/pipewire/` and reboot things will behave as they should again.

If you are having to set our virtual devices as default I can see only a few possibilities for the cause. The first would be not having `Process All Outputs` or `Process All Inputs` enabled in EasyEffects settings. The second would be the audio application asking the server to not allow third party applications to move them away from the default device. And the third would be the media session manager moving the applications away from our virtual devices.

**Comment by wwmm** [comment]
In any case it may help to see some EE logs. Kill it `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`.

**Comment by wwmm** [comment]
I am also on Arch Linux and using gnome. So the package versions in your system should not be the problem. IT feels like some kind of bad configuration somewhere.

**Comment by Etaash-mathamsetty** [comment]
> > So this might be a regression in pipewire.
> 
> Are you using `WirePlumber` or the built-in PipeWire media session manager? Maybe if you delete `~/.local/state/wireplumber/` or `~/.local/state/pipewire/` and reboot things will behave as they should again.
> 
> If you are having to set our virtual devices as default I can see only a few possibilities for the cause. The first would be not having `Process All Outputs` or `Process All Inputs` enabled in EasyEffects settings. The second would be the audio application asking the server to not allow third party applications to move them away from the default device. And the third would be the media session manager moving the applications away from our virtual devices.

I will try that, I use wireplumber
