### ISSUE TITLE
Installed easyeffets in Endeavour and is not starting

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#1375]
### EasyEffects Version

easyeffects 6.2.3

### What package are you using?

Arch (easyeffects)

### Distribution

Endeavour (Arch Linux based)

### Describe the bug

easyeffects wont start 

### Expected Behavior

start

### Debug Log

<details>$ G_MESSAGES_DEBUG=easyeffects easyeffects
(process:1916): easyeffects-DEBUG: 09:50:35.257: easyeffects version: 6.2.3
(process:1916): easyeffects-DEBUG: 09:50:35.260: main: locale directory: /usr/share/locale
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.268: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: system input presets directory: "/home/sergio/.config/kdedefaults/easyeffects/input"; 
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: system output presets directory: "/home/sergio/.config/kdedefaults/easyeffects/output"; 
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: user presets directory already exists: /home/sergio/.config/easyeffects/
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: user presets directory already exists: /home/sergio/.config/easyeffects/input
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: user presets directory already exists: /home/sergio/.config/easyeffects/output
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: user presets directory already exists: /home/sergio/.config/easyeffects/autoload/input
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.269: presets_manager: user presets directory already exists: /home/sergio/.config/easyeffects/autoload/output

(easyeffects:1916): Gtk-WARNING **: 09:50:35.356: Unknown key gtk-button-images in /home/sergio/.config/gtk-4.0/settings.ini

(easyeffects:1916): Gtk-WARNING **: 09:50:35.356: Unknown key gtk-menu-images in /home/sergio/.config/gtk-4.0/settings.ini

(easyeffects:1916): Gtk-WARNING **: 09:50:35.356: Unknown key gtk-toolbar-style in /home/sergio/.config/gtk-4.0/settings.ini
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.441: pipe_manager: compiled with PipeWire: 0.3.44
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.441: pipe_manager: linked to PipeWire: 0.3.44
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: core version: 0.3.44
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: core name: pipewire-0
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: found metadata: settings
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: found metadata: default
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: found metadata: route-settings
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: Audio/Sink 41 alsa_output.pci-0000_00_05.0.analog-stereo with timestamp 1643547035460745560 was added
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: Audio/Source 42 alsa_input.pci-0000_00_05.0.analog-stereo with timestamp 1643547035460814570 was added
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: Audio/Sink 80 easyeffects_sink with timestamp 1643547035460858939 was added
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.460: pipe_manager: Audio/Source/Virtual 84 easyeffects_source with timestamp 1643547035460885264 was added
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.462: pipe_manager: easyeffects_sink node successfully retrieved with id 80 and timestamp 1643547035460858939
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.462: pipe_manager: easyeffects_source node successfully retrieved with id 84 and timestamp 1643547035460885264
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.462: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, { "name": "alsa_output.pci-0000_00_05.0.analog-stereo" }
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.462: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, { "name": "alsa_input.pci-0000_00_05.0.analog-stereo" }
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.533: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.588: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.647: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.746: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.764: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.784: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.784: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.819: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.870: soe: rnnoise using the default model
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.897: soe: output_level successfully connected to PipeWire graph
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.901: soe: spectrum successfully connected to PipeWire graph
(easyeffects:1916): easyeffects-DEBUG: 09:50:35.992: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.031: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.104: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.207: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.225: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.245: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.245: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.287: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.341: sie: rnnoise using the default model
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.365: sie: output_level successfully connected to PipeWire graph
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.369: sie: spectrum successfully connected to PipeWire graph
easyeffects-INFO: 09:50:36.398: application: disabling global bypass
(easyeffects:1916): easyeffects-DEBUG: 09:50:36.407: application_ui: Icon Theme breeze detected
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
easyeffects: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

</details>

### Additional Information
I removed PulseAudio and installed Pipewire, maybe I forgot something. I cant see what.
* I am using KDE

**Comment by wwmm** [comment]
>easyeffects: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

I have never seen this error. Considering that `xcb` is involved I think you have some serious problems in lower level libraries being used by gtk. I does not look like a problem in PipeWire.

**Comment by wwmm** [comment]
>I think you have some serious problems in lower level libraries being used by gtk.

Or a serious problem in the gtk installation.

**Comment by servimo** [comment]
I will have a look

**Comment by servimo** [comment]
I found the problem, I am on a VirtualBox machineand it only accept one CPU. (strange thing)
