### ISSUE TITLE
ctrl+alt+F11 breaks EasyEffects on Ubuntu

### ISSUE THREAD

**Issue by EmmanuelMess** [wwmm/easyeffects#1376]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04

### Describe the bug

Pressing ctrl+alt+F11 and then ctrl+alt+F2 breaks EasyEffects sound.

### Expected Behavior

Pressing ctrl+alt+F11 and then ctrl+alt+F2 doesn't affect EasyEffects sound.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
I use Gnome on Arch Linux and it is even worse when I decide to switch tty. I am thrown back to the login screen. Honestly I doubt there is anything I can do about issues involving tty switching. Depending on the distribution and desktop used different things can happen. And if they are killing the audio server in the process there is nothing I can do. Implementing automatic restarting on server death is really complicated in our case.

**Comment by EmmanuelMess** [comment]
But it doesn't break with all ttys for some it seems to work.

**Comment by wwmm** [comment]
Something you can try is running EE in debug mode. First kill it `easyeffects -q` and then start it this way `G_MESSAGES_DEBUG=easyeffects easyeffects`. Maybe something interesting is shown in its logs when the problem happens.

**Comment by wwmm** [comment]
#1447 is enough to track this problem so we can close this issue.
