### ISSUE TITLE
Fails to start with PipeWire 0.3.44 - "%n in writable segment detected"

### ISSUE THREAD

**Issue by landtuna** [wwmm/easyeffects#1382]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04

### Describe the bug

I get the following when I try to start with `flatpak run`:

```
You have PipeWire 0.3.44 installed
This is newer or the same as PipeWire 0.3.31 required to run EasyEffects
*** %n in writable segment detected ***
```

### Expected Behavior

I expected the application to launch.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
What is the output of 
```
flatpak run --command=/app/bin/easyeffects com.github.wwmm.easyeffects
```

**Comment by landtuna** [comment]
```
~/third-party$ flatpak run --command=/app/bin/easyeffects com.github.wwmm.easyeffects
*** %n in writable segment detected ***
```

**Comment by landtuna** [comment]
Sorry - a reboot cleared this up. I must have had PipeWire in a bad state.
