### ISSUE TITLE
[Feature request] Add support for adding multiple instance of the same effect

### ISSUE THREAD

**Issue by TheHllm** [wwmm/easyeffects#1388]
Having two instances of the same effect can be helpful in many situations, sadly this is currently not possible. From what i can tell, the *only* problem in adding this would be having to change the manner in which the configuration is sorted, as currently the name of each effect is used as a key in the config.

**Comment by wwmm** [comment]
This is among the plans for the next big release #1316. But there is a lot of work that has to be done for that and I am not sure when I will be able to start.
