### ISSUE TITLE
Newly opened audio first contains a snippet of the previously played audio

### ISSUE THREAD

**Issue by markochk** [wwmm/easyeffects#1392]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

When starting to play a new audio/video, it'll first, for a split second, contain audio from the end of the previously played audio/video. It doesn't matter when that last audio/video was played - it could be seconds ago, hours ago, or before computer was suspended.

### Expected Behavior

Audio/video opened shouldn't start with audio from previously played audio/video.

### Additional Information

About 6 months ago I switched from PulseEffects to flatpak EasyEffects and that's when this started happening, but it wasn't bothering me too much. It still isn't a huge issue, but I decided to report it primarily for posterity.

The cause could be old hardware, as I'm using a laptop with a Sandy Bridge Intel CPU.

Here's a [video](https://webmshare.com/play/Ge1Me) where I switch between 2 youtube tabs, and when I play the second tab (which contains no audio), you could hear it start with a snippet of the first tab's audio.
This issue doesn't occur if I open EasyEffects and disable processing for that window (Firefox in this case).

Again, it's not a huge issue, but I still figured it wouldn't hurt to get it out there.

PS: sorry if I completely botched my description of the issue - I really struggled to phrase it properly and that's what caused me to delay in reporting it.

**Comment by wwmm** [comment]
This may be because the plugins still have buffers from the previous stream saved internally. Which plugins did you have enabled?

But if that is the problem I do not think there is much I could do. In the past we reset the plugins state when there were sampling rate or latency changes. But that has worse side effects. And trying to find out if it is the same stream or an older one is not doable.

**Comment by markochk** [comment]
I use equalizer, convolver and maximizer. I just tested turning them all off and enabling each one separately, and equalizer is not the problem, but convolver and maximizer each cause this issue to manifest.

I understand. It's really not a huge issue. I'll leave it up to you if you think it's better to close the issue or leave it open. Thanks for answering.
