### ISSUE TITLE
EasyEffects loses audio stream on device port changes

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1393]
### EasyEffects Version

6.2.3 git master

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

EE is not redirecting audio stream to it's processing sink after the device port is changed (I call it "port" because pavucontrol names it that way, I don't remember how it's named in PipeWire, maybe route; it's basically the change from speaker to headphones or vice versa on the same device).

This issue was not occurring before. Surely it was not happening two days ago. It should be related to the new wireplumber `0.4.8-1` update on Arch Linux.

I can easily reproduce it every time.

1. Start playing with mpv on speakers.
2. EE is processing.
2. Pause reproduction.
3. Plug in headphones.
4. Unplug headphones, return to speakers.
5. Resume reproduction.
6. EE is not processing.

Same issue starting on headphones, then unplugging and replugging in. EE sink does not receive audio stream: mpv has been redirected to default output device.

### Expected Behavior

The same as before. EE keeps getting audio stream from the player. The player is not redirected to default device on port changes.

### Debug Log

<details><summary>mpv start on headphones</summary><br/>

```
(easyeffects:2121): easyeffects-DEBUG: 22:58:36.511: pipe_manager: Stream/Output/Audio 100 mpv with timestamp 1644443916511465305 was added
(easyeffects:2121): easyeffects-DEBUG: 22:58:36.514: pipe_manager: new metadata property: 100, target.node, Spa:Id, 105
(easyeffects:2121): easyeffects-DEBUG: 22:58:36.534: pipe_manager: mpv port 99 is connected to easyeffects_sink port 84
(easyeffects:2121): easyeffects-DEBUG: 22:58:36.534: pipe_manager: mpv port 98 is connected to easyeffects_sink port 106
(easyeffects:2121): easyeffects-DEBUG: 22:58:45.069: soe: limiter latency: 0.005125 s
(easyeffects:2121): easyeffects-DEBUG: 22:58:45.076: soe: output_level: new PipeWire blocksize: 2048
```
</details>

<details><summary>pause and headphones unplugged</summary><br/>

```
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.519: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_14.2.analog-stereo"}
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.519: application: device alsa_card.pci-0000_00_14.2 has changed its input route to: analog-input-internal-mic
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.521: presets_manager: autoloading preset Empty for device alsa_input.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.522: presets_manager: loaded preset: /home/ggius/.config/easyeffects/input/Empty.json
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.556: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"easyeffects_sink"}
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.556: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_14.2.analog-stereo"}
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.556: new default input device: alsa_input.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.557: presets_manager: autoloading preset Empty for device alsa_input.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.557: presets_manager: loaded preset: /home/ggius/.config/easyeffects/input/Empty.json
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.571: pipe_manager: new metadata property: 100, target.node, , 
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.577: application: device alsa_card.pci-0000_00_14.2 has changed its output route to: analog-output-speaker
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.578: presets_manager: autoloading preset LoudnessEqualizerSpeaker for device alsa_output.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.579: soe: pipeline latency: 0.000000 ms
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.579: soe: disconnecting the crossfeed filter from PipeWire
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.582: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_14.2.analog-stereo"}
**(easyeffects:2121): easyeffects-DEBUG: 22:59:02.591: pipe_manager: mpv port 99 is connected to alsa_output.pci-0000_00_14.2.analog-stereo port 42**
**(easyeffects:2121): easyeffects-DEBUG: 22:59:02.591: pipe_manager: mpv port 98 is connected to alsa_output.pci-0000_00_14.2.analog-stereo port 44**
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.592: soe: filter successfully connected to PipeWire graph
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.646: presets_manager: loaded preset: /home/ggius/.config/easyeffects/output/LoudnessEqualizerSpeaker.json
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.667: new default output device: alsa_output.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.668: presets_manager: autoloading preset LoudnessEqualizerSpeaker for device alsa_output.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:02.684: presets_manager: loaded preset: /home/ggius/.config/easyeffects/output/LoudnessEqualizerSpeaker.json
```
</details>

<details><summary>headphones plugged in and resume mpv reproduction</summary><br/>

```
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.511: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"easyeffects_sink"}
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.519: application: device alsa_card.pci-0000_00_14.2 has changed its output route to: analog-output-headphones
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.519: pipe_manager: mpv port 99 is connected to easyeffects_sink port 84
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.519: pipe_manager: mpv port 98 is connected to easyeffects_sink port 106
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.519: presets_manager: autoloading preset LoudnessEqualizerHeadphones for device alsa_output.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.521: soe: pipeline latency: 0.000000 ms
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.521: soe: disconnecting the filter filter from PipeWire
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.533: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_14.2.analog-stereo"}
**(easyeffects:2121): easyeffects-DEBUG: 22:59:26.541: pipe_manager: mpv port 99 is connected to alsa_output.pci-0000_00_14.2.analog-stereo port 42**
**(easyeffects:2121): easyeffects-DEBUG: 22:59:26.541: pipe_manager: mpv port 98 is connected to alsa_output.pci-0000_00_14.2.analog-stereo port 44**
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.547: soe: crossfeed successfully connected to PipeWire graph
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.581: presets_manager: loaded preset: /home/ggius/.config/easyeffects/output/LoudnessEqualizerHeadphones.json
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.582: new default output device: alsa_output.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.582: presets_manager: autoloading preset LoudnessEqualizerHeadphones for device alsa_output.pci-0000_00_14.2.analog-stereo
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.599: presets_manager: loaded preset: /home/ggius/.config/easyeffects/output/LoudnessEqualizerHeadphones.json
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.757: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_14.2.analog-stereo"}
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.757: application: device alsa_card.pci-0000_00_14.2 has changed its input route to: analog-input-mic
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.770: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_14.2.analog-stereo"}
(easyeffects:2121): easyeffects-DEBUG: 22:59:26.771: new default input device: alsa_input.pci-0000_00_14.2.analog-stereo

```
</details>

**Comment by wwmm** [comment]
I have seen more problems lately with headphones connection/disconnection. I did not have time yet for a full investigation but at least on my side it seems random. Sometimes it is fine sometimes it isn't. What is the output of `pw-dot` when it happens to you? You can see the output with `xdot`. Are all the links correct?

**Comment by wwmm** [comment]
>mpv has been redirected to default output device.

Oh... That is weird...

**Comment by Digitalone1** [comment]
> What is the output of `pw-dot` when it happens to you? You can see the output with `xdot`. Are all the links correct?

I will post the output of `pw-dot`, but for now I can say that from helvum I was able to see mpv connected directly to the output device rather than EE sink. 

I'm pretty sure it is related to the last wireplumber update. I will downgrade and let you know.

**Comment by sinatosk** [comment]
I too have this issue, I downgraded to wireplumber 0.4.7 on arch linux and it's working again while not changing the version of EE itself

**Comment by Digitalone1** [comment]
> I too have this issue with wireplumber 0.48, downgraded to wireplumber 0.4.7 on arch linux and it's working again using EE 6.2.3

Thanks for testing it out, I was quite sure `0.4.7` was working properly because I played content with it not having issues.

But I switched back to pipewire-media-session. No issues with it too. The problem should be related to some new behavior of wireplumber redirecting all sinks to the new default device.

Attached [pw.dot.txt](https://github.com/wwmm/easyeffects/files/8039035/pw.dot.txt) output, it's showing the same I was seeing in helvum: mpv connected directly to output device, EE sink disconnected.

I will stick to pipewire-media-session. Honestly, never understood which benefits wireplumber is supposed to offer. When I have time I will report the issue on wireplumber gitlab.

**Comment by sinatosk** [comment]
> > I too have this issue with wireplumber 0.48, downgraded to wireplumber 0.4.7 on arch linux and it's working again using EE 6.2.3
> 
> Thanks for testing it out, I was quite sure `0.4.7` was working properly because I played content with it not having issues.
> 
> But I switched back to pipewire-media-session. No issues with it too. The problem should be related to some new behavior of wireplumber redirecting all sinks to the new default device.
> 
> Attached [pw.dot.txt](https://github.com/wwmm/easyeffects/files/8039035/pw.dot.txt) output, it's showing the same I was seeing in helvum: mpv connected directly to output device, EE sink disconnected.
> 
> I will stick to pipewire-media-session. Honestly, never understood which benefits wireplumber is supposed to offer. When I have time I will report the issue on wireplumber gitlab.

I think pipewire-media-session is some kind of reference implementation of the idea of media session and wireplumber is an intended ready to use media session implementation

I won't use pipewire-media-session because development of it is reduced/stopped

**Comment by wwmm** [comment]
>I won't use pipewire-media-session because development of it is reduced/stopped

And on top of that we may not have the option of using the built-in media session in the future. There is a clear intention of delegating this functionality to WirePlumber. So it would be good if one of you reported this to them so it gets fixed. Somehow I still could not reproduce this particular bug here on my PC.

**Comment by Digitalone1** [comment]
Reported to wireplumber devs. https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/192

> I think pipewire-media-session is some kind of reference implementation of the idea of media session and wireplumber is an intended ready to use media session implementation
> 
> I won't use pipewire-media-session because development of it is reduced/stopped

No doubts. But if these issues occur (and frankly, they are quite annoying), it means wireplumber is not stable yet, at least for being used in conjunction with EE. So it's worth to give pw media session a try until wireplumber become quite mature.

**Comment by bdaase** [comment]
It looks like I'm also affected by this.
However, in my case it's sometimes enough to make the easyeffects window visible again...

**Comment by pv** [comment]
What is the actual behavior that should be fixed?

How does easyeffect force applications to be directed to somewhere? Via setting default.configured.audio.sink in metadata, and that is no longer respected?

**Comment by wwmm** [comment]
>How does easyeffect force applications to be directed to somewhere? Via setting default.configured.audio.sink in metadata, and that is no longer respected?

No. Setting the default medata is not the best way to redirect applications output. We call `set_metadata_target_node` and ask the PipeWire's media session manager to move the stream to our virtual device. And that is working. But what @Digitalone1 reported is that WirePlumber is deciding to move the application back to the default device in some situations.

I plug and unplug headphones and micropphones to my onboard soundcard regularly but I did not notice this problem yet. So it is not obvious to me what exactly is going wrong inside WirePlumber.

**Comment by Digitalone1** [comment]
This issue will be resolved on the next wireplumber release. `wireplumber-git` already contains the fix.

https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/192#note_1287994
