### ISSUE TITLE
Multiple errors possibly related with lv2

### ISSUE THREAD

**Issue by saltasatelites** [wwmm/easyeffects#1396]
Hi.

I've Easyeffects running on ArchLinux. Update and with all dependencies installed.

Today casually, starting Easyeffects from the console it throw all these bunch of errors. I'va been googling and it seems related with lv2 more than with Easyeffects. In fact I've seen other programs with the same issue.
That's all I can say. If you need more info tell me please.

Thanks

`error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl (No es un directorio)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/librnnoise_lv2.so/manifest.ttl
`

**Comment by wwmm** [comment]
>error: failed to open file /usr/lib/lv2/librnnoise_lv2.so/manifest.ttl

That does not make any sense at all. We do not use `rnnoise` through a `LV2` plguin. We use its library directly. No LV2 involved. This error is probably a side effect of something else that might be wrong in your installation. What would it be I have no idea.

**Comment by wwmm** [comment]
Try to see if you have other software that could be using rnnoise for noise suppression. Maybe they are the ones installing a LV2 plugin related to rnnoise.

**Comment by saltasatelites** [comment]
Ok, thank you for your answer. I'm going to uninstall some programs to see which is creating the error.

**Comment by saltasatelites** [comment]
I have no idea what software have installed librnnoise_lv2.so in the LV2 folder, and how long has been there, because I never start Easyeffects directly from the console. After a few hours searching, I have done something that should never be done, delete a library, but now everything works well. Solved
