### ISSUE TITLE
I am unable to use my bluetooth speaker with EasyEffects

### ISSUE THREAD

**Issue by bigbobshotmomsbobs** [wwmm/easyeffects#1399]
This worked before with PulseEffects and PavuControl. In Pavu it would appear as an entry in the Playback tab and from there you could tell what stream to go where. (Spotify>PulseEffects. PulseEffects>Speaker) Ever since this replacement, this feature is no longer available. EasyEffects seems to only work with my internal speakers? And poorly too btw.. crackles,  the limiters seem not to function, causes some system lag..  I was informed that no one else is having this issue but me? Could I just revert my system back to before this replacement? Are there any Linux distributions still not currently using pipewire ? Whatever I have to do. I really don't like having losing functionality for an "upgrade". Thanks.

**Comment by wwmm** [comment]
What you are reporting is indeed quite unusual. So the first thing to do is killing EasyEffects `easyeffects -q` and restarting it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can have some idea of what is going on.

>In Pavu it would appear as an entry in the Playback tab and from there you could tell what stream to go where.

I do not have a bluetooth device. But as far as I know selecting the output device in Pavucontrol is still possible
![Screenshot from 2022-02-17 12-23-43](https://user-images.githubusercontent.com/16225172/154513269-49be0a67-b867-4bed-af70-61570bff606f.png)

>Could I just revert my system back to before this replacement?

Which replacement are you talking about?

**Comment by wwmm** [comment]
>Ever since this replacement, this feature is no longer available.

Do you mean those streams that were visible in Pavucontrol? They were there because GStreamer was used as a "man in the middle" doing the audio processing. In PipeWire we use its native filters and the last filter in the chain is linked to the output device. As Pavucontrol is still a Pulseaudio application you are not going to see these filters in it. You will need a PipeWire application like `Helvum`.

**Comment by bigbobshotmomsbobs** [comment]
And to be clear, in that screenshot there, EasyEffects is doing totally nothing. It isn't even registering that Spotify is playing, nothing is showing on the equalizer ? Now that I mention it.. I'm not even sure how this would function with my internal speakers anymore.. there was _just_ an update maybe that further broke whatever is going on ? I'll try testing with internal speakers now- that _was_ kinda working but also issues.. I'm more concerned with the connectivity issue first though

**Comment by wwmm** [comment]
You should have EasyEffects virtual sink and source in Pavucontrol. Are you sure you have all the PipeWire packages installed? Specially `pipewire-pulse`.

**Comment by bigbobshotmomsbobs** [comment]
lol somehow that package was not installed? I installed from the Manjaro package manager, installing that package now will try rebooting seeing what happens. As of now, pavu has nothing for easyeffects. This is a fresh install of the latest manjaro

**Comment by wwmm** [comment]
As I use Arch Linux I do not know if Manjaro is doing something unusual. In case it helps this is my current output of
```
pacman -Qs pipewire

local/easyeffects-git 6.2.3.r18.ge7b2215d-1
    Audio Effects for PipeWire Applications
local/gst-plugin-pipewire 1:0.3.46-1
    Multimedia graph framework - pipewire plugin
local/lib32-pipewire 1:0.3.45-1
    Low-latency audio/video router and processor - 32-bit client library
local/libpipewire02 0.2.7-2
    Low-latency audio/video router and processor - legacy client library
local/pipewire 1:0.3.46-1
    Low-latency audio/video router and processor
local/pipewire-alsa 1:0.3.46-1
    Low-latency audio/video router and processor - ALSA configuration
local/pipewire-pulse 1:0.3.46-1
    Low-latency audio/video router and processor - PulseAudio replacement
local/wireplumber 0.4.8-1
    Session / policy manager implementation for PipeWire
```

`WirePlumber` is there only because I am testing it. As it still has some rough edges it is probably better for you to keep using the built-in session manager package `pipewire-media-session`.

**Comment by wwmm** [comment]
`gst-plugin-pipewire` is here for other reasons. EasyEffects does not use GStreamer.

**Comment by bigbobshotmomsbobs** [comment]
Hmm seems that installing pipewire-pulse is easier said than done, I'm getting a string of dependency broken error messages, starts with saying it needs to remove pulseaudio , then from there goes to -jack -iirc then manjaro-pulse then pulseaudio-bluetooth  I'm not sure how I feel about proceeding from here. Are there any reports that indicate success using EasyEffects with bluetooth before? It is supported right?

**Comment by bigbobshotmomsbobs** [comment]
that command gave me

> local/easyeffects 6.2.3-1
    Audio Effects for Pipewire applications
local/pipewire 1:0.3.45-1
    Low-latency audio/video router and processor

**Comment by bigbobshotmomsbobs** [comment]
I switched back to Debian, problems solved. locks like the programs are back to my habitual favorites too GOOD if the devs/controllers of these apps are watching please leave them alone please please please they work fine in debian and if they get messed up again i will be upset THANK you and God bless you

**Comment by randolph-fishbowl2** [comment]
@wwmm https://steinoutward.github.io/Quhb_-PcQQuB4vAmp7WIOj7XpaIs/
