### ISSUE TITLE
[Autogain Feature Request] Allow selecting which metrics to use for the geometric mean

### ISSUE THREAD

**Issue by X-m7** [wwmm/easyeffects#1409]
### EasyEffects Version

6.2.3

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I use the autogain plugin as a way to avoid the scenario where I get my ears blown out by loud audio after having raised the system volume because I was listening to quieter stuff earlier, so ideally I can just keep the system volume fixed at a specific level. The geometric mean reference works quite well for this, however after some time the Integrated measure inevitably gets stuck at a high level (thus making quieter stuff less audible), and so I end up having to either raise the system volume or go into EasyEffects and reset the plugin's history. None of the individual measures work any better, the momentary one spikes too often too quickly (so music with distinct beats will cause a large volume spike every beat), the short-term one reacts too slowly (so I end up having to adjust the system volume anyway), and the integrated one becomes less useful over time as it moves slower and slower until it effectively freezes.

So, it appears to me that excluding the integrated value from the mean might make it work better for my use case, however at present there is no option for that. Furthermore, the integrated value in the [EBU R 128](https://en.wikipedia.org/wiki/EBU_R_128) standard (which is what the `libebur128` library implements) is meant to measure the loudness of a single program/piece/movie/etc, so it would likely not be particularly helpful in scenarios like playing though a playlist of varied songs for example. 

### Expected Behavior

An option to customise the geometric mean option is currently missing. While it would likely make the current UI for selecting the reference cumbersome I think it might need some changes anyway if additional measures like #584 and #587 are added later on.

**Comment by Digitalone1** [comment]
Hello, @wwmm can answer you on the topic. Anyway I had similar issues in the past with Autogain and ended up using a different   approach. Did you try my [Loudness Equalizer](https://github.com/Digitalone1/EasyEffects-Presets) preset?

Surely it's not perfect, but you can customize it at your need selecting different levels in the compressors or changing the equalizer parameters. I use it from two years and always had the feeling of steady volume, no need to change system level and when it's not applied I immediately recognize the sound is different in volume.

**Comment by X-m7** [comment]
> Hello, @wwmm can answer you on the topic. Anyway I had similar issues in the past with Autogain and ended up using a different approach. Did you try my [Loudness Equalizer](https://github.com/Digitalone1/EasyEffects-Presets) preset?
> 
> Surely it's not perfect, but you can customize it at your need selecting different levels in the compressors or changing the equalizer parameters. I use it from two years and always had the feeling of steady volume, no need to change system level and when it's not applied I immediately recognize the sound is different in volume.

Haven't tried that simply because I didn't find it if I just searched for "linux loudness equalization", the stuff I found just said to use EasyEffects (or PulseEffects back in the day) with no explanation whatsoever on what setup or plugins to use, even just finding out that Autogain could at least approximate what I wanted was a hassle lol. Anyway, thanks for the recommendation, I'll try it out and see if it works better.

**Comment by wwmm** [comment]
>An option to customise the geometric mean option is currently missing.

It is easy to add an option that allows the geometric mean to be calculated using only the  `momentary` and the `short-term` estimations. I will do that today. It is something I intended to do for some time. I only delayed it because I wanted to implement #584 too. But `libebur128` did not play nice with that. It allows a custom window to be set. But when I tried something like `30 s` there were bad side effects over the other estimations. If I remember well the momentary and the short-term were updated only once the custom window passed. What is not the intention.

In the past before developing the autogain plugin I used an approach based on compressors too. It was different from the one @Digitalone1 uses. Both methods have advantages and disadvantages. Personally I prefer an autogain because it changes the content's dynamic range in a larger time scale when compared to compressors, limiters and gates. The reason is that an autogain multiplies the whole audio buffer by the same correction factor. You will still loose some dynamic range over time when listening to long contents. Specially if you use one while listening to classical music. But on other musical styles and audio contents you may have a decent volume control while retaining some dynamic range.

Compressors on another hand are designed to kill dynamic range. When that is what you want compressors will outperform an autogain by far because they usually act on a shorter time scale. But when using them to control volume I feel we kill too much dynamic range in the process.

**Comment by wwmm** [comment]
@X-m7 the autogain in our master branch now has an option `Geometric Mean (MS)` that takes the average of the `Momentary` and `Short-Term` loudness. You can test it installing the AUR package.

At least to me the "MS" will be interesting when listening to streamers. For music I still think the "MSI" is a better compromise between keeping some dynamic range without being forced to touch the volume control too much.

**Comment by X-m7** [comment]
Just tried out the new `Geometric Mean (MS)` option, and it appears the one scenario where it is weak is for 0 amplitude cases (as in the equaliser display in EasyEffects is completely devoid of bars) for longer than say half a second, in that case the momentary measure goes extremely low (for example when looping this [video](https://www.youtube.com/watch?v=WVYiaboK1DI), at the end the momentary measure goes to -860), so it takes noticeably longer to drop the gain back to a more reasonable level (though still faster than I can react to bring down the volume myself). Fortunately adjusting the target appears to make that edge case less of an issue, I initially raised it to try to compensate for the integrated measure damping the gain anyway. All in all, definitely an improvement over the `Geometric Mean (MSI)` as far as I'm concerned, thanks so much @wwmm for adding the MS option!

For anyone else wondering which approach (autogain vs the @Digitalone1 compression method) would work better for managing loudness and/or trying to get something roughly like Windows' Loudness Equalization but on Linux, here's my impressions (probably oversimplified since I'm no audio geek, so no opinions on dynamic range, audio quality, etc):

### Autogain (with MS Geometric Mean reference)
Better at making quieter audio more audible, also good at keeping consistently loud audio from being too loud (thus no manual volume adjustment needed), easier to tweak (basically only the target dB), however relatively long quiet audio followed by a sudden significantly louder sound will result in a volume spike (usually stops faster than I can blink, always faster than I can react to lower the system volume).

### Compression
Better at preventing extremely loud spikes (thus no particularly uncomfortable moments), still decent at making quieter audio more audible, but far more complex to tweak (I have no real understanding of which knob does what), I found myself having to change the system volume between roughly 35-45% a lot since I couldn't find any set volume that doesn't either make consistently quiet audio too quiet or consistently loud audio too loud.

### Summary
Autogain: Hassle free except for occasionally poking your eardrums
Compression: Better for your eardrums but more tweaking needed

Both are definitely better than nothing at all (aka pushing volume to 70+% in quiet segments, eardrums explode on loud noise, drop volume to 30%, can't hear quiet segments, repeat ad infinitum).

**Comment by wwmm** [comment]
>Fortunately adjusting the target appears to make that edge case less of an issue, I initially raised it to try to compensate for the integrated measure damping the gain anyway

I always have my autogain target set to `-23 dB` and the audio players volume at 100%. So 90% of the times what my autogain is doing is reducing volumes and not amplifying them. But I imagine different adjustments may be necessary on other speakers.

>however relatively long quiet audio followed by a sudden significantly louder sound will result in a volume spike

Sudden changes to amplitude are by far the main weakness of our autogain. The main reason is that in the EBUR128 standard the `momentary` loudness is estimated using a time window of `400 ms` and the `short-term` loudness with a time window of `3000 ms`. There is plenty of time for a sudden change in amplitude to be noticeable. But as it is not reacting super fast to anything you have the chance retain more of the original content dynamic range. As everything in life there is a compromise.

My advice is that just like in the approach used by Digitalone1 you put a limiter at the end of the processing chain. That would at least protect your speakers and your ears from peaks that would go beyond `0 dB`. 

>I found myself having to change the system volume between roughly 35-45% a lot since I couldn't find any set volume that doesn't either make consistently quiet audio too quiet or consistently loud audio too loud.

And here we have the compromise again but on the compressor approach side. It will react a lot faster to sudden amplitude changes. But as we have to set on it a fixed threshold value if the average input signal amplitude deviates too much from the ones you used when setting the threshold the signal will go through way more compression than originally intended.

Automatic volume control is a tough problem to be solved in a perfect way. When you think you have finally found the "true solution" all it takes to bring you back to reality is listening to something whose musical style is very different from the one you are used too.

**Comment by wwmm** [comment]
All of this made me take a look at `libebur128` docs again. It has a function `ebur128_set_max_history` that sets the maximum history. According to its docs
```
Applies to ebur128_loudness_range() and ebur128_loudness_global() when EBUR128_MODE_HISTOGRAM is not set.
```
If I remember well histogram mode is recommended for offering better performance. What is good considering how heavy libeur128 can be. So I never really tested without it. But I am looking at it now and with the histogram mode disabled I can use
`ebur128_set_max_history` to, for example, forcing the integrated loudness to consider only the last 30 seconds. That is interesting. I am willing to give up some performance for that... I will do more tests later.

**Comment by wwmm** [comment]
The `ebur128_set_max_history` was added exactly for autogain control of live sources https://github.com/jiixyj/libebur128/pull/49. It seems it will be worth not using the histogram mode and adding to our window a `maximum history` control.

**Comment by X-m7** [comment]
Oh, apologies if my comment earlier sounded like complaining, I am aware that there won't be a perfect solution for every situation, not to mention personal preferences regarding tradeoffs (like in my case I don't mind split second spikes much if it means I can hear quieter stuff) and whatnot, I was just noting my thoughts down to help others like me better consider the options. Those volume spikes I mentioned would have been a full second or two (if not longer) of my scrambling to drop the volume manually without the autogain, so it's still a great improvement over nothing at all.

Still, thanks for the explanation, I'll see if leaving the target set to -23 dB and increasing my system volume instead works better, before I was targeting about 40% volume since that was around where I tended to leave it at without any effects applied. All my media players have always had their volume set to 100% though, I only ever adjust my system volume since that's what the hotkeys are bound to.

Being able to limit the duration of the integrated measure definitely sounds interesting, it might at least partially sort out #584 too, if anything it makes me wonder how well averaging the momentary and integrated values would work if the latter was limited to say 6-10 seconds instead of the 3 seconds that the short-term value looks at.

**Comment by wwmm** [comment]
>Oh, apologies if my comment earlier sounded like complaining, I am aware that there won't be a perfect solution for every situation,

No problems :-) It did not sound as a complaint to me.

**Comment by wwmm** [comment]
>it makes me wonder how well averaging the momentary and integrated values would work if the latter was limited to say 6-10 seconds instead of the 3 seconds that the short-term value looks at.

I will try to remember to add another option where the average of the momentary and the integrated loudness is taken.

**Comment by wwmm** [comment]
Implemented on the latest master
![Screenshot from 2022-02-24 12-31-23](https://user-images.githubusercontent.com/16225172/155555960-b906a16b-5c25-4f2b-882f-2e1ad7f546ea.png)

**Comment by wwmm** [comment]
>I only ever adjust my system volume since that's what the hotkeys are bound to.

That is what I do because I also have multimedia keys on my keyboard. I keep the audio players volume at 100 % and EasyEffects is always running. The only volume control I touch is the system volume control.

**Comment by X-m7** [comment]
So I've been using the `Geometric Mean (MI)` option with the max history at the default 15s for a bit, and it definitely avoids uncomfortable spikes far better than the MS option while still responding quite quickly. Although now with the history limit the MSI option is now viable for me too long term, so I might come back to that and see how it compares to the MI option. For what it's worth I haven't noticed any changes regarding anything performance related.

Anyway, now it looks like I'll have a far better chance at finding the ideal settings (or at least get closer to it), thanks again for all the work you've done!

**Comment by wwmm** [comment]
I think we can close this. So far the "non histogram" mode has been working really well.
