### ISSUE TITLE
Alignment of limiter plugin UI inconsistent with other plugins

### ISSUE THREAD

**Issue by BlobCodes** [wwmm/easyeffects#1417]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora Silverblue 35

### Describe the bug

The controls of the limiter plugin are aligned at the bottom of the application while all the other plugins have their controls either aligned at the top or filling the usable space.

The following two screenshots should explain it:
![Bildschirmfoto vom 2022-03-02 01-29-37](https://user-images.githubusercontent.com/14961554/156272376-c78f1d67-54ff-4fca-9287-76ce6be446fd.png)
![Bildschirmfoto vom 2022-03-02 01-29-47](https://user-images.githubusercontent.com/14961554/156272378-e3fd126d-e519-4c01-955e-d03222b2602a.png)

### Expected Behavior

All plugins have their UIs consistently aligned at the top

**Comment by wwmm** [comment]
Setting `<property name="valign">start</property>` to the Limiter template fixes this problem. But what is weird is that the interface of the other plugins do not require that to be set. I think that somewhere inside the limiter xml code there must be a container with a alignment property that is making gtk4 to assume that the rest of the ui should be at the bottom.

**Comment by BlobCodes** [comment]
I just played around with the GTK debugger, setting vexpand-set to true in this `GtkBox` seems to fix the issue.

**Comment by wwmm** [comment]
>I just played around with the GTK debugger, setting vexpand-set to true in this GtkBox seems to fix the issue.

Setting `vexpand` to true had no effect. But the thing is that this should not be necessary. It isn't on the other plugins xml. Something in the limiter xml is forcing the current behavior.

**Comment by BlobCodes** [comment]
> > I just played around with the GTK debugger, setting vexpand-set to true in this GtkBox seems to fix the issue.
> 
> Setting `vexpand` to true had no effect. But the thing is that this should not be necessary. It isn't on the other plugins xml. Something in the limiter xml is forcing the current behavior.

I set vexpand**-set** to true (which just means that vexpand was explicitly set), so in the UI file I think vexpand should be set to false to fix it.

That beaing said, the real cause of this issue should definitely be addressed instead.

**Comment by wwmm** [comment]
>I set vexpand**-set** to true (which just means that vexpand was explicitly set), so in the UI file I think vexpand should be set to false to fix it.

Oh I see. Indeed this also fixes the problem like the approach I talked about earlier also did.

>That being said, the real cause of this issue should definitely be addressed instead.

Yes. This property does not have to be set on the other plugins xml. So something in the limiter xml is forcing the current behavior and has to be fixed.

**Comment by BlobCodes** [comment]
Making the GtkBoxes with labels "SC Preamp", "Attack", "Release" and "Threshold" invisible also fixes the problem, so these seems to be the problem.

![Bildschirmfoto vom 2022-03-02 16-08-40](https://user-images.githubusercontent.com/14961554/156389211-7c2b1fb8-6ea2-4532-a093-74668c48b621.png)

**Comment by BlobCodes** [comment]
The GtkBoxes with these Labels all have vexpand=true set. Removing the vexpand fixes the problem.

https://github.com/wwmm/easyeffects/blob/ee0a518cfff8fdfe2bb04c3053826f3f558b6019/data/ui/limiter.ui#L174

https://github.com/wwmm/easyeffects/blob/ee0a518cfff8fdfe2bb04c3053826f3f558b6019/data/ui/limiter.ui#L259

https://github.com/wwmm/easyeffects/blob/ee0a518cfff8fdfe2bb04c3053826f3f558b6019/data/ui/limiter.ui#L302

https://github.com/wwmm/easyeffects/blob/ee0a518cfff8fdfe2bb04c3053826f3f558b6019/data/ui/limiter.ui#L345

**Comment by wwmm** [comment]
Thanks @BlobCodes. That was the source of the problem. There are some subtle differences in behavior between gtk4 and gtk3 when it comes to how parent containers handle children request for size. In some cases when children requests to use more vertical or horizontal size the parent widget tries to do that. I forgot to change this in the limiter xml.

I have already updated the master branch with this update.

**Comment by wwmm** [comment]
We can close this issue.
