### ISSUE TITLE
Pipewire updated yesterday.  Today, EasyEffects won't open.  Says I have an outdated Pipewire.

### ISSUE THREAD

**Issue by chrisabbeytx** [wwmm/easyeffects#1422]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Mint

### Describe the bug

I am a potato-level Linux user who should probably just go back to Windows.  I got EasyEffects using my Software Manager.  So far, I have tried removing and re-installing through the Software Manager.  I get the same message, and EasyEffects does not open.

### Expected Behavior

I expect EasyEffects to open and run.

### Debug Log

<details><summary>Debug Log</summary><br/>

Could not find compatible PipeWire.
Install PipeWire 0.3.31 or newer for EasyEffects to work correctly. 

More info:
Either PipeWire is not installed or is not recent enough for EasyEffects. 
If on Ubuntu or an Ubuntu-based system you may install newer PipeWire from: https://pipewire-debian.github.io
You may try PulseEffects which does not require PipeWire. 

If you believe this message was shown in error, please report it to: https://github.com/wwmm/easyeffectse

</details>

**Comment by chrisabbeytx** [comment]
> Please run `pipewire --version`

Thanks for your time.  I ran that, and was told that pipewire wasn't found.  That's odd, because I've been using pipewire and EasyEffects since it became available on Flathub.  But I reinstalled pipewire by the instructions in the error message, and rebooted.

I then ran your command line, and got this:

$ pipewire --version
pipewire
Compiled with libpipewire 0.3.48
Linked with libpipewire 0.3.48

**Comment by vchernin** [comment]
So, now that pipewire is reinstalled and you rebooted does EasyEffects start?

**Comment by chrisabbeytx** [comment]
No, I removed and reinstalled EasyEffects after reinstalling pipewire, but I get the same message.

**Comment by vchernin** [comment]
Could you run `pw-dump`?

**Comment by chrisabbeytx** [comment]
I just removed and reinstalled EasyEffects one more time and rebooted, and it will now launch.  Thank you again for your time.

**Comment by vchernin** [comment]
Ok, not a problem. Glad you got it working!

**Comment by chrisabbeytx** [comment]
Me too!  I love this app!

**Comment by wwmm** [comment]
It is weird that two reboots were required. But if it is working now I think we can close this.
