### ISSUE TITLE
easyeffects: symbol lookup error:

### ISSUE THREAD

**Issue by mamadouyacine** [wwmm/easyeffects#1424]
when I launch easyeffects on my fedora 35 with gnome 41, I get this error:
easyeffects: symbol lookup error: easyeffects: undefined symbol: adw_style_manager_get_default, version LIBADWAITA_1_0

**Comment by vchernin** [comment]
Did you mean gnome 41?

**Comment by mamadouyacine** [comment]
Yes gnome 41

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by vchernin** [comment]
Are you using the rpm or the Flatpak build?

**Comment by mamadouyacine** [comment]
Im using the RPM build

**Comment by wwmm** [comment]
>Im using the RPM build

Maybe all that has to be done is asking for the package maintainer to recompile the package. It seems to me that some kind of change was done to libadwaita in your distribution repository.

**Comment by mamadouyacine** [comment]
I'm using the RPM build

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by mamadouyacine** [comment]
Hi, sorry for the late answer. Everything works fine now with the official rpm build.

Thanks !
________________________________
