### ISSUE TITLE
does any smoothness option exist in spectrum visualiser?

### ISSUE THREAD

**Issue by SaicharanKandukuri** [wwmm/easyeffects#1428]
Is there is any way/Option to make the spectrum visualizer look smooth instead of a sudden spiky change 

In Math
instead of visualizing/rendering two changes in the `Y-axis` in two graphs also render some data points between them to make it look smooth

**Comment by wwmm** [comment]
Not at this moment. My knowledge about audio spectrum plugins implementation is very limited. And PipeWire's dynamic latency and sampling rate changes make improvements to it even more difficulty. So I do not know when features like the one you ask will be implemented.

**Comment by wwmm** [comment]
I have made some changes to the spectrum plugin update rate. I think that now different sampling rates finally feel the same visually. But as the solution is a little tricky this has to be tested on other systems besides mine. This together with the return of the spline interpolation that happened in the last release should help to fix this issue.

**Comment by SaicharanKandukuri** [comment]
Thanks for the update, gotta try

**Comment by wwmm** [comment]
Tomorrow I will try to add a configuration setting to our preferences window to control the update interval.

**Comment by wwmm** [comment]
I think it is as good as it can be considering the current limitations. Let's close this issue.
