### ISSUE TITLE
You're not solving the OBS problem?

### ISSUE THREAD

**Issue by sephid86** [wwmm/easyeffects#1430]
하하하하하하하
hahahahahahaha...

그럼 이 문제가 언제 해결되냐?
So when will this issue be resolved?

사용자들이 다 늙어 죽고나면 해결되냐?
Wouldn't it be resolved after all users died while waiting?

니말데로 이게 OBS 에서 변경되면 해결 될 수 있는 문제 일 수 도 있겠지
As you said, this may be a problem that can be resolved if this is changed in OBS.

근데 이 문제를 OBS 에서 언제 해결할지 너도 모르잖아.
But you don't know when OBS will solve this problem.

그럼 나중에 코딩을 다시 되돌리더라도 이 문제를 니 프로그램에서 해결하면 되잖아.
If so, you need to solve this problem now, even if you go back to the original coding later.

내가 말한 기능이 추가 된다면 이 문제가 해결된 이후에도 계속해서 쓸수 있고
If the function I mentioned is added, you can continue to use it even after this problem is resolved.

이게 다른 호환성 문제에서도 대응할수 있는 방법인데
This is a way to deal with other compatibility issues as well.

너는 OBS 가 이 문제를 해결해 줄지 어떨지도 모르면서
You don't know if OBS will solve this problem.

너는 OBS 에게만 전가 하며 외면 하고 회피하고 있을뿐이네.
You are only passing the responsibility on to OBS, turning your attention and avoiding it.

이 문제를 니가 만든 프로그램에서 해결할 방법이 있는지 찾아보거나 생각해보지 않고 문제를 해결하는것을 귀찮아 하네.
You neglect to solve the problem without looking for or thinking about whether there is a way to solve this problem in your program.

니가 만든 프로그램 앞에서 너의 프로그램 사용자들한테 꼬우면 쓰지 말던가 이거네.
You are ignoring the inconvenience of users of your program in front of your program.

비겁하다.
Therefore, you are a coward.

오만하네.
and arrogant.

니 그런 태도 맘에 안들어.
I resent your attitude towards this matter.

난 너같은 프로그래머가 되기 싫어.
I swear I don't want to be a programmer like you.
I promise not to become a programmer like you.

fhank you.

P.S

If you ask me to code

Just like you are irresponsible in this matter

For that function I need, it's enough to use Windows

Your attitude is hindering the development of Linux.

**Comment by vchernin** [comment]
Avoiding workarounds for issues easily resolved elsewhere is spending time wisely. That time could instead be spent on fixing issues specific to EasyEffects.

If software always implemented workarounds for other software, it would become a unmaintainable mess. It’s not a sane long term strategy.

I understand the frustration when things don’t work but this issue doesn’t add anything useful.

**Comment by sephid86** [comment]
> 

The method I have proposed is not simply a way to solve the problem of one OBS.

This helps with compatibility with other programs that are experiencing similar problems.

You did not specifically answer in which aspect the method I proposed has a problem.

It simply avoided that OBS had to solve it.

that makes me mad

All users will be in Silvertown if other programs don't allow for temporary workarounds during the standards-compliant transition period.

**Comment by sephid86** [comment]
Hey. then teach me

You said you only need to edit one or two lines of code in OBS.

which line

I will compile and use it myself.

**Comment by wwmm** [comment]
While I understand OBS users are frustrated I will not rewrite our code in a way that is essentially useful only for OBS. Specially when it is super simple to set a id for an audio stream. And if you do not believe me just take a look at a very old PulseEffects code from the time we used GStreamer streams https://github.com/wwmm/easyeffects/blob/4ec1f83b4318c7210327cc8b60f87c3d3ebaf509/src/source_output_effects.cpp#L70. 

I am totally willing to extend our blocklist functionality with the usage of the `application.id` tag if OBS starts to use it. But I am not complicating our code blocklist code to workaround the fact OBS is using the `media tag` for this task.

Oh! And remember. EasyEffects is not a product developed by a company. It is a project done by volunteers for free in their free time. Have that in mind before making demands like you were our boss.

**Comment by sephid86** [comment]
thank you sir.

**Comment by wwmm** [comment]
>impossible to unsubscribe this ??

As far as I could see I can't unsubscribe people. I think the only way is if the user click in the `Unsubscribe` button that is in the issue's right side panel.
