### ISSUE TITLE
6.2.4+: pipewire-dependency version bump required

### ISSUE THREAD

**Issue by mkszuba** [wwmm/easyeffects#1434]
### EasyEffects Version

6.2.4

### What package are you using?

Other (specify below)

### Distribution

compiled by hand on Gentoo Linux

### Describe the bug

For quite a while now easyeffects has depended on pipewire 0.3.31 or newer; from what I can see in `src/meson.build` this is still the case even on the Git master branch. However, since version 6.2.4 the source file `pipe_manager.cc` references the symbol `PW_KEY_OBJECT_SERIAL` - which has only been available in pipewire since version 0.3.41.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Indeed, I also ran into this with the Flatpak build. Although I have only tested 0.3.47 for now I’m sure it’s the same issue.

**Comment by vchernin** [comment]
This can be closed: fce164ee2aaebeeebd72e711187abbbc48a1b1e6
