### ISSUE TITLE
Headless dynamic configuration

### ISSUE THREAD

**Issue by nab-os** [wwmm/easyeffects#1437]
Hi,

I'm looking for a way to control plugin inputs, volumes, enable & disable apps, etc from a CLI or another application through D-Bus, CLI commands, sockets or any other way.

Being able to dynamically change parameters without GUI access would be very useful for example for video or music streaming setups.
Also it would be nice to be able to get current parameter values to use them in other applications.

Would that be possible to implement, and can we discuss on how to do it ?

**Comment by nab-os** [comment]
After looking at the code I would propose using a [local socket with AF_LOCAL](https://www.man7.org/linux/man-pages/man2/socket.2.html) and sending commands through it. 
Commands could look like this:
`[output|input] <plugin_name> [get|set] <parameter> <value>`
We would need to add a way for plugins to handle a parameter set or get

What do you think of this ?

**Comment by Digitalone1** [comment]
You could get, set and change plugin parameters through gsettings command line utility. For application volume, there's nothing by EasyEffects, but you could change them through specific Pipewire commands.

**Comment by nab-os** [comment]
Ho ! I didn't know about gsettings, thanks you very much !

**Comment by wwmm** [comment]
I talked a little about this in this discussion https://github.com/wwmm/easyeffects/discussions/916. The same idea remains on EasyEffects.
