### ISSUE TITLE
Is it possible to set persisting per app volume levels?

### ISSUE THREAD

**Issue by colourfuloctopus** [wwmm/easyeffects#1443]
I don't know how EA controls the volume levels so perhaps this is outside of its scope but I've been having an irritating issue with MPD reseting volume levels when switching tracks and the MPD devs do not seem too concerned so I'm looking for other solutions. 

At the moment EA volume levels seem to reset when rebooting. Other applications - like MPD - seem to be able to control it as well. In an ideal world I'd like to be able to set a volume level and lock it so it persists and nothing but EA could alter it. If this is not possible with EA - is there another application or method to achieve this with Pipewire?

Thanks in advance.

**Comment by wwmm** [comment]
>so perhaps this is outside of its scope

unfortunately it is out of our scope. In the same way ti is out of the scope of other applications like Pavucontrol. Depending on how PipeWire is configured on your computer you will have to contact PipeWire's developers or `WirePlumber's` developers if you are using it as media session manager.

The audio server is the one responsible for restoring volumes or deciding if it should be possible to change them or not. The most we can do is showing a control to set the value.
