### ISSUE TITLE
Sound crackling

### ISSUE THREAD

**Issue by Cpt-Dingus** [wwmm/easyeffects#1448]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

KUbuntu 20.04.4

### Describe the bug

Any sound coming through EasyEffects (even without modules) comes out crackled. This does not happen if I close EasyEffects or just feed audio through my headset and not the EE sink. 
Video of test tone at 990hz: https://streamable.com/zpz96v

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>(even without modules) comes out crackled.

That may be a sign something is not right in PipeWire. The reason is that without any plugin added in our window the effects pipeline is essentially passin through data
```
audio application -> virtual device -> output level meter -> spectrum
```

The output level meter and the spectrum plugin do not apply any change to the data. And our virtual device is just a PipeWire `null-sink`. In other words our virtual device comes from PipeWire code.

**Comment by wwmm** [comment]
In any case kill EasyEffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see some logs.

**Comment by Cpt-Dingus** [comment]
Hello, i was able to recreate the bug even after running the aforementioned command, this is the output of enabling the debug log https://pastebin.com/byJGXXg5. I have ran this for a few minutes with it still doing the crackling without showing anything on the log. I may have run the log incorrectly, although I hope that is not the case.

**Comment by wwmm** [comment]
The log is too short. Try to put `G_MESSAGES_DEBUG=easyeffects` before `/usr/bin/flatpak`

**Comment by Cpt-Dingus** [comment]
Sorry for late response, but I haven't been able to reproduce the issue since the post. A library update probably fixed it.
