### ISSUE TITLE
Feature request: show peak output volume

### ISSUE THREAD

**Issue by 1player** [wwmm/easyeffects#1452]
It would be nice if the UI would show the maximum output dB ever seen, to be able to tell if audio is or has been clipping, or not. Many DAWs offer a similar functionality, and I'm not sure how it is called. My suggestion is, on the status bar, next to the current output dB that's constantly changing, to show the maximum dB output for both channels, and can be reset to -100 (or -inf) dB by clicking on it.

Use case: I'm using a custom equalization curve for my headphones (from https://github.com/jaakkopasanen/AutoEq) using the Convolver plugin, and due to equalization the input volume has to be reduced a little to avoid clipping. Right now there is no way for me to tell what is the maximum output dB my system is pushing out, and if I need to lower the input volume further or I can raise it.

**Comment by Digitalone1** [comment]
Hello @1player 

I don't think it's a useful feature since the application ship a limiter to avoid clipping.

**Comment by 1player** [comment]
A limiter introduces distortion, it's not a good solution when I'm trying to equalise some high-end headphones.

Knowing how much your output clips by, and reducing the input volume is much better, but it requires this feature which is present in most DAWs and mixers because of its usefulness.

**Comment by 1player** [comment]
Here's an example of such feature in Ableton: the `-Inf` gauge in the mixer indicates the peak output volume. To avoid distortion one would reduce the input so that it's always below 0 dB, or bad things happen.

<img width="381" alt="SessionViewMixer" src="https://user-images.githubusercontent.com/690120/160381923-2ad4ad2a-3b51-4c02-b99e-f504e3f70a8d.png">

**Comment by Digitalone1** [comment]
It's not really useful for most of the users, which does not mean it won't be ever introduced.

Maybe in a specific pop over menu in the bottom bar. Honestly, filling that bar with other two level meters and a reset button seems overkill. In a pop over menu near the global level meter could be done.

**Comment by wwmm** [comment]
I think the main problem is space in the window for this. DAWs usually have this but they are software with a different purpose and target public. So their graphical interface is designed in a way that has space for things like this.

I will keep this open and with an `enhancement` tag. As the interface is right now I do not think there is space in the window for historical peaks. But who knows how our window be in the future. It has changed a lot along the years.

**Comment by 1player** [comment]
It doesn't need to be obtrusive, I reckon it's pretty simple to implement. Attached is a mockup.

![mockup](https://user-images.githubusercontent.com/690120/160414788-673db280-4d4c-4732-94fb-ca0038717652.jpg)

The important functionality is that the peak figure can be reset by clicking on it.

**Comment by NicolasLM** [comment]
> It's not really useful for most of the users.

Anecdotal but I struggled while setting my microphone gain after effects. Most level recommendations out there are given for peak values, like having the loudest peak at -6 dBFS for example. Unfortunately easyeffects does not present this information in a user friendly manner (it is here but just moves too quickly for a person to process).

Another piece of evidence that this feature is actually quite useful is that most audio interfaces with meters hold the highest peak for about a second so that they are easily visible to the user.

**Comment by 1player** [comment]
Yeah, the few times a year I need to set up my audio devices, I wish this feature was present. 

It's not that hard to implement at all, it's just a matter of remembering the max dBm value seen and presenting it. I did try to write a PR, but abandoned it because I'm not comfortable with neither C++ nor GTK.

**Comment by Digitalone1** [comment]
> Yeah, the few times a year I need to set up my audio devices, I wish this feature was present.
> 
> It's not that hard to implement at all, it's just a matter of remembering the max dBm value seen and presenting it. I did try to write a PR, but abandoned it because I'm not comfortable with neither C++ nor GTK.

Write it in pseudo code, maybe we can implement it.

I also remember another user suggesting a button to reset this maximum (rather than auto updating it after an amount of time).

**Comment by wwmm** [comment]
The new level meter plugin remembers the true peak. We can close this issue.
