### ISSUE TITLE
Every boot easyeffects dont start correctly. 

### ISSUE THREAD

**Issue by CBx86** [wwmm/easyeffects#1453]
### EasyEffects Version

EasyEffects 6.2.4

### What package are you using?

Fedora

### Distribution

Fedora 35

### Describe the bug

Hey guys!

Every time i boot, EasyEffects Sink appear set. 
Ok.
But dont have sound. 
If i set "Line Out" - Sound works!
And set "EasyEffects Sink" all works fine! Until next reboot.

Many Thanks!

### Debug Log

<details><summary>Debug Log</summary><br/>

```
/var/log/messages

Mar 29 10:13:31 quati plasmashell[1365]: org.kde.plasma.pulseaudio: No object for name "easyeffects_sink"
Mar 29 10:13:31 quati plasmashell[1365]: org.kde.plasma.pulseaudio: No object for name "easyeffects_sink"
Mar 29 10:13:31 quati systemsettings5[6861]: org.kde.plasma.pulseaudio: No object for name "easyeffects_sink"
Mar 29 10:13:31 quati systemsettings5[6861]: org.kde.plasma.pulseaudio: No object for name "easyeffects_sink"

```
</details>

**Comment by wwmm** [comment]
What you describe is suspiciously similar to #1451. Are you using KDE?

**Comment by CBx86** [comment]
Ops. 
Looks the same. 
I did a search and didn't find it when I opened the issue. 
Sorry. 
Many Thanks!

**Comment by wwmm** [comment]
No problems. As you have already added comments on the other one we can close this issue.
