### ISSUE TITLE
PulseEffects Legacy Trace/breakpoint trap (core dump) during start up

### ISSUE THREAD

**Issue by JesseLimerick** [wwmm/easyeffects#1468]
### EasyEffects Version

4.8.5.r1.g4ec1f83b-2

### What package are you using?

Other (specify below)

### Distribution

Arch Linux

### Describe the bug

After some updates and a reboot, pulseeffects-legacy fails to start.

I get this error when attempting to start the program:
`(pulseeffects:8213): GLib-GIO-WARNING **: 19:57:10.789: Unable to look up enum nick ‘Downward’ via GType

(pulseeffects:8213): GLib-GIO-ERROR **: 19:57:10.789: The schema default value for key 'mode' in schema 'com.github.wwmm.pulseeffects.compressor' was rejected by the binding mapping function.
Trace/breakpoint trap (core dumped)`

I have tried both the git version and the standard version, recompiled PulseEffects and still have the issue.

### Expected Behavior

The program should start.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:15207): pulseeffects-DEBUG: 20:02:39.768: main: locale directory: /usr/share/locale
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.781: presets_manager: system input presets directory: "/etc/PulseEffects/input";
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.781: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input";
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.781: presets_manager: system output presets directory: "/etc/PulseEffects/output";
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.781: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output";
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.781: presets_manager: user presets directory already exists: /home/jll/.config/PulseEffects
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.782: presets_manager: user presets directory already exists: /home/jll/.config/PulseEffects/input
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.782: presets_manager: user presets directory already exists: /home/jll/.config/PulseEffects/output
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.782: presets_manager: user presets directory already exists: /home/jll/.config/PulseEffects/autoload
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.857: application: PE version: 4.8.5
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.858: pulse_manager: context is connecting
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.858: pulse_manager: context is authorizing
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.859: pulse_manager: context is setting name
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.860: pulse_manager: context is ready
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.860: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.860: pulse_manager: protocol version: 35
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: Pulseaudio version: 15.0
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: default pulseaudio sink audio format: s32le
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: default pulseaudio source sampling rate: 48000 Hz
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.861: pulse_manager: default pulseaudio source audio format: s32le
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.893: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:15207): pulseeffects-DEBUG: 20:02:39.893: sie: using output device: alsa_output.pci-0000_00_1b.0.analog-stereo

(pulseeffects:15207): GLib-GIO-WARNING **: 20:02:39.933: Unable to look up enum nick ‘Downward’ via GType

(pulseeffects:15207): GLib-GIO-ERROR **: 20:02:39.933: The schema default value for key 'mode' in schema 'com.github.wwmm.pulseeffects.compressor' was rejected by the binding mapping function.
Trace/breakpoint trap (core dumped)
```
</details>

### Additional Information

I've been using PulseEffects legacy with no issues, since pipewire easyeffects became a thing

**Comment by wwmm** [comment]
>The schema default value for key 'mode' in schema 'com.github.wwmm.pulseeffects.compressor' was rejected by the binding mapping function.

It seems something has changed in the compressor plugin. I will have to investigate. In the mean time run `pulseeffects -r` to reset its settings. With lucky the other plugins will still work and the problem happens only when the compressor is loaded.

**Comment by wwmm** [comment]
>It seems something has changed in the compressor plugin

That is not it. It seems something has changed in gtk3 or gtkmm3. Weird...

**Comment by JesseLimerick** [comment]
Unfortunately I still have the same issue with `pulseeffects -r`

**Comment by vchernin** [comment]
I recall when I tried updating the Flatpak runtime to 42 (or 21.08) I noticed similar key complaints. It is fine for now since it is on the older runtime..

I can reproduce when I update the pulseeffects extension runtime, since the LSP flatpak extension got updated,  from [1.1.30](https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP/commit/4ac0475ef0b9853623c280a9aa9bda97e24d1b83) to https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP/commit/7a0874fc6046b0293971f81aa3f9a74234d11cca.

**Comment by vchernin** [comment]
As a workaround, I could probably continue using the bundled LSP indefinitely in pulseeffects, and not mounting the extension so pulseeffects doesn't find it. It doesn't seem worth the hassle.

**Comment by wwmm** [comment]
I was able to reproduce the issue here on my computer. With the new LSP version one of the compressor parameters has slightly different names for some of the possible enum values. The only reason why EasyEffects is not crashing is because it interacts with the plugin in a different way. It uses the numerical values instead of the string values. Only the string have changed.

**Comment by wwmm** [comment]
I release a new PulseEffects version `4.8.6`. It fixes the problem on my computer.

**Comment by JesseLimerick** [comment]
`4.8.6` fixes the problem, thank you!

**Comment by Arthur-D** [comment]
Just wanna comment for anyone else doing a web search that Kubuntu 22.04 has the 4.8.4 version with this issue in the repos, so for anyone experiencing it switching to the Flatpak solves it.
