### ISSUE TITLE
Why does Pulseeffects converts all audio to float32le 48kHz? Is it possible to change to reduce cpu usage?

### ISSUE THREAD

**Issue by Maccer1** [wwmm/easyeffects#1474]
In the top bar I see:

![image](https://user-images.githubusercontent.com/8525464/162628463-9617eb1a-a358-4afd-9f3c-214622fcaa42.png)

Why does it convert to float32le if then it has to go back to s16le? Does this conversion impact CPU usage? Is it possible to avoid this conversion?

**Comment by wwmm** [comment]
>Why does it convert to float32le if then it has to go back to s16le?
>Is it possible to avoid this conversion?

The vast majority of audio plugins use only `float32` as format. So there this conversion has to be done.

>Does this conversion impact CPU usage?

I never saw a situation where the conversion from `16 bits integers` to `32 bits float` could be noticed in the CPU usage. Usually only sampling rate conversions are heavy enough cause visible changes in the CPU utilization.

You have no reason to worry about a conversion from `16 bits integers` to `32 bits floats`. If I am not mistaken the most it is going to happen is having some of the extra bits in the float number set to zero. When going from 32 bits to 16 bits you may be loosing information if the 32 bits data comes from a a recording that was actually done with 32 bits. Most of the 32 bits files you wil see  on everyday life are actually 16 bits material converted to 32 bits. In this case it is fine to go from 32 to 16.

**Comment by wwmm** [comment]
I have changed the title not only because thee image is from PulseEffects. The processing chain is a little different in EasyEffects. But the fact that the filters work only with `float 32` remains.

**Comment by wwmm** [comment]
In case you are seeing high CPU usage have in mind that some plugins algorithm are indeed heavy on resources. The conversion from 16 to 32 bits has nothing to do with this.
