### ISSUE TITLE
EasyEffects Trace/breakpoint trap during start up

### ISSUE THREAD

**Issue by tilkomp** [wwmm/easyeffects#1483]
### EasyEffects Version

easyeffects 6.2.4-1 

### What package are you using?

Arch (easyeffects)

### Distribution

Artix Linux 

### Describe the bug

tried to install easyeffects only to be met by this error

(easyeffects:28846): Adwaita-WARNING **: 02:47:27.788: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(easyeffects:28846): easyeffects-ERROR **: 02:47:27.810: pipe_manager: context connection failed
Trace/breakpoint trap

### Expected Behavior

program should start

### Debug Log

(process:28824): easyeffects-DEBUG: 02:46:52.441: easyeffects version: 6.2.4
(process:28824): easyeffects-DEBUG: 02:46:52.443: main: locale directory: /usr/share/locale
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: system input presets directory: "/home/tilkomp/.config/kdedefaults/easyeffects/input"; 
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: system output presets directory: "/home/tilkomp/.config/kdedefaults/easyeffects/output"; 
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: user presets directory already exists: /home/tilkomp/.config/easyeffects/
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: user presets directory already exists: /home/tilkomp/.config/easyeffects/input
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: user presets directory already exists: /home/tilkomp/.config/easyeffects/output
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: user presets directory already exists: /home/tilkomp/.config/easyeffects/autoload/input
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.445: presets_manager: user presets directory already exists: /home/tilkomp/.config/easyeffects/autoload/output

(easyeffects:28824): Adwaita-WARNING **: 02:46:52.506: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.523: pipe_manager: compiled with PipeWire: 0.3.48
(easyeffects:28824): easyeffects-DEBUG: 02:46:52.523: pipe_manager: linked to PipeWire: 0.3.49

(easyeffects:28824): easyeffects-ERROR **: 02:46:52.527: pipe_manager: context connection failed
Trace/breakpoint trap

**Comment by wwmm** [comment]
>pipe_manager: context connection failed

This kind of error usually happens when something is broken or missing in PipeWire.
