### ISSUE TITLE
Misalignment between plugins name and actual plugin

### ISSUE THREAD

**Issue by Neo595** [wwmm/easyeffects#1488]
Hello (again)
Thanks for the great job.
Now the "avoid resampling" feature is working smoothly...
Distro ubuntu 22.04 / 64b / Mate
pipewire 0.35
easyeffects 6.2.4

When I selected the "volume" plugins  the displayed interface seems to be "loudness" plugins interface.  Everything can be tuned, however, the output sound is not affected by the loudness correction (any setting changes the output).
By the way, I don't have the loudness plugins in the list, only the bass loudness (quite effective).

![volume_plugins](https://user-images.githubusercontent.com/25134439/164220599-3c850f3d-968f-4b9b-9359-7a2656e6c326.png)
[pw-dump.txt](https://github.com/wwmm/easyeffects/files/8521050/pw-dump.txt)
Regards.

**Comment by wwmm** [comment]
>the output sound is not affected by the loudness correction

Did you set the `output volume` to something different from `0.0 dB`? If I am not mistaken this plugin only acts when a value different from zero is used there.

>When I selected the "volume" plugins the displayed interface seems to be "loudness" plugins interface.

Sounds like a problem in the translation. As it isn't a language I speak someone that does will have to help to improve it.

**Comment by wwmm** [comment]
As this has to be fixed in the language translation this issue can be closed. Someone that knows the language has to improve the translation in weblate.
