### ISSUE TITLE
Changing points size in spectrum preferences crashes the app

### ISSUE THREAD

**Issue by rail01** [wwmm/easyeffects#1495]
### EasyEffects Version

6.2.4

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Whenever I try to change spectrum's points size in EasyEffects' preferences, the app crashes either immediately or after clicking +/- a few times. I noticed the problem occurs more often when changing the value of points size down rather than up.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(easyeffects:44346): easyeffects-DEBUG: 17:05:54.691: convolver_box: max fft frequency: 22040.205078
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'env G_MESSAGES_DEBUG=easyeffect…' terminated by signal SIGABRT (Abort)
```
</details>

### Additional Information

- Session: X.org
- DE: Xfce 4.16
- OS: Arch
- Kernel: 5.17.4-arch1-1

**Comment by Digitalone1** [comment]
`6.2.5` released. The issue can be closed.
