### ISSUE TITLE
Doesn't let me change some configuration options

### ISSUE THREAD

**Issue by sph3** [wwmm/easyeffects#1500]
### EasyEffects Version

6.2.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04

### Describe the bug

It doesn't let me change the first two options in the settings:
- Start service at login
- Shutdown on window close

I click on the toggle and it just goes back to the original state.

### Expected Behavior

It should change the config.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Known quirk with the Flatpak build, I have a patch to give an message when this happens I just haven’t had the time to push it.

**Comment by sph3** [comment]
Thanks for the response. But is there any way I can toggle these settings?

**Comment by vchernin** [comment]
`flatpak permission-reset com.github.wwmm.easyeffects` and then try the switches

**Comment by sph3** [comment]
Still not working :(

**Comment by vchernin** [comment]
what is your `xdg-desktop-portal` version? 1.14.x currently has a bug which breaks the portal we use.

**Comment by sph3** [comment]
I don't have any `xdg-desktop-portal`.

**Comment by vchernin** [comment]
You do not have the xdg-desktop-portal package installed? It is a dependency of Flatpak.

**Comment by vchernin** [comment]
I assume pop os just reused Ubuntu's packages, which in this case is indeed the broken 1.14.3 https://packages.ubuntu.com/search?keywords=xdg-desktop-portal&searchon=names&suite=jammy&section=all

**Comment by sph3** [comment]
So I'll just have to wait for them to update it?

**Comment by vchernin** [comment]
> So I'll just have to wait for them to update it?

Indeed I don’t see how the autostart file requests will ever work until it is updated.

In the meantime please try https://github.com/flathub/com.github.wwmm.easyeffects/issues/3#issuecomment-908632842 if you haven’t already.

**Comment by vchernin** [comment]
FYI xdg-desktop-portal 1.14.4 will fix the autostart file issue, and there is now a user-friendlier warning in flathub stable (well in a couple hours). 

It's not super helpful, but there isn't an easy way (that I'm aware of) to open the settings app to show easyeffects' background permission switch. Nor do we have a helpful way of handling errors if the background portal is not implemented (portal backend too old probably). it simply can't work.

**Comment by sph3** [comment]
> Pop!_OS 22.04 issue regular linux : /usr/lib/xdg-desktop-portal Pop!_OS 22.04 : /usr/libexec/xdg-desktop-portal
> 
> my temporary solution
> 
> ```shell
> gedit /home/$USER/.var/app/com.github.wwmm.easyeffects/config/glib-2.0/settings/keyfile
> ```
> 
>     1. change **enable-autostart=true**
> 
>     2. change **shutdown-on-window-close=false**
> 
> 
> **WARNING** : don't open **preferences** menu because will reset above change
> 
> Auto startup
> 
> ```shell
> ln -s /var/lib/flatpak/exports/share/applications/com.github.wwmm.easyeffects.desktop ~/.config/autostart
> ```

Thanks! I thought editing the keyfile didn't work because when I opened the Preferences menu it was unchanged.

**Comment by synvie92** [comment]
> > Pop!_OS 22.04 issue regular linux : /usr/lib/xdg-desktop-portal Pop!_OS 22.04 : /usr/libexec/xdg-desktop-portal
> > my temporary solution
> > ```shell
> > gedit /home/$USER/.var/app/com.github.wwmm.easyeffects/config/glib-2.0/settings/keyfile
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. change **enable-autostart=true**
> > 
> > 2. change **shutdown-on-window-close=false**
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **WARNING** : don't open **preferences** menu because will reset above change
> > Auto startup
> > ```shell
> > ln -s /var/lib/flatpak/exports/share/applications/com.github.wwmm.easyeffects.desktop ~/.config/autostart
> > ```
> 
> Thanks! I thought editing the keyfile didn't work because when I opened the Preferences menu it was unchanged.

after edited keyfile will work fine, **don't open/edit preferences menu because will reset keyfile changed and UI display no changed possible bug**, other function work fine.

below command check for work in background and startup
```shell
top | grep easyeffect
```

**Comment by xdubx** [comment]
my savefolder is under the user folder
```shell
ln -s ~/.local/share/flatpak/exports/share/applications/com.github.wwmm.easyeffects.desktop ~/.config/autostart

```

**Comment by vchernin** [comment]
This was an incorrect portal backend setup in pop os, it should be fixed now.

**Comment by Booligoosh** [comment]
Can confirm it's fixed in Pop!_OS now, thank you 👍

**Comment by sph3** [comment]
It is fixed.
