### ISSUE TITLE
Spectrum view needs a fixed Y axis

### ISSUE THREAD

**Issue by 1player** [wwmm/easyeffects#1512]
The current spectrum view has a dynamic Y axis, depending on the volume of the loudest frequency. As such, it's impossible to distinguish between low volume and high volume moments, as they're all "maximised" in the spectrum view.

It would be great if the Y axis were fixed (from -100 to 0 dB), so that it's easier to parse and use it for, e.g. EQing out an annoying frequency, like every other spectrum analyzer does.

**Comment by wwmm** [comment]
Some kind of option will have to be added to our settings window to control this. For the general spectrum use a fixed scale will be useless when signal levels are too low.

**Comment by wwmm** [comment]
I have updated our master branch with a new spectrum option that allows the dynamic scale to be disabled. When this is done the chart code will use the global maximum and minimum to do the drawing. As the global max/min do not change often this has almost the same effect as having a static scale. Alternating the setting between on and off resets the global max/min.

I think we can finally close this issue.
