### ISSUE TITLE
New app icon?

### ISSUE THREAD

**Issue by bertob** [wwmm/easyeffects#1520]
The current icon doesn't quite fit the HIG, would you be interested in help with a new one?

Here's a first attempt at making the current metaphor a bit more HIG-compliant, but we could also try something completely different.

![image](https://user-images.githubusercontent.com/1908896/167961868-9d395230-cc1f-4fab-8d6b-be88c9c9ee55.png)

**Comment by wwmm** [comment]
>would you be interested in help with a new one?

Yes. Any improvement to the icon is welcome :-). Specially considering I have no knowledge about icon designing. We just have to keep in min situations like https://github.com/wwmm/easyeffects/issues/867#issuecomment-1056077158. It took years for our icon to be compatible with QT desktops. It would be good to have a new icon that still works there.

**Comment by wwmm** [comment]
>but we could also try something completely different.

I am open to new ideas. But I like the one in your preview image.

**Comment by Digitalone1** [comment]
I like the current icon, but also the one in the preview is nice.

Which rules specifically the current icon does not fit?

**Comment by vchernin** [comment]
There are some docs here: https://developer.gnome.org/hig/guidelines/app-icons.html

It makes sense to change it since currently PulseEffects and EasyEffects share the same icon, despite being increasingly different.

**Comment by ceiphr** [comment]
That icon is gorgeous! @bertob if you don't mind, is there somewhere I can find the icon in your preview image?
