### ISSUE TITLE
Fonts in GUI are very fuzzy

### ISSUE THREAD

**Issue by VorpalBlade** [wwmm/easyeffects#1523]
### EasyEffects Version

6.2.5

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Fonts in the easyeffects GUI are very fuzzy and "blotchy". It does not look like just an artefact of ignoring the hinting settings in fontconfig for example, but rather like the image has been scaled down and then upscaled or something. It is very strange looking.

* I'm using KDE and thought it might be a Gnome program issue, but other Gnome/GTK programs render just fine. I tested bless (hex editor) and Gimp (the only other GTK programs I have installed).
* I'm not using any high DPI screens or fractional scaling. Just basic old low-DPI laptop with a low-DPI external monitor hooked up.
* It doesn't matter which monitor I'm displaying the program on. The laptop screen is marginally higher DPI so it is not quite as obvious there, but it is still "fuzzy and blotchy".
* I'm using X11 (as I'm on a nvidia 10-series GPU)

Here is a screenshot:
![image](https://user-images.githubusercontent.com/3315306/168343385-3c2252ca-b0c8-4d58-bebb-24fc7497859c.png)

Zoomed out like here the difference is not at all visible. I suggest opening the image directly to see it at full size. I also noticed I can't really see the problem if I zoom in heavily in Gimp. The issue is basically only visible at "native" size (and will thus likely be hidden if you have a high DPI screen).

Here is a detail of the image showing the issue: 
![image](https://user-images.githubusercontent.com/3315306/168344196-e8e2ace3-bbb5-4a99-a4b9-5e01d3b7490c.png)

Relevant font settings (from the KDE settings, I assume GTK apps pick this up as well, since at least bless and Gimp seem to?):
* System font: Dejavu Sans
* Full hinting
* Greyscale antialiasing

### Expected Behavior

The font rendering should be "sensible" even if you do not have a high DPI screen.

### Debug Log

<details><summary>Debug Log</summary><br/>

I don't believe there is anything relevant here, but I included it just in case.

```
$ G_MESSAGES_DEBUG=easyeffects easyeffects 
(process:7400): easyeffects-DEBUG: 20:24:59.168: easyeffects version: 6.2.5
(process:7400): easyeffects-DEBUG: 20:24:59.169: main: locale directory: /usr/share/locale
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: system input presets directory: "/home/arvid/.config/kdedefaults/easyeffects/input"; 
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: system output presets directory: "/home/arvid/.config/kdedefaults/easyeffects/output"; 
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: user presets directory already exists: /home/arvid/.config/easyeffects/
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: user presets directory already exists: /home/arvid/.config/easyeffects/input
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: user presets directory already exists: /home/arvid/.config/easyeffects/output
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: user presets directory already exists: /home/arvid/.config/easyeffects/autoload/input
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.171: presets_manager: user presets directory already exists: /home/arvid/.config/easyeffects/autoload/output
(easyeffects:7400): easyeffects-DEBUG: 20:24:59.310: Exitting the main function with status: 1
```
</details>

**Comment by VorpalBlade** [comment]
I forgot I also had `mate-terminal` installed from trying it out before. I tried it and fonts look crisp in that program as well. So yet another GTK program without this issue. Whatever it is it doesn't seem to be GTK related thus?

**Comment by VorpalBlade** [comment]
I made an interesting discovery on another computer where I had Cinnamon installed since before. Hooked up to the same monitor (this is a desktop, so it only has one monitor):
* Booted and logged into Cinnamon: easyeffects was not very blurry (only a little bit).
* When I switched to KDE easyeffects was still not very blurry.
* At this point I was very confused and rebooted and logged directly into KDE. Now easyeffects is super-blurry again!

After some more debugging it seems something persists between logins between the DEs:
* I can make it blurry if I first log into KDE. This does not persist when switching to Cinnamon. (E.g it is readable when switching to Cinnamon.)
* Logging into Cinnamon first makes easyeffects less blurry. This persists when switching to KDE.
* Logging into Cinnamon second after KDE does not make easyeffects less blurry if I switch back to KDE after.
* Rebooting (or logging in as root on a console and stopping the user session (i.e. `systemctl stop user@1000.service`) resets the state.
* I diffed the environment variables set in the various sessions. Apart from various IDs/temp-paths that vary every session, `GTK_OVERLAY_SCROLLING=1` and `GNOME_DESKTOP_SESSION_ID=this-is-deprecated` seems to leak/persist from Cinnamon. Nothing persists from the KDE session. Manually setting either of these does not fix it. So whatever it is is not an environment variable.

I had far more GTK programs to test with on this computer. None of them are however affected like this except for easyeffects. I cannot make heads or tails of this, but it is really annoying.

**Comment by wwmm** [comment]
> had far more GTK programs to test with on this computer. None of them are however affected like this except for easyeffects. I cannot make heads or tails of this, but it is really annoying.

I think the reason is that the other gtk applications you are testing with are not written in `GTK 4` like EasyEffects is. Install the package `gtk4-demos` and run `gtk4-demo` to see how the fonts will look like. It may also be worth to install `libadwaita-demos` and run `adwaita-1-demo`. As we use libadwaita it is possible it may be the one responsible for  the bad fonts.

All that being said I think something is not right in how gtk4 is handling fonts. I can't remember where in its issue page but other people were complaining about something that was done by older gtk versions in the font rendering that is not done anymore in gtk4 because it is not considered necessary. The fact is that gtk4 does indeed handle fonts differently.

**Comment by VorpalBlade** [comment]
> I think the reason is that the other gtk applications you are testing with are not written in GTK 4 like EasyEffects is.

Yes, you are correct. I do have one other gtk4 app installed on one of the computers, but I did not happen to test that one. That is `baobab` (the gnome disk analyzer). It does indeed show the same issue as easyeffects. Comparing the two demos (gtk4 and adwaita) both display the issue, so that doesn't make a difference.

> All that being said I think something is not right in how gtk4 is handling fonts.

That much is indeed obvious now! However if that alone was the problem, what I don't understand still is why it makes a difference if I'm logging into KDE or Cinnamon and (even stranger) why certain results of that login persist until the user session is restarted! I'm going to try to investigate that further.

**Comment by VorpalBlade** [comment]
Okay, I think I found the cause to why Cinnamon and KDE made a difference (though I still don't understand the persistence effect): I thought I was using the same fonts (Dejavu Sans) but apparently had a different setting for "Default font" ("desktop font", "window title font" etc were all Dejavu). For default font it was using Noto Sans instead, which does seem to render better with GTK4 specifically.

Unfortunately Dejavu Sans renders better with everything else in my opinion (being much sharper, which I guess to a large extent is a personal preference, I go as far as using traditional bitmap fonts in my terminal emulator for perfect sharpness at the cost of no antialiasing).

Is there any way I could override the font for just easyeffects (or GTK4 apps in general)? I don't really use any except for easyeffects currently, though I guess that might change in the future as more programs are ported over.

**Comment by wwmm** [comment]
>Is there any way I could override the font for just easyeffects (or GTK4 apps in general)?

I never tried. But I think that gtk4 and gtk3 follows different configuration files. So there is probably a way to at least force gtk4 applications to use another font.

**Comment by wwmm** [comment]
Open gtk4 issue that is probably related to what you are seeing https://gitlab.gnome.org/GNOME/gtk/-/issues/3787

**Comment by wwmm** [comment]
>Open gtk4 issue that is probably related to what you are seeing https://gitlab.gnome.org/GNOME/gtk/-/issues/3787

There is a lot of hostile comments in that thread from both sides but I saw that on `gtk >= 4.6.0` it was added an option that improves the rendering on non HiDPI displays. Open the file `~/.config/gtk-4.0/settings.ini` and set `gtk-hint-font-metrics=1`. I tested it here on my computer and it does make things better.

**Comment by wwmm** [comment]
>I tested it here on my computer and it does make things better.

It is not perfect. But definitely better than the default behavior on my simple display.

**Comment by VorpalBlade** [comment]
> It is not perfect. But definitely better than the default behavior on my simple display.

Maybe, I can't really tell the difference. Maybe when using Noto it is slightly better. Really not seeing any difference when using Dejavu though.

However I discovered another interesting thing. GTK4 ignores the FREETYPE_PROPERTIES environment variable, which I set a long time ago to improve rendering (i.e. bring back how it looked back in the day)

```
export FREETYPE_PROPERTIES="truetype:interpreter-version=35 cff:no-stem-darkening=1 autofitter:warping=1"
```

Qt and GTK3 and older respect this properly.

&lt;rant&gt;

I may be holding on to the past here, as well as *definitely* ranting a bit... But I think font rendering peaked around the era of Windows XP and for Linux around or just before 2010. For me, crisp sharp fonts with minimal antialiasing (and no subpixel stuff) just lead to less headaches when working in front of a computer for a long time. HiDPI may change that in the future, but if I have a graphics card that can drive a 4k HiDPI screen I'd rather have more screen real estate at a lower DPI. And since I occasionally also game, having too high DPI just slows things down.

Also Linux does terrible at mixed DPI setups (at least under X11, which I need because nvidia which I need because CUDA...), something I notices with my work laptop all the time. Since it is too expensive to go completely HiDPI I'd rather continue at low DPI for the foreseeable future. Gnome devs seem to be jumping the gun and assuming everyone have setup just like theirs though... Not the first time that happens.

&lt;/rant&gt;

**Comment by wwmm** [comment]
>Why is it a hidden option as opposed to in the Gnome settings? Oh wait it is gnome...

I asked myself the same question. I like developing in gtk but this is one of those moments where I remember the time I used KDE and I say "What the fuck is this gtk". I am having a hard time trying to understand why they gave higher priority to things like "text rotation" instead of  the legibility of static text... But this time I won't complain too much. It could have been worse. I am surprised this hidden option was even accepted...

I wish we could magically have a toolkit with everything that is good on GTK and QT without the questionable decisions that each of them has... But it is not going to happen... So it is what it is...

**Comment by VorpalBlade** [comment]
> I wish we could magically have a toolkit with everything that is good on GTK and QT without the questionable decisions that each of them has... But it is not going to happen... So it is what it is...

Out of those two, I have personally only developed in QT (commercial software, at a previous workplace), so I don't have much useful to add (having never coded for GTK). And I no longer do any GUI coding at all. Maybe electron if you don't mind the javascript and HTML? The one time I made a "GUI" in web development (an interactive research-robot control web page) using Bootstrap I found it acceptable and less annoying than QT at least.

What I *really* want is something like LaTeX for GUIs: "Here is the content, figure out how to layout it, and allow me to do the occasional override if I absolutely have to". That is still an unsolved (and very hard, maybe unsolvable) problem.

**Comment by VorpalBlade** [comment]
Feel free to close this issue, as it is really not an easyeffects bug, but a GTK4 bug (with a badly documented workaround). Thanks so much for the help in figuring it out. Without the key information about GTK4 behaving differently I would still have been scratching my head!

**Comment by wwmm** [comment]
>Maybe electron if you don't mind the javascript and HTML?

I looked at it in the past but moving to it would require way more work than moving to QT. And just like in a move to QT I would not have some things that GTK does in a really straightforward way. I guess we can not have everything in life :-)

>Feel free to close this issue

Ok :+1:
