### ISSUE TITLE
Can't load presets

### ISSUE THREAD

**Issue by Miroslav11** [wwmm/easyeffects#1524]
### EasyEffects Version

6.2.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint 20.3

### Describe the bug

Pipewire is installed and it's working fine. I'm trying to deal with "Dynamic range compression" in easyeffects.

I've put the preset "LoudnessEqualizer.json" from (https://github.com/Digitalone1/EasyEffects-Presets) inside ".var/app/com.github.wwmm.easyeffects/config/easyeffects/output", and when I'm trying to load it "Presets -> Load", it's not loading

### Expected Behavior

Should be loaded

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Digitalone1** [comment]
@vchernin Could it be a Flatpak permission issue?

**Comment by Miroslav11** [comment]
Probably, but I don't know which permission?

**Comment by wwmm** [comment]
@Miroslav11 try to get some logs as explained at https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs. Maybe there is a error message when trying to load the preset that could point us in the right direction.

**Comment by Miroslav11** [comment]
[loading_presets.txt](https://github.com/wwmm/easyeffects/files/8693553/loading_presets.txt)

**Comment by Miroslav11** [comment]
@wwmm there you go :)

**Comment by wwmm** [comment]
It is the first time I see an error like this
```
presets_manager: [json.exception.parse_error.101] parse error at line 7, column 1: syntax error while parsing value - invalid literal; last read: '<U+000A><U+000A><U+000A><U+000A><U+000A><U+000A><'

presets_manager: [json.exception.type_error.304] cannot use at() with null
```
I wonder if the preset file was somehow corrupted.

**Comment by wwmm** [comment]
At least in the github page the preset file has nothing unusual at the line `7`

**Comment by Miroslav11** [comment]
@Digitalone1 said it's working fine on non flatpak versions.

I've tried on both of my OS, Pop OS 22.04 (native pipewire), and on Linux mint 20.3. On both systems I can't load

**Comment by wwmm** [comment]
>Digitalone1 said it's working fine on non flatpak versions.

I have just tested one of his presets on my computer (not flatpak) and there was no problem. But I can't see how Flatpak could be causing an `invalid literal` when trying to load the preset. Weird...

Try to open the file you copied to the flatpak folder. did something "unusual" appear inside of it after the copy?

**Comment by Miroslav11** [comment]
I've compared them word from word in Geany IDE. Everything is the same

**Comment by vchernin** [comment]
> I've put the preset "LoudnessEqualizer.json" from (https://github.com/Digitalone1/EasyEffects-Presets) inside ".var/app/com.github.wwmm.easyeffects/config/easyeffects/output", and when I'm trying to load it "Presets -> Load", it's not loading

This works fine for me on the flatpak build.

**Comment by wwmm** [comment]
I see. Something else that does not happen on my computer is 
```
Gtk-WARNING **: 18:42:11.918: Locale not supported by C library.
	Using the fallback 'C' locale.
```
@Digitalone1 I wonder if the locale could be getting in our way again.

**Comment by Digitalone1** [comment]
@wwmm json format does not follow locale and, as far as I remember, no locale dependent function is used in preset loading.

**Comment by Miroslav11** [comment]
ok, I was curious and I've installed Fedora on VM and I've installed easyeffects through dnf package manager, and there's the same error as in Flatpak on Linux Mint

```
(easyeffects:5366): easyeffects-WARNING **: 22:09:58.026: presets_manager: [json.exception.parse_error.101] parse error at line 7, column 1: syntax error while parsing value - invalid literal; last read: '<U+000A><U+000A><U+000A><U+000A><U+000A><U+000A><'

(easyeffects:5366): easyeffects-WARNING **: 22:09:58.026: presets_manager: [json.exception.type_error.304] cannot use at() with null
(easyeffects:5366): easyeffects-DEBUG: 22:09:58.026: presets_manager: loaded preset: /home/vm/.config/easyeffects/output/LoudnessEqualizer.json

(easyeffects:5366): easyeffects-WARNING **: 22:10:04.650: presets_manager: [json.exception.parse_error.101] parse error at line 7, column 1: syntax error while parsing value - invalid literal; last read: '<U+000A><U+000A><U+000A><U+000A><U+000A><U+000A><'

(easyeffects:5366): easyeffects-WARNING **: 22:10:04.651: presets_manager: [json.exception.type_error.304] cannot use at() with null
(easyeffects:5366): easyeffects-DEBUG: 22:10:04.651: presets_manager: loaded preset: /home/vm/.config/easyeffects/output/LoudnessEqualizer.json
```

**Comment by Digitalone1** [comment]
@Miroslav11 Which is your country? What locale have you set on your system?

Does this issue happen only on that preset? Did you try other presets?

**Comment by wwmm** [comment]
>I was curious and I've installed Fedora

If I am not mistaken @vchernin uses Fedora. What makes this even more weird because he can load the preset.

>What locale have you set on your system?

I am also curious. It would be interesting to see what is the output of the command `locale` in your computer @Miroslav11. Or should this command be executed inside the Flatpak sandbox @vchernin?

**Comment by vchernin** [comment]
Yup, I’m using Fedora Silverblue 36. But the behaviour shouldn’t be any different from Fedora Workstation.

> Or should this command be executed inside the Flatpak sandbox @vchernin?

Yeah, for the locale used in the Flatpak, you can enter the sandbox with `flatpak run --command=bash com.github.wwmm.easyeffects`

Seeing as it also happens with non-Flatpak (dnf) `locale` would be good to know on the host too.

**Comment by Miroslav11** [comment]
> @Miroslav11 Which is your country? What locale have you set on your system?
> 
> Does this issue happen only on that preset? Did you try other presets?
![Screenshot from 2022-05-15 08-58-45](https://user-images.githubusercontent.com/25286527/168461276-8bb610c9-2f3a-4da2-b95a-ace3cd986546.png)


Croatia. But it could be because my Language for the system is English, and region and time format is in Croatian?

**Comment by Miroslav11** [comment]
OK, I've reset everything to English, rebooted pc, but still can't load

**Comment by Miroslav11** [comment]
> Does this issue happen only on that preset? Did you try other presets?

I've just tried preset from this link https://github.com/JackHack96/EasyEffects-Presets and it's the same, can't load. I can only load my own saved preset

**Comment by Miroslav11** [comment]
> > I was curious and I've installed Fedora
> 
> If I am not mistaken @vchernin uses Fedora. What makes this even more weird because he can load the preset.
> 
> > What locale have you set on your system?
> 
> I am also curious. It would be interesting to see what is the output of the command `locale` in your computer @Miroslav11. Or should this command be executed inside the Flatpak sandbox @vchernin?

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Now is this one since i've switched, but problem stays the same

**Comment by Miroslav11** [comment]
>

**Comment by Miroslav11** [comment]
> Yeah, for the locale used in the Flatpak, you can enter the sandbox with `flatpak run --command=bash com.github.wwmm.easyeffects`
> 
> Seeing as it also happens with non-Flatpak (dnf) `locale` would be good to know on the host too.

Same, everything is in English US now

**Comment by Miroslav11** [comment]
Gonna install Fedora alongside mint and pop os but without changing locale (leave it everything to English US) and see what happens

**Comment by Digitalone1** [comment]
> I've just tried preset from this link https://github.com/JackHack96/EasyEffects-Presets and it's the same, can't load. I can only load my own saved preset

Please post the preset that you can load.

**Comment by Miroslav11** [comment]
> Please post here the preset that you can load.
[compressor.json.zip](https://github.com/wwmm/easyeffects/files/8694485/compressor.json.zip)

It's just the plain default compression, but here you go

**Comment by Digitalone1** [comment]
So we can say that if you save a preset, that preset can be loaded. But if you download an external preset, you can't import it.

Can you try to save different presets with different values and effects to try to reproduce the bug?

**Comment by Miroslav11** [comment]
> So we can say that if you save a preset, that preset can be loaded. But if you download an external preset, you can't load it.

Yep

> 
> Can you try to save different presets with different values and effects to try to reproduce the bug?

Gonna try that and post  it here

**Comment by Miroslav11** [comment]
@Digitalone1 is it somehow possible that you screenshot me your values from your preset so i will enter them manually and save it and then try to load it?

You can do it on your github where I've opened that issue day ago

**Comment by Digitalone1** [comment]
Nope, too long to do. Create different presets on your own to see which one is not loading after you save it. To be sure, just empty the list before you load.

It could be something related to types, in example, compressor do not have bool true/false values, but the equalizer has them.

Maybe could be reproduced only on some effects and not with others.

**Comment by Miroslav11** [comment]
ok. gonna try. it will take a while

**Comment by Miroslav11** [comment]
@wwmm as soon as I touch "Maximum History" in "Autogain" easyeffects crashes. I've tried to display debug messages but there isn't one, it's just crash
![Peek 2022-05-15 11-02](https://user-images.githubusercontent.com/25286527/168465213-f867fa21-1757-4983-9377-330b266d6148.gif)

**Comment by Digitalone1** [comment]
Yes, I can reproduce this, but it's a different issue not related to reading presets.

**Comment by Miroslav11** [comment]
> Yes, I can reproduce this, but it's a different issue not related to reading presets.

can you tell me what presets did you used for tweaking dynamic range compression? so I can start with them

**Comment by Miroslav11** [comment]
never mind. I've found it on my open issue on your github

**Comment by Digitalone1** [comment]
> can you tell me what effects did you used for tweaking dynamic range compression? so I can start with them

Just play with the compressor in downward mode.

Anyway if you want to try to set the LoudnessEqualizer preset, just look inside the json file (open it with a text editor), there are all the parameters you can set in the application. No time to make screenshots now, maybe I wiil later in the other issue.

**Comment by Miroslav11** [comment]
> > can you tell me what effects did you used for tweaking dynamic range compression? so I can start with them
> 
> Just play with the compressor in downward mode.
> 
> Anyway if you want to try to set the LoudnessEqualizer preset, just look inside the json file (open it with a text editor), there are all the parameters you can set in the application. No time to make screenshots now, maybe I wiil later in the other issue.

I've played with all of them individually and then combined, and all of them can be loaded later.
The thing is that json file that I've created don't have html inside. Maybe that is the problem?

**Comment by Miroslav11** [comment]
Jeez! I've found the problem LoL.
When i'm saving json file from github I'm right clicking and go with save as, and firefox create bunch of html inside.

So now I've copied and pasted json file so that there's no html inside, and it can be loaded :)

**Comment by Miroslav11** [comment]
So..if anyone else encounter this kind of problem...don't do what I did LoL

**Comment by Digitalone1** [comment]
Okay, the good thing is that we discovered a bug in Autogain to fix in the next release. :)

**Comment by Digitalone1** [comment]
@wwmm does nlohmann library have a function to check the correctness of the file so we can warn the users if the preset they are using is corrupted/invalid in order to avoid this issues in the future?

**Comment by Miroslav11** [comment]
> Okay, the good thing is that we discovered a bug in Autogain to fix in the next release. :)

yep. :)

![Peek 2022-05-15 11-56](https://user-images.githubusercontent.com/25286527/168467138-b88dd25b-66d0-45eb-af70-f3fe982b9705.gif)

Preset loaded :)

**Comment by wwmm** [comment]
>Yes, I can reproduce this, but it's a different issue not related to reading presets.

I have no problems at all with the maximum history control in the autogain window. Even If I change it while audio is being processed. But whatever it is happening in your computers I agree it has nothing to do with the preset bug.

**Comment by wwmm** [comment]
>does nlohmann library have a function to check the correctness of the file so we can warn the users if the preset they are using is corrupted/invalid in order to avoid these issues in the future?

I have no idea. My guess is that it will throw some kind of exception but probably only when actually trying to load a parameter. I am not sure if it parses the file as soon as we give it its path.

**Comment by wwmm** [comment]
>When i'm saving json file from github I'm right clicking and go with save as, and firefox create bunch of html inside.

That has happened to me a few times but in other situations not related to presets. It is annoying having to remember to clicking on  `raw` to get what I actually want :smile:

**Comment by wwmm** [comment]
As far as I could understand we can fix this issue. If not feel free to reopen it.
