### ISSUE TITLE
wrong caracter inserted in  auto start command line after update

### ISSUE THREAD

**Issue by Neo595** [wwmm/easyeffects#1527]
### EasyEffects Version

6.2.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

Hello
After an application update, auto start command line is wrongly updated.
Command line updated : 
 flatpak run --command=easyeffects ''\''com.github.wwmm.easyeffects'\''' --gapplication-service
Obsviously, easyeffect is not started at all;

Removing "\" and '\''' fixes the issue.

### Expected Behavior

Don't change the autostart command

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
This is an xdg-desktop-portal 1.14 bug. It is fixed in 1.14.4 or later.

**Comment by Neo595** [comment]
the backslash caracter have been removed after " caracters

![image](https://user-images.githubusercontent.com/25134439/168478700-3d349319-d2f6-49c0-a818-46eeb59268d8.png)
