### ISSUE TITLE
MDA Loudness plugins not working

### ISSUE THREAD

**Issue by Neo595** [wwmm/easyeffects#1530]
### EasyEffects Version

6.2.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

Hello,
Loudness MDA Plugins is no more working.
No output, no processing audible
Also, setting parameters are not working properly (strange increment, update,...)
Regards.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Neo595** [comment]
Running from command line:

(easyeffects:2): easyeffects-WARNING **: 12:57:27.301: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 12:57:27.301: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 12:57:27.301: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 12:57:27.301: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 12:57:28.087: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 12:57:28.087: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 12:57:28.087: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 12:57:28.087: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

**Comment by Neo595** [comment]
After reloading MDA package, the plugins is starting  to work again, but parameters setting remains weird. setting -2.7 lead to -3.
+/- buttons acts also strangely.

**Comment by Digitalone1** [comment]
Which is your country and what locale is set on your system? EasyEffects widgets format follows the system locale, so maybe you have to write the numbers with comma as decimal separator.

**Comment by Neo595** [comment]
France / French
. or , makes no difference.

**Comment by Digitalone1** [comment]
It seems OK.

Please post the debug log as reported [here](https://github.com/wwmm/easyeffects/wiki/Reporting-bugs). 

And the output of `locale -a`.

**Comment by wwmm** [comment]
>Please post the debug log as reported [here](https://github.com/wwmm/easyeffects/wiki/Reporting-bugs).

That may help. I also suggest you try to change the plugin parameters while getting the logs. This way we will see if errors are happening when changing them.

**Comment by Neo595** [comment]
No log when I'm changing the parameters.
hier, when I applied "reset", the volume level moves from -3.0 to 0 without any action.
Reload the preset restores a correct state.
Page Up/Dn allows to add/substract 1db from  "volume"

This is newer or the same as PipeWire 0.3.41 required to run EasyEffects
(process:2): easyeffects-DEBUG: 05:46:25.491: easyeffects version: 6.2.5
(process:2): easyeffects-DEBUG: 05:46:25.492: main: locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: system input presets directory: "/app/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: system output presets directory: "/app/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: user presets directory already exists: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: user presets directory already exists: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: user presets directory already exists: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: user presets directory already exists: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 05:46:25.509: presets_manager: user presets directory already exists: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 05:46:25.687: pipe_manager: compiled with PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 05:46:25.687: pipe_manager: linked to PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 05:46:25.689: pipe_manager: core version: 0.3.51
(easyeffects:2): easyeffects-DEBUG: 05:46:25.689: pipe_manager: core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: found metadata: settings
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: found metadata: default
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: found metadata: route-settings
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: Audio/Sink 44 alsa_output.pci-0000_06_00.0.iec958-stereo with timestamp 1652759185690518348 was added
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: Audio/Source 45 alsa_input.pci-0000_06_00.0.iec958-stereo with timestamp 1652759185690537459 was added
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: Stream/Output/Audio 121 SMPlayer with timestamp 1652759185690563769 was added
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: SMPlayer port 120 is connected to alsa_output.pci-0000_06_00.0.iec958-stereo port 41
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: SMPlayer port 119 is connected to alsa_output.pci-0000_06_00.0.iec958-stereo port 47
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: Audio/Sink 127 easyeffects_sink with timestamp 1652759185690595800 was added
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: Audio/Source/Virtual 55 easyeffects_source with timestamp 1652759185690604840 was added
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_06_00.0.iec958-stereo"}
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: new metadata property: 0, default.configured.audio.source, Spa:String:JSON, {"name":"easyeffects_sink"}
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_06_00.0.iec958-stereo"}
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_06_00.0.iec958-stereo"}
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: new metadata property: 121, target.node, Spa:Id, 60
(easyeffects:2): easyeffects-DEBUG: 05:46:25.690: pipe_manager: new metadata property: 121, target.object, Spa:Id, 188
(easyeffects:2): easyeffects-DEBUG: 05:46:25.691: pipe_manager: easyeffects_sink node successfully retrieved with id 127 and timestamp 1652759185690595800
(easyeffects:2): easyeffects-DEBUG: 05:46:25.691: pipe_manager: easyeffects_source node successfully retrieved with id 55 and timestamp 1652759185690604840
(easyeffects:2): easyeffects-DEBUG: 05:46:25.697: pipe_manager: new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"easyeffects_sink"}
(easyeffects:2): easyeffects-DEBUG: 05:46:25.749: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:25.778: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:25.822: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.366: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.380: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.393: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.393: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:2): easyeffects-DEBUG: 05:46:26.414: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.445: soe: rnnoise using the default model
(easyeffects:2): easyeffects-DEBUG: 05:46:26.462: soe: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 05:46:26.464: soe: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 05:46:26.467: soe: crystalizer successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 05:46:26.470: soe: bass_loudness successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 05:46:26.472: soe: limiter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 05:46:26.491: soe: limiter latency: 0.005079365 s
(easyeffects:2): easyeffects-DEBUG: 05:46:26.491: soe: output_level: new PipeWire blocksize: 512
(easyeffects:2): easyeffects-DEBUG: 05:46:26.514: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.541: lv2_wrapper: http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:26.579: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:27.119: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:27.134: lv2_wrapper: http://lsp-plug.in/plugins/lv2/loud_comp_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:27.147: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:27.147: lv2_wrapper: urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
(easyeffects:2): easyeffects-DEBUG: 05:46:27.168: lv2_wrapper: http://lsp-plug.in/plugins/lv2/sc_mb_compressor_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 05:46:27.197: sie: rnnoise using the default model
(easyeffects:2): easyeffects-DEBUG: 05:46:27.212: sie: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 05:46:27.213: sie: spectrum successfully connected to PipeWire graph
easyeffects-INFO: 05:46:27.233: application: disabling global bypass
(easyeffects:2): easyeffects-DEBUG: 05:46:27.291: application_ui: Icon Theme Yaru-dark detected
(easyeffects:2): easyeffects-DEBUG: 05:46:27.897: app_info: cannot lookup application icon SMPlayer in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:27.897: app_info: cannot lookup application icon SMPlayer in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.070: new default output device: alsa_output.pci-0000_06_00.0.iec958-stereo
(easyeffects:2): easyeffects-DEBUG: 05:46:30.072: pipe_manager: new metadata property: 121, target.node, Spa:Id, 127
(easyeffects:2): easyeffects-DEBUG: 05:46:30.073: pipe_manager: new metadata property: 121, target.object, Spa:Id, 328
(easyeffects:2): easyeffects-DEBUG: 05:46:30.073: pipe_manager: SMPlayer port 120 is connected to easyeffects_sink port 57
(easyeffects:2): easyeffects-DEBUG: 05:46:30.073: pipe_manager: SMPlayer port 119 is connected to easyeffects_sink port 56
(easyeffects:2): easyeffects-DEBUG: 05:46:30.084: new default input device: alsa_input.pci-0000_06_00.0.iec958-stereo
(easyeffects:2): easyeffects-DEBUG: 05:46:30.090: app_info: cannot lookup application icon SMPlayer in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.090: app_info: cannot lookup application icon SMPlayer in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.090: application: device alsa_card.pci-0000_06_00.0 has changed its input route to: iec958-stereo-input
(easyeffects:2): easyeffects-DEBUG: 05:46:30.090: application: device alsa_card.pci-0000_06_00.0 has changed its output route to: iec958-stereo-output
(easyeffects:2): easyeffects-DEBUG: 05:46:30.091: app_info: cannot lookup application icon SMPlayer in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.091: app_info: cannot lookup application icon SMPlayer in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.091: app_info: cannot lookup application icon SMPlayer in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.091: app_info: cannot lookup application icon SMPlayer in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.091: soe: crystalizer blocksize: 512
(easyeffects:2): easyeffects-DEBUG: 05:46:30.094: soe: pipeline latency: 5.079365 ms
(easyeffects:2): easyeffects-DEBUG: 05:46:30.098: soe: crystalizer latency: 2.2675737e-05 s
(easyeffects:2): easyeffects-DEBUG: 05:46:30.133: app_info: cannot lookup application icon SMPlayer in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.133: app_info: cannot lookup application icon SMPlayer in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.134: app_info: cannot lookup application icon SMPlayer in /usr/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.134: app_info: cannot lookup application icon SMPlayer in /usr/local/share/pixmaps
(easyeffects:2): easyeffects-DEBUG: 05:46:30.134: soe: pipeline latency: 5.102041 ms
(easyeffects:2): easyeffects-DEBUG: 05:46:31.736: sie: No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 05:47:42.561: presets_manager: saved preset: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/LoudNess.json
(easyeffects:2): easyeffects-DEBUG: 05:47:45.817: presets_manager: saved preset: /home/neo/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output/paramloud.json
(easyeffects:2): easyeffects-DEBUG: 05:48:16.871: pipe_manager: new metadata property: 131, target.node, Spa:Id, -1
(easyeffects:2): easyeffects-DEBUG: 05:48:17.058: pipe_manager: new metadata property: 64, target.node, Spa:Id, -1
(easyeffects:2): easyeffects-DEBUG: 05:48:17.356: pipe_manager: new metadata property: 131, target.node, Spa:Id, -1

Initial state after reset 
![initial_after_reset](https://user-images.githubusercontent.com/25134439/168726401-79a573db-3b80-45a6-9cc3-50a712ce9a8c.png)

click on "+" parameter volume
![volume+](https://user-images.githubusercontent.com/25134439/168726476-3e1f1500-bf9d-4444-84dc-a8d8cabb91cf.png)

click again on "+" (click on "-" does nothing)
![volume+again](https://user-images.githubusercontent.com/25134439/168726522-a4de192b-c59d-4d26-9bdf-e8eae4251afd.png)

Enter -2.7 then press return
![enter_-2 7_enter](https://user-images.githubusercontent.com/25134439/168726597-ea1b22c5-0f92-4f23-a55e-b38b33a6b210.png)

**Comment by wwmm** [comment]
>when I applied "reset", the volume level moves from -3.0 to 0 without any action.

Strange. When I click in this plugin reset button the value goes from `-3.0` to `-3.1` that is the default value. It does not go to zero.

**Comment by wwmm** [comment]
So far I have not been able to reproduce this problem. I tried with `LC_NUMERIC = en_US.UTF-8` and `LC_NUMERIC = pt_BR.UTF-8` and even with the change from `.` to `,` in the decimals things are fine. So I am not sure locale is the cause of the problem thins time.

**Comment by Neo595** [comment]
It's not systematic, but after reset applied, the same return to 0 scheme applies to the "output" box, from -6 to 0 by 0.1dB increment.
It can be reproduced also on "link" box
initial value -9.1dB
+ => -8.9dB
+ => -7.9dB
Loosing focus :  -7.0dB
+ => -6.9dB
Loosing focus :  -6.0dB
If you keep the focus, the sequence (+ button) is : -9.1 , -8.9 , -7.9 , -6.9 , -5.9, -4.9 , -3.9, -2.9, -1.9, -0.9, 0 , 0
Then here, the reset is no more working : starting from -9,1 the incrementing to 0

If you release the focus of the box, the value is rounded.

initial value -9.1dB
- => nothing
loosing focus => -9.0dB
- => -9.1dB
loosing focus => -9.0dB

**Comment by Digitalone1** [comment]
I think the format is not the French locale, even if you have set it in your system. 

Maybe you have the French locale set without having it generated.

If you see the locale documentation on Arch wiki, the formats you want have to be decommented from a file, then generated and at last you set one of them.

It seems you have only set the French locale without generating it.

If this is the issue, I wonder why it happens on Ubuntu which has to provide the correct locale settings after the installation stage. These sort of problems are more frequent on Arch. Maybe you miss or uninstalled some language pack from Ubuntu repository?

**Comment by Neo595** [comment]
Opening limiter plugins, I can observe again strange behavior when clicking in + or - buttons.
Example : 
Stereo link : initial value 100%
"-" => 99.99%
Put the focus on Threshold, stereo link moves to 99%
starting at 100% "-" => 99,99%, "-" => 98.99%  => 97.99% (keeping the focus)
after losing focus, rounded to XX.00%

**Comment by Neo595** [comment]
Further findings
Opening spectrum windows
Focus on "line width" 
![image](https://user-images.githubusercontent.com/25134439/169871104-55b5349e-5b77-4481-a23b-8b253dcad6df.png)

Then click on  "+" => 3.1
click on "+"=> no change
click on "-" => 2.9
click on "-"=>1.9
click on "-"=>0.9
click on "-"=>0.1
click on "-"=> no change
click on "+"=> 0.2/0.3/0.4
click on "+"=>0.2
click on "+"=> no change

**Comment by Digitalone1** [comment]
Did you read my last post?
