### ISSUE TITLE
Preferences -> Start Service at Login : has no effect

### ISSUE THREAD

**Issue by Odin000** [wwmm/easyeffects#1539]
### EasyEffects Version

6.2.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04 LTS

### Describe the bug

when toggled has no effect, so I still need to start EasyEffects after login manually.

### Expected Behavior

EasyEffects start after login

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
As you are on `Pop!_OS` this may have the same cause as #1500

**Comment by Odin000** [comment]
#1500 is closed, and I see the same issue with #1500 is fixed, so toggling the settings is working fine, it's just that autostart has no effect at all.

**Comment by wwmm** [comment]
>it's just that autostart has no effect at all.

Because of the Flatpak sandbox the autostart file has to handled in a different way in its packages. Take a look at #1394. The debug steps explained there by @vchernin will help us to understand what is going on.

**Comment by vchernin** [comment]
Ubuntu (likely also pop) still ships xdg-desktop-portal 1.14.3 which is unable to create a correct autostart file. They need to update to 1.14.4. 

Can you confirm the contents of `~/.autostart/com.github.wwmm.easyeffects.desktop` is a desktop file, but the app id is wrongly quoted?

If so there is nothing we can do here to fix this.

**Comment by Odin000** [comment]
~/.config/autostart/com.github.wwmm.easyeffects.desktop  sadly confirmed lol

**Comment by xdubx** [comment]
`
[Desktop Entry]
Type=Application
Name=com.github.wwmm.easyeffects
Exec=flatpak run --command=easyeffects ''\\''com.github.wwmm.easyeffects'\\''' --gapplication-service
X-Flatpak=com.github.wwmm.easyeffects
`
it seems that the ' is not allowed in the exec command.  i changed the exec cmd to

`
flatpak run --command=easyeffects com.github.wwmm.easyeffects --gapplication-service
`

**Comment by vchernin** [comment]
[Reported upstream](https://bugs.launchpad.net/ubuntu/+source/xdg-desktop-portal/+bug/1975638)
