### ISSUE TITLE
Solved the problem of obs studio.

### ISSUE THREAD

**Issue by sephid86-2** [wwmm/easyeffects#1541]
easyeffects - pipe_manager.cpp

214 void on_node_info(void* object, const struct pw_node_info* info) {
215   if (PipeManager::exiting) {
216     return;
217   }
218    
219   auto* const nd = static_cast<node_data*>(object);
220    
221   auto* const pm = nd->pm;
222    
223   if (auto node_it = pm->node_map.find(nd->nd_info->timestamp); node_it != pm->node_map.end()) {

-224     if (g_strcmp0(spa_dict_lookup(info->props, PW_KEY_STREAM_MONITOR), "true") == 0) {                                                                                                                      
+224     if (g_strcmp0(spa_dict_lookup(info->props, PW_KEY_STREAM_MONITOR), "true") == 0 || g_strcmp0(spa_dict_lookup(info->props, PW_KEY_STREAM_CAPTURE_SINK), "true") == 0) {

obs studio 의 문제를 해결하였습니다.
Solved the problem of obs studio.

obs 에서 media name '데스크탑 오디오'는 출력이 아닙니다.
입력입니다.
Media name 'desktop audio' in obs is not output.
It is input.

녹음을 하기 때문에 'monitor of' 를 받는 입력입니다.
This is the input that receives the 'monitor of' because we are recording.

그리고 오디오 인터페이스 또는 오디오 믹서는 USB 인 경우가 많고 입출력의 디바이스 이름이 같은 경우가 많습니다.
And the audio interface or audio mixer is often USB, and the input and output device names are often the same.

github nickname wwmm 에게
to github nickname wwmm

나는 당신에게 진심을 담아 정중하게 사과를 하고 싶습니다.
I would like to sincerely apologize to you sincerely.

당신이 나를 기억하는지 모르겠습니다. github nickname sephid86 입니다.
I don't know if you will remember me. github nickname sephid86

나는 당신이 나의 'issue' 에 대해 제대로 살펴보지 않고 닫은것 같았고 나를 무시한다고 생각했습니다.
I thought you closed my 'issue' without properly looking at it and ignoring me.

그래서 화가났고 당신에게 말을 함부로 하였습니다.
So I'm angry and I've been rude to you.

이것에 대해 나는 진심으로 정중하게 사과합니다.
For this I sincerely and sincerely apologize.

정말 죄송합니다.
I'm really sorry.

언젠가 기회가 된다면 당신을 만나고 싶습니다.
If I have a chance someday, I would like to meet you.

지금은 어렵지만 언젠가 내가 당신의 나라로 가겠습니다.
It is difficult now, but one day I will go to your country.

총을 가지고 나오실 필요는 없습니다.
You don't have to bring a gun.

나는 나약한 사람이고 당신과 나 우리에게는 키보드가 있습니다.
I'm a weak person and you and I have keyboards.

우린 좋은 친구가 될수 있을것입니다.
We could be good friends.

다음 업데이트에서 위 내용의 패치를 검토해주시길 정중하게 요청합니다.
I respectfully ask you to review the above patches in the next update.

easyeffects 는 아주 좋은 훌륭한 프로그램입니다.
easyeffects is a great program that is very good.

이런 좋은 프로그램을 만들어주셔서 감사합니다.
Thank you for making such a great program.

PS
구글에 제 닉네임 sephid86 을 검색하면 나의 부끄러움이 제일 위에 박제 되어 있어서 슬픕니다.
When I searched my nickname sephid86 on Google, my shame became taxiderm at the top.

sad...

내가 제시한 방법에 다른 추가 수정이 더 필요합니다. 어떤것을 더 수정해야 하는지 더 찾아보겠습니다.
The method I presented requires other additional modifications.
I'll look for more.

-----

https://github.com/wwmm/easyeffects/issues/1430

https://github.com/wwmm/easyeffects/issues/807

-----
https://www.clien.net/service/board/cm_linux/17259856?od=T31&po=0&category=0&groupCd=

**Comment by wwmm** [comment]
Ok. Let's try to keep the past in the past :-). 

I did not think about `PW_KEY_STREAM_CAPTURE_SINK`. Its documentation does not say much about it
```
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/pipewire/keys.h#L287
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/d55bc1eb86e8e3e3bf600ac218e8d5f59ac2bfa3
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/5ae75e1d2a08bbf7316c299eddbacf175617fee8
```
 . In the commit related to Pulseaudio there is the following comment
```
Make the pulseaudio layer set the PW_KEY_STREAM_CAPTURE_SINK property
when a monitor device is selected as a source to make it easier for the
session manager to find the right source.
```
. What I understand of this is that any stream selecting a `sink monitor` as source will have the `PW_KEY_STREAM_CAPTURE_SINK` property set. Interesting. @sephid86-2 I think that your idea is a good starting point for a workaround. But to be on the safe I will apply it only if the stream name is `OBS`. Either this or creating an option allowing this check to be disabled. The reason is that as PW_KEY_STREAM_CAPTURE_SINK works any stream recording from a sink monitor activates it. And there may be cases where the user wants EasyEffects to apply effects to such streams.

I don't really like to add checks targeting specific apps but at least in this case we would be targeting the application name instead of a `media name` that changes with translations. What do you think @Digitalone1?

**Comment by wwmm** [comment]
I have updated our master branch with the following code
```
    if (nd->nd_info->name == "OBS") {
      if (g_strcmp0(spa_dict_lookup(info->props, PW_KEY_STREAM_CAPTURE_SINK), "true") == 0) {
        remove_node = true;
      }
    }
```

**Comment by sephid86-2** [comment]
May I ask why you don't use object.id ?

당신의 관용에 감사합니다.
Thank you for your generosity.

나는 당신의 의견에 동의합니다.
I agree with your opinion.

그리고 나도 당신이 말한것처럼 sink 에 대해 effects 를 적용하고 싶어하는 사람이 있을지도 모른다는 생각을 하였습니다.
And I also thought that there might be people who want to apply effects to sink like you said.

그래서 내가 제안 하고 싶은것은
So what I would like to suggest is

하드웨어 입력에 대해서만 effects 를 적용할수 있는 옵션을 추가하는것입니다.
Adding an option to apply effects only to hardware inputs.

and I did...

easyeffects 소스코드 수정으로 화면상에서 더이상 obs 'desctop audio' 가 표시 되지 않게 하였지만
By modifying the easyeffects source code, obs 'desctop audio' is no longer displayed on the screen.

process all input option 이 on 일때 obs 'dectop audio' 에 easyeffects source 를 막지 못하고 있다.
When the process all input option is on, the easyeffects source cannot be blocked in obs 'desktop audio'.

나는 이것을 해결할 방법을 찾고 있습니다.
I am looking for a way to solve this.

... 그리고 한가지 부탁하고 싶은것은...
...and I'd like to ask you one thing...

sephid86 의 issue 금지를 풀어주셨으면 합니다..
I hope that sephid86's prohibition on writing 'issue' will be lifted.

**Comment by Digitalone1** [comment]
> In general we should not even be using `object.id` for nodes anymore. One day I will start moving things to `object.serial` that is what is recommended nowadays. 

Nice, so we can remove the timestamp hack.

**Comment by sephid86** [comment]
This issue has been resolved in the master branch, waiting for an update, so I'm closing it.
For 'capture sink' and related issues, you may want to check the above links.

**Comment by sephid86-2** [comment]
thank you sir
