### ISSUE TITLE
I'm thinking of a way to respond to the 'capture sink'.

### ISSUE THREAD

**Issue by sephid86** [wwmm/easyeffects#1547]
I'm thinking of a way to respond to the 'capture sink'.

Hello, handsome sir. good morning.

Due to the limitations of the translator, I'm not sure if the meaning of my opinion will be conveyed properly.

Hope the translator is smart...

what i wanted to say

The premise that 'there is no program that works like OBS' cannot be guaranteed.

We need to be able to respond to this.

So my idea is to add 'process all stream capture sink(monitor of audio) toggle switch' to easyeffects preferences.

This should be off by default and you should be able to turn it on if needed.

-----

pipe_manager.cpp
~  243 //    if (nd->nd_info->name == "OBS") {
   244       if (g_strcmp0(spa_dict_lookup(info->props, PW_KEY_STREAM_CAPTURE_SINK), "true") == 0) {
+  245         nd->nd_info->capture_sink=spa_dict_lookup(info->props, PW_KEY_STREAM_CAPTURE_SINK);
   246         remove_node = true;                                                                                                                                                                                 
   247       }
~  248 //    }

pipe_manager.hpp
   63   std::string application_id;
   64 
+  65   std::string capture_sink;                                                                                                                                                                                  
+  66 

stream_input_effects.cpp
 void StreamInputEffects::on_app_added(const NodeInfo node_info) {
  143   const auto blocklist = util::gchar_array_to_vector(g_settings_get_strv(settings, "blocklist"));
  144 
  145   auto is_blocklisted = std::ranges::find(blocklist, node_info.application_id) != blocklist.end();
  146 
  147   is_blocklisted = is_blocklisted || std::ranges::find(blocklist, node_info.name) != blocklist.end();
  148 
~ 149   if (g_settings_get_boolean(global_settings, "process-all-inputs") != 0 && !is_blocklisted && node_info.capture_sink != "true") {                                                                           
  150     pm->connect_stream_input(node_info.id);
  151   }
  152 }
  
-----

Of course the above source doesn't work yet. More additions and modifications are needed to make it work.

And in a different story from the above

Looking at the source code, it seems that 'default input device' is returned when enable is turned off in input.

Then, mic (default input device) is connected instead of 'monitor of audio'.

This is why I said it's a bug in easyeffects.

If you can't get it back to its original state when you unenable it, that's a bug.

To solve this

If capture_sink is true when canceling enable in input, 'default output device' must be returned to connect to 'monitor of audio'.

We should consider that even beginners who do not know how to use pavucontrol can use this program.

I want many people to know that easyeffects is a very good and good program.

what do you think of the sir

ps. 
But in which country do you live sir?

**Comment by wwmm** [comment]
>So my idea is to add 'process all stream capture sink(monitor of audio) toggle switch' to easyeffects preferences.

An option for this is probably going to be added while attempting to improve #1335.

>Looking at the source code, it seems that 'default input device' is returned when enable is turned off in input.

If I understood what you meant that is what happened in releases older than `6.2.5`. As the recommended procedure was not properly documented in PipeWire's sources when effects were disabled in EasyEffects we were doing the same thing we did in Pulseaudio that was moving the stream to the default device. But in our latest release what is done is setting the target metadata to null https://github.com/wwmm/easyeffects/blob/b17d7498145774c743ebbce41fbc9c106ddf569e/src/pipe_manager.cpp#L1548. With this PipeWire's media session manager will move the stream to a "proper place" that respects the application preferences. When it comes to "restore the stream" it is better to just let PipeWire do its thing. If we try to implement our own restoration logic we will just get in the server way.

**Comment by sephid86** [comment]
> 

Thank you for your kind reply.

I'll check to see if I'm missing anything.
