### ISSUE TITLE
Input Effects not displaying in Patchbay

### ISSUE THREAD

**Issue by hitanol** [wwmm/easyeffects#1552]
### EasyEffects Version

6.2.5

### What package are you using?

Arch (easyeffects)

### Distribution

Arch

### Describe the bug

The FX for Input devices are not displaying in Helvum /  PatchBay / qpwgraph, i only can see the Output effects (and when i have eq in output and want to create it for input it only shows the output equalizer in patchbay)

![imagen](https://user-images.githubusercontent.com/99027279/171023604-a2c2e9a0-0b6b-4b6d-a5f5-15672158f8ff.png)

![imagen](https://user-images.githubusercontent.com/99027279/171024095-d2b07a17-6859-43d9-89f5-69e19a5bce07.png)

### Expected Behavior

A correctly display of FX devices in Patchbay softwares for a "more-manual" control of the effects

**Comment by Digitalone1** [comment]
I don't understand what you are trying to do and, anyway, EasyEffects is not meant to be used for manual control in patchbays.

**Comment by hitanol** [comment]
> I don't understand what you are trying to do

the reason is that i saw the effects in patchbay before, but i rebooted and now it isnt there and thats a problem for me cuz i cant apply the effects to a virtual mic inside the easyeffects app but i can route it in patchbay...

**Comment by Digitalone1** [comment]
Easyeffects ignores virtual sink/sources. Maybe we could add them in the future.

**Comment by hitanol** [comment]
pleaseee, it would be an important improvement!

and i saw the problem, the effects only appears when you connect a physical mic, so i need to keep a jack connected as a workaround

**Comment by wwmm** [comment]
>Easyeffects ignores virtual sink/sources. Maybe we could add them in the future.

I am not sure we ignore them. I think support for this has already been added https://github.com/wwmm/easyeffects/blob/b993866ffd2404c37ff15c0f3b65baaedcc868d7/src/pipe_manager_box.cpp#L422 @hitanol how are you creating this virtual mic?

>and i saw the problem, the effects only appears when you connect a physical mic, so i need to keep a jack connected as a workaround

If I remember well the filters nodes are created when the pipeline is linked. And our pipeline is linked only when EasyEffects is actually processing something.

**Comment by wwmm** [comment]
@hitanol is this https://github.com/wwmm/easyeffects/pull/1252 what you want to do with a virtual mic?

**Comment by hitanol** [comment]
> how are you creating this virtual mic?

I'm using [this](https://github.com/siddhpant/broo) project to use my phone as a microphone via Mumble, it creates Broo Monitor sinl, and can use as a microphone input


And about it only loads at linked pipeline...
after you disconnect the jack, effects still available in patchbay (please don't fix this, for me it's an improvement :( )

**Comment by wwmm** [comment]
>I'm using [this](https://github.com/siddhpant/broo) project to use my phone as a microphone via Mumble, it creates Broo Monitor sinl, and can use as a microphone input

Based on its source code it creates a virtual mic through a `loopback` device https://github.com/siddhpant/broo/blob/20517ad00231d49f1bdecfc9d95bd14edcedd332/broo#L118. I think I have to do some tests with loopback devices. Something different may be happening with them.

**Comment by wwmm** [comment]
The problem has nothing to do with the usage of loopback devices. That program is creating the virtual mic with the code
```
pw-loopback --capture-props='media.class=Audio/Sink node.name=Broo node.description=Broo'
```
. And what the `Audio/Sink` does is creating an output device. You can even see it in EasyEffects output device selector. Things are working as they should on our side. In other for this device to be visible in our source selection menu it should have been created with `Audio/Source` or` Audio/Source/Virtual`.

Although output devices have monitors that can be used as a source in PipeWire it is better to create an actual source. Broo is doing the same procedure that has to be done on Pulseaudio. That is why they are creating a sink instead of a source.

Honestly mixing sink monitors with sources in our selection menu does not seem a good thing to do. It is what has to be done on Pulseaudio. But PipeWire offer better ways to create a virtual mic.

**Comment by wwmm** [comment]
Is this still a problem? I mean... The fact Broo creates a sink instead o a source is not something that should be fixed on our side. But what about the filters nodes not being visible in Patchbay?

**Comment by hitanol** [comment]
> Is this still a problem? I mean... The fact Broo creates a sink instead o a source is not something that should be fixed on our side. But what about the filters nodes not being visible in Patchbay?

yes, still happening, but the workaround to able the affects is connecting a physical jack to the mic port, then you can route the input effects
