### ISSUE TITLE
Not detecting PipeWire on Arch

### ISSUE THREAD

**Issue by empsps** [wwmm/easyeffects#1554]
### EasyEffects Version

6.2.5

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

It simply doesn't detect PipeWire. It's clearly installed, version 0.3.51.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Using the Arch package but same thing happened with Flatpak version.

**Comment by vchernin** [comment]
Could you get a log? `G_MESSAGES_DEBUG=easyeffects easyeffects` for arch.

**Comment by sph3** [comment]
```
(easyeffects:392473): easyeffects-ERROR **: 22:07:45.795: pipe_manager: context connection failed
fish: Process 392473, 'easyeffects' from job 1, 'G_MESSAGES_DEBUG=easyeffects ea…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by vchernin** [comment]
What is `pipewire --version`? Or `systemctl status --user pipewire`

**Comment by sph3** [comment]
`systemctl status --user pipewire`
```
○ pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
TriggeredBy: ● pipewire.socket
```

```
pipewire
Compiled with libpipewire 0.3.51
Linked with libpipewire 0.3.51
```

**Comment by wwmm** [comment]
>systemctl status --user pipewire

The output should be like this
```
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-05-31 21:14:00 -03; 59min ago
TriggeredBy: ● pipewire.socket
   Main PID: 1237 (pipewire)
      Tasks: 2 (limit: 38382)
     Memory: 27.9M
        CPU: 17.732s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─1237 /usr/bin/pipewire

mai 31 21:14:00 wwmm systemd[1101]: Started PipeWire Multimedia Service.
```
Your PipeWire service is dead.

**Comment by sph3** [comment]
It is running now, I enabled and started the service. But EasyEffects still doesn't work.

**Comment by wwmm** [comment]
>It is running now, I enabled and started the service. But EasyEffects still doesn't work.

Make sure you finish any instance `easyeffects -q` before testing.

**Comment by sph3** [comment]
`easyeffects -q` just gives me the same error and still doesn't work.

**Comment by wwmm** [comment]
Are commands like `pw-top`, `pw-dump` or `pw-cli list-objects Node` working? A failure to make a context connection usually means something is broken in PipeWire. I have never seen other causes.

**Comment by wwmm** [comment]
>All these commands output can't connect: Host is down or Error: "failed to connect: Host is down"

PipeWire may have started but something is broken. Did you try to reboot the computer?

**Comment by wwmm** [comment]
Besides what has been said by @vchernin also take a look at `sudo journalctl -b | grep -i pipewire`. Maybe the system's logs will show something interesting.

**Comment by azsorlex** [comment]
@sph3 @sephid86 I was just considering creating an issue about this: I reinstalled Arch, and easyeffects didn't work. So I installed `lib32-pipewire pipewire-pulse pipewire-jack lib32-pipewire-jack` (which removed their pulse counterparts), rebooted, and it worked. I'm not 100% sure if all of them are necessary, but I'm just glad it works.

**Comment by wwmm** [comment]
> I'm not 100% sure if all of them are necessary, but I'm just glad it works.

I do not have `pipewire-jack` and `lib32-pipewire-jack` installed. So these ones are not needed. In theory `pipewire-pulse` should not be needed because we do not make Pulseaudio calls. But for some reason PipeWire only exports its default metadata object when this package is installed.

**Comment by sephid86** [comment]
@azsorlex 
In my case, easyeffects works when pipewire and pipewire-pulse are installed.

Arch Linux.

And maybe pipewire-jack is not needed to run easyeffects.

And it is recommended to install wireplumber.

According to Archwiki, it is recommended to use wireplumber.

**Comment by azsorlex** [comment]
> In my case, easyeffects works when pipewire and pipewire-pulse are installed.
> 
> According to Archwiki, it is recommended to use wireplumber.

In that case, why aren't they listed as dependencies? Is it simply because they remove existing pulse-related packages? I think at this point if someone _wants_ to install easyeffects, they also _want_ to install everything needed for it to work and remove it's conflicts, given it doesn't obliterate the system.

**Comment by wwmm** [comment]
>In that case, why aren't they listed as dependencies?

I do not know how package maintainers take these decisions but in the case of `pipewire-pulse` it is probably because EasyEffects does not use it directly. Same thing with WirePlumber. From an API point of view we do not need any of them. The current package management situation is more related to PipeWire than to us. Eventually the built-in session manager will be removed from PipeWire and only WirePlumber will remain. And like I said before it is weird that PipeWire only provides some information when pipewire-pulse is installed.

**Comment by sephid86** [comment]
@azsorlex @wwmm 

As you may know, pipewire acts as a router.

It is used not only for audio but also for video.

Arch seems to have its current form to allow users to choose what they want to connect to the pipewire.

**Comment by Arkapravo-Ghosh** [comment]
> @sph3 @sephid86 I was just considering creating an issue about this: I reinstalled Arch, and easyeffects didn't work. So I installed `lib32-pipewire pipewire-pulse pipewire-jack lib32-pipewire-jack` (which removed their pulse counterparts), rebooted, and it worked. I'm not 100% sure if all of them are necessary, but I'm just glad it works.

Remove pipewire-pulse and mask wireplumber service globally if you have it. Also, the Flatpak version works well (You need to create your own autostart file though).

**Comment by vchernin** [comment]
> (You need to create your own autostart file though).

Only when the distro has broken or outdated portal packages, ubuntu 22.04 has nearly fixed theirs.

**Comment by wwmm** [comment]
I think this issue can be closed. We can't force Arch to change how software is package.
