### ISSUE TITLE
Looping volumes in Pipe Manager

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1555]
I was checking Pipe Manager.

https://github.com/wwmm/easyeffects/blob/3d4408303b8177b7b19efc37c7c8bac9cc47b361/src/pipe_manager.cpp#L593-L594

Aren't there too much `i++`?

Should be

```
for (uint i = 0U; i < n_volumes; max = std::max(volumes.at(i++), max));
```

**Comment by wwmm** [comment]
>Aren't there too much i++?

Yes. A long time ago clang-tidy complained about the empty for loop. I do not remember now if it was a serious warning or just something about it being bad practice. But I accepted its suggestion about how to fix it. In the process I probably did not notice the variable was incremented twice.
