### ISSUE TITLE
Convolver and dynamic output sample rate

### ISSUE THREAD

**Issue by Zhern** [wwmm/easyeffects#1558]
Since Pipewire is able to dynamically change output sample rates with no resampling (when possible), I wondered if there was a way to make the convolver equalizer able to load a different preset depending on the current sample rate?

For example, I currently force my output sample rate to 44100 and I set the convolver equalizer with a 44100 signal because I listen to music in CD quality 90% of the time.
I would like to enable Pipewire automatic output sample rate switching depending on the input signal (and on the DAC capabilities), but then the convolver equalizer should be able to automatically switch profile depending on the current sample rate.

**Comment by wwmm** [comment]
The convolver already follows the current sampling rate. What you may be thinking about is loading a different impulse response file depending on the current pipewire rate. In my opinion it is overkill. It is not the audio signal that is being resampled. It is just the impulse response file. Other convolvers also do this.

**Comment by wwmm** [comment]
I think we can close this issue.
