### ISSUE TITLE
Streamlining flathub deployments

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1573]
Just wanted to note, flathub is working on a few improvements to [the site](https://beta.flathub.org/apps/details/com.github.wwmm.easyeffects). Notably this includes the ability to either require or have optional payments for apps. Also, the build pipeline could eventually be done from this repo instead of from https://github.com/flathub/com.github.wwmm.easyeffects/. Does that sound interesting whenever the flathub work is ready?

A disadvantage of keeping the flatpak builds here is if something breaks, the fix would need to be pushed to master here. But that doesn't happen frequently if at all.

**Comment by wwmm** [comment]
>Does that sound interesting whenever the flathub work is ready?

Considering we already have some flatpak scripts here it makes sense. And most of the flatpak bug reports come to this repository anyway. Having to take a look at two different sites as we have been doing is not productive. The question is how complicated it will be to have the build pipeline here.

**Comment by vchernin** [comment]
> The question is how complicated it will be to have the build pipeline here.

It's fairly straightforward, we could reuse parts of [this comprehensive workflow](https://github.com/obsproject/obs-studio/blob/master/.github/workflows/flatpak.yml) (it already does more than what's necessary here). But it won't be very useful until flathub makes publishing tokens easily accessible.

**Comment by vchernin** [comment]
As with the other issue, I think this can be closed.
