### ISSUE TITLE
Adding feature to switch output device through the command line

### ISSUE THREAD

**Issue by FuriousBottle** [wwmm/easyeffects#1577]
Hi, I'm not sure if this goes against the intended use case for EasyEffects, but after I started using it as my main audio manager/controller, I wanted a way to change the output device through CLI so that I could do integrate it into a polybar module. I've forked the repository and have a working version to allow me to:
1. List available output devices, along with the Node ID
2. Set the output device using the Node ID provided through a call to g_settings_set_string

With these two functions, I am able to fulfill my intentions for a control module. Would this be a feature that you would be interested in incorporating, or should I have been going about this a different way from the start?

**Comment by Digitalone1** [comment]
We have a callback that updates the pipeline when the output/input device name changes in gsettings (if you provide the exact string of the name of the device). Why did you need the node ID? We already get it searching through all tracked nodes.

I gave a look at your code. We don't use stoi/stof anymore, have an util method str_to_num for locale undependent string conversion.

**Comment by Digitalone1** [comment]
> I guess I'm also trying to gauge if this is a feature that anyone would want? If it is, I can work on it further and get a bit more understanding of how the application works as a whole to align it with the overall strategy, but if not, then I won't pursue it much more.

It's nice, you're welcome. Anyway if you want a way to change the output device through the command line, outside the application, you can do it with gsettings utility:

https://manpages.ubuntu.com/manpages/trusty/man1/gsettings.1.html

`gsettings set SCHEMA [:PATH]  KEY VALUE`

Never tried it myself, but I assume it works if the syntax is correctly followed and the proper string is provided.

Improvements are welcome, but I don't get the point of using and exposing node ID in this stage. In the last commits we are also moving away from node id using pipewire serials or device names directly, see [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2409).

**Comment by FuriousBottle** [comment]
Cheers, I did have a look at the gsettings path, but I had varying levels of success with it - sometimes it would work and others it wouldn't.

Based on this conversation, I'll keep going with it, but use a better strategy and won't use the node IDs. Thanks again for the feedback, this is my first foray into attempting to contribute to a project, so you've given me a very pleasant introduction!

**Comment by Digitalone1** [comment]
> Cheers, I did have a look at the gsettings path, but I had varying levels of success with it - sometimes it would work and others it wouldn't.

Please explain more, when and how it didn't work. Was it only a wrongly typed string name or something wrong related to EasyEffects? The device name should be the exact string, even a different lower/uppercase letter can cause a fail in the string comparison.

Besides there should be also another way to trigger the change of the output device in EasyEffects. You could set the "Use Default Device" option and change the default device through Pipewire, even if I actually don't remember the command to do this. 

@wwmm do you know a command line executable for changing the default device through Pipewire?

**Comment by FuriousBottle** [comment]
Actually I think the gsettings appears to be working reliably now. I was probably having issues with it when I was playing around with new builds. There were a few times that I forgot to kill the process when it was running in gapplication-service mode in the background, and I would see different behaviours between newly created GUI processes and the background process (which is to be expected when they are different builds).

For reference, the gsettings command is below, where I would change the output device based on the node name. I expect, based on the name of the device, to change the default device could be an ALSA function rather than Pipewire? I couldn't see much about setting devices through pipewire itself when I looked.

`gsettings set com.github.wwmm.easyeffects.streamoutputs output-device alsa_output.pci-0000_2a_00.4.analog-stereo`

**Comment by wwmm** [comment]
>wwmm do you know a command line executable for changing the default device through Pipewire?

I never tried to do this through the command line even on Pulseaudio. But I imagine `pw-cli` must be capable of doing it. If not `pactl` can always be used even if it is a Pulseaudio utility.

**Comment by wwmm** [comment]
It does not seem `pw-cli` does this. It is probably `pw-metadata`.

**Comment by wwmm** [comment]
According to PipeWire's wiki https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Migrate-PulseAudio this should work
```
pw-metadata 0 default.configured.audio.sink '{ "name": "<sink-name>" }'
```

**Comment by FuriousBottle** [comment]
Thanks for that, I'll look into if I can do it that way instead as well. Thanks for the advice!
