### ISSUE TITLE
Convolver Import not working

### ISSUE THREAD

**Issue by dinotheextinct** [wwmm/easyeffects#1582]
### EasyEffects Version

6.2.5

### What package are you using?

openSUSE

### Distribution

Tumbleweed

### Describe the bug

When trying to import wav files in to the convolver I get the following error message from console:

`easyeffects-WARNING **: 00:50:25.122: convolver_menu_impulses:  Only stereo impulse files are supported!`

These two message from application start up:

`asyeffects:30858): easyeffects-WARNING **: 00:54:40.960: soe: convolver: irs file path is null. Entering passthrough mode...

(easyeffects:30858): easyeffects-WARNING **: 00:55:12.278: convolver_box: : irs file path is null.`

### Expected Behavior

Files being imported and EQ applied

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>convolver_menu_impulses: Only stereo impulse files are supported!

You are probably trying to load a `mono` impulse response file. At this moment only stereo files are supported.

**Comment by wwmm** [comment]
>Convolvers that support mono are probably converting the impulse to stereo internally.

OR applying the same file for each channel individually. In the end it should be the same as converting the file to stereo.

**Comment by dinotheextinct** [comment]
> > Convolvers that support mono are probably converting the impulse to stereo internally.
> 
> Or applying the same file for each channel individually. In the end it should be the same as converting the file to stereo.

But this is not possible within the Convolver?

**Comment by dinotheextinct** [comment]
By duplicating the mono file and making it stereo it sounds horrible.
[Stereo.zip](https://github.com/wwmm/easyeffects/files/8980662/Stereo.zip)

**Comment by wwmm** [comment]
>But this is not possible within the Convolver?

It is technically possible. But our code will have to go through some changes before trying to support mono files. As most of the impulse response files I have ever seen are ordinary stereo files mono support did not seem a high priority. And as far as I remember it would be the same as having a stereo file with the same data on both channels.

>By duplicating the mono file and making it stereo it sounds horrible.

It does and I do not think it has nothing to do with the duplication. Maybe the fact this impulse response file has over `1.5 seconds` is not playing nice with the zita convolver library we use for the convolution. Or this impulse is actually designed to make that amount of echo. The plots of its data are quite different from the impulse files I have here. What is the source of this impulse? From where did you get it?

**Comment by wwmm** [comment]
I downloaded the file in the link https://github.com/jaakkopasanen/AutoEq/blob/master/results/innerfidelity/innerfidelity_harman_over-ear_2018/Fostex%20TH610/Fostex%20TH610%20minimum%20phase%2048000Hz.wav and I've got a very different one. Are you sure there was no problems while downloading or converting it to stereo? Your files has a lot more data. I converted the file from mono to stereo following the steps at https://trac.ffmpeg.org/wiki/AudioChannelManipulation#monostereo. It is not exactly the same as duplicating the data but the different will be just in the volume.

**Comment by dinotheextinct** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Fostex%20TH610/Fostex%20TH610%20minimum%20phase%2044100Hz.wav

This is the file I used, yours is a different one.

**Comment by dinotheextinct** [comment]
Not even sure where you found yours, when going from the result page, I only get offered three entries, non of which are yours from innerfidelity.

**Comment by dinotheextinct** [comment]
Transformed your .wav to stereo, sounds also horrible sadly. ^^

**Comment by wwmm** [comment]
>Transformed your .wav to stereo, sounds also horrible sadly. ^^

How are you doing the conversion. This is the file I've got 
[teste.zip](https://github.com/wwmm/easyeffects/files/8984926/teste.zip). It not only sounds totally fine but it is a lot smaller than than one you provided before

> By duplicating the mono file and making it stereo it sounds horrible. [Stereo.zip](https://github.com/wwmm/easyeffects/files/8980662/Stereo.zip)

 Compare the plot of the data either in our convolver window or in Audacity. The file you generated has a completely different profile. Something is not right in it.

**Comment by wwmm** [comment]
Plot from your converted impulse
![Screenshot from 2022-06-25 11-32-50](https://user-images.githubusercontent.com/16225172/175778209-b9f560d8-168c-4342-b797-84a687292ba7.png)
The plot from the one I have generated from the link you provided
![Screenshot from 2022-06-25 11-31-47](https://user-images.githubusercontent.com/16225172/175778215-90b182cf-4a69-4b9f-bbdf-80ead125f106.png)

**Comment by wwmm** [comment]
I think I understand what is going on. Did you download that file clicking on the `Download` displayed in the github page or did you clicked on `View raw`? Do not click on raw. Use the download button so github gives you the file in the right format.

**Comment by wwmm** [comment]
When I open the binary returned by `View raw` I can see that there are html code embedded in it. I am not sure about what github is doing but you definitely do not want html code in your impulse response file :smile: .

**Comment by dinotheextinct** [comment]
Ohmaygawd, if thats truly the issue then I am sorry. How to fucking download the files though? I am so confused with github...now I see the download button, sheeeesh. Sorry for the trouble and thanks for all the feedback!

**Comment by dinotheextinct** [comment]
Sheeesh it sounds so good now! I am comparing this convolver equalizer against my parametric setting which I used before.

**Comment by vchernin** [comment]
I think https://github.com/wwmm/easyeffects/issues/1528 should be changed to convolver import, preset import and any other imports. It is a fairly easy mistake to make with GitHub.

**Comment by dinotheextinct** [comment]
What should I do when on the bottom left an Exclamation Mark appears left of the db displays? Is that clipping? How can I prevent it? Its audible.

**Comment by wwmm** [comment]
>What should I do when on the bottom left an Exclamation Mark appears left of the db displays? Is that clipping? How can I prevent it? Its audible.

If you are not using the autogain plugin or it does not make sense to use it for what you want to do you will have to set the input gain / output gain controls in a way clipping is avoided. It is a good idea to have a limiter as the last plugin in the pipeline.. But it is more for safety measures. If possible set the input/output gain in a way clipping is avoided.

**Comment by dinotheextinct** [comment]
Alright, how does the Autogain setting work? Because I would like to test easily with same Volume levels against the Equalizer from my RME DAC.

**Comment by wwmm** [comment]
>I think https://github.com/wwmm/easyeffects/issues/1528 should be changed to convolver import, preset import and any other imports. It is a fairly easy mistake to make with GitHub.

Yes. But in this particular case it is tricky to figure out there is a problem. The file with html code plays like any other wave file. I only noticed the problem when I tried to view its binary content. VLC played it without complaints...

**Comment by wwmm** [comment]
>Alright, how does the Autogain setting work?

In most cases I have a limiter as the last plugin and the autogain right before it. For my workflow the default autogain settings are enough to have a decent automatic volume control. But depending on you you set you applications volume you may wan to adjust the target level.

Our autogain adjusts volume based on the EBUR128 standard for loudness normalization. In other words it is based on perceived loudness.

**Comment by wwmm** [comment]
>Because I would like to test easily with same Volume levels against the Equalizer from my RME DAC.

In this case you want to have the autogain before the equalizer in the pipeline.

**Comment by vchernin** [comment]
> The file with html code plays like any other wave file. I only noticed the problem when I tried to view its binary content. VLC played it without complaints...

True it does accept any file, but I think we could check for html headers for the impulse to avoid this common case.

**Comment by wwmm** [comment]
>In this case you want to have the autogain before the equalizer in the pipeline.

Ignore this comment. Only now I saw you talked about the equalizer from your DAC.

**Comment by wwmm** [comment]
>True it can technically accept any file, but I think we could check for html headers for the impulse import to avoid this common case. I highly doubt anyone actually wants to import a html file into the impulse.

That would help. Although I have no idea about how to check this in a binary file :smile:

**Comment by wwmm** [comment]
I think we can close this.
