### ISSUE TITLE
Pre-amp gain in EQ

### ISSUE THREAD

**Issue by bhack** [wwmm/easyeffects#1592]
### EasyEffects Version

6.2.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu

### Describe the bug

I'am loading different eq APO audio profiles from autoeq project.
I see on the GUI that the negative preamp value is applied correctly from what it is specified in the APO.

But I've attached an x42 lv2 plugin meter on the device monitor out sink and I see the avg and peak LUFS but especially the  dBTP values lowered.

E.g. with the EQ bypassed we have something like a peak <1 dBTP when we have EQ on it switch at <7 dBTP peaks. 

I expect that the negative gain it is just going to compensate the freq we boost to avoid clipping but it is quite strange that we are loosing so many dB of peak.

What do you think?

### Expected Behavior

I expect quite near dBTP value with and without EQ.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by bhack** [comment]
> The first thing I would do is checking if it happens only when the pre-amp gain is set to the equalizer or to any of the other plugins. 

Do we have a quite neutral plugin to do this test_ So that I could lower the input gain and check the effect on the dBTP peak.

**Comment by bhack** [comment]
> The idea is to compensate and avoid clipping but the input/output gain control acts on the whole signal and not on a particular frequency. So this is something to have in mind.

Yes I suppose that we need to measure the peak for every frequency but it is quite strange that on different samples we have always this quite large margin in db on peak.

**Comment by wwmm** [comment]
>Do we have a quite neutral plugin to do this test?

I think the `delay` plugin with zero delay applied is a good candidate. Or the limiter as long as the signal level does not make it active.

**Comment by wwmm** [comment]
>Yes exactly I've just tried with the delay with a 30sec sample and -5db input gain impact the dBTP in the meter from -9.1 to -3.9 so in this case it is quite accurate.

So the unexpected level difference is only with the equalizer plugin? What happens if you set all your band gains to zero?

**Comment by bhack** [comment]
I will test right now. 
In the meantime could it be caused by the fact that filters are calculated at 48kHz and we could using at 44.1kHz?

https://github.com/jaakkopasanen/AutoEq/issues/240#issuecomment-752201931

**Comment by bhack** [comment]
P.s. with a flat equalizer is ok:
 -5db input gain and in the meter from -3.9 to -8.9 dBTP

**Comment by wwmm** [comment]
>In the meantime could it be caused by the fact that filters are calculated at 48kHz and we could using at 44.1kHz?

Although I am a physicist digital signal processing isn't really my expertise. The author of the LSP equalizer has far more experience with all the math involved and can definitely properly answer this question. But based on the little I remember about how true peaks are determine I think it makes sense sampling rate makes some difference. What I am not sure is if the difference should be noticeable.

**Comment by wwmm** [comment]
>P.s. with a flat equalizer is ok:
-5db input gain and in the meter from -3.9 to -8.9 dBTP

In this case our input/output gain code is fine. If it is related to how the equalizer works it is better to ask about this to the LSP author. Is there any difference if you change the equalizer mode between `IIR`, `FIR`, `FFT` and `SPM`?

**Comment by wwmm** [comment]
Are you setting each band mode to `APO`? I think these AutoEQ profiles are created with the type of model APO uses in its equalizer. Different filter algorithms may lead to different results.

**Comment by bhack** [comment]
I guess, when we have an autoeq EQ profile with a max gain peak on a very low freq (e.g. +5.xDb) it set then the input gain negating that value to -5.xDb and it will lower all the other frequency peaks. 
But do you think could be it harder to clip at that frequencies (e.g. mastering will generally have more headroom on these low frequencies)? 
So that in the end we have only an effect to avg lowering the volume and increasing the headroom of all the other frequencies and so lowering the dBTP peaks?

**Comment by wwmm** [comment]
>So that in the end we have only an effect to avg lowering the volume and increasing the headroom of all the other frequencies and so lowering the dBTP peaks?

Usually the too much amplification to low frequencies can easily cause clipping. So it makes sense the pre-amp gain was setting only looking at it. But as the pre-amp will be applied to the whole signal all frequencies will have their peak reduced by this amount. But I do not think this is the whole story. 

In a equalizer you will have overlap between bands. Besides the amplification/reduction that comes from the pre-amp and from the low frequency band some amount of change to its amplitude will be caused by the neighbor bands. I have my doubts the pre-amp value is taken this in consideration.

In any case I am just guessing. I never looked at the math behind equalizers.

**Comment by bhack** [comment]
> In a equalizer you will have overlap between bands. Besides the amplification/reduction that comes from the pre-amp and from the low frequency band some amount of change to its amplitude will be caused by the neighbor bands. I have my doubts the pre-amp value is taken this in consideration.

This is true.

But what I see in @jaakkopasanen autoeq is a very trivial approach (headroom is a constant of -0,2):

https://github.com/jaakkopasanen/AutoEq/blob/master/autoeq.py#L117

If you randomly sample an @oratory1990 preset it doesn't have this approach as pre-amp gain compensation are not exactly the negation of the max freq gain - an headroom constant:
https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets

See his two replies in this recent thread:
https://www.reddit.com/r/oratory1990/comments/uaoxi5/weekly_roratory1990_eq_thread_questions_requests/i7jb2zp/

**Comment by wwmm** [comment]
>See his two replies in this recent thread:

As expected the "correct" pre-amp value will depend on the relative position between bands or whatever is being applied to the signal. The difference you see may be coming from this.

**Comment by bhack** [comment]
I will try to open a ticket in autoeq.

**Comment by bhack** [comment]
We can track https://github.com/jaakkopasanen/AutoEq/issues/474

**Comment by bhack** [comment]
@wwmm I am thinking, other then eventually fixing upstream calculated gain compensations values for the imported presets as users could use these just as a baseline and then customize it directly in easyeffects could we have a button on our side to calc the required pre-amp negative gain compensation to avoid clipping?

**Comment by wwmm** [comment]
>could we have a button on our side to calc the required pre-amp negative gain compensation to avoid clipping?

I have my doubts this can be properly done outside of the plugin code. I think the most we can do is setting the input/output gain based on the maximum amplification value among the bands. But taking into account the overlap and the interaction between bands is probably only possible with information that is only inside the plugin. Just setting the input value based on the highest amplification is something the user can do easily. Adding a button just for this isn't going to be of much help.

**Comment by bhack** [comment]
> Just setting the input value based on the highest amplification is something the user can do easily. Adding a button just for this isn't going to be of much help.

Yes this is useless.

> But taking into account the overlap and the interaction between bands is probably only possible with information that is only inside the plugin.

This is the point, @sadko4u what do you think?

**Comment by sadko4u** [comment]
I literally don't understand the problem.
When you're inserting an EQ into the audio chain, you're modifying the balance between all frequencies in the audio signal.
There is no surprise that by changing the spectrum you change the LUFS, dBTP and EBU values.
Moreover, even just phase changes can modify the dBTP values.
If you want to compensate frequency boost or frequency cut, this wil work not always and under several conditions.
Let's consider you have an 1 kHz sine generator at 0 dBFS and has cut all below 100 Hz with the high-pass filter.
According to your understanding, the EQ should compensate the cutted out 100 Hz by boosting all frequencies above the 100 Hz. But that will make sound 1 kHz sine signal louder than 0 dBFS and it will start to overdrive the channel.

**Comment by bhack** [comment]
It was not exactly the point. 
It is more that autoeq presets we import are simply going to set the pre-amp gain to avoid clipping at  `-(peq_max_gains - 0.2)`. So basically it take the max gain in peq and then it compensate with its negation in the pre-amp gain.

But if you take any of the oratory1900 [eq presets](https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets) it is just not the max gain in peq minus an headroom margin:
https://www.reddit.com/r/oratory1990/comments/uaoxi5/weekly_roratory1990_eq_thread_questions_requests/i7jb2zp/
>     Does the preamp gain correlate directly to the largest dB boost in the profile
>  yep!
But remember that filters will overlap. So the pre-amp gain is not equivalent to the highest gain parameter of any of the filters you enter, but it's equivalent to the highest gain resulting in the total transfer function (all filters combined).
E.g. when you have a low-shelf filter at 100 Hz with a gain of 5.5 dB, and you also have a peak filter at 30 Hz with a gain of 3 dB, then the needed pre-amp gain would be -8.5 dB.
However if the peak filter would be at 200 Hz instead of 30 Hz, the pre-amp gain would have to be at 5.5 dB instead (unless the peak filter has a very low Q-factor and still has a notable effect below 100 Hz, in which case the pre-amp gain maybe would need to be a bit lower)

Generally users adjusting peq filters from these baselines or set values from scratch. So the point here is if the plugin can calculate the required negative gain to avoid clipping/overdrive one we have finalized the PEQ.

> According to your understanding, the EQ should compensate the cutted out 100 Hz by boosting all frequencies above the 100 Hz. But that will make sound 1 kHz sine signal louder than 0 dBFS and it will start to overdrive the channel.

I just expect on the avg on different enough music tracks I could achieve almost the same dBTP in the monitor with and without EQ with the right pre-amp compensation.

**Comment by sadko4u** [comment]
LSP Plugins don't provide the automatic gain compensation at this moment.
Moreover, I find that adding some peak filter to the chain will automatically lower all unrelated frequencies and you will lose the LUFS value for the track. That's so called 'masking effect'.


There is probably a related issue here:
https://github.com/sadko4u/lsp-plugins/issues/188

**Comment by bhack** [comment]
If I understend correctly LUFS could be impacted negatively for sure as not all the frequencies have the same weight in LUFS. 
So e.g. if we are going  in PEQ to boost a quite low frequency +9 dB  in PEQ with a pre-amp gain of -9 dB probably we are going to impact the LUFS enough as we are going to lower all the other frequency by -9 dB and so also frequencies that has more specific eight in the LUFS.
 
What I expect on the avg is that on multiple tracks the the dBTP is not too far from 0 dBTP with or without EQ.

The point for the EQ/plugin I think is more:
How we could automatically calculate the pre-eq (negative) gain  to not overdrive/clamp the track > 0 dBFS considering the highest gain resulting in the total transfer function (all filters combined)?

**Comment by sadko4u** [comment]
> How we could automatically calculate the pre-eq (negative) gain to not overdrive/clamp the track > 0 dBFS considering the highest gain resulting in the total transfer function (all filters combined)?

This is not trivial question. With the single frequency that easy. With the multiple frquencies probably we need to integrate the magnitude over the all audible spectrum or find the maximum peak over the spectrum or... That requires heavy R&D, I think.

**Comment by bhack** [comment]
> This is not trivial question. With the single frequency that easy. With the multiple frquencies probably we need to integrate the magnitude over the all audible spectrum or find the maximum peak over the spectrum or... That requires heavy R&D, I think.

@oratory1990 How do you calc your pre-amp gain in your PDFs ?

**Comment by oratory1990** [comment]
find the global maximum of the magnitude transfer function and multiply by minus 1.  
  
This is the safest way to do it - if the transfer function amplifies by no more than 5 dB, then the level will not increase by more than 5 dB.  
Since real-life usecases will not typically be maximum amplitude monofrequent, it is often sufficient to use less pre-amp gain (= a number closer to 0), very often it's fine to simply not apply any pre-amp gain at all.  
  
That's because real-life signals (music, speech) rarely feature content where a single frequency will reach the maximum signal amplitude, instead it will be a broad spectrum, no single frequency reaching maximum amplitude.

**Comment by bhack** [comment]
As an additional note I think that we have more opportunity to clip when the max of the EQ curve is quite flat as we are covering more frequencies with an expected clip.

E.g. this is oratory's EQ curve for SUNDARA and the peak is quite flat:
![immagine](https://user-images.githubusercontent.com/1710528/177332551-f6e86b65-3113-4fce-bb19-78d46f2ec579.png)


We have a suggested -4.9 Db pre-amp compensation:

![immagine](https://user-images.githubusercontent.com/1710528/177333026-fba1e3d8-a0c7-400e-8b9c-4b480c2e069e.png)

![immagine](https://user-images.githubusercontent.com/1710528/177333303-f3773446-dc3a-49b8-b91c-f6538eec866c.png)

So we are penalizing with -4.9 Db frequencies that are not boosted and could impact more the LUFS.

**Comment by bhack** [comment]
Just to complete, the K-weighting curve for LUFS/LKFS (from [Audacity docs](https://alphamanual.audacityteam.org/man/Perceived_Loudness_(EBU_R_128))):

![immagine](https://user-images.githubusercontent.com/1710528/177568029-e3b77421-acc4-41bf-86b1-fc551318f1c9.png)

It is quite clear that if we are going to globally compensate -4.9 dB mainly for the +5.0 dB boost on band 1 in the previous SUNDARA example we are going to impact LUFS enough as higher frequency have more dB weight in the LUFS calc.

**Comment by bhack** [comment]
So I don't think that we have any solution to recover LUFS as we could be in the case to need to compensate globally pre-gain for boosted low k-weigthing freq in PEQ.

> find the global maximum of the magnitude transfer function and multiply by minus 1.
This is the safest way to do it - if the transfer function amplifies by no more than 5 dB, then the level will not increase by more than 5 dB.

@wwmm We can do this in EasyEffects or we need to calc this in the @sadko4u EQ plugin?

> Since real-life usecases will not typically be maximum amplitude monofrequent, it is often sufficient to use less pre-amp gain (= a number closer to 0), very often it's fine to simply not apply any pre-amp gain at all.
That's because real-life signals (music, speech) rarely feature content where a single frequency will reach the maximum signal amplitude, instead it will be a broad spectrum, no single frequency reaching maximum amplitude.

Given a specific EQ configuration/preset this seems to be totally related to a "sufficient sample" of music tracks that you are listening. 
So what do you think about having a sort of function that will let to set minimum reference headroom (-0.2/-0.1 dBTP?) and that dynamically autoset pre-amp gain monitoring the dBTP > 0 multiplied by minus 1 - headroom?

I think that after few tracks you could achieve a good auto pre-amp gain value on real data thus limiting LUFS sacrifice.

What do you think?

**Comment by wwmm** [comment]
>We can do this in EasyEffects or we need to calc this in the @sadko4u EQ plugin?

I never calculated a transfer function. But if I remember well it is something that the equalizer code would be doing. I don't think it can be done externally.

**Comment by bhack** [comment]
P.s. The Logic could be similar to:
https://x42-plugins.com/x42/x42-limiter

But without permanetly use/run that plugin and only to fine tune a tracks driven safe enought pre-amp gain value.

**Comment by bhack** [comment]
@wwmm AutoEq was already calculated correctly https://github.com/jaakkopasanen/AutoEq/issues/474#issuecomment-1193665037.

> Since real-life usecases will not typically be maximum amplitude monofrequent, it is often sufficient to use less pre-amp gain (= a number closer to 0), very often it's fine to simply not apply any pre-amp gain at all.
That's because real-life signals (music, speech) rarely feature content where a single frequency will reach the maximum signal amplitude, instead it will be a broad spectrum, no single frequency reaching maximum amplitude.

I this ticket, as suggested, I think it is still valid if we could add a feature to find a more dynamic/real-life pre-amp value to avoid at the same time clipping on average and to not sacrificing the LUFS too much with just the theoretical negative pre-amp gain.

**Comment by jaakkopasanen** [comment]
It's quite dangerous for me to start calculating LUFS values or something like that since it's impossible to know the source material in advance.

I could perhaps add a `--preamp` parameter though, which is added on top of the automatic preamp. Would then work for GraphicEq and FIR filters.

**Comment by bhack** [comment]
> It's quite dangerous for me to start calculating LUFS values or something like that since it's impossible to know the source material in advance.
> 
> I could perhaps add a `--preamp` parameter though, which is added on top of the automatic preamp. Would then work for GraphicEq and FIR filters.

This was my draft idea on the previous comment:

> Given a specific EQ configuration/preset this seems to be totally related to a "sufficient sample" of music tracks that you are listening.
So what do you think about having a sort of function that will let to set minimum reference headroom (-0.2/-0.1 dB?) and that dynamically autoset pre-amp gain monitoring the dBTP > 0 multiplied by minus 1 - headroom?
I think that after few tracks you could achieve a good auto pre-amp gain value on real data thus limiting LUFS sacrifice.
What do you think?

**Comment by Odin000** [comment]
I'm stuck here, EasyEffects on my PC is not Clipping but the one on my Laptop is Clipping with the same preset. both have the same version 6.3.0.
Just to make it clear, on my PC I need to lower my Input gain with the same db amount I raised in my eq => no clipping all fine.
when I do the same on my Laptop it's clipping, do u think the problem is related ?

**Comment by wwmm** [comment]
Can you hear the clipping or is EasyEffects showing the clipping warning in its bottom bar? One possibility is that you have a different input signal level getting to EasyEffects or that your laptop soundcard or its driver have some influence in this behavior.

in any case I suggest you have a limiter as the last plugin in the pipeline to have some form of soundcard protection against too high signal levels. After that the only thing you can do is taking a look at the maximum signal levels you usually send to EasyEffects and adjusting the input/output gains so that you do not have clipping.

**Comment by Odin000** [comment]
I can definitely hear the clipping, and it's showing on the bottom bar.
How to check if I have another input signal level getting to EasyEffects ? 
adding the Limiter solves the clipping problem, thanks alot

**Comment by Odin000** [comment]
EasyEffects just crashed, which didn't happen before, and after starting it again on my PC, it started clipping just like on my Laptop, so I just added the Limiter to the pipeline here too, anyway what I've realized is, that the limiter is just preventing the clipping while the input gain is not getting reduced, I mean the Quality of sound is suffering still.
I donno what's the Problem here, and hope  it's not a big issue.

**Comment by wwmm** [comment]
>the limiter is just preventing the clipping while the input gain is not getting reduced, I mean the Quality of sound is suffering still.

Yes. You want the limiter there as a last resort. Ideally you do not want it to touch the signal.

>How to check if I have another input signal level getting to EasyEffects ?

usually only the applications that have effects enabled will be sending audio to it. But you can see everything that is linked to our virtual devices running `pw-dot` and viewing its output file with the command `xdot`. Helvum is another program that can see the links.

**Comment by wwmm** [comment]
>I donno what's the Problem here, and hope it's not a big issue.

I think all you have to do is setting the input/output equalizer gain to lower values. Like explained in the posts above compensating for the extra amplification done by the equalizer bands is not something easy to be done automatically. So the users have to be on the safe side and reducing the gains to a value that is low enough to avoid clipping.
