### ISSUE TITLE
Failure to start, "Message recipient disconnected from message bus without replying"

### ISSUE THREAD

**Issue by magicgoose** [wwmm/easyeffects#1598]
### EasyEffects Version

6.2.6-1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

(It started happening in the latest version and maybe the one before it. Used to work just fine.)
When attempting to start easyeffects from KDE UI, it would not start, instead shows an error message:

> Message recipient disconnected from message bus without replying

When started from terminal, it would also fail, but only once after OS booted. After that, it starts normally (only from terminal). When it fails, the error is the same:

> GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

### Expected Behavior

easyeffects launches normally

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:13432): easyeffects-DEBUG: 12:48:11.843:       easyeffects.cpp:35      easyeffects version: 6.2.6
(process:13432): easyeffects-DEBUG: 12:48:11.843:       easyeffects.cpp:45      locale directory: /usr/share/locale
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:72  system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:72  system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:72  system input presets directory: "/home/user/.config/kdedefaults/easyeffects/input"; 
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:75  system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:75  system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:75  system output presets directory: "/home/user/.config/kdedefaults/easyeffects/output"; 
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:215 user presets directory already exists: /home/user/.config/easyeffects/
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:215 user presets directory already exists: /home/user/.config/easyeffects/input
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:215 user presets directory already exists: /home/user/.config/easyeffects/output
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:215 user presets directory already exists: /home/user/.config/easyeffects/autoload/input
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.845:   presets_manager.cpp:215 user presets directory already exists: /home/user/.config/easyeffects/autoload/output
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
(easyeffects:13432): easyeffects-DEBUG: 12:48:11.902:   easyeffects.cpp:60      Exitting the main function with status: 1
```
</details>

### Additional Information

Operating System: Arch Linux
KDE Plasma Version: 5.25.1
KDE Frameworks Version: 5.95.0
Qt Version: 5.15.5
Kernel Version: 5.18.6-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 62.7 GiB of RAM

**Comment by Digitalone1** [comment]
Arch Gnome Wayland here, no issue. Can you try on Plasma Wayland?

**Comment by wwmm** [comment]
That is weird. The new release does not have changes that would justify a DBUSc connection failing. Install the package `gtk4-demos` and run `gtk4-demo` in a terminal. Does it starts normally? It may also be good to test the libadwaita demo from the package `libadwaita-demos`.

**Comment by magicgoose** [comment]
> That is weird. The new release does not have changes that would justify a DBUSc connection failing. Install the package `gtk4-demos` and run `gtk4-demo` in a terminal. Does it starts normally?

Yes. Same for `adwaita-1-demo` except it uses a wrong theme (non-dark, when dark is set system-wide).

> Can you try on Plasma Wayland?

Yes in a few minutes...

**Comment by magicgoose** [comment]
> does the same thing happens if you install the AUR package?

Yes (installed using `paru -S easyeffects-git` which automatically removed the other package).

**Comment by wwmm** [comment]
>Yes (installed using paru -S easyeffects-git which automatically removed the other package).

So the this bug must be related to KDE somehow. What is weird because I would expect lost of people reporting problems if EE were broken on KDE. As I have GNOME on all my computers I can't test on KDE right now.

If you create a new user is the bug still present? Maybe somewhere a configuration got corrupted.

**Comment by vchernin** [comment]
> Same for adwaita-1-demo except it uses a wrong theme (non-dark, when dark is set system-wide).

This also sounds like a broken setup, since kde supports the freedesktop dark preference/color scheme portal. Your system wide dark mode setting should be followed by libadwaita apps like the libadwaita demo or easyeffects (provided you haven’t overridden it in the app settings). Maybe this [wiki entry](https://github.com/wwmm/easyeffects/wiki/FAQ#on-kde-plasma-524-or-later) helps?

**Comment by hridampalwe** [comment]
Can confirm same happening with me 
Distribution : Endeavour OS

**Comment by wwmm** [comment]
>Launching from command line works fine but launching from plasma shortcut results in described plasma notification.

That is interesting. When the user clicks on our desktop icon DBUS should be used to launch EasyEffects in service mode. That is why in our desktop file we set the property `DBusActivatable=true` and we install the file `/usr/share/dbus-1/services/com.github.wwmm.easyeffects.service`. So it makes sense you do not see a warning when launching from the command line.

Support for `DBusActivatable` programs is something that has to be implemented by the desktop. The application just indicates that this should be used and install the dbus service file. The rest should be done by the desktop. This may explain why users on KDE are seeing this error but not the ones on GNOME. It looks like a KDE bug.

**Comment by hridampalwe** [comment]
>  It looks like a KDE bug.

Ah thank you for clarifying.

**Comment by SadPersonn** [comment]
same issue

**Comment by yorigcs** [comment]
Same here :/

**Comment by wwmm** [comment]
Everyone with the "same issue" is also able to launch from the command line? Or is it crashing there too? If yes it may be #1606. But if not the only thing I can think of at this moment is a KDE bug.

**Comment by xVanjaZ** [comment]
I just got a clean install of Arch with KDE and I get the same message notification. Whenever I try to run it from the CLI I get the following:
```$ easyeffects

(easyeffects:7214): Gtk-WARNING **: 22:06:04.042: Locale not supported by C library.
        Using the fallback 'C' locale.

(easyeffects:7214): Adwaita-WARNING **: 22:06:04.156: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.224:       lv2_wrapper.cpp:65      Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.224:       lv2_wrapper.cpp:353     http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.224:       lv2_wrapper.cpp:353     http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.224:       lv2_wrapper.cpp:353     http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.373:       lv2_wrapper.cpp:65      Could not find the plugin: urn:zamaudio:ZaMaximX2

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.373:       lv2_wrapper.cpp:353     urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.373:       lv2_wrapper.cpp:353     urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.373:       lv2_wrapper.cpp:353     urn:zamaudio:ZaMaximX2 port symbol not found: rel

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.455:       lv2_wrapper.cpp:65      Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.455:       lv2_wrapper.cpp:353     http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.455:       lv2_wrapper.cpp:353     http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.455:       lv2_wrapper.cpp:353     http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.600:       lv2_wrapper.cpp:65      Could not find the plugin: urn:zamaudio:ZaMaximX2

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.600:       lv2_wrapper.cpp:353     urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.600:       lv2_wrapper.cpp:353     urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:7214): easyeffects-WARNING **: 22:06:04.600:       lv2_wrapper.cpp:353     urn:zamaudio:ZaMaximX2 port symbol not found: rel
locale::facet::_S_create_c_locale name not valid
```

**Comment by Digitalone1** [comment]
@xVanjaZ please try `easyeffects-git` from AUR.

**Comment by xVanjaZ** [comment]
@Digitalone1 Thanks for the reply (I wasn't expecting to get a reply that fast). That seems to work! Thanks a lot!
