### ISSUE TITLE
Presets drop-down menu steals focus and can result in all system inputs being ignored

### ISSUE THREAD

**Issue by zephyrj** [wwmm/easyeffects#1605]
## Environment
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 5.17.15-76051715-generic 
Shell: bash 5.1.16 
Resolution: 3840x2160 
DE: GNOME 42.1 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal

## EasyEffects installation
Flatpak
Version 6.2.6

## Issue seen
When clicking on the `Presets` drop down button in the top-left of the app it takes the focus of the mouse and keyboard away from everything else on the Desktop - you cannot select other windows or click any OS buttons. If you click the `Presets` menu button again then the focus is returned and everything is selectable.

A worse situation occurs if you open the `Presets` drop-down and then select `Import Presets` - this opens a file picker behind the `Presets` drop-down but in-front of the main app window. The result is that the `Presets` drop-down still grabs the mouse and keyboard focus so you cannot interact with the file-picker and because the main app screen is behind the file-picker you can't select the `Presets` button to close the drop-down. When in this state you can't interact with anything on the system - keyboard and mouse presses are all ignored with no obvious way to get out of the situation.

I can't provide a screenshot I'm afraid because, as described above, my system is unusable in this state. I have attached the debug output.
[easyeffects-output.txt](https://github.com/wwmm/easyeffects/files/8999372/easyeffects-output.txt)

**Comment by wwmm** [comment]
Unfortunately it is a known problem with gtk4. Take a look at #1182 and #1179. In the case of the menus you can try to play with the option `Hide Menus on Outside Clicks`. In some cases it will avoid the lock but the downside is that you will only be able to close the menu if you click again on its button. This was the most I could do on my side. The real fix has to be done by the gtk4 developers. I think the related issues about these problems are still open in their GitLab page.

As we already have an older issue about this I will close this one.

**Comment by hevanaa** [comment]
Just ran into this issue on Fedora 37 on Gnome and latest easyeffects flatpak from flathub (easyeffects v7.0). If someone else encounters this, the 6.3 version from Fedora project repositories works fine (install with "dnf install easyeffects"). 

Here is how to get out of the locked window. Press Ctrl-Alt-F3 (or F4, any Fx other than your window session) to get to a command prompt. Login and run "killall easyeffects". Switch back to your window session with Ctrl-Alt-F2. 

The reason I tried the flatpak is that there are some quirks in the 6.3 version, too. 

1. I'm using the default Dark Theme in Gnome and I there is no visible indication in which state the buttons "Enable/disable the global bypass" and "Enable/disable this effect" are in. So I have to watch the input/output levels to see if the effect is on/off.

2. The convolver graph is also strange. It shows a grap from 0.00 to 0.09 s, but the graph x y axis have way too large scale, so the signal shown is a tiny one above the 0.00 number. Also the x y numbers in the  upper right corner have no relation to where the mouse is in the window (at least what the x scale shows). 

Not sure if I should report these issues separately or if they are known. I have no intention to test the 7.0 version further until the gtk4 issues are sorted.
