### ISSUE TITLE
Feature Request: parameter to save/dump the currently active configuration `--dump-current-config`

### ISSUE THREAD

**Issue by igsz** [wwmm/easyeffects#1608]
### EasyEffects Version

4.8.4

### What package are you using?

Other (specify below)

### Distribution

Ubuntu 22.04

### Describe the bug

Thank you for this great tool! I use it a lot. In fact, I change the settings quite frequently, such that I have implemented keyboard shortcuts to apply certain settings on demand. I know that there are presets, but I need to enable/disable individual filters or tweak specific parameters of filters and it is not feasible to define a preset for each of them. Therefore, I have implemented a new parameter `--dump-current-config` which writes a preset named `current` to disk. I can then modify this file using scripts and load the modified script with `--load-preset current`. In effect, this mechanism can be used as sort of an API to modify all aspects of all filters programmatically. What do you think, would such a parameter be worth incorporating into the main code repository? It was really easy to implement (just needed to add a new parameter and call `presets_manager->save`). Until a proper API is available, this may be a quick and easy solution. I can submit a pull request if that helps, but I figured you probably have your own/better idea about how to implement it (if you find it useful).

**Comment by wwmm** [comment]
>4.8.4

Are you sure this is the version? I ask because this is a `PulseEffects` version. And nowadays PulseEffects only gets fizes for critical bugs. Current development is on EasyEffects.

>What do you think, would such a parameter be worth incorporating into the main code repository?

I see no problems in adding a `--dump-current-config` option that saves everything to a file. But we already have an option that loads presets. They just have to be in the usual preset folder.

>In effect, this mechanism can be used as sort of an API to modify all aspects of all filters programmatically.

It isn't really needed considering `GSettings API` can be used to change any of our parameters. There is no need to generate json files.

**Comment by igsz** [comment]
Thanks for the prompt reply.

> Are you sure this is the version?

No, hehe. This is a PulseEffects version. My feature request is equally valid for EasyEffects, I guess though.

> GSettings API can be used to change any of our parameters

I wasn't aware of this API. I keep getting surprised at how powerful this tool is. I agree, this is much better than the JSON file-based interaction. However, the GSettings API seems incomplete. For example, there is no config value for the input or output level of the `Limiter` filter. All I can do via GSettings is turn the filter off or on (or is this different in EasyEffects?). Is it possible to expose this filter property via the API?

**Comment by wwmm** [comment]
You should be able to control almost every parameter through the GSettings API. Take a look at https://github.com/wwmm/easyeffects/discussions/916. Everything that is shown inside the `dconf-editor` window can be changed through the GSettings API. You just have to know the right path for each key. But you can figure out it through the dconf-editor window.

**Comment by wwmm** [comment]
>or is this different in EasyEffects?

There is a small difference in how the database is managed in EasyEffects. It uses what Gsettings calls `relocatable schemas`. But putting this aside it is almost the same things that is done in PulseEffects.

**Comment by igsz** [comment]
I got it to work with your hints. Thanks!
