### ISSUE TITLE
EasyEffects doesn't detect input or output devices

### ISSUE THREAD

**Issue by abbyck** [wwmm/easyeffects#1614]
### EasyEffects Version

6.2.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux with Gnome 42.2

### Describe the bug

I've installed easyeffects via pacman.
On launching easyeffects, I can not see any audio applications or sampling rate or any such info.
Also, unable to play the test signal from Pipewire tab.
![image](https://user-images.githubusercontent.com/19362717/176961135-80be6c38-292f-4159-b88c-2e100d6c155a.png)

I've checked pipewire installed.
```
pw-cli dump short core
0: u="abbyck" h="prime" v="0.3.52" n="pipewire-0"
```
These are the clients listed on pipewire -> Clients menu
![image](https://user-images.githubusercontent.com/19362717/176961667-b7f6d7c4-57b6-4f1f-a468-17ae69dc8e8f.png)

logs also didn't say much. Could someone please point out to me what am I missing

### Debug Log

<details><summary>Debug Log</summary><br/>

```G_MESSAGES_DEBUG=easyeffects easyeffects
(process:24836): easyeffects-DEBUG: 01:23:46.578: 	easyeffects.cpp:35	easyeffects version: 6.2.6
(process:24836): easyeffects-DEBUG: 01:23:46.580: 	easyeffects.cpp:45	locale directory: /usr/share/locale
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:72	system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:72	system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:75	system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:75	system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:215	user presets directory already exists: /home/abbyck/.config/easyeffects/
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:215	user presets directory already exists: /home/abbyck/.config/easyeffects/input
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:215	user presets directory already exists: /home/abbyck/.config/easyeffects/output
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:215	user presets directory already exists: /home/abbyck/.config/easyeffects/autoload/input
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.582: 	presets_manager.cpp:215	user presets directory already exists: /home/abbyck/.config/easyeffects/autoload/output
(easyeffects:24836): easyeffects-DEBUG: 01:23:46.679: 	easyeffects.cpp:60	Exitting the main function with status: 1
```
</details>

### Additional Information

pw-dump: https://www.toptal.com/developers/hastebin/erorepupab.csharp

### Pavucontrol tabs
![image](https://user-images.githubusercontent.com/19362717/176962421-4ddb49df-e19a-43e2-9e15-eb6715403f60.png)
![image](https://user-images.githubusercontent.com/19362717/176962470-c15f33eb-3821-4862-9596-78af92b39044.png)
![image](https://user-images.githubusercontent.com/19362717/176962491-008ab054-0678-44cc-a379-040c4000404b.png)
![image](https://user-images.githubusercontent.com/19362717/176962529-e40a6f0c-4f7d-4f3a-8154-b7fda3e45c1f.png)

**Comment by wwmm** [comment]
>I can not see any audio applications or sampling rate or any such info.

Do you have the package `pipewire-pulse` installed? It may seem weird but there is vital information PipeWire only provides when this package is installed.

>logs also didn't say much. Could someone please point out to me what am I missing

Did you kill the active instance `easyeffects -q` before trying to get logs? They seem too short indeed.

**Comment by abbyck** [comment]
Hi, Thanks for the reply. 
Looks like `pipewire-pulse` with a restart solved the issue. Does this need to be in the Arch Linux installation section as an optional step?

**Comment by wwmm** [comment]
>Does this need to be in the Arch Linux installation section as an optional step?

As PipeWire is right now EasyEffects is useless if `pipewire-pulse` is not installed. For example PipeWire only provides the metadata object that is needed to get information about the system default devices when this package is installed.

**Comment by Digitalone1** [comment]
Indeed the Arch Linux package should add pipewire-pulse as a dependency which now is missing leading to this type of issues.

@wwmm I suggest to update the PKGBUILD on master branch as a reference replacing `pipewire` with `pipewire-pulse`. Requiring just pipewire-pulse will guarantee both packages.

**Comment by wwmm** [comment]
> I suggest to update the PKGBUILD on master branch as a reference replacing pipewire with pipewire-pulse. Requiring just pipewire-pulse will guarantee both packages.


Ok. I will do it. But as most people are using other pkgbuilds I am not sure it is going to help.

**Comment by Digitalone1** [comment]
The AUR git package will be updated somehow. For Arch upstream the only option is to open a bug ticket.
