### ISSUE TITLE
No sample rate, sample format and latency shown for G4 Music using pipewire sink

### ISSUE THREAD

**Issue by BlobCodes** [wwmm/easyeffects#1620]
### EasyEffects Version

6.2.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 36 Silverblue

### Describe the bug

The aforementioned information is not shown in easyeffects when using the experimental pipewire sink in G4 Music:
![Bildschirmfoto vom 2022-07-03 12-51-16](https://user-images.githubusercontent.com/14961554/177036270-a8bdd595-9112-4fa4-af94-e4757bf627d3.png)

### Expected Behavior

The information is shown in easyeffects.

**Comment by wwmm** [comment]
I installed it and I see the same thing. The reason why is that G4Music stream does not have the properties `node.latency` and `node.rate` set. You can see that if you run `pw-cli list-objects Node` and then `pw-cli info id_number` after identifying the id number of the G4Music stream. 

Considering that G4Music is using GStreamer and that the GStreamer plugins for PipeWire are not in a good shape this is probably a bug that has to be reported to the PipeWire developers. The plugins for GStreamer are developed by them too.

**Comment by wwmm** [comment]
As it does not seem this can be fixed on our side I will close this issue.
