### ISSUE TITLE
Autogain Output Gain (Output Gain meter absurdly displays ~100+ dB)

### ISSUE THREAD

**Issue by chadweiske** [wwmm/easyeffects#1621]
### EasyEffects Version

EasyEffects 6.2.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

After reboot
EasyEffects set to autostart
Using CARLA to patch Spotify player/Firefox into EasyEffects Sink

Autogain Output Gain reads at least 60 dB--and during some quieter songs over 140 dB for an Output Gain reading.

(If I unpatch EasyEffects and patch Spotify direct to final audio destination in Carla, Spotify's level is sufficient where adding 60-140 dB of gain is absurd)

### Expected Behavior

Spotify patched to EasyEffects (using CARLA) should attenuate to a target -23 dB (using the Geometric MSI over 15s--the Default settings for the Autogain Effect)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
I do not use Carla. So it would help to see some images showing what is going on. I use Spotify and Firefox regularly and I do not remember having ever seen values like these. Why use Carla to link the app to EasyEffects sink if it can do this on its own?

**Comment by chadweiske** [comment]
I believe Carla is a GUI to show the audio connections between softwares, drag-and-drop cables, etc. (also allows patching in VST/other audio plugins).

...even without Carla: 
Starting up EasyEffects (no effects/plugins loaded) the audio drops immediately and considerably. 
It's effectively inaudible until I add Autogain--which on default load is adding over 20 dB.
Momentary, Short-Term, and Integrated all are reading ~ -50 dB. 
Toggle master bypass for EasyEffects the audio is effectively inaudible. 
Closing EasyEffects, the audio stream returns to normal listening volume (I don't have a rough/objective read on levels in this scenario).

The behavior seems as if EasyEffects (bypassed or not) has some 48 dB pad activated..

**Comment by wwmm** [comment]
>Starting up EasyEffects (no effects/plugins loaded) the audio drops immediately and considerably.

If this is happening even without effects loaded then something changed the volume of our virtual sink. I can't think of anything else that could be changing the volume even if bypass is activated. Unfortunately any third party tool can mess with our virtual sink volume.

**Comment by chadweiske** [comment]
Oh wow, that sounds like that might be it. Do you know of any tools that can access that?

**Comment by wwmm** [comment]
>Do you know of any tools that can access that?

I don't remember the name but in the past some users volume/device manager applets that had some questionable behavior. But there are other things that could make our sink volume to be unintentionally changed. If you set them as default devices, what is not recommended, and you change volumes with multimedia keys you will change our sinks volume. Once your hardware is set as default again you may already have a lower volume configured in our devices.

**Comment by chadweiske** [comment]
Discovered the solution. 

Running 'pavucontrol' in terminal shows the EasyEffects Sink under Output Devices..

It looks like the volume was knocked down pretty low.

**Comment by wwmm** [comment]
>It looks like the volume was knocked down pretty low.

This has happened to some users in the past. There was a time where I even disabled our virtual devices volume control. But people asked to allow it to be controlled. The side effect is this one you have seen. It is one of those situations where it does not matter what is done someone is not going to be happy.

**Comment by wwmm** [comment]
I think we can close this.
