### ISSUE TITLE
Improve Gate layout

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1633]
![image](https://user-images.githubusercontent.com/25790525/177534372-beee98ed-9014-4d79-ae22-b91bcd67530e.png)

@wwmm @LebedevRI What do you think? 

Curve and Hysteresis spinbuttons grouped with `linked` Adw style. The labels above enclosed in an homogeneous box. I like it more.

If it's good for you, I'll make the MR.

**Comment by wwmm** [comment]
It seems good to me. But are you sure that the linked style class is doing something? If I remember well it does nothin when the GtkBox has a space between children set.

**Comment by Digitalone1** [comment]
Not 100% sure, there's no spacing set inside the box. Maybe you can take a look during the review.

**Comment by LebedevRI** [comment]
* i like more closely located the threshold and zone spinbuttons, that is already what is being done in master, just not as aggressively
* i think, grouping the spinbuttons+label might be good
* i don't like checkbox. i did originally use it but then intentionally switched away to the button
* i don't see why the new label location is better?

**Comment by Digitalone1** [comment]
What I don't like in the master layout is the different height of the spinbuttons. At least we use the same height in UI with vertical spinbuttons 

The button for Hysteresis could be good, but I like more the checkbutton because it's more aligned with the curve label.

It seems obvious to me where Curve/Hysteresis applies. So you like only the linked spinbuttons?

**Comment by Digitalone1** [comment]
This should be better. Previously I forgot the margins around the spinbuttons.

![image](https://user-images.githubusercontent.com/25790525/177570427-cec67f5a-ef3e-496c-9daa-0ffbe665f65a.png)

Anyway I still don't like the different height of spinbuttons. Having them aligned on the last row is better in my opinion.

**Comment by wwmm** [comment]
This week I had tons of things to do at my work. Only now I could stop to look at this.

I am ok with both solutions. When the buttons have the same height it is still possible to see that there are different sections. But it is definitely easier to notice them with different buttons size. On the other hand different button sizes have the problem that the GtkEntry the spinbutton uses to show/edit the number is now unnecessarily large in the vertical. What is a little ugly and super easy to notice.

Maybe if we put the buttons and the labes of the curve and hysteresis sections inside a box the `card` css class we can have both things without the need to change the button size.

**Comment by wwmm** [comment]
Or maybe just creating two more pairs of button linked by the `linked` css class. Attack and Release are usually something we think at the same time. So they could be together. And for consistency the same could be done for the `Reduction` and `Makeup` buttons. This way it would be easy to see that there are `4 different blocks` without having to force different button heights.

**Comment by wwmm** [comment]
This is how it looks like if we group the other buttons
![Screenshot from 2022-07-09 12-45-17](https://user-images.githubusercontent.com/16225172/178112851-68c49f76-f232-46da-a4cd-05cb0c818b00.png)
It seems enough to me make it easier to see that curve and hysteresis are a block. And we also have the benefit that the gate window feels more compact in the horizontal direction. What do you think?

**Comment by Digitalone1** [comment]
It's okay to me. In the future we can also make dry and wet spinbuttons with link class.
