### ISSUE TITLE
How to install on Ubuntu?

### ISSUE THREAD

**Issue by o771e** [wwmm/easyeffects#1634]
Can't see any installation guide for Ubuntu. Is there any?

**Comment by wwmm** [comment]
There isn't a guide. But after a long time and some work done by @hosiet there are packages for Debian https://github.com/wwmm/easyeffects/issues/1000#issuecomment-1165561392. If they are going to work in the Ubuntu version you are using I don't know. If not you can try the Flatpak package.

**Comment by swfsql** [comment]
It appears that the package will exist in the kinetic suite (2022-10-22).  
https://packages.ubuntu.com/kinetic/easyeffects
