### ISSUE TITLE
Does not launch after I edit pipewire-pulse.conf

### ISSUE THREAD

**Issue by MaggI002** [wwmm/easyeffects#1635]
Distribution and Desktop Environment:
    Garuda Linux, Kwin-x11

How you installed EasyEffects:
    Pacman

Messages printed by EasyEffects when executed from command line in debug mode:
[output.txt](https://github.com/wwmm/easyeffects/files/9056122/output.txt)

Screenshots of Pavucontrol tabs:
![image](https://user-images.githubusercontent.com/85078603/177583023-86edfddb-c2e1-4bb8-afe5-f9811e7b3133.png)
![image](https://user-images.githubusercontent.com/85078603/177583117-556d4521-7029-43ae-b5be-8e47e0924a66.png)
![image](https://user-images.githubusercontent.com/85078603/177583177-b18eeccb-3eab-43de-945c-9df851836d17.png)
![image](https://user-images.githubusercontent.com/85078603/177583300-630daa4d-e44d-471a-9c68-265b9931805c.png)
![image](https://user-images.githubusercontent.com/85078603/177583346-76ee4224-327a-40e9-9f6a-3a03739088ec.png)

This happens only when I add 
context.exec = [
    { path = "pactl"  args = "module-switch-on-connect" }
    { path = "pactl"  args = "load-module module-loopback source="easyeffects_sink" sink="alsa_output.pci-0000_06_00.1.hdmi-stereo" }
]

(I did not mark it as code, because it was not obvious which line is the third one)

to ~/.config/pipewire/pipewire-pulse.conf
If I make the third line a comment and reboot I can launch EasyEffects again.
The whole purpose of me doing this is because I have to use helvum (pavucontrol or qpwgraph) to connect monitor of EasyEffects Sink to GA102 High Definition Audio... every time I reboot. I also wanted to make multiple sinks and connect each of them to one client automatically, so I that can record multiple tracks in OBS, even though I can connect them manually (also with helvum, pavucontrol or qpwgraph).
I also found that connecting them using the command
`pactl load-module module-loopback source="easyeffects_sink" sink="alsa_output.pci-0000_06_00.1.hdmi-stereo"`
does work and does not make EasyEffects unable to launch.

Thanks

**Comment by wwmm** [comment]
>Messages printed by EasyEffects when executed from command line in debug mode:

Did you kill any possible EasyEffects instance `easyeffects -q` before trying to get the logs? They seem too short.

>I also found that connecting them using the command ... does work and does not make EasyEffects unable to launch.

I never tried to load things through the PipeWire configuration files. So I am not sure about what it is doing. But if it works when the loopback is created in the command line but it doesn't when editing the configuration files we have to find out what PipeWire does different in this case.

**Comment by MaggI002** [comment]
I noticed that what I put in as output from EasyEffects is actually the output of `pw-dump`. This is what was supposed to be there (I did not run it again, I saved it to a file so this is the original output): 
<details>
<summary> Output </summary>

```
(process:11242): easyeffects-DEBUG: 16:57:55.731:       easyeffects.cpp:35      easyeffects version: 6.2.6
(process:11242): easyeffects-DEBUG: 16:57:55.732:       easyeffects.cpp:45      locale directory: /usr/share/locale
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:72  system input presets directory: "/etc/easyeffects/input";
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:72  system input presets directory: "/etc/xdg/easyeffects/input";
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:72  system input presets directory: "/home/davko/.config/kdedefaults/easyeffects/input";
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:75  system output presets directory: "/etc/easyeffects/output";
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:75  system output presets directory: "/etc/xdg/easyeffects/output";
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:75  system output presets directory: "/home/davko/.config/kdedefaults/easyeffects/output";
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:215 user presets directory already exists: /home/davko/.config/easyeffects/
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.737:   presets_manager.cpp:215 user presets directory already exists: /home/davko/.config/easyeffects/input
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.738:   presets_manager.cpp:215 user presets directory already exists: /home/davko/.config/easyeffects/output
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.738:   presets_manager.cpp:215 user presets directory already exists: /home/davko/.config/easyeffects/autoload/input
(easyeffects:11242): easyeffects-DEBUG: 16:57:55.738:   presets_manager.cpp:215 user presets directory already exists: /home/davko/.config/easyeffects/autoload/output
Failed to register: Timeout was reached
(easyeffects:11242): easyeffects-DEBUG: 16:58:20.767:   easyeffects.cpp:60      Exitting the main function with status: 1
```

</details>
I tried running `easyeffects -q` and `easyeffects` (in this order) today, their output was the same as the output above.
Also after restarting pipewire I found that my microphone was connected to my output (via loopback).
![image](https://user-images.githubusercontent.com/85078603/177746462-61375f04-b503-402a-97e8-5f67539e0adc.png)
I am going to try rebooting without commenting out the third line (even though I think I already tried that), rebooting with only the second line commented out etc. If anything of interest happens, I will comment about it.

**Comment by MaggI002** [comment]
After rebooting without anything commented out, EasyEffects was running just fine, except the loopback was from monitor of EasyEffects Source to playback of EasyEffects Sink for some reason. Also the monitor of my output (PHL 245E1) was connected to probe of echo canceller, after disconnecting it, I could hear myself (which makes sense). Here is the screenshot from Helvum:
![image](https://user-images.githubusercontent.com/85078603/177751086-2f24fd2f-3e7f-4021-887a-25da5fc02d57.png)
What I find even stranger is that now EasyEffects Sink was connected to my output, since it was not for like the past week. I will try to modify the command in the PipeWire config file and rebooting. Again, if I come across anything of interest, I will comment about it.

**Comment by MaggI002** [comment]
Since there does not seem to be a problem with EasyEffects, I am closing this issue. If anybody wants some resources because they want to do the same thing with OBS, I will include some references.
https://www.reddit.com/r/archlinux/comments/nwicio/virtual_sink_in_pipewire/
https://wiki.archlinux.org/title/PipeWire
https://docs.pipewire.org/index.html

For PulseAudio, not PipeWire: 
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/
