### ISSUE TITLE
Tag release issue

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1658]
I just checked the new release on upstream Arch and despite all the effort to have the translations updated, the latest ones are still missing. I tried to compile on my system and they're applied.

Initially I thought it was a Github issue, but I think the problem is that the tag has been set on the `updated changelog` commit which is not enough. It should have been set on `merge pull request from weblate`.

Anyway, let's go ahead for this time. Fortunately it's only the translations which is not a real issue. But next time we have to care about this because if we have a big fix just before the release, setting the tag on the commit which is not the `merge commit` could lead to a useless release without the fix.

**Comment by vchernin** [comment]
I wonder if it’s possible to get the update release notes script to somehow trigger a weblate PR/refresh through their API, and then the script can remind the user to merge it and tag that. 

I have also seen some projects have a release checklist, [e.g. this](https://github.com/flatpak/xdg-desktop-portal/blob/main/RELEASE_HOWTO.md), but automating is always nicer if it’s not too difficult to implement.

**Comment by Digitalone1** [comment]
Since there's #1726, this can be closed.
