### ISSUE TITLE
RNNoise: Standard Model not recognized in translated versions

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1659]
Unfortunately I only noticed this now.

![Schermata del 2022-07-19 08-39-04](https://user-images.githubusercontent.com/25790525/179687463-4d65c3e7-510c-41ef-8e24-0fa4cc8702dd.png)

The `Standard Model` in translated versions has the delete button, even if it can't be removed from the list. Because of this, trying to apply it will warn the user that the model is not loaded (no dialogs or toasts, just the label with the error style).

Internally everything works as expected because the Standard Model is still applied (because it tries to load a non-existent model and falls back to standard one), but from UI perspective is a wrong behavior.

This should be caused by the translatable label. Any idea on how to recognize the Standard Model not depending on the translation?

**Comment by Digitalone1** [comment]
Even if we have 

```c++
static const std::string default_model_name = _("Standard Model");
```

the `default_model_name` is `Standard Model`. The translation is not working even if it's present in the po file.

**Comment by Digitalone1** [comment]
It's fixed if I construct the translated string locally.

![Schermata del 2022-07-19 12-18-04](https://user-images.githubusercontent.com/25790525/179727936-0144c49c-450e-4666-b005-314671a65695.png)

@wwmm Do you have an idea why this is happening? Maybe the translated strings are not ready when constructed globally?

Are there other global translated strings in other files?

**Comment by wwmm** [comment]
>Are there other global translated strings in other files?

As far as I could see this was the only one.
