### ISSUE TITLE
Add Dry/Wet for plugins which already have those knobs

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1671]
We discussed about this in other topics.

![Schermata del 2022-07-22 20-10-12](https://user-images.githubusercontent.com/25790525/180500217-0be873c9-aa0f-4bdf-a4ff-63477ab4644e.png)

Differently by #1589 which misses them and it could have a solution made by us, other plugins (I think all of LSP, not Calf) already ship dry/wet and we could just expose them in our UI.

Anyway I see an issue in the way we will use to implement them. LSP uses -infinite dB for dry in the default state which means no input unprocessed signal is used. This could also be set for wet output processed signal. But we can't replicate these states because we use finite dB values for our settings.

We already had this kind of issue in the past with release threshold in the Compressor which is -inf as default in LSP. We couldn't make it and I set -120 db as default, while the lowest finite value in LSP UI is -79,9 dB (anyway from Ardour/Carla settings I think a more precise linear value could be set manually).

LSP uses a workaround to pass from -79,9 to -inf dB, but we can't do that. This means if we introduce those controls we will always have dry and wet mixed together, even if one of them is imperceptible. I think this is not the best solution, so we should find a better implementation.

Maybe we could try with percentages rather than dB levels? @wwmm Any idea?

**Comment by Digitalone1** [comment]
Actually we already have those controls for Reverb, which I think is one of the few Calf plugins to have them.

```
	Port 11:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      amount
		Name:        Wet Amount
		Minimum:     0.000000
		Maximum:     2.000000
		Default:     0.250000

	Port 12:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      dry
		Name:        Dry Amount
		Minimum:     0.000000
		Maximum:     2.000000
		Default:     1.000000

```

Both can have -inf but the minimum we have is -100 db

**Comment by wwmm** [comment]
>Maybe we could try with percentages rather than dB levels? @wwmm Any idea?

My initial though was just using a linear scale between `0.0` and `1.0` and moving on with our lives. In theory it may be possible to do some clever mapping in the spinbutton label formatting callback to show the `-Inf`. But I do not think it is worth the effort. In my opinion linear values with a step of `0.01` should be more than enough.

**Comment by wwmm** [comment]
>In my opinion linear values with a step of 0.01 should be more than enough.

Or a linear percentage scale from `0.00 %` to `100.00 %`

**Comment by Digitalone1** [comment]
I will try to implement in the reverb since the controls are already there.

**Comment by Digitalone1** [comment]
@wwmm so I managed to write a new solution which intends to replicate the behavior of dry and wet knobs in calf and lsp native UI.

So far it's compiling correctly, but unfortunately it's too late and I can't test now. So I pushed it to my new [branch](https://github.com/Digitalone1/easyeffects/tree/drywet2).

Please take a look at it. If there are any hints, please report here. I will test tomorrow if I have time.

**Comment by wwmm** [comment]
>Please take a look at it. If there are any hints, please report here. I will test tomorrow if I have time.

Looking at the code it seems to do what we want. Something else we will have to think about is if we allow translations for `-inf` or not. Depending on how different the word `infinity` is written on some languages it may be weird not allowing translations to it. But in this case we would have to handle `s.starts_with("-inf")` in the same way that plugins names comparisons had to be handled in some places because of the translations. I am not sure it is worth the headache...

**Comment by Digitalone1** [comment]
Otherwise we could use the ∞ symbol.

**Comment by wwmm** [comment]
>Otherwise we could use the ∞ symbol.

It is something to consider. But based on some experience I had with the use of font icons in PulseEffects this can be a little tricky. There was a case where I used an unicode `arrow` and when I saw one of the users screenshots in one of our old issues I've noticed that his system fonts did not have the arrow. The same thing can happen to the infinity symbol.

**Comment by Digitalone1** [comment]
Okay but that is a user issue, not related to PulseEffects. Fonts are not like icons. 

Anyway I forgot to say that gsettings lacks a clear way to get the min and max values from a key. 

I did not want to pass the limit argument to the argument, but playing with "gsettings schema get range" is tricky because it returns a GVariant as `sv`, which I suppose it's a vector of strings that I should convert to double. 

Well at the end it's more straightforward if we just define a double lower bound and use it once and for all, just like we did for minimum db values in utils.

**Comment by wwmm** [comment]
So far everything is fine here. I am just a little confused about the meaning of `lower_bound` in the code. Is it there so we can avoid `-Inf` being used in controls that do not use `zero` as linear values?

>I did not want to pass the limit argument to the argument, but playing with "gsettings schema get range" is tricky because it returns a GVariant as sv, which I suppose it's a vector of strings that I should convert to double.

Yes. I tried to use it in the past and it was a little annoying. I will take a look at it again.

**Comment by wwmm** [comment]
@Digitalone1 I decided to take a look at how `GLib` developers get the range https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gsettings-tool.c#L348. BAsed on their code I have written a function that returns a pair of strings with `[minimum, maximum]`. The following code
```
auto [min, max] = util::gsettings_get_range(settings, "dry");

util::warning(min);
util::warning(max);
```
prints
```
easyeffects-WARNING **: 21:17:49.061: 	reverb.cpp:55	-100.0

easyeffects-WARNING **: 21:17:49.061: 	reverb.cpp:56	6.0
```
As we are getting strings as output there is the annoyance of having to check if we actually have a valid number there... But it should help to make use of the ranges we have defined in the schemas.

**Comment by Digitalone1** [comment]
> So far everything is fine here. I am just a little confused about the meaning of `lower_bound` in the code. Is it there so we can avoid `-Inf` being used in controls that do not use `zero` as linear values?

Yes.

In other words, `lower_bound` is true by default and the control works as it always did in the past.

If it's false, the minimum value is converted to 0, acting as - infinity dB.

Maybe a better name could be found, you can replace it.

**Comment by Digitalone1** [comment]
> @Digitalone1 I decided to take a look at how `GLib` developers get the range https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gsettings-tool.c#L348. Based on their code I have written a function that returns a pair of strings with `[minimum, maximum]`. The following code
> 
> ```
> auto [min, max] = util::gsettings_get_range(settings, "dry");
> 
> util::warning(min);
> util::warning(max);
> ```
> 
> prints
> 
> ```
> easyeffects-WARNING **: 21:17:49.061: 	reverb.cpp:55	-100.0
> 
> easyeffects-WARNING **: 21:17:49.061: 	reverb.cpp:56	6.0
> ```
> 
> when `dry` is the key in the `reverb` schema. As we are getting strings as output there is the annoyance of having to check if we actually have a valid number there... But it should help to make use of the ranges we have defined in the schemas.

That's nice but isn't it better if we just assume -100 dB is the lowest finite number and check it?

**Comment by Digitalone1** [comment]
That's also another thing I don't like about getting the range from that function.

https://docs.gtk.org/gio/method.SettingsSchemaKey.get_range.html

> This information should not be used by normal programs. It is considered to be a hint for introspection purposes. Normal programs should already know what is permitted by their own schema. The format may change in any way in the future — but particularly, new forms may be added to the possibilities described above.

**Comment by wwmm** [comment]
>Maybe a better name could be found, you can replace it.

If a better name comes to my mind I will replace it.

>That's nice but isn't it better if we just assume -100 dB is the lowest finite number and check it?

Assuming we do not forget about the `-100 dB` in the future while setting the range of new plugins or old ones it is. 

>That's also another thing I don't like about getting the range from that function.

Oh... I forgot about that. Considering the current pace of Glib development it doesn't seem likely that they are actually going to change this. But I agree it is better to avoid it. In any case I will keep the helper function in utils.cpp. It may be useful in the future.

**Comment by wwmm** [comment]
But it is funny that the `gsettings` command they provide to the system when installing glib is implemented using an API they tell to not be used :smile:
