### ISSUE TITLE
Implement LSP Multiband Gate

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1672]
Since we have the LSP Gate, it makes much more sense replacing the Calf MB Gate with the LSP one.

@LebedevRI do you have plans to import it?

I might suggest to replicate the MB Comp layout having Sidechain controls inside an expander widget rather than the switcher.

**Comment by LebedevRI** [comment]
It you want to take a stab, please feel free to.
I think, having UI consistency would be nice, so i'd personally go the same route as with the compressor->gate,
by copying the LSP-driven MB compressor and tuning it...
