### ISSUE TITLE
Effects not beein added

### ISSUE THREAD

**Issue by koemam13** [wwmm/easyeffects#1693]
### EasyEffects Version

6.2.8

### What package are you using?

AUR (easyeffects-git)

### Distribution

Garuda Linux (Arch based)

### Describe the bug

Started easyeffects, went to the effects tab tried to add the Bass enhancement. But it didnt change the sound accordingly

### Expected Behavior

Expected some more bass.

### Debug Log

[easyeffects.txt](https://github.com/wwmm/easyeffects/files/9198816/easyeffects.txt)

### Additional Information

pw dump:
[dump.txt](https://github.com/wwmm/easyeffects/files/9198820/dump.txt)

**Comment by wwmm** [comment]
>bass_enhancer.cpp:29	soe: http://calf.sourceforge.net/plugins/BassEnhancer is not installed

Check if you have the package with `Calf Studio Plugins` installed. At least here on Arch Linux the package is named `calf`.

**Comment by koemam13** [comment]
Thank you. This was the issue. I feel kinda dumb that i've overlooked that debug message. :D
