### ISSUE TITLE
Missing parameters into Equalizer and Loudness

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1698]
![image](https://user-images.githubusercontent.com/25790525/181625024-1b64b8bc-2f5d-4931-a134-3ee514827bfe.png)

Should we add Balance and Pitch L/R?

**Comment by Digitalone1** [comment]
Also for Loudness Compensator:

```
	Port 10:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      hclip
		Name:        Hard-clipping enable
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/lv2core#toggled


	Port 11:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      hcrange
		Name:        Hard-clipping range
		Minimum:     0.000000
		Maximum:     24.000000
		Default:     6.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds
```

**Comment by wwmm** [comment]
I think it makes sense to add them. The balance control isn't really needed because the stereo tools plugins provides one. But on the other hand putting one more plugin in the pipeline just to do balance when the user is using only the equalizer sounds like an overkill.

**Comment by Digitalone1** [comment]
Any idea where to place those balance and pitch spinbuttons?

Having them in the same layout as mode/band parameters does not seem a good idea to me because the will enlarge the already existing buttons (especially with some translations).

I was thinking of doing a layout of the label on top of the spinbutton rather than having both on the same line. But don't know if this is appreciated.

Another option could be having only buttons at the right and organize spinbuttons (horizontal) and relative labels below the band sliders box.

I'm open to suggestions.

**Comment by wwmm** [comment]
>I was thinking of doing a layout of the label on top of the spinbutton rather than having both on the same line. But don't know if this is appreciated.

It is the kind of thing we would have to see how it looks. At this moment I have the feeling it may become a little confusing alternating labels and spinbuttons in the vertical.

Something else to consider is doing something similar to the one done in the autogain. But in this case we lose some vertical space.

**Comment by Digitalone1** [comment]
I think I'll go with leaving all the buttons in the right side and placing the spinbuttons at the top

**Comment by Digitalone1** [comment]
![image](https://user-images.githubusercontent.com/25790525/182679635-d392b6f4-75f1-4abc-bb09-2b993e13c7da.png)

@wwmm what do you think?

I'll make the MR. I could change it for some refinements if needed.

**Comment by wwmm** [comment]
>what do you think?

It is fine. I actually had the same idea after some time.

**Comment by Digitalone1** [comment]
Wait, I still have to add the hard clipping to the Loudness.

Do you know which is the meaning of this parameter? I looked at the Loudness native UI and the hard clipping button is there, but It seems there's no control to set the range?

**Comment by wwmm** [comment]
>Do you know which is the meaning of this parameter? I looked at the Loudness native UI and the hard clipping button is there, but It seems there's no control to set the range?

If I remember well `hard clipping` in this context means that the filter will force the signal to stay under a maximum value not matter the cost. And usually the cost is having distortion. As there is no way to set where the "hard brick wall" is I imagine the filter is using `0 dB` as reference.

**Comment by wwmm** [comment]
In a limiter clever algorithms are applied to somehow reduce the signal amplitude so that it does not go over the threshold. Usually when people tell that `hard clipping` is going to be done what is going to happen is that instead of trying a clever way to reduce the amplitude the filter will just throw away the part of the signal that is above the threshold. As expected this causes a lot of distortion because you are literally cutting away part of the signal.

As the loudness plugin amplifies/reduces the signal based on loudness curves depending on the level the signal can go over 0 dB easily. I would personally control the input level to avoid this. But maybe musicians and audio engineers actually want the distortion in some cases.

**Comment by Digitalone1** [comment]
Nice, I'll see if I can add this part to the manual.

**Comment by wwmm** [comment]
The `Stereo Tools` plugins has a similar control named `Softclip`. This one is little more subtle. Distortion is done through a smooth curve https://www.hackaudio.com/digital-signal-processing/distortion-effects/soft-clipping/.

I think only very advanced users would know what to do with the kind of distortion that is done through soft and hard clipping. 99% of people should just be reducing the input levels to avoid clipping.
