### ISSUE TITLE
Wayland tooltip freeze

### ISSUE THREAD

**Issue by gybfefe** [wwmm/easyeffects#1709]
Sudden move with mouse to let pop up a tooltip on the window yields immediate freeze occasionally on sway garuda wayfire

**Comment by wwmm** [comment]
One or tow weeks ago I started seeing this here on `Arch Linux + GNOME + Wayland`. I did not try to do tests on Xorg yet but I suspect we are seeing a new GTK4 bug... I do not see what we could be doing that would make only the tooltip freeze. This is the kind of thing GTK handles on its own.

**Comment by wwmm** [comment]
@gybfefe what EasyEffects version are you using? I am trying to reproduce this bug now but for some reason so far I could not. Maybe one of the fixes in the last releases had some effects in this tooltip bug.

**Comment by wwmm** [comment]
@Digitalone1 gtk4 definitely has problems with the tooltips https://gitlab.gnome.org/GNOME/gtk/-/issues/4941. I think that it should be fixed in gtk `4.7.1`. But it is not in the Arch Linux repository yet.

**Comment by gybfefe** [comment]
Thank you for the enlightenment ,it's version 6.2.8

**Comment by wwmm** [comment]
>Thank you for the enlightenment ,it's version 6.2.8

Ok. Unfortunately this bug will hit everybody. I was able to reproduce it again in my computer. The only thing we can do is waiting for a gtk release that has the fix for the bug.

**Comment by wwmm** [comment]
We can close this issue. As far as I can see this was fixed by the gtk developers.
