### ISSUE TITLE
Global latency not updated at startup

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1721]
I saw this another time while testing. I though we fixed it in the past.

My latency is always 5 ms because of the Limiter, but at the startup 0 is reported. It's properly updated only if I change something in the plugins or in the stack order.

@wwmm could you reproduce?

**Comment by wwmm** [comment]
>I though we fixed it in the past.

Me too. I will pay attention to this. I added to each plugin a method `get_latency_seconds` so we could get the latency whenever it is needed. Even if the plugin did not set the latency before `get_latency_seconds` is called as we emit a signal ass soon as the latency is set we should have its value.

Maybe the LSP plugin is not actually setting the latency value unless certain conditions are met.

**Comment by wwmm** [comment]
I am changing the `lookahead` parameter of some LSP plugins and I do not see the latency changing anymore. Only if I remove and add again the plugin. Strange. I will have to give a closer look but it does not seem the plugin is updating the `out_latency` port value.

**Comment by wwmm** [comment]
> it does not seem the plugin is updating the out_latency port value.

That is not it. I can see in the logs the new latency value being printed. It is almost like the signal is not being emitted or no slot was connected.

**Comment by wwmm** [comment]
For some reason this line https://github.com/wwmm/easyeffects/blob/bc0366b05cd8d9437cd6b73939b3795504be81e9/src/effects_base.cpp#L187 does not seem to be working. Strange...

**Comment by Digitalone1** [comment]
I don't remember how it work, but seeing that line I wonder why we have a signal sending a float that we do not use.

**Comment by Digitalone1** [comment]
Besides in plugin_base we have `sigc::signal<void(const float)> latency;`, but we connect a reference argument.

In the past, if I remember well, we said non reference shouldn't connect to reference, am I right?

**Comment by wwmm** [comment]
I have just found out something totally unexpected. This works
```
      auto limiter = std::make_shared<Limiter>(log_tag, tags::schema::limiter::id,
                                               schema_base_path + tags::plugin_name::limiter + "/", pm);

      connections.push_back(limiter->latency.connect([=, this](const auto& v) { broadcast_pipeline_latency(); }));

      filter = limiter;
```
It seems that after the type casting to the base class the signal connection silently fails.

**Comment by wwmm** [comment]
I've found the real source fo the problem. The header `plugins_base.hpp` defines `sigc::signal<void(const float)> latency;`. But `limiter.hpp` also defines it and as a result the signal from the derived class is overriding the one from the base class. That is why the connection seems not to be working. It does. The wrong signals is being connected.

 I will check all the plugins headers and remove any `sigc::signal<void(const float)> latency;` definition that may be there.

**Comment by wwmm** [comment]
I will also remove the useless float argument in the process.

**Comment by wwmm** [comment]
As far as I can see this problem is fixed.

**Comment by Digitalone1** [comment]
> As far as I can see this problem is fixed.

Sure.
