### ISSUE TITLE
Updating translation template files after pushes to master?

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1726]
Since we have more automation I thought of adding another bot to make PRs if there are pot/po files that could be updated. The main caveat of course is to merge any existing weblate translation PRs before updating the template files.

Is there any good reason not to do this? I assume we probably always want the files updated with the latest merged strings.

For implementation, weblate has [an add on to automatically update the po files](https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-gettext-msgmerge) but not the pot file itself. Instead we could just run the meson commands and check for a diff.

**Comment by wwmm** [comment]
>The main caveat of course is to merge any existing weblate translation PRs before updating the template files.

Not only the weblate PRs. If we update the template before merging PR from other people it is almost a guaranteed conflict. I have seen a few in the past.

>Is there any good reason not to do this?

Not really. The only annoyance is the possibility of having to handle conflicts with pull requests or merging in general.
