### ISSUE TITLE
Tooltip crash

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1729]
I discovered another bug. Maybe GTK related.

If a tooltip is shown and you are able to go on it with the cursor, the whole window freezes. Easily reproducible on plugin bypass tooltip.

The only option is to force the process shutdown.

At least on Wayland. Can someone reproduce?

**Comment by wwmm** [comment]
Yes. Take a look at #1709. I thought I could not reproduce it anymore but it is still there. Running a binary compiled with sanatiser support somehow makes this bug a lot more easier to reproduce. And having the spectrum enabled seems to increase the probability of it happening too. I am still not sure if it is something we are doing or a gtk bug.

**Comment by Digitalone1** [comment]
Oh, I totally miss that ticket. You can close this.

Anyway, as a temporary workaround, we could comment the tooltips in the builders to not show them.

**Comment by wwmm** [comment]
>Anyway, as a temporary workaround, we could comment the tooltips in the builders to not show them.

The downside is that in some cases like the `save preset` button the purpose of the button may not be immediately clear for new users without the tooltip.

I will try to debug this freezing again. The fact I can only reproduce this bug when our pipeline is active is suspicious.
