### ISSUE TITLE
Migrate from deprecated tbb task.h

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1746]
The include of `<execution>` from tbb always causes this when compiling. The build will probably break when tbb decides to remove `task.h`.

```
[36/72] Compiling C++ object src/easyeffects.p/effects_box.cpp.o
In file included from /usr/include/c++/12/pstl/parallel_backend_tbb.h:26,
                 from /usr/include/c++/12/pstl/parallel_backend.h:20,
                 from /usr/include/c++/12/pstl/algorithm_impl.h:22,
                 from /usr/include/c++/12/pstl/glue_execution_defs.h:50,
                 from /usr/include/c++/12/execution:32,
                 from ../include/convolver_menu_combine.hpp:23,
                 from ../include/convolver_ui.hpp:30,
                 from ../include/plugins_box.hpp:27,
                 from ../include/effects_box.hpp:29,
                 from ../src/effects_box.cpp:20:
/usr/include/tbb/task.h:21:139: note: ‘#pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.’
   21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                                                                                           ^
```

There is some info here: https://github.com/oneapi-src/oneTBB/issues/243

How exactly does EE use tbb? Maybe there is a easy enough alternative to `task.h` in tbb.

**Comment by vchernin** [comment]
Actually upon further checking I don’t see this deprecation warning in the arch build in CI, but it is on fedora locally and in the flatpak build. The difference is arch has tbb 2021.x and our bundled flatpak and fedora still has tbb 2020.x. So maybe if I try update tbb in flatpak it will go away.

**Comment by wwmm** [comment]
>How exactly does EE use tbb?

We do not use tbb directly. The parallel version of some standard c++ libraries are the ones forcing tbb as dependency. There isn't a way for us to force the use of another header as far as I know.
