### ISSUE TITLE
Audio routing

### ISSUE THREAD

**Issue by v1gnesh** [wwmm/easyeffects#1773]
Hello,

Firstly, thank you for this excellent bit of work.
With this and Digitalone1's LoudnessEq plugin, audio-all-over-the-place woes are totally solved.

Have a question on using EasyEffects in a wider setting...

Say I plug the 3.5mm out from a Windows machine or a TV into another (Linux) PC's line in.
Can I use EasyEffects w/ the LoudnessEq plugin to process that audio, to get adjusted audio out of the Linux box?

3.5mm jack of Windows workstation / HDMI out of TV -->
Line In or Mic (which should I use?) of Linux workstation running EasyEffects -->
Line Out from Linux PC to speakers.

Want to do something about the extremely jumpy audio levels from devices that aren't Linux.
Devices on which I may not be able to install software; can just get audio out of 3.5mm or HDMI.

Thanks in advance!

**Comment by wwmm** [comment]
>Can I use EasyEffects w/ the LoudnessEq plugin to process that audio, to get adjusted audio out of the Linux box?

You can if you configure a loopback device https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#loopback. It is possible to create them through PipeWire's configuration files too like you can see here https://github.com/wwmm/easyeffects/issues/1126#issuecomment-1147748628. In your case you will want the loopback in a different position. You have to identify the sound card port with the audio that has to be processed and link it to the loopback input. The other part should be easier. The output of the loopback device has to be linked to our virtual sink `EasyEffects Sink`. Its `node.name` is `easyeffects_sink`.

I have never had the need to setup loopback devices so I can't really guide you on the configuration details. But I think it is possible to set in its configuration file where its input and output should be linked to. Then PipeWire will do the links on its own.

When people redirect audio from a smartphone to the PC through bluetooth the audio server usually automatically creates a loopback device. So what you want should be possible.

**Comment by wwmm** [comment]
>In your case you will want the loopback in a different position.

And differently from the multichannel case you do not want to blocklist its streams.

**Comment by v1gnesh** [comment]
Thank you very much, I'll read up & try it out.

In your wanderings of the internet, have you ever come across this as a product, i.e., a machine running Linux (+EasyEffects) serving as an audio 'corrector', before sending output to speakers.
I suppose there are audio processing units that do DSP for studio stuff and all, but I need a tiny unit just to run LoudnessEq everywhere.

**Comment by wwmm** [comment]
>In your wanderings of the internet, have you ever come across this as a product, i.e., a machine running Linux (+EasyEffects) serving as an audio 'corrector', before sending output to speakers.

I don't think I have ever seen something like this. There are probably dedicated DSP hardware out there for tasks like this. But solutions based on Linux and customizable are probably not easy to find if they even exist. 

One problem would be processing power. Even in a raspberry things can get hard if a CPU hungry plugin is used. I think that a long time ago someone was using PulseEffects and a raspberry in some kind of motorcycle sound system. But you won't be able to use as many plugins as you would in a good desktop CPU. But I think that the raspberry cpu should be capable of handling the loudnessEq plugin.

**Comment by wwmm** [comment]
I think this issue can be closed.
