### ISSUE TITLE
Suggestion: Add support for multiple EQ

### ISSUE THREAD

**Issue by Cpt-Dingus** [wwmm/easyeffects#1775]
In some use cases, having more than one EQ can come in very handy, but EE currently only supports having one at a time. Would it be possible to add support for more than one?

**Comment by wwmm** [comment]
It is in our plans https://github.com/wwmm/easyeffects/issues/1316. But although a lot has already been done in this direction there still some technical difficulties that have to be solved before multiple filter instances can actually be used.
