### ISSUE TITLE
irs files not recognized in 22.04 anymore

### ISSUE THREAD

**Issue by YannoteX** [wwmm/easyeffects#1776]
### EasyEffects Version

4.8.4-1

### What package are you using?

Other (specify below)

### Distribution

Ubuntu 22.04

### Describe the bug

I'm trying to get presets from irs files but I can't import or even make the software recognize them.

### Expected Behavior

I wanted initially to find presets from irs files in the preset section.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>4.8.4-1

That is a very old `PulseEffects` version. Although PulseEffects receives only fixes for critical bugs(development is on EasyEffects) there are newer versions than `4.8.4`. I strongly suggest you try to update to `4.8.7` if using PipeWire and EasyEffects is not an option for you. PulseEffects `4.8.4` is not going to work with recent versions of some system packages. This may be the reason why you are facing some problems.

**Comment by mamopa** [comment]
Is there a description how one could update from 4.8.4 to 4.8.7 (Ubuntu)

**Comment by wwmm** [comment]
>Is there a description how one could update from 4.8.4 to 4.8.7

Using the Pipewire package https://flathub.org/apps/details/com.github.wwmm.pulseeffects is probably the easiest way unless someone is proving a PPA for it.

**Comment by wwmm** [comment]
As a package upgrade is probably the solution I think this issue can be closed.
