### ISSUE TITLE
OBS - Desktop audio quality is very bad, and my head is exploding 'cuz I can't fix it (is this a Pipewire bug, EE bug, OBS bug? I don't know at all)

### ISSUE THREAD

**Issue by gabriele2000** [wwmm/easyeffects#1780]
### EasyEffects Version

6.2.8

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_Os 22.04

### Describe the bug

Well, let's say that I use 192000Hz samplerate system-wide, but that's not the source of the issue since I tried to freshly install pipewire and OBS; the issue didn't go away.
I noticed this <pre>info: ------------------------------------------------
info: pulse-input: Server name: &apos;PulseAudio (on PipeWire 0.3.56) 15.0.0&apos;
info: pulse-input: Audio format: float32le, 192000 Hz, 2 channels
info: pulse-input: Started recording from &apos;easyeffects_sink.monitor&apos;
info: [Loaded global audio device]: &apos;Desktop Audio&apos;
info: pulse-input: Server name: &apos;PulseAudio (on PipeWire 0.3.56) 15.0.0&apos;
info: pulse-input: Audio format: s32le, 192000 Hz, 2 channels
info: pulse-input: Started recording from &apos;alsa_input.pci-0000_00_1f.3.analog-stereo&apos;
info: [Loaded global audio device]: &apos;Mic/Aux&apos;
info: Switched to scene &apos;Scene&apos;
info: ------------------------------------------------
</pre> and it was not like that a second ago... the first audio format was at 44100Hz, but anyway, the problem is still present anyway.

I'll drop a [post on reddit](https://www.reddit.com/r/pop_os/comments/wwyfgm/obs_internal_audio_is_utter_cp_but_pipewire_has/)

### Expected Behavior

Clear and concise description huh?

As my ears activate themselves and prepare to listen to the fabolous recording that my precious PC and the famous-software "OBS" has produced, they shouldn't bleed after 2 seconds.
This is something that didn't happen a month ago, maybe even 3 weeks ago.

I record at 320Kb/s and I'm expected to hear 320Kb/s, not 192Kb/s (if I'm lucky)

OH, the microphone input is perfect, so I guess it's a sink issue?

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
I am confused about what is the problem. I watched the your video at reddit but just looking and listening to it I could not understand what it is you are trying to solve. The music in the background isn't sounding the way you expect it to be?

>I record at 320Kb/s and I'm expected to hear 320Kb/s, not 192Kb/s

Or is the problem that the recorded video is not at 320 Kb/s? EasyEffects process raw pcm audio. So whatever PipeWire is giving us is not going to have its amount of data per second changed.

**Comment by gabriele2000** [comment]
> I am confused about what is the problem. I watched the your video at reddit but just looking and listening to it I could not understand what it is you are trying to solve. The music in the background isn't sounding the way you expect it to be?
> 
> > I record at 320Kb/s and I'm expected to hear 320Kb/s, not 192Kb/s
> 
> Or is the problem that the recorded video is not at 320 Kb/s? EasyEffects process raw pcm audio. So whatever PipeWire is giving us is not going to have its amount of data per second changed.

I'll give you my headphones EasyEffects profile, you can hear every bit of my disappointment this way: I make use of EQ, compressor, limiter... the sound is very strange, not detailed: it's like when you compress too much a song, for example.
[profile.zip](https://github.com/wwmm/easyeffects/files/9436811/profile.zip)

**Comment by wwmm** [comment]
>the sound is very strange, not detailed: it's like when you compress too much a song, for example.

This kind of feeling will change from one hardware to another. But I see some strange choices in this profile. Are you sure you want the limiter in the middle of the pipeline? Usually it is used as the last plugin to protect the sound card from saturation. What is really easy to produce when using the compressor in upward mode like you are doing. It will depend on how high is the signal level at the beginning of the pipeline. Some of the bad sound you are listening to is probably coming from a saturated sound card.

**Comment by gabriele2000** [comment]
> > the sound is very strange, not detailed: it's like when you compress too much a song, for example.
> 
> This kind of feeling will change from one hardware to another. But I see some strange choices in this profile. Are you sure you want the limiter in the middle of the pipeline? Usually it is used as the last plugin to protect the sound card from saturation. What is really easy to produce when using the compressor in upward mode like you are doing. It will depend on how high is the signal level at the beginning of the pipeline. Some of the bad sound you are listening to is probably coming from a saturated sound card.

That bad sound simply isn't there, it's the output recording that has that strange sound, I hear things perfectly.
Anyway, thanks for the suggestion, I'll move the limiter at the end of the pipeline.

**Comment by wwmm** [comment]
>it's the output recording that has that strange sound, I hear things perfectly.
>As "sound compressed", I really refer to a low bitrate, when a file is compressed too much and too much details are lost.

If it is only the recorded audio that sounds weird something may be going on in PipeWire when all clients are active. It may have selected a `quantum size (latency)` in this scenario that is triggering some kind of bug or different behavior in OBS. Run `pw-top` while OBS is recording and EasyEffects is running. This command will show the requested latency by each client as well as the one actually being used by the hardware.

**Comment by gabriele2000** [comment]
> 

![Screenshot - 2022-08-27 - 23:29:06](https://user-images.githubusercontent.com/12186181/187048697-6a5fee74-8989-4ff0-b0ca-b31289f56405.jpg)

**Comment by wwmm** [comment]
There is nothing unusual in the latency value being used in your sound card `1024 / 48000 = 0.021 = 21 ms`. This is an everyday latency and shouldn't cause any side effects.

>I hear at 96000

How if your sound card is running at `48000 Hz`? The OBS stream is requesting 96 kHz but PipeWire is using 48 kHz to play to the sound card. OR did you talk about your input device? This one is at 96 kHz indeed.

**Comment by gabriele2000** [comment]
> How if your sound card is running at `48000 Hz`? The OBS stream is requesting 96 kHz but PipeWire is using 48 kHz to play to the sound card. OR did you talk about your input device? This one is at 96 kHz indeed.

I thought that if "default-clock-value" was set at 96000 everything would be upsampled at 96000Hz... you're telling me that was all placebo/useless?
If so, can I configure ALSA to run at 96000Hz?

Just to recap:
-ALSA apparently is running at 48000Hz
-Pipewire.conf = 96000Hz default clock value, I want this.
-OBS cannot record at more than 48000Hz but that was not a problem, since the audio issue is: everything sounds like it's at a too low bitrate.
-The microphone is perfect, the desktop audio is the issue, when OBS captures from the microphone he can pick the full range of sounds and it's just crystal clear.

I even tried to run everything at 48000Hz to no avail: the problem is still there.
At this point I don't know if it's OBS's fault, Pipewire's fault or EasyEffects fault, which I doubt because the issue persists if I try to capture "built-in analog stereo", which is the post-processed audio or "EasyEffects Sink" which "Simplescreenrecorder" captures just fine, with 0 problems at all.
It's OBS's fault based on exclusion, but I wonder why, because it never gave me that problem.

**Comment by wwmm** [comment]
>I thought that if "default-clock-value" was set at 96000 everything would be upsampled at 96000Hz... you're telling me that was all placebo/useless?

According to your pw-top output your soundcard is at 48 kHz. No doubt about it. 

>Pipewire.conf = 96000Hz default clock value, I want this.

Show here the contents of this file. Is it in the system folder or at `~/.config/pipewire/pipewire.conf`?

**Comment by gabriele2000** [comment]
> According to your pw-top output your soundcard is at 48 kHz. No doubt about it.

Is there a way to change it?
This MSI laptop's motherboard audio chip should be able to run at 192000Hz natively, it's even advertised on the website.

> Show here the contents of this file. Is it in the system folder or at `~/.config/pipewire/pipewire.conf`?
<pre><font color="#4E9A06"><b>gabriele@msi-gp72m</b></font>:<font color="#3465A4"><b>~</b></font>$ cat /etc/pipewire/pipewire.conf.d/pipewire.conf
context.properties =
{
	default.clock.rate = 96000
}
<font color="#4E9A06"><b>gabriele@msi-gp72m</b></font>:<font color="#3465A4"><b>~</b></font>$ 
</pre>

**Comment by wwmm** [comment]
This should have been enough to force the rate. I wonder if you also have to add it to the allowed sampling rate list `default.clock.allowed-rates`. As I want dynamic sampling rate switching I have edited only this line. I did not touch my default value.

**Comment by wwmm** [comment]
There is a way to set a temporary value at runtime https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#runtime-settings. Does this change the pw-top output?

**Comment by gabriele2000** [comment]
> This should have been enough to force the rate. I wonder if you also have to add it to the allowed sampling rate list `default.clock.allowed-rates`. As I want dynamic sampling rate switching I have edited only this line. I did not touch my default value.

At this point I suspect it's not a samplerate problem.
I tried to set the allowed samplerate to 44100 48000 96000 192000, it's not the problem, now I'm certain.
I even changed the samplerate of ALSA, now it's at 96000.

It's like a bitrate problem but this doesn't make any sense...
I'll do a little demonstration, be sure to use my profile, so you can hear the "problem" better.

**Comment by wwmm** [comment]
>The issue is subtle. It's clearly not a Sink issue or pipewire or something...

I agree. It is subtle but there is a difference. After putting the autogain plugin as the first filter in the pipeline I've noticed that the OBS stream average loudness is `1 dB` above the one recorded by `simplescreenrecorder`. I wonder if this inscrease in the average loudness is coming from some kind of dynamic range compression OBS can be doing under the hoods. I am not familiar with how the encoders work. Is there a chance the settings OBS is using to create the mp4 are reducing the dynamic range as a way to reduce file size? I ask this because the mp4 generated by OBS has roughly half the size. And there is no video there.

**Comment by gabriele2000** [comment]
>Is there a chance the settings OBS is using to create the mp4 are reducing the dynamic range as a way to reduce file size? I ask this because the mp4 generated by OBS has roughly half the size. And there is no video there.

Oh, sorry, I should've mention that I re-encoded every video with HandBrake with the h.265 codec, but the audio was unchanged since I told HandBrake to not change AAC and mp3.
Basically only the SimpleScreenRecorder audio was re-encoded, but I agree, the difference in the sound is there: the OBS output is slightly louder, I didn't notice this at first.

I don't think that the loudness is the key factor here, there would be some kind of crackling or something, but not that degradation in quality, from my little experience.
There's no filter set anyway, I can plug some audio filters but there is none, as I want the "clean" output to be processed, not the "post-processed output", as my preference of EQ will conflict with other's taste.

**Comment by wwmm** [comment]
>I don't think that the loudness is the key factor here, there would be some kind of crackling or something, but not that degradation in quality, from my little experience.

You would have a crackling if the device was being saturated. What is not the case. At least on my hardware that "degradation in quality" is sounding like a dynamic range compression. What depending on what is being desired can be considered a degradation in quality indeed.

**Comment by gabriele2000** [comment]
> > I don't think that the loudness is the key factor here, there would be some kind of crackling or something, but not that degradation in quality, from my little experience.
> 
> You would have a crackling if the device was being saturated. What is not the case. At least on my hardware that "degradation in quality" is sounding like a dynamic range compression. What depending on what is being desired can be considered a degradation in quality indeed.

I'll just wait for the next pipewire update, if it fixes the problem, I'll know that the bug was a Pipewire bug... let's wait for now.

**Comment by gabriele2000** [comment]
It was an OBS bug.
Version 28 fixed the problem.
