### ISSUE TITLE
I can't use equaliser and some other plugins for the microphone

### ISSUE THREAD

**Issue by ghost** [wwmm/easyeffects#1781]
Hello so I can use pitch,crossfeed, and noise reduction. But most of the other plugins do not work. What I mean is when I click on the button on the bottom left to output the sound to my headphones so I can hear how my voice is changing, I can tell that the equalizer is not working at all and when I click on the plugin there is no "bar" detecting that there is audio going through this plug in if that makes sense (which is what is happening for the plugins that do work). Any suggestions, i am probably just using this wrong. I am on void linux running the version 6.2.4_1.

**Comment by wwmm** [comment]
Kill the current EE instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`.  You probably do not have some plugins packages installed. Recente EE versions will show a message to you in this case but the one you are using will just print to its logs the missing plugins in your system.

**Comment by wwmm** [comment]
As the solution is probably just installing some optional packages I think this issue can be closed.
