### ISSUE TITLE
EasyEffects not running at all

### ISSUE THREAD

**Issue by Sylviarill** [wwmm/easyeffects#1805]
### EasyEffects Version

6.3.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04

### Describe the bug

After installing from Pop!_OS' store its flatpak, EasyEffects will not run at all with no warning or anything.

### Debug Log

There is no log unfortunately, it literally gives no signs of running at all so I have no idea of what I can provide in general.

### Additional Information

Please note that this Pop!_OS installation is vanilla from their latest iso, so aside of VNC Server, Telegram and KeePassXC there is nothing installed in there just yet, that's the main reason as of why I'm so confused, it is a brand new installation.

**Comment by Sylviarill** [comment]
No idea as of why but it did run after restarting the session once more so, just leaving it there in case people need!

**Comment by cosmicAP** [comment]
> No idea as of why but it did run after restarting the session once more so, just leaving it there in case people need!

thanks it worked on mine too after few restarts
