### ISSUE TITLE
Changes for new LSP 1.2.3 release

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1807]
Linux Studio Plugins 1.2.3 release [changelog](https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.3).

We have to adapt controls for the following points:

- [x] Updated compressor plugin bundles: added negative boosting gain option in 'Boosting' mode.
- [x] Updated gate plugin bundles: added negative gain option for ducking gateway option.

**Comment by wwmm** [comment]
>added negative boosting gain option in 'Boosting' mode

In the `sc_mb_compressor_stereo.ttl` file the minimum value for the `bsa_` parameters now is `0.000251`. So we just have to use `-72 dB` as minimum instead of zero.

>added negative gain option for ducking gateway option.

"ducking gateway option"??

**Comment by wwmm** [comment]
As expected the plugin accepts larger reduction values. If this is what changed in the last release I am not sure. It could have been done in the past and we just did not notice it. When setting the reduction to 72 dB there is clearly a difference in behavior. But I am confused about what is exactly going on. The gate still reduces the signal level. But not as much as when using negative values.

**Comment by wwmm** [comment]
I've updated the master branch with the new gate reduction range. Now we have to find out if that is what changed in the last release. As well as figuring out what reductions above `0 dB` are doing. I did not understand it yet.

**Comment by wwmm** [comment]
The lsp commits should be somewhere inside this site https://github.com/lsp-plugins

**Comment by wwmm** [comment]
That is what changed https://github.com/lsp-plugins/lsp-plugins-gate/commit/a19cc22f3ebc11910dfdd834bd1d18e0b7fddd7c. It is the larger range indeed. Now we have to understand what the `reversed mode` is doing. It definitely did not amplify the signal. The reduction is just smaller.

**Comment by Digitalone1** [comment]
Take a look also here: https://github.com/lsp-plugins/lsp-plugins-mb-gate/commit/ffd2b27987f27ff104ce2d0eb8808554a8799dd2

There are changes to the modes. LFP (recursive 1-pole Low-Pass Filter) and SMA (Simple Moving Average).

**Comment by wwmm** [comment]
>Assigned more correct names for sidechain types
>There are changes to the modes. LFP (recursive 1-pole Low-Pass Filter) and SMA (Simple Moving Average).

Ok. So if I understood correctly we just have to update the names.

>the amount of gain applied to the input signal when the gate is closed (if negative) or open (if positive)

I did more tests and it is like he says. Positive values allow the gate to operate in an inverted mode. It is a little confusing because I was expecting positive values to mean that the signal would be amplified. But what it does is that it reduces the signal when the current intensity is `above the threshold`. Under normal operation the gate will reduce the amplitude when the signal is below the threshold.

**Comment by Digitalone1** [comment]
Anyway later I will open a ticket on LSP Github to list the changes more accurately.

**Comment by Digitalone1** [comment]
Maybe it's better to blocklist `lsp-plugins` in pacman until easyeffects fully integrates the new release features.

**Comment by wwmm** [comment]
>Maybe it's better to blocklist lsp-plugins in pacman until easyeffects fully integrates the new release features.

So far I did not see crashes happening because of this. I am updating the gates with the new filter names.

**Comment by wwmm** [comment]
>That's nice, but I'm afraid I should modify my presets to retain the previous gate behavior.

Because of the reduction gain or the sidechain mode? The reduction change should not cause problems because values above 0 dB could not be set before anyway. But if one of the sidechain modes whose names have changed were being used I imagine that unexpected results may happen.

**Comment by Digitalone1** [comment]
So, let's see if I understood.

- Negative reduction: the amplitude is reduced (by the positive absolute value, ideally) when the gate is closed. Same as previous versions.
- Positive reduction: the amplitude is amplified when the gate is open? Is this like upward compressor, except that the amplification is done above a threshold?

**Comment by Digitalone1** [comment]
> I did more tests and it is like he says. Positive values allow the gate to operate in an inverted mode. It is a little confusing because I was expecting positive values to mean that the signal would be amplified. But what it does is that it reduces the signal when the current intensity is `above the threshold`. Under normal operation the gate will reduce the amplitude when the signal is below the threshold.

Okay, so I was wrong. But isn't this the behavior of a downward compressor?

**Comment by wwmm** [comment]
>But isn't this the behavior of a downward compressor?

It feels similar indeed.

>The gain is positive when the gate is open, so it should amplify, not reduce. It's not clear.

That is what I thought initially. But what is happening is that "values above 0 dB silently change the operation mode". That is why it still reduces the level.

**Comment by Digitalone1** [comment]
Good to know at least. We should write that in a clear way inside our documentation.

**Comment by wwmm** [comment]
>It feels similar indeed.

But the gate can easily completely kill the signal. I did some tests with the threshold set to `-40 dB` both in the compressor and in the "reversed gate" and with `72 dB` in the gate there was only silence. In the downward compressor there was just a decrease in the level even with the ratio set to 100. So they are not doing the same thing.

**Comment by sadko4u** [comment]
Hello!

* The `Boosting gain` option for the compressor from (0 dB ... 72 dB) to (-72 dB .. +72 dB).
![изображение](https://user-images.githubusercontent.com/12834464/188931564-7dcf06bd-4dc6-43bf-b19d-21f332c30269.png)

* 'Reduction' option for the gate has extended range from (-72..0 db) to (-72 ... +72 dB).
![изображение](https://user-images.githubusercontent.com/12834464/188931751-8e280afe-c201-455a-bce4-b8260ff2b9b1.png)

The same is true for multiband versions of plugins, too.

**Comment by wwmm** [comment]
Thanks @sadko4u! Could you explain a little about what is different when the gate is in reversed mode and how this is better than just using the compressor in downward mode so we can properly update our manual? Although I have noticed differences in behavior I am not sure about when the reserved gate is the better tool for the job.

**Comment by sadko4u** [comment]
The reverse gate can be a good option when you want, for example, to overdub some content with background music. To not to make the overdubs too loud (and sometimes it is impossble because of loud background music), you can sidechain the background music with the gate. When the voice of overdubs starts, the sidechain input signal raises and moves the working point of the gate above the threshold. That auomatically makes the gate to open and reduce the loudness of the background music processed by the gate. So instead of raising the loudness of overdubs (what is not always possible), we apply the reverse technique: automatically lowering the loudness of the background music.

**Comment by Digitalone1** [comment]
Thank you @sadko4u.

The changes have need done. It remains to update the manual.

**Comment by wwmm** [comment]
I see. Thanks!
