### ISSUE TITLE
Suggestion: Make PipeWire node.description more human readable

### ISSUE THREAD

**Issue by RafaelKr** [wwmm/easyeffects#1812]
### Discussed in https://github.com/wwmm/easyeffects/discussions/1811

<div type='discussions-op-text'>

<sup>Originally posted by **RafaelKr** September  8, 2022</sup>
Running `pw-cli ls Node` has the following output for me:

<details>

```
	id 28, type PipeWire:Interface:Node/3
 		object.serial = "28"
 		factory.id = "10"
 		priority.driver = "20000"
 		node.name = "Dummy-Driver"
	id 29, type PipeWire:Interface:Node/3
 		object.serial = "29"
 		factory.id = "10"
 		priority.driver = "19000"
 		node.name = "Freewheel-Driver"
	id 37, type PipeWire:Interface:Node/3
 		object.serial = "38"
 		factory.id = "10"
 		client.id = "32"
 		node.name = "Midi-Bridge"
 		media.class = "Midi/Bridge"
	id 46, type PipeWire:Interface:Node/3
 		object.serial = "47"
 		object.path = "v4l2:/dev/video0"
 		factory.id = "10"
 		client.id = "32"
 		device.id = "42"
 		node.description = "Integrated Camera"
 		node.name = "v4l2_input.pci-0000_05_00.3-usb-0_3_1.0"
 		media.class = "Video/Source"
 		media.role = "Camera"
	id 51, type PipeWire:Interface:Node/3
 		object.serial = "81"
 		object.path = "alsa:pcm:0:hdmi:0:playback"
 		factory.id = "18"
 		client.id = "32"
 		device.id = "44"
 		priority.session = "696"
 		priority.driver = "696"
 		node.description = "GA104 High Definition Audio Controller Digital Stereo (HDMI)"
 		node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo"
 		node.nick = "HDA NVidia"
 		media.class = "Audio/Sink"
	id 52, type PipeWire:Interface:Node/3
 		object.serial = "54"
 		object.path = "alsa:pcm:1:front:1:playback"
 		factory.id = "18"
 		client.id = "32"
 		device.id = "45"
 		priority.session = "1009"
 		priority.driver = "1009"
 		node.description = "Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo"
 		node.name = "alsa_output.pci-0000_05_00.6.analog-stereo"
 		node.nick = "HD-Audio Generic"
 		media.class = "Audio/Sink"
	id 53, type PipeWire:Interface:Node/3
 		object.serial = "55"
 		object.path = "alsa:pcm:1:front:1:capture"
 		factory.id = "18"
 		client.id = "32"
 		device.id = "45"
 		priority.session = "2009"
 		priority.driver = "2009"
 		node.description = "Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo"
 		node.name = "alsa_input.pci-0000_05_00.6.analog-stereo"
 		node.nick = "HD-Audio Generic"
 		media.class = "Audio/Source"
	id 62, type PipeWire:Interface:Node/3
 		object.serial = "89"
 		factory.id = "18"
 		client.id = "61"
 		node.description = "EasyEffects Sink"
 		node.name = "easyeffects_sink"
 		media.class = "Audio/Sink"
	id 63, type PipeWire:Interface:Node/3
 		object.serial = "90"
 		factory.id = "18"
 		client.id = "61"
 		node.description = "EasyEffects Source"
 		node.name = "easyeffects_source"
 		media.class = "Audio/Source/Virtual"
	id 72, type PipeWire:Interface:Node/3
 		object.serial = "99"
 		client.id = "61"
 		node.description = "ee_soe_output_level"
 		node.name = "ee_soe_output_level"
 		node.nick = "output_level"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 77, type PipeWire:Interface:Node/3
 		object.serial = "104"
 		client.id = "61"
 		node.description = "ee_soe_spectrum"
 		node.name = "ee_soe_spectrum"
 		node.nick = "spectrum"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 88, type PipeWire:Interface:Node/3
 		object.serial = "115"
 		client.id = "61"
 		node.description = "ee_sie_output_level"
 		node.name = "ee_sie_output_level"
 		node.nick = "output_level"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 93, type PipeWire:Interface:Node/3
 		object.serial = "120"
 		client.id = "61"
 		node.description = "ee_sie_spectrum"
 		node.name = "ee_sie_spectrum"
 		node.nick = "spectrum"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 98, type PipeWire:Interface:Node/3
 		object.serial = "125"
 		client.id = "61"
 		node.description = "ee_sie_rnnoise"
 		node.name = "ee_sie_rnnoise"
 		node.nick = "rnnoise"
 		media.type = "Audio"
 		media.category = "Filter"
 		media.role = "DSP"
	id 103, type PipeWire:Interface:Node/3
 		object.serial = "189"
 		factory.id = "6"
 		client.id = "111"
 		application.name = "spotify"
 		node.name = "spotify"
 		media.class = "Stream/Output/Audio"
 		media.role = "Music"
	id 105, type PipeWire:Interface:Node/3
 		object.serial = "213"
 		factory.id = "8"
 		client.id = "32"
 		device.id = "106"
 		priority.session = "1010"
 		priority.driver = "1010"
 		node.description = "Teufel BOOMSTER"
 		node.name = "bluez_output.00_12_6F_C1_2C_50.a2dp-sink"
 		media.class = "Audio/Sink"
```
</details>

As you can see most nodes have a "human readable" name set as the `node.description` and a more generic name as `node.nick`. 

Currently helvum, the "official" patchbay for PipeWire, prefers the nick and falls back to the description. So the names for the EasyEffects nodes look okay:

![image](https://user-images.githubusercontent.com/14234815/189139178-99036463-bea5-4385-8cde-eade84dd2b4e.png)

But there's an ongoing discussion about changing it to the order `node.description` > `node.nick` > `node.name`:
https://gitlab.freedesktop.org/pipewire/helvum/-/issues/38

So I'd like to suggest to set the description to something more human readable to prepare for that change.</div>

**Comment by RafaelKr** [comment]
I gave it a shot in #1819 and made the description the same as the nick. I think this is a good first step.

Maybe this can be improved even further with more human-readable descriptions (e.g. `EasyEffects Output Level` instead of `output_level`) but I think this needs a bit more of refactoring and I'm not deep enough into C++ and this codebase to do it.

**Comment by wwmm** [comment]
>but I think this needs a bit more of refactoring and I'm not deep enough into C++ and this codebase to do it.

I think I will have time to take a look at this in the next days.

**Comment by RafaelKr** [comment]
That sound great! The minimal changes in #1819 would still be ready to merge on their own if the changes to `src/pipe_manager.cpp` are correct.

**Comment by wwmm** [comment]
I admit I have forgotten the current state of this issue. How are things on Helvum side? Do we need to do more changes or are the ones already in place enough?

**Comment by RafaelKr** [comment]
With the changes in place EasyEffects is prepared for the merge of the Helvum Merge Request [!27 Draft: Display better names](https://gitlab.freedesktop.org/pipewire/helvum/-/merge_requests/27).

With that MR Helvum will prefer `node.description` over `node.nick`. Currently the EasyEffects `node.description` is less descriptive than the `node.nick`, see my "Details" spoiler in the OP: https://github.com/wwmm/easyeffects/issues/1812#issue-1366521414.
With the changes from my PR #1819 description and nick are the same, so nothing will change when the Helvum version with the changes from MR !27 will be released.

So the issue with the regressing display names with the new Helvum version is resolved when you release the next EasyEffects version.
But the node description in EasyEffects could still be improved, e.g. `EasyEffects Output Level` instead of `output_level`.

**Comment by RafaelKr** [comment]
Yes, with the 7.0 release nothing regarding the node names in Helvum should break, it should be as is.

**Comment by RafaelKr** [comment]
Yes, with the 7.0 release nothing regarding the node names in Helvum should break, it should be as is.

BTW: I edited my previous comment to make it more clear.

**Comment by RafaelKr** [comment]
Helvum 0.4.0 was now released. The EasyEffects 7.0.0 labels are, as expected, still the same as they were with Helvum 0.3.4 👌

**Comment by wwmm** [comment]
>Helvum 0.4.0 was now released. The EasyEffects 7.0.0 labels are, as expected, still the same as they were with Helvum 0.3.4

Ok :-). So now it is only a matter of doing the following small improvement

>But the node description in EasyEffects could still be improved, e.g. EasyEffects Output Level instead of output_level

I will try to do this this week.

**Comment by wwmm** [comment]
With the latest changes in our master branch the description should be equal to what can be seen in the `Add Effects` menu. This means that the descriptions showed in Helvum will now also be translated just like in the `Add Effects` menu.

**Comment by RafaelKr** [comment]
Love it, thanks for your work on that! :heart:

**Comment by RafaelKr** [comment]
Just tested it, works great!

Easy Effects (Devel) [Compilation from master]
![Screenshot from 2023-02-16 16-02-40](https://user-images.githubusercontent.com/14234815/219402459-ea309907-5f61-4856-bdee-a3630da3e83d.png)

for reference
Easy Effects v7.0.0
![Screenshot from 2023-02-16 16-03-01](https://user-images.githubusercontent.com/14234815/219402074-d14b1f2f-3acf-4881-9583-8f2e32db1a54.png)
