### ISSUE TITLE
Change Input/Output Device from command line/script

### ISSUE THREAD

**Issue by HannahSlaughterZacharski1988** [wwmm/easyeffects#1821]
### Discussed in https://github.com/wwmm/easyeffects/discussions/1337

<div type='discussions-op-text'>

<sup>Originally posted by **Ameb** January 14, 2022</sup>
Hello.
I use multiple audio devices. keep all of them connected and use the Input / Output device dropdown to switch between them (Easyeffects is my default device in pipewire)

```
$ pactl get-default-sink   
easyeffects_sink
```

Is it possible to change the input/output device from CLI or a script? We can bind presets to devices, but not the other way around.

A screenshot to understand what i mean with the device dropdown:

![image](https://user-images.githubusercontent.com/386567/149456326-bf56f55a-ae9e-4bd8-a20e-a9b725048b6e.png)

Cheers
</div>

**Comment by wwmm** [comment]
>Is it possible to change the input/output device from CLI or a script? 

Yes. Following the idea at #916 all you have to do is constructing the right path
![Screenshot from 2022-09-13 20-00-30](https://user-images.githubusercontent.com/16225172/190024034-4869a1d2-307e-439c-a2a3-dbecc9645a11.png)

>Easyeffects is my default device in pipewire

If you ever enable `Use Default Output/Input` again do not do this.

**Comment by wwmm** [comment]
This issue can be closed.
