### ISSUE TITLE
Convolver effect causing audio stutters

### ISSUE THREAD

**Issue by har-nick** [wwmm/easyeffects#1840]
### EasyEffects Version

6.3.0

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I don't know the underlying cause, so I'm just giving what I actually do that causes this, sorry.

When opening/closing KDE's volume control widget (I'm assuming it's plasma-pa package), audio stutters for a moment before continuing.

Tested with aur/spotify and YouTube via Firefox to the same effect. Issue doesn't occur with Equalizer effect as I used to use it.

Weirdly, I can't record this issue through OBS. Audio stutters once when opening OBS, and won't happen until I close it.

**Comment by wwmm** [comment]
KDE volume control widget is probably making PipeWire's switch to a different latency. The convolver plugin is one of the few plugins in EasyEffects that have to be restarted when the latency or the sampling rate is dynamically changed by PipeWire. 

Something you may try is forcing PipeWire to use a constant `quantum size (latency)`. Until I find a way to make the convolver play nice with  dynamic latency changes it is the only solution.

**Comment by har-nick** [comment]
Thank you for such a quick reply!

Honestly, I don't feel confident in changing much of the settings in Pipewire as I simply don't understand them so I'll stick with using the EQ filter instead for now.

**Comment by wwmm** [comment]
In case you change your mind in the future there are ways to temporarily set a fixed quantum size without editing configuration files https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#quantum-ranges. Through this method the setting is lost after a logout or reboot but it can still be useful in some situations.
