### ISSUE TITLE
libboost_filesystem (boost-libs) updated  and now can't use the application

### ISSUE THREAD

**Issue by erlonbie** [wwmm/easyeffects#1847]
### EasyEffects Version

Can't open the application to check it, but I assume it is on the latest version

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux (ArcoLinux)

### Describe the bug

If I run the program through the terminal, I get this message:

`error while loading shared libraries: libboost_filesystem.so.1.79.0: cannot open shared object file: No such file or directory`

libboost_filesystem (boost-libs) had an update 3 days ago (1.80.0-2), and I updated my system yesterday. Before that I might have updated 1 or 2 weeks ago.

### Expected Behavior

Open the gui application and works and it should.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>Can't open the application to check it, but I assume it is on the latest version

Are you sure? Boost stopped being an EasyEffects dependency a long time ago.

**Comment by wwmm** [comment]
Run it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`

**Comment by erlonbie** [comment]
![image](https://user-images.githubusercontent.com/50176483/191858004-2ae2e95e-5dee-4609-9efc-b6e0ba5c4df0.png)

Like this? Sorry in advance if this a trivial thing and I don't know how to do it.

**Comment by Digitalone1** [comment]
If you don't need to use PulseAudio, please install Easy Effects in place of PulsEffects.

**Comment by wwmm** [comment]
>Like this? Sorry in advance if this a trivial thing and I don't know how to do it.

Oh... You have PulseEffects installed and not EasyEffects. In any case when this kind of problem happens the solution is just to rebuild the packaage. What should be done by your distribution package maintainers. But as you are using a distribution based on Arch Linux one possible solution is to build your own package through an AUR PKGBUILD.

**Comment by erlonbie** [comment]
> > Like this? Sorry in advance if this a trivial thing and I don't know how to do it.
> 
> Oh... You have PulseEffects installed and not EasyEffects. In any case when this kind of problem happens the solution is just to rebuild the packaage. What should be done by your distribution package maintainers. But as you are using a distribution based on Arch Linux one possible solution is to build your own package through an AUR PKGBUILD.

I just reinstalled through the AUR (where I installed from) and now it's working fine! Thanks for the tip, @wwmm 

closing the issue.
