### ISSUE TITLE
Feature Request : Add a remote control system (e.g. like OBS Websocket)

### ISSUE THREAD

**Issue by xurei** [wwmm/easyeffects#1863]
### EasyEffects Version

6.2.8

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I would like to use EasyEffects for voice effects while streaming.
From my understanding, the only way to do this now is to either use the GUI (really impractical while streaming) or a preset (kinda practical yet complicated to setup and maintain over time).

I'm thinking about a system like OBS-Websocket, where you could control some aspects of EasyEffects with a networked messaging system (MQTT, Websocket, whatever). This would enable me to e.g. toggle effects using a keyboard shortcut.

I'm ready to implement a simple version of this for my personal needs. The most important commands I need is being able to toggle an effect.

How do you feel about this feature ? Is it something that would be useful for other people ? 
Is it a thing that could be integrated in the official releases (provided its quality meets you standards) ?

### Expected Behavior

A mini server listening for commands that would toggle an effect, change a value in an effect etc.

### Debug Log

N/A

### Additional Information

N/A

**Comment by wwmm** [comment]
There is no need to create a service to change our parameters. You can do this with the GSettings API https://github.com/wwmm/easyeffects/discussions/916. The discussion was for pulseeffects but the same idea applies for easyeffects. The paths just have to be adjusted.

Something that can not be done with GSettings is getting the level meters. This would require something more complex indeed.

**Comment by vchernin** [comment]
There is also a new [global shortcuts](https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.GlobalShortcuts.xml) portal, which EasyEffects could use to ask the host for a global keyboard shortcut. Albeit it is still new so I don’t think there are stable/released implementations today.

**Comment by wwmm** [comment]
I think we can close this issue.
