### ISSUE TITLE
Wrong frequency displayed in spectrum mouseover

### ISSUE THREAD

**Issue by DorianRudolph** [wwmm/easyeffects#1866]
### EasyEffects Version

6.3.0.r172.g16b4ec79-1

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

![20221002_15h56m34s_grim](https://user-images.githubusercontent.com/10325838/193457860-2f75e6bd-a558-48e2-be37-80333471e481.png)

The label says `x = 142 Hz`, but I would expect something like `x = 6000 Hz` (not sure what the exact value should be, but certainly something between 5000 and 10000).

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Hi. Try to rebuild your AUR package. I have fixed this regression some time ago https://github.com/wwmm/easyeffects/commit/c6be82b92d7c675ec1c1a1bb80a99116c7298b57. At least here on my side things are fine now.
