### ISSUE TITLE
Reducing number of equalizer bands doesn't distribute them evenly

### ISSUE THREAD

**Issue by reidrivenburgh** [wwmm/easyeffects#1877]
Hi.  I think EasyEffects is great, but I might be missing something about the equalizer.  I believe the default is to have 32 bands, which to me seems like a lot (I'm no audio engineer).  I tried reducing the number to 8, but it ends up only keeping the left-most ones, from 22 Hz to 101 Hz.  That doesn't seem useful.  I expected it would spread the 8 over the full spectrum to some degree.  Am I crazy...?  TIA.

**Comment by wwmm** [comment]
Hi. If you click on the `Calculate Frequencies` button some values will be suggested assuming you want to mimic a graphical equalizer with the given number of bands. But take them just as a suggestion. Technically speaking what is in EasyEffects is a parametric equalizer. So the user should customize the parameters according to his/her needs.

**Comment by reidrivenburgh** [comment]
Ah, I didn't try hitting that button.  Thanks!
