### ISSUE TITLE
Easyeffects stops working and i have to kill it via system monitor

### ISSUE THREAD

**Issue by ghost** [wwmm/easyeffects#1892]
### EasyEffects Version

6.3.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 37 Beta

### Describe the bug

Easyeffects randomly stops working and i have to kill it via system monitor in order to open it again. I usually notice because spotify says "cant reproduce the song" and goes mute. If i try to open the application by clicking its icon, it doesnt open. If i kill it, then everything starts working again. I tried both the fedora flatpak and the RPM version, both have the same issue.

**Comment by wwmm** [comment]
More information will be necessary in order to know what is going on. Is there anything related to EasyEffects in the output of `sudo journalctl`?

As you are using a beta fedora release one possibility is that some library in it is not playing nice with EasyEffects. At least here on Arch Linux I think I have never seen what you are describing.

**Comment by chriztheanvill** [comment]
I have the same problem in Fedora and Debian. Stops working randomly.
I found this:
`GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken`

**Comment by wwmm** [comment]
>GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken

Strange. We do not even talk do DBUS directly. This may be a problem in a lower level library like gtk4.

**Comment by chriztheanvill** [comment]
> 

In Fedora I've downgraded pipewire from 0.3.59 to 0.3.49 and works normally. The case, in Debian SID I cant downgrade it.
```bash
## Fedora packages
pipewire
pipewire-alsa
pipewire-codec-aptx
pipewire-gstreamer
pipewire-libs
pipewire-pulseaudio
pipewire-utils
wireplumber
```

**Comment by wwmm** [comment]
>In Fedora I've downgraded pipewire from 0.3.59 to 0.3.49 and works normally. 

Strange. I am using `0.5.59` here on Arch Linux without problems.

**Comment by chriztheanvill** [comment]
Are you using wireplumber or pipewire-media-session?

**Comment by wwmm** [comment]
>Are you using wireplumber or pipewire-media-session?

I have been using `wireplumber` for a few months.

**Comment by chriztheanvill** [comment]
```bash
(easyeffects:8973): easyeffects-WARNING **: 07:10:24.650: 	pipe_manager.cpp:1358	Remote error res: Broken pipe

(easyeffects:8973): easyeffects-WARNING **: 07:10:24.650: 	pipe_manager.cpp:1359	Remote error message: connection error

```

**Comment by wwmm** [comment]
>(easyeffects:8973): easyeffects-WARNING **: 07:10:24.650: 	pipe_manager.cpp:1358	Remote error res: Broken pipe

>(easyeffects:8973): easyeffects-WARNING **: 07:10:24.650: 	pipe_manager.cpp:1359	Remote error message: connection error

These warning are not related to dbus and can happen on perfectly fine systems sometimes. Something else is the source of the current problem you see seeing.

**Comment by kinnounko** [comment]
I am having this same issue on Arch Linux. I am not sure what triggers EE to get into this state, but I indeed have to kill and restart it for it to work again. I can't seem to find any leads as to why this happens either.

**Comment by chriztheanvill** [comment]
> I am having this same issue on Arch Linux. I am not sure what triggers EE to get into this state, but I indeed have to kill and restart it for it to work again. I can't seem to find any leads as to why this happens either.

I kind of get it. Using Firefox or VLC, pipewire stop working, so I think is not Easyeffects.

**Comment by wwmm** [comment]
>I kind of get it. Using Firefox or VLC, pipewire stop working, so I think is not Easyeffects.

Is there any chance that the computer was suspended or entered hibernation before the problem happened?

**Comment by wwmm** [comment]
>Is there any chance that the computer was suspended or entered hibernation before the problem happened?

Or that PipeWire's process died. For some reasons it is hard to implement automatic restart in EasyEffects after the death of the audio server. So if PipeWire is crashing EasyEffects will have to be manually restarted. PipeWire is able to restart itself automatically when it dies. But EasyEffects isn't. The same thing may be true for Firefox and VLC. THis could explain why other programs are also affected.

**Comment by kinnounko** [comment]
> > Is there any chance that the computer was suspended or entered hibernation before the problem happened?
> 
> Or that PipeWire's process died. For some reasons it is hard to implement automatic restart in EasyEffects after the death of the audio server. So if PipeWire is crashing EasyEffects will have to be manually restarted. PipeWire is able to restart itself automatically when it dies. But EasyEffects isn't. The same thing may be true for Firefox and VLC. This could explain why other programs are also affected.

That sounds like a promising explanation. I'll try to debug it when I have some time and I'll report back here

**Comment by chriztheanvill** [comment]
> > Is there any chance that the computer was suspended or entered hibernation before the problem happened?
> 
> Or that PipeWire's process died. For some reasons it is hard to implement automatic restart in EasyEffects after the death of the audio server. So if PipeWire is crashing EasyEffects will have to be manually restarted. PipeWire is able to restart itself automatically when it dies. But EasyEffects isn't. The same thing may be true for Firefox and VLC. This could explain why other programs are also affected.

No. 
* Turn on the PC. (Fedora 36 or Debian Sid)
* start using Firefox or VLC
* some minutes after, (the pc wasn't suspended, hibernation, sleep)
* then all sound devices disappear for a moment (stop any sound), easyeffects does not stop.
* back again all sound devices but easyeffects still on, but does not affect to any device and cannot open the GUI of easyeffects. Needs to be killed to work again.
* The issue could be reproduce if open again Firefox or VLC.

**Comment by wwmm** [comment]
>then all sound devices disappear for a moment (stop any sound), easyeffects does not stop.

Other than PipeWire process dying I can't think of a natural reason why all the sound devices would disappear. I am assuming that by disappear you mean not being visible in audio managers like Pavucontrol or Gnome Settings. Virtual devices can be easily unloaded by a third party tool but at the very least the nodes related to the sound card hardware should not be disappearing if the server process is no dying. Strange...

**Comment by kinnounko** [comment]
For me the issue is rather that the EasyEffects panel just doesn't seem to be catching any audio. From Pavucontrol I can see that it is indeed processing audio in some manner. So I think chriztheanvill's issue is not the same as mine at least.

**Comment by wwmm** [comment]
>For me the issue is rather that the EasyEffects panel just doesn't seem to be catching any audio. From Pavucontrol I can see that it is indeed processing audio in some manner. 

@kinnounko is there any chance that you are seeing what is discussed at #1789?

**Comment by kinnounko** [comment]
> > For me the issue is rather that the EasyEffects panel just doesn't seem to be catching any audio. From Pavucontrol I can see that it is indeed processing audio in some manner.
> 
> @kinnounko is there any chance that you are seeing what is discussed at #1789?

It does seem to be that issue. Thanks for pointing me there.

**Comment by wwmm** [comment]
>On the other hand EF 7.0 completely broke the "Filter" but thats another issue.

This is happening only in the Flatpak package. We are not sure why yet.
