### ISSUE TITLE
Easy effects interface not in French

### ISSUE THREAD

**Issue by Tuxman2** [wwmm/easyeffects#1918]
### EasyEffects Version

6.3.0

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro

### Describe the bug

I can set Easy effects in French. Only English.

### Expected Behavior

Have Easy effects interface in French.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Use Easy effects on Gnome 42.x.

**Comment by wwmm** [comment]
What is the output of the command `locale`? AT this moment I do not see a reason why only French translations would not be working. Maybe something is missing in Manjaro locale configuration. Or some kind of problem happened when the Manjaro package for EasyEffects was built.

**Comment by Tuxman2** [comment]
Hi,

sorry to reply late.
Ok, I found the problem. I switched to fr_FR for locale and now it works.

I close the subject.
