### ISSUE TITLE
Bass enhancer plugin not working after latest update.

### ISSUE THREAD

**Issue by DeeBeeDouble** [wwmm/easyeffects#1935]
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 36

### Describe the bug

After the latest update, the bass enhancer plugin stopped working. For now, it seems to be the only one not working. Using helvum I can see that the audio is still routed through it, but it has no effect. I can change every setting for it, it does absolutely nothing.

### Expected Behavior

The plugin should work like it previously did.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
You have PipeWire 0.3.59 installed
This is newer or the same as PipeWire 0.3.41 required to run Easy Effects
lilv_lib_open(): error: Failed to open library /app/lib/lv2/calf.lv2/calf.so (/usr/lib/x86_64-linux-gnu/libjack.so.0: undefined symbol: pw_thread_fill_attr)

(easyeffects:2): easyeffects-WARNING **: 20:29:16.303: 	lv2_wrapper.cpp:225	failed to instantiate http://calf.sourceforge.net/plugins/BassEnhancer
```
</details>

**Comment by wwmm** [comment]
It is the same thing that is happening at #1933. The filters are working fine when using native packages. It is in the flatpak package that something is not right. We are not sure about what yet.
