### ISSUE TITLE
The autostart service .desktop file uses the wrong icon

### ISSUE THREAD

**Issue by m911t** [wwmm/easyeffects#1936]
### EasyEffects Version

7

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I went to check the presence of Easyeffects on Gnome Tweaks, and I found a broken app icon image for Easyeffects. turns out the desktop file for the easyeffects-service.desktop file uses "easyeffects" as icon, while the normal application uses "com.github.wwmm.easyeffects"

### Expected Behavior

The icon is properly shown.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by piorrro33** [comment]
Depending on your icon pack you may have a symlink for the `easyeffects` icon, I know that the Papirus icon pack has one for example.
Nevertheless I agree the service desktop file should be updated to match the new icon name.

**Comment by wwmm** [comment]
Thanks! I have updated our master branch with a fix for this.
