### ISSUE TITLE
Sound stuttering on certain hardware when mixing streams of different sample rates

### ISSUE THREAD

**Issue by jkatzmewing** [wwmm/easyeffects#1940]
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Debian Bookworm with KDE (on Wayland)

### Describe the bug

I've been having issues for a while with sound stuttering on my custom AMD Cezanne desktop, when using EasyEffects. This does not seem to happen on other machines, including a far less powerful Surface Pro 3. pw-top shows errors whenever there's a stutter, but otherwise I had trouble finding more info. This was a particular issue with Pithos, but happened with Quod Libet as well.

For a while I managed with fixed Pipewire quantum between 512 and 2048. This solved the problem in most cases, and in fact just setting the quantum limit to 2048 (as opposed to 8192) seemed to prevent almost as much.

I also noticed that most of the stutters happened during or shortly after KDE notification sounds, while playing music. So I tried turning those off, and that helped. Having two music apps playing at the same time, I was able to reliably and continuously produce stuttering.

Noticing that the DSP and Quod Libet were set to 48000 Hz and Pithos was playing at 44100, I tried setting the DSP in Pipewire to 44100 Hz... And it worked! Multiple streams now mix without any stuttering or errors at all.

### Expected Behavior

Ideally EasyEffects should be able to process streams of different sample rates without stuttering on any modern hardware.

**Comment by jkatzmewing** [comment]
Sorry, this was wrong - it turns out I can get

**Comment by wwmm** [comment]
> also noticed that most of the stutters happened during or shortly after KDE notification sounds, while playing music

Which plugins are enabled? The notifications may be forcing PipeWire to change latency or sampling rate. Fixed quantum values will force a fixed latency but depending on your PipeWire is configured sampling rate changes may still happen. The convolver and the crystalizer plugins still require a reinitialization when latency or sampling rate changes. And they are known to cause noticeable stuttering/crackling in some systems.

**Comment by jkatzmewing** [comment]
Currently just crossfeed and equalizer.

**Comment by wwmm** [comment]
>Currently just crossfeed and equalizer.

These plugins should be fine on latency and sampling rate changes. Something else is going on. I have the feeling we will have to look at what is being shown by Pipewire's logs when the problem happens. The source of this stuttering may be in the server side.

**Comment by jkatzmewing** [comment]
Thank you, and FYI I was actually just able to reproduce the stutter without EasyEffects. Closing this, sorry for the false alarm.
