### ISSUE TITLE
Plans for the next release

### ISSUE THREAD

**Issue by wwmm** [wwmm/easyeffects#1950]
Small list of changes I would like to do in the next release:

- [x] Improving the spectrum update frequency without adding additional latency. `Done on 7.0.1.` 
- [x] Use GtkListviews in the equalizer window. Our current approach is very slow and not convenient to do things like sorting the bands. `Done on 7.0.1.`
- Use the soundtouch library to offer an alternative pitch shift algorithm. [soundtouch page](https://www.surina.net/soundtouch/) and [article](https://www.surina.net/article/time-and-pitch-scaling.html) and [code example](https://codeberg.org/soundtouch/soundtouch/src/branch/master/source/SoundStretch/main.cpp)
- [x] Improving the echo canceller plugin somehow. `Done on 7.0.1.`

**Comment by bhack** [comment]
It could be also interesting to re-evaluate:

https://github.com/wwmm/easyeffects/issues/1433#issuecomment-1229354428
https://github.com/wwmm/easyeffects/issues/1316#issuecomment-1257054964

**Comment by wwmm** [comment]
>It could be also interesting to re-evaluate:
>https://github.com/wwmm/easyeffects/issues/1433#issuecomment-1229354428
>https://github.com/wwmm/easyeffects/issues/1316#issuecomment-1257054964

Some weeks ago I was looking at the "show plugins curves problem" again. It is still as annoying as ever. It does not seem to have any kind of restriction in the LV2 API about how plugins are supposed to send this kind of information to theeir custom window. Each plugin author seems to do something different. And even reading both `Linux Studio Plugins` as LV2 hots source code I still have no idea about how to even start...

**Comment by bhack** [comment]
One of the annoying problem in EQ is that if you customize an EQ preset Easyeffect doesn't [recompute the pre-amp value to avoid clipping](https://github.com/jaakkopasanen/AutoEq/issues/474#issuecomment-1193665037).
If we cannot to this we need to manually launch and connect e.g. x42 monitors to manually track dBTP peaks and adjust the pre-amp.

**Comment by Digitalone1** [comment]
An unsolved issue is the automatic management of multichannel. Unfortunately this is a regression compared to PulseEffects on Pulseaudio. 

Pipewire does not offer an automatic channel remapping yet and the only way to workaround this issue at the moment is to set a loopback virtual device which works, but it's not user friendly to use and configure.

Personally EasyEffects is enough for my use case because I use a stereo system, but I don't like this great app does not have a feature that was already included in the past version (PulseEffects).

**Comment by wwmm** [comment]
>Pipewire does not offer an automatic channel remapping yet and the only way to workaround this issue at the moment is to set a loopback virtual device which works, but it's not user friendly to use and configure.

As far as I am aware the situation is still the same on PipeWire's side. It still provides upmixing/downmixing only to streams. What is really inconvenient to any program that uses PipeWire's own filter API.

A long time ago I tried to make a hybrid filter that had the usual DSP ports in the input and streams handling the output ports. But for some reason I do not remember my attempt failed miserably.

**Comment by DoctorBertalis** [comment]
Thank you very much for your work! I already left a bug report here:
https://github.com/wwmm/easyeffects/issues/723
After closing it, the quality of the pitch shift plugin has become noticeably better. But still, the work of the Rubberband plug-in has its drawbacks in processing complex musical compositions, such is its specificity, since it uses a frequency signal conversion method. In fact, it is a phase vocoder, but there is another method of shifting the pitch, temporal, without changing the sound time of the original composition, which is implemented in the Soundtouch plugin.
You can read about these two methods here:
https://www.surina.net/article/time-and-pitch-scaling.html
In my case, when I use sound processing with a small pitch shift of only minus 32 cents, then using the Soundtouch plugin in programs such as Foobar2000 (in Wine on Linux) or Maple JB (on Android) gives an almost perfect result, in contrast from Rubberband!
The point of my current post is to propose to improve EasyEffects by adding a Soundtouch plugin option in addition to the existing Rubberband, so that I can select one of them in the Pitch item. Although it is believed that the Soundtouch gives a little more delay than the Rubberband, its use for high-quality pitch-shifting with small values ​​is more than justified.
Here is a link to the source:
https://www.surina.net/soundtouch/
Thank you!

**Comment by wwmm** [comment]
>The point of my current post is to propose to improve EasyEffects by adding a Soundtouch plugin option in addition to the existing Rubberband, so that I can select one of them in the Pitch item. Although it is believed that the Soundtouch gives a little more delay than the Rubberband, its use for high-quality pitch-shifting with small values ​​is more than justified.

Interesting. Considering how problematic the rubberband library has been in some hardware it is a good idea to offer another option.

**Comment by bhack** [comment]
Can we find a quick way to undo the flat the response button in the EQ?
It will be very useful to switch on and of to compare forth and back the EQ effect when fine tuning the EQ cause reloading the preset every time is a little bit time consuming.

**Comment by wwmm** [comment]
>Can we find a quick way to undo the flat the response button in the EQ?

Unless gsettings has a built-in way to revert settings to the last used values this collides with how the database works. Once the flat button changes the values the new `0 dB` gain is saved instantly in the database. The setting won't be propagated to the plugin otherwise.

As I do not think gsettings has such a feature it would be necessary to keep track of what is happening to the gain values. It seems a little niche to add this level of complication just to not load a preset.

**Comment by bhack** [comment]
I understand but the problem was not just to load the preset again. It is that if you are going to listen the same part of the track it is too slow to access with the mouse to the load preset sub-menu and switching forth and back between the load preset menu and flat profile button isn't fast enough.

**Comment by wwmm** [comment]
>I understand but the problem was not just to load the preset again. It is that if you are going to listen the same part of the track it is too slow to access with the mouse to the load preset sub-menu and switching forth and back between the load preset menu and flat profile button isn't fast enough.

Couldn't the plugin bypass button help with this? In most situations setting the gain to flat would have the same effect as bypassing the filter.

**Comment by bhack** [comment]
> Couldn't the plugin bypass button help with this?

Yes the problem is that the relationship between the gain and DBFS is not linear so generally when you bypass the plugin the volume is sensibly higher and you are fooled by perceived volume levels in your EQ setting job.

And we don't have a bypass but keep the gain level function.

And we cannot just set the gain to zero cause we could clip when the plugin is on.

**Comment by p-chan5** [comment]
How about adding some fields like description, usage, or categories? This would be very helpful when identifying a preset. Also, how about a favorites section? The images are from [Hive 2](https://u-he.com/products/hive/), a synth from [u-he](https://u-he.com/) with a Linux version!
<img src="https://user-images.githubusercontent.com/123143444/215309130-bb115fdf-ae80-4aaf-aaaf-a857a2d73069.png" height="250"> ![003](https://user-images.githubusercontent.com/123143444/215309141-f7ae72ab-338a-4def-b6eb-a43f9ad37782.png)

**Comment by wwmm** [comment]
>How about adding some fields like description, usage, or categories? This would be very helpful when identifying a preset. Also, how about a favorites section?

The main problem with this idea is where these new widgets to view and set tags would be. We don't really have space for them in our presets menu. Maybe if we did not have different presets for input and output. But as we do we would probably need to implement 2 favorites sections. And again where to put them is a problem.

One possibility would be not putting them in the presets menu. But having a favorites section hidden somewhere else does not seem useful. It would not be too bad to set the tags in another place but again if we do not see them in the presets menu they are not going to be useful.

**Comment by p-chan5** [comment]
You are right. This only makes sense in plugins where a large number of presets are commonly included. Perhaps something similar to the EasyEffects interface would be the [Vital](https://github.com/mtytel/vital) synth. Although it would also be necessary to develop a browser. It's not a bad idea, but it's much more complex than it seems.
<img src="https://user-images.githubusercontent.com/123143444/215675058-62183a8a-5d0d-49d0-b22c-974a45c536e6.png" height="300">

**Comment by p-chan5** [comment]
On other topics... The other day I noticed that EasyEffects shows more precise values ​​using the mouse wheel in some of the `Equalizer` bands unlike PulseEffects. It would be great to see this feature come back as I find it much faster than the default!

![001](https://user-images.githubusercontent.com/123143444/215679842-5b8cb2a3-6216-40f1-9ec6-3c4e3f612bc6.gif) <img src="https://user-images.githubusercontent.com/123143444/215679879-a3b0a29e-aa3c-49fb-b891-d5ba975f57d0.gif" height="315">

**Comment by DoctorBertalis** [comment]
> On other topics... The other day I noticed that EasyEffects shows more precise values ​​using the mouse wheel in some of the `Equalizer` bands unlike PulseEffects. It would be great to see this feature come back as I find it much faster than the default! I mean it took me a long time to get to -10 dB pensive It would also be nice to be able to set these values by double clicking on the number.

Yes, so far in version 6.3.0 on my system, this is the situation with the adjustment step:
1. Mouse wheel step is +/-0.1dB
2. Keyboard keys "Up/Down" is +/-0.01dB
3. Keyboard keys "PageUp/PageDown" is +/-0.1dB.
But is it possible to make an adjustment step of +/-1.0 dB on the 3rd point? Then the adjustment will be more convenient.

**Comment by wwmm** [comment]
>Embora eu até tenha a planilha das outras coordenações nem todos eles atualizaram com os nomes de docentes da planilha do codib. Divulgá-las agora só causará o caos kkk

I will take a look at it. But I am not sure GTK allows us to have both the precise and not precise steps.

**Comment by wwmm** [comment]
Currently our bands are set as
```
<property name="step-increment">0.01</property>
<property name="page-increment">0.1</property>
```
As far as I can see the mouse scroll and the page up/down keys trigger the `page-increment`. The up/down arrows trigger the `step-increment`. Maybe we can make the page-increment equal to `1.0` and keep the step-increment as it is now.

**Comment by wwmm** [comment]
>Maybe we can make the page-increment equal to 1.0 and keep the step-increment as it is now.

Done. I have also made some changes to the spectrum plugin update rate. I think that now different sampling rates finally feel the same visually. But as the solution is a little tricky this has to be tested on other systems besides mine.

**Comment by p-chan5** [comment]
Thanks for taking it into account! I hope it can be tested soon.

**Comment by wwmm** [comment]
>Thanks for taking it into account! I hope it can be tested soon.

It is already in our master branch. So people with access to any kind of package that builds from it can already test it. Our github artifacts generated for each commit have Arch Linux and Flatpak packages that can be used https://github.com/wwmm/easyeffects/actions/runs/4105986735.

**Comment by wwmm** [comment]
The update interval used by the level meters and the spectrum can now be customized by the user through a new option in our preferences window. But there are some limitations. If PipeWire sends buffers fast enough the setting should work as intended. But if for some reason PipeWire is sending buffers in a time window that is longer than the one set in our configuration option it obviously is not going to work. There is no way to force the server to send buffers faster.

**Comment by wwmm** [comment]
Version `7.0.1` released. It has the features marked as completed in this issue first post. Hopefully the changes to the pitch plugin will be done on `7.0.2`

**Comment by p-chan5** [comment]
Thanks for posting! Were there changes to the structure of the `.js` files? I mean, are the presets made in `7.0.0` are compatible with this version?

**Comment by wwmm** [comment]
>I mean, are the presets made in 7.0.0 are compatible with this version?

Yes. There was no change to the presets format. So unless a new bug has been introduced presets should still work.

**Comment by bhack** [comment]
Do you think it would be possible to not freeze the UI or have some UI feedback when loading a preset?

**Comment by wwmm** [comment]
>Do you think it would be possible to not freeze the UI or have some UI feedback when loading a preset?

The freeze you are seeing is probably related to GSettings saving the parameters to the database. How noticeable it is depends on how powerful the CPU is as well as on the amount of settings being written. On my computer I have to change a lot of parameters to see the freezing. Fixing it is tricky. Specially when we consider that inside Flatpak GSettings uses a different backend that has really bad performance. Are you using Flatpak or a native package?

As GSettings works in the GTK main thread I doubt a notification is viable. Unless there is a way to make GSettings run in a secondary thread. But I doubt it is possible.

**Comment by bhack** [comment]
Flatpak, It is just 1/2 sec of UX freeze.

**Comment by vchernin** [comment]
I think it was discussed somewhere before, but using `g_settings_delay` and `g_settings_apply` would probably make sense for loading presets and loading all settings, if it is practical.

**Comment by p-chan5** [comment]
> Do you think it would be possible to not freeze the UI or have some UI feedback when loading a preset?

I thought I was the only one :O

This happened to me when I `Reset` the settings of an effect or the general ones. Also when I lowered/raised the equalizer bands. As @wwmm said it's a problem with the Flatpak package. if you install it using your distribution's repositories this shouldn't be a problem for low end machines like mine.

It would be great to write a solution for Flatpak friends.

**Comment by p-chan5** [comment]
> Flatpak, It is just 1/2 sec of UX freeze.

In my case it was 5 to 10 seconds. Yes, it was frustrating to edit something at that speed, so I switched to distribution packages.

**Comment by wwmm** [comment]
>I think it was discussed somewhere before, but using g_settings_delay and g_settings_apply would probably make sense for loading presets and resetting all settings, if it is practical.

Unfortunately it isn't. I played with them some years ago. As the function name suggests is just delays the writing operation. It does not make it happen in a background thread. You still have to call `g_settings_apply` and when you do the freezing happens anyway.

**Comment by vchernin** [comment]
From my brief testing with the flatpak build, `g_settings_delay` does seem to help with at least the reset button. By checking for the amount of writes with strace:
`sudo strace -P ~/.var/app/com.github.wwmm.easyeffects.Devel/config/glib-2.0/settings/keyfile -p EASYEFFECTS_PID &> trace.log`

I reliably see exactly 200 `openat` syscalls (along with writes) with master, but 20 with this change when clicking the reset button.
```diff
diff --git a/src/util.cpp b/src/util.cpp
index 8e9f24ae..4d94028b 100644
--- a/src/util.cpp
+++ b/src/util.cpp
@@ -324,6 +324,8 @@ void reset_all_keys_except(GSettings* settings, const std::vector<std::string>&
 
   g_object_get(settings, "settings-schema", &schema, nullptr);
 
+  //g_settings_delay(settings);
+
   keys = g_settings_schema_list_keys(schema);
 
   for (int i = 0; keys[i] != nullptr; i++) {
@@ -332,6 +334,8 @@ void reset_all_keys_except(GSettings* settings, const std::vector<std::string>&
     }
   }
 
+  //g_settings_apply(settings);
+
   g_settings_schema_unref(schema);
   g_strfreev(keys);
 }
@@ -352,3 +356,4 @@ auto str_contains(const std::string& haystack, const std::string& needle) -> boo
 }
 
 }  // namespace util
```

More testing is needed with what to do with other code, but this seems like somewhat of an improvement. Since my system is fairly fast it is hard to say how much this would help on lower hardware, but surely 190 less file opens and subsequent writes would help.

**Comment by wwmm** [comment]
>I reliably see exactly 200 openat syscalls (often along with reads) with master, but 20 with this change when clicking the reset button.

What is quite weird in my opinion considering what this function documentation says
```
Changes the [GSettings](https://github.com/wwmm/easyeffects/issues/GSettings.html) object into 'delay-apply' mode. In this mode, changes to settings are not immediately propagated to the backend, but kept locally until [g_settings_apply()](https://github.com/wwmm/easyeffects/issues/GSettings.html#g-settings-apply) is called.
```
Maybe `kept locally until g_settings_apply is called` has a different meaning in the Flatpak backend... But it should just be doing the same thing later.

In the past when I tested this function we did not try to avoid writings to keys whose value did not actually change. When I tried them with presets that had lots of plugins there was no difference at all to the blocking. I tried now the changes above to the reset function but my system is also fast and I am not using the Flatpak backend. It is hard to say there is any difference at all.

**Comment by vchernin** [comment]
> >Changes the GSettings object into 'delay-apply' mode. In this mode, changes to settings are not immediately propagated to the backend, but kept locally until g_settings_apply() is called.
> 
> 
> 
> Maybe `kept locally until g_settings_apply is called` has a different meaning in the Flatpak backend... But it should just be doing the same thing later.

My interpretation was that on master it will open and read/write the settings file for each key it tries to reset, but with this change it will batch it by only reading the file once, and then check all the keys from the buffer.

Although that is a not a complete explanation since it does do 30, not 1, read syscalls to the file vs 300 on master throughout the test.

**Comment by bhack** [comment]
I don't know if it will solve the freeze but in any case I think that delay is better as we want to have atomicity in the change right?

**Comment by wwmm** [comment]
>but with this change it will batch it by only reading the file once, and then check all the keys from the buffer.

It is not readings but writings that it must be batching as the reset is writing to the keys in the database. The flatpack backend is really dumb... I don't the default backend is doing something like this... In any case it seems this will benefit flatpack users.

>I think that delay is better as we want to have atomicity in the change right?

It is not about atomicity. It is just the flatpack backend being dumb and opening/closing its ini file on every key update. Gsettings runs in the same thread as GTK so there is no data racing or anything else that would benefit from atomic readings/writes.

In general we do not really want a delay. When you load a preset the new parameters values are written to the database. Then gsettings broadcasts this change and it eventually gets to the plugins and the window widgets that are listening to them. A delay when using the default backend just means forcing the the new parameters to take more time to take effect.

**Comment by wwmm** [comment]
>The flatpack backend is really dumb...

By this I meant its default behavior...

**Comment by wwmm** [comment]
I have updated the master branch with calls to `g_settings_apply(settings); ` both in the reset function as well as in the class member that each plugin calls to load its section in the preset file. Not visible difference in the default backend but it is probably going to help the ini file backend used by Flatpak.

**Comment by vchernin** [comment]
> Not visible difference in the default backend but it is probably going to help the ini file backend used by Flatpak.

Doing some testing loading [this preset](https://github.com/Digitalone1/EasyEffects-Presets/blob/1148788e2768170d704fd2de4f7f5053d32f71d4/LoudnessEqualizer.json) and then resetting settings, I see about 47 MB of disk writes on master and about 75 MB with stable according to gnome system monitor. It seems to be a bit faster on my system now that I look more closely too.

**Comment by wwmm** [comment]
>Doing some testing loading [this preset](https://github.com/Digitalone1/EasyEffects-Presets/blob/1148788e2768170d704fd2de4f7f5053d32f71d4/LoudnessEqualizer.json) and then resetting settings, I see about 47 MB of disk writes on master and about 75 MB with stable according to gnome system monitor.

In the default backend the total disk write is smaller than `2 MB` even after loading several presets. This shows how bad this ini backend is.

**Comment by wwmm** [comment]
The current master branch uses `soundtouch` for the pitch plugin instead of rubberband. We can finally close this issue.

![Screenshot from 2023-05-14 20-34-29](https://github.com/wwmm/easyeffects/assets/16225172/b2a67b6b-3222-4fe1-9625-f6a106325a18)


@vchernin some of the automated scripts will need some update. I tried a quick change to one of the ubuntu CI but it did not work :smile:
