### ISSUE TITLE
Latest commits fail to build!

### ISSUE THREAD

**Issue by frkli1965** [wwmm/easyeffects#1952]
Hi,

Latest commits fail to build with the following error...

../src/application.cpp:409:9: error: ‘adw_show_about_window’ was not declared in this scope; did you mean ‘gtk_show_about_dialog’?
  409 |         adw_show_about_window(
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         gtk_show_about_dialog

Also build instructions should be updated where "meson _build --prefix=/usr" is to be replaced with "meson setup build --prefix=/usr" as the former is now deprecated.

Kind regards,

**Comment by wwmm** [comment]
What is the version of the `libadwaita` you have installed in your system? Here on Arch Linux I have the latest stable release `1.2.0` and the code compiles.

**Comment by frkli1965** [comment]
Hi,

As it turns out, I only had v1.1.0 of libawaita-1.so installed so I cloned the latest (v1.3.alpha) from the GitHub repository, and EE not only compiles but runs also.

The OS is Ubuntu 22.04 (Kernel v6.1_rc4) with the latest Sway build (i.e. Wayland) btw so the latest EE should be good for quite a while it seems.

Many thanks for your expeditious response and keep up the great work as always!

Kind regards,

PS. Would you like me to close this issue?
