### ISSUE TITLE
Frequency pointed by mouse on spectrum analyser is wrong

### ISSUE THREAD

**Issue by Neo595** [wwmm/easyeffects#1955]
### EasyEffects Version

6.3

### What package are you using?

Other (specify below)

### Distribution

Ubuntu 22.10

### Describe the bug

Spectrum analyser view
Bounds of the spectrum analyser : 20Hz / 22000Hz
put the mouse on the spectrum analyser window.
Check the frequency reported.
moving the mouse from the left to right, the frequency changes from 20Hz to 200Hz.
![Capture du 2022-11-08 13-12-10](https://user-images.githubusercontent.com/25134439/200637902-752b73d4-9c30-438f-b23b-62074f1f3db3.png)

### Expected Behavior

Report correct frequency according to mouse position
From 20Hz left to 20

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
This has been fixed in EasyEffects `7.0.0`.

**Comment by Neo595** [comment]
Hello,
Thanks. Confirmed.
regards
