### ISSUE TITLE
latency offset ignored when easyeffects service is loaded

### ISSUE THREAD

**Issue by sleeksorrow** [wwmm/easyeffects#1958]
### EasyEffects Version

6.3.0

### What package are you using?

Other (specify below)

### Distribution

Ubuntu 22.10

### Describe the bug

I have a jabra wireless headset with USB dongle that has ~250ms latency without correctly reporting that. I can successfully compensate that issue by setting latency offset manually using pulseaudio controlling cli:
`pactl set-port-latency-offset [card] [output] 250000`

Now as soon as easyeffects has loaded its service, this is being ignored and audio is again 250ms behind the video.

I now can set `set-port-latency-offset` to whatever value I want there is no change in behavior anymore. Even if the destination sink is not easyeffects sink but the headset dongle directly, there is no change. Only when I stop the easyeffects service completely with `easyeffects -q` the setting immediately works again.

### Expected Behavior

Expected behavior would be that the configured latency offset still is respected as configured, no matter if easyeffects service is loaded or not.

### Additional Information

pipewire: 0.3.58
wireplumber: 0.4.12
Jabra Evolve2 65 connected to Jabra Link 380 USB dongle

**Comment by wwmm** [comment]
I think that this issue is somewhere inside the audio server (PipeWire). We don ´t really have control over latency compensation on our side. The most we can do (and is already done) is telling PipeWire each filter latency. From this point on is in PipeWire's hands.

**Comment by sleeksorrow** [comment]
Hm, sad. Well, thank you for looking into this so quickly.

**Comment by wwmm** [comment]
I think it is worth to open an issue in PipeWire's page. I am not sure if this latency offset is supposed to be working with `DSP filters (pw_filter)`
