### ISSUE TITLE
Error with libjack causes some plugins to not work

### ISSUE THREAD

**Issue by rigopoui** [wwmm/easyeffects#1968]
### Problem description
I noticed that the 'Stereo Tools' plugin wasn't working for some reason. No input was being passed through it. Looking at my terminal, I got this output when loading the plugin.

```
(easyeffects:2): easyeffects-WARNING **: 09:50:27.787: 	lv2_wrapper.cpp:225	failed to instantiate http://calf.sourceforge.net/plugins/StereoTools
lilv_lib_open(): error: Failed to open library /app/lib/lv2/calf.lv2/calf.so (/usr/lib/x86_64-linux-gnu/libjack.so.0: undefined symbol: pw_thread_fill_attr)
```

I guess this more likely is a packaging/versioning problem with the flatpak of EasyEffects that I have installed (latest version), but I figured it's worth to open a ticket here in case it's an actual bug.
I have also opened an issue on the `flathub` repo - [link here](https://github.com/flathub/com.github.wwmm.easyeffects/issues/167) feel free to close if you know this only affects the flatpak release.

**Comment by vchernin** [comment]
this is https://github.com/wwmm/easyeffects/issues/1933, a workaround was merged a couple horus ago for the flathub repo, it should show up in `flatpak update` in an hour or two.

**Comment by bhack** [comment]
> /usr/lib/x86_64-linux-gnu/libjack.so.0: undefined symbol: pw_thread_fill_attr

It is trying to find the symbol in the old library so that symbol doesn't exist there. It is in the `libjack.so` version of `pipwire-jack`.

See
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2093#note_1243246

**Comment by vchernin** [comment]
> It is trying to find the symbol in the old library so that symbol doesn't exist there. It is in the libjack.so version of pipwire-jack.

Ah, I should have been able to guess that from the fact it was a libjack in `/usr` which is the runtime pipewire version. Maybe something with pipewire packaging changed in the latest freedesktop runtime or this was always subtly broken but working. I guess just some ldd tweaks will fix this.

**Comment by bhack** [comment]
Wasn't it already intrinsically solved with https://github.com/flathub/com.github.wwmm.easyeffects/pull/165#issuecomment-1303229112 ?

**Comment by vchernin** [comment]
> Wasn't it already intrinsically solved with [flathub/com.github.wwmm.easyeffects#165 (comment)](https://github.com/flathub/com.github.wwmm.easyeffects/pull/165#issuecomment-1303229112) ?

That solves it by updating the bundled pipewire, but issue is that also causes easyeffects to not launch with older versions of the pipewire daemon. #1976 is the proper fix which just ensured lilv finds the right libjack path while keeping existing systems working.

**Comment by wwmm** [comment]
I imagine we can close this issue.
