### ISSUE TITLE
Disabling "Process all Output Streams" breaks functionality

### ISSUE THREAD

**Issue by aleasto** [wwmm/easyeffects#1980]
### EasyEffects Version

6.3.0

### What package are you using?

Fedora

### Distribution

Fedora 36

### Describe the bug

Disabling "Process all Output Streams" causes enabled streams to hang until I open `pavucontrol` or the `Plasma PulseAudio applet` or just change the system volume through a macro

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(easyeffects:14939): easyeffects-DEBUG: 00:32:59.215:   pipe_manager.cpp:1149   Stream/Output/Audio 157 Firefox with serial 870 has been added
(easyeffects:14939): easyeffects-DEBUG: 00:32:59.221:   pipe_manager.cpp:895    new metadata property: 157, target.node, Spa:Id, 152
(easyeffects:14939): easyeffects-DEBUG: 00:32:59.222:   pipe_manager.cpp:1189   Firefox port 140 is connected to alsa_output.usb-SteelSeries_SteelSeries_Arctis_9_000000000000-00.stereo-game port 47
(easyeffects:14939): easyeffects-DEBUG: 00:32:59.222:   pipe_manager.cpp:1189   Firefox port 109 is connected to alsa_output.usb-SteelSeries_SteelSeries_Arctis_9_000000000000-00.stereo-game port 49
(easyeffects:14939): easyeffects-DEBUG: 00:33:04.536:   stream_output_effects.cpp:165   No app linked to our device wants to play. Unlinking our filters.
```
-- Here I send `KEY_VOLUMEDOWN`
```
(easyeffects:14939): easyeffects-DEBUG: 00:33:06.796:   pipe_manager.cpp:895    new metadata property: 180, target.node, Spa:Id, -1
(easyeffects:14939): easyeffects-DEBUG: 00:33:06.797:   pipe_manager.cpp:1189   Firefox port 140 is connected to easyeffects_sink port 70
(easyeffects:14939): easyeffects-DEBUG: 00:33:06.797:   pipe_manager.cpp:1189   Firefox port 109 is connected to easyeffects_sink port 69
(easyeffects:14939): easyeffects-DEBUG: 00:33:06.799:   stream_output_effects.cpp:156   At least one app linked to our device wants to play. Linking our filters.

```
</details>

**Comment by wwmm** [comment]
>Disabling "Process all Output Streams" causes enabled streams to hang until I open pavucontrol or the Plasma PulseAudio applet or just change the system volume through a macro

This does not make sense. If `process all outputs` is disabled the only thing that is going to happen is that EasyEffects is not going to try to move streams to its virtual devices. In other words EasyEffects is not going to touch the stream. Are you sure the streams are hanging?

```
(easyeffects:14939): easyeffects-DEBUG: 00:32:59.222:   pipe_manager.cpp:1189   Firefox port 140 is connected to alsa_output.usb-SteelSeries_SteelSeries_Arctis_9_000000000000-00.stereo-game port 47
(easyeffects:14939): easyeffects-DEBUG: 00:32:59.222:   pipe_manager.cpp:1189   Firefox port 109 is connected to alsa_output.usb-SteelSeries_SteelSeries_Arctis_9_000000000000-00.stereo-game port 49
(easyeffects:14939): easyeffects-DEBUG: 00:33:04.536:   stream_output_effects.cpp:165   No app linked to our device wants to play. Unlinking our filters.
```

This is the expected behavior. If there is no active stream connected to its virtual device EasyEffects will unlink its filters to make sure no CPU power is wasted processing silence.

**Comment by aleasto** [comment]
Yea I'm sure :stuck_out_tongue: 
It is not reproducible on every boot, i'm not sure what circumstances triggers it yet.

I have Process all Output Streams disabled, and on top of it I enable Firefox in the Output list (i imagine easyeffects keeps a whiltelist of processes?)
In the Debug log, the YouTube video on Firefox would keep loading and the "Enabled" checkbox of the Firefox stream in easyeffects is unticked. Only after I send KEY_VOLUMEDOWN (or open pavucontrol or plasma-pa) the checkbox becomes ticked and video immediatly starts playing, and the audio is processed by easyeffects as i want.

The issue is not limited to Firefox, but it was what i used to gather the log.

**Comment by wwmm** [comment]
>i imagine easyeffects keeps a whiltelist of processes?

No. There isn't a whitelist. If `Process All Outputs` is enabled EasyEffects will try to move all audio streams to its virtual devices. Sometimes people want that for everything except a few streams. That is where the blocklist is useful. You can exclude some streams from this behavior. 

When `Process All Outputs` is disabled you will only have effects for a stream if you manually put the `Enable` checkbox in the active state. In any case "enabled" means that the stream was moved to EasyEffects virtual device. Not necessarily EasyEffects is the one doing that. Programs like Pavucontrol can do this and even PipeWire may move the stream to our virtual device when its "last used device restoration" policy is applied.

>Only after I send KEY_VOLUMEDOWN (or open pavucontrol or plasma-pa) the checkbox becomes ticked and video immediatly starts playing, and the audio is processed by easyeffects as i want.

I have never seen something like this happening. I wonder if it is some weird interaction with Plasma. It does not make sense at all that the video does not start. From the player point of view it is just playing audio to a `null sink`. It does not matter if it is an EasyEffects null sink. It should behave the same way for all of them. I can see situations where you may not have sound while the video is playing. But the video no starting feels like some kind of major problem somewhere outside of EasyEffects.

**Comment by aleasto** [comment]
Screen recording of what happens:
You can see the when first hitting play Spotify appears in the stream list, and is disabled, but nothing happens.
Only after i change volume (see the plasma volume OSD appearing) the stream becomes enabled and starts.

https://user-images.githubusercontent.com/8167495/201759495-502c077e-19d5-4ec9-a7bf-31b0c38755ed.mp4

**Comment by aleasto** [comment]
Got perhaps a new good bit of information:
While the stream is stuck, pavucontrol says "Unknown output" for that stream.

**Comment by wwmm** [comment]
>While the stream is stuck, pavucontrol says "Unknown output" for that stream.

Something odd is happening in your PipeWire installation. The only situation where `Unknown output` should be happening is when an output device that can not be recognized by `Pulseaudio clients` is being used. As Pavucontrol is not able to identify native PipeWire objects it shows this message. But the null sink created by EasyEffects is configured to be visible to Pulseaudio clients. 

This delay is also far from normal. I think it is worth looking at PipeWire logs.

**Comment by aleasto** [comment]
Hi, sorry for the big delay but I finally reproduced the issue again and found the following `wireplumber` log:
```
dic 06 12:07:38 zero wireplumber[7238]: <WpSiStandardLink:0x556262bcdca0> Link was not activated before removing
dic 06 12:07:38 zero wireplumber[7238]: <WpSiStandardLink:0x556262bcdde0> Failed to create links because of wrong ports
```
Which when googled shows a bunch of wireplumber+easyeffects issues like mine. For example, https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/346 or https://github.com/wwmm/easyeffects/issues/1809

**Comment by aleasto** [comment]
Looks like this was triaged upstream and should be fixed in an upcoming release https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/369

**Comment by aleasto** [comment]
Also this you were commenting on is the same issue: https://github.com/Audio4Linux/JDSP4Linux/issues/74#issuecomment-1301507802
