### ISSUE TITLE
Can't build 7.0.0

### ISSUE THREAD

**Issue by Vascom** [wwmm/easyeffects#1985]
### EasyEffects Version

7.0.0

### What package are you using?

Fedora

### Distribution

Fedora Rawhide

### Describe the bug

Can't build.
```
../src/echo_canceller.cpp:153:28: error: ‘state_left’ was not declared in this scope
  153 |       speex_preprocess_run(state_left, data_L.data());
      |                            ^~~~~~~~~~
../src/echo_canceller.cpp:153:7: error: ‘speex_preprocess_run’ was not declared in this scope
  153 |       speex_preprocess_run(state_left, data_L.data());
      |       ^~~~~~~~~~~~~~~~~~~~
../src/echo_canceller.cpp:154:28: error: ‘state_right’ was not declared in this scope
  154 |       speex_preprocess_run(state_right, data_R.data());
      |                            ^~~~~~~~~~~
```

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Probably because `speex` is not installed. In any case speex is supposed to be an optional dependency. But in these 2 particular lines I forgot to add an #ifdef to disable these function calls when speex is not available. I will fix this later today.

**Comment by hch12907** [comment]
Those lines are missing an ifdef guard. As a workaround, install `speex` with dnf.

**Comment by Vascom** [comment]
Thanks.
I added `pkgconfig(speex)` as build dependency.

**Comment by wwmm** [comment]
Our master branch now has the missing #ifdef.
