### ISSUE TITLE
Default Output doesn't update when device is connected

### ISSUE THREAD

**Issue by Nathorr** [wwmm/easyeffects#1989]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

When default output device, for example USB DAC, is disconnected, EasyEffect's default output device on Pipewire tab changes automatically to the new default one. When the same device is connected again the default device doesn't get updated before switching "Use Default Output" off and on again.

Step-by-step

1. Disconnect default audio output device. Result: EasyEffect's default output device on Pipewire tab changes to something else.
2. Connect that same output device back again. Result: EasyEffect's default output device on Pipewire tab doesn't change back to the connected device even though it is selected as a default one. Switching "Use Default Output" off and on again updates the device to the correct one.

### Expected Behavior

On default device connection EasyEffect's default output device would update correctly without the need of switching Use Default Output off and on again.

### Additional Information

This is useful feature if you're using multiple laptop or desktop devices sharing the same output device via USB switch.

**Comment by wwmm** [comment]
As far as I could see the audio plays to where it is supposed to be. It is just the dropdown in the window not being updated to the current default device.

**Comment by Nathorr** [comment]
You are correct. For some reason I thought it wasn't the case. So, just a minor enhancement. Thanks!

**Comment by wwmm** [comment]
Fixed in our master branch.
