### ISSUE TITLE
Improve Speex UI

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1990]
![image](https://user-images.githubusercontent.com/25790525/202189107-9944388f-04c0-4fe4-936b-46a1e5946916.png)

Since we have quite all effects centered, why is this aligned at the left?

@wwmm What do you think? Is it better to center horizontally the grids at the top?

**Comment by wwmm** [comment]
I think I forgot to try a centered alignment to see how it would look. I don't think I will have time today to test this. If you have and it seems better to have they centered you can make a PR.

**Comment by Digitalone1** [comment]
When I have time, I will.

**Comment by wwmm** [comment]
I think we can close this issue.
