### ISSUE TITLE
EasyEffects cannot launch after install on Arch

### ISSUE THREAD

**Issue by Lukas-drz** [wwmm/easyeffects#2003]
### EasyEffects Version

7.0.0-1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Terminal output : Failed to register
KDE output : Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

### Expected Behavior

Launch :D
You have the journalctl log below

### Debug Log

nov. 21 17:40:43 ryzen3600 audit[4816]: USER_END pid=4816 uid=1000 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
nov. 21 17:40:43 ryzen3600 audit[4816]: CRED_DISP pid=4816 uid=1000 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
nov. 21 17:40:43 ryzen3600 kernel: audit: type=1106 audit(1669048843.022:147): pid=4816 uid=1000 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
nov. 21 17:40:43 ryzen3600 kernel: audit: type=1104 audit(1669048843.022:148): pid=4816 uid=1000 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
nov. 21 17:40:45 ryzen3600 plasmashell[843]: kf.sonnet.core: No language dictionaries for the language: "en_US"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: Could not find the Plasmoid for Plasma::FrameSvgItem(0x55dc7fb36490) QQmlContext(0x55dc7f50fd40) QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml")
nov. 21 17:41:11 ryzen3600 plasmashell[843]: Could not find the Plasmoid for Plasma::FrameSvgItem(0x55dc7fb36490) QQmlContext(0x55dc7f50fd40) QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml")
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationItem.qml:221:21: QML SelectableLabel: Binding loop detected for property "implicitWidth"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationItem.qml:221:21: QML SelectableLabel: Binding loop detected for property "implicitWidth"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationItem.qml:221:21: QML SelectableLabel: Binding loop detected for property "implicitHeight"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/lib/qt/qml/org/kde/plasma/components.3/ScrollView.qml:45:27: QML ScrollBar: Binding loop detected for property "visible"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/lib/qt/qml/org/kde/plasma/components.3/ScrollView.qml:45:27: QML ScrollBar: Binding loop detected for property "visible"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/SelectableLabel.qml:38:5: QML TextArea: Binding loop detected for property "implicitHeight"
nov. 21 17:41:11 ryzen3600 plasmashell[843]: file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationItem.qml:221:21: QML SelectableLabel: Binding loop detected for property "implicitWidth"
nov. 21 17:41:12 ryzen3600 dbus-daemon[513]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.151' (uid=0 pid=4826 comm="sudo journalctl")
nov. 21 17:41:12 ryzen3600 dbus-daemon[513]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service': Unit dbus-org.freedesktop.home1.service not found.
nov. 21 17:41:12 ryzen3600 sudo[4826]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
nov. 21 17:41:12 ryzen3600 audit[4826]: USER_ACCT pid=4826 uid=1000 auid=1000 ses=2 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="lukas" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
nov. 21 17:41:12 ryzen3600 kernel: audit: type=1101 audit(1669048872.932:149): pid=4826 uid=1000 auid=1000 ses=2 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="lukas" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
nov. 21 17:41:12 ryzen3600 sudo[4826]:    lukas : TTY=pts/1 ; PWD=/home/lukas ; USER=root ; COMMAND=/usr/bin/journalctl
nov. 21 17:41:12 ryzen3600 audit[4826]: CRED_REFR pid=4826 uid=1000 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_env,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
nov. 21 17:41:12 ryzen3600 sudo[4826]: pam_unix(sudo:session): session opened for user root(uid=0) by lukas(uid=1000)
nov. 21 17:41:12 ryzen3600 audit[4826]: USER_START pid=4826 uid=1000 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
nov. 21 17:41:12 ryzen3600 kernel: audit: type=1110 audit(1669048872.933:150): pid=4826 uid=1000 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_env,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
nov. 21 17:41:12 ryzen3600 kernel: audit: type=1105 audit(1669048872.933:151): pid=4826 uid=1000 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
nov. 21 17:41:13 ryzen3600 kwin_x11[705]: kwin_core: XCB error: 152 (BadDamage), sequence: 7767, resource id: 16792885, major code: 143 (DAMAGE), minor code: 3 (Subtract)

**Comment by wwmm** [comment]
This seems more like a KDE problem. In any case follow the step number 3 in our basic logs section https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs to run easyeffects in debug mode.

**Comment by Lukas-drz** [comment]
I have KDE on my laptop running EndeavorOS (Arch based) and it's working...
The flatpak package do not work as well on this desktop computer running Arch...
The command easyeffects -q returns only a timeout : failed to register.
It's probably a KDE problem with this app but I have no idea what.

**Comment by Lukas-drz** [comment]
Okay it's working now and it was not a KDE problem !
It took me a while to see it.
I had pulseaudio installed and running and pipewire
I installed pipewire-pulse and it works juste fine now...
Sorry
