### ISSUE TITLE
Effects do not work on pause/song skip

### ISSUE THREAD

**Issue by CHJ85** [wwmm/easyeffects#2010]
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu

### Describe the bug

Now that I'm using Pipewire with EasyEffects, the audio goes away for a second whenever i skip the song. No reverb fade out or anything. Very annoying. Could you look into this please?

### Expected Behavior

Back when I used Pulseaudio with PulseEffects, I would use the Reverb effect to let songs that I play fade on pause or transition on skip.

### Possible workaround

If it's not fixable, then perhaps adding support for the pipewire-pulse daemon in PulseEffects would solve the problem?

### Additional Information

I'm using Rhythmbox btw.

**Comment by wwmm** [comment]
>the audio goes away for a second whenever i skip the song

Which plugins are enabled in EasyEffects? I haven't seen something like this in at least a year. The only thing I can think of is that for some reason PipeWire is using a very large latency in your computer when Rhythmbox is running. The command `pw-top` should help to see if that is the case.

>adding support for the pipewire-pulse daemon in PulseEffects would solve the problem?

No. It doesn't even make sense to use it in EasyEffects code. If too high latency is not the reason why the problem is happening something else at the server level is not right. There isn't really much that can be done on EasyEffects side.

**Comment by CHJ85** [comment]
There aren't many plugins enabled. The reverberation and the compressor. But I tried a whole bunch of different presets, so I doubt that it's a plugin thing.

**Comment by wwmm** [comment]
>There aren't many plugins enabled. The reverberation and the compressor.

Reverberation through the reverb plugin or the convolver? In any case they should not latency. Take a print of the pw-dot output while you are playing something. 

>When I press pause, the audio stops immediately without fading out the reverb, which is fine in this instance because it's a video. But it's not the expected behavior.

There is not fading in EasyEffects (PulseEffects also did not have it).

**Comment by CHJ85** [comment]
Yes PulseEffects did have fading. The stronger reverb, the longer the fade. It didn't irrupt once I pressed pause or stop.

**Comment by CHJ85** [comment]
Okay so where do I find the pw-top?
And I'm not sure if you understand what I mean by "fading". I don't mean the audio is fading out. But the reverb effect is fading out. And that's what I want EasyEffect doing as well. But like I said, EasyEffect's behavior is that the audio completely erupts once I press pause or stop.
Would there be a way to implement this into EasyEffects?

**Comment by wwmm** [comment]
>Okay so where do I find the pw-top?

It should be available in the terminal. At least on Arch Linux once PipeWire is installed this command is available.

>I don't mean the audio is fading out. But the reverb effect is fading out.

Uhm... I think I will need to see a video showing what you want. 

>Would there be a way to implement this into EasyEffects?

Things were quite different in PulseEffects. The effects PipeWire was handled through GStreamer. While in PipeWire it is done through native PipeWire filters `pw_filter`. In PulseEffects we paused the effects pipeline when no audio app was active. In PipeWire the only thing that can be done is unlinking the filters. So the whole thing is completely different and buffers can be lost along the way. I do not think there is a way to make the behavior the same.

**Comment by CHJ85** [comment]
> It should be available in the terminal. At least on Arch Linux once PipeWire is installed this command is available.
I'm on Ubuntu actually.
> Uhm... I think I will need to see a video showing what you want.
I'll see if I can put a video together.
But you know in PulseEffects, if you enabled reverb, you'd still hear a little bit of reverb for a short second after you pause a song or whatever audio source. Well. In EasyEffects, it doesn't. It just erupts right away. This sounds bad when you're listening to music because when the song ends and the next one begins, there's a short few milliseconds of no sound before the next song starts, including a half a second of reverb from the previous song.
And to me, this sounds like a bug because the transmission should be seamless.

**Comment by wwmm** [comment]
>This sounds bad when you're listening to music because when the song ends and the next one begins, there's a short few milliseconds of no sound before the next song starts, including a half a second of reverb from the previous song.

Is there any change if you increase the `Inactivity Timout` in EasyEffects preferences window?

**Comment by CHJ85** [comment]
Nope. Tried that already. It's set to 150s now, which should be quite sufficient.
Anyway, here's the pw-top: https://imgur.com/a/RDK9s0L

**Comment by wwmm** [comment]
>Nope. Tried that already. It's set to 150s now, which should be quite sufficient.

I see. HIgher timout means that EasyEffects will take longer to unlink its filters. What usually results in CPU power wasted processing silence. If this has no effect one possibility is that PipeWire is stopping sending additional buffers by itself once the audio player is paused. I doubt there is something we can do about this from our side.

>Anyway, here's the pw-top: https://imgur.com/a/RDK9s0L

Based on this image PipeWire is using a latency equal to `256 / 48000 = 0.005` seconds. Five milliseconds is a low value when considering everyday usage. I wonder what would happen if you forced a larger quantum value like `1024`. As Pulseaudio is a high latency server and GStreamer introduced even more latency on top of it my guess is that in the past you had no less than `50 ms` or even `100 ms` of latency when running PulseEffects.

**Comment by CHJ85** [comment]
And when you say there's nothing you can do about this, you mean that this is something that the PipeWire team needs to be informed about? This bug is basically on their end?

**Comment by wwmm** [comment]
>I see. So how do I force a larger quantum value?

Take a look at the `quantum range` section of this page https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#quantum-ranges. There are ways to make the change permanent too. But I would first to use the temporary approach to see if it will really help to improve the situation.

>And when you say there's nothing you can do about this, you mean that this is something that the PipeWire team needs to be informed about? This bug is basically on their end?

Yes. Assuming I understood what you are trying to do I think it is hard to implement it without changes in the server. There isn't really much that can be controlled from the client (EasyEffects) side. We are already delaying the filters unlinking. If even so the buffers end abruptly only in the server something can be done about it. But if you do open an issue there it is probably a good idea to show a video with the current and desired behavior. Once you do paste the link to the issue here so I can follow it there. 

I am not sure it is a bug in the usual meaning of the word. It is how things are. And at least on my current hardware I do not really notice this problem. So it may be tricky for PipeWire developers "to fix it".

**Comment by CHJ85** [comment]
I see. I'll put together a video explaining things better.
Thank you so much for all your help. 👍

**Comment by CHJ85** [comment]
Hi again. I figured out what the problem is. Upon further testing, I realize that this only happens whenever my bluetooth headphones are plugged in. I discovered this during my video recording actually.
So I looked at the volume controls. My headphones were set to "A2DP Sink, codec LDAC". Setting this to "codec SBC" kinda solved the issue. I'm getting the normal behavior now but with some crackling noises.
So I'm thinking that this is just one of these bugs that'll eventually be fixed down the line. I mean, PipeWire is relatively new to the game and nowhere near ready prime time (in a lot of areas).

**Comment by wwmm** [comment]
>Upon further testing, I realize that this only happens whenever my bluetooth headphones are plugged in

Bluetooth devices always have some kind of unexpected behavior... Unbelievable... But it is the first time I see them doing something like this. Good to know.

>I'm getting the normal behavior now but with some crackling noises.

Is `pw-top` still showing a quantum size related to very low latency? Crackling noises are sometimes caused by latency values too low for the hardware capabilities. If you force a higher value they may go away.

**Comment by CHJ85** [comment]
I tried setting it to 1024. Not sure if that did anything as far as this annoying bug.
But I honestly have faith in the Pipewire team that they'll fix this down the road. 
If you'd be willing to let em know about this, that'll be great. I'm obviously not a developer nor a programmer, so I wouldn't be able to provide with much. Because this is definitely something that needs to be looked into.

**Comment by wwmm** [comment]
>If you'd be willing to let em know about this, that'll be great. I'm obviously not a developer nor a programmer, so I wouldn't be able to provide with much. Because this is definitely something that needs to be looked into.

No problems. As I do not have a working bluetooth device at this moment I can't do any test about this. So it is not going to be productive if I am the one reporting the bug. In any case they actively work in the bluetooth layer. There is a good chance indeed that this will be improved even without reporting the problem.
