### ISSUE TITLE
Feature request: GraphicEQ from AutoEQ support

### ISSUE THREAD

**Issue by Cpt-Dingus** [wwmm/easyeffects#2020]
While EasyEffects already supports AutoEQ presets, it only supports the ParametricEQ (10 band) setting, not the much more precise GraphicEQ preset (~127 bands). 

GraphicEQ import support was also added in 7.0, but the base EQ is capped at 32 bands, not enough to fit the comparatively massive 127 bands.

Perhaps support could be achieved making a separate effect that is made solely for an AutoEQ preset?

**Comment by wwmm** [comment]
>Perhaps support could be achieved making a separate effect that is made solely for an AutoEQ preset?

Do you mean doing something that would support 127 bands? This is impossible because the equalizer from Linux Studio Plugins we use has only 32 bands. A whole new equalizer plugin with 127 would be needed. There is no way to combine 32 bands equalizer instances to support 127.

**Comment by Cpt-Dingus** [comment]
That is what I had in mind, however if it requires a major inner-workings change then it probably isn't worth it I guess. 
Asked as this would be a game changer for EasyEffects (at least in my book), as no other Linux EQs support AutoEQ.

**Comment by Cpt-Dingus** [comment]
Forgot to close.
