### ISSUE TITLE
Importing impulse to convolver freezes the whole system UI

### ISSUE THREAD

**Issue by AlexSleepy** [wwmm/easyeffects#2032]
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_OS 22.04 LTS

### Describe the bug

(I'm not 100% it's Flatpak, I've installed it from Pop!_Shop, and can't find if it comes from the Flatpak, but most likely it is)

When I try to import an impulse response to convolver, the whole system UI becomes unresponsive

Steps to reproduce:
- Go to effects tab and add a convolver
- Select Impulses -> Import Impulse
- See that file browser is open, but Impulses panel is displayed over it, and system doesn't react to any clicks or keyboard shortcuts (but sound continues to play normally if that matters)

I was able to switch to the new console (ctrl+alt+f3) and kill the EasyEffects process

### Expected Behavior

file browser should let import impulse responses without freezing the whole UI

**Comment by wwmm** [comment]
This is a `gtk4` bug that happens mostly on systems using `x11`. OR at least here on my computer with gnome + wayland I have never seen it. You can see more details at #1179. Only gtk's developers can really o something about this.
