### ISSUE TITLE
Primary menu item groupings

### ISSUE THREAD

**Issue by bertob** [wwmm/easyeffects#2034]
The [HIG recommends](https://developer.gnome.org/hig/patterns/controls/menus.html) grouping Preferences, Keyboard Shorcuts, Help, and About $APP together at the bottom of the primary menu.

![image](https://user-images.githubusercontent.com/1908896/207578516-671c89ac-c873-4552-88ed-107c3abf5f7c.png)

Example from Text Editor:

![image](https://user-images.githubusercontent.com/1908896/207579029-a1bc62d5-9ca2-4ed7-aafe-4c27c4a720c1.png)

**Comment by wwmm** [comment]
Implemented in our master branch.
