### ISSUE TITLE
easyeffects returns 1 (failure) on succesful commands

### ISSUE THREAD

**Issue by jn64** [wwmm/easyeffects#2035]
### EasyEffects Version

6.3.0

### What package are you using?

Fedora

### Distribution

Fedora 37

### Describe the bug

Using easyeffects CLI returns 1 when it succeeds on certain commands. I did not test all, but at least the following:

- `easyeffects -b 1`
- `easyeffects -b 2`
- `easyeffects -w`

### Expected Behavior

Return 0 on successful commands.

Return > 0 only on failure.

### Additional Information

Refer to [Exit Status (Bash Reference Manual)](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html)

**Comment by wwmm** [comment]
Some people noticed this before #978. The problem is that we do not have control over the return value. That is being handled by gtk as we have to return `G_APPLICATION_CLASS(application_parent_class)->command_line(gapp, cmdline);`. I am not aware of a way to properly bypass what gtk is deciding to return.

**Comment by jn64** [comment]
No other GTK application has this issue.

**Comment by wwmm** [comment]
>No other GTK application has this issue.

This means nothing. Almost no gtk application runs using gtk service mode like easyeffects has to do. When you run easyeffects with a command line option you probably have another easyeffects instance already running in the background. It is up to gtk to ensure that the service instance running in the background stays alive while the new instance executed to handle the command line option dies. It is after killing this new instance that the return value you do not desire is returned by gtk.

**Comment by wwmm** [comment]
I have updated our master branch replacing the call to `G_APPLICATION_CLASS(application_parent_class)->command_line(gapp, cmdline);` by `return EXIT_SUCCESS;` in some places. If this does not fix this problem I do not know what else could be done.
