### ISSUE TITLE
Muting easyeffects input doesn't work

### ISSUE THREAD

**Issue by Eyenseo** [wwmm/easyeffects#2038]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

arch

### Describe the bug

Muting easy effects input stream via pavucontrol doesn't mute easy effects - it continues to route the audio. 
```
No mute: Mic -> EE -> Discord/Application/...
Mute EE: Mic -> EE -> Discord/Application/...
Mute Mic: Mic -/> EE -/> Discord/Application/...
```

### Expected Behavior

Muting easy effects mutes it's stream and nothing can be heard.
```
Mute EE: Mic -> EE -/> Discord/Application/...
```

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Long story short we do not force these controls to be enabled anymore because they were an endless source of headaches for many people that did not even needed them. More details at #1817.
