### ISSUE TITLE
Installing Flatpack version 7.0 ends up installing version 6.3

### ISSUE THREAD

**Issue by luisalvarado** [wwmm/easyeffects#2039]
### EasyEffects Version

7.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.10

### Describe the bug

I am trying to install version 7 and every time I do it via flatpack it ends up installing version 6.3

### Expected Behavior

It should install version 7 I would believe.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Where does it say version 6.3? `flatpak install flathub com.github.wwmm.easyeffects` installs version 7 for me.

**Comment by luisalvarado** [comment]
no, just that one. It says 6.3 when I got to the about section inside of it. Here:

![image](https://user-images.githubusercontent.com/29236/208322603-3529412a-463e-4e75-a66d-aa943e5582d9.png)

**Comment by vchernin** [comment]
Can you try launch with `flatpak run com.github.wwmm.easyeffects`

**Comment by luisalvarado** [comment]
@vchernin it was the same thing, but get this. I turned off the computer and went to bed. Got up again, started easyeffects again and guess what, it is 7.0 So the computer needed reboot to show the new one? Is there like a cache or temp easyeffects folder in flatpak I was not aware of?

**Comment by wwmm** [comment]
>If so the existing instance will continue running until it is quit.

This is probably what happened.

>Is there like a cache or temp easyeffects folder in flatpak I was not aware of?

It is not a cache but the service instance running in the background. When easyeffects is executed again while an instance is already running gtk will show our window if no command line option was given and automatically finish the new instance that has been started.

**Comment by luisalvarado** [comment]
Ohhhh thanks. Yes that has to be it. Thank you friends.
