### ISSUE TITLE
LSP 1.2.4: Min and Max sidechain sources

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2042]
New LSP version out: https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.4

I see from the changelog:
- Added 'Min' and 'Max' sidechain sources for single-band and multiband dynamic processing plugins: Compressor, Dynamic Processor, Expander, Gate.

Should this be exposed in EE too?

**Comment by wwmm** [comment]
>Should this be exposed in EE too?

Although I do not know yet exactly what these new sources are doing differently I think we should expose them.

Changing the topic slightly I have already implemented listview in the equalizer. But I did not have time to put sorting in place yet. To my surprise the performance was still disappointing... It seems that the amount of widgets in each band is so large that creating many of them is super heavy and there is nothing we can do about it =/. In any case it makes more sense using listview since gtkbox in more for static children.

**Comment by Digitalone1** [comment]
> > Should this be exposed in EE too?
> 
> Although I do not know yet exactly what these new sources are doing differently I think we should expose them.
> 
> Changing the topic slightly I have already implemented listview in the equalizer. But I did not have time to put sorting in place yet. To my surprise the performance was still disappointing... It seems that the amount of widgets in each band is so large that creating many of them is super heavy and there is nothing we can do about it =/. In any case it makes more sense using listview since gtkbox in more for static children.

I'm contributing to another project that needs more effort to grow. EE is quite complete in the current state, it only needs maintenance (in my opinion). Don't know if I have the time to look at it but, anyway, we already have the sorting algorithm, so the listview could stay with che current implementation.

**Comment by wwmm** [comment]
>I'm contributing to another project that needs more effort to grow. EE is quite complete in the current state, it only needs maintenance (in my opinion). Don't know if I have the time to look at it but, anyway, we already have the sorting algorithm, so the listview could stay with che current implementation.

No problems :-). I think that until the end of the year I will have enough free time to add these new controls.

**Comment by sadko4u** [comment]
`Min` selects absolute minimum sample value between two channels in a stereo channel, `Max` does the opposite.

**Comment by wwmm** [comment]
>Min selects absolute minimum sample value between two channels in a stereo channel, Max does the opposite.

Thanks! :-)

**Comment by wwmm** [comment]
Assuming I did not make any mistake this is implemented in our master branch.

**Comment by LebedevRI** [comment]
Thank you! (I was actually surprised that these didn't exist in LSP originally.)
