### ISSUE TITLE
Refuses to load at startup on Linux Mint.

### ISSUE THREAD

**Issue by DarkAlchy** [wwmm/easyeffects#2067]
### EasyEffects Version

7.0.0

### What package are you using?

Other (specify below)

### Distribution

Linux Mint

### Describe the bug

![image](https://user-images.githubusercontent.com/10561690/211183909-59939841-4e9e-4976-ab61-1183250b412b.png)
Did what it asked, even rebooted to no avail.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
What desktop environment are you using? I recall some users on linux mint had success by installing `xdg-desktop-portal-gnome` with `--no-install-recommends` and then rebooting.

**Comment by DarkAlchy** [comment]
XFCE.

**Comment by violetmage** [comment]
Is the issue resolved?

If not, what is the output of this command:
`flatpak permissions`

**Comment by DarkAlchy** [comment]
Never was resolved and I since stopped using Linux just too many bad things like this over using Windows.
