### ISSUE TITLE
Equalizer is not processing dsd over pcm 

### ISSUE THREAD

**Issue by citral23** [wwmm/easyeffects#2069]
### EasyEffects Version

7.0.0

### What package are you using?

Other (specify below)

### Distribution

Debian testing

### Describe the bug

I have an apo equalizer for my SHP9500, and no matter what player I use (mpv, rhtythmbox, audacious) or dac (topping e30, hidizs s9 pro) the sound doesn't make it through the EQ when playing DSD because the freq is too high.

Staying in the same player and switching to a flac file, it instantly passes through

I have default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 352800 384000 705600 768000 ] and see on the topping that it's playing at 352.8 khz, 192khz for the same song in flac

### Expected Behavior

I would expect the equalizer to treat the signal as any other PCM one

### Debug Log

[ERR] Unsupported sample rate: 352800.000000, maximum supported sample rate is 192000

### Additional Information

Workaround : 
Limit the max rate to 192khz, tested working. There's no way to tell a difference as far as human hearing is concerned, I'm just lazy to convert files so it's not really an issue, just a FYI

**Comment by wwmm** [comment]
>Unsupported sample rate: 352800.000000, maximum supported sample rate is 192000

From where exactly is this warning coming? Show me what is being printed in the terminal before and after it. Inside EasyEffects we do not force a sampling rate restriction in most of the plugins. As the Equalizer is from the `Linux Studio Plugins` project we have to figure if the plugin is the one with an upper rate value or if PipeWire is forcing this restriction for some reason.

**Comment by wwmm** [comment]
What is the version of the Linux Sutdio Plugin package on your system? Based on this https://github.com/sadko4u/lsp-plugins/blob/cd5cf1ebfb9037882432c8cd817e821642c80290/CHANGELOG#L25 you will need at least lsp `1.2.4` to have 384 kHz support in the equalizer. But unless they add support for higher rates 384 kHz is the highest you will have.

**Comment by citral23** [comment]
Sorry missed the last line that has additional info :

citral@miles:~$ easyeffects 

(easyeffects:13344): Adwaita-WARNING **: 19:10:33.775: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:339 spa_pod_get_array()
[ERR] Unsupported sample rate: 352800.000000, maximum supported sample rate is 192000

(easyeffects:13344): easyeffects-WARNING **: 19:10:56.113: 	lv2_wrapper.cpp:225	failed to instantiate http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr

**Comment by citral23** [comment]
ii  lsp-plugins-lv2                         1.1.31-3                          amd64        LSP (Linux Studio Plugins) audio-plugins (LV2 plugins)

I guess you can mark it as closed then as it's outside of your scope

**Comment by wwmm** [comment]
>I guess you can mark it as closed then as it's outside of your scope

Yes. I do not know the reasons why the maximum rate used by LSP plugins is fixed at 384 kHz but we definitely can not do something about this in EasyEffects code.

**Comment by sadko4u** [comment]
> Yes. I do not know the reasons why the maximum rate used by LSP plugins is fixed at 384 kHz but we definitely can not do something about this in EasyEffects code.

Because for some plugins that defines the overall allocated memory size for buffers. And, the counter-question is: what's the purpose of using such high sample rates?
