### ISSUE TITLE
EasyEffects - System wide presets

### ISSUE THREAD

**Issue by anathonous** [wwmm/easyeffects#2073]
Hello,
I am using laptop-mode-tools and have a custom exec setup to load and unload presets when booting the system and to change execs on docking and undocking. I was wondering where I could place EasyEffects preset files so that when setting profiles it works properly.

This may be of issue as pipewire isn't running as system service. Maybe i should be using pipewire as a systemservice with easyeffects as a systemservice aswell.

Might you have any insights on how to get this to work properly?

**Comment by wwmm** [comment]
>I was wondering where I could place EasyEffects preset files so that when setting profiles it works properly.

Preset files have to be inside `~/.config/easyeffects/output/` or `~/.config/easyeffects/input/` depending on whether they are for speakers or microphones. Once they are there you can run `easyeffects -l preset_name` to activate the desired preset.

>This may be of issue as pipewire isn't running as system service. Maybe i should be using pipewire as a systemservice with easyeffects as a systemservice aswell.

This may be a problem indeed. EasyEffects is a desktop application. It just pretends to run as a service in the background by hiding its window. As result it can only be started once your desktop is initialized. If latptop-mode-tools does something once EasyEffects is already running things will be fine. The command I showed above will work. But when the system boots laptop-mode-tools will probably do some things before your desktop is loaded.

**Comment by anathonous** [comment]
I think laptop-mode tools runs as a root service. so execs are processed as
root.
