### ISSUE TITLE
No effects are being utilized other than the volume in PulseEffects 4.8.4 in ubuntu 22.04

### ISSUE THREAD

**Issue by keithcurtin20** [wwmm/easyeffects#2075]
I upgraded my OS from 20 to 22 and PulseEffects stopped working. I uninstalled and reinstalled. The volume works fine and goes up and down but i don't get the effects to show any output.

See the screenshots below. Changing the volume there changes the volume totally fine. The Bass Enhancer isn't showing anything in the harmonics bar at the bottom as it is playing. All the effects do the same thing.

I know this is deprecated software but i was wondering if there was just a quick fix to this that i'm just missing. 

 
![image](https://user-images.githubusercontent.com/45767959/212994205-8f634c37-4564-4e2e-980a-eb3f06c2b9c3.png)

![image](https://user-images.githubusercontent.com/45767959/212994277-89784da3-766f-4cb3-b2f9-5a15385c96f6.png)

**Comment by wwmm** [comment]
PulseEffects `4.8.4` is not going to work in recent distributions. You will need a package with the bugfix release `4.8.7`

**Comment by keithcurtin20** [comment]
Do you know how I can get that?

This link won't let me download it for whatever reason.
https://packages.debian.org/source/unstable/pulseeffects

normally i just do `sudo apt install pulseeffects` but I don't know how to install a package that is unstable

**Comment by keithcurtin20** [comment]
![image](https://user-images.githubusercontent.com/45767959/213015373-2990fadb-8f13-4f0d-9f09-d8c740f7109d.png)

I actually found it but there is a dependency problem

**Comment by wwmm** [comment]
In these situations installing through a Flatpak package is an option to consider https://github.com/wwmm/easyeffects/wiki/PulseEffects-Wiki#flatpak

**Comment by keithcurtin20** [comment]
That did the track. Thank you for the fast responses!
