### ISSUE TITLE
This error "This project only supports the gcc compiler due to usage of c++20 features" doesn't make sense

### ISSUE THREAD

**Issue by yurivict** [wwmm/easyeffects#2076]
### EasyEffects Version

7.0.0

### What package are you using?

Other (specify below)

### Distribution

FreeBSD

### Describe the bug

clang supports c++20.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>clang supports c++20.

Did you try to compile EasyEffects on it? A few months ago I tried and clang failed miserably because it did not fully support C++20. And based on https://en.cppreference.com/w/cpp/compiler_support it still does not fully support c++20. So the message makes sense.

**Comment by SM9CC** [comment]
I was able to build it perfectly fine using LLVM 16.

**Comment by ppw0** [comment]
> I was able to build it perfectly fine using LLVM 16.

I'm curious to know how. Did you use libc++? How did you get past the source_location error?

**Comment by vchernin** [comment]
> I'm curious to know how. Did you use libc++? How did you get past the source_location error?

If it's useful CI currently builds with clang 16 on alpine linux:

https://github.com/wwmm/easyeffects/blob/cf37bb3b9c692850b93f299eaeeaff874f4f75ab/.github/workflows/CI.yaml#L151
