### ISSUE TITLE
GNOME volume control doesn't work for EasyEffects sink

### ISSUE THREAD

**Issue by tapir** [wwmm/easyeffects#2079]
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.10

### Describe the bug

I have EasyEffect sink selected as the output device in GNOME  but I've recently noticed that changing the volume there doesn't have any effect at all.

### Expected Behavior

That I could change the master volume of the sink

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Long story short we now follow PipeWire default behavior for virtual sinks. It is not a bug. More details at #1817.
