### ISSUE TITLE
Firefox plays broken sounds via EasyEffects (with recordings)

### ISSUE THREAD

**Issue by lilydjwg** [wwmm/easyeffects#2082]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

mpv works fine. Firefox (two instances of them) plays like this (recorded from phone): https://pb.nichi.co/rent-degree-order (.m4a). It plays sound only a fraction of time, with noise. When I try to record via monitor of my output device with gst-launch-1.0 (via pulsesrc), it plays continuously but still with noise: https://pb.nichi.co/trigger-record-file (.ogg).

pw-top shows:

```
not recording:

R  110   2048  48000  42.4ms  11.9us  0.99  0.00   42    S16LE 2 48000 bluez_output.C8_7B_23_7F_7F_81.1
R   48      0      0  75.4us  19.2us  0.00  0.00    0     F32P 2 48000  + easyeffects_sink
R   61      0      0  27.9us  44.5us  0.00  0.00    0                   + ee_soe_output_level
R  150      0      0  35.7us  13.1us  0.00  0.00    0                   + ee_soe_spectrum
R  162      0      0  49.0us 173.5us  0.00  0.00    0                   + ee_soe_equalizer
R   85   3600  48000  81.5us  48.4us  0.00  0.00    0    F32LE 2 48000  + Nightly
S  176      0      0    ---     ---   ---   ---     0                  ee_test_signals

then recording:

R  110    256  48000   5.2ms   8.0us  0.98  0.00  1661    S16LE 2 48000 bluez_output.C8_7B_23_7F_7F_81.1
R   48      0      0  29.6us  18.6us  0.01  0.00    0     F32P 2 48000  + easyeffects_sink
R   61      0      0  32.7us  21.9us  0.01  0.00    0                   + ee_soe_output_level
R  150      0      0  36.8us  11.8us  0.01  0.00    0                   + ee_soe_spectrum
R  162      0      0  72.5us 205.9us  0.01  0.04    0                   + ee_soe_equalizer
R   85   3600  48000  78.2us  74.3us  0.01  0.01    0    F32LE 2 48000  + Nightly
R  104    480  48000 155.5us  16.1us  0.03  0.00    2    S16LE 2 48000  + gst-launch-1.0
```

Switching to other outputs (via pauvcontrol) works fine. CPU usage is low. Disabling the equalizer (the only effect I use) doesn't make sound back to normal.

Restart easyeffects and it's back to normal. This is the second time I restart easyeffects alone to resolve a sound issue so I think it's worth a report.

### Expected Behavior

No noise. Play without silent intervals.

### Debug Log

No log can be obtained until I find a reliable way to reproduce.

**Comment by wwmm** [comment]
>not recording:
>R  110   2048  48000  42.4ms  11.9us  0.99  0.00   42    S16LE 2 48000 bluez_output.C8_7B_23_7F_7F_81.1

>then recording:
>R  110    256  48000   5.2ms   8.0us  0.98  0.00  1661    S16LE 2 48000 bluez_output.C8_7B_23_7F_7F_81.1

There is a large difference in latency between both cases. Without recording it is `2048 / 48000 = 0.043` seconds and while recording it goes down to `256 / 48000 = 0.005` seconds. Considering you are using a bluetooth device the latency may be too low when recording. What is shown by pw-top when mpv is running?

**Comment by lilydjwg** [comment]
Unfortunately the problem is gone. Now things work fine and with mpv it's like this

```
R  162    512  48000 496.9us   4.2us  0.05  0.00    0    S16LE 2 48000 bluez_output.C8_7B_23_7F_7F_81.1
R  125      0      0  30.7us  21.2us  0.00  0.00    0     F32P 2 48000  + easyeffects_sink
R  137      0      0   9.8us   6.4us  0.00  0.00    0                   + ee_soe_output_level
R  155      0      0  15.3us  35.7us  0.00  0.00    0                   + ee_soe_spectrum
R  127    882  44100  47.2us  66.1us  0.00  0.01    0     F32P 2 44100  + mpv
R  152      0      0  26.0us 175.9us  0.00  0.02    0                   + ee_soe_equalizer
```

**Comment by lilydjwg** [comment]
No, mpv doesn't play normally either. It might be that a previously-normal mpv could resume to play from a paused state but new programs don't? Anyway this issue happens again and affects both Firefox and mpv.

When I switch output with helvum to my bluetooth device (the one easyeffects outputs to), the issue is still there until easyeffects' lines disappear. When I switch to the builtin analog sound output (which easyeffects doesn't use) it immediately works fine.

When I switch easyeffects' output device from bluetooth to the builtin analog, it works fine. When I reconnect my bluetooth device, it's back to normal.

**Comment by wwmm** [comment]
>the issue is still there until easyeffects' lines disappear.

PipeWire is probably switching to a higher latency when EasyEffects is not running. Not that we request low latency. We do not make any request. PipeWire automatically switches latency on its own when it thinks it has to.

If too low latency is the cause of the problem using the instructions at https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#quantum-ranges to temporarily force a fixed quantum size like 1024 or 2048 should make the noise go away. But if this does not help some kind of lower level PipeWire problem is happening.

**Comment by lilydjwg** [comment]
The exact same problem hasn't happened yet, but I've got another similar one.

I'm outputting to the builtin speaker (the bluetooth one isn't connected). Suddenly there is no sound while watching a video with Firefox. mpv plays but no sound is heard either.

EasyEffects settings has only a disabled autogain configured. Connecting mpv to `spectrum` or `output_level` sound is back: it seems that the `autogain` filter doesn't output sound.

I've got a bunch of logs from pipewire-pulse around the time this started, but it didn't last long:

```
pipewire-pulse[1171556]: spa.loop: 0x55d7c2aa4e58: queue full 88, need 152
pipewire-pulse[1171556]: spa.loop: 0x55d7c2aa4e58: queue full 88, need 152
pipewire-pulse[1171556]: spa.loop: 0x55d7c2aa4e58: queue full 88, need 152
pipewire-pulse[1171556]: spa.loop: 0x55d7c2aa4e58: queue full 88, need 152
pipewire-pulse[1171556]: spa.loop: 0x55d7c2aa4e58: queue full 88, need 152
```

Changing `clock.force-quantum` doesn't help.

Restart EasyEffects and things are back to nornal.

pw-top:
```
R   96    512  44100  11.6ms 139.8us  1.00  0.01   36    S32LE 2 48000 alsa_output.pci-0000_00_1f.3.analog-stereo
R  134      0      0  91.6us 100.5us  0.01  0.01   36     F32P 2 48000  + easyeffects_sink
R  150      0      0  85.3us  89.2us  0.01  0.01   36                   + ee_soe_output_level
R   73      0      0  84.0us  14.7us  0.01  0.00   36                   + ee_soe_spectrum
R  180      0      0 101.9us  28.7us  0.01  0.00   36                   + ee_soe_autogain
R   80    882  44100  96.8us  22.8us  0.01  0.00   36     F32P 2 44100  + mpv
I  103   1024  48000   0.5us   2.0us  0.00  0.00    1    S32LE 2 48000 alsa_input.pci-0000_00_1f.3.analog-stereo.3
I  181      0      0   0.0us   0.0us  0.00  0.00    0    F32LE 2 48000 Nightly
S   64      0      0    ---     ---   ---   ---     0                  ee_test_signals
```

**Comment by wwmm** [comment]
>Suddenly there is no sound while watching a video with Firefox. mpv plays but no sound is heard either.

This feels like #1789.

**Comment by lilydjwg** [comment]
OK, this issue happens again. My bluetooth speaker is now making very quiet, high frequency noise. `pw-metadata -n settings 0 clock.force-quantum 2048` changes nothing. Enabling global bypass changes nothing but producing a slight short sound (that EasyEffects makes every time it starts or stops working when an application starts or stops to play).

I can see errors are counting for my bluetooth speaker in pw-top but I find no details.

```
R  121    512  44100  11.3ms   8.1us  0.98  0.00  4995    S16LE 2 48000 bluez_output.C8_7B_23_7F_7F_81.1
R  101      0      0  31.5us  15.4us  0.00  0.00    0     F32P 2 44100  + easyeffects_sink
R  163      0      0  28.5us  16.0us  0.00  0.00    0                   + ee_soe_output_level
R   92      0      0  27.2us  10.2us  0.00  0.00    0                   + ee_soe_spectrum
R   64    882  44100  43.0us  21.5us  0.00  0.00    0     F32P 2 44100  + mpv
R  179      0      0  39.2us 177.9us  0.00  0.02    0                   + ee_soe_equalizer
R  130      0      0  29.2us   9.1us  0.00  0.00    0                   + ee_soe_autogain
I   85      0      0   0.0us   0.0us  0.00  0.00    0    F32LE 2 48000 Nightly
S  161      0      0    ---     ---   ---   ---     0                  ee_test_signals
```

**Comment by wwmm** [comment]
>Enabling global bypass changes nothing 

When enabling the global bypass the pipeline should become
```
audio player -> null-sink -> spectrum -> output level meter -> soundcard
```
It is strange this causes any noise because the spectrum and the output level meter do not change the audio data. And the null-sink is a PipeWire's module we load to create our virtual devices.

>I can see errors are counting for my bluetooth speaker in pw-top but I find no details.

Since one or 2 PipeWire releases ago these errors seem to be happening more frequently. I wonder if PipeWire became more prone to `xrun` errors.

**Comment by wwmm** [comment]
Maybe the noise is from the discarded audio buffers when the pipeline is rebuilt. In any case if the problem is indeed #1789 sometimes only killing and restarting EasyEffects makes the audio come back. THis is a PipeWire bug we have been facing for many months. For some reason it seems to happen more on some hardware setups than on others.

**Comment by lilydjwg** [comment]
> When enabling the global bypass the pipeline should become

I didn't notice the null-sink, but I can confirm that the effects I've configured are bypassed.

> In any case if the problem is indeed #1789 

No, after you linked to the issue I realize that's a separate issue I encountered earlier today. They have different behaviors when I connect lines in Helvum. (I restarted EasyEffects twice to fix today.)

> Maybe the noise is from the discarded audio buffers when the pipeline is rebuilt.

Do you mean the slight noise it produces every time EasyEffects updates the pipeline? This one doesn't annoy me much (I just let you know I heard it). The noise I'm complaining about in this issue is continuous playing instead the audio applications try to play.

**Comment by lilydjwg** [comment]
The exact syndrome happens again, but to the builtin speaker. And I've got something in the debug log:

Firefox, bad:
```
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.924:         pipe_manager.cpp:1166   Stream/Output/Audio 193 Nightly with serial 30118 has been added
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.927:         pipe_manager.cpp:899    new metadata property: 193, target.node, Spa:Id, 67
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.927:         pipe_manager.cpp:899    new metadata property: 193, target.object, Spa:Id, 29230
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.934:         pipe_manager.cpp:1206   Nightly port 185 is connected to easyeffects_sink port 83
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.934:         pipe_manager.cpp:1206   Nightly port 161 is connected to easyeffects_sink port 111
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.935:         stream_output_effects.cpp:156   At least one app linked to our device wants to play. Linking our filters.
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.937:         plugin_base.cpp:289     soe: autogain successfully connected to PipeWire graph
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.937:         pipe_manager.cpp:1206   easyeffects_sink port 147 is connected to ee_soe_autogain port 189
(easyeffects:2853731): easyeffects-DEBUG: 13:59:36.937:         pipe_manager.cpp:1206   easyeffects_sink port 48 is connected to ee_soe_autogain port 145
(easyeffects:2853731): easyeffects-DEBUG: 13:59:37.007:         output_level.cpp:37     soe: output_level: PipeWire blocksize: 2048
(easyeffects:2853731): easyeffects-DEBUG: 13:59:37.007:         output_level.cpp:38     soe: output_level: PipeWire sampling rate: 48000
(easyeffects:2853731): easyeffects-DEBUG: 13:59:37.050:         output_level.cpp:37     soe: output_level: PipeWire blocksize: 512
(easyeffects:2853731): easyeffects-DEBUG: 13:59:37.050:         output_level.cpp:38     soe: output_level: PipeWire sampling rate: 48000
(easyeffects:2853731): easyeffects-DEBUG: 13:59:46.007:         pipe_manager.cpp:212    Stream/Output/Audio 193 Nightly has been removed
```

mpv, good:
```
(easyeffects:2853731): easyeffects-DEBUG: 13:59:52.155:         pipe_manager.cpp:1166   Stream/Output/Audio 161 mpv with serial 30137 has been added
(easyeffects:2853731): easyeffects-DEBUG: 13:59:52.157:         pipe_manager.cpp:899    new metadata property: 161, target.node, Spa:Id, 67
(easyeffects:2853731): easyeffects-DEBUG: 13:59:52.157:         pipe_manager.cpp:899    new metadata property: 161, target.object, Spa:Id, 29230
(easyeffects:2853731): easyeffects-DEBUG: 13:59:52.168:         pipe_manager.cpp:1206   mpv port 106 is connected to easyeffects_sink port 83
(easyeffects:2853731): easyeffects-DEBUG: 13:59:52.168:         pipe_manager.cpp:1206   mpv port 185 is connected to easyeffects_sink port 111
(easyeffects:2853731): easyeffects-DEBUG: 13:59:57.571:         pipe_manager.cpp:212    Stream/Output/Audio 161 mpv has been removed
(easyeffects:2853731): easyeffects-DEBUG: 14:00:01.207:         stream_output_effects.cpp:165   No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2853731): easyeffects-DEBUG: 14:00:01.207:         stream_output_effects.cpp:323   disconnecting the autogain filter from PipeWire
(easyeffects:2853731): easyeffects-DEBUG: 14:00:01.208:         pipe_manager.cpp:212     196 ee_soe_autogain has been removed
```

I'm going to restart Firefox to see if it can be back.

**Comment by lilydjwg** [comment]
Full log (empty lines should be me pressing Enter at the terminal): [ee.log](https://github.com/wwmm/easyeffects/files/10553765/ee.log)

**Comment by lilydjwg** [comment]
I use WirePlumber version 0.4.13-1. I'll try wireplumber-git.

**Comment by lilydjwg** [comment]
This issue no longer happens for days with latest EasyEffects.
