### ISSUE TITLE
EasyEffects - does not show audio input or output

### ISSUE THREAD

**Issue by swordnikolav** [wwmm/easyeffects#2084]
Hi
 I have this problem, it does not show me the input or the output, I have a venom linux system.

I attach the debug log.
 Regard's!
https://bpa.st/4J66E

**Comment by wwmm** [comment]
>pipe_manager.cpp:1311	found metadata: settings

There should be a default metadata too. Usually when it is missing the reason is `pipewire-pulse` not being installed. I do not know how your distribution names the package that provides it.

**Comment by swordnikolav** [comment]
The Pipewire-Pulse package comes with the pipewire pack.

The distribution is Venom Linux, a distro based on Linux from scratch.

I have solved the problem, it was necessary to run Wirepumler, thanks anyway!

**Comment by wwmm** [comment]
I am glad it is working now.
