### ISSUE TITLE
Easy Effects Flatpak Not Starting On Manjaro

### ISSUE THREAD

**Issue by wereretot** [wwmm/easyeffects#2101]
### EasyEffects Version

stable (latest no numerical listed)

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Manjaro

### Describe the bug

The program from the command line waits for about 10 to 15 seconds and then fails. All packages of easy effects do this.

### Expected Behavior

I expect the program to launch from the command line.

### Debug Log

flatpak run com.github.wwmm.easyeffects G_MESSAGES_DEBUG=com.github.wwmm.easyeffects                                             
1 ✘ 25s
You have PipeWire 0.3.64 installed
This is newer or the same as PipeWire 0.3.41 required to run Easy Effects

** (process:161728): WARNING **: 17:16:23.311: Error writing credentials to socket: Error sending message: Broken pipe
Failed to register: Timeout was reached

**Comment by wereretot** [comment]
Solved as I install the version on the Arch software installer and a few extra pipe wire packages.

**Comment by mackworthy** [comment]
I'm also getting this problem with the flatpak, but do not get any error messages (even after passing the `G_MESSAGES_DEBUG` flag). The same thing happens on the version installed from the AUR.

@wereretot, did you run into a similar thing? Which additional packages did you need to install?
