### ISSUE TITLE
Wrong pipewire version detected

### ISSUE THREAD

**Issue by FabC** [wwmm/easyeffects#2108]
### EasyEffects Version

Easy Effects	com.github.wwmm.easyeffects	7.0.0	stable	flathub	system

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint 21.1

### Describe the bug

At the program start I got the message:
<code>
$ flatpak run com.github.wwmm.easyeffects
pw-dump succeeded; system likely has PipeWire 0.3.x or later.
You have PipeWire 0.3.18 installed
This is less than PipeWire 0.3.41 recommended to run Easy Effects
</code>
All the installed pipewire package show version 0.3.48

Then the appllication doesn't start.

### Expected Behavior

The start of the program

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Please run 
```
G_MESSAGES_DEBUG=easyeffects flatpak run --command=easyeffects com.github.wwmm.easyeffects
```

and paste the logs here.

**Comment by violetmage** [comment]
Is the issue resolved? Should the ticket be closed?

If not, please see @vchernin's comment, and additionally please provide the output of:
`pw-dump --version`

**Comment by FabC** [comment]
> Please run
> 
> ```
> G_MESSAGES_DEBUG=easyeffects flatpak run --command=easyeffects com.github.wwmm.easyeffects
> ```
> 
> and paste the logs here.

This is the output

(process:2): easyeffects-DEBUG: 07:01:35.267:   easyeffects.cpp:35      easyeffects version: 7.0.0
(process:2): easyeffects-DEBUG: 07:01:35.269:   easyeffects.cpp:45      locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 07:01:35.278:       presets_manager.cpp:49  system input presets directory: "/app/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 07:01:35.278:       presets_manager.cpp:49  system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 07:01:35.278:       presets_manager.cpp:49  system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:2): easyeffects-DEBUG: 07:01:35.278:       presets_manager.cpp:52  system output presets directory: "/app/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 07:01:35.278:       presets_manager.cpp:52  system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 07:01:35.279:       presets_manager.cpp:52  system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:2): easyeffects-DEBUG: 07:01:35.279:       presets_manager.cpp:194 user presets directory already exists: /home/fabrizio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 07:01:35.279:       presets_manager.cpp:194 user presets directory already exists: /home/fabrizio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 07:01:35.279:       presets_manager.cpp:194 user presets directory already exists: /home/fabrizio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 07:01:35.279:       presets_manager.cpp:194 user presets directory already exists: /home/fabrizio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 07:01:35.279:       presets_manager.cpp:194 user presets directory already exists: /home/fabrizio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 07:01:35.374:       pipe_manager.cpp:1426   compiled with PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 07:01:35.374:       pipe_manager.cpp:1427   linked to PipeWire: 0.3.41
(easyeffects:2): easyeffects-DEBUG: 07:01:35.375:       pipe_manager.cpp:1397   core version: 0.3.18
(easyeffects:2): easyeffects-DEBUG: 07:01:35.375:       pipe_manager.cpp:1398   core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 07:01:37.090:       pipe_manager.cpp:1311   found metadata: default
(easyeffects:2): easyeffects-DEBUG: 07:01:37.090:       pipe_manager.cpp:1311   found metadata: route-settings

**Comment by FabC** [comment]
> Is the issue resolved? Should the ticket be closed?
> 
> If not, please see @vchernin's comment, and additionally please provide the output of: `pw-dump --version`

This is the command output:

```
pw-dump
Compiled with libpipewire 0.3.18
Linked with libpipewire 0.3.18
```

**Comment by vchernin** [comment]
> All the installed pipewire package show version 0.3.48

> Compiled with libpipewire 0.3.18
> Linked with libpipewire 0.3.18

Clearly somehow the packages that show a newer pipewire version are wrong somehow. I don't see how pw-dump could display the wrong version.

**Comment by FabC** [comment]
In the mean time I advanced to pipewire 0.3.66 but with the same result.

**Comment by vchernin** [comment]
What version is shown under the PipeWire page in EasyEffects after starting it with:

`G_MESSAGES_DEBUG=easyeffects flatpak run --command=easyeffects com.github.wwmm.easyeffects`

**Comment by FabC** [comment]
> If the core version is that then what pw-dump is saying is accurate. Have you tried restarting your system?

Yes I did. Digging in the files on my system i found these:

```
lrwxrwxrwx 1 root root     26 feb 17 04:20 /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0 -> libpipewire-0.3.so.0.366.0
-rw-r--r-- 1 root root 871536 feb 17 04:20 /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0.366.0

lrwxrwxrwx 1 root root      20 gen  2  2021 /usr/local/lib/x86_64-linux-gnu/libpipewire-0.3.so -> libpipewire-0.3.so.0*
lrwxrwxrwx 1 root root      26 gen  2  2021 /usr/local/lib/x86_64-linux-gnu/libpipewire-0.3.so.0 -> libpipewire-0.3.so.0.318.0*
-rwxr-xr-x 1 root root 3295528 gen  2  2021 /usr/local/lib/x86_64-linux-gnu/libpipewire-0.3.so.0.318.0*

```

318 and 366 recall me the pipewire versions, why are there in different folders ?

**Comment by vchernin** [comment]
> > If the core version is that then what pw-dump is saying is accurate. Have you tried restarting your system?
> 
> 
> 
> Yes I did. Digging in the files on my system i found these:
> 
> 
> 
> ```
> 
> lrwxrwxrwx 1 root root     26 feb 17 04:20 /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0 -> libpipewire-0.3.so.0.366.0
> 
> -rw-r--r-- 1 root root 871536 feb 17 04:20 /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0.366.0
> 
> 
> 
> lrwxrwxrwx 1 root root      20 gen  2  2021 /usr/local/lib/x86_64-linux-gnu/libpipewire-0.3.so -> libpipewire-0.3.so.0*
> 
> lrwxrwxrwx 1 root root      26 gen  2  2021 /usr/local/lib/x86_64-linux-gnu/libpipewire-0.3.so.0 -> libpipewire-0.3.so.0.318.0*
> 
> -rwxr-xr-x 1 root root 3295528 gen  2  2021 /usr/local/lib/x86_64-linux-gnu/libpipewire-0.3.so.0.318.0*
> 
> 
> 
> ```
> 
> 
> 
> 318 and 366 recall me the pipewire versions, are those folders correct ?
> 
> 

Libraries in `/usr/local/lib` will  usually override those in `/usr/lib`. `/usr/lib` is usually provided by your distro package manager. How did you install pipewire?

**Comment by FabC** [comment]
So, it makes sense that version 0.3.18 overrides 0.3.66. No idea how I installed in /usr/lib.

**Comment by vchernin** [comment]
> So, it makes sense that version 0.3.18 overrides 0.3.66. No idea how I installed in /usr/local, I suppose apt-get did it.

Well, if you don't remember how you installed them you could manually remove the unwanted pipewire versions from `/usr/local/lib`. I would be surprised if apt put them there. It may be worth trying to look through `/usr/local` if there is other unexpected software.

**Comment by FabC** [comment]
In the /usr/local/lib/x86_64-linux-gnu/pkgconfig folder, I found a libpipewire-0.3.pc file:

```
prefix=/usr/local
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

moduledir=${libdir}/pipewire-0.3

Name: libpipewire
Description: PipeWire Interface
Version: 0.3.18
Requires: libspa-0.2
Libs: -L${libdir} -lpipewire-0.3
Cflags: -I${includedir}/pipewire-0.3 -D_REENTRANT
```

This looks like as the indication that the 0.3.18 was (wrongly ?) installed inthe /usr/local/lib.

**Comment by violetmage** [comment]
This kind of thing can happen when installing unsanboxed software from outside of your distro's repository, A lot of proprietary software, especially those with installer scripts instead of a ppa or supplementary repository, are notorious for adding wierd files in even wierder places.

If you haven't used software like that, and haven't played with compiling your own software that might have pipewire dependencies, then this might be a package manager bug.

**Comment by servimo** [comment]
This happen to me when I compiled a software using  ./configure without setting prefix=/usr, then make, then make install and then, in the other day, installed a package pre-compiled of the same software without uninstalled the previous compiled by me.

**Comment by violetmage** [comment]
Yes, that would explain the problem.

If the issue is resolved, please consider closing this ticket.

**Comment by FabC** [comment]
Very fruitful discussion, problem not solved but I understood what happened.
Many thanks.
