### ISSUE TITLE
EasyEffect service (--gapplication-service)  is killed after a few seconds/minutes on Ubuntu 22.04

### ISSUE THREAD

**Issue by doh38** [wwmm/easyeffects#2110]
### EasyEffects Version

7.0.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04// on Xorg and XWayland same behaviour :)

### Describe the bug

Hey,
The gapplication-service seems to be killed after a few seconds. 
If I open easyeffect in a terminal like this:
`flatpak run com.github.wwmm.easyeffects `
It will hold and is kept running
If I open it as service also in terminal (Which I really need :)) ):
`flatpak run com.github.wwmm.easyeffects --gapplication-service`

It will run for some seconds (15--> 30s)  and "disappear"
I get a normal "go back to prompt" in terminal without errors. Here the terminal action:

```
doh@Xpsus:~$ flatpak run com.github.wwmm.easyeffects --gapplication-service
You have PipeWire 0.3.63 installed
This is newer or the same as PipeWire 0.3.41 required to run Easy Effects
doh@Xpsus:~$
```

### Expected Behavior

run without being killed, it sounds really better while it runs :) 

*I don't know how to start it as a debug with flatpack  :) But If you tell me the right command.I'm really keen to do it :)

**Comment by wwmm** [comment]
>I don't know how to start it as a debug with flatpack :) But If you tell me the right command.I'm really keen to do it :)

Take a look at the step number 3 at https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs.

**Comment by doh38** [comment]
I followed very bravely the instructions, but unfortunately it doesn't work.
I get this throwing the flatpak core dump command:
```
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 44, in run
    subprocess.check_call(["coredumpctl", "dump"] + shlex.split(self.coredumpctl_matches),
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['coredumpctl', 'dump']' returned non-zero exit status 1.
```
Seems to be a bug. you may know better :)

**Comment by vchernin** [comment]
Could try running `coredumpctl dump`.?`flatpak-coredumpctl` seems to be running into trouble calling `coredumpctl`

What desktop environment are you using? Default gnome on Ubuntu?

**Comment by doh38** [comment]
[debug.easyeffects.txt](https://github.com/wwmm/easyeffects/files/10553820/debug.easyeffects.txt)
Again I will need a clean command line. the attached file is what `G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects --gapplication-service `
outputs.
Can you (please ^^ ) send me the correct command  for coredumpctl?
I tried:
```
doh@Xpsus:~$ coredumpctl -o /tmp/pe372.coredump dump G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects
No match found.
```
But it doesn't seems to be the right way. I'm really not comfortable with the coredump thing and even less with flatpak. sorry -.-'

**Comment by vchernin** [comment]
Maybe just try this by itself:

`coredumpctl -o /tmp/pe372.coredump dump`

Coredumpctl keeps a record of coredumps (a log detailing a crash) from the system, you don't need to provide it a command to start easyeffects.

**Comment by doh38** [comment]
I already tried that and it give the same "No match" reply. there is also no .coredump in the tmp dir. but just an observation. it (probably) my not be a crash. nothing looks like it actually. it seems that the service is "peacefully" shot somehow.

**Comment by vchernin** [comment]
Could you try run `flatpak permission-reset com.github.wwmm.easyeffects`, and then run easyeffects again? See if there are any prompts about background permissions.

**Comment by doh38** [comment]
Yesss <3 That was the issue. seems that if it's not "permissioned" the daemon doesn't work correctly. awesome :) it's holding beautifully now <3
