### ISSUE TITLE
Excluded outputs still gets enabled automatically

### ISSUE THREAD

**Issue by kawazoe** [wwmm/easyeffects#2115]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Garuda Linux

### Describe the bug

I use a loopback device in front of my main audio output. For this to behave correctly with easy effects, I had to exclude this device from the list of output apps. This worked fine until I updated to 7.0.0.

Now, easy effects always attempts to connect to this device. This results in the following graph:
![image](https://user-images.githubusercontent.com/406575/216843382-28fd54a8-b201-4a1c-9f22-dda0c3c9731b.png)

As you can see, since easy effects attempts to enable processing through my loopback device, it creates a signal loop, as that device is also my default output device. The loop is illustrated as the first row of nodes, with Brave being the app that actually produces sound in this example.

Trying to uncheck "Enable" in the easy effects' UI only causes it to check itself back on after a few seconds. You will also notice that I have 2 more loopback devices configured. They do not appear to be affected by this issue, and the "Enable" checkbox is not clickable for them, as I would expect. This only affects the first of the three because it is also my default output device.

### Expected Behavior

What should happen is easy effects respect my exclusions, and instead, produce the following graph:
![image](https://user-images.githubusercontent.com/406575/216844526-e69b85fa-0aeb-4bd0-9031-55fca99ee44f.png)

In this example, easy effects still outputs to my default output, just as Brave which is NOT enabled for processing in easy effects. Turning Brave on for processing should then only switch the target node from `MG16XU 5+6` to the `Easy Effects Sink` just on its right.

### Additional Information

There are two potential workarounds.  

The first one is to set my output device in easy effects to the one that corresponds to the `Sound Core3D` node on the far right on my graphs. This is automatic, but will also double the volume of everything going through this output.

The second one is to manually open qpwgraph and forcefully disconnect the `Easy Effects Sink` node from my default output device's node `MG16XU 5+6`. This usually lasts until the session is locked, or the computer goes to sleep, or reboots. This is also how I got to produce the "Expected Behavior"'s graph.

**Comment by wwmm** [comment]
>I had to exclude this device from the list of output apps

Does the loopbackdevice still has the exact same name it had before? Our blocklist checks only the node name and nothing else.

>Trying to uncheck "Enable" in the easy effects' UI only causes it to check itself back on after a few seconds. 

When a stream is blocklisted EasyEffects does not touch it anymore. But third party tools or the media session manager (probably wireplumber) can still do it. Like Pulseaudio PipeWire also tries to restore a stream to the last used device or to whatever device it thinks it should be. And loopback devices are just streams at the end of the day. My guess is that the media session manager is for some reason moving the loopback device stream to EasyEffects sink.

**Comment by wwmm** [comment]
In any case kill easyeffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can have more information.

**Comment by wwmm** [comment]
>You will also notice that I have 2 more loopback devices configured. They do not appear to be affected by this issue, and the "Enable" checkbox is not clickable for them, as I would expect. This only affects the first of the three because it is also my default output device.

It does not make sense that the blocklist works for all loopback devices except one. It feels like some subtle change happened to the node name. The fact it is the default device does not affect the blocklist. It does not even look at this information. The blocklist only cares about nodes that can play/record audio. Loopback device streams are handled like any other player/recorder stream.

**Comment by kawazoe** [comment]
> Does the loopbackdevice still has the exact same name it had before? Our blocklist checks only the node name and nothing else.

Yes, and the "Exclude" checkbox is still ticked on this device.

> My guess is that the media session manager is for some reason moving the loopback device stream to EasyEffects sink.

Good to know. Do you know of an easy way to force WirePlumber to forget those associations? Last time I tried to do this, I had to shutdown its service, delete the file it uses to store those settings, and then reboot. If you know of any other way, I would appreciate your insight.

**Comment by wwmm** [comment]
>Do you know of an easy way to force WirePlumber to forget those associations? Last time I tried to do this, I had to shutdown its service, delete the file it uses to store those settings, and then reboot. If you know of any other way, I would appreciate your insight.

As far as I am aware editting/deleting `~/.local/state/wireplumber/restore-stream` and restarting wireplumber is the only way.

**Comment by kawazoe** [comment]
You were right. It was WirePlumber doing some weird stuff... Wiping the file fixed the problem.
