### ISSUE TITLE
EasyEffects not asking for background permission 

### ISSUE THREAD

**Issue by louie123456789** [wwmm/easyeffects#2116]
EasyEffects Version

7.0.0
What package are you using?

Flatpak (Flathub)
Distribution

Ubuntu Mate 22.04

Describe the bug

The app tells me to enter the specific command of resetting the permissions and i still cant enable it to start up with my linux session.

**Comment by vchernin** [comment]
try install the gnome background portal with `sudo apt install xdg-desktop-portal-gnome --no-install-recommends` and reboot.
