### ISSUE TITLE
Autogain: use exponential moving average

### ISSUE THREAD

**Issue by road2react** [wwmm/easyeffects#2117]
Right now, the Maximum History option controls the duration of the Integrated average gain. However, this causes a problem: if the original volume changes, after the maximum history is elapsed, the adjusted gain would suddenly change due to the jump in the Integrated average.

It would be optiminal to have the option to use an exponential moving average. This would also make history memoryless (i.e. the new average gain is a constant proportion of the previous gain and the current gain) and would not need to store data for the entire history.

**Comment by wwmm** [comment]
I am not sure if this can be done from our side. The maximum history in our window is a parameter from the `libebur128` library we use to estimate loudness. So different kinds of moving window averages would probably have to be implemented there. Unless we can get some kind of poor main solution based on the momentary and short-term loudness.

**Comment by wwmm** [comment]
>I wonder if it's feasible to just use the RMS (or similar) to calculate the current loudness.

Although I do not know the details behind the `EBUR 128 standard`  calculations it can not be so simple. The idea is to estimate the `perceived loudness` of the average human ear. As we listen better to voice frequency than to low and high I imagine at the very minimum some filtering for high and lower frequencies have to be done. As well as frequency dependent weights.

**Comment by wwmm** [comment]
This site has a short description of the main steps https://essentia.upf.edu/reference/std_LoudnessEBUR128.html. As expected not so simple.

**Comment by wwmm** [comment]
As we can not do this on our side and nowadays the autogain allows the integrated value time window to be customized we can close this issue.
