### ISSUE TITLE
[Feature Request] Ability to toggle between Calf Plugins and LSP

### ISSUE THREAD

**Issue by p-chan5** [wwmm/easyeffects#2120]
Hi, I've seen EasyEffects migrate from one plugin suite to another over the years and, to be honest, I miss some of them. It would be great to be able to choose between one version or another. I imagine a port would have to be made that would allow you to manage your settings in the Easy interface. This could be located under `Using Linux Studio Plugins` / `Calf Studio Gear` and now be a button. What do you think?

<img src=https://user-images.githubusercontent.com/123143444/218192323-a51be851-89b1-4141-ac93-28c2a280e88c.jpg> <img src=https://user-images.githubusercontent.com/123143444/218193620-cc3438c9-8155-4a29-80a2-9e875e597663.jpg>

**Comment by wwmm** [comment]
Toggling between Calf and LSP plugins is not viable. The parameters exposed by the plugins are completely different both in name and quantity. And the corresponding schema in the GSettings database is a xml file with all the key names hardcoded.

What would have to be done is wrapping the old Calf plugins again and exposing them with a different name. But offering multiple plugins for the same task isn't really EasyEffects focus. The idea is more around wrapping plugins that offer as many features as possible. This way we reduce the maintenance burden. The only reason why I am considering adding another pitch plugin is the bad behavior of the rubberband library on some systems.

**Comment by wwmm** [comment]
And in the case of the multiband Calf plugins that were replaced one of the motivations was problems in its band splitting implementation. I do not know if this was fixed. So there is that to consider too.

**Comment by p-chan5** [comment]
I understand, thanks for your explanation. Yes, LSP plugins are somewhat more advanced than Calf. Sorry, I was unaware of the compatibility issues. Maybe in the future you could consider #1433 as a way to bring them back.

**Comment by wwmm** [comment]
>I understand, thanks for your explanation. Yes, LSP plugins are somewhat more advanced than Calf. Sorry, I was unaware of the compatibility issues. Maybe in the future you could consider https://github.com/wwmm/easyeffects/issues/1433 as a way to bring them back.

No problems :-). It would be really nice to allow people to use whatever plugin they want. It is just one of those situations where we pay a price for not being a general purpose host like Carla or Ardour. EE code evolved in a way that does not play nice with this idea. Specially our presets infrastructure.

Maybe in the future things will change. In the past allowing multiple filters instances seemed impossible. But today we have it.

**Comment by wwmm** [comment]
As #1433 is the proper way to handle this we can close this issue.
