### ISSUE TITLE
Speech processor & noise reduction

### ISSUE THREAD

**Issue by v1gnesh** [wwmm/easyeffects#2122]
Hi @wwmm & @Digitalone1 ,

You both (and everyone else involved in improving this of course) are really doing great work with excellent audio enhancements for Linux.
It is because of people like you that Year of Linux on the Desktop always appears so tantalizingly close.
It was such a relief to find out about this in 2020, and that I could somehow get it working through flatpak.
Now that it's even in debian upstream, bye bye flatpak indeed.

I use @Digitalone1's LoudnessEqualizer on the output to get consistent audio levels.
At one point, I had asked him if I can apply the same to the input too (just changing the `output` to `input` or something, in the config)... and that it'll work.
I now see with v7 there's speech processor in addition to noise reduction.
Do you have any suggestions on how I should order these 3 when applying on the input microphone?

BTW, @wwmm, it's good to see you use Ubuntu (I think?) in your sample video about these 2 plugins, on the related issue on this topic.

**Comment by wwmm** [comment]
Thanks! :-)

>Do you have any suggestions on how I should order these 3 when applying on the input microphone?

When it comes to the speech processor and the noise reduction based on rnnoise I think it depends on the situation and type of noise. After some tests on my computer the better results happened with
```
echo canceller -> speech processor -> rnnoise
```
But something different may happen on other setups. The first thing to have in mind is that the neural network in the rnnoise library was trained for certain types of noise. In some situations it may be better to use only the generic noise reduction provided by the speech plugin. Usually I have both enabled. But when rnnoise starts to take the voice away together with the noise I use only the generic noise reduction in the speech processor.

Another point to consider is whether voice detection is enabled or not in the speech processor. Depending on this and on how well rnnoise handles the signal it may not be a good idea to put the speech processor after rnnoise.

>BTW, @wwmm, it's good to see you use Ubuntu (I think?) in your sample video about these 2 plugins, on the related issue on this topic.

I use GNOME on Arch Linux.

**Comment by Digitalone1** [comment]
> At one point, I had asked him 

I'm a girl. :) 

>I now see with v7 there's speech processor in addition to noise reduction. Do you have any suggestions on how I should order these 3 when applying on the input microphone?

@wwmm could help you better than me since I don't use any of them. Anyway, I would put them at the beginning, before any other effect to first clear the sound, then apply other processors. 

But, as I said, never used them, so I don't know how to configure them for the preset you're using.

**Comment by v1gnesh** [comment]
>     At one point, I had asked him
> I'm a girl. :)

Whoops, sorry about that!
Thank you both. I'll have to experiment with the different options and see how it goes.

> I use GNOME on Arch Linux.

Haha, "I use Arch BTW" vibes then.

**Comment by violetmage** [comment]
If you are applying this to a microphone for speech (e.g. video chat), then as @Digitalone1 said, the Speech Processor should definately be the first in the chain.

Note that in EasyEffects, the Speech Processor already has a simple denoiser built-in, so unless you have a more optimized denoiser already, I think you should just add the Speech Processor, adjust it on it's own, then add the rest of your effects chain back in after it.

**Comment by Massimo-B** [comment]
Comparing **Speech Processor** with enabled Denoise and Voice detection with **Noise Reduction** (Using RNNoise) with Voice Detection enabled, Threshold 1% and Release 0ms:

I have a very sensible Headphone mics from Antlion which already have quite low electric noise or environment noise reception.
Both filters actually do a quite equal job, removing the already low noise. I don't think I'm going to use both in chain, also keeping in mind to lower CPU usage which is already an issue with easyeffects. But I noticed one thing that **Noise Reduction** does better: The mic is so sensible that I hear every breathing when turning on input monitoring. **Noise reduction** removes that and keeping only the clean voice. What do the options Wet Level and Relase actually do, where do I find the documentation?

**Speech Processor** doesn't remove breathing. In my case I don't even hear a difference with Voice detection enabled or disabled.

**Comment by wwmm** [comment]
>What do the options Wet Level and Release actually do

As in the other plugins the `wet level` is used to mix a fraction of unprocessed sound to the processed audio. This can be useful depending on what it is being done.

I was not the one that implemented the voice detection algorithm but if I remember well the release control affects for how long the plugin will keep sending audio in its output after the probability of voice detection goes below the threshold. Imagine that at some point the plugin detected that there was voice and stopped forwarding silence. If the user suddenly stops speaking the plugin won't bring silence back immediately. It will "wait for a while" before inserting silence again.
