### ISSUE TITLE
5.1 audio broken

### ISSUE THREAD

**Issue by VorpalBlade** [wwmm/easyeffects#2133]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I recently got a 5.1 setup (for very cheap from a second hand shop). However, only the KDE settings speaker test worked with anything but the front left/right speakers, everything else was limited to stereo. Looking in `qpwgraph` it is obvious that the issue is that easyeffects only passes stereo sound through.

I only use easyeffects for a slight bass boost (using the bass enhancer effect), so I don't see why 5.1 sounds should not be possible to pass through.

What is actually an even larger issue is that without easyeffects, stereo sound is spread out in a sensible way across all channels (automatically it seems). With easyeffects that doesn't work and only the left, right and sub speakers are used.

### Expected Behavior

I would expect easyeffects to be "transparent" to the number of channels. E.g. passing through and applying filters to all the channels.

If an effect that is incompatible with the current number of channels is added, I would expect some sort of warning/error to show up in the UI.

### Debug Log

<details><summary>Debug Log</summary><br/>

Not appliccable?

</details>

**Comment by wwmm** [comment]
There is an issue about this #1126. Long story short there is no easy way to support multichannel audio at this moment. THe only workaround is the user setting its own loopback devices to do the downmixing as explained in one of #1126 comments.

As there is already an issue about this I will close this one.

**Comment by wwmm** [comment]
This comment https://github.com/wwmm/easyeffects/issues/1126#issuecomment-1147748628
