### ISSUE TITLE
Firefox audio may stop playing

### ISSUE THREAD

**Issue by atomGit** [wwmm/easyeffects#2135]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro, KDE

### Describe the bug

* an audio stream (whether a video or audio file) may or may not play in Firefox when it's first started (plays ~90% of the time, fails ~10%)
* when pausing the audio/video, sound may be lost when playback is resumed
* much of the time when audio is lost, it can be regained by pausing the stream, waiting for a second, then resuming playback
* once in a blue moon, when sound is regained, only one channel (left) works
* once in a blue moon, when sound is regained, it is wildly distorted
* this problem occurs only if a preset is loaded and Firefox is enabled in EE, however disabling all filters in the preset does not get the sound back - only disabling Firefox seems to work
* when sound is lost, the level meters in the preset may stop working, or not 
* this issue usually never occurs for local files, however it can occur, though it seems the issue needs to occur in Firefox first after which you have to mess with EE settings (pwr button on/off, enabling an excluded app, etc.)

i first noticed this issue around [Jul-2022](https://github.com/Digitalone1/EasyEffects-Presets/issues/7)

test:

* Firefox (any recent version)
* EE 7.0.0
* [EasyEffects-Presets/LoudnessEqualizer.json](https://github.com/Digitalone1/EasyEffects-Presets/blob/master/LoudnessEqualizer.json)
* load any audio/video source on any website, pause the source, then resume - continue until the sound stops

notes:

* sound card is a USB audio interface
* HDMI sound is disabled in system settings
* i'm not using any custom config's for pipewire, etc.

possibly related:

* [Firefox plays broken sounds via EasyEffects (with recordings) · Issue #2082 · wwmm/easyeffects](https://github.com/wwmm/easyeffects/issues/2082)
* [issue with LoudnessEqualizer.json · Issue #7 · Digitalone1/EasyEffects-Presets](https://github.com/Digitalone1/EasyEffects-Presets/issues/7)
* [firefox audiostreams persist even though no audio is playing from firefox · Issue #2024 · wwmm/easyeffects](https://github.com/wwmm/easyeffects/issues/2024)
* [no sound, randomly, viewing video with FF , Chrome, VLC · Issue #1789 · wwmm/easyeffects](https://github.com/wwmm/easyeffects/issues/1789)
* [Sometimes only sound from one channel or no sound at all · Issue #1476 · wwmm/easyeffects](https://github.com/wwmm/easyeffects/issues/1476)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Probably the same as #1789

**Comment by atomGit** [comment]
> Probably the same as #1789

i linked that bug in my post, but i'm not sure it's the same

> Randomly, sometime when viewing a video with FF or Chrome (YouTube) or VLC then there is no sound.

doesn't happen for me for local files ever unless i do some voodoo to invoke the problem

> It seems this occurs after several starts and stops, or several launching and quitting.

doesn't sound like what i'm seeing

> I must restart the PC to get again sound For FF or Chrome or VLC.

in my case i can just disable processing in EE for Firefox - no restart

**Comment by wwmm** [comment]
>i linked that bug in my post, but i'm not sure it's the same

This bug has slightly different side effects for different users but at the end of the day it is still the same hard to catch PipeWire bug. Unfortunately there is nothing we can do from our side. It is a problem PipeWire is having when managing the filters state. 

In the past it usually manifested itself through the lack of sound in one channel like the one you described. Now it is more often to see other things.

>in my case i can just disable processing in EE for Firefox - no restart

Exactly what happens in some situations. Another workaround that not always work is using the global bypass. In any case it is still a variation of https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1733.

**Comment by atomGit** [comment]
> ...it is still the same hard to catch PipeWire bug

ah, thanks for that - i wasn't sure of the origin
