### ISSUE TITLE
Where is std::ranges::find() defined?

### ISSUE THREAD

**Issue by yurivict** [wwmm/easyeffects#2159]
### EasyEffects Version

7.0.1

### What package are you using?

Other (specify below)

### Distribution

FreeBSD

### Describe the bug

```std::ranges::find()``` is used in the code (ex. in src/app_info.cpp:83), but C++ docs doesn't have such function:
see https://en.cppreference.com/w/cpp/ranges

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
It is here https://en.cppreference.com/w/cpp/algorithm/ranges/find. No special procedure needed at least on GCC. I did no test on newer clang versions yet.

**Comment by yurivict** [comment]
Ok, thanks!
