### ISSUE TITLE
error when meson build

### ISSUE THREAD

**Issue by qiu-yang** [wwmm/easyeffects#2161]
### EasyEffects Version

7.0.1

### What package are you using?

Arch (easyeffects)

### Distribution

Ubuntu22.04

### Describe the bug

when meson build
data/meson.build:50:0: ERROR: Can not assign None to variable.

### Debug Log

$ meson build
The Meson build system
Version: 0.61.2
Source dir: /home/y/gitproject/easyeffects
Build dir: /home/y/gitproject/easyeffects/build
Build type: native build
Project name: easyeffects
Project version: 7.0.1
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libportal-gtk4 found: YES 0.6
Configuring config.h.in using configuration
Configuring com.github.wwmm.easyeffects.metainfo.xml.in using configuration
WARNING: Gettext not found, all translation targets will be ignored.

data/meson.build:50:0: ERROR: Can not assign None to variable.

A full log can be found at /home/y/gitproject/easyeffects/build/meson-logs/meson-log.txt

**Comment by wwmm** [comment]
>WARNING: Gettext not found, all translation targets will be ignored.

You have to install it.

**Comment by wereretot** [comment]
I get this same issue.
