### ISSUE TITLE
Sort equalizer bands internally

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2162]
So now that I have time, I'd like to address this issue.

First let's do a recap. After making the import of GraphicEQ presets, a user complained about the bands not sorted by frequency. So we used the c++ `stable_sort` to sort them but this solution had two issues:

1. It could only sort imported presets from APO/GraphicEQ formats
2. The performance was not very good.

The first is self-explanatory: at that time if a user made their bands in the GUI and those bands were not sorted, they had to sort them manually (which is quite cumbersome) because we didn't have a method to sort them automatically.

The second point depends on how the sort algorithm works. Not 100% sure on what stable sort does, but the values of the vector should be replaced if needed and, for every replace there are 3 copies (copy in the temporary, then copy the first into the second and the second/temporary into the first). So it depends on how the vector is unsorted. Worse the sort, more the copies, bad the performance.

So @wwmm introduced a new GTK widget for the bands in the GUI. This solution solved the first point, but not the second since I suppose the list of widgets has to be sorted quite the same way as the vector built for APO/GraphicEQ import.

Besides this introduces an inconsistency (in my opinion) because, even if the bands are sorted graphically, they are not sorted internally, so if I make the sort and save the preset, I will have an unsorted preset at the next reload (replacing an existing different preset or at the next service startup).

So I think we should use a different approach sorting directly on the gsettings keys rather than the widgets or custom structures. Especially because the gsettings keys are bound to lv2 plugin values, so they reflects on the audio processor and the GUI, giving also the opportunity to save the preset retaining the sorted bands.

Thinking about this solution I came up with the following pseudo-code. Note that it's a draft (syntax should be not correct, types are wrong...) made only for presentation purpose:

```c++
void sort_bands () {
  struct EQ_Band {
    std::string type;
    std::string mode;
    std::string slope;
    double freq;
    double gain;
    double q;
    bool solo;
    bool mute;
  };

  const auto used_bands = g_settings_get_int(settings, "band_num");
  
  if (used_bands < 1 || used_bands > max_bands) {
    return;
  }
  
  std::multimap<double, struct EQ_Band> sorted_bands;
  
  for (int n = 0; n < used_bands; n++) {
    const double f = g_settings_get_double(settings_left, band_gain[n].data());
    
    sorted_bands.emplace(
      pair<double, struct EQ_Band>(
        f, 
        {
          .freq = f,
          .type = g_settings_get_enum(settings_left, band_type[n].data()),
          .mode = g_settings_get_enum(settings_left, band_mode[n].data()),
          .slope = g_settings_get_enum(settings_left, band_slope[n].data()),
          .gain = g_settings_get_double(settings_left, band_gain[n].data()),
          .q = g_settings_get_double(settings_left, band_q[n].data()),
          .solo = g_settings_get_boolean(settings_left, band_solo[n].data()),
          .mute = g_settings_get_boolean(settings_left, band_mute[n].data())
        }
      )
    );
  }
  
  for (const auto& p : sorted_bands) {
    g_settings_set_double(settings_right, band_frequency[n].data(), p.second.freq);
    g_settings_set_enum(settings_right, band_type[n].data(), p.second.type);
    g_settings_set_enum(settings_right, band_mode[n].data(), p.second.mode);
    g_settings_set_enum(settings_right, band_slope[n].data(), p.second.slope);
    g_settings_set_double(settings_right, band_gain[n].data(), p.second.gain);
    g_settings_set_double(settings_right, band_q[n].data(), p.second.q);
    g_settings_set_boolean(settings_right, band_solo[n].data(), p.second.solo);
    g_settings_set_boolean(settings_right, band_mute[n].data(), p.second.mute);
  }
}
``` 

What this wants to do:
1. Define a struct as helper to aggregate what we need (the data of a single band);
2. Retrieve the number of used bands;
3. Define a `multimap` of the above structure indexed by frequencies (multiple bands can have the same frequency, so we can't use a plain `map`);
4. Loop through used bands and, for each band, retrieve their values from gsettings, then store them into a new structure;
5. Insert that structure in the multimap specifying the frequency as index;
6. Loop through the multimap (which should be sorted by frequency) and store the values of each band into gsettings.

This in theory should have big advantages. As already said before, it reflects on lv2 plugin values and on the GUI. On the performance side, should be faster because we copy the values of the bands only two times: one for the struct construction (with `emplace` should be constructed in place), the other for the storing of the data into gsettings. The sort is made by the multimap internally, but I think it only moves the internal pointers, no other copies involved.

Then I'd like to do it in `equalizer.cpp`, so it could be executed also when the window is not shown (not really needed at the moment, but maybe useful in the future...).

But this only takes into account the situation when the bands are not splitted. For the `split band` scenario we have to make the whole process also for `settings_right`.

@wwmm what do you think? Is it doable or there's something I'm missing?

**Comment by wwmm** [comment]
>So @wwmm introduced a new GTK widget for the bands in the GUI. This solution solved the first point, but not the second since I suppose the list of widgets has to be sorted quite the same way as the vector built for APO/GraphicEQ import.

Yes the sort is done through https://github.com/wwmm/easyeffects/blob/ce43c2f8d71c69459cf3f7b3450c7366563352d2/src/equalizer_ui.cpp#L603. But as far as I could see the huge  performance bottleneck is in GTK and not in the vector sort. For some reason the amount of widgets per band seems too much for gtk to create many bands in a short time.

>Besides this introduces an inconsistency (in my opinion) because, even if the bands are sorted graphically, they are not sorted internally, so if I make the sort and save the preset, I will have an unsorted preset at the next reload (replacing an existing different preset or at the next service startup).

Yes. At the time I considered propagating the sorting to the preset. But it was clearly not as easy as I initially thought.

>On the performance side, should be faster because we copy the values of the bands only two times: one for the struct construction (with emplace should be constructed in place), the other for the storing of the data into gsettings.

GSettings can be incredibly slow when it comes to writing. So whatever it is being saved by avoiding copies is probably negligible in front of how slow several writings to gsettings key are.

>But this only takes into account the situation when the bands are not splitted. For the split band scenario we have to make the whole process also for settings_right.

I think that any approach will have this downside. So we will have to live with it.

>what do you think? Is it doable or there's something I'm missing?

It should work. The only thing that can be worrying is that the act of creating many bands by itself is unfortunately really slow even using the container that is optimized for this. By forcing gsettings writings in the process we may make this even worse when 15 or more bands are used. But only trying we will know what is actually going to happen. So feel free to go ahead :-).

On a different topic gtk 4.10 deprated all the functions we use for file dialogs. As they are targeting gtk 5 we have time. But maybe if we use the functions they are recommending the file dialogs problems will go away. I will try to take a look at this when I have time.

**Comment by wwmm** [comment]
But again only trying we will know how concerning performance will actually be.

**Comment by Digitalone1** [comment]
> It should work. The only thing that can be worrying is that the act of creating many bands by itself is unfortunately really slow even using the container that is optimized for this. By forcing gsettings writings in the process we may make this even worse when 15 or more bands are used. But only trying we will know what is actually going to happen. So feel free to go ahead :-).

Why is it a problem on band creation? Do you want to sort bands on creation? I did not specify it, but my intention was to sort only when a button is clicked in the GUI.

Gsettings copies are expensive, but we already avoid them when the values are equals, right? So it still depends on how the bands are unsorted, but we have the advantage that the sort is retained on next sessions and it can be stored in a preset.  

> On a different topic gtk 4.10 deprated all the functions we use for file dialogs. As they are targeting gtk 5 we have time. But maybe if we use the functions they are recommending the file dialogs problems will go away. I will try to take a look at this when I have time.

Please make a new issue listing which functions are deprecated. I will take a look at it.

**Comment by Digitalone1** [comment]
So I wanted to test this but I can't compile because of the deprecation.

I managed to correctly change `gtk_widget_show` and `gtk_widget_hide`, but for the other functions I don't have any clue on how to do it.

Is there a way I can still compile even on deprecation?

**Comment by wwmm** [comment]
>Why is it a problem on band creation? Do you want to sort bands on creation? I did not specify it, but my intention was to sort only when a button is clicked in the GUI.

Oh... Right. In this case widgets do not need to be destroyed.

>Gsettings copies are expensive, but we already avoid them when the values are equals, right? 

A few naive comparisons are in place to avoid most of the writes if the values are equal. But depending on how the bands parameters are configured and on the amount of them there can be potentially a lot of writes while doing the sorting this way. If it will be something to be concerned about only tests will tell.

>Please make a new issue listing which functions are deprecated. I will take a look at it.

As you probably have already noticed the compiler shows them.

>So I wanted to test this but I can't compile because of the deprecation.

Strange. I can compile with them just fine. But Iǘe notice that the Arch Linux image on our github actions can't. Probably because the devel build is enabling the compiler option that forces the compilation to abort on deprecated code. ARe you compiling with the `Devel` option given to Meson?

**Comment by wwmm** [comment]
This option https://github.com/wwmm/easyeffects/blob/ce43c2f8d71c69459cf3f7b3450c7366563352d2/meson.build#L57. But if you are not using `Devel` I do not know why the compilation is aborting on those messages. The AUR pkgbuild also still works on my computer.

**Comment by Digitalone1** [comment]
> > Why is it a problem on band creation? Do you want to sort bands on creation? I did not specify it, but my intention was to sort only when a button is clicked in the GUI.
> 
> Oh... Right. In this case widgets do not need to be destroyed.
> 
> > Gsettings copies are expensive, but we already avoid them when the values are equals, right?
> 
> A few naive comparisons are in place to avoid most of the writes if the values are equal. But depending on how the bands parameters are configured and on the amount of them there can be potentially a lot of writes while doing the sorting this way. If it will be something to be concerned about only tests will tell.
> 
> > Please make a new issue listing which functions are deprecated. I will take a look at it.
> 
> As you probably have already noticed the compiler shows them.
> 
> > So I wanted to test this but I can't compile because of the deprecation.
> 
> Strange. I can compile with them just fine. But I've noticed that the Arch Linux image on our github actions can't. Probably because the devel build is enabling the compiler option that forces the compilation to abort on deprecated code. Are you compiling with the `Devel` option given to Meson?

**Comment by Digitalone1** [comment]
> But if you are not using `Devel` I do not know why the compilation is aborting on those messages. The AUR pkgbuild also still works on my computer.


I gave ninja command in build folder, don't know if I'm on devel or not. I will try in the weekend.

**Comment by vchernin** [comment]
I am admittedly not sure why I tacked on -Werror onto the devel meson option. It is good to use, but it is best in a separate CI flag in meson or something. Usually you don't want things like unused variable warnings to be stopping development builds...

**Comment by Digitalone1** [comment]
> A few naive comparisons are in place to avoid most of the writes if the values are equal. But depending on how the bands parameters are configured and on the amount of them there can be potentially a lot of writes while doing the sorting this way. If it will be something to be concerned about only tests will tell.

We could estimate that, if all the values of a band are different, there should be 7 copies (3 strings/enums, 3 doubles and 2 bools). Then this should be multiplied for the number of used bands.

**Comment by Digitalone1** [comment]
In the first post I said only two copies, but I was considering the whole amount of data. The first copy as the construction of the multimap, then the copy of the data contained in the multimap to gsettings. Sure considering primitive types contained in the multimap, the copies are higher.

**Comment by vchernin** [comment]
>  Probably because the devel build is enabling the compiler option that forces the compilation to abort on deprecated code. 

Fixed this in https://github.com/wwmm/easyeffects/pull/2164

**Comment by wwmm** [comment]
They deprecated the `GtkComboBox` and the `GtkComboBoxText` widgets :O. Now the docs says `Use GtkDropDown with a GtkStringList instead.`. Well... We already use GtkDropdown in some places. But replacing all the combo boxes by it will be a little tedious. Specially where `gtk_combo_box_set_active` is used... But it is what it is...

**Comment by bhack** [comment]
> . But as far as I could see the huge performance bottleneck is in GTK and not in the vector sort. For some reason the amount of widgets per band seems too much for gtk to create many bands in a short time.

Yes I agree. I am quite sure the in this case `θ` is `std::ranges::sort` but  GStetting key handling and/or GTK widgets handling.

**Comment by Digitalone1** [comment]
Anyway I ported the code and managed to compile it correctly. Didn't have the time to test it yet, but if everything goes right we will have a sorting feature that is storable in presets. This is a good advantage even if the performance are not good.

**Comment by Digitalone1** [comment]
It's working. Tested with 32 bands, it's very fast. I'll let you judge, will make the PR.
