### ISSUE TITLE
Verifying Flathub page?

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#2163]
Flathub’s newer webpage now has a [verification badge](https://beta.flathub.org/about). It is mainly meant to show the app author has control over the published app on Flathub. Even though this is still a new feature, it seems easy enough to enable already, if you think it makes sense.

You should be able to login with GitHub here, and then verify Easy Effects, and maybe PulseEffects too by clicking on developer settings for each app:

https://beta.flathub.org/userpage

**Comment by wwmm** [comment]
Done. I verified both of them. But I admit I did not see where is the badge in the page :smile:

**Comment by vchernin** [comment]
> Done. I verified both of them. But I admit I did not see where is the badge in the page :smile: 

It seems to take a couple minutes, I refreshed a few times but it shows up now: https://beta.flathub.org/apps/com.github.wwmm.easyeffects
