### ISSUE TITLE
Blocks/freezes GNOME UI = top menu and all other apps

### ISSUE THREAD

**Issue by peter-kehl** [wwmm/easyeffects#2184]
Thank you for Easy Effects, Wellington.

### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro (Arch Linux, but more stable)

### Summary
Pressing "Add Effect" button blocks/freezes ability to switch to any other GNOME/X11 apps/windows, and most of GNOME.

### Details

Have Easy Effects started, with default settings, no effect applied. (1 output player - Google Chrome. But that makes no difference, the following happened even with no players.)

Click Output (tab at the top) > Effects (tab at the bottom) > "Add Effect" button on the left. I do not type anything, nor I choose any effect at all.

Right at that point (when the small Effects search/filter and list popup is shown), I can't anymore:
-  switch to other apps with Ctrl+TAB, neither through GNOME Dashboard, nor through clicking at an (existing open) window of  any other application;
- I have GNOME Dashboard "moved to dock" with "Dash to Dock" GNOME extension (recommended/built-in on Manjaro), and set to auto-hide. When I move the mouse over it, it does show up. But it doesn't let me switch to any (already running) apps, nor it starts any other apps.
- use the GNOME Panel (usually at the bottom, I have it configured to be at at top). I have it on authohide, and the panel does show up when I move mouse over; but the menu items don't show up, neither react, when I click;
- even take a screenshot (with "Print Screen" key, Alt + "Print Screen", Shift + "Print Screen" - which do work otherwise)
until I click outside the small Effects search/filter and list popup. I have to click somewhere in Easy Effects window - if I click outside it, it doesn't switch.
- change volume of any sound (if playing anything) with volume buttons on my keyboard, nor with volume controls on my USB headset.

### Expected Behavior

Still be allowed to switch to other apps, use the GNOME Panel, etc.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
export G_MESSAGES_DEBUG=easyeffects
easyeffects

# console output from the above:
(process:67302): easyeffects-DEBUG: 12:04:39.939: 	easyeffects.cpp:35	easyeffects version: 7.0.0
(process:67302): easyeffects-DEBUG: 12:04:39.940: 	easyeffects.cpp:45	locale directory: /usr/share/locale
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:49	system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:49	system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:52	system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:52	system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:194	user presets directory already exists: /home/pkehl/.config/easyeffects/
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:194	user presets directory already exists: /home/pkehl/.config/easyeffects/input
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:194	user presets directory already exists: /home/pkehl/.config/easyeffects/output
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:194	user presets directory already exists: /home/pkehl/.config/easyeffects/autoload/input
(easyeffects:67302): easyeffects-DEBUG: 12:04:39.945: 	presets_manager.cpp:194	user presets directory already exists: /home/pkehl/.config/easyeffects/autoload/output
(easyeffects:67302): easyeffects-DEBUG: 12:04:40.050: 	easyeffects.cpp:60	Exitting the main function with status: 1
```
</details>

`/etc/easyeffects` does NOT exist.

### Additional Information

GNOME version: 43.3:
![image](https://user-images.githubusercontent.com/4270240/225721005-b0e9329c-a564-4ef0-a1a0-d6c0d89179bb.png)

I've disabled all GNOME extensions, rebooted, and the first application that I started was Easy Effects. But, the problem has been still there.

The same for these kernels:
- Current Manjaro x64 kernel `6.2.6-1` updated today:
  `Linux spectre 6.2.6-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Mar 13 12:59:13 UTC 2023 x86_64 GNU/Linux`
- `6.1.19-1` (long term support):
  `Linux spectre 6.1.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC`
- `5.15.102-1` (long term support):
  `Linux spectre 5.15.102-1-MANJARO #1 SMP PREEMPT`

I have not used Easy Effects before, so I can't tell when this problem started.

**Comment by wwmm** [comment]
It is the same as #1182 and affects specially Xorg users. It is a known gtk4 problem. They have some open issues on their side about this. Unfortunately nothing that can be done in EasyEffects to really fix this problem. The closest thing to a workaround I could ever find is the option `Hide Menus on outside Clicks` I have added to EasyEffects preferences window. The downside is that if you disable it the only way to close the menu is clicking on its button.

**Comment by peter-kehl** [comment]
Thank you so much for following up, and for the workaround setting. I'll
give it a thumbs up on GTK4 @ GNOME.org, too.
