### ISSUE TITLE
Filter: Allow selecting frequencies with a slider instead of the 'increase' and 'decrease' buttons.

### ISSUE THREAD

**Issue by NahrWahr** [wwmm/easyeffects#2185]
While setting up filters by ear to hear a particular instrument or setting up speakers, its quite tedious to input the frequencies by numerical value one by one, and going back and forth till you find it to sound satisfactory. 

Instead there should be a slider which goes from 20Hz to 20.000Hz. Makes testing different frequencies for picking out the part you want to hear a lot easier, when you get to move the slider and hear the change. The way it usually is in new DAWs and mixing software.

**Comment by wwmm** [comment]
>Instead there should be a slider which goes from 20Hz to 20.000Hz. Makes testing different frequencies for picking out the part you want to hear a lot easier

But at the same time when you already know the frequency you want using the slider may be annoying if its step does not match the value you want. I do not think it is a good idea to replace the spinbutton by a slider.

**Comment by wwmm** [comment]
In the case of the plugins that come from Linux Studio Plugins the native plugin window can be used for this. I think that the current state of things is as good as it can get.
