### ISSUE TITLE
T14s G3 AMD: My created .irs concolver file creates a huge audio delay

### ISSUE THREAD

**Issue by Utini2000** [wwmm/easyeffects#2209]
### EasyEffects Version

7.0.1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I created my own .irs convolver file which outputs the correct sound quality but causes a huge audio delay on my system.
Download Link: https://files.bestmail.ws/Arch/T14s_G3_AMD/T14s_G3_AMD_Dolby_Convolver.zip
System: Thinkpad T14s Gen 3 AMD Ryzen 7 PRO 6850u

How I created the .irs file:
Boot Windows
Configure Dolby Atmos settings preset to movies or music
Play an 48kHz impulse tone and 0dB
Record that impulse tone in audacity (setting input = output)
Crop the recording to the impulse tone
Export it as .wav and rename that to .irs

### Expected Behavior

Convolver file shouldn't cause a delay

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>Convolver file shouldn't cause a delay

I am not an expert on audio convolution but I have my doubts this is necessarily true. Comparing your impulse file with others I have downloaded from the internet something that called my attention is how larger it is the `duration` file in your impulse. It is above `2 seconds` when the vast majority of the impulses I have here do not get near half a second. I am not sure if the duration can be arbitrarily large without consequences.

**Comment by Utini2000** [comment]
Well as soon as I remove the convolver plugin, the delay is gone. 
Have you maybe tried my file on your system? 

I used this audio impulse file to generate the .irs: https://freesound.org/people/unfa/sounds/205620/
So if it is too long, should I just crop it further? Even if that means that some parts of the impulse will be cropped out then?

**Comment by wwmm** [comment]
>Have you maybe tried my file on your system?

Yes. I can see the delay. But I am not sure about the cause. I implemented our convolver using the `zita-convolver` library that is supposed to do realtime convolution without adding latency. But it is not clear to me if that is still the case when the impulse is very long.

>So if it is too long, should I just crop it further? Even if that means that some parts of the impulse will be cropped out then?

I honestly do not know. I have never tried to create an impulse. Considering I have seen in the internet impulses as long as 28 seconds I imagine that ins some situations it is what it is. The question is if zita-convolver will still be zero-latency with these sizes...

**Comment by Utini2000** [comment]
Alright, I shorted the .irs file by a lot. Basically I trimmed it to the very middle part that shows some "real" frequency response. 
The file size is now 312 Bytes vs before 383 KiloBytes.
This removed the delay and the sound quality is mostly the same but still worse than with the big file.
Out of interest I shorted the .irs file even more to just 188 Bytes. This will cause an even worse sound quality.

So shorting does impact the sound quality negatively but this can be tolerated as long as it is not shorted too much. 
I can live with the compromise of the shortened .irs file to get not audio delay. 
So for me this is fine / fixed :) Not sure if you want to keep this open since there still is some underlying issue?

**Comment by Utini2000** [comment]
Increased the size / crop to 600 Bytes... not it sounds almost the same and I can't notice any lag.
Can you notice a lag? Link: https://files.bestmail.ws/Arch/T14s_G3_AMD/T14S_G3_Music_Movies.irs

**Comment by wwmm** [comment]
>Increased the size / crop to 600 Bytes... not it sounds almost the same and I can't notice any lag.
Can you notice a lag? 

I also can not notice the lag.

**Comment by mdsmendes94** [comment]
I have the same exact issue
@Utini2000 Were you able to further improve your impulse without the delay or figuring out what's causing the delay?

**Comment by Utini2000** [comment]
> I have the same exact issue @Utini2000 Were you able to further improve your impulse without the delay or figuring out what's causing the delay?

Yes, see: https://github.com/wwmm/easyeffects/issues/2209#issuecomment-1485525404

**Comment by Utini2000** [comment]
Closing btw :)

**Comment by mdsmendes94** [comment]
> > I have the same exact issue @Utini2000 Were you able to further improve your impulse without the delay or figuring out what's causing the delay?
> 
> Yes, see: [#2209 (comment)](https://github.com/wwmm/easyeffects/issues/2209#issuecomment-1485525404)

I have a guess on whats causing the bad quality audio, it's lack of samples. When trimming your impulse audio change to spectogram and trim only where there are colours. That's the only way I found to optimize, size, duration and quality.

![image](https://github.com/user-attachments/assets/dea3a97f-ddc8-48db-90bd-40a1a9e13296)
Top is mine with far more samples
Bottom is yours with less samples generating less sound quality

But yea trim using the impulse using where the spectogram start and ends result in better quality for audio
