### ISSUE TITLE
How to replace GTK4 ComboBox

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2210]
I wonder how to do this.

In the XML UI is very easy, but in the code we use this:

https://github.com/wwmm/easyeffects/blob/master/src/filter_ui.cpp#L110

I don't know if it's reusable for [DropDown](https://docs.gtk.org/gtk4/class.DropDown.html) using the `active-id`. I have to try compiling when have time...

But maybe we should also take in consideration moving to [AdwComboRow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.ComboRow.html)? It seems similar to GTK4 DropDown having the same `activate` signal inherited by AdwActionRow (the same signal is used in the DrowDown).

Whow knows if libadwaita will deprecate also AdwComboRow in the future. Maybe we should ask to them...

**Comment by wwmm** [comment]
>I don't know if it's reusable for [DropDown](https://docs.gtk.org/gtk4/class.DropDown.html) using the active-id.

It does not have `active-id`. The closest thing is `gtk_drop_down_set_selected` that uses the position id. So all those bindings will have to be reimplemented in a different way. Unfortunately =/

>But maybe we should also take in consideration moving to AdwComboRow? It seems similar to GTK4 DropDown having the same activate signal inherited by AdwActionRow (the same signal is used in the DrowDown).

Maybe. But I think that the last time I played with it it only worked right when wrapped by a libadwaita container I do not remember the name now. So we have to think if it isn't easier to just use gtkdropdown.

>Whow knows if libadwaita will deprecate also AdwComboRow in the future. Maybe we should ask to them...

I think it does not use gtkcombobox. So it should be fine to use it if it works in the same place the comboboxes are now without having to change the ui too much.

**Comment by Digitalone1** [comment]
Maybe we should use the bind with mapping, getting the `guint` position and giving it to [g_settings_set_enum](https://docs.gtk.org/gio/method.Settings.set_enum.html).

**Comment by Digitalone1** [comment]
> As gtkdropdown requires a model maybe there is a way to do the binding to the model in a similar way we do now. I did not have time yet to investigate this.

Where? Can you link it?

I see that [GListModel](https://docs.gtk.org/gio/iface.ListModel.html) does not have any `giunt` property to signal the selected item. Besides the item can be retrieved by `giunt` position, but gsettings returns a string (enum), so it seems there's still the issue of converting the string to the guint.

**Comment by wwmm** [comment]
>Where? Can you link it?

I am just hoping that it has a way to make the binding 😄. I do not know if it is actually possible. In some examples they use a stringlist object that seems more high level than the base glistmodel. Maybe it has a smarter way to do the binding.

**Comment by wwmm** [comment]
>If you want to bind this to GSettings, you can use the selected-item property of the GtkDropDown to update the settings storage.

Hmm... Worth taking a look at.

**Comment by wwmm** [comment]
>I am seriously considering using integer keys instead of enums for these settings...

But if we do that we will have to change many other things that are working fine while breaking presets again... So it is not an option...

**Comment by Digitalone1** [comment]
Anyway if an enum is set with a `guint`, I don't get why the bindings has to use the strings.

It's more an issue related to gsettings here.

Besides gsettings documentation for `set_enum` says its possible to get the `nick` with `get_string`, so maybe it's possible to set an enum using a string with `set_string`. The problem is that, if this works, it should work only in English because the string retrieved from the DropDown is the one translated.

I think the only way is using mappings and set enum with DropDown  position (`get_selected`) and DropDown selection with enum (`get_uint`). Using `user_data` in a smart way with pairs or tuples, there should be a way to cast to the needed data and reuse one single function in user interface utils for all this tasks.

**Comment by wwmm** [comment]
>The problem is that, if this works, it should work only in English because the string retrieved from the DropDown is the one translated.

Probably. That is what happens in the GTKCOMBOBOXTEXT if active-id is not used. Translations break the code.

>I think the only way is using mappings and setting the enum with DropDown position (get_selected) and the DropDown selection with enum (get_uint). Using user_data in a smart way with pairs or tuples, there should be a way to cast to the needed data and reuse one single function in user interface utils for all this tasks.

I have my doubts about how reusable a mapping function can be. Let's look at https://github.com/wwmm/easyeffects/blob/57cd192f7a09ed03daaa34c8493d13c1275777e7/src/filter_ui.cpp#L24 for example. Each binding requries 2 mapping functions where we had to hardcode all the strings that already are in the gsettings schema. Besides how dumb and tiring this approach was the problem in duplicating strings is that now we have more places to check if they are right and matching the ones from other locations. Even if we find a clever way to use tuples, pairs, etc it does not look like we can avoid hardcoding these strings somewhere. That is what I dislike the most in this approach. These strings are already in the schema and in ui xml. Now we will have third place to check for them...

I will investigate if the "gobject" approach suggested by the gtk developer in that discussion can somehow avoid this. But I do not have my hopes high =/

**Comment by wwmm** [comment]
I implemented a wrapper for the dropdown binding https://github.com/wwmm/easyeffects/commit/fe771d58a6ebe9d3e4f0b700bb2f8843a05469a3. I think it is ridiculous we have to resort to something like this but it is better than the string hardcoding that comes with the standard biding_with_mapping. Now we have to test this wrapper and make sure that the conditionals I put in place are enough to avoid an infinity signal loop.

**Comment by wwmm** [comment]
>Besides I think there's an issue in the current implementation because you track the connections, but in the template you return only the last one. Maybe we need to return both?

The connection to the widget object will die once the widget is destroyed. The one to gsettings probably will when the filter is removed. But sometimes gsettings connections done with `g_signal_connect` live longer than expected or do not even finish. So these ones I track as a failsafe.

>But with mappings we don't need to track connections, right?

It shouldn't be needed. I am not sure if we even can tracking them because `g_settings_bind_with_mapping` does not return a handle_id. 

>If you prefer this approach, I will make the PR.

It is a good approach. Just the extra writing to gsettings that makes a little concerned about dumb backends like the one used by Flatpak. As we have quite a lot of combo to be converted to dropdown these extra writings may add up.  I am looking at `GSettingsBindSetMapping` docs and it says the following about the return type

>a new GVariant holding the data from value , or NULL in case of an error

I wonder what it does if we just return null. Does it prints error messages to the terminal or just silently move on? Maybe we can just return null to avoid the extra writing if gsettings does not go crazy about this.

>And another thing. In various parts of the code I see the static_cast of pointers mixed with auto and auto*. Isn't it better to have always auto* p_name = static_cast<Type*>(...);?

Yes. The places that aren't are probably the ones where clang-tidy suggestions were not implemented yet. It usually suggests this for readability reasons.

**Comment by wwmm** [comment]
>Just the extra writing to gsettings that makes a little concerned about dumb backends like the one used by Flatpak

Thinking about it again it may not be a concerning. This writing will only happen when manually selecting a new value in the dropdown. It is not the same as loading a preset file where many keys are changed at once. I think it is fine to do the PR.

**Comment by Digitalone1** [comment]
If I return `nullptr`, I get 

```
invalid conversion from ‘std::nullptr_t (*)(const GValue*, const GVariantType*, gpointer)’ 
{aka ‘std::nullptr_t (*)(const GValue*, const GVariantType*, void*)’} to 
‘GSettingsBindSetMapping’ {aka ‘GVariant* (*)(const GValue*, const GVariantType*, void*)’} [-fpermissive]
```

Tried also to return `g_variant_new("ms", nullptr);` as suggested [here](https://docs.gtk.org/glib/ctor.Variant.new_string.html), it compiles, but I get a core dump after changing the dropdown.

> Thinking about it again it may not be a concerning. This writing will only happen when manually selecting a new value in the dropdown. It is not the same as loading a preset file where many keys are changed at once. I think it is fine to do the PR.

Ok.

**Comment by Digitalone1** [comment]
So this can be closed. Now it's only a matter of changing the XML and using the GtkDropDown with the binding template on all ComboBox widgets.

@wwmm is this the only thing to do to remove all the deprecations?

**Comment by wwmm** [comment]
>is this the only thing to do to remove all the deprecations?

I think it is. At least the other warnings I've noticed I have already removed.

**Comment by wwmm** [comment]
>I found out that this method does not work with tags. The template expect a string literal...

I did not fully understand how you are trying to use it with tags. Where will this be necessary?

**Comment by Digitalone1** [comment]
> I did not fully understand how you are trying to use it with tags. Where will this be necessary?

Here for example:

https://github.com/wwmm/easyeffects/blob/master/src/equalizer_band_box.cpp#L115-L122

**Comment by Digitalone1** [comment]
Maybe it's worth to reopen and find a new solution. :(

**Comment by wwmm** [comment]
>Maybe it's worth to reopen and find a new solution. :(

Yes. That is really unfortunate :disappointed:. I totally forgot about these cases where we do not have a string literal for the template. I will we will have to make the string a runtime argument in `gsettings_bind_enum_to_dropdown`. THe annoyance will be to pass both gsettings and the string to the bind_with_mapping. But it should be doable.

**Comment by wwmm** [comment]
>I think we will have to make the string a runtime argument in gsettings_bind_enum_to_dropdown.

And in this case it probably won't make sense to keep this function as a template.

**Comment by wwmm** [comment]
>I wanted to use a pair to store both settings and the key string to pass as user_data. What do you think about this solution?

It should work if you do something similar to what is done in https://github.com/wwmm/easyeffects/blob/41837bc08b4d5bc98a8378eae4b79a1005c446a8/src/util.cpp#L279. The reason is that user_data is a pointer. Depending to what it is the object may be destroyed once `gsettings_bind_enum_to_dropdown` finishes. It took me quite some time to realize how to handle this problem when implementing util::idle_add.

**Comment by wwmm** [comment]
The `destroy` callback `g_settings_bind_with_mapping` has as last argument would have to be used to destroy the user_data structure memory. But it should work.

**Comment by Digitalone1** [comment]
I did the following, but I haven't the time to test it now.

```c++
void gsettings_bind_enum_to_dropdown(GSettings* settings,
                                     const gchar* key,
                                     GtkDropDown* dropdown,
                                     GSettingsBindFlags flags = G_SETTINGS_BIND_DEFAULT) {
  struct Data {
    std::pair<GSettings*, const gchar*> p{settings, key};
  };

  g_settings_bind_with_mapping(
      settings, key, dropdown, "selected", flags,
      +[](GValue* value, GVariant* variant, gpointer user_data) {
        auto* d = static_cast<Data*>(user_data);
        g_value_set_uint(value, static_cast<guint>(g_settings_get_enum(std::get<0>(d->p), std::get<1>(d->p))));
        return 1;
      },
      +[](const GValue* value, const GVariantType* expected_type, gpointer user_data) {
        auto* d = static_cast<Data*>(user_data);
        g_settings_set_enum(std::get<0>(d->p), std::get<1>(d->p), static_cast<gint>(g_value_get_uint(value)));
        return g_variant_new_string(g_settings_get_string(std::get<0>(d->p), std::get<1>(d->p)));
      },
      new Data(), nullptr);
}
```

Will try this evening, but you say to add a final callable to delete `Data`, right?

**Comment by wwmm** [comment]
>but you say to add a final callable to delete Data, right?

If we don't there will be memory leaks caused by `new Data()` not being destroyed.

>std::pair<GSettings*, const gchar*> p{settings, key};

Is the pair really needed? I think we can just create 2 struct members. One named settings and the other key.

**Comment by wwmm** [comment]
>You're right. I thought the use the pair because I didn't know the data had to be wrapped in a structure.

I imagine that the structure could be replaced by something like `new std::pair`. But it seems simpler and more flexible to use a structure.

**Comment by Digitalone1** [comment]
> > You're right. I thought the use the pair because I didn't know the data had to be wrapped in a structure.
> 
> I imagine that the structure could be replaced by something like `new std::pair`. But it seems simpler and more flexible to use a structure.

I wanted to use only the pair, but how can I create a new one? Will it work with `new`?

**Comment by Digitalone1** [comment]
No luck, still not working on the equalizer band. Now because of the sensitive bind.

https://github.com/wwmm/easyeffects/blob/master/data/ui/equalizer_band.ui#L63-L67

Tried to change to `selected` lookup and refactoring the callback, but I got a core dump.

I will make a draft PR. Maybe you @wwmm can resolve it.

**Comment by wwmm** [comment]
>Tried to change to selected lookup and refactoring the callback, but I got a core dump.

Ok. I will take a look at it now.

**Comment by Digitalone1** [comment]
@wwmm I see you fixed it. I though to do the same, but used `guint*` rather than `guint`.

Where can I see the signature of those callables on the documentation? There are other parts to replace the sensitive bindings, expecially in the Compressor.

**Comment by wwmm** [comment]
>Where can I see the signature of those callables on the documentation? There are other parts to replace the sensitive bindings, expecially in the Compressor.

The most I have ever seen about it in the documentation is https://docs.gtk.org/gtk4/class.Expression.html. But it does not really talk about the function signature. I had to look at some of the GTK source code to figure out that after the pointer to the widget they put the variables retrieved by the gtkexpression through the `lookup`. In the closure that sets the sensitive property we have
```
<lookup name="selected">band_type</lookup>
```
. So the callback arguments have to be
```
auto set_band_scale_sensitive(EqualizerBandBox* self, guint selected_id) -> gboolean {
```
because the widget template class is named `EqualizerBandBox` and there is only one lookup for a property of type `guint`.  If there are more properties being looked up like in 
```
<closure type="gchararray" function="set_band_width_label">
    <lookup name="value">band_quality</lookup>
    <lookup name="value">band_frequency</lookup>
</closure>
```
then the callback has to have 3 arguments matching the types of whatever is being looked up
```
auto set_band_width_label(EqualizerBandBox* self, double quality, double frequency) -> const char* {
```
The return type has to match the type of the destination property. As the closure above is setting a GtkLabel text its return type has to be a const char*.

**Comment by Digitalone1** [comment]
OK.
