### ISSUE TITLE
Core dump or Equalizer reset

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2215]
Always reproducible on latest master after clicking the reset button.

I got the following error:

```
GLib-GIO:ERROR:../glib/gio/gsettings.c:504:settings_backend_keys_changed: assertion failed: (l < 256)
Bail out! GLib-GIO:ERROR:../glib/gio/gsettings.c:504:settings_backend_keys_changed: assertion failed: (l < 256)
Annullato (core dump creato)
```

Update: It does not happen on stable release.

**Comment by wwmm** [comment]
Same thing here. The last change in the reset function was the use of `g_settings_delay` and `g_settings_apply` to increase performance on Flatpak. At the time I did not test the equalizer reset. I will see if removing these functions fixes the crash.

**Comment by wwmm** [comment]
>I will see if removing these functions fixes the crash.

It does. That is really unexpected. Honestly I do not understand why gsettings is crashing just because we are delaying the calls inside the for loop. @vchernin we may have to degrade flatpak performance again...

**Comment by wwmm** [comment]
Each channel gsettings object is created as 
```
self->settings = g_settings_new_with_path(tags::schema::equalizer::id, schema_path.c_str());

self->settings_left =
      g_settings_new_with_path(tags::schema::equalizer::channel_id, (schema_path + "leftchannel/").c_str());

self->settings_right =
      g_settings_new_with_path(tags::schema::equalizer::channel_id, (schema_path + "rightchannel/").c_str());
```

Once everything is set they are relocatable schemas that are children of the one in `self-settings`. The other plugins do not go this deep. Only the equalizer because it makes sense to split each channel in their own schema. But as there are equalizer settings that affect both each channel schema is configured as children of the main equalizer schema. For some weird reason delayed mode is not playing nice with this setup.

**Comment by Digitalone1** [comment]
Maybe the first path cleans already both children (channels) and the delayed ones crash because they're empty?

I'm asking because if this is the reason, I wonder why it doesn't happen where they are not delayed. Even if there's no delay, I suppose the children are already missing after cleaning the parent.

**Comment by Digitalone1** [comment]
No, unfortunately it's not what I was supposing. Resetting a path it's only cleaning keys on the same level, not also keys on their subpaths.

But maybe I understood the issue. Will make other tests...

**Comment by Digitalone1** [comment]
The crash is happening [here](https://github.com/GNOME/glib/blob/main/gio/gsettings.c#L504).

I don't fully understand this code, but it seems they won't allow more than 256 changes (in delay mode). Likely the equalizer has more than 256 keys to change.

I resolved the issue restoring the delay and making checks on changes count. Will make the PR this afternoon.
