### ISSUE TITLE
Adding an equalizer band resets all filters to Bell type

### ISSUE THREAD

**Issue by ttttcrngyblflpp** [wwmm/easyeffects#2219]
### EasyEffects Version

7.0.0

### What package are you using?

Other (specify below)

### Distribution

Debian 5.19.11

### Describe the bug

Adding a band to the equalizer settings causes all existing filters to have their type reset to Bell.

### Expected Behavior

Adding a band should not change settings of the existing filters.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Same thing as #1472. So we can close this issue.
