### ISSUE TITLE
Excluded list disappears and EasyEffects gets unresponsive when working with it.

### ISSUE THREAD

**Issue by BayouGuru67** [wwmm/easyeffects#2225]
### EasyEffects Version

7.0.1

### What package are you using?

FlatPack

### Distribution

Kubuntu 22.04 LTS

### Describe the bug

The excluded applications list disappears when rebooting.  This has been an annoying ongoing problem for me with every version of pulse and easyeffects tried thus far.  It is annoying because there are quite a few applications that respond quite unfavorably to EasyEffects and must be excluded, and this bug makes EasyEffects anything but Easy to deal with!  

Additionally, when working with the list, the application becomes unresponsive in that the excluded applications list dialog won't close if you add more than one program to the list, and sometimes even if just adding one!  It does not do this when simply looking at the list.  The EasyEffects window becomes very sluggish or completely unresponsive to the point of needing a killall easyeffects from the terminal.  System monitoring tools do not show an unusual peak in CPU usage when this is happening.

The effects do continue to render when the interface goes catatonic, so there's that.  :)  

FYI, I generally never shut off my computer, I have it set so that just the screen shuts off after an inactivity period.  EasyEffects is set to run on startup.  My normal effects load is a Filter, AutoGain, Compression and Limiting, with the Filter being used on a more part-time basis via a separate preset.  The effects presets seem to work fine, the program's current issues for me are wholly centered around the excluded list.

### Expected Behavior

The excluded programs list is expected to remain present and in effect once EasyEffects is restarted after rebooting.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Commit: 857d33f
```
</details>

**Comment by Digitalone1** [comment]
> The excluded programs list is expected to remain present and in effect once EasyEffects is restarted after rebooting.

For this, load the excluded list and save the preset which autoloads at the next reboot.

**Comment by BayouGuru67** [comment]
Thank you very much!  That and the Esc button info "solved" those issues for me.  So, FYI, clicking on the button or the arrow on the button may or may not work once you have added programs to the excluded list.  Esc seems to work regardless.  I am very thankful for the knowledge!  I do still have some issues with the software, and am passing this on to you as suggestion(s) from some broke old dude who loves your software and uses it every day.  Please do not be offended by my directness.  I got used to being this way back when I was beta testing Atari software decades ago.

I'm guessing it's the counter-intuitive placement of the excluded apps button in the bottom-right corner of the players screen, down in what is generally seen as the "global" section of the app, where the global performance info is shown, (albeit across the screen) and about as far away from everything else as one could possibly get for accessing something functionally-tied to a preset (without requiring a second monitor) that threw me.  

Kinda makes me wonder why that and the players buttons are there in the first place when there's unused left-menu entries there just wasting space that could not only serve to house the data from those buttons but allow for consolidation of the interface into a much more logical and intuitive layout with the left menu and effects list staying put, because that's what this app is for, and the excluded apps can go on the right screen of the players left menu item with the rest of the players/sources and related information from what is currently inside the bottom-of-screen players and presets buttons.  In this way, all of the inconveniently-placed buttons at the bottom of the screen can go away entirely, with that space now only needed if you wish to keep the real time performance stats there, which also means more space for the effects/info above.  This also gives the left menu "Players" text an actual purpose and allows for a simplification of the interface while retaining all of the functionality and increasing the ergonomic efficiency for the end user.  
"Test Signal" in the "Pipewire" tab could go to the right screen of  the Output left menu, giving it purpose, with perhaps a rudimentary output source mixer between the test signal and whatever's playing (if anything).  Could also be a mute all other sources checkbox.
Preset Auto-loading could go into the right screen of the now-functional "players" left menu item where it's more relevant/accessible than under a Pipewire tab's submenu.  
Additionally, A global/per-preset option for each excluded app sure would make life easier, because **all** of my excluded apps hate **all** of the presets, so I am having to duplicate my exclusion lists over and over again for all the presets.  That's a pain.  If something doesn't like EasyEffects, per-preset becomes kinda irrelevant, clunky and annoying to deal with, especially if you have a half-dozen or so presets for different "occasions". For my purposes, the exclusion list is for dealing with the residual pipewire/easyeffects incompatibilities that munge my audio output globally.  Has nothing to do with presets from my perspective as a user.
