### ISSUE TITLE
EE crashes due to the filter updating parameters from the data thread

### ISSUE THREAD

**Issue by pinkflames** [wwmm/easyeffects#2228]
### EasyEffects Version

7.0.1

### What package are you using?

Gentoo

### Distribution

Gentoo

### Describe the bug

I have been observing EasyEffects crashing. The may or may not be recent issue, as I'm quite okay with jank and I do restart PipeWire and everything related to it multiple times a day.

According to Wim: `the filter is updating parameters from the data, thread, that's not allowed` and `you can't to anything IPC in the process callback`.

Unfortunately I'm not familiar with the details, so you'll need to ask him, if you have any questions.

### Debug Log

Here's a [sanitized and pruned coredumpctl info output](https://github.com/wwmm/easyeffects/files/11113031/coredumpctl-info.txt) that made Wim conclude that EE is doing something it should not be doing.

**Comment by wtay** [comment]
The easiest is to do pw_loop_invoke() on the main loop, it's like idle add but you can call it from the data thread.

**Comment by wwmm** [comment]
>The easiest is to do pw_loop_invoke() on the main loop, it's like idle add but you can call it from the data thread.

Is `pw_loop_invoke` used somewhere in pipewire to call `pw_filter_update_params`? It is not obvious how to use `pw_loop_invoke`. 

I am using `pw_thread_loop`. Is there anything else that has to be done because of this?

**Comment by wwmm** [comment]
I think I understood how to use pw_loop_invoke but now I am stuck in a weird `invalid use of incomplete type ‘struct pw_thread_loop’`. The funny thing is that on other parts of our code the threaded loop object can be accesseed just fine.

**Comment by wwmm** [comment]
I am doing some tests and the incomplete type error only happens with pw_loop_invoke. Other functions like `pw_thread_loop_start` compile without problems in the same location. I imagine that the fact pw_loop_invoke is a macro is somehow related.

**Comment by wwmm** [comment]
I tried

>pw_loop_invoke(reinterpret_cast<spa_loop*>(pm->thread_loop), update_filter, 1, nullptr, 0, false, this);

And now the error is `‘struct spa_loop’ has no member named ‘loop’`. Hmm... I am starting to suspect pw_thread_loop does not work with invoke.

**Comment by wwmm** [comment]
Master branch updated. I defined the a function
```
auto update_filter(struct spa_loop* loop, bool async, uint32_t seq, const void* data, size_t size, void* user_data)
    -> int {
  auto* self = static_cast<PluginBase*>(user_data);

  spa_process_latency_info latency_info{};

  latency_info.ns = static_cast<uint64_t>(self->latency_value * 1000000000.0F);

  std::array<char, 1024U> buffer{};

  spa_pod_builder b{};

  spa_pod_builder_init(&b, buffer.data(), sizeof(buffer));

  const spa_pod* param = spa_process_latency_build(&b, SPA_PARAM_ProcessLatency, &latency_info);

  pw_filter_update_params(self->filter, nullptr, &param, 1);

  return 0;
}
```
that is called by
```
pw_loop_invoke(pw_thread_loop_get_loop(pm->thread_loop), update_filter, 1, nullptr, 0, false, this);
```
inside the gilter `process` callback. I imagine it should be fine now. @pinkflames if possible try to do some tests with the master branch.

**Comment by pinkflames** [comment]
PipeWire git master now also avoids crashing EE while also printing warnings such as this to `journalctl --user`: *mar 31 20:31:46 hostname easyeffects[65120]: pw.filter: method cannot be called from here: Device or resource busy*. I can also confirm that applying the commit c51b1721e0b10f5d7f410cc50f143c23c05706e1 prevents both EE crashing and the new warning being logged, so it appears the issue is, indeed, fixed.
