### ISSUE TITLE
No way to disable EasyEffects Sink/Source

### ISSUE THREAD

**Issue by ObaniGemini** [wwmm/easyeffects#2234]
### EasyEffects Version

Current

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I'm using easy effects to put some effects on my mic (easyeffects source), but I have no use for the sink. Is there a way to disable one or the other?

The sink seems to take priority on the default output and it puts me at a constant 30/40% use of cpu for basically nothing (it includes the spectre and sink processing I guess, plus all the pipewire sources added)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>I'm using easy effects to put some effects on my mic (easyeffects source), but I have no use for the sink. Is there a way to disable one or the other?

The only way to "disable" them is making sure nothing is  playing to / recording from them. In your particular case the first step is disabling `Process All Outputs` so that EasyEffects does not try to move streams to its virtual sink. The other step is never setting our virtual devices as your system default devices. This is a general recommendation #1836.

>The sink seems to take priority on the default output and it puts me at a constant 30/40% use of cpu for basically nothing

There isn't a way for clients to set priorities for the devices they create. So it must be something wireplumber/pipewire is doing on its own.

**Comment by sgtcoder** [comment]
Why does the input/source have a Easy Effects sink anyways?

```
The other step is never setting our virtual devices as your system default devices.
```
This is not possible because Pipewire keeps resetting default and switching back over to the Easy Effects sink.

**Comment by wwmm** [comment]
>This is not possible because Pipewire keeps resetting default and switching back over to the Easy Effects sink.

Wireplumber probably has a bad configuration somewhere making it do this. Try to remove the folder `~/.local/state/wireplumber/` and rebooting. In any case it is not something that can be fixed from our side. Wireplumber is the onde doing it for some reason.

**Comment by Fxzzi** [comment]
any way to set easyeffects to only modify speakers / headphones and not mic?

**Comment by wwmm** [comment]
> any way to set easyeffects to only modify speakers / headphones and not mic?

Disable `Process All Inputs` in our Preferences Window and use a manager like pavucontrol to force the stream to be moved back to your microphone. Or use the disable checkbox in EE players tab.

WirePlumber remembers the last used device and tries to restore streams to them. So just setting EasyEffects to not move them is not enough. You have to make wireplumber forget the association.

**Comment by Fxzzi** [comment]
Thanks, sorta works but a little finnicky, why not a simple method to just disable any effects on the inputs and disable the easyeffects source?

**Comment by wwmm** [comment]
> why not a simple method to just disable any effects on the inputs and disable the easyeffects source?

Because it is not possible to disable a virtual device. It is necessary to completely destroy it. What will require some careful code rewriting on our side because there are some initialization we do once when the app starts. If we destroy de device all the information acquired before will be invalid. 

It is one of those things that are not impossible to do. But really annoying to do.

**Comment by JohnTheCoolingFan** [comment]
I've turned off "process all outputs" and my default output device is my headphoes, yet in helvum I still see EasyEffects Sink that outputs into a spectrometer and a volume meter that then goes into my output device. It causes audio popping consistently when I launch some games or OBS studio. Goes away after I disconnect those nodes from the output.

**Comment by wwmm** [comment]
>yet in helvum I still see EasyEffects Sink that outputs into a spectrometer and a volume meter that then goes into my output device. It causes audio popping consistently when I launch some games or OBS studio. Goes away after I disconnect those nodes from the output.


Strange. PipeWire should have made this pipeline inactive when nothing is playing to the virtual sink.  Are the links in the active state? This can be seen in `pw-dot` if Helvum is not providing this information.

**Comment by JohnTheCoolingFan** [comment]
I think the links are active until I disconnect them, judging by how they turn to dotted lines in helvum. I can check it using `pw-dot` sometime later to completely validate.

**Comment by JohnTheCoolingFan** [comment]
EasyEffects Sink is connected to the default audio output by default, but it's in dotted lines, so they are inactive until I do some things, like launching OBS. That connection becomes active then (I also had a firefox connection going to my output device, yet it was inactive).

With no manual edits to the connections and obs running:
[pw.dot.txt](https://github.com/user-attachments/files/18811045/pw.dot.txt)

**Comment by wwmm** [comment]
>With no manual edits to the connections and obs running:

Hum... This feels like a regression in PipeWire. It did not use to put this kind of pipeline in the active state in the past. We request the filter links to be of the passive kind exactly for PipeWire to be able to not make them active in situations like this one.

The obvious workaround for this is removing the links. Something we used to do in the past when PipeWire was not able to properly put the links in the idle state in situations like this one. And in the Qt branch I've brought back this procedure for other reasons. The question is if it is worth the effort to resurrect this in the gtk branch that is going to be replaced... In any case it still feels strange that PipeWire is not able to handle this case on its own anymore...
