### ISSUE TITLE
Set ellipsize on DropDown

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2236]
Can we prevent this?

![Schermata del 2023-03-31 15-12-38](https://user-images.githubusercontent.com/25790525/229132014-9761a4d1-7b1a-448b-94c8-99b5c041a721.png)

I can't see a way to set the `ellipsize` property on the internal label of the DropDown.

**Comment by wwmm** [comment]
>I can't see a way to set the ellipsize property on the internal label of the DropDown.

The only way I am aware of is doing the same I had to do to enable ellipsize to the input/output devices dropdown https://github.com/wwmm/easyeffects/blob/master/data/ui/factory_input_device_dropdown.ui. It seems to be the price to be paid for its flexibility... We are forced to write a whole custom factory putting our own label... At least it can be done in the xml.

Something I do not like in the dropdown that I did not have time to find a solution for yet is the fact the mouse scroll button does not work on it. That is annoying...

**Comment by wwmm** [comment]
>The only way I am aware of is doing the same I had to do to enable ellipsize to the input/output devices dropdown 

In the cases where a stringlist is being used instead of a custom model the binding has to be done as in https://github.com/wwmm/easyeffects/blob/master/data/ui/factory_presets_dropdown.ui

**Comment by wwmm** [comment]
Oh... I forgot that this compressor dropdown already has a custom factory https://github.com/wwmm/easyeffects/blob/master/data/ui/factory_node_dropdown.ui. So it is just a matter of setting the gtklabel property there.

**Comment by Digitalone1** [comment]
> Something I do not like in the dropdown that I did not have time to find a solution for yet is the fact the mouse scroll button does not work on it. That is annoying...

This could be signaled to GTK devs, maybe they will implement it in the future.


> Oh... I forgot that this compressor dropdown already has a custom factory https://github.com/wwmm/easyeffects/blob/master/data/ui/factory_node_dropdown.ui. So it is just a matter of setting the gtklabel property there.

Did it. The ellipsize overrides the wrap property.
