### ISSUE TITLE
Clarify the README

### ISSUE THREAD

**Issue by DNDEBUG** [wwmm/easyeffects#2239]
what do you mean by 
```Don't set Easy Effects' virtual devices as your default audio input/output. Easy Effects is designed assuming that your hardware stays as default.```
makes me think that i should not set Easy Effects for my mic and stuff

**Comment by wwmm** [comment]
We mean what is said at #1836. Users often set our virtual devices as the system default device. This should not be done. But unfortunately there is no way we can prevent it. That is why we put a warning.
