### ISSUE TITLE
EasyEffects stuck on older Pipewire

### ISSUE THREAD

**Issue by DomieMic65** [wwmm/easyeffects#2258]
### EasyEffects Version

7.0.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint 21.1

### Describe the bug

While my system is on Pipewire 0.3.63 `Server Name: PulseAudio (on PipeWire 0.3.63)` , EasyEffects uses Pipewire 0.3.41.
There is no issue with the sound or something else.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

Commit: 6e542e7

**Comment by wwmm** [comment]
>While my system is on Pipewire 0.3.63 Server Name: PulseAudio (on PipeWire 0.3.63) , EasyEffects uses Pipewire 0.3.41.

It isn't using the older version. The Flatpak package compiled EasyEffects with it https://github.com/wwmm/easyeffects/blob/7d7eeb67fd567bd9e92b579e435e3a4d4cd52f80/util/flatpak/easyeffects-modules.json#L181 but at runtime your PipeWire installation is used. No reason to worry :-).

**Comment by DomieMic65** [comment]
Thanks for clarifying!!
