### ISSUE TITLE
Metainfo description and changelog not translated

### ISSUE THREAD

**Issue by flipflop97** [wwmm/easyeffects#2262]
When viewing Easy Effects in GNOME Software in Dutch, the description and changelog are not translated at all. I've translated the description and most recent changelog entries a while ago, and they are visible in the [source](https://github.com/wwmm/easyeffects/blob/master/po/news/nl.po), so they should be available. Noticable, is that the description ("Audio Effects for PipeWire Applications") *is* translated, but the description and changelog aren't.

**Comment by vchernin** [comment]
That is strange, indeed the description and channeling are meant to be translated. What easy effects package are you viewing in gnome software? The stable flatpak from flathub or a package from a distribution?

**Comment by flipflop97** [comment]
> That is strange, indeed the description and changelog are meant to be translated. What easy effects package are you viewing in gnome software? The stable flatpak from flathub or a package from a distribution?

The only sources I've configured are Flathub, Flathub Beta and GNOME Nightly, where Easy Effects is only available from Flathub. I don't have any distro-specific sources configured.

![afbeelding](https://user-images.githubusercontent.com/13943260/231525615-d058a916-ffcb-44d2-b13e-e0d74fc83c50.png)

![afbeelding](https://user-images.githubusercontent.com/13943260/231524999-0e7eb2d9-23c8-45d3-8b9b-e869a95df018.png)

**Comment by wwmm** [comment]
>That is strange, indeed the description and changelog are meant to be translated.

Yes. Maybe the problem is here https://github.com/wwmm/easyeffects/blob/8f39c8f7fcdb7e3d5c313f596f0e637a473a1128/data/meson.build#L57. I think I probably should have changed `po_dir: '../po',` to `po_dir: '../po/news',` when the templates were split. I will change it now.

**Comment by vchernin** [comment]
> https://github.com/wwmm/easyeffects/blob/8f39c8f7fcdb7e3d5c313f596f0e637a473a1128/data/meson.build#L57
> . I think I probably should have changed `po_dir: '../po',` to `po_dir: '../po/news',` when the templates were split. I will change it now.

This seems to have done the trick, translated metadata shows up in gnome software for me on newer builds, I think this can be closed.
