### ISSUE TITLE
Opening browser while song is playing in rhythmbox results in buzzing sound.

### ISSUE THREAD

**Issue by BayouGuru67** [wwmm/easyeffects#2286]
### EasyEffects Version

7.0.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Kubuntu 22.04.2 LTS (fully-updated)

### Describe the bug

Was listening to music with rhythmbox.  Opened a brave browser window and the audio suddenly got a rather annoying "buzz" superimposed on it.  Stopped playback in rhythmbox, and after a couple of seconds, the buzzing stopped.  Leaving the browser window open, I resumed playback normally once the buzz went away.  This has happened repeatedly and reliably over time across a number of reboots, so it is not a momentary issue, however this is a description of one specific issue. 

This problem is not limited to brave browser, as I have a whole list of exception programs defined in EasyEffects for just this reason.  There are a number of programs that have this symptom!  A couple of the most reliable are:
Shiesen Sho from KDE games
KNetwalk from KDE Games

Other programs can also cause the problem, but these are the most annoying ones I can rely on to cause problems every time they are run.  The exception list is only partially effective, and the browser is not an option for the list, as it is the primary reason I run EasyEffects to begin with, i.e.: YouTube/YouTubeTV/Plex/STIRR/Pluto TV... audio processing.

Let me know if there's anything I can run from the terminal and send to you to help us with this. 

### Expected Behavior

Programs are not supposed to impose a buzzing noise over the playback of audio.  Simply running programs that don't/are not outputting audio should not affect the audio.  It does not appear to be an error or crash specifically, as EasyEffects continues to operate as though nothing is wrong.  There are no reported errors in the system logs related to easyeffects that I could find.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Plasma version:  5.24.7
Kernel Version:  5.19.0-40
X.Org Version: 1.21.1.4
GPU driver Info:  Mesa 23.0.3 - kisak

**Comment by wwmm** [comment]
This is looking like a PipeWire bug. unless it only happens when a specific EasyEffects plugins are active when the noise happens?

>Let me know if there's anything I can run from the terminal and send to you to help us with this.

usually when something bad happens as soon as a new stream is started the first thing to look at is if PipeWire dynamically switched to a lower latency value. The command `pw-top` will help to figure this out. The column `QUANT` and `RATE` will help to estimate the curret server latency by calculating `QUANT / RATE`.

**Comment by Yisus7u7** [comment]
I get the same problem using the google chrome browser (even with the browser closed the problem persists).

It's really annoying that short buzz while playing music.

**Comment by wwmm** [comment]
@Yisus7u7 maybe your soundcard inputs are being saturated when a transient happens. Based on your image the level meters are above `0 dB`. If a transient make the signal go even higher clipping and its associated noise will happen.

**Comment by Yisus7u7** [comment]
> @Yisus7u7 maybe your soundcard inputs are being saturated when a transient happens. Based on your image the level meters are above `0 dB`. If a transient make the signal go even higher clipping and its associated noise will happen.

Is there any way to solve it?

**Comment by Yisus7u7** [comment]
I tried again and the problem persists, I choked on the cake I was eating when the buzz interrupted the rhythm of the song, lol

**Comment by wwmm** [comment]
>Is there any way to solve it?

Reducing the volume of the audio player or using the plugins input/output control. It is also a good idea to have the `limiter` plugin as the last plugin in the pipeline. This way your sound card will be protected against saturation.

It may also help to print the output of `pw-top` before and after the problem happens so we can see what PipeWire is doing to the latency value.

**Comment by BayouGuru67** [comment]
After some time has elapsed, with updates to both Pipewire (now at version 0.3.84) and EasyEffects (now at version 7.1.3, I can now have EasyEffects keep running when I close the window, as the problem of losing audio when switching inputs on my A/V Receiver (switching between computers) is no longer present!  Hooray!  

I have noticed that during this time the distortion of audio has risen and fallen in severity, but has never really left.  As of now, I still get buzzy distortion when I try to play some games when audio is already playing.  As of now, an easy example of this is the port of the Microsoft Pinball game "Space Cadet Pinball".  If I have audio playing, either from YouTube/Online in a browser or from a local player like Rhythmbox, and I open the pinball game...bam!...distorted audio!  Close the game and it cleans back up.  I also am of the opinion that this is a pipewire thing, as the same thing also  happens with JamesDSP and the Calf Effects packages....and the particular characteristics or severity seems to fluctuate somewhat with each update to Pipewire, generally and gradually trending towards improvement.  On the upshot, most of the games that used to give me this problem, such as Shisen-Sho, no longer pose a problem as they are now in the Excluded lists of all the presets now, and I am keeping the pinball game out of the list intentionally in order to monitor the developments/improvements/changes with each update.

I do wish there was an easier way to add a program to the exclusion lists of <b>all</b> of the current local presets at once instead of just the active one, then I can remove it from whichever preset(s) it doesn't need to be excluded from (if any). It would make working around these PipeWire issues/problematic games so much easier for those of us who have a significant number of presets and a mild case of CRS.

**Comment by wwmm** [comment]
>I still get buzzy distortion when I try to play some games when audio is already playing

Games request unreasonably low latency values. The next time you run them execute in a terminal `pw-top`. The quantum column is directly related to the latency value used by PipeWire through the equation `latency = quantum / rate`. My guess is that PipeWire is switching to a latency that is too low for your system to handle in that situation. 

If this is the source of the noise temporarily setting the latency to a fixed and higher value will fix it. PipeWire's wiki show how to test this https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Latency

**Comment by wwmm** [comment]
>I do wish there was an easier way to add a program to the exclusion lists of all of the current local presets at once instead of just the active one

Although the isn't a a way to do things in batch in our window you can do this editing the presets file in a text editor. It will work if you.
