### ISSUE TITLE
Plugins become useless after their reset button is pressed

### ISSUE THREAD

**Issue by wwmm** [wwmm/easyeffects#2290]
@vchernin and @Digitalone1 I have noticed now that after resetting a plugin their controls have no effect anymore. I will try to do more investigation along this week. I think something is happening to the gsettings object once it has no keys anymore. In dconf the plugin index disappears after the reset. And although there is no error the settings do not come back after we change them. Only the bypass button key returns. But probably because it is bound to a different gsettings object that was not the one the reset was using as argument.

**Comment by wwmm** [comment]
I wonder if somehow something different happens inside Flatpak as its backend is different.

**Comment by Digitalone1** [comment]
Unfortunately I didn't caught this behavior when the reset on the Equalizer was fixed.

But doing some quick test I found out it's back to normal when the window is closed and the reopened.

How is this possible? Should we delete and recreate some objects after the reset to prevent this?

**Comment by Digitalone1** [comment]
Also removing the plugin from the list and readding it resolves the issue. This leads me to think that after a reset all the keys needs to be bound like it's done at the plugin interface initialization.

**Comment by wwmm** [comment]
>This leads me to think that after a reset all the keys needs to be bound like it's done at the plugin interface initialization.

At first sight it seems to be the case. But it is weird the documentation tells nothing about it. I would expect the binding to be gone when the gsettings object is destroyed. After all the resetting is just setting the key to it's default value. Or at least is what it's docs suggests it is happenning.

**Comment by wwmm** [comment]
Maybe we could try to define our own reset function instead of calling the one from gsettings. I can not look at this right now but since we have the key name and the gsettings object there must be a way to read it's defa6 value and then setting the keys accordingly. Hopefully this won't break the bindings.

**Comment by wwmm** [comment]
>must be a way to read it's default value

Thinking about it now maybe the only way requires using a function they suggest that should never be used. I am on the way to my work now. So only later I will be able to check this properly.

**Comment by Digitalone1** [comment]
Maybe it's simpler.

We got the schema [here](https://github.com/Digitalone1/easyeffects/blob/1e5e3da39cc49baf794c5a66448ff6c719a3621b/src/util.cpp#L207).

Then we [unref](https://github.com/Digitalone1/easyeffects/blob/1e5e3da39cc49baf794c5a66448ff6c719a3621b/src/util.cpp#L238) it.

Maybe we don't need to unref?

**Comment by wwmm** [comment]
I was looking at the wrong reset implementation before. If I am not mistaken this should be what the default backend is doing https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdelayedsettingsbackend.c#L198. so maybe creating our own might work.

>Maybe it's simpler.

There is a function that gives the default value directly https://docs.gtk.org/gio/method.Settings.get_default_value.html. It should be fine to use this one.

**Comment by wwmm** [comment]
I am doing some tests with 
```
auto default_value = g_settings_get_default_value(settings, keys[i]);

  if (g_settings_set_value(settings, keys[i], default_value) == 0) {
    using namespace std::string_literals;

    util::warning("The setting "s + keys[i] + " is not writable");
  }
```
in the place of as a replacement for `g_settings_reset(settings, keys[i]);`. In dconf the section under the plugin index does not disappear anymore. But the bug still happens. This is really weird...

**Comment by wwmm** [comment]
@Digitalone1 and @vchernin I've found the source of the problem. It is the delayed mode. As soon as I disabled it the reset behaved as expected.

**Comment by wwmm** [comment]
I have updated the master branch disabling the delayed mode by default again. At least until we understand why the hell gsettings is behaving in a different way because of it.

In any case this issue can be closed.

**Comment by Digitalone1** [comment]
Maybe opening an issue on GTK Gitlab may help...
