### ISSUE TITLE
'Killed' when media stopped/paused.

### ISSUE THREAD

**Issue by MeowIce** [wwmm/easyeffects#2301]
### EasyEffects Version

6.3.0

### What package are you using?

Fedora

### Distribution

Fedora 37

### Describe the bug

When I pause the current playing media, either from Chrome or Sayonara, EasyEffects got killed with 'Killed' .

### Debug Log

<details><summary>Debug Log</summary><br/>

Logs:
[bug.txt](https://github.com/wwmm/easyeffects/files/11358392/bug.txt)

pw-dump:
[pwdump.txt](https://github.com/wwmm/easyeffects/files/11358395/pwdump.txt)
</details>

**Comment by wwmm** [comment]
>6.3.0

That is a very old version. I strongly you upgrade to `7.0.3`
