### ISSUE TITLE
Wrap when needed in plugin credits

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2304]
We should avoid this:

![image](https://user-images.githubusercontent.com/25790525/235319461-3c27e343-e349-480b-a61b-df09a49d17e2.png)

**Comment by Digitalone1** [comment]
To solve this I was thinking to set a simple label and fill it at every plugin ui creation with fmt format `Using {}`. This will help also with translations because some languages need the verb after the library name.

The problem is that we now use the bold style for the library name, but the above solution can only apply the style to the whole text.

A workaround could be using a GtkTextBuffer and GtkTextTags to apply style to only a part of the text, but it's too complex and may still not work with translations, so it's not worth the effort. 

So I'd like to know if it's good to present the credit with a single style (regular or bold) to only one label with the wrap property and filling it with the fmt format `Using {}`. @wwmm what do you think?

**Comment by wwmm** [comment]
>This will help also with translations because some languages need the verb after the library name.

Oh... I did not think about this.

>So I'd like to know if it's good to present the credit with a single style (regular or bold) to only one label with the wrap property and filling it with the fmt format Using {}. @wwmm what do you think?

It is fine to have a single style.

**Comment by Digitalone1** [comment]
Anyway this issue is caused by [GtkBinLayout](https://docs.gtk.org/gtk4/class.BinLayout.html).

> GtkBinLayout will stack each child of a widget on top of each other.

Staying on top of each other, the wrap property won't work either.

I will try removing it.

**Comment by Digitalone1** [comment]
I also noticed this. :laughing: 

![image](https://user-images.githubusercontent.com/25790525/235964553-cb1d3e84-8cf5-42e7-afa5-ac5f7df8838d.png)

The wrap property is not even set (and we don't want it here). So now GTK sets the wrap by default. I don't remember it was like that before.

**Comment by Digitalone1** [comment]
It's better using the `wrap-word`, not `wrap-word-char`.

https://docs.gtk.org/Pango/enum.WrapMode.html

**Comment by Digitalone1** [comment]
Maybe now I understood. It's the AdwActionRow that sets the wrap that way. A plain GtkLabel should have the wrap disabled.

**Comment by Digitalone1** [comment]
We need to set `title-lines` on action rows that can be ellipsized.

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/property.ActionRow.title-lines.html

2 lines is reasonable.

![image](https://user-images.githubusercontent.com/25790525/235976090-cefc04b7-6081-4ac4-bacd-4fcf6ec77365.png)

In the preferences window we don't need it because the size cannot be shrunk over a certain limit. But elsewhere it's better to set it.

**Comment by Digitalone1** [comment]
This is better (I extended the text on purpose for testing reasons):

![image](https://user-images.githubusercontent.com/25790525/235987108-3d156fc8-5844-4f53-9688-061b68ac0d2f.png)
