### ISSUE TITLE
inputs and outputs 

### ISSUE THREAD

**Issue by footboxgggggg** [wwmm/easyeffects#2329]
due to an update in Chrome os my input and output is alsa-source and alsa-sink monitor and alsa-sink and my discord input is PCM source and my discord output is PCM sink could you please update your thingy so i could use pulse effects on discord ?

**Comment by wwmm** [comment]
>so i could use pulse effects on discord ?

PulseEffects or Easyeffects? PulseEffects isn't developed anymore. In any case this sounds like the kind of thing that has to be changed in the audio server and not on its clients. 

PulseEffects can only see devices Pulseaudio shows to it. In the same way Easyeffects can only see devices PupeWire is showing to it. None of these programs can directly access ALSA devices.
