### ISSUE TITLE
Equalizer effect could provide better visual feedback

### ISSUE THREAD

**Issue by NicolasLM** [wwmm/easyeffects#2333]
I understand that the current equalizer effect uses the UI of a physical hardware graphical EQ, there is nothing wrong with that. However many software EQ plugins have shifted to a different UI that, in my opinion, provides better feedback.

Unfortunately I could not find the definitive name of this particular EQ UI so let me post a screenshot instead:

![image](https://github.com/wwmm/easyeffects/assets/7612656/12e503e8-a478-49bc-8ffe-016ab3c6a1fc)

The key improvement over sliders is that each band show its impact on the frequency response taking into account its quality and slope.

**Comment by wwmm** [comment]
It would be nice but #515 does not allow us to do this. Although we do not use GStreamer anymore and nowadays we have our own simple LV2 wrapper getting the frequency response curves from the plugin is still a pain. As far as I know there isn't a standard way to get them in LV2. You have to read the plugin source code and do some "reverse engineering" to see how the plugin sends its curves to its built-in window. What is obviously going to be different from a plugin to another and will make maintenance over time a nightmare.

As there isn't a way to do this without the frequency response curves I will close this issue.

**Comment by NicolasLM** [comment]
Got it, thank you for the explanation and for all the work on this project!

**Comment by wwmm** [comment]
The latest master branch is capable of showing the native equalizer ui. There are lots of rough edges to fix but we can finally see the frequency response curves.
