### ISSUE TITLE
Turn off Inactivity timer

### ISSUE THREAD

**Issue by Vreex** [wwmm/easyeffects#2340]
It is very inconvenient to restart easyeffects when my laptop came back from sleep

Also, Why is there a timer to begin with??

**Comment by wwmm** [comment]
>It is very inconvenient to restart easyeffects when my laptop came back from sleep

If the computer sleeping is related to the problem you are probably seeing #1083. It has nothing to do with the inactivity timeout.

>Also, Why is there a timer to begin with??

It exists so EasyEffects avoids wasting CPU when there is no audio stream active. There isn't a way to pause the effects pipeline. Sometimes PipeWire pauses it on its own when there is no stream playing to our sink. But sometimes ti doesn't. So the only safe way to avoid wasting CPU is unlinking our filters when there is not active stream linked to our virtual sink.

As we can't get rid of the timeout as things are right now and there is already an open issue about computer sleep problems we can close this one.
