### ISSUE TITLE
Portability of config file

### ISSUE THREAD

**Issue by Kommynct** [wwmm/easyeffects#2345]
as it stands in my .config/easyeffects folder there's just a bunch of empty folders, i'd like to be able to share my config so that i can automatically using my dotfiles have easyeffects fully configured on a new system.

Is that possible somewhere and i'm just missing it?

**Comment by wwmm** [comment]
>i'd like to be able to share my config so that i can automatically using my dotfiles have easyeffects fully configured on a new system.

The easiest way is saving your settings to a preset file and loading it in the new system. Almost all EasyEffects settings are saved to the preset.

As we use `GSettings` to handle our settings trying to copy its whole database to a new computer is probably not a good idea. IT is safer to just create presets and get them inside `~/.config/easyeffects/`

**Comment by Kommynct** [comment]
Quick question, now that I realize that it's setup with gsettings, I can just add a gsettings command to my setup script, however, I want to edit the speech processor settings, and I can't figure out how to write this

If anyone could help i'd appreciate it, sorry for bumping a closed issue

gsettings set com.github.wwmm.easyeffects.streaminputs speex/0 enable-dereverb true

**Comment by wwmm** [comment]
@Kommynct you can follow the same ideas at #916. The path to the speex plugin can be found through dconf
![Screenshot from 2023-05-16 12-01-43](https://github.com/wwmm/easyeffects/assets/16225172/2b2f432a-bc6a-400e-83bb-523c0fa487f6)
