### ISSUE TITLE
Max Samplerate Supported?

### ISSUE THREAD

**Issue by Ghoost666** [wwmm/easyeffects#2350]
### EasyEffects Version

6.3.0

### What package are you using?

Fedora

### Distribution

Fedora 37

### Describe the bug

Hey i just played around with pipewire`s resampling the other day and noticed that with 384khz and 768khz easyeffects stop working, (also pavucontrol/pipewire was acting strangly (i couldnt set a a sound card as my default output, it defaulted to the easyeffects sink)

so im wondering what samplerate easyeffects officially supports? the highest samplerate working was 192khz for me

### Expected Behavior

easyeffects supporting all samplerates up to 768khz

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>so im wondering what samplerate easyeffects officially supports? the highest samplerate working was 192khz for me

EasyEffects does not put an upper bound on the sampling rate. We use whatever PipeWire is using. But if I remember well PipeWire does put some limits in the possible sampling rates.

>6.3.0

Any reason to be using such an old EasyEffects version?

**Comment by Ghoost666** [comment]
i noticed that the spectrometerisnt working well with 192khz and more either, it looks like it speeds up (and for some reason it shows way more bass than with 44,1/48khz)

not sure where i should start troubleshooting this if pipewire is the culprit here

im using 6.3.0 because its the current version in the fedora repositories, tho i wanted to try the flathub version anyway, any chance that this fixes this?

**Comment by wwmm** [comment]
>not sure where i should start troubleshooting this if pipewire is the culprit here

I am not sure if there is something you can do. PipeWire has 192 kHz hardcoded as upper limiter in some places https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/doc/spa-pod.dox#L231.

>im using 6.3.0 because its the current version in the fedora repositories, tho i wanted to try the flathub version anyway, any chance that this fixes this?

The Flatpak package already has  has `7.0.4`. So it should work.

**Comment by Ghoost666** [comment]
ah.. shit :D thanks i missed pipewire`s limitation there

ah i saw that 7.0 fixes the spectrometer, great thanks, i will try it :)
