### ISSUE TITLE
No sound coming through despite program showing in EasyEffects

### ISSUE THREAD

**Issue by hellkith** [wwmm/easyeffects#2351]
### EasyEffects Version

6.2.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint 20

### Describe the bug

The issue I'm having is that software running through EasyEffects causes me to hear nothing of the application.
for instance I am running Spotify through it and I hear nothing of the music regardless of output device.
If I disable Spotify with the toggle infront of it I do hear audio.

The same counts for other applications such as Discord.

Screenshot is made while Spotify is playing music.
![image](https://github.com/wwmm/easyeffects/assets/6150722/903d5de5-8955-4f08-8ab4-0ac8769afdc7)

### Expected Behavior

for the audio to play and be altered by EasyEffects

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Just to note, I am not 100% sure on the package.
According to the software manager it's the "flatpak" one. 

![image](https://github.com/wwmm/easyeffects/assets/6150722/ad542c5a-9c9b-4051-a557-e4560ef59ca4)

**Comment by hellkith** [comment]
Closing issue as I figured out what it was :facepalm: 
In my sound settings, my output device was set to my headphones and not "Easyeffects sink".
I've switched it to that one and that fixed it.

**Comment by wwmm** [comment]
>In my sound settings, my output device was set to my headphones and not "Easyeffects sink".

As discussed on #1836 setting EasyEffects devices as the system default devices is not a good idea. There are cases where this does not work. The only supported configuration is the one where your hardware stays as the default.

I wonder why your flatpak install is stuck on `6.2.4`. Version `7.0.4` is available and as lots of new features and bug fixes.

**Comment by hellkith** [comment]
> > In my sound settings, my output device was set to my headphones and not "Easyeffects sink".
> 
> As discussed on #1836 setting EasyEffects devices as the system default devices is not a good idea. There are cases where this does not work. The only supported configuration is the one where your hardware stays as the default.
> 
> I wonder why your flatpak install is stuck on `6.2.4`. Version `7.0.4` is available and as lots of new features and bug fixes.

Hmmm that is very odd. Is 7.0.4 available for Linux Mint 20?

**Comment by wwmm** [comment]
>Hmmm that is very odd. Is 7.0.4 available for Linux Mint 20?

I think it should be but @vchernin will be able to give a definitive ansawer.
