### ISSUE TITLE
Reset button really needed for Level Meter?

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2360]
I was thinking about this. Is it really needed? Should we remove it?

**Comment by Digitalone1** [comment]
I'm looking at the gsettings schema: the bypass and the reset-history are saved for this plugin, but I suppose we still don't need the Reset button at the bottom. The bypass can be toggled by the user and the same is for the history.

And since the reset history is only a one time function that is used to restore the meters, why we are saving it to gsettings? The same is happening for the AutoGain.

**Comment by wwmm** [comment]
>And since the reset history is only a one time function that is used to restore the meters, why are we saving it to gsettings? The same is happening for the AutoGain.

The reset-history being saved to gsettings is probably an oversight while doing copy and paste. It does not make sense indeed. As the level meter is right now it does not need the reset button. At some point I tried to make it have a configurable `time window` like the autogain but unfortunately libebur128 uses it only for the integrated loudness and not for the true peaks. So for now we can remove the reset button from the level meter.

**Comment by wwmm** [comment]
>The reset-history being saved to gsettings is probably an oversight while doing copy and paste.

Oh no. It was not. GSettings is being used as a way to decouple the widgets code from the plugin class.

**Comment by wwmm** [comment]
>Oh no. It was not. GSettings is being used as a way to decouple the widgets code from the plugin class.

And to make sure that third party tools are able to access this setting https://github.com/wwmm/easyeffects/blob/6a5dc57b50931434af3516d6f9ac28a723a55eb9/src/autogain_ui.cpp#L70. I admit it is a lazy approach :smile:. But I think that it is better than passing more pointers around.

**Comment by wwmm** [comment]
Third party tools like tray applets rely on the settings being available either through command line options or gsettings. Compared to trying to exposing this option through command line the gsettings hack is a lot easier.

**Comment by wwmm** [comment]
In the level meter I do not see a reason why someone would want to activate its `reset-history` through a third party tool. It only makes sense to use this plugin with EE window opened. So in the level meter we can remove it from gsettings. But in the autogain there is a point in using third party tools because the user may want to reset its history without needing to open EE window for this. So it is better to keep it in the autogain.

**Comment by Digitalone1** [comment]
> So in the level meter we can remove it from gsettings. But in the autogain there is a point in using third party tools because the user may want to reset its history without needing to open EE window for this. So it is better to keep it in the autogain.

OK.
