### ISSUE TITLE
Distorted audio after suspend

### ISSUE THREAD

**Issue by OlegAckbar** [wwmm/easyeffects#2363]
### EasyEffects Version

7.0.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 23.04

### Describe the bug

After waking my laptop from suspend most of the times I experience distorted audio caused by EasyEffects. Restarting EasyEffects solves this problem.
Here's video of what's happening: https://youtu.be/0fNEUE1tVRY
Preset I'm currently using: https://gist.github.com/OlegAckbar/8219c9cee3d7bb2262fdec27bb057eca

### Debug Log

pw-dump: https://gist.github.com/OlegAckbar/a5ebc70069b5010b69c611ec3076b395

### Additional Information

I'm willing to provide any other logs in necessary.

**Comment by wwmm** [comment]
>I'm willing to provide any other logs in necessary.

When this kind of noise is involved `pw-top` output while the noise is happening  can help. It will show how PipeWire has set the latency.

I also think we will need some help from PipeWire developers. When PipeWire dies or is restarted after the computer is suspended it is normal to not have sound in EasyEffects because EasyEffects is not able to automatically reinitialize all the PipeWire objects it creates. Implementing this is hard as EasyEffects is right now. But when a noise like yours happens something totally different must be going on and I have my doubts we can fix only from EasyEffects side considering the computer suspension is involved.

@wtay and @pinkflames have you ever seen this kind of noise https://youtu.be/0fNEUE1tVRY when PipeWire comes back from computer suspension?

**Comment by pinkflames** [comment]
I think similar issue has been reported at least once before. And I'm quite sure that this has to be a driver bug, if it's related to the computer existing system suspend state. Or at least the driver is where it needs to be dealt with.

If it's EasyEffects and not PipeWire that needs to be restarted, then the most obvious thing to check would be to check `cat /proc/asound/card*/*/*/hw_params`  to see if there's any open devices, perhaps kept open by EasyEffects or something going through it. pw-top could also be used but that would not do the check purely from the ALSA perspective.

**Comment by OlegAckbar** [comment]
@wwmm here's pw-top during noise events
![mpv-shot0012](https://github.com/wwmm/easyeffects/assets/9915567/79b4038d-b226-4cc5-99f8-0ca34635519e)

**Comment by wwmm** [comment]
>here's pw-top during noise events

The latency is fine. So the noise is not because it has become too low. And the amount of errors is also low considering how horrible is the noise. I admit I have no idea about what is causing it =/.

**Comment by wwmm** [comment]
>to see if there's any open devices, perhaps kept open by EasyEffects or something going through it

That can happen only indirectly through PipeWire since we do not touch ALSA objects.

**Comment by pinkflames** [comment]
I did not mean that EE is opening the ALSA device but maybe something is keeping the device open, and my guess was that once EE closes, the device might also close and that probably clears the issue when it's next re-opened.

The presets may point to an EE bug but I'm not sure.. can the issue be reproduced if EE is not running?

**Comment by OlegAckbar** [comment]
Here's video of how just closing EasyEffects removes any noises. https://youtu.be/Nx8lp98gtPE

**Comment by pinkflames** [comment]
Way too fast for device suspend to happen, besides audio is actively playing. One thing I observed is that it's also briefly glitching out when you launch EE, so, I think, it's some more general performance issue or bug.

Also it almost sounds like the audio is clipping, so maybe double check that none of the filters show their input or output volume being maxed out.

**Comment by pinkflames** [comment]
Yes, it's very obviously slipping. I guess it's on @wwmm to figure out why it only happens after suspend.

**Comment by wwmm** [comment]
>Yes, it's very obviously clipping. I guess it's on @wwmm to figure out why it only happens after suspend.

Looking at the video it seems that the `single band compressor` decided to to lots of amplification when it went back from suspending. Our compressor is from Linux Studio Plugins. So I do not know what is actually happening inside of it. @OlegAckbar could you do some tests without it to see if only the single band compressor is doing too much amplification when the computer suspends?

**Comment by wwmm** [comment]
Looking at the video again it is almost like the left channel can not go below `-10 dB`. Even in the gate where there is no clipping yet the left channel seems to have some kind of constant signal that does not let its level go below - 10 dB. This is very weird. 

Before the first plugin in the pipeline it is a null-sink. And before it the audio player stream. Although there is obviously some clipping happening I think that there is something getting to EasyEffects input that is contributing to the noise. Not all of it is the one usually I usually hear when audio is clipping.

**Comment by wwmm** [comment]
>Not all of it is what I usually hear when audio is clipping.

If clipping is the only source of the noise reducing the output gain of the last plugin will be enough to make the noise go away. But I think there is something more than just clipping going on.

**Comment by wwmm** [comment]
@OlegAckbar run `pw-dot` when the noise is present. Its output file can be viewed with the command `xdot` and will show the links between filters and devices. Maybe something is going wrong when the computer suspends.

**Comment by OlegAckbar** [comment]
Ok, here's video where I turning on and off different plugins. It seems after suspend each plugin adds a little bit noise or so I think. https://youtu.be/lU9gEh634Fw
Here's also my pw-dot output before noise bug and after it occurs.
[pw-dot_.zip](https://github.com/wwmm/easyeffects/files/11519715/pw-dot_.zip)

**Comment by OlegAckbar** [comment]
Gate + single band compressor gives no noise, but when you add multiband compressor, equalizer and limiter or their combinations sound become distorted.

**Comment by wwmm** [comment]
>Here's also my pw-dot output before noise bug and after it occurs.

The only thing unusual in the pw-dot output after the noise is that one of the Firefox streams is stuck in the `init` phase. But I am not sure it this would cause all these problems.

**Comment by wwmm** [comment]
>Gate + single band compressor gives no noise, but when you add multiband compressor, equalizer and limiter or their combinations sound become distorted.

All these filters are based on plugins from `Linux Studio Plugins`. I wonder if there are noises with other plugins not based on LSP like the `bass enhancer`, `exciter`, `autogain`, `crossfeed`, etc.

**Comment by wwmm** [comment]
I am doing some tests on my laptop and nothing unusual happens after suspending it. So somehow drivers and hardware play a role in this.

**Comment by OlegAckbar** [comment]
> I am doing some tests on my laptop and nothing unusual happens after suspending it. So somehow drivers and hardware play a role in this.

It doesn't happen instantly. It could happen only after second suspend or when you launch specific application. For example for me launching OBS triggering it.

**Comment by wwmm** [comment]
>It doesn't happen instantly. It could happen only after second suspend or when you launch specific application. For example for me launching OBS triggering it.

Even launching OBS after suspending a few times I could not get the same kind of noise. The only noise I've got when OBS was launched is related to the latency value and not the suspending. My laptop has troubles handling low latency.

**Comment by bhack** [comment]
I found the same issue  occasionally in past and few days ago with EQ on a system.

**Comment by OlegAckbar** [comment]
So I've updated my Pipewire from 0.3.65 (Ubuntu 23.04 default) to latest 0.3.71 and I can't reproduce this issue. Seems it was Pipewire issue after all.

**Comment by AMKamel** [comment]
## Workaround for Hyprland + hypridle users

After suspend/resume, EasyEffects filter chain (rnnoise, equalizer, compressor, deesser) breaks — audio becomes garbled/fast-forwarded. Restarting EasyEffects fixes it, but doing it manually every time is painful.

**Key insight:** Do NOT restart PipeWire — that kills existing app audio connections (Signal, Chrome, Slack lose their mic). Only restart EasyEffects.

### Fix

Add EasyEffects restart to hypridle `after_sleep_cmd` in `~/.config/hypr/hypridle.conf`:

```
general {
    after_sleep_cmd = hyprctl dispatch dpms on; pgrep -x waybar || waybar; (sleep 3 && killall easyeffects 2>/dev/null; sleep 1 && easyeffects --gapplication-service &) &
}
```

The `(...)&` is important — runs the restart in the background so it does not block DPMS on (which causes a black screen on resume).

### Why this works

- hypridle runs inside the Hyprland session, so all env vars (`WAYLAND_DISPLAY`, `DBUS_SESSION_BUS_ADDRESS`) are available
- systemd system-level services do NOT have access to the Wayland display, so EasyEffects crashes with "could not connect to display" / "Could not load the Qt platform plugin xcb"
- Not restarting PipeWire means apps keep their audio streams — no need to restart Signal/Chrome/etc after resume

### Environment

- CachyOS (Arch-based), Hyprland, PipeWire 1.6.2, WirePlumber 0.5.14, EasyEffects 8.1.8, hypridle 0.1.7
- HyperX QuadCast 2 S USB mic
- Input preset with rnnoise, equalizer, compressor, deesser

Ideally EasyEffects would auto-reconnect its filter chain after suspend/resume without needing a full restart.

**Comment by wwmm** [comment]
>Ideally EasyEffects would auto-reconnect its filter chain after suspend/resume without needing a full restart.

Definitely. But what is odd is that it seems to depend on the hardware or on the hardware and software combination whether suspending the computer breaks easyeffects or not. In the tests I did in the past I could never reproduce the issues people had with the system suspension. Audio came back automatically. 

PulseEffects had the exact same issue on Pulseaudio. So whatever it is the cause it does not seem to come from the application or the sound server.
