### ISSUE TITLE
version warning pop-up, with supported pipewire version

### ISSUE THREAD

**Issue by Pyerix101** [wwmm/easyeffects#2365]
### EasyEffects Version

7.0.4

### What package are you using?

Flatpak (Flathub)

### Distribution

PikaOS

### Describe the bug

starting up easyeffects a version warning pop-up shows up telling that i have a too old version of pipewire, but running pactl info the server name shoes up as 0.3.58.
Also, after suspending the pc, and resuming the session, the audio clips and i have to restart easyeffects for it to work properly

### Expected Behavior

the version warning pop-up should not show up and the audio should not clip.

### Debug Log

<details><summary>Debug Log</summary><br/>

```

```
</details>

### Additional Information

PikaOS 22.10 (Ubuntu based)
Gnome 43.1

**Comment by vchernin** [comment]
For the pipewire version pop up see https://github.com/wwmm/easyeffects/issues/2327.

**Comment by aeischeid** [comment]
sames issue: 
![image](https://github.com/wwmm/easyeffects/assets/60911/bc7ed8cf-6456-4134-9152-db389bcc4478)

**Comment by wereretot** [comment]
Same issue

**Comment by wwmm** [comment]
As this is being tracked on #2327 we can close this issue.
