### ISSUE TITLE
When playing song with foobar2000 (wine) plugin Level Meter begins stutter

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#2385]
### EasyEffects Version

EasyEffects 7.0.4 from git

### What package are you using?

Other (specify below)

### Distribution

Compiled EasyEffects from git

### Describe the bug

When playing song with foobar2000 (wine) plugin Level Meter begins stutter in sound.

### Expected Behavior

if I disable the plugin the sound plays correctly.

### Debug Log

<details><summary>Debug Log</summary><br/>

Paste your log here:
Open EasyEffects with "G_MESSAGES_DEBUG=easyeffects easyeffects":  (the 2 last lines)

(easyeffects:23360): easyeffects-DEBUG: 10:59:38.420: 	effects_base.cpp:248	soe: pipeline latency: 5 ms
(easyeffects:23360): easyeffects-DEBUG: 10:59:48.072: 	stream_input_effects.cpp:165	No app linked to our device wants to play. Unlinking our filters.

[pw.tar.gz](https://github.com/wwmm/easyeffects/files/11645825/pw.tar.gz)

</details>

### Additional Information

What more logs is needed? 

My pipewire.conf in /home/user/.config:
## Properties for the DSP configuration.
    default.clock.rate          = 96000
    default.clock.allowed-rates = [ 96000 ]
    default.clock.quantum       = 2048
    default.clock.min-quantum   = 32
    default.clock.max-quantum   = 2048
    default.clock.quantum-limit = 8192
    #default.video.width         = 640
    #default.video.height        = 480
    #default.video.rate.num      = 25
    #default.video.rate.denom    = 1

When I play using DeadBeef everything is good.

**Comment by wwmm** [comment]
>When I play using DeadBeef everything is good.

This together with the fact that the level meter just passthrough the audio data without changing it makes the situation very bizarre. The only thing I can thing of is that foobar is requesting low latency to PipeWire and the system is not being able to handle the extra load that comes with the level meter. Like the autogain the level meter uses the library `libebur128` and it can be heavy on resources. Run `pw-top` and compara what happens to the `RATE` and `QUANT` columns when running foobar and deadbeaf.

**Comment by wwmm** [comment]
>foobar2000 (wine)

Games executed through wine tend to ask very low latency. The same thing may be happening with foobar. IF the combination of `cpu + soundcard + drivers` is not able to handle the low latency stutter and crackling usually happen.

**Comment by servimo** [comment]
I didn't find a way to reduce the latency, some changes in the user config makes DeadBeef to stutter sound too. I just decided to play Foobar2000 without the Level Meter plugin and back to my default config. 👍🏼

**Comment by wwmm** [comment]
>I didn't find a way to reduce the latency

Actually what you have to do in these situations is increasing the latency. Before launching the audio application try to set the environmental variable `PULSE_LATENCY_MSEC` to something like `120`. You will see in `pw-top` that PipeWire's latency will be higher. This should help.

**Comment by servimo** [comment]
I edited and had to /etc/environment "PULSE_LATENCY_MSEC=120" and till now its working OK.

**Comment by servimo** [comment]
I was thinking it was something I have to change  in pipeewire conf about rate and quantum.

**Comment by wwmm** [comment]
I think we can close this.
