### ISSUE TITLE
seemingly inacurate warning about

### ISSUE THREAD

**Issue by arderyp** [wwmm/easyeffects#2388]
### EasyEffects Version

7.0.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

Upon starting EasyEffects, I get this warning:

```
Could not find compatible PipeWire.
It is recommended to install PipeWire 0.3.44 or newer for Easy Effects to work correctly. 

More info:
PipeWire  was found, which is not considered recent enough for Easy Effects.
If on Ubuntu or an Ubuntu-based system you may install newer PipeWire from: https://pipewire-debian.github.io
You may try PulseEffects which does not require PipeWire.
You may dismiss this warning by clicking "OK", please note PipeWire  is not tested to work with Easy Effects. 

If you believe this message was shown in error, please report it to: https://github.com/wwmm/easyeffects
```

When I check my PipeWire version, I see a version number that conflicts with the message above:

```
$ pipewire --version
pipewire
Compiled with libpipewire 0.3.48
Linked with libpipewire 0.3.48
```

### Expected Behavior

No warning, since PipeWire version `0.3.48` is above the EasyEffects minimum required version of `0.3.44`

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

I'm happy to test any steps/commands, just let me know.

**Comment by wwmm** [comment]
There is an issue about this #2327
