### ISSUE TITLE
Wireless headphones break the volume control

### ISSUE THREAD

**Issue by EmmanuelMess** [wwmm/easyeffects#2392]
### EasyEffects Version

7.0.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04

### Describe the bug

The headphones have a sound level button integrated that supposedly connects to the OS of the device sending data and syncs the volume. But controlling via the headphones makes the Ubuntu bar do nothing. Before controlling from the headphones the Ubuntu bar works as expected (but I don't think it is correctly informing the headphones of the volume change).

### Expected Behavior

The Ubuntu sound bar should sync with the device. At least, the audio bar should work.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Without EasyEffects, the audio bar works, but doesn't sync.

**Comment by wwmm** [comment]
I think I have to see how you are setting you default devices. Under normal circumstances EasyEffects has nothing to do with your system volume level controls. Are you settings EasyEffects  virtual devices as the system default? If yes do not do this #1836

**Comment by EmmanuelMess** [comment]
Defaults in Discord
![image](https://github.com/wwmm/easyeffects/assets/10991116/7af02052-a7d8-4384-a44e-191d51f49e01)

Defaults Ubuntu
![image](https://github.com/wwmm/easyeffects/assets/10991116/3d4966b2-b220-46b6-8b56-1a0fc186aebb)

Other defaults ubuntu
![image](https://github.com/wwmm/easyeffects/assets/10991116/69b2ebbd-fcd6-4605-ae7f-23303995b085)

**Comment by wwmm** [comment]
The default seems fine. Honestly I have no idea about what may be happening to WirePlumber/PipeWire. EasyEffects does not try to set system volumes even for its own virtual devices. The real cause of a broken volume control is definitely at a lower level and should be reported to PipeWire or WirePlumber developers.

**Comment by EmmanuelMess** [comment]
Will report to PipeWire.

**Comment by EmmanuelMess** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3285

**Comment by wwmm** [comment]
>https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3285

Ok. I am following the issue there just in case they need more technical information.
