### ISSUE TITLE
ladsp plugins

### ISSUE THREAD

**Issue by chiddekel** [wwmm/easyeffects#2402]
### EasyEffects Version

7.0.4

### What package are you using?

Fedora

### Distribution

Fedora 38

### Describe the bug

Wish list - add suport for this:

ladspa-realtime-noise-suppression-plugin
 

copr repo - lkiesow/noise-suppression-for-voice 

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
What does it do that can not be done with our `noise reduction` and `speech processor` plugins?. Our speech processor plugins has voice detection and a general purpose noise reduction while the noise reduction plugin based on rnnoise works well for noises that match its training.

At this moment we do not have any ladspa wrapper. One would have to be written from scratch and would be used only by this plugin. And in its source code I see it also uses the `rnnoise` library. So it does not seem there is any advantage in adding support for it.

**Comment by chiddekel** [comment]
How accurate this plugin is comparing to Nvidia noises cancellation?

**Comment by wwmm** [comment]
>How accurate this plugin is comparing to Nvidia noises cancellation?

As the last Windows I used was `Windows 98` I have no idea about how they compare. Considering that Nvidia is a big company they kinda have the obligation of being better. But I do not know.

One weakness of any plugin based on `rnnoise` is that its neural network was trained for specific types of noise. When the noise you want to filter match the neural network training it works really well. But not so much on the other cases. There are wells to create a custom training. And you can load the file in EasyEffects. But I have never tried to create one. The rnnoise page on github have some pointers in this regard if I am not mistaken.

**Comment by chiddekel** [comment]
How about using the noise suppression api for extend model capable to more advnaced use case with start on esayeffect or direc lasdsp plugin use?
https://ts2.space/en/a-comprehensive-guide-to-google-cloud-speech-to-text-apis-noise-suppression-techniques/

**Comment by wwmm** [comment]
>How about using the noise suppression api for extend model capable to more advnaced use cas

It doesn't seem to be suitable for realtime audio processing. And being a cloud solution there is also the problem of depending on the internet connection. It makes sense on a web browser. But it does not seem a good match for our case.

**Comment by chiddekel** [comment]
> > How about using the noise suppression api for extend model capable to more advnaced use cas
> 
> It doesn't seem to be suitable for realtime audio processing. And being a cloud solution there is also the problem of depending on the internet connection. It makes sense on a web browser. But it does not seem a good match for our case.

If any of this interest - There is container options for mentioned api.

https://cloud.google.com/speech-to-text/priv/docs

**Comment by wwmm** [comment]
At this moment there are 3 noise reduction plugins in EasyEffects. It should be enough. Let's close this issue.

**Comment by chiddekel** [comment]
I'm out of Computer 🖥️ - can nam it?

**Comment by wwmm** [comment]
>I'm out of Computer 🖥️ - can nam it?

Recently an external contributor added a plugin based on the [DeepFilterNet](https://github.com/Rikorose/DeepFilterNet) library. As all noise filters is not perfect. But it works quite well in my personal experience. It will help to cover the cases where the other 2 fail.
