### ISSUE TITLE
Spectrum displays wrong x coordinate on mouseover

### ISSUE THREAD

**Issue by azrdev** [wwmm/easyeffects#2405]
### EasyEffects Version

6.3.0

### What package are you using?

Fedora

### Distribution

Fedora 37

### Describe the bug

When hovering the mouse over the live spectrum view at the top, it displays in the top right corner the coordinates of the mouse pointer: x = <frequency> Hz, y = Volume dB.

However, the x value is a number (bands? it's less than pixels) between the configured minimum frequency and 200 (or 300 -- there is some relation to the configured min/max frequencies), which is *obviously linear* in the distance from the left border, instead of following the (logarithmic) real frequency of the FFT graph.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
This bug was fixed a long time ago. The real problem is the EasyEffects version you are using. A lot has changed when compred to the current reelase `7.0.5`
