### ISSUE TITLE
Extreme crackling when Android emulator is running

### ISSUE THREAD

**Issue by Grafcube** [wwmm/easyeffects#2406]
### EasyEffects Version

7.0.4

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Whenever I start an Android emulator, all audio suddenly gets extremely crackly to the point where it just sounds like noise. If it matters, the qemu output is excluded in easyeffects but that doesn't make a difference.

### Expected Behavior

Audio is clearly audible.

### Debug Log

[debug.log](https://github.com/wwmm/easyeffects/files/11771934/debug.log)

### Additional Information

[pw-dump](https://github.com/wwmm/easyeffects/files/11771940/pw-dump.txt)

**Comment by wwmm** [comment]
Take a look at the output of `pw-top` when there is noise. Usually in these cases "too low" latency is the cause. My guess is that Android emulator is requesting a quantum(latency) value that is too low for your system to handle.

**Comment by Grafcube** [comment]
This is what I see when I have an emulator running while audio is playing but I don't know how to read it.

![image](https://github.com/wwmm/easyeffects/assets/34889224/ae1143a6-0c4a-4101-92b9-80b80f023445)

**Comment by wwmm** [comment]
QEMU requested a latency of `118 / 44100 = 2.7 milliseconds`. As PipeWire usually preferes power of 2 it has set the quantum size to 128 what led to a latency of `128 / 48000 = 2.7 milliseconds`. No all systems handle well latency values that are so low. It will depend on the combination of CPU, soundcard, drivers etc. For example my desktop handles this just fine but my laptop struggles even with quantum sizes as high as 2048.

Games also tend to ask unreasonably low latency. So usually what I do when I am playing is setting the environmental variable `PULSE_LATENCY_MSEC` to something lie 60 or 120. Try to set it before launching the emulator.

**Comment by Grafcube** [comment]
Using `PULSE_LATENCY_MSEC=60` seems to fix the issue. Is there a more permanent solution?

**Comment by wwmm** [comment]
>Is there a more permanent solution?

If by solution you mean not having crackling without resorting to forcing a lower bound to the latency value I am afraid there isn't. Most likely your soundcard hardware or driver is not capable f handling low latency.

But if what you want is just forcing the lower bound to the latency globally there are two possibilities. Editting PipeWire cofiguration and setting a minimum quantum value. Or putting `PULSE_LATENCY_MSEC` inside `/etc/environment` and rebooting. Personally I prefer the `PULSE_LATENCY_MSEC` approach. IT specifies the target latency in milliseconds directly. If I remmeber well PipeWire configuration fiels only allow the quantum to be set. But the latency is the quantum divided by the sampling rate. So depending on the sampling rate the result will be different.

**Comment by AdityasahuX07** [comment]
> Using `PULSE_LATENCY_MSEC=60` seems to fix the issue. Is there a more permanent solution?

Hi can you explain me how to fix this audio  issue stap by step

Where i have to pyt this value at config or env
 `PULSE_LATENCY_MSEC=60`

**Comment by wwmm** [comment]
> Where i have to pyt this value at config or env
> `PULSE_LATENCY_MSEC=60`

@AdityasahuX07 you have to options. Manually start the application in the command line or settings this globally for all applications. If manually launching an app is ok something like `PULSE_LATENCY_MSEC=60 app_exe_name` is enough. But to set this for all apps editting system configuration files like `/etc/environment` is required.

On Windows the manual approach is similar. To set it globally it is probably necessary to search for the user environmental variables configuration in its launcher menu.
