### ISSUE TITLE
Reset EasyEffects Sink/Source to 100% volume level

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2408]
Am I wrong or we had an option to reset the level of EE null sinks? I can't find that setting anymore.

Don't know why but sometimes the system automatically changes the default device and I end up to modifying the EE sink level from the keyboard. Then when I restore the default device, the EE sink remains at the previous level and this is frustrating because every time I have to keep an eye on the EE level to restore it to 100%.

In an ideal world the EE sink would never be exposed to be changed by the user, but at the moment this is the situation. Can we just add an option to reset the level to 100%? I don't know... maybe every time a stream is moved to be processed by EE pipeline.

**Comment by wwmm** [comment]
By default PipeWire disables volume and mute controls for null-sinks. What we use to do in the past was to set a flag that forced it to enable the controls. But that caused issues for some users for reasons similar to the ones you are describing. So now it does not matter what is done to our virtual devices volume and mute controls. We let PipeWire do what it wasn't that is totally ignoring them.

**Comment by Digitalone1** [comment]
I wonder which is the point of disabling the controls if I can still change them. 

If I'm dealing the same issues of those users, disabling the controls was not the solution. Can you link those issues discussions? I'd like to read them. 

Do you think resetting regularly the level upon a user settings won't solve this situation?

**Comment by wwmm** [comment]
>I wonder which is the point of disabling the controls if I can still change them.

It just seem you can. What is happening is that the clients you are using were written  for pulseaudio and not pipewire. In pulseaudio there isn't the concept of a sink with controls disabled. So pavucontrol and similar software  will always show them even if at the end of the day they do not work.

>Do you think resetting regularly the level upon a user settings won't solve this situation?

We tried it. It was not enough to avoid users having our virtual devices randomly muted. Whatever it was randomly muting our them was being executed after EE reset the devices controls. There is plenty of issues here where users thought there was a problem in EE when all that was happening was that our sink was mysteriously muted. I tried lots of things along the years but this problem always come back. These controls are not worth the headache they bring.

**Comment by Digitalone1** [comment]
> It just seem you can. What is happening is that the clients you are using were written for pulseaudio and not pipewire.

Are you sure? I'm talking about the audio management in Gnome Desktop. I read it was even redesigned in the last release. How is it possible it's still written in Pulseaudio? I can select EE Sink as default device and change the level from keyboard volume keys.

**Comment by wwmm** [comment]
>Are you sure? I'm talking about the audio management in Gnome Desktop. I read it was even redesigned in the last release.

I can still see pulseaudio headers being used at its [repository](https://gitlab.gnome.org/GNOME/gnome-control-center/-/tree/main/panels/sound) 

>I can select EE Sink as default device and change the level from keyboard volume keys.

Pulseaudio clients can do this in pipewire too. In the particular case of EE devices the control will move without  doing anything because they are disabled.

**Comment by wwmm** [comment]
And even if it's backend is somehow using pipewire it is still the client responsibility to check if it makes sense to show the controls.

**Comment by Digitalone1** [comment]
> Pulseaudio clients can do this in pipewire too. In the particular case of EE devices the control will move without doing anything because they are disabled.

Yes, only now I realized this, but when I was testing some presets yesterday I noticed a big change of volume. I wrongly thought it was the null sink, but at the moment the only culprit is something that changed the volume of mpv. -_-

**Comment by Digitalone1** [comment]
Well, there's nothing to do. My mistake.

**Comment by wwmm** [comment]
No problems. It happens 😄 . But I wonder why EE devices are being used as fallback on your system so often. It may be worth to delete wireplumber folder inside ~/.local/state and reboot to reset this association.
