### ISSUE TITLE
[QUESTION] How would I use this to get audio from a source and play it through the microphone.

### ISSUE THREAD

**Issue by FredsMedia** [wwmm/easyeffects#2409]
Ok, so let’s start. I am on SteamOS and I know this probably isn’t the place to ask this, but I couldn’t really find what I was looking for elsewhere. I am trying to get music playing from either a web browser or maybe VLC and make it come out of both my default audio output (headphones) and my microphone to the Voice Chat I am in. Can this app do that, and if so how? If you don’t want to explain and want to point me to a website or something that is completely fine. Thanks 

-FredsMedia

**Comment by wwmm** [comment]
> I am trying to get music playing from either a web browser or maybe VLC and make it come out of both my default audio output (headphones) and my microphone to the Voice Chat I am in. Can this app do that, and if so how?

If I understood you want the people listening to you "on the other side" to also listen to the music being played on your computer. In this case what you have to do is searching for tutorials explaining how to setup a `loopback device`. I have never done this myself but if I am not mistaken it is how people do it.

**Comment by wwmm** [comment]
For example loopback devices are capable of making your mic signal to be played in your computer speakers. With some clever choice of input and output sources in the loopback device it is probably possible to do what you want. 

Pipewire's wiki talks a little about it https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#loopback.

**Comment by wwmm** [comment]
>Can this app do that, and if so how?

No.  EasyEffects can not do this by itself.
