### ISSUE TITLE
Moving any Equalizer slider by click and drag crashes Easy Effects under Wayland

### ISSUE THREAD

**Issue by medmedin2014** [wwmm/easyeffects#2419]
### EasyEffects Version

7.0.5

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro

### Describe the bug

On Plasma, simply clicking and dragging by mouse any slider of the equalizer crashes Easy Effects under Wayland, while using mouse scroll wheel to move the slider works fine

### Debug Log

(process:9399): easyeffects-DEBUG: 18:25:53.883:        easyeffects.cpp:35      easyeffects version: 7.0.5
(process:9399): easyeffects-DEBUG: 18:25:53.886:        easyeffects.cpp:45      locale directory: /usr/share/locale
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:49  system input presets directory: "/etc/easyeffects/input"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:49  system input presets directory: "/etc/xdg/easyeffects/input"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:49  system input presets directory: "/home/mohamed/.config/kdedefaults/easyeffects/input"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:49  system input presets directory: "/usr/share/manjaro-kde-settings/xdg/easyeffects/input"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:52  system output presets directory: "/etc/easyeffects/output"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:52  system output presets directory: "/etc/xdg/easyeffects/output"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:52  system output presets directory: "/home/mohamed/.config/kdedefaults/easyeffects/output"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:52  system output presets directory: "/usr/share/manjaro-kde-settings/xdg/easyeffects/output"; 
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:194 user presets directory already exists: /home/mohamed/.config/easyeffects/
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:194 user presets directory already exists: /home/mohamed/.config/easyeffects/input
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:194 user presets directory already exists: /home/mohamed/.config/easyeffects/output
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.937:    presets_manager.cpp:194 user presets directory already exists: /home/mohamed/.config/easyeffects/autoload/input
(easyeffects:9399): easyeffects-DEBUG: 18:25:53.938:    presets_manager.cpp:194 user presets directory already exists: /home/mohamed/.config/easyeffects/autoload/output

(easyeffects:9399): Adwaita-WARNING **: 18:25:54.313: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.442:    pipe_manager.cpp:1429   compiled with PipeWire: 0.3.71
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.442:    pipe_manager.cpp:1430   linked to PipeWire: 0.3.71
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.487:    pipe_manager.cpp:1400   core version: 0.3.71
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.489:    pipe_manager.cpp:1401   core name: pipewire-0
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.489:    pipe_manager.cpp:1312   found metadata: settings
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.490:    pipe_manager.cpp:1312   found metadata: default
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.490:    pipe_manager.cpp:1312   found metadata: route-settings
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.491:    pipe_manager.cpp:1167   Audio/Sink 55 alsa_output.pci-0000_00_1b.0.analog-stereo with serial 55 has been added
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.491:    pipe_manager.cpp:1167   Audio/Source 56 alsa_input.pci-0000_00_1b.0.analog-stereo with serial 56 has been added
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.492:    pipe_manager.cpp:1167   Stream/Output/Audio 104 Elisa with serial 1707 has been added
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.492:    pipe_manager.cpp:1207   Elisa port 61 is connected to alsa_output.pci-0000_00_1b.0.analog-stereo port 34
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.493:    pipe_manager.cpp:1207   Elisa port 106 is connected to alsa_output.pci-0000_00_1b.0.analog-stereo port 52
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.493:    pipe_manager.cpp:1167   Audio/Sink 118 easyeffects_sink with serial 1875 has been added
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.494:    pipe_manager.cpp:1167   Audio/Source/Virtual 121 easyeffects_source with serial 1876 has been added
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.495:    pipe_manager.cpp:900    new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1b.0.pro-output-0"}
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.496:    pipe_manager.cpp:900    new metadata property: 0, default.video.source, Spa:String:JSON, {"name":"v4l2_input.pci-0000_00_1d.7-usb-0_8_1.0"}
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.496:    pipe_manager.cpp:900    new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1b.0.analog-stereo"}
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.496:    pipe_manager.cpp:900    new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_1b.0.analog-stereo"}
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.497:    pipe_manager.cpp:900    new metadata property: 104, target.node, Spa:Id, 100
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.497:    pipe_manager.cpp:900    new metadata property: 104, target.object, Spa:Id, 1744
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.499:    pipe_manager.cpp:1524   easyeffects_sink node successfully retrieved with id 118 and serial 1875
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.499:    pipe_manager.cpp:1529   easyeffects_source node successfully retrieved with id 121 and serial 1876
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.521:    plugin_base.cpp:370     soe: output_level successfully connected to PipeWire graph
(easyeffects:9399): easyeffects-DEBUG: 18:25:54.530:    plugin_base.cpp:370     soe: spectrum successfully connected to PipeWire graph
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/werman/noise-suppression-for-voice>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/rnnoise_stereo.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/rnnoise_mono.lv2/ (ignored)
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.368:    lv2_wrapper.cpp:98      http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.406:    plugin_base.cpp:370     soe: equalizer successfully connected to PipeWire graph
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.407:    pipe_manager.cpp:1207   easyeffects_sink port 71 is connected to ee_soe_equalizer port 82
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.411:    pipe_manager.cpp:1207   easyeffects_sink port 74 is connected to ee_soe_equalizer port 81
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.480:    plugin_base.cpp:370     sie: output_level successfully connected to PipeWire graph
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.498:    plugin_base.cpp:370     sie: spectrum successfully connected to PipeWire graph
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.537:    stream_output_effects.cpp:317   disconnecting the equalizer filter from PipeWire
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.540:    pipe_manager.cpp:213     66 ee_soe_equalizer has been removed
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.550:    plugin_base.cpp:370     soe: equalizer successfully connected to PipeWire graph
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.551:    pipe_manager.cpp:1207   easyeffects_sink port 71 is connected to ee_soe_equalizer port 94
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.553:    pipe_manager.cpp:1207   easyeffects_sink port 74 is connected to ee_soe_equalizer port 91
easyeffects-INFO: 18:25:55.609:         application.cpp:50      disabling global bypass
(easyeffects:9399): easyeffects-DEBUG: 18:25:55.653:    application_ui.cpp:86   Icon Theme breeze-dark detected
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.512:    stream_output_effects.cpp:317   disconnecting the equalizer filter from PipeWire
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.516:    pipe_manager.cpp:213     96 ee_soe_equalizer has been removed
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.526:    plugin_base.cpp:370     soe: equalizer successfully connected to PipeWire graph
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.527:    pipe_manager.cpp:1207   easyeffects_sink port 71 is connected to ee_soe_equalizer port 81
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.528:    pipe_manager.cpp:1207   easyeffects_sink port 74 is connected to ee_soe_equalizer port 79
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.584:    application.cpp:78      new default output device: alsa_output.pci-0000_00_1b.0.analog-stereo
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.584:    application.cpp:86      new default input device: alsa_input.pci-0000_00_1b.0.analog-stereo
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.585:    application.cpp:98      device alsa_card.pci-0000_00_1b.0 has changed its input route to: analog-input-internal-mic
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.585:    application.cpp:130     device alsa_card.pci-0000_00_1b.0 has changed its output route to: analog-output-headphones
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.593:    pipe_manager.cpp:900    new metadata property: 104, target.node, Spa:Id, 118
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.593:    pipe_manager.cpp:900    new metadata property: 104, target.object, Spa:Id, 1875
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.600:    pipe_manager.cpp:1207   Elisa port 61 is connected to easyeffects_sink port 120
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.600:    pipe_manager.cpp:1207   Elisa port 106 is connected to easyeffects_sink port 70
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.685:    output_level.cpp:37     soe: output_level: PipeWire blocksize: 1024
(easyeffects:9399): easyeffects-DEBUG: 18:25:57.685:    output_level.cpp:38     soe: output_level: PipeWire sampling rate: 48000
zsh: killed     G_MESSAGES_DEBUG=easyeffects easyeffects

### Additional Information

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.8-4-MANJARO (64-bit)
Graphics Platform: Wayland

**Comment by wwmm** [comment]
>On Plasma, simply clicking and dragging by mouse any slider of the equalizer crashes Easy Effects under Wayland, while using mouse scroll wheel to move the slider works fine

Does not happen on my computer. But I am on Arch Linux and not Manjaro. I also use GNOME but if KDE was the problem there would probably be lots of other people reporting this problem. Maybe something in Manjaro package for easyeffects or gtk4 is not right.

>zsh: killed G_MESSAGES_DEBUG=easyeffects easyeffects

This isn't a crash but the system deciding to kill our process.

**Comment by wwmm** [comment]
>Did you test while playing music in any audio player like Elisa or Clementine ?

Tested while watching a video on firefox.

**Comment by wwmm** [comment]
>lilv_world_add_plugin(): warning: Duplicate plugin https://github.com/werman/noise-suppression-for-voice
>lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/rnnoise_stereo.lv2/
>lilv_world_add_plugin(): warning: ... and file:///usr/lib/lv2/rnnoise_mono.lv2/ (ignored)

This is unusual but it should not be a reason for the system to kill EE.

**Comment by wwmm** [comment]
>while using mouse scroll wheel to move the slider works fine

Under the hoods drag and scroll will call the same EasyEffects function. The fact that only the drag causes problems sounds more like a gtk4 bug than an EasyEffects bug.

**Comment by medmedin2014** [comment]
@wwmm Searching journald, I found that the OS is the one responsible for killing Easy Effects due to High CPU usage
![Screenshot_20230623_002141](https://github.com/wwmm/easyeffects/assets/7027319/f48bf7b6-ca53-4336-a4a9-5ca4f8aa8caf)
It seems there is a problem on how Easy Effects apply the selected effect changes (e.g Equalizer) when we use click and drag, I'm not sure but I think Easy Effects continuously applies each changed value of the slider while the mouse is moving instead of applying the final value that should be read when the mouse drag is released.
And because my laptop has a weak CPU i3-1005g1, the OS is killing Easy Effects to keep itself running.

**Comment by servimo** [comment]
I use left click on the line to go up or down close to what I am looking for, then I use the scroll button till I get to the right number I want.

**Comment by wwmm** [comment]
>but I think Easy Effects continuously applies each changed value of the slider while the mouse is moving instead of applying the final value that should be read when the mouse drag is released.

It is not that we do this. It is how the `GtkScale` works. We bind its value property to the corresponding property in our gsettings database and under the hoods gsettings propagates the value to all the places listening to it. What includes the LV2 equalizer plugin we use. As the plugins run in a realtime thread if the CPU is not powerful enough to finish all these gain updates fast enough the system will kill our process in self defense. That is the usual downside of the realtime thread.

I doubt there is something I can do about it. I can't change how gtk behaves when we drag the scale. And I also can't make the equalizer fast because it is a third party plugin.

**Comment by wwmm** [comment]
>I doubt there is something I can do about it. I can't change how gtk behaves when we drag the scale

And listening/viewing  the changes as we drag the scale is a valid use case. So even if there is a way to update only when we release the scale it may not be a good idea to do this by default.

**Comment by wwmm** [comment]
I think that the proper workaround here would be to find a way to solve #1383

**Comment by medmedin2014** [comment]
> > I doubt there is something I can do about it. I can't change how gtk behaves when we drag the scale

I don't know about GTK API, but in Java and .Net there were always 4 (or more) methods that handle click, drag, move and release mouse actions.

> And listening/viewing the changes as we drag the scale is a valid use case. So even if there is a way to update only when we release the scale it may not be a good idea to do this by default.

Tracking fast changes while moving the slider is useful only when you need to draw them in real-time on screen or when you want to move precisely a graphic or a shape to another position, but in case of applying a sound effect doing it for the intermediate values is simply waste of CPU usage and power and slows down the app because in that tiny lapse of time the user can't hear (and even doesn't want to hear) those intermediate output sounds.

**Comment by wwmm** [comment]
>I don't know about GTK API, but in Java and .Net there were always 4 (or more) methods that handle click, drag, move and release mouse actions.

GTk has too. But that is not what was talking about. We bind our widgets properties to keys in our gsettings database. When you change a key in the database gsettings emits the signal that updates the widget property value without the need to set any callback. In the same way when the widget property is directly changed by the user the new value is propagated to the gsettings database through the binding done previously. I could attach controllers to the click and drag of the scale but this has no effect over the fact that the widget internal implementation will still trigger a signal for the gsettings database for every new value while dragging the scale if the property binding is in place.

To do what you are suggesting I would have to kill the binding when the user holds the scale and remake it when the mouse button is released so we do not break all the other possible ways to change the scale while having the automatic database update through the binding. For example using the scroll or the keyboard arrows. They use the binding from their properties to the corresponding gsettings keys to update the plugin parameters and not a combination of callbacks and signals emitted by the widget when we scroll or use the arrows. It is doable to kill and remake the binding all the time. I had to do something like this a long time ago. But besides the additional code complication this brings with it we will totally kill the continuous update mode as you can´t have both active at the same time... 

I am not sure this problem occurs often enough to justify all this trouble. In all these years it is the first time I hear about a system killing EE because of the continuous update of the equalizer scale. I tested now on my laptop that has a weak `i7-7500U` cpu and just like in my desktop where I have a powerful `Ryzen 7700` the system did not kill EE... So it is possible something else than just having a weak processor is involved here.

**Comment by wwmm** [comment]
The current master branch has an additional spinbutton in the band menu that allows the gain to be set. This can be used as workaround in the systems where using the scale is causing crashes.

**Comment by medmedin2014** [comment]
@wwmm  The same crash happens on a different laptop running KDE Neon.
