### ISSUE TITLE
Debian 12 Bookworm launch error

### ISSUE THREAD

**Issue by Slyfox88** [wwmm/easyeffects#2423]
### EasyEffects Version

easyeffects/stable,now 7.0.0-1 amd64

### What package are you using?

Other (specify below)

### Distribution

Debian 12 Bookworm

### Describe the bug

After installing app failed to launch.

### Expected Behavior

Expect app to launch

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(easyeffects:84435): Gtk-WARNING **: 19:16:14.202: Unknown key gtk-modules in /home/user/.config/gtk-4.0/settings.ini

(easyeffects:84435): Adwaita-WARNING **: 19:16:14.246: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
[W][03121.110588] pw.conf      | [          conf.c:  939 try_load_conf()] can't load config client-rt.conf: No such file or directory
[W][03121.110638] pw.conf      | [          conf.c:  939 try_load_conf()] can't load config client.conf: No such file or directory
[E][03121.110644] pw.conf      | [          conf.c:  963 pw_conf_load_conf_for_context()] can't load default config client.conf: No such file or directory

(easyeffects:84435): easyeffects-ERROR **: 19:16:14.274:        pipe_manager.cpp:1451   could not create PipeWire context
Trace/breakpoint trap (core dumped)

```
</details>

**Comment by wwmm** [comment]
>can't load config client-rt.conf: No such file or directory

It seems your pipewire installation is broken. The file `/usr/share/pipewire/client-rt.conf` should be there

**Comment by Slyfox88** [comment]
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Server Name: pulseaudio
Server Version: 16.1

**Comment by wwmm** [comment]
Are you sure you have PipeWire running? EasyEffects does not run on Pulseaudio. You have to remove Pulseaudio and install PipeWire if you want to sue EasyEffects.

**Comment by rambo919** [comment]
Same problem on MX Linux KDE based on DB12

> > $ easyeffects 
> 
> (easyeffects:18693): Gtk-WARNING **: 13:29:26.187: Unknown key gtk-modules in /home/user/.config/gtk-4.0/settings.ini
> 
> (easyeffects:18693): easyeffects-ERROR **: 13:29:26.444:        pipe_manager.cpp:1457   context connection failed
> Trace/breakpoint trap

**Comment by Slyfox88** [comment]
Yeah, surprisingly the just released Debian 12 doesn't use PipeWire by default.
