### ISSUE TITLE
sync preset menu to what is active tab is

### ISSUE THREAD

**Issue by noelcurray** [wwmm/easyeffects#2424]
there are times that I mistakenly remove all of the effects because I am in a wrong tab.

![Screenshot_20230624_194522](https://github.com/wwmm/easyeffects/assets/83384364/b86b45a2-3027-4a30-8d3a-5e3714903ae2)

I suggest that the preset menu is sync if its output or input is active or just remove the output and input button on preset and only shows the preset of what is the current active tab.

**Comment by wwmm** [comment]
Hum... I am not sure how I feel abou this. For example I am among the ones that like the fact it is possible to change the input effects preset without actually having to switch to the input effects section. This forced synchronization would be quite annoying...

>there are times that I mistakenly remove all of the effects because I am in a wrong tab.

Which easyeffects version are you using? The latest version asks for confirmation before saving or deleting presets.

**Comment by noelcurray** [comment]
>Hum... I am not sure how I feel abou this. For example I am among the ones that like the fact it is possible to change the input effects preset without actually having to switch to the input effects section. This forced synchronization would be quite annoying...

well, if the software owner preferred it like this, then thank you for taking time to read my suggestion. 

> Which easyeffects version are you using? 

version 7.0.5

**Comment by wwmm** [comment]
>well, if the software owner preferred it like this, then thank you for taking time to read my suggestion.

If lots of people prefer things other way it is not the end of the world for me to change. Let's keep this issue opened for a while to see what happens.

**Comment by wwmm** [comment]
Implemented in the current master branch so we have space in the menu to handle #2445
