### ISSUE TITLE
No longer working after 7.0.5 update

### ISSUE THREAD

**Issue by OsaPL** [wwmm/easyeffects#2449]
### EasyEffects Version

7.0.5

### What package are you using?

Flatpak

### Distribution

Arch

### Describe the bug

After updating to the newest flatpak, the app works but wont capture any inputs/outputs.
Reverting to 7.0.4:
`flatpak update --commit=17b21ec1454afad808e324e41c80a718c803eed2f85b28bdc670786db69230fb com.github.wwmm.easyeffects`
fixes it.

### Debug Log

<details><summary>Debug Log</summary>
[log.txt](https://github.com/wwmm/easyeffects/files/12061437/log.txt)
</details>

**Comment by OsaPL** [comment]
[log.txt](https://github.com/wwmm/easyeffects/files/12061442/log.txt)

**Comment by wwmm** [comment]
So far I did not notice anything strange in your logs. I see you are also using Arch Linux. Is this problem happening also happening to the package in the stable repository or only in Flatpak?

**Comment by OsaPL** [comment]
I've been using flatpack version, cause trying to install it through pacman, yielded me some dep confilcts with other packages. It may be correlated with me not using newest pulse version atm (newer versions than `16.1` have latency issues with my setup). Once I can update, I'll check and report back.

**Comment by Digitalone1** [comment]
> It may be correlated with me not using newest pulse version atm (newer versions than `16.1` have latency issues with my setup). Once I can update, I'll check and report back.

You mean plain `pulseaudio` or `pipewire-pulse`?

**Comment by wwmm** [comment]
>cause trying to install it through pacman, yielded me some dep confilcts with other packages.

I think I see what is going on. You did not move from Pulseaudio from PipeWire. EasyEffects does not work on Pulseaudio. You have to let pacman replace Pulseaudio by PipeWire if you want yo use EasyEffects.

**Comment by OsaPL** [comment]
I dont have `pulseaudio`, what I've meant is `libpulse`, shouldve been more specific.
Anyways its all okay now, there was a some kind of problem with installed `gst-plugins-base-libs` before, which took me a while to find, and after a force install `pacman -Syy`, both flatpack, and repository versions work.
Sorry for taking up your time, but also thanks for the quick replies.
