### ISSUE TITLE
flatpak run easyeffects after update: no such backend / failed to open display

### ISSUE THREAD

**Issue by vitoravelino** [wwmm/easyeffects#2462]
### EasyEffects Version

easyeffects version: 7.0.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

I've updated `com.github.wwmm.easyeffects` (7.0.5) and `org.freedesktop.LinuxAudio.Plugins.LSP` (1.2.8) to the latest stable versions and suddenly it stopped working.

How it happened:

1. First the `org.freedesktop.LinuxAudio.Plugins.LSP` appeared and after trying to start easyeffects it didn't work
2. I ran `flatpak update` and the easyeffects update appeared
3. I upating hoping that it would fix the issue but still didn't work
4. I tried to downgrade to the previous versions but still didn't work

### Debug Log

<details><summary>Debug Log</summary><br/>

```
GTK_DEBUG=all G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects -q
(process:2): easyeffects-DEBUG: 12:42:17.300: 	easyeffects.cpp:35	easyeffects version: 7.0.5
(process:2): easyeffects-DEBUG: 12:42:17.301: 	easyeffects.cpp:45	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 12:42:17.307: 	presets_manager.cpp:49	system input presets directory: "/app/etc/xdg/easyeffects/input";
(easyeffects:2): easyeffects-DEBUG: 12:42:17.307: 	presets_manager.cpp:49	system input presets directory: "/etc/easyeffects/input";
(easyeffects:2): easyeffects-DEBUG: 12:42:17.307: 	presets_manager.cpp:49	system input presets directory: "/etc/xdg/easyeffects/input";
(easyeffects:2): easyeffects-DEBUG: 12:42:17.307: 	presets_manager.cpp:52	system output presets directory: "/app/etc/xdg/easyeffects/output";
(easyeffects:2): easyeffects-DEBUG: 12:42:17.307: 	presets_manager.cpp:52	system output presets directory: "/etc/easyeffects/output";
(easyeffects:2): easyeffects-DEBUG: 12:42:17.308: 	presets_manager.cpp:52	system output presets directory: "/etc/xdg/easyeffects/output";
(easyeffects:2): easyeffects-DEBUG: 12:42:17.308: 	presets_manager.cpp:194	user presets directory already exists: /home/vitor.avelino/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 12:42:17.308: 	presets_manager.cpp:194	user presets directory already exists: /home/vitor.avelino/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 12:42:17.308: 	presets_manager.cpp:194	user presets directory already exists: /home/vitor.avelino/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 12:42:17.308: 	presets_manager.cpp:194	user presets directory already exists: /home/vitor.avelino/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 12:42:17.308: 	presets_manager.cpp:194	user presets directory already exists: /home/vitor.avelino/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output

(easyeffects:2): Gdk-WARNING **: 12:42:17.320: No such backend: *

(easyeffects:2): Gtk-WARNING **: 12:42:17.320: Failed to open display
```
</details>

**Comment by vitoravelino** [comment]
@wwmm thanks for the quick response. Without the `-q` it's still the same.

> Something related to gtk4 seems to be broken in your installation. The question is what.

:cry:

**Comment by wwmm** [comment]
Recently an user with similar log output realized that his PipeWire installation had only the bits necessary for video but not the part that is responsible for audio and that replaces Pulseaudio. Could it be that your package manager somehow replaced PipeWire by Pulseaudio after the update?

**Comment by vitoravelino** [comment]
I use bspwm but I logged recently on gnome on wayland. I've removed `rm $XDG_RUNTIME_DIR/wayland-0*` and now the output is: 

```sh
flatpak run com.github.wwmm.easyeffects
F: Remote X11 display detected.
F: X11 access will require --share=network permission.

(easyeffects:2): Gdk-WARNING **: 13:46:35.503: No such backend: *

(easyeffects:2): Gtk-WARNING **: 13:46:35.503: Failed to open display
```

I'll check the permissions later to see if it's related to that.

**Comment by wwmm** [comment]
Hum... I do not think it should be necessary to manually add permission. What do you think @vchernin ?

**Comment by vchernin** [comment]
> Hum... I do not think it should be necessary to manually add permission. What do you think @vchernin ?

It definitely should work on both X11 and Wayland out of the box. We use the same permissions virtually all other gtk apps on flathub use. 

It sounds like your X11 setup is  configured to use a remote display which is probably not wanted. But it couldn’t hurt to try the permission for debugging.

**Comment by vitoravelino** [comment]
No luck with the permission.

>  Could it be that your package manager somehow replaced PipeWire by Pulseaudio after the update?

Unfortunately no.

**Comment by vitoravelino** [comment]
I uninstalled everything removing data, restarted and reinstalled and now it's working. 

Keep up the good work. 

Thanks for the support!
