### ISSUE TITLE
[Feature Request] Replace Calf Filter with LSP Filter Stereo

### ISSUE THREAD

**Issue by p-chan5** [wwmm/easyeffects#2489]
Hi developers! I recently upgraded to version [1.2.8](https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.8) of lsp-plugins. This release includes a [new filter plugin](https://lsp-plug.in/?page=manuals&section=filter_stereo). I've been using it for a while and it seems to me that it could replace the [Calf](https://calf-studio-gear.org/doc/Filter.html) one, since it has additional options, such as the `Bandpass`, `Ladder-pass` and `Ladder-rej` filters. And a slope of up to `x16`!

This is the introduction video of the filter plugin series:

https://www.youtube.com/watch?v=BN0h4WnNnW8

Thank you for your time and I hope it is possible. Greetings!

**Comment by wwmm** [comment]
We can close this issue.
