### ISSUE TITLE
Little bug with automatic gain: output gain info

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#2490]
### EasyEffects Version

easyeffects-git 7.0.6.r29g70f84b8a-1

### What package are you using?

AUR (easyeffects-git)

### Distribution

Manjaro Linux

### Describe the bug

Output Gain level in plugin Automatic Gain exceed the limit of the border.
![easyeffects-gain](https://github.com/wwmm/easyeffects/assets/10197145/3c30e328-fa01-45a7-a35b-08ac5d351862)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
It is a gtk4 bug that has been knows for a while #1441. Last time I looked at gtk gitlab page I saw that one of its developers were working on this. But for some reason the fixes were not merged until today.

**Comment by servimo** [comment]
Ok

Em sáb., 5 de ago. de 2023 11:23, Wellington Wallace <
***@***.***> escreveu:
