### ISSUE TITLE
Converter link is dead

### ISSUE THREAD

**Issue by sezanzeb** [wwmm/easyeffects#2499]
The link to the preset converter https://pe-to-ee-preset-converter.herokuapp.com/ (in https://github.com/wwmm/easyeffects/wiki/Community-Presets) is broken.

Is there no gist or repo somewhere for `convert.sh`?

@AbsurdlySuspicious

**Comment by AbsurdlySuspicious** [comment]
@wwmm Could you please also leave a link to this comment in wiki so it would be easier to find in future?

**Comment by wwmm** [comment]
>Could you please also leave a link to this comment in wiki so it would be easier to find in future?

Done.
