### ISSUE TITLE
The Solo button enables the left channel but not the right one (Equalizer Effect)

### ISSUE THREAD

**Issue by p-chan5** [wwmm/easyeffects#2503]
### EasyEffects Version

7.0.6

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro 22.1.3

### Describe the bug

This happens when enabling Solo mode in the equalizer band options. You can check this in the native plugin window (Experimental Features) Filters Right 0-7

### Expected Behavior

Both channels must be enabled.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
It should be working now.
