### ISSUE TITLE
Microphone input quality issues

### ISSUE THREAD

**Issue by l3ackEyeD** [wwmm/easyeffects#2506]
Following issue
I have a USB Microphone (Rode Podcaster) hooked into easy effects as input. When I turn on the monitoring for it (icon in the bottom right of easy effects) it sounds fantastic. But when I check in discord/teamspeak or any other application, where I can listen to the voice, it sounds really bad (lot of background noise and overall lower quality)

I try to fix the issue for a while, but cant wrap my head around it. Any input would be greatly appreciated

Description:    Manjaro Linux
Release:        23.0.0
Codename:       Uranos
Running Pipewire and Wireplumber

**Comment by wwmm** [comment]
>When I turn on the monitoring for it (icon in the bottom right of easy effects) it sounds fantastic. But when I check in discord/teamspeak or any other application, where I can listen to the voice, it sounds really bad (lot of background noise and overall lower quality)

That is weird. When the test button is pressed EasyEffects links the output to its microphone effects pipeline directly to the soundcard. If the sound is ok this way we can rule out the plugins being the ones responsible for the bad audio.

Maybe when the other apps are also running Pipewire is switching to a bad latency value. Run the command `pw-top` the next time you caan test. It will show the `quantum` and `sampling rate` PipeWire is actually using and with these value we can estimate the server latency.

**Comment by l3ackEyeD** [comment]
Thanks for the quick response!

![Screenshot_20230812_024011](https://github.com/wwmm/easyeffects/assets/16986456/6402c55e-7c1a-4cae-a77e-3735c4dce6e7)

**Comment by wwmm** [comment]
>Discords stats as an example

This shows only what Discord requested but not what PipeWire is actually using. This information comes in the soundcard/mic device columns. Based on the image you initially posted the soundcard latency does not seem low enough to cause problems `512 / 48000 = 0.011 seconds`. It will depend on the hardware. My laptop can not handle it. But my desktop can go a lot lower than this just fine.

If too low latency is the problem you can verify by temporarily setting a fixed and higher latency value https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Latency. Try to set the quantum to something like 2048 to see what happens.

**Comment by l3ackEyeD** [comment]
Okay I tried your advice and sadly it didnt make a difference in the quality.

> This information comes in the soundcard/mic device columns 

I am not really sure where to find that information. Sorry for the inconvenience.
Tomorrow I will try to run the mic on a windows machine to isolate the issue to linux.

I am very grateful for your help

**Comment by l3ackEyeD** [comment]
I dug deeper into the issue. It doesn't seem to be a problem on easy effects side.

**Comment by 20manas** [comment]
@I3lackEye I'm encountering the same issue. How did you fix the issue?
