### ISSUE TITLE
The minimum and maximum gain values are wrong (Equalizer Effect)

### ISSUE THREAD

**Issue by p-chan5** [wwmm/easyeffects#2509]
### EasyEffects Version

7.0.7

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro 21.1.3

### Describe the bug

After setting the gain min and max value it only goes to `+/-35 dB` instead of `+/-36 dB` as displayed in the plugin's native window.

![0001](https://github.com/wwmm/easyeffects/assets/123143444/5dc98e8c-3d43-48c1-b7cb-87618054361e) ![0002](https://github.com/wwmm/easyeffects/assets/123143444/0e621eff-cdf0-4c76-82ee-aac51a10383f)

### Expected Behavior

The minimum and maximum gain values ​​are `+/-36 dB`

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Digitalone1** [comment]
Will be fixed in the next release.
