### ISSUE TITLE
When loading a preset with Level Meter plugin

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#2514]
### EasyEffects Version

easyeffects-git-7.0.7.r13.g1ff6a04a-1-x86_64

### What package are you using?

AUR (easyeffects-git)

### Distribution

Manjaro Linux

### Describe the bug

When loading a preset with Level Meter plugin:

"Preset Not Loaded Correctly
:One or More Parameters Have a Wrong Format"
                    Close (Press ESC) 

Started EasyEffects with "G_MESSAGES_DEBUG=easyeffects easyeffects"
"(easyeffects:28153): easyeffects-WARNING **: 17:56:59.776: 	presets_manager.cpp:799	A parsing error occurred while trying to load the level_meter#0 plugin from the preset. The file could be invalid or corrupted. Please check its content.

(easyeffects:28153): easyeffects-WARNING **: 17:56:59.793: 	presets_manager.cpp:541	[json.exception.out_of_range.403] key 'level_meter' not found."

Actual Predefinition used is not showing.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Try to save a new preset. There was a bug related to the level meter settings that was fixed in the last release #2502

**Comment by servimo** [comment]
You mean save it and then reload? I am not at home now, later I will try this and give you a feedback.

**Comment by wwmm** [comment]
>You mean save it and then reload? I am not at home now, later I will try this and give you a feedback.

Yes. You have to make EasyEffects to save it again so that the section that was supposed to be in the file is written to it.

**Comment by servimo** [comment]
Yes, this remove the warning.
