### ISSUE TITLE
[Feature Request] The possibility of organize output presets under a folder, a tag or a use case: let's say, for earphones, amplifiers or author. 


### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#2515]

**Comment by servimo** [comment]
... And a folder's name? I have some presets that I use most of the time which are for earphones, sometimes I forget the name of it, and need to scroll a lot to find.

**Comment by wwmm** [comment]
>The user can create a folder inside .config/easyeffects/output and then it appears in the list of effects.

The "then it appears" that requires a lot of changes. The presets ui will have to be capable of allowing these folders to be created and removed. The code under the hoods will have to understand it has to search in subfolders and so on. It is not that it is impossible to do. But it is going to complicate how some things are handled.

**Comment by servimo** [comment]
Just thinking...
