### ISSUE TITLE
libtbb seems not found on 32-bit system even if installed already (likely regression)

### ISSUE THREAD

**Issue by hosiet** [wwmm/easyeffects#2527]
### EasyEffects Version

7.0.7

### What package are you using?

Other (specify below)

### Distribution

Debian Sid/Unstable

### Describe the bug

Current status of Debian easyeffects/7.0.7-1 build (https://buildd.debian.org/status/package.php?p=easyeffects):

![image](https://github.com/wwmm/easyeffects/assets/8443926/7e54a4c4-68d8-40f8-9c15-add0e0884d4c)

Obviously it fails to build on all 32-bit systems, including i386, due to libtbb not found even when the library is already installed.

Looking into libtbb on 32-bit OS, I found that currently libtbb does not provide `tbb.pc` on 32-bit system, but `tbb32.pc` instead. The root cause is shown in onetbb upstream CMakeLists.txt on https://github.com/oneapi-src/oneTBB/blob/71e1bb8efcc630e9625987101f6ac0aa556ea267/src/tbb/CMakeLists.txt#L157-L161 :

```cmake
if (CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(TBB_PC_NAME tbb)
else()
    set(TBB_PC_NAME tbb32)
endif()
```

In this case, the logic of tbb library lookup in https://github.com/wwmm/easyeffects/commit/1a940f180c94eb7e7d3e061497b4a2693b4f533f might be insufficient when tbb library is provided via a different .pc filename.

I haven't bisected the current easyeffects codebase yet, but it should be rather easy to reproduce this issue using any 32-bit Linux OS. Let me know if you need any help. Thanks!

**Comment by wwmm** [comment]
>In this case, the logic of tbb library lookup in https://github.com/wwmm/easyeffects/commit/1a940f180c94eb7e7d3e061497b4a2693b4f533f might be insufficient when tbb library is provided via a different .pc filename.

This sounds like something to report to `Meson` developers. We just tell Meson to find the library. If it can on 64 bits systems but not on 32 because of the lack of pkgconfig files they should probably fallback to other means.

>I haven't bisected the current easyeffects codebase yet, but it should be rather easy to reproduce this issue using any 32-bit Linux OS. Let me know if you need any help. Thanks!

Our Meson file is the only one referencing tbb. We do not even use it directly. The C++ standard library is the one requiring it for the parallel implementation of some functions. As the distributions do not put tbb as a mandatory dependency we added it to EasyEffects dependency.

**Comment by wwmm** [comment]
>The C++ standard library is the one requiring it for the parallel implementation of some functions.

I wonder if this is still the case nowadays. I haven't tested this in a long time. At least in the past the compilation crashed if calls to the parallel version of `std::for_each` were done without tbb installed.

**Comment by hosiet** [comment]
> > In this case, the logic of tbb library lookup in [1a940f1](https://github.com/wwmm/easyeffects/commit/1a940f180c94eb7e7d3e061497b4a2693b4f533f) might be insufficient when tbb library is provided via a different .pc filename.
> 
> This sounds like something to report to `Meson` developers. We just tell Meson to find the library. If it can on 64 bits systems but not on 32 because of the lack of pkgconfig files they should probably fallback to other means.

This does not look like `Meson`'s issue, but rather `libtbb` library developer's decision to use a different pkg-config `.pc` name on 32-bit systems. On 64-bit systems, they provide `tbb.pc`. On 32-bit systems, they proide `tbb32.pc`.

(BTW: meson is unable to tell that `tbb32.pc` and `tbb.pc` all provide the so-called `tbb` library. These pkg-config files does not mention standalone keyword `tbb` in their contents. Meson can only believe that they are two different libraries.)

I found a related discussion in Meson's issue list for the difference between `dependency()` and `find_library()`: https://github.com/mesonbuild/meson/issues/6405 .

Given flawed (or intended different) pkg-config `.pc` filename for `libtbb` already, I believe easyeffects will have to do workarounds unless the project does not intent to support 32-bit systems anymore. If that is the case, please let me know.

I believe the most straightforward workaround for now is to revert https://github.com/wwmm/easyeffects/commit/1a940f180c94eb7e7d3e061497b4a2693b4f533f , which still uses fallback `find_library()` method to locate libtbb. Reverting this commit is verified to be working as shown now at https://buildd.debian.org/status/package.php?p=easyeffects&suite=experimental .

The secondly workaround that I am currently thinking of is to detect `dependency('tbb32')` instead of `dependency('tbb')` on 32-bit systems. I am not sure if easyeffects maintainers are willing to implement such twisted logic in `src/meson.build`.

> > I haven't bisected the current easyeffects codebase yet, but it should be rather easy to reproduce this issue using any 32-bit Linux OS. Let me know if you need any help. Thanks!
> 
> Our Meson file is the only one referencing tbb. We do not even use it directly. The C++ standard library is the one requiring it for the parallel implementation of some functions. As the distributions do not put tbb as a mandatory dependency we added it to EasyEffects dependencies.

I believe whether easyeffects should continue to use libtbb or not is unrelated to the current topic.

**Comment by wwmm** [comment]
>I believe the most straightforward workaround for now is to revert https://github.com/wwmm/easyeffects/commit/1a940f180c94eb7e7d3e061497b4a2693b4f533f , which still uses fallback find_library() method to locate libtbb. Reverting this commit is verified to be working as shown now at https://buildd.debian.org/status/package.php?p=easyeffects&suite=experimental .

If this is enough I can do it.

>I believe whether easyeffects should continue to use libtbb or not is unrelated to the current topic.

Not us but C++ standard library.

**Comment by hosiet** [comment]
> > I believe the most straightforward workaround for now is to revert [1a940f1](https://github.com/wwmm/easyeffects/commit/1a940f180c94eb7e7d3e061497b4a2693b4f533f) , which still uses fallback find_library() method to locate libtbb. Reverting this commit is verified to be working as shown now at https://buildd.debian.org/status/package.php?p=easyeffects&suite=experimental .
> 
> If this is enough I can do it.

Yes, please consider reverting that specific commit and I believe we can close this issue.

**Comment by wwmm** [comment]
>Yes, please consider reverting that specific commit and I believe we can close this issue.

It is done.

**Comment by hosiet** [comment]
I see it committed at https://github.com/wwmm/easyeffects/commit/32599bdec8eac122a4b767c7898022c5bc1f5910 . Thanks!
