### ISSUE TITLE
crash: pw_filter_update_params called from wrong context

### ISSUE THREAD

**Issue by AgainACat** [wwmm/easyeffects#2530]
### EasyEffects Version

7.01

### What package are you using?

Other (specify below)

### Distribution

Ubuntu 23.10 Mantic

### Describe the bug

*** pw_filter_update_params called from wrong context, check thread and locking: Operation not permitted
Killed.

moving cursors of equalizer or when video ends

![Screenshot from 2023-08-19 21-43-34](https://github.com/wwmm/easyeffects/assets/128521655/616a8bed-469f-490c-8797-ca968b8bb823)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
This was fixed a few months ago. If you upgrade to the latest version `7.0.7` or one that is newer than 7.0.1 these warnings will go away.
