### ISSUE TITLE
[Feature Request] automatically switch preset per output

### ISSUE THREAD

**Issue by edwloef** [wwmm/easyeffects#2531]
### EasyEffects Version

7.07

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I would like to be able to set a preset to the default preset for a specific audio output, so I can e.g. apply different processing to my headphones and speakers, and switch automatically when the audio output is changed.

**Comment by wwmm** [comment]
You already can
![Screenshot from 2023-08-20 11-19-34](https://github.com/wwmm/easyeffects/assets/16225172/30b9926f-db9b-42b2-9f22-a1836c38d308)
Just make sure the desired device is plugged when creating the profiles
