### ISSUE TITLE
Complete the LSP Filter effect

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2544]
### EasyEffects Version

latest git

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

I have an autoloaded preset with the Filter effects included.

Today I wanted to test the new LSP Filter and compiled the latest git using the `PKGBUILD_AUR` reported here (`easyeffects-git` from AUR is not working because of a dependency issue and it's not updated anymore).

After the installation was complete, I shutdown the running instance and started the new build. Unfortunately it crashes with a core dump because the `resonance` key is missing. Always reproducible.

Downgraded at the upstream version and it's working correctly. I think there's something triggering the application of the old `resonance` parameter which is missing in the new Filter plugin and this is likely happening in the autoload stage.

This should be resolved otherwise users with the old Filter in the autoload preset can't start the next release.

### Expected Behavior

Easyeffects new version loading correctly with an autoload preset containing keys of a previous old plugin which now are missing.

### Debug Log

```
GLib-GIO-ERROR **: 09:57:56.141: Settings schema 'com.github.wwmm.easyeffects.filter' does not contain a key named 'resonance'
```

**Comment by Digitalone1** [comment]
I understood which is the issue. The preset code for the Filter was not updated when porting from CALF to LSP. It's still applying the `resonance` while the `width` is missing. I will make a PR.

**Comment by Digitalone1** [comment]
@wwmm The `gain` control is present only in the gkey schema and the `filter.cpp`, but not in the ui builder, neither in preset. Was it an intended choice to exclude it? Should I add it?

**Comment by Digitalone1** [comment]
There are also these controls:

```
Port 9:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      react
		Name:        FFT reactivity
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.200000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds
		             http://lv2plug.in/ns/ext/port-props#logarithmic

Port 10:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      shift
		Name:        Shift gain
		Minimum:     0.000000
		Maximum:     100.000000
		Default:     1.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#logarithmic
		             http://lv2plug.in/ns/ext/port-props#hasStrictBounds

Port 12:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      bal
		Name:        Output balance
		Minimum:     -100.000000
		Maximum:     100.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds

```

Should we add them?

**Comment by wwmm** [comment]
>I understood which is the issue. The preset code for the Filter was not updated when porting from CALF to LSP. It's still applying the resonance while the width is missing. I will make a PR.

Oops... I was aware I still had to work in the preset class but I did not remember it would actually crash when trying to load a preset. My bad.

>Should we add them?

Initially I though we should. But I am testing these controls now and they only seem to affect the FFT analysis. And the fft analysis is only useful when using the plugin native window. So I think we can skip these controls.

**Comment by wwmm** [comment]
The `balance` control works like the on in the equalizer and affects the balance between left and right channels. So it makes sense to add this one to the custom window and the preset class.

**Comment by Digitalone1** [comment]
Just a reminder for me: the button to show the native window does not respect the relative global settings.

**Comment by Digitalone1** [comment]
@wwmm The filter has also an Allpass type not included. Did you exclude it on purpose?

I think Ladder types should have a better label. As I understood, `Ladder-pass` is a variant of the Low-Pass. See the followings:

- https://www.uaudio.com/blog/moog-ladder-filter/
- https://www.reddit.com/r/synthesizers/comments/q5b4lt/what_is_a_ladder_filter/

While `Ladder-rej` should be a Band-Reject made in "Ladder Mode". But it seems there's no plain Band-Reject, maybe it's Notch?

Anyway I suggest to rename both respectively `Low-pass (Ladder)` and `Band-reject (Ladder)`. This would also help translator on translations. What do you think @wwmm?

**Comment by wwmm** [comment]
>The filter has also an Allpass type not included. Did you exclude it on purpose?

No. I just forgot about it.

>Anyway I suggest to rename both respectively Low-pass (Ladder) and Band-reject (Ladder). This would also help translator on translations. What do you think @wwmm?

The problem is it does not match very well what the frequency response shows. For example a ladder-rejections around 1000 HZ actually lets what is around this frequency pass and rejects what is outside of it. More or less the opposite of what a band rejection does
![Screenshot from 2023-08-25 18-26-56](https://github.com/wwmm/easyeffects/assets/16225172/d48ad5ae-41cd-4d7e-b6a8-8cd70fa349a8)
. So naming it `Band-reject (Ladder)` does not seem right. Something similar happens when selecting the ladder-pass mode. It is not the frequency response of a filter that is letting what is below the cutoff pass and rejecting the rest
![Screenshot from 2023-08-25 18-31-41](https://github.com/wwmm/easyeffects/assets/16225172/c796dc13-51d8-4361-8e00-9602b5cad1e9)
. It amplifies/attenuates the "middle step" of a ladder.  For now I think it is better to keep the English name as it is.

**Comment by wwmm** [comment]
>But it seems there's no plain Band-Reject, maybe it's Notch?

A notch filter is different from a band-reject. There isn't an explicit setting for a band-reject. The `ladder-reject` with a `positive gain` has a frequency response similar to that a band-reject filter would have
![Screenshot from 2023-08-25 18-37-42](https://github.com/wwmm/easyeffects/assets/16225172/66702efb-3a4d-4572-9cbd-bd89b3a2bccf)

**Comment by wwmm** [comment]
By the way I still have to add the gain control and the top filter mode control (IIR, FFT, etc). I will do this tomorrow if everything goes well.

**Comment by Digitalone1** [comment]
Good to know. For me it was tricky to translate this types, so I tried to search on the internet, but I misunderstood it. Therefore ladder in the label is to be interpreted as "stair", right?

**Comment by wwmm** [comment]
>Therefore ladder in the label is to be interpreted as "stair", right?

It is what I think about when I read ladder in this context.

**Comment by wwmm** [comment]
>It is what I think about when I read ladder in this context.

Because in Brazilian Portuguese we use the same word when talking about "ladder" or "stairs". But in English there is some distinction.

**Comment by Digitalone1** [comment]
> Because in Brazilian Portuguese we use the same word when talking about "ladder" or "stairs". But in English there is some distinction.

in Italian `ladder` translates to something that does not give the idea of what the filter does. I will try to find a better term...

**Comment by Digitalone1** [comment]
> By the way I still have to add the gain control and the top filter mode control (IIR, FFT, etc). I will do this tomorrow if everything goes well.

Okay. And, please, reopen this issue so I have a reminder to add the Allpass filter when I have time.
