### ISSUE TITLE
rnnoise plugin version

### ISSUE THREAD

**Issue by sephid86** [wwmm/easyeffects#2545]
Is the latest version of rnnoise plug-in installed in easyeffects?

I would like to know how to replace it with the latest version of the rnnoise plugin. please.

I want use this plugin
https://github.com/werman/noise-suppression-for-voice

**Comment by wwmm** [comment]
>Is the latest version of rnnoise plug-in installed in easyeffects?

We do not embed rnnoise in our sources. We use the one that was available in the system when EasyEffects was compiled. 

>I want use this plugin

This isn't the rnnoise library but just a plugin also based on rnnoise. Some of the features advertised in its readme are also available in EasyEffects. But you have to enable the `Speech Processor` plugin to have them.

**Comment by sephid86** [comment]
Thank you for your answer. I will review what you said. And if the quality is lacking, I will comment on this post again. The rnnoise plugin I talked about is of very good quality. This is good because there is less deterioration.

If the method you mentioned is of better quality, I will close this post myself.

**Comment by wwmm** [comment]
The rnnoise plugin in our master branch has been improved with its own voice activity detection algorithm. So this can now be done without the need to use the speech processor plugin.

**Comment by sephid86** [comment]
I bow my head and thank you.

I'm short on time these days and need some time to check, so I'll close the issue first.

If a problem is found in the future, we will reopen the issue.
