### ISSUE TITLE
Complete RNNoise effect

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2556]
@WillyPillow @wwmm 

- [x] VAD Threshold ans Wet controls should use dB unit rather than linear scale
- [x] Expose dB and ms units in new widgets UI for VAD Threshold, Wet and Release

**Comment by wwmm** [comment]
>VAD Threshold ans Wet controls should use dB unit rather than linear scale

The wet control should be. But looking at the code the `VAD threshold` is being compared to a probability of voice detection. So its function is similar to the VAD control in the speex processor plugin. I think we should put just a percentage symbol on it.

**Comment by WillyPillow** [comment]
Thanks for the comments! I should be able to upload a new PR addressing these points ~tomorrow.

**Comment by wwmm** [comment]
>Thanks for the comments! I should be able to upload a new PR addressing these points ~tomorrow.

I think I can do this now.

**Comment by wwmm** [comment]
I have updated the master branch. It seems fine but test it when possible.

**Comment by Digitalone1** [comment]
This is how the Model list is shown on my laptop. I don't think it's very pleasant to see only one entry in the list.

![Schermata del 2023-08-28 01-07-45](https://github.com/wwmm/easyeffects/assets/25790525/728b06f9-8209-45d4-aaa3-6051e7f03be5)

Can we force a minimal height? At least to show 2-3 entries of the list and force the whole UI to be vertical scrollable.

**Comment by wwmm** [comment]
>Can we force a minimal height? At least to show 2-3 entries of the list and force the whole UI to be vertical scrollable.

It is probably better to reorganize the whole interface a little in a way that the list is not in the same vertical box as the new controls. Something came to my mind now. Let me do some tests.

**Comment by wwmm** [comment]
This should make things a little better
![Screenshot from 2023-08-27 21-48-53](https://github.com/wwmm/easyeffects/assets/16225172/9d199d55-6aa3-471d-a866-deda0654a73f)
The minimum list height is automatically the same as the one from the AdwPreferencesGroup at its side.

**Comment by Digitalone1** [comment]
@wwmm Nice.

I don't like the fact that the current release emits many warnings on the new LSP. I suggest to wait 2-3 days and, if no issue will came out, make a new release. 

For exposing new features of LSP, we can still do it in another next release.

**Comment by wwmm** [comment]
>I don't like the fact that the current release emits many warnings on the new LSP. I suggest to wait 2-3 days and, if no issue will came out, make a new release.

I think we can do it today.

>For exposing new features of LSP, we can still do it in another next release.

Yes. Based on what I have seen on the plugins native window it may require some work to handle the mode where the compressor/gate channels are independent. The contents in one of the native window combo boxes become completely different when compression/gating of each channel is independent.

**Comment by wwmm** [comment]
>At least one day to make new translations by translators

Ok.

**Comment by Digitalone1** [comment]
@vchernin new 7.0.8 out; it needs LSP 1.2.10.
