### ISSUE TITLE
Missing a parameter + a default value in the new filter plugin.

### ISSUE THREAD

**Issue by p-chan5** [wwmm/easyeffects#2570]
Hi guys, I was testing this effect in depth and noticed a few things were missing:

1. Equalizer Mode is absent. You should be able to choose between IIR, FIR, FFT or SPM processing.

![002](https://github.com/wwmm/easyeffects/assets/123143444/6a3ba92a-0d38-41b6-aeed-1cb92f579e91)

![000](https://github.com/wwmm/easyeffects/assets/123143444/5059f3f9-16b8-42e9-96a1-93c825b9291c)

2. The default value of Frequency is 10,000 Hz and not 2,000 Hz

Everything else is fine. Thank you very much for this wonderful effect :D

**Comment by wwmm** [comment]
>Equalizer Mode is absent. You should be able to choose between IIR, FIR, FFT or SPM processing.

Yes. As well as some of the new compressor and gate options. I rushed this release because as the last one was people's logs were spammed by warnings about not found LV2 ports.

**Comment by p-chan5** [comment]
Thanks @wwmm. Yes, from what I understand there are still problems with the new version of LSP.

Don't worry and take your time. These changes can wait a little longer.

Just in case I'll keep looking for bugs. If I discover something new, rest assured that I will report it here. Greetings.
