### ISSUE TITLE
noise reduction chops up my speech

### ISSUE THREAD

**Issue by majewsky** [wwmm/easyeffects#2572]
### EasyEffects Version

7.0.8

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I have an input effects chain set up with just the Noise Reduction filter on "Standard Model". This worked like a charm up until 7.0.7. After upgrading to 7.0.8 today, my voice is now appearing chopped up, as if the noise classification is too aggressive. 

### Expected Behavior

Speech should not be filtered out.

### Additional Information

This is unrelated to recording applications: I can reproduce it by just having EasyEffects open, having just the Noise Reduction filter with default settings on, and using the bottom-right corner button that mirrors the processed input onto my headphones.

After some twiddling with the newly added parameters, it appears that turning the "Threshold" down from the default 95% makes it better. But even at 20%, there's still some chopping that the 7.0.7 version does not exhibit.

**Comment by wwmm** [comment]
As the code is right now the voice detection is always applied. It is something that can be improved in the future but I think that setting the threshold to zero should be enough to have the old behavior back. In this case anything should be considered voice. Did you try to set it to zero?

**Comment by majewsky** [comment]
Interesting. At zero, it does seem to work as intended. Would it make more sense to put that as a default then? I don't have insight into the general case, but in my specific case whatever the previous versions did was a rock-solid default, so while I appreciate giving more options, I'm biased towards leaving the defaults as they were before.

**Comment by wwmm** [comment]
>Would it make more sense to put that as a default then?

Then some people will complain that the voice detection does not work by default. It is probably going to be necessary to add an on/off switch for the whole voice detection block.

**Comment by wwmm** [comment]
>What are the settings to match the previous behavior?

Setting the release value to the maximum should help. But I will update our master branch with a toggle to fully disable the VAD.

**Comment by wwmm** [comment]
I have updated our master branch. Users on Arch Linux can test it through the AUR package. IT seems fine as far as I could see in my tests. Let me know if you face any problem.

**Comment by Ropid** [comment]
It seems to me there's a bug with the settings not getting applied after a restart. I've set threshold to 0%, but when I restart then the filter seems to behave like with the default 95% setting. I have to open the easyeffects window and change threshold to something else and then back to 0% to get it to apply the setting.

**Comment by wwmm** [comment]
>It seems to me there's a bug with the settings not getting applied after a restart. I've set threshold to 0%, but when I restart then the filter seems to behave like with the default 95% setting. I have to open the easyeffects window and change threshold to something else and then back to 0% to get it to apply the setting.

Thanks for the report @Ropid . I fixed our master branch now.

**Comment by wwmm** [comment]
>+1 on making 0% the default.

I added to our master branch a switch that allows the voice detection to be disabled. With this control in place it does not make sense to make the threshold equal to zero by default.

**Comment by zastrixarundell** [comment]
Okay. I can't seem to find  that swith @wwmm. Is it available in the latest flatpak? The flatpak was last updated 10 days ago.

**Comment by wwmm** [comment]
New release done.

**Comment by zastrixarundell** [comment]
Updated the flatpak for EasyEffects with [#182](https://github.com/flathub/com.github.wwmm.easyeffects/pull/182) and everything seems to be working. Thanks a lot for the info!
