### ISSUE TITLE
wiki workflow

### ISSUE THREAD

**Issue by marcscama** [wwmm/easyeffects#260]
HELLO guys

i want know if i can't use the app or there is something wrong on my configuration

i use a usb dac speakers (kanto yu2) and linuxmint 19 mate and flathub pulseffects.

i comment with # the file pulseaudio module on...
but sometimes if i run before spotify and after the pulseeffects i have no sound

also i see in the pulseaudio option input that pulseefect is working...

so i'm confused and i need a workflow to setup  correct the input and output

thanks

**Comment by wwmm** [comment]
You post is a little confusing. I didn't understand.

It shouldn't make difference who is started first. Unless you have Pulseaudio 11 and one of the modules mentioned at [FAQ](https://github.com/wwmm/pulseeffects/wiki/FAQ) no special procedure is necessary.

If that is not the problem maybe you just need to turn on the option `Enable All Applications`
![screenshot from 2018-07-11 11-24-14](https://user-images.githubusercontent.com/16225172/42578372-bb09369e-84fc-11e8-8509-e8e5194c8f7b.png)

**Comment by marcscama** [comment]
thank you for your reply

now when i open pulseeffects it rest blocked...

**Comment by marcscama** [comment]
![schermata a 2018-07-15 10-42-01](https://user-images.githubusercontent.com/32490781/42732156-ed9a5b2a-881b-11e8-9d1f-e62c3330e981.png)
![schermata a 2018-07-15 10-42-38](https://user-images.githubusercontent.com/32490781/42732157-edba87f6-881b-11e8-8a52-908d817ec1f8.png)

is it normal this configuration? the mic is normal?

**Comment by wwmm** [comment]
Do not set `PulseEffects(apps)` as default system output or input device because this will probably break PulseEffects audio routing. Use your sound card as default device instead.

**Comment by mikhailnov** [comment]
Try PulseAudio 12.2 and PulseEffects native deb package (not Flatpak)
```
sudo add-apt-repository ppa:mikhailnov/desktop1-dev -y
sudo apt install pulseeffects calf-plugins pulseaudio -y
```
and reboot.

I think such problems were solved in PulseAudio 12. Please test.

**Comment by mikhailnov** [comment]
use `pavucontrol` to fix default output devices if https://github.com/wwmm/pulseeffects/issues/260#issuecomment-407586131 does not help
![screenshot_56](https://user-images.githubusercontent.com/15802528/43171787-7126289e-8fb4-11e8-9051-563b5947d5f6.png)
