### ISSUE TITLE
Fail to build when rnnoise is not enabled

### ISSUE THREAD

**Issue by hosiet** [wwmm/easyeffects#2600]
### EasyEffects Version

git HEAD (2023-09-11)

### What package are you using?

Other (specify below)

### Distribution

(any)

### Describe the bug

With https://github.com/wwmm/easyeffects/commit/2c9bb225fe615207ba5ebe1c6fae3e6a3296e720 , `RNNoise::init_release()` is called if `ENABLE_RNNOISE` is defined. However, `RNNoise::init_release()` is not guarded with macro `ENABLE_RNNOISE` when first defined. This raises the following build error when rnnoise is not enabled during configure:

```
../src/rnnoise.cpp: In member function ‘void RNNoise::init_release()’:
../src/rnnoise.cpp:354:3: error: ‘vad_grace_left’ was not declared in this scope
  354 |   vad_grace_left = release;
      |   ^~~~~~~~~~~~~~
../src/rnnoise.cpp:355:3: error: ‘vad_grace_right’ was not declared in this scope
  355 |   vad_grace_right = release;
      |   ^~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

I believe that the solution is to guard `RNNoise::init_release()` with `#ifdef ENABLE_RNNOISE` as well.

**Comment by wwmm** [comment]
Thanks! I have updated the master branch with these changes.
