### ISSUE TITLE
[Feature request] Only load preset for 1 device, deactivate for all other devices

### ISSUE THREAD

**Issue by then4p** [wwmm/easyeffects#2606]
Hi, I love EasyEffects and it works great on my laptop for making the speakers sound a bit more bassy and clear. However, for headphones, bluetooth devices etc. I'd love to keep a clean output. Currently I have a "Clean Output" preset and a "Speaker" preset. The speaker preset is autoloading whenever the speakers are the active device, but now I keep adding BT headsets, new HDMI devices etc. to autoload the "Clean Output" preset. 

A feature to only activate a preset for a specific device and name, and deactivate it for everything else would be amazing.

**Comment by wwmm** [comment]
I think that what you ask is in the same direction as #1359. So it will be more efficient for me to keep only the other issue opened and close this one.

>A feature to only activate a preset for a specific device and name, and deactivate it for everything else would be amazing.

I hope to find time some day to do some work in our autoloading code. But deactivating isn't doable becaulse all that the presets do is updating our gsettings database. The database is the one automatically updating the widgets. That is one you do not have to load a preset to bring back the parameters used in the last section. The database remembers them and automatically loads them. So we have to find a solution that does not work against our database.
