### ISSUE TITLE
convolver impulse/spectrum graphics broken

### ISSUE THREAD

**Issue by MASHtm** [wwmm/easyeffects#2610]
### EasyEffects Version

7.0.8

### What package are you using?

Fedora

### Distribution

Fedora 38 MATE spin

### Describe the bug

Adding a convolver effect and loading an impulse leads to random grahpics display. Sometimes only the X-axis has values and no curve at all, sometimes a curve with random lines to/from coord 0,0 (top-left corner) is shown. Display changes from load/restart to the next one.

Tried with several "presets" for my Lenovo Carbon X1 from
https://www.reddit.com/r/thinkpad/comments/q5pt38/x1_extreme_gen_4_dolby_atmos_setup_for_linux/
and
https://github.com/JackHack96/EasyEffects-Presets/

Tried both on my Lenovo with Intel GPU and on my Desktop with nvidia GPU (nvidia not nouveau).

This worked back an pulseeffects IIRC. Didn't work on any easyeffects 7.0.x release yet.

### Expected Behavior

Correct sample display.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by MASHtm** [comment]
These pictures are generated on my nvidia Desktop machine. That's why convolver is loaded but disabled. But that doesn't affect the bug described.

That's what i have currently on my screen with "music-balanced" loaded. Can try to reproduce more of them at any time, but this one shows at least the case with lines to the top-left corner pretty well.
![easyeffects_convolver_1](https://github.com/wwmm/easyeffects/assets/1577572/6c30ba99-2561-4f0b-b13e-0f1c2332a120)

Another one with different Impulse (Dolby ATMOS ((128K MP3)) 1.Default) showing the "only x-axis" case.
![easyeffects_convolver_2](https://github.com/wwmm/easyeffects/assets/1577572/73b6de08-222c-4e18-af1f-15edc316620a)

Another one of "music-balanced" after reloading it again...
![easyeffects_convolver_3](https://github.com/wwmm/easyeffects/assets/1577572/9c87ea39-8e41-45ac-a2b4-f12e675a0477)

**Comment by wwmm** [comment]
This is how the impulse `music-balanced` looks on my computer
![Screenshot from 2023-09-20 19-06-04](https://github.com/wwmm/easyeffects/assets/16225172/9674038a-3dde-4dc2-8729-f23891c22c16)
I wonder what is going on for this plot to become like the one in your images. If you run in debug mode https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs what is printed in the logs?

**Comment by MASHtm** [comment]
Sorry for the delay. I missed your last response last week and did not get a notification.

Even your screenshot is wrong IMO. Try to load the impulse in audacity (or similar). It ends where your your display shows more then just the impulse and where mine get "fuzzy". This looks like "old" or "uninitialized" data from a large buffer is drawn while the impulse itself is much shorter then shown. It seems the actual count of sample points drawn is wrong.

When I try to load an impulse the debug output shows (meanwhile easyeffects 4.1.0!):
```
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.758: 	convolver.cpp:282	soe: convolver: irs file: /home/mash/.config/easyeffects/irs/voice.irs
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.758: 	convolver.cpp:283	soe: convolver: irs rate: 48000 Hz
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.758: 	convolver.cpp:284	soe: convolver: irs channels: 2
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.758: 	convolver.cpp:285	soe: convolver: irs frames: 125
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.758: 	convolver.cpp:324	soe: convolver: kernel initialized
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.758: 	convolver.cpp:360	soe: autogain factor: 0.87686676
(easyeffects:172682): easyeffects-DEBUG: 16:41:26.759: 	convolver.cpp:442	soe: convolver: zita is ready
(easyeffects:172682): easyeffects-DEBUG: 16:41:31.475: 	convolver_ui_common.cpp:33	reading the impulse file: /home/mash/.config/easyeffects/irs/voice.irs
(easyeffects:172682): easyeffects-DEBUG: 16:41:31.475: 	convolver_ui.cpp:192	 calculating the impulse fft...
(easyeffects:172682): easyeffects-DEBUG: 16:41:31.476: 	convolver_ui.cpp:277	min fft frequency: 380.952392578125
(easyeffects:172682): easyeffects-DEBUG: 16:41:31.476: 	convolver_ui.cpp:278	max fft frequency: 23619.046875
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.238: 	convolver.cpp:282	soe: convolver: irs file: /home/mash/.config/easyeffects/irs/music-balanced.irs
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.238: 	convolver.cpp:283	soe: convolver: irs rate: 48000 Hz
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.238: 	convolver.cpp:284	soe: convolver: irs channels: 2
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.238: 	convolver.cpp:285	soe: convolver: irs frames: 364
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.238: 	convolver.cpp:324	soe: convolver: kernel initialized
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.238: 	convolver.cpp:360	soe: autogain factor: 0.8000903
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.239: 	convolver.cpp:442	soe: convolver: zita is ready
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.239: 	convolver_ui_common.cpp:33	reading the impulse file: /home/mash/.config/easyeffects/irs/music-balanced.irs
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.239: 	convolver_ui.cpp:192	 calculating the impulse fft...
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.240: 	convolver_ui.cpp:277	min fft frequency: 131.1475372314453
(easyeffects:172682): easyeffects-DEBUG: 16:41:42.240: 	convolver_ui.cpp:278	max fft frequency: 23868.8515625
```

**Comment by wwmm** [comment]
>This looks like "old" or "uninitialized" data from a large buffer is drawn while the impulse itself is much shorter then shown.

I did more tests and that last half of the plot is changing when the impulse is reloaded. Some kind of regression happened indeed. I wonder where considering the convolver code hasn't changed in a while.

**Comment by wwmm** [comment]
It is weird. Impulse files with thousands of points (usually the ones I test) seem fine. So the problem may be the spline interpolation doing something weird when the number of points is low. I will have to investigate it.

**Comment by MASHtm** [comment]
Interesting. If I use the "[Dolby ATMOS ((128K MP3)) 1.Default.irs" impulse from JackHack96 with 10386 samples I get an empty impulse graph. The others show just fine impulse graphs as you say. 

Maybe my assumption that it worked in the past (back to pulseeffects) was wrong and the short irs files never worked. I only use those since I got my Carbon X1 back late in 2022.

**Comment by wwmm** [comment]
>Maybe my assumption that it worked in the past (back to pulseeffects) was wrong and the short irs files never worked.

Maybe it worked. In PulseEffects the interpolation was done with the `C++ Boost` library. But as it is a huge dependency that caused some headaches for package maintainers from time to time I  switched to the GNU GSL library. Maybe it has problems I am not aware of or I am using it wrongly. I did a test now without the interpolation
![Screenshot from 2023-09-30 11-57-30](https://github.com/wwmm/easyeffects/assets/16225172/d08c5315-6424-4d81-b832-f6e7dda8fbac)

**Comment by wwmm** [comment]
We have to use interpolation because some impulse files have several thousands of points. Trying to draw all of them is not only pointless but also very heavy on the CPU. I have to figure out what is going wrong when using GSL in our case.

**Comment by wwmm** [comment]
@MASHtm I have found the source of the problem. It is fixed in our master branch now.

**Comment by MASHtm** [comment]
I cherrypicked the patch and rebuilt 7.1.0 f38 rpm with it. Looks good.

**Comment by MASHtm** [comment]
looks good on 7.1.1-1.f39 as well. closing the issue
