### ISSUE TITLE
Audio processing stops when program is loaded and closed

### ISSUE THREAD

**Issue by sithdaddy** [wwmm/easyeffects#2611]
### EasyEffects Version

7.1.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint 21.2 Cinnamon 5.8.4

### Describe the bug

EasyEffects is loaded by the OS from the startup applications manager with this command..

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service`

The command above runs EasyEffects service fine in the background , audio processing of the input and output work fine.

When i load the EasyEffects program to perform changes to the settings and then close it , the audio processing stops as well and the OS resorts back to whatever default audio driver it knows.

I attached some pictures from Flatseal that show how the flatkpak for EasyEffects is set up.

![flatseal1](https://github.com/wwmm/easyeffects/assets/32434220/80bff8d1-2121-443b-9b04-02e42ba151ae)
![flatseal2](https://github.com/wwmm/easyeffects/assets/32434220/3a25b40c-d4a0-4f63-af82-155ea560f3f4)
![flatseal 3](https://github.com/wwmm/easyeffects/assets/32434220/a6958324-2c6a-4497-a1df-a1a36018e3b9)

### Expected Behavior

Opening and closing the EasyEffects program at any time without the audio processing to stop as soon as the program closes.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Sounds like you have shutdown on window close enabled in preferences. 

@wwmm these days gnome does not try to shut down flatpak applications without background permission. It just puts a small warning in the top right menu. This means we could change shutdown on window close to disabled by default in flatpak, like in other builds.

**Comment by wwmm** [comment]
>This means we could change shutdown on window close to disabled by default in flatpak, like in other builds.

I have no objections to the change. @sithdaddy can you confirm if setting this setting to off in EasyEffects preferences window is enough to fix your problem?

**Comment by sithdaddy** [comment]
When i try to uncheck "Shutdown on Window Closing" i get the message bellow in the picture...
![easyeffects settings](https://github.com/wwmm/easyeffects/assets/32434220/18426ea8-892d-4d96-8214-8cd4aff00ba2)

BTW , i get the same message when i try enable "Launch Service at System Startup" .

**Comment by vchernin** [comment]
> When i try to uncheck "Shutdown on Window Closing" i get the message bellow in the picture...
> 
> ![easyeffects settings](https://github.com/wwmm/easyeffects/assets/32434220/18426ea8-892d-4d96-8214-8cd4aff00ba2)
> 
> 
> 
> BTW , i get the same message when i try enable "Launch Service at System Startup" .

That is because your system does not provide a background portal implementation. You can workaround the issue by using gnome's with `sudo apt install --no-install-recommends xdg-desktop-portal-gnome`

**Comment by sithdaddy** [comment]
The solutions seems to have worked.

I had to do an extra step though. I had to use Flatseal to enable the EasyEffects flatpak to run in the background. Without that step i was still not able to toggle the "Shutdown on Window Closing"  and  "Launch Service at System Startup"  switches.

![flatseal4](https://github.com/wwmm/easyeffects/assets/32434220/6268aad7-7ed4-4180-805e-d9e38acc083a)

I even tried this before doing the extra step above in Flatseal : `sudo flatpak permission-reset com.github.wwmm.easyeffects` which didnt help either.

Not sure if this extra step in Flatseal would have been required had i installed `sudo apt install --no-install-recommends xdg-desktop-portal-gnome` before installing the EasyEffects flatpak.

Let's see if this will solve the problem long term.  Thanks for the tip guys.

I have not been using Linux for very long and i am still learning. My question is , does the Cinnamon desktop not have it's own background portal ?

**Comment by vchernin** [comment]
> I even tried this before doing the extra step above in Flatseal : `sudo flatpak permission-reset com.github.wwmm.easyeffects` which didnt help either.

That error message unfortunately isn’t applicable to this situation.

> Not sure if this extra step in Flatseal would have been required had i installed `sudo apt install --no-install-recommends xdg-desktop-portal-gnome` before installing the EasyEffects flatpak.

Had the background portal been working you would have been able to allow easyeffects background access. This has the same effect of enabling the background switch in flatseal.

> I have not been using Linux for very long and i am still learning. My question is , does the Cinnamon desktop not have it's own background portal ?

It definitely seems that way, on a fresh installation these things should be working out of the box.

**Comment by wwmm** [comment]
> Close as fixed?

Yes.
