### ISSUE TITLE
Settings schema 'com.github.wwmm.easyeffects.rnnoise' does not contain a key named 'enable-vad'

### ISSUE THREAD

**Issue by TheEpic-dev** [wwmm/easyeffects#2631]
### EasyEffects Version

7.1.0-1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

After upgrading from version 7.0 to 7.1, `easyeffects` on Arch Linux crashes with the following message:
```bash
$ easyeffects

(easyeffects:pid: GLib-GIO-ERROR **: 20:08:14.676: Settings schema 'com.github.wwmm.easyeffects.rnnoise' does not contain a key named 'enable-vad'
 Job 1, 'easyeffects' terminated by signal SIGTRAP (Trace or breakpoint trap)
 ```

Any idea how I could solve this? I tried running the following lines, but it did not solve it. I tried with both `0` and `1`.
```bash
$  dconf write /com/github/wwmm/easyeffects/streaminputs/rnnoise/enable-vad 1
$  dconf write /com/github/wwmm/easyeffects/streaminputs/rnnoise/0/enable-vad 1
```

### Additional Information

I also have a bunch of optional plugins installed; I'm not sure if one of those may be responsible.

```bash
Optional Deps   : calf: limiter, exciter, bass enhancer and others [installed]
                  lsp-plugins-lv2: equalizer, compressor, delay, loudness [installed]
                  zam-plugins-lv2: maximizer [installed]
                  mda.lv2: bass loudness plugin [installed]
```

**Comment by wwmm** [comment]
>Any idea how I could solve this?

It seems that for some reason the pacakge manager installation scripts did not run `glib-compile-schemas data/schemas/` after installing the package. Usually this happens automatically. In any case if you execute it as root it should fix this problem.

**Comment by TheEpic-dev** [comment]
Perfect, that fixed it. Thanks a lot for the answer, and this great application! :smile:

It was probably just my computer. It did weird things during a recent update.
