### ISSUE TITLE
Hangs when open dropdowns, popup window, etc.

### ISSUE THREAD

**Issue by azvyae** [wwmm/easyeffects#2644]
### EasyEffects Version

7.1.0

### What package are you using?

Fedora

### Distribution

Fedora 38

### Describe the bug

Last time i'm using this it has no problem when accessing dropdown button on preset autoloading, or the ... dots in the top right, i'm not sure that i just updated the easy effects and this (the hangs) happens.

I'm using wayland anyway

**Comment by wwmm** [comment]
It is the same as #1182. It has to be fixed by gtk4 developers. But for some reason they are taking years to do it.
