### ISSUE TITLE
Huge virtual memory usage of >8GiB

### ISSUE THREAD

**Issue by Massimo-B** [wwmm/easyeffects#2645]
### EasyEffects Version

7.0.5

### What package are you using?

Arch (easyeffects)

### Distribution

Gentoo

### Describe the bug

After uptime of 3 days, easyeffects is using more than 8GiB of virtual memory.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by Massimo-B** [comment]
[easyeffects_pmap.txt](https://github.com/wwmm/easyeffects/files/12877805/easyeffects_pmap.txt)

**Comment by wwmm** [comment]
As far as I am aware controlling the virtual memory usage is outside of the app control. It is something decided by the system at a much lower level It is not the same as actually allocated physical memory. And it is probably harmless. For example Firefox is using more than 12 GB of virtual memory at the moment I am write this message. And it has been opened for just a few minutes.

I do not see anything wrong here. High virtual memory use is not a memory leak.
