### ISSUE TITLE
Input and Output devices keep switching

### ISSUE THREAD

**Issue by RobCod** [wwmm/easyeffects#2658]
### EasyEffects Version

7.1.0

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Easy Effects constantly changes my Input and Output devices under device management making me open it and switch them back again, the toggle switches seem to do nothing to lock this from happening.

### Expected Behavior

I set the output and input devices and it should never change to my KVM switch or other random device EVER.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Not log
```
</details>

**Comment by violetmage** [comment]
You can get logs by running easyeffects from a terminal.

Can you share a screenshot of the panel that opens when you click the "Audio mixer" button, that is shown in your last screenshot?

Is there any reason why you have the "Use Default Input / Output" options disabled?

**Comment by wwmm** [comment]
>Easy Effects constantly changes my Input and Output devices under device management
>Switches happen randomly at startup

When you disable `Use Default` EasyEffects will try to use the device that was selected. But this is only going to work if at the moment it tries to do it PipeWire/WirePlumber has already notified EasyEffects about these devices existence. If they are not ready yet then something else will be used. Considering that restarting is the key for the issue my guess is that by the time EasyEffects tries to use them PipeWire did not prepare these devices yet.

If that is the case trying to delay EasyEffects startup so PipeWire has more time to load the devices you want to use will help.

**Comment by RobCod** [comment]
Yeah Reason I have it set up that way is because the audio doesn't go through easyeffects when I have my devices set as the devices I want them to output to

**Comment by wwmm** [comment]
>It looks like you've set easy effects as your default input and output.

Yes. This can cause random problems. Specially when the system starts https://github.com/wwmm/easyeffects/discussions/1836

**Comment by RobCod** [comment]
It seems to be working as expected now, I'll report back once I restart my computer.

**Comment by violetmage** [comment]
@RobCod any news?

**Comment by RobCod** [comment]
> @RobCod any news?

Still works well! Which is odd, cause it never worked when I tried this before

**Comment by violetmage** [comment]
close as fixed?

**Comment by RobCod** [comment]
Yeah you can close it

**Comment by violetmage** [comment]
I can't, as I'm not a maintainer. You can, however, since you opened the issue.

Also, I'm happy we could help
