### ISSUE TITLE
Easyeffects compressor no volume output

### ISSUE THREAD

**Issue by reejit** [wwmm/easyeffects#2659]
### EasyEffects Version

7.1.0

### What package are you using?

Arch (easyeffects)

### Distribution

Arch

### Describe the bug

Whenever I am using easy effects everything works but the compressor gives me a gain of minus 100 decibels which practically makes it mute I don't know how to change it but I can't turn off the compressor because it will make the sound very distorted any work around I can use without removing the function of compressor?
![16975413071148357713356126694212](https://github.com/wwmm/easyeffects/assets/70316178/e87d868a-80c3-448d-a41d-fb3a7d10b8b4)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by violetmage** [comment]
What happens when you press the reset button in the compressor settings?

**Comment by wwmm** [comment]
The compressor is fine on my computer but for development purposes I use our current master branch. @reejit does the problem go away if you install the AUR package?

**Comment by wwmm** [comment]
This is probably the same as #2608. So it will be more efficient to keep the discussion there. Put the information you brought here there.

**Comment by wwmm** [comment]
>I will add that sometimes only one channel works for me, though I am now not sure if it is in compressor or earlier.

This is probably https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3547
