### ISSUE TITLE
Equalizer: Solo and Mute band options don't work

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2665]
Please, try to reproduce it on your system. Enabling them in the band settings do not change the output. It's the same inside the  native UI.

Could it be an LSP bug? I don't see it reported on their Github...

**Comment by wwmm** [comment]
>Enabling them in the band settings do not change the output. It's the same inside the native UI.

No. THey are working fine here. I tested through the `high-pass` and `low-pass` modes. For example I set the low-pass to `100 Hz`. The solo and mute buttons did what I would expect them to do.

**Comment by Digitalone1** [comment]
You're right, I expected some differences in the sound, but I only hear them in particular setups, not the one I frequently use.
