### ISSUE TITLE
DeepFilter: UI inconsistencies

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2666]
Is there a specific reason to use a scale while other dB units use a spinbutton?

![Schermata del 2023-10-17 21-09-42](https://github.com/wwmm/easyeffects/assets/25790525/cd09b509-98ad-41dc-9dbd-3dc2a6a4f87d)

**Comment by wwmm** [comment]
>Is there a specific reason to use a scale while other dB units use a spinbutton?

This controls has a big effect in the quality of the filtering. Sliding it until finding the good point bear ear is a lot more faster than using an spinbutton.

Initially I wanted to put it above this block with its width forced to be equal to adwpreferences section. But it was not easy to achieve it. So I just left it inside the row.

**Comment by Digitalone1** [comment]
Okay.
