### ISSUE TITLE
VERY persistent no Background permissions error

### ISSUE THREAD

**Issue by ameameam3** [wwmm/easyeffects#2669]
### EasyEffects Version

7.1.0

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Linux

### Describe the bug

Background permissions completely refuse to work after several reboots, cycled through *every* solution, tried reinstalling every component....

xdg-desktop-portal-gnome, gtk...

flatseal has all permissions for portals greyed out.

### Expected Behavior

background permissions are asked for? or something.

### Additional Information

```
(easyeffects:2): easyeffects-WARNING **: 01:55:46.140: 	libportal.cpp:70	Background access has been denied

(easyeffects:2): easyeffects-WARNING **: 01:55:46.140: 	libportal.cpp:71	Please allow Easy Effects to ask again with flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 01:55:46.155: 	libportal.cpp:84	due to error, setting autostart state and switch to false
```
this is the only error that's thrown in the terminal

**Comment by ameameam3** [comment]
no idea, but easyeffects (arch) started working properly after i reinstalled it. flatpak didn't want to work no matter what i did

**Comment by wwmm** [comment]
>flatpak didn't want to work no matter what i did

Based on your error messages the most likely explanation is not having the right `xdg portal` package installed. But as you are on Arch Linux it is easier to just use the native package instead.
