### ISSUE TITLE
no window opens

### ISSUE THREAD

**Issue by addeps3** [wwmm/easyeffects#2714]
### EasyEffects Version

7.1.0-1

### What package are you using?

Arch (easyeffects)

### Distribution

manjaro

### Describe the bug

no window opens. 

### Expected Behavior

opposite from above.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
export G_MESSAGES_DEBUG
[$ easyeffects 
(process:119056): easyeffects-DEBUG: 13:51:51.457: 	easyeffects.cpp:35	easyeffects version: 7.1.0
(process:119056): easyeffects-DEBUG: 13:51:51.462: 	easyeffects.cpp:45	locale directory: /usr/share/locale
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.468: 	presets_manager.cpp:162user presets directory already exists: /home/ma/.config/easyeffects/
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.468: 	presets_manager.cpp:162user presets directory already exists: /home/ma/.config/easyeffects/input
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.468: 	presets_manager.cpp:162user presets directory already exists: /home/ma/.config/easyeffects/output
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.468: 	presets_manager.cpp:162user presets directory already exists: /home/ma/.config/easyeffects/autoload/input
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.468: 	presets_manager.cpp:162user presets directory already exists: /home/ma/.config/easyeffects/autoload/output
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.974: 	pipe_manager.cpp:1429	compiled with PipeWire: 0.3.79
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.974: 	pipe_manager.cpp:1430	linked to PipeWire: 0.3.81
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.998: 	pipe_manager.cpp:1400	core version: 0.3.81
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.998: 	pipe_manager.cpp:1401	core name: pipewire-0
(easyeffects:119056): easyeffects-DEBUG: 13:51:51.998: 	pipe_manager.cpp:1312	found metadata: settings

```
</details>

### Additional Information

xfce. Sorry for low-wordage, have sleep deprivation and have school assignments due tomorrow... fml

**Comment by violetmage** [comment]
Did easyeffects work before?

If so, what changed between then and now?

**Comment by addeps3** [comment]
> Did easyeffects work before?
> 
> If so, what changed between then and now?

No, unfortunately, never worked =/

**Comment by wwmm** [comment]
>pipe_manager.cpp:1312	found metadata: settings

There should be a `default`  metadata too. When there isn't one the reason is not having `pipewire-pulse` installed. EasyEffects does not need the Pulseaudio compatibility layer but distributions package PipeWire in a way that the part of its code that provides the metadata is put inside the pipewire-pulse package.

**Comment by wwmm** [comment]
Have in mind that installing pipewire-pulse means having to uninstall Pulseaudio. This is normal.

**Comment by addeps3** [comment]
> Have in mind that installing pipewire-pulse means having to uninstall Pulseaudio. This is normal.

right. Forgot about pipe-pulse, was a while ago i dealth with fka pulseffects :) 

thanks!
