### ISSUE TITLE
Easyeffects crashes while using scrcpy

### ISSUE THREAD

**Issue by tekuseacc** [wwmm/easyeffects#2715]
### EasyEffects Version

7.1.0

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro

### Describe the bug

easyeffects is working properly but when scrcpy [https://github.com/Genymobile/scrcpy](url) is opened to work simultaneously with an android phone it closes and then even after opening easyeffects manually after closing scrcpy it works only on foreground and the effects get disabled if easyeffects is closed. 

to reproduce install scrcpy and attach an android phone using a usb cable on the same device in which easyeffects is working.

### Expected Behavior

Easyeffects should work properly even while using scrcpy https://github.com/Genymobile/scrcpy), or someway to disable the easy effects on it to prevent crashing.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>to reproduce install scrcpy and attach an android phone using a usb cable on the same device in which easyeffects is working.

I did that and there was no crash. You will have to take some logs on your computer so we can at least see at which point the crash is happening. Take a look at the third step describe at this page https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs.
