### ISSUE TITLE
Easy Effects Disabling All Sound

### ISSUE THREAD

**Issue by BungoJiggins** [wwmm/easyeffects#2737]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04.3 LTS

### Describe the bug

First, some context. One: I'm incredibly new to Linux, so I'll inevitably fumble on some details. Two: I've used Easy Effects for about a month before this without much issue. For unrelated reasons, I had to force a shutdown via my power button, and after rebooting, my sound was totally broken. 

In particular, it seems like pipewire with no installation of Easy Effects has sound, but once I install Easy Effects, my sound only works when I open the application and disable it from acting on whatever audio source I'm trying to hear. The sound is about the same when I do this, so evidently no effects work this way. The client also has the audio bars functioning while enabled (i.e., while I can't hear anything). The enable/disable checkbox is essentially a mute/unmute button, at the moment. 

I've tried changing my default audio sink with pactl, as well as several reinstallations of all the working parts. I can't get pw-dot to yield any kind of picture (I can open other people's dot files, but mine are blank; I think it's failing to generate anything). I'm not really sure how to spot any muting in pavucontrol. I ran Easy Effects in debug mode and attached the log. Additionally, I have tried both no effects and my old configuration—there was no difference. 

### Expected Behavior

The Easy Effects client should carry over sound seamlessly and apply any desired effects. 

### Debug Log

Attached the debug log as a txt.
[EE debug.txt](https://github.com/wwmm/easyeffects/files/13316103/EE.debug.txt)

**Comment by unigazer** [comment]
@BungoJiggins I had the exact same issue on Ubuntu 20.04. You need to update the PipeWire package. Thanks @fshubthunfischbaum for the issue reference.

**Comment by BungoJiggins** [comment]
Updating PipeWire fixed it. Thanks, everyone!
