### ISSUE TITLE
Add "quit" to main menu

### ISSUE THREAD

**Issue by jtl5770** [wwmm/easyeffects#2738]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 39

### Describe the bug

With Fedora 39, the taskbar button for running applications is gone. So there is no way anymore to easily quit easyeffects (if you have set it to be started automatically and not quit when closed).

### Expected Behavior

Usually, an app can be can be expected to have a dedicated "quit" menu entry in the hamburger menu. My proposal is to add just that.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by violetmage** [comment]
Please see #2739

**Comment by wwmm** [comment]
Implemented in our master branch.
