### ISSUE TITLE
Audio Output stops after running EasyEffects

### ISSUE THREAD

**Issue by golobolus** [wwmm/easyeffects#2741]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (easyeffects)

### Distribution

Ubuntu 22.04

### Describe the bug

Audio output suddenly stops upon opening EasyEffects. When application is disabled from the EasyEffects UI the audio output comes back.

UI is seen oscillating but no audio output.
[Screen Record](https://github.com/wwmm/easyeffects/assets/3991718/da320cbd-abb1-45b3-aa00-854acdac87e8)

### Expected Behavior

When opening EasyEffects the audio output should just inherit the presets created and set, not mute the audio output.

### Debug Log

<summary>Debug Log</summary><br />

[pw-dump.txt](https://github.com/wwmm/easyeffects/files/13323647/pw-dump.txt)
[easyeffects.log](https://github.com/wwmm/easyeffects/files/13323648/easyeffects.log)

**Comment by wwmm** [comment]
This is a PipeWire bug I have already reported to them https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3547. Unfortunately no solution so far. As we already have open issues here related to this problem we can close this one.

**Comment by wwmm** [comment]
>Ubuntu 22.04

That being said Ubuntu users usually need to use third party repositories to update PipeWire to a more recent release. This won't fix the particular bug I have reported to PipeWire developers. But may help in other cases like #2732 and #2737.
