### ISSUE TITLE
No sound with latest Flaptak update 7.1.3

### ISSUE THREAD

**Issue by mirocw** [wwmm/easyeffects#2744]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint 21.2

### Describe the bug

I was using easy effect for a dynamic range compression with https://github.com/Digitalone1/EasyEffects-Presets preset.
Everything worked perfectly fine until the latest update few days ago. Now there's no sound. When i turn off easy effect, sound is back.

### Expected Behavior

should be sound

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Take a look at #2732 and #2737. It seems the users of Debian based distributions need to upgrade the PipeWire  package.

**Comment by mirocw** [comment]
yep, working now. thanks.
