### ISSUE TITLE
Enabling effects mutes all audio

### ISSUE THREAD

**Issue by clalcofe** [wwmm/easyeffects#2749]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

SteamOS

### Describe the bug

I've been using Easy Effects on SteamOS to equalize my headphones for a couple of months now. The application worked flawlessly until recently. Right now, whenever I enable effects, no sound comes out of the headphones, and it doesn't matter whether I enable the effects system-wide or just for a specific application. I suspect a system or app update might have broken compatibility somehow. The correct input/output devices have been selected under the Device Management section of the app. In the OS System Settings, under Audio, I've tried selecting both my DAC/Amp and Easy Effects Sink as the default playback devices. If I select the DAC/Amp as the default playback device, I get sound if I disable the effects from Easy Effects but not otherwise. If I select Easy Effects Sink as the playback device, I get no sound no matter what.

Any help would be greatly appreciated.

**Comment by wwmm** [comment]
Probably the same as #2732, #2737 and #2744. Try to see if a more recent PipeWire release is available in a third party repository. Debian based distributions seem to lag a lot behind in PipeWire upgrades.

**Comment by clalcofe** [comment]
Thank you for the speedy answer! I'm not very familiar with Linux yet, so I'm not sure how I'd go about updating PipeWire and I'm afraid I'd break something. However, I figured out how to downgrade Easy Effects to an older version. Version 7.0.7 is working just fine!

**Comment by wwmm** [comment]
>Thank you for the speedy answer! I'm not very familiar with Linux yet, so I'm not sure how I'd go about updating PipeWire and I'm afraid I'd break something. However, I figured out how to downgrade Easy Effects to an older version. Version 7.0.7 is working just fine!

Ok. In this case downgrading EasyEffects is probably the easiest solution until SteamOS updgrades its PipeWire package.
