### ISSUE TITLE
Audio won't output

### ISSUE THREAD

**Issue by 18aKissD** [wwmm/easyeffects#2751]
Ubuntu 22.04

I can see the virtualization, and apps but as soon as I turn enable on, it will mute anything, so it is not functioning properly.

No, the sink is not muted, it outputs audio. I've seen some of us had the same or nearly the same issue and you suggested to check if the audio is muted through the sink.

In my case, it's not. It seems like it has the input, it just can't output it to my devices. Tried all kind of device eg. Built-in speaker, jack, Dac. 

Please ask for any more info, thanks

**Comment by violetmage** [comment]
I'm assuming you're using the flatpak?

What do your system audio settings (pavucontrol) look like?

Is easyeffects set to use the default device and/or process all outputs?

What effects are you using?

Additionally, you might try looking at helvum while using easyeffects, to see if the problem  is something simple.

**Comment by wwmm** [comment]
>Oh I see. It is working. Yesterday I even wiped my Linux for this. Somehow if I googled these solutions didn't come up, so sorry for opening the issue.

No problems :-)
