### ISSUE TITLE
Easy Effects not working after some system edits.

### ISSUE THREAD

**Issue by Y2K350** [wwmm/easyeffects#2757]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Debian 12

### Describe the bug

Hello everyone,

I started using easy effects on a base install of Debian 12 running with pipewire and had no issues. After some changes to my audio configuration and experimenting with pulse audio, it no longer works. I've since uninstalled Pulseaudio and when entering pipewire --version I receive pipewire Compiled with libpipewire 0.3.65 Linked with libpipewire 0.3.65. I have tried using the Easy Effects sync as well as just the normal device in Gnome and other applications settings, but no matter what I do, I have to enable the global bypass in easy effects to get any audio.

Forgive me as I'm still learning about linux as I go along, but could anyone suggest any mistakes I possibly made?

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Take a look at #2732, #2737 and #2744. An upgrade to the PipeWire package may solve the problem.
