### ISSUE TITLE
PulseEffects EQ UI (I'm still using pulseaudio) nearly unusable on slower device because sliders need 10+ seconds to show the value entered

### ISSUE THREAD

**Issue by ell1e** [wwmm/easyeffects#2761]
### EasyEffects Version

the one latest on com.github.wwmm.pulseeffects for ARM64 architectures

### What package are you using?

Flatpak (Flathub)

### Distribution

postmarketOS 23.06

### Describe the bug

PulseEffects EQ's UI (I'm still using pulseaudio) seems to be nearly unusable on slower device because sliders need 10+ seconds to show the value entered. This way it's completely impossible, especially when using touch, to enter any targeted value, given the sliders are also relatively small vertically. It seems like the UI only updates when the audio also kicks in which seems nice but completely unnecessary, it's way more important IMHO to see the value I entered than to keep the audio strictly in sync like that.

### Expected Behavior

Equalizer sliders react immediately and show entered value, like scrolling around also immediately reacts. This is not what happens, after a tap they remain completely frozen for multiple seconds and entering any remotely intended value like that just doesn't really [work.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by violetmage** [comment]
The legacy pulseaudio branch is not really maintained anymore, so unless there is a simple way to fix this issue, the only real options are finding a way to get pipewire as your audio server, or finding a different DSP/effects app that will work with pulseaudio on your system.

**Comment by ell1e** [comment]
Is there any different app?

It's not possible to just switch audio servers on a linux phone, because call audio is really complicated and specific to set up so I'm just bound to whatever my distro serves me. I believe they plan to switch to pipewire at some point, but it hasn't happened yet.

**Comment by violetmage** [comment]
What UI (do you still call it a DE if it's on a phone?) are you using?

I don't have any experience in this area, but it looks like all the major ones have pipewire support in some capacity.

**Comment by ell1e** [comment]
It's not really dependent on the desktop shell I think, more on how the daemons handling the call audio are configured. I'm using Phosh/Phoc so it's basically a GNOME desktop just with a more lightweight alternative to the usual gnome-shell.

**Comment by violetmage** [comment]
More googling makes me think that audio on the PinePhone is a rabbit hole. Theres always [jamesdsp](https://github.com/Audio4Linux/JDSP4Linux) if you are doing mostly corrective stuff to your audio (eq, impulse response, etc.) and don't need effects like pitch shift or auto-gain.

**Comment by ell1e** [comment]
Does PulseEffects have some way to set the sliders via command line? The functionality otherwise seems to be flawless, it's just entering the desired curve that's affected.

**Comment by violetmage** [comment]
Thinking back to when I used pulseaudio, I'm remembering that `exit-idle-time`, a configuration variable in pulseaudio's `daemon.conf`, would often be the cause of jank in many applications that tried to do anything more complicated than play back an sudio file.

IIRC, I just ended up commenting out that line in `daemon.conf` on all of my systems that I needed the audio to not be janky on, which meant that pulseaudio just never went to sleep.

You might try that (or at least set it to a big ish number, like 60) on your phone, and see if pulseeffects behaves any different/better.

**Comment by violetmage** [comment]
If you don't need to edit your equalizer often, then you should be able to leave `daemon.conf` alone, and just make your desired change in dconf-editor

**Comment by ell1e** [comment]
That sounds super useful, thanks!

Should I close this issue then? I mean it's still kinda behaving the way I described, and I doubt it's PinePhone-related, it just seems to be that the device is just very slow cpu-wise. (I kind of doubt it's exit time related too since this was while a song was playing, surely pulseaudio wouldn't exit during playback?)

**Comment by violetmage** [comment]
Yeah, you can close this as completed if you want, as we probably won't make any changes in the legacy branch, and dconf-editor isn't that bad of a workaround.

**Comment by ell1e** [comment]
Okay, that's fair! Closing it then. Thanks for all the help

**Comment by wwmm** [comment]
>Does PulseEffects have some way to set the sliders via command line?

Yes. Take a look at the example scripts shown at https://github.com/wwmm/easyeffects/discussions/916

>it just seems to be that the device is just very slow cpu-wise

Or maybe its disk writing times are large? For reason I do not remember the flatpak package has to use an `ini file` based backend for the gsettings database instead of the high performance binary file based it is usually used in native packages. Even on good desktops that ini file backend is ridiculously slow.
