### ISSUE TITLE
Use stereo versions of LSP plugins when "split channels" is not active

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [wwmm/easyeffects#2762]
New native window feature is really useful, but since leftright plugin is always used in equalizer, it's pretty hard to use new exposed features if you don't need to tune channels separately. (Inspect function for example). 

I haven't found an option to sync actions for both channels in leftright version, so if this is at all feasible, this enhancement would be really useful.

**Comment by wwmm** [comment]
Switching between variants on the fly is not viable because there is a lot about the settings that is hardcoded. Specially the ports names. And these plugins have really a lot of them. And on top of that the gsettings database we use works with xml files that are written by hand for a given plugin.

>I haven't found an option to sync actions for both channels in

When `split-channels` is disabled EasyEffects forces the settings of the left channel to be sent to the right channel. Unless some bug is happening they should already be in sync in our custom window and in the plugin instance. But not in the native window. You have to close and reopen it for its widgets to be updated.

**Comment by wwmm** [comment]
I think that the only solution would be to wrap one of the stereo plugins in a new independent plugin. But it is a lot of work and functionality duplication just for the sake of making it easier to use the native plugin window.

**Comment by Digitalone1** [comment]
If I remember correctly, the only plugin using `leftright` version is the Equalizer. Reading the title of this issue, it seems there are more. Am I missing something?

**Comment by wwmm** [comment]
>If I remember correctly, the only plugin using leftright version is the Equalizer. Reading the title of this issue, it seems there are more. Am I missing something?

It is the only one. What I understood from the title is that the idea would be to switch from left-right to a standard stereo plugin when split-channels is disabled. I can see why someone would want that when using the native window but the amount of work required to put something like this in place is really big. And it would only really be useful when using the native window.

**Comment by AbsurdlySuspicious** [comment]
> the only plugin using leftright version is the Equalizer.

That's right. I've seen suggestions to use LR versions in other effects as well, so I kind of generalized issue title. 

> When split-channels is disabled EasyEffects forces the settings of the left channel to be sent to the right channel.

Sync on the easyeffects side works just as you described, this request was only related to "realtime" usage of functions that are exposed in the plugin UI but not in the easyeffects UI.

Well I kinda expected that implementing this would be pretty much infeasible. I'll keep this issue open in case you want to keep it as a low-prio request, but otherwise feel free to close it

**Comment by wwmm** [comment]
>Well I kinda expected that implementing this would be pretty much infeasible. I'll keep this issue open in case you want to keep it as a low-prio request, but otherwise feel free to close it

I think we can close it because switching between LSP libraries on the fly requires a lot of work throughout the whole code and is probably not going to happen.

**Comment by AbsurdlySuspicious** [comment]
For anyone encountering the same issue:

> I haven't found an option to sync actions for both channels in leftright version

`L/R link` option has been implemented in LSP equalizer (probably other LSP plugins too). You can find the toggle for it at the bottom left of spectrum graph widget
