### ISSUE TITLE
Immediate mute when effect is applied

### ISSUE THREAD

**Issue by M15071060** [wwmm/easyeffects#2763]
### EasyEffects Version

7.1.3

### What package are you using?

Other (specify below)

### Distribution

Debian 12

### Describe the bug

EasyEffects captures my audio without issue, however as soon as I apply any effect, on any source, the output is immediately muted.

I am not sure if it's related or if I'm missing something, but my USB mic is not listed under inputs, and so I'm unable to test if the same issue persists there.

![image](https://github.com/wwmm/easyeffects/assets/12193730/65105d4c-e819-4fe7-a958-1e16d2b14161)
![image](https://github.com/wwmm/easyeffects/assets/12193730/1a7adbd0-dced-45e5-adcf-12989a93bdbb)

I have checked in PulseAudio volume control, and it doesn't **appear** that anything is being muted, which I've seen as a potential issue before.

![image](https://github.com/wwmm/easyeffects/assets/12193730/ae680c36-dc77-45aa-be0f-1ca4dd1a9805)

### Expected Behavior

Effects should apply to audio sources and mic should show as input.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Forgive me if I'm just missing something, but I was unable to find an answer elsewhere.

Thank you.

**Comment by wwmm** [comment]
Probably the same as #2732, #2737 and #2744. For some unknown reason users of Debian based distributions need to upgrade their PipeWire package to use the latest EasyEffects release. It was not intentional. But using the latest PipeWire release is a good idea anyone because it was considerably improved compared to the standard package available in Debian/Ubuntu.

**Comment by violetmage** [comment]
Is there a reason why you aren't using the native easyeffects package that ships in debian now?

**Comment by M15071060** [comment]
> Is there a reason why you aren't using the native easyeffects package that ships in debian now?
> 
> Edit: it looks like debian's easyeffects package is on version 7.0.0, so not exactly recent, but still usable.

Thanks for pointing this out, I had just defaulted to Flatpak as it was the more up-to-date, but it does work without issue.

> Probably the same as #2732, #2737 and #2744. For some unknown reason users of Debian based distributions need to upgrade their PipeWire package to use the latest EasyEffects release. It was not intentional. But using the latest PipeWire release is a good idea anyway because it was considerably improved compared to the standard package available in Debian/Ubuntu.

Thanks for the response, I'll look into doing this!
