### ISSUE TITLE
Output cuts out when applying filters

### ISSUE THREAD

**Issue by robertosw** [wwmm/easyeffects#2773]
### EasyEffects Version

7.1.3

### What package are you using?

NixOS

### Distribution

NixOS 23.05

### Describe the bug

As soon as at least one audio filter is applied to the output stream, audio output cuts out. Shown in this video (just a screen recording, but audio is visible using the bars in easyeffects)
[EasyEffects Filter Bug.webm](https://github.com/wwmm/easyeffects/assets/47303535/e6f08979-b5fb-46b3-bea3-1f5eed5270bf)

- After global pass through is enabled, the sound comes back, but the filter is not used.
- Deactivating the filter does not help. The output is still missing
- The audio comes back immediately as soon as the filter is deleted

### Debug Log

No relevant messages where shown. Only some CSS errors, but they were there from the start of the program

### Additional Information

My Nix config regarding audio:
```
	sound.enable = true;                       # use Alsa
	hardware.pulseaudio.enable = false;

	services.pipewire = {
		enable = true;			# enable pipewire service
		audio.enable = true;		# use PipeWire as the primary sound Server
		alsa.enable = true;		# Whether to enable ALSA support.
		alsa.support32Bit = true;
		pulse.enable = true;		# Whether to enable PulseAudio server emulation
		wireplumber.enable = true;	# modular session / policy manager for PipeWire

		jack.enable = false;		# Whether to enable JACK audio emulation.
	};	

	security.rtkit.enable = true;
	users.users.<my username>.extraGroups = [ "audio" ];
```

**Comment by wwmm** [comment]
Which PipeWire versions are you using? Some Ubuntu/Debian users had a similar problem and upgrade to a newer PipeWire fixed it. For some reason I am not aware of the last EasyEffects release is not playing nice with "too old" Pipewire versions.

**Comment by violetmage** [comment]
@wwmm At this point, I think that it will be worth trying to build the flatpak using the gnome 44 runtime, just to see if it helps, as this issue is affecting too many users to be something we can ignore.

**Comment by wwmm** [comment]
>At this point, I think that it will be worth trying to build the flatpak using the gnome 44 runtime, just to see if it helps, as this issue is affecting too many users to be something we can ignore.

I do not know if this is viable or the better thing to do. I do not remember if the runtime was upgraded just for the sake of being upgraded or if this was needed for some reasons.

What I do not understand is that there was no major change to our interaction with PipeWire for a while. The only change I remember related to links was done quite some time ago https://github.com/wwmm/easyeffects/commit/24e70897d2f99d348f0cac8813e44c86dd61310b. And it was recommended by PipeWire devs. If this is the reasons the only proper solution is upgrading PipeWire.

**Comment by violetmage** [comment]
It can't hurt to try, at least for the development flatpak, right?

**Comment by robertosw** [comment]
I ended up uninstalling EasyEffects alltogether, because I also faced another problem. Even without having any filters added (unimportant if activated or not), I had to uncheck the 'activate' checkbox for every new application that outputs sound. Once I unchecked this, audio for this application is no longer muted, because Easyeffects remembered my setting.

Would I be of any help if I reinstall easyeffects and see if I can get the latest versions of alsa, pipewire and pulseaudio installed and report my findings here?

**Comment by wwmm** [comment]
>Would I be of any help if I reinstall easyeffects and see if I can get the latest versions of alsa, pipewire and pulseaudio installed and report my findings here?

I do not think it is necessary. It is probably the same issue that is affecting all the other Ubuntu/Debian users and that is solved by a PipeWire upgrade.
