### ISSUE TITLE
Adding an effect mutes the audio. Also player and output is greyed out.

### ISSUE THREAD

**Issue by ZeroCommits** [wwmm/easyeffects#2785]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Debian 12

### Describe the bug

Adding an effect mutes the audio. Also player and output is greyed out. Any effect/s added mutes the audio.

![image](https://github.com/wwmm/easyeffects/assets/37379471/904577ae-64e4-489a-9117-9ce31532d0e5)

### Expected Behavior

This is the first time I'm using EasyEffects. I am expecting the effect/s to be applied immediately.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:2): easyeffects-DEBUG: 00:00:45.866: 	easyeffects.cpp:35	easyeffects version: 7.1.3
(process:2): easyeffects-DEBUG: 00:00:45.866: 	easyeffects.cpp:45	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 00:00:45.874: 	presets_manager.cpp:162	user presets directory already exists: /home/$USER/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 00:00:45.874: 	presets_manager.cpp:162	user presets directory already exists: /home/$USER/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 00:00:45.874: 	presets_manager.cpp:162	user presets directory already exists: /home/$USER/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 00:00:45.874: 	presets_manager.cpp:162	user presets directory already exists: /home/$USER/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 00:00:45.874: 	presets_manager.cpp:162	user presets directory already exists: /home/$USER/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 00:00:45.878: 	easyeffects.cpp:60	Exitting the main function with status: 1

```

</details>

**Comment by wwmm** [comment]
Probably the same as #2732, #2737 and #2744. For some unknown reason users of Debian based distributions need to upgrade their PipeWire package to use the latest EasyEffects release. One solution is upgrading your PipeWire package. The other would be to to build a Flatpak package based on https://github.com/wwmm/easyeffects/pull/2779. Would this be a simple thing to do @vchernin ?

**Comment by violetmage** [comment]
Speaking of which, what is the plan / criteria for 7.1.4?

Making a new release would mean also updating the stable flatpak for everyone, hopefully putting a stop to these pipewire version conflict issues.

**Comment by wwmm** [comment]
>Speaking of which, what is the plan / criteria for 7.1.4?

Under ordinary circumstances there would not be a reason to do a release now. But considering the flood of Debian/Ubuntu users reports it is probably better to do one tomorrow.
