### ISSUE TITLE
Refactor code sections that use util::idle_add

### ISSUE THREAD

**Issue by violetmage** [wwmm/easyeffects#2795]
This is a comprehensive list of all the files that might contain race conditions by way of using util::idle_add without enough safeguards. If you are refactoring or want to help refactor any util::idle_add sections, check here first to see what needs to be done.

- [x] autogain_ui.cpp
- [x] bass_enhancer_ui.cpp
- [x] bass_loudness_ui.cpp
- [x] compressor_ui.cpp
- [x] convolver_menu_combine.cpp
- [x] convolver_ui.cpp #2765 
- [x] crossfeed_ui.cpp
- [x] crystalizer_ui.cpp
- [x] deepfilternet_ui.cpp
- [x] deesser_ui.cpp
- [x] delay_ui.cpp
- [x] echo_canceller_ui.cpp
- [x] effects_box.cpp
- [x] equalizer_ui.cpp
- [x] exciter_ui.cpp
- [x] expander_ui.cpp
- [x] filter_ui.cpp
- [x] gate_ui.cpp
- [x] level_meter_ui.cpp
- [x] limiter_ui.cpp
- [x] loudness_ui.cpp
- [x] maximizer_ui.cpp
- [x] multiband_compressor_ui.cpp
- [x] multiband_gate_ui.cpp
- [x] pitch_ui.cpp
- [x] reverb_ui.cpp
- [x] rnnoise_ui.cpp
- [x] speex_ui.cpp
- [x] stereo_tools_ui.cpp

**Comment by violetmage** [comment]
@wwmm do I have to do anything to make sure that you can edit the task list?

**Comment by wwmm** [comment]
>do I have to do anything to make sure that you can edit the task list?

No. I already have write access.

**Comment by wwmm** [comment]
The work on this has finally finished and is in `7.1.4` code.
