### ISSUE TITLE
HoloCure (game) audio output is ignored by EasyEffects unless manually routed through "Easy Effects Sink"

### ISSUE THREAD

**Issue by AlexFolland** [wwmm/easyeffects#2800]
### EasyEffects Version

7.1.3

### What package are you using?

Manjaro (easyeffects) from unstable repo; effectively a copy of Arch (easyeffects)

### Distribution

Manjaro (using unstable repos)

### Describe the bug

HoloCure's game audio is ignored by EasyEffects unless manually routed through the sink named "Easy Effects Sink", which can be done in the "Playback" tab of PulseEffects Volume Control.  Only after doing so is HoloCure's audio affected by EasyEffects' output effects.

### Expected Behavior

All programs with audio output are expected to be routed through EasyEffects by default, unless I have explicitly ignored them in the EasyEffects menu.

### Additional Information

I noticed that HoloCure's output has no name.  Its name seems to be an empty string.  Maybe that's contributing to this issue.

Also, I noticed that when starting HoloCure, I saw an entry appear in EasyEffects for a moment, then disappear.

I am using HoloCure from Steam.  It costs no money to add to a Steam account.

I am not using Flatpak for Steam or EasyEffects.  They are both installed natively using the Manjaro unstable repos.

**Comment by wwmm** [comment]
>I noticed that HoloCure's output has no name. Its name seems to be an empty string. Maybe that's contributing to this issue.

It makes sense. The next time you run this game execute in a terminal `pw-cli list-objects Node`. After figuring out its `id number` execute `pw-cli info id_number` so we can see which properties are there.

**Comment by AlexFolland** [comment]
I used `pw-cli list-objects Node` to try to find it.  It was not easy to find, but I think I found its ID.  Then I tried `pw-cli info 246` to show more info about it.  I couldn't find a nice GUI for showing info about this thing beside a volume display so that I can see which node is producing what output.

```
[alex@alex-pc ~]$ pw-cli info 246
	id: 246
	permissions: rwxm-
	type: PipeWire:Interface:Node/3
*	input ports: 0/0
*	output ports: 2/65
*	state: "running"
*	properties:
*		client.api = "pipewire-pulse"
*		pulse.server.type = "unix"
*		application.name = ""
*		application.process.id = "346678"
*		application.process.user = "alex"
*		application.process.host = "alex-pc"
*		application.process.binary = "wine64-preloader"
*		application.language = "en_US.UTF-8"
*		window.x11.display = ":0.0"
*		application.process.machine-id = "dd40a436ff9b430fb95648a0d737003e"
*		application.process.session-id = "2"
*		media.name = "audio stream #1"
*		node.rate = "1/48000"
*		node.latency = "240/48000"
*		stream.is-live = "true"
*		node.name = ""
*		node.want-driver = "true"
*		node.autoconnect = "true"
*		media.class = "Stream/Output/Audio"
*		adapt.follower.spa-node = ""
*		object.register = "false"
*		factory.id = "6"
*		clock.quantum-limit = "8192"
*		factory.mode = "split"
*		audio.adapt.follower = ""
*		library.name = "audioconvert/libspa-audioconvert"
*		client.id = "243"
*		object.id = "246"
*		object.serial = "1517"
*		pulse.attr.maxlength = "11520"
*		pulse.attr.tlength = "9600"
*		pulse.attr.prebuf = "8"
*		pulse.attr.minreq = "3840"
*	params: (9)
*	  3 (Spa:Enum:ParamId:EnumFormat) r-
*	  1 (Spa:Enum:ParamId:PropInfo) r-
*	  2 (Spa:Enum:ParamId:Props) rw
*	  4 (Spa:Enum:ParamId:Format) rw
*	  10 (Spa:Enum:ParamId:EnumPortConfig) r-
*	  11 (Spa:Enum:ParamId:PortConfig) rw
*	  15 (Spa:Enum:ParamId:Latency) rw
*	  16 (Spa:Enum:ParamId:ProcessLatency) rw
*	  17 (Spa:Enum:ParamId:Tag) -w
```

**Comment by wwmm** [comment]
>node.name = ""

This is the reason why. It does not set a `node.name`.  What is really unusual. All apps I am aware of have this string set to something...

In any case the real question now is if it is fine for us to let the stream go ahead with an empty node name.

**Comment by wwmm** [comment]
@AlexFolland When possible install the AUR package. I've changed the code a little. Instead of ignoring streams with empty node names we now set the tag to "Undefined Name". This way there is no risk of an empty string making the code crashing somewhere.

**Comment by AlexFolland** [comment]
Why wouldn't it be?  What matters is the object and the audio.  What the node is called is irrelevant.

I am lucky PulseAudio Volume Control does not have this issue, and simply displays the playback source.

Really, the name should be taken from the window title of the process ID, application.process.id.  The HoloCure window has a proper title, and that would make the user immediately aware of what the source is, as it would be linked together in an obvious way.

Thank you for your response!

**Comment by AlexFolland** [comment]
> @AlexFolland When possible install the AUR package. I've changed the code a little. Instead of ignoring streams with empty node names we now set the tag to "Undefined Name". This way there is no risk of an empty string making the code crashing somewhere.

I suggest switching to using the window title for all sources that have windows.  This "node name" is not visible to the user on the desktop, so has no intuitive linking in the user's mind if the window title is very different.

I'll install the latest from the AUR and see if the core issue is solved a bit later today.  Thank you for your work on this!

**Comment by wwmm** [comment]
>Why wouldn't it be? What matters is the object and the audio. What the node is called is irrelevant.

Because the same is used in some places like when processing the blocklist entries. And probably others I do not remember now. It is not necessarily something that is only being shown to the user. And in the case of devices for example you necessarily have to use their node names in some situations because the server can reuse id numbers. 

And on top of that is the fact EasyEffects was written taken PulseEffects workflow as basis. So  there are some things that were done using the same kind of information that were available in Pulseaudio. In short not many.

>I am lucky PulseAudio Volume Control does not have this issue, and simply displays the playback source.

Pavucontrol does not have to do most of the things EE has to do. So it can just show whatever it wants in its window and move on even if they are not properly defined.

>Really, the name should be taken from the window title of the process ID, application.process.id. 

Hmm? That is a number and not a name or title. Maybe you were thinking about `application.name`; But this is also empty in this game stream.

In any case this goes back to what I said above. Streams and devices are both "nodes". And sometimes you have to uniquely identify a node and believe it or not the name can be the only reliable thing in some cases. It is what it is....

>I suggest switching to using the window title for all sources that have windows. This "node name" is not visible to the user on the desktop, so has no intuitive linking in the user's mind if the window title is very different.

And again I do not understand.  There is no window title in your `pw-cli info` output. The information EasyEffects can use is the one PipeWire gives to it. In other words the ones in that pw-cli info output. And some of the information there is only available if the the audio client provided it to the audio server. The problem is that the clients are not forced to do it. Some do but most do not.

**Comment by wwmm** [comment]
Unless you have in mind using the process id to get the window title using some system calls without using PipeWire's calls. But I think that the most we could have through this approach is the executable name. And that is what PipeWire usually puts inside `application.name`. So we may have another empty string in the end.

But even if this somehow works and we are able to get the window title instead of just the executable name there are plenty of audio streams that do not have window titles. It seems a really complicated approach just to cover some edge cases.

**Comment by violetmage** [comment]
Just wanting to clarify, that makes this a bug in HoloCure, correct?

I'm not very familiar with the finer details of WINE/proton, but is there any chance that they might have something to do with this?

**Comment by wwmm** [comment]
>I'm not very familiar with the finer details of WINE/proton, but is there any chance that they might have something to do with this?

Probably. I've just noticed the same behavior on `Baldur's Gate 3`. The media name is set to `media.name = "audio stream #1"` and there is no node or application name set. As expected Pavucontrol shows the same thing.

I do not remember this being the case in the past. Something may have changed in wine/Proton. But as I said before the problem is that Pulseaudio/PipeWire do not require these tags to be set. It is optional to provide them or not =/.

**Comment by AlexFolland** [comment]
> Unless you have in mind using the process id to get the window title using some system calls without using PipeWire's calls. But I think that the most we could have through this approach is the executable name. And that is what PipeWire usually puts inside `application.name`. So we may have another empty string in the end.

Yes, that is what I was thinking.  Using the executable name, or even `application.process.binary` which is actually available in this case, makes a lot of sense to me as a fallback in cases where this particular `node.name` field is an empty string.  If I saw `wine64-preloader`, I would know what that is in the EasyEffects list.  That being said, the problem is really the audio source being ignored by EasyEffects.  I will try the git build from the AUR now and comment again soon.

`Just wanting to clarify, that makes this a bug in HoloCure, correct?`

It would have to be a bug in wine (in this case, the fork, Proton), if Proton is indeed the one which set an empty `node.name`.  A program written for Windows doesn't have any business setting a PipeWire or PulseAudio field directly, as far as I understand it.

`But as I said before the problem is that Pulseaudio/PipeWire do not require these tags to be set. It is optional to provide them or not =/.`

Does this need to be raised with the PipeWire authors?  It seems important for an audio source that is actually creating audio output to be identifiable.

**Comment by wwmm** [comment]
>Does this need to be raised with the PipeWire authors?

Maybe. But as they have to maintain compatibility with Pulseaudio and Pulseaudio never required the tags to be set I am not sure if they can do much about it.

>It seems important for an audio source that is actually creating audio output to be identifiable.

I agree it is. But even OBS did not went out of its way to set unique id numbers for each of its streams for example. 

>Using the executable name, or even application.process.binary which is actually available in this case, makes a lot of sense to me as a fallback in cases where this particular node.name field is an empty string

We will probably have use `application.process.binary` as fallback. We already have some fallback in places. Add one more is not a big deal.

**Comment by AlexFolland** [comment]
Yes, it shows up now with "Undefined Name"!  This issue is resolved, so I am closing this ticket.  I agree that a further improvement as you have also suggested would be using `application.process.binary` as a fallback in cases like this.  Thank you!

**Comment by AlexFolland** [comment]
I'd like to mention that in Windows (the operating system family), when viewing the Volume Mixer which shows various audio sources and levels for those sources, the window name for those audio sources is displayed, which is very user-friendly.  If that kind of thing could happen in EasyEffects with a system call using the provided process ID to fetch the window name, that would be the most user-friendly to me.

**Comment by wwmm** [comment]
> If that kind of thing could happen in EasyEffects with a system call using the provided process ID to fetch the window name, that would be the most user-friendly to me.

I honestly do not know if there is way to get the window name of a foreign process. THere is definitely a way to find its executable name because `top` and similar software do it. But the string in the window title is something that the application decides and I have never seen QT or GTK exposing it in a way that external process could read them.

>For example, where it says "qmmp" in my screenshot, (or maybe where it says "Playback" instead), it would instead say "In Flames - Our Infinite Struggle", which is the window name.

We already show the `media.name` that in some players is set to the name of the song being played. In your pw-cli output it was set to `audio stream #1`. Pavucontrol also shows this tag. The problem is that not all audio players use it =/.

**Comment by wwmm** [comment]
We may also face some difficulties in the Flatpak package. Let's consider that there is some kind of system call that allows the binary name or the window title of a given process to be read. Will a Flatpak app be able to access it? I have no idea...

**Comment by AlexFolland** [comment]
That's terrible.  In Windows, you can simply get the `MainWindowTitle` member from the `Process` object, like so: `Process.GetProcessById(id).MainWindowTitle`.  How is this not standardized in Linux?  No wonder it's not the year of the Linux desktop yet!  Well, thanks for being realistic.

**Comment by wwmm** [comment]
> How is this not standardized in Linux? No wonder it's not the year of the Linux desktop yet! Well, thanks for being realistic.

On Linux the "standard" way to get a similar information is reading `/proc/PID/comm` or `/proc/PID/cmdline`. But they are not necessarily equal to the window title.

**Comment by AlexFolland** [comment]
I guess they just need to add `/proc/PID/mainwindowtitle` and have desktop environments and/or window managers populate it automatically.  All windowed programs that I use have valid and useful window titles which are displayed in my desktop environments panel ("taskbar" in Windows terminology), so why should it be difficult to access those?  My window manager knows them all, so it should just forward them.  Oh well.  This is getting off-topic since it's just wishful at this point.  I wish it was easy to access this clearly-important information.

**Comment by wwmm** [comment]
I have updated our master branch with the work around. If `application.name` and `node.name` are empty `application.process.binary` is used if it is available. Not all apps set it. MPV doesn't for example. If everything fails then `Undefined` is shown.

**Comment by AlexFolland** [comment]
Maybe if everything else fails but `application.process.id` is populated, it could say "Undefined (process ID 346678)" so at least the user has a way to figure it out if they check the running processes.

By the way, in checking this, I noticed that somehow my process manager, ksysguard, has a `Window Title` column which seems accurate.  Are you sure there's no simple way to query it?  I looked into the ksysguard source code and couldn't find how they query it though.

**Comment by wwmm** [comment]
>By the way, in checking this, I noticed that somehow my process manager, ksysguard, has a Window Title column which seems accurate.

Interesting. I installed it here on my computer but for some reason it fails miserably in this task. It could get the title only of a Firefox tab and the Guake dropdown terminal. I showed an empty string for all the other programs.

 > Are you sure there's no simple way to query it?

I ave no idea. The most I could find on google was a few references to `xdottool` being able to do it. But it is probably through some X11 only API. Maybe that is what ksysguard is doing and would explain it failing on my computer considering I use Wayland.

**Comment by violetmage** [comment]
For what it's worth, I also like the idea of showing "Undefined name (Process #12345678)" as a last resort when possible.

**Comment by AlexFolland** [comment]
Thanks for that message supporting that idea.  I think it's important to say "ID" instead of "#" in that case since other programs will refer to the number as specifically the "process ID" or "pid".

**Comment by wwmm** [comment]
>Thanks for that message supporting that idea. I think it's important to say "ID" instead of "#" in that case since other programs will refer to the number as specifically the "process ID" or "pid".

I am implementing it now. Just have in mind we also need a fallback for the lack of `id` number. For example `MPV` streams also do not have the id property. So no easy way to get its process id number just from what PipeWire provides us. I wonder what is happening inside PipeWire in these cases. I can understand missing tags when their availability depends on the audio client setting them. But the client does not set PID. Why can PipeWire get this number for some streams but not for others?? Weird...

**Comment by AlexFolland** [comment]
Yeah, that is very confusing.  Everything should have a process ID, since every audio stream must come from a process.  It makes no sense for that to ever be missing.  That seems like a bug in PipeWire.

**Comment by AlexFolland** [comment]
Maybe in that case, it could say "Undefined (missing process ID)" to show that even PipeWire doesn't know where the stream is from.

**Comment by wwmm** [comment]
Master branch updated again. IT is probably working fine. But I do not have a real world case where all the fallback fail to test.
