### ISSUE TITLE
No output after SteamOS 3.5 update (SOLVED)

### ISSUE THREAD

**Issue by serif** [wwmm/easyeffects#2809]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

SteamOS 3.5.7

### Describe the bug

**Problem**: Launching Easy Effects mutes audio from all applications

**Solution** (Flatpak): Reset settings with `com.github.wwmm.easyeffects -r`

Possible solution for others: `easyeffects -r`

The problem appeared after updating SteamOS to 3.5 some time ago. It may have to do with driver changes between 3.4 and 3.5. I tried restarting, updating the flatpak, connecting/disconnecting my external audio device (dock, hdmi), and selecting different output options under the Pipewire section, but no luck, null output after launching EE. I don't know the cause, but in case someone else has this issue, I wanted to let you know resetting fixed it. Thank you for keeping presets separate from that reset, btw. :)

### Expected Behavior

Audio should continue to output when using EE.

### Debug Log

I'm sorry I didn't capture a Debug Log before trying the reset.

### Additional Information

And thank you so much for this wonderful app! My speakers have an intolerably bad response curve without it! I'm getting a cheap measurement mic soon and will be using Room EQ Wizard to create an even better eq curve, and I'll be very glad for the import functions then too.

**Comment by serif** [comment]
I had found the reset suggestion in your comment [here](https://github.com/wwmm/easyeffects/issues/2803#issuecomment-1854847706). Thank you again.

**Comment by wwmm** [comment]
Ok. Feel free to reopen in case of more problems.
