### ISSUE TITLE
Autogain output gain bar graph overflows with positive output gain

### ISSUE THREAD

**Issue by dantob** [wwmm/easyeffects#2813]
### EasyEffects Version

7.1.3

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

![Screenshot from 2023-10-27 21-46-02](https://github.com/wwmm/easyeffects/assets/12003874/c798ac5c-7a1a-482b-b269-f9146c9d109c)

**Comment by wwmm** [comment]
This is a known gtk4 bug #1441 that unfortunately has not been fixed for years...
