### ISSUE TITLE
Freezing while having EQ context menu open

### ISSUE THREAD

**Issue by desudesudesudesudesudesudesu** [wwmm/easyeffects#2814]
### EasyEffects Version

7.1.3

### What package are you using?

Arch (easyeffects)

### Distribution

archlinux

### Describe the bug

Inconsistent to recreate but happens very frequently either on ALT-TAB or on clicking other UI elements. Haven't experienced a UI unfreeze yet, solved by closing EasyEffects.
Bug triggered @ 0:30

[untitled.webm](https://github.com/wwmm/easyeffects/assets/151712842/52c0f9d6-37fc-44bb-ac62-055e990c6f0f)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
It is probably the same gtk4 bug that is discussed at #1182. Nowadays even on wayland we can see some variations of it.

In EasyEffects preferences window there is a poor workaround for it. Disable the option `Hide Menus on Outside Clicks`. It will help to avoid some of the annoying effects of this gtk4 bug but you will be forced to click on the menu button to close it.
