### ISSUE TITLE
[Feature Request] Echo effect

### ISSUE THREAD

**Issue by tmvkrpxl0** [wwmm/easyeffects#2826]
Hello, I've been using EasyEffect for making my mic sound better, but I recently decided to try making my voice sound robotic.
Common way to achieve this is to use echo (not reverb), I do see echo canceling, and this may not fit with goal of the project, but could you please add echo effect?

**Comment by tmvkrpxl0** [comment]
Currently I'm using Delay with Stereo Tools. It does work but feels weird.

**Comment by tmvkrpxl0** [comment]
Also Does Easy Effect support changing sample rate?

**Comment by wwmm** [comment]
About the sampling rate question EasyEffects follows the  one PipeWire is using. So you have to make PipeWire use a different one if you want to change it.

>Currently I'm using Delay with Stereo Tools. It does work but feels weird.

As I am not an expert on echo creation the only other approach that comes to my mind is using the reverb plugin. If you play with the `Pre Delay` and the `Decay` time parameters you can have echo instead of just the usual reverberation effect.
![Screenshot from 2023-12-25 12-11-30](https://github.com/wwmm/easyeffects/assets/16225172/95b2e201-393d-4a27-b51b-d958cc8a7d7b)
I tried the parameters above while watching a youtube video and there was echo. You will just have to tune the parameters to get what you want.

**Comment by wwmm** [comment]
The amount of unprocessed (dry) and processed signal (wet) also have an impact as expected.

**Comment by tmvkrpxl0** [comment]
I couldn't get reverb to only echo and not actually reverb.
About bitrate, command `pw-metadata -n settings 0 clock.force-rate 11025` sometimes works, although weird. I deleted the original comment because I thought I figured out how, turns it I didn't.
It changes bitrate of my entire pc including playing audio, so I'll have to find another way.

**Comment by wwmm** [comment]
>command pw-metadata -n settings 0 clock.force-rate 11025

Is there a reason to choose this strange rate value? I am not sure if all plugins will work well with it.

>I couldn't get reverb to only echo and not actually reverb

Yes. Its echo has some reverberation mixed in it. I am not sure if it can be filtered. Something else that may be possible is using the convolver if you find in the internet an impulse response file that adds echo to the signal. There are some that add reverberation. Maybe there is one focused on echo out there.

**Comment by tmvkrpxl0** [comment]
The rate value is picked arbitrarily from bit rate lists of Audacity. It seemed low enough, but others can work. It does work for now, idk what happened before.

**Comment by wwmm** [comment]
This post suggests that the convolver approach is viable https://dsp.stackexchange.com/questions/24689/how-to-generate-realistic-echo-to-sounds. I have never tried to use a "room impulse response" generator but maybe you can use one to generate the impulse response you need.

**Comment by tmvkrpxl0** [comment]
"echo" I mean just playing the original audio right as it is with bit of delay, I should've clarified this earlier.

**Comment by wwmm** [comment]
>I mean just playing the original audio right as it is with bit of delay, alongside with original, overlapping

Like what is done by this
![Screenshot from 2023-12-25 13-01-47](https://github.com/wwmm/easyeffects/assets/16225172/6981c3ba-432d-4848-a8ef-2ef6d272ff1c)
?

**Comment by tmvkrpxl0** [comment]
Yeah, exactly

**Comment by tmvkrpxl0** [comment]
Sorry for late reply, I'd like to make correction.
The delay effect configuration plays audio with delay on each side but what I intended was playing it twice, at same time on both sides.
If this is too niche then I'll combine with streo.

**Comment by wwmm** [comment]
>but what I intended was playing it twice, at same time on both sides.

I am not sure I understand. As it feels like you want a mono sound using the stereo tools plugin to create one is probably the solution.

**Comment by sadko4u** [comment]
https://lsp-plug.in/?page=manuals&section=art_delay_mono
https://lsp-plug.in/?page=manuals&section=art_delay_stereo

You can build any delay you want

https://www.youtube.com/watch?v=mEP1WyLFruY
