### ISSUE TITLE
level meter in automatic amplifier with overflow

### ISSUE THREAD

**Issue by Cyborgscode** [wwmm/easyeffects#2829]
### EasyEffects Version

7.1.3

### What package are you using?

Fedora

### Distribution

F38

### Describe the bug

Version     : 7.1.3
Release     : 1.fc38
Architecture: x86_64

The automatic amplification multiplier box overflows far beyond the window frame

Screenshots available:

https://bugzilla.redhat.com/show_bug.cgi?id=2255892

### Expected Behavior

no overflow for level meter.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Unfortunately this is a gtk4 bug. More information in another issue #1441
