### ISSUE TITLE
Continuous Integration for PulseEffects

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/easyeffects#284]
Let's use this issue to track different thoughts on this to not forget them.

CI should include:

* automatically built (e.g. daily) package `pulseaudio-git` in PPA 
* build it automatically in Launchpad 
* autoimport from https://github.com/wwmm/pulseeffects.git and build (or import from mikhailnov/pulseeffects and automerge wirth wwmm/pulseeffects, probably `git-build-recipe` can help?)
* OR: Launchpad Recipe probably is a better choice (https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted)

Those tests will detect only issues with building, but we should also continuously test running PulseEffects (PE). We can use debian's `autopkgtest` to run autotests when building those daily packages http://packaging.ubuntu.com/html/auto-pkg-test.html , http://packaging.ubuntu.com/html/ 

* can `autopkgtest` be ran in Launchpad?

Run-test may be based on https://lists.altlinux.org/pipermail/sisyphus/2018-April/366621.html:

* run pulseaudio (will it be easy and possible in a headless minimal environment on Launchpad?)
* run PulseEffects in Xvfb headlessly
* make screenshot
* compare it with master screenshot using imagemagick (see link above for a working example)

* here comparing screenshots will result into a lower percent of screenshots similarity if localization (e.g. Russian) gets fuzzies (and what next?)

* next, some more complicated tests can be implemented, e.g. take an audio stream, apply PE's effects and test the result, but I now don't know how to implement it; it should be done only after other basic parts.

We will build in a clean chroot insuring that it's buildable.

* We should install resulting package into a very clean and minimal environment to ensure that no runtime dependencies are missed

Probably useful links:
* https://wiki.ubuntu.com/AutomatedTestingDeployment
* https://help.launchpad.net/Packaging/SourceBuilds/Recipes

I will probably try to implement CI like this later.

**Comment by mikhailnov** [comment]
Launchpad is an open source system which can be ran on private servers, so we don't vendorlock to proprietary CI services

**Comment by mikhailnov** [comment]
https://wiki.ubuntu.com/Testing/Automation

**Comment by mikhailnov** [comment]
Launchpad PPAs do not run `autopkgtest` tests: https://answers.launchpad.net/launchpad/+question/246354
Autopkgtest infrastructure can be installed on a separate server and integrated with Github: https://wiki.ubuntu.com/ProposedMigration/AutopkgtestInfrastructure
(It seems to complicated for now, a bash scripts that simply run somewhere will be easier)

**Comment by mikhailnov** [comment]
Or maybe such testing is not needed so much and may block development, and so just daily builds&tests will be enough

**Comment by wwmm** [comment]
I agree. It is not necessary to test every commit. Specially because I usually make too many

**Comment by mikhailnov** [comment]
https://meta.sr.ht/

**Comment by wwmm** [comment]
I finally had time to do something in this direction. I am using circleci https://circleci.com/gh/wwmm/pulseeffects. At least Gitlab continuos integration builds pull requests besides branch updates. I wonder if circleci+github will do the same.

**Comment by wwmm** [comment]
The config file is here https://github.com/wwmm/pulseeffects/blob/master/.circleci/config.yml and in case you think it would be useful to build in other images besides the one from Arch Linux there is an example here https://github.com/paolostivanin/OTPClient/blob/master/.circleci/config.yml

**Comment by mikhailnov** [comment]
https://github.com/wwmm/pulseeffects/blob/master/.circleci/config.yml is just building, we'd better write some other tests with strating Xfvb, pulseaudio etc...

**Comment by mikhailnov** [comment]
It would be nice to also test building on non-Linux platforms, Cirrus CI (not Circle CI) has FreeBSD support - https://cirrus-ci.org/guide/FreeBSD/ (it's just an idea for future)

**Comment by mikhailnov** [comment]
Why do you force one thread when building (`ninja -j 1`)?

**Comment by mikhailnov** [comment]
I've made CI tests, but I'm not sure that they are worth including to upstream because they will break in case of adding new build dependencies:

```diff
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 9b6812ea..21bd95aa 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,8 +9,44 @@ jobs:
       - run: pacman -Syu --noconfirm && pacman -S --noconfirm pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm libpulse gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv
       - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
 
+  ubuntu_1804:
+    docker:
+      - image: ubuntu:18.04
+    steps:
+      - checkout
+      # Now follow https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source#debian--ubuntu
+      # First install package building tools
+      - run: apt install -y devscripts equivs
+      # Now generate a fake deb package depending from all Build-Depends in debian/control
+      # and install this package with all dependencies
+      - run: mk-build-deps --install debian/control
+      # remove generated deb package to not break git repo consistency
+      - run: rm -f *.deb && git reset --hard
+      # now build the deb package without signing it
+      - run: dpkg-buildpackage -i -us -uc
+
+  debian_sid:
+    docker:
+      # Note: Debian Sid may be too unstable due to possible temporary removals of some build deps
+      # from their repos, but it probably will not happen, let's and use Debian Sid insted of latest Ubuntu
+      - image: debian:testing
+    steps:
+      - checkout
+      # Now follow https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source#debian--ubuntu
+      # First install package building tools
+      - run: apt install -y devscripts equivs
+      # Now generate a fake deb package depending from all Build-Depends in debian/control
+      # and install this package with all dependencies
+      - run: mk-build-deps --install debian/control
+      # remove generated deb package to not break git repo consistency
+      - run: rm -f *.deb && git reset --hard
+      # now build the deb package without signing it
+      - run: dpkg-buildpackage -i -us -uc
+
 workflows:
   version: 2
   build:
     jobs:
       - archlinux
+      - ubuntu_1804
+      - debian_sid
```

**Comment by wwmm** [comment]
I am forcing 1 thread `ninja -j 1` because the build crashes there if I do not do this. I imagine that they are limiting free users resources. I do not remember the exact error but the compilation process was being killed by the system.

I agree that we have to test more than just compiling. But it is a start :-)

I did a tests with your patch and the build failed https://circleci.com/gh/wwmm/pulseeffects/19. For now I will keep only the arch image. I think that until we test more than just building the source having only one image it is enough.

**Comment by mikhailnov** [comment]
ok, thank you

**Comment by wwmm** [comment]
I think that what we have at this moment is enough. And with PipeWire being used many things are different today when compared to the past.
