### ISSUE TITLE
[Feature Request] Downsampling/Bit crusher effect

### ISSUE THREAD

**Issue by tmvkrpxl0** [wwmm/easyeffects#2847]
Announcement systems or old devices have low bit rate, and I'd like to simulate voices from it using Easy Effect.
Sorry if my requests are too niche, I'm looking for ways to mimic Half Life voice line these days.
There's an option in pipewire that adjusts bit rate. However, it is applied globally, not only to recording but also playing. And applications don't adjust well to it.
Discord, for example, sometimes cannot play audio at all if it goes too low. Bit rate I used back then was 11025, which is one of the options in audacity.

I appreciate your effort in this and thank you.

**Comment by wwmm** [comment]
>Sorry if my requests are too niche, I'm looking for ways to mimic Half Life voice line these days.

It definitely is. But there is no harm in asking. The question is how to do it. EasyEffects follows the sampling rate used by PipeWire. So even if I write a plugin that lowers the rate I will have to bring it back to the one PipeWire is using. So this is not a  solution.

Maybe there is some kind of algorithm out there that can simulate the low bitrate effect without actually lowering it. Or maybe even a LV2 plugin with such a thing already implemented. THis would be the ideal solution. But I am not aware of it.

**Comment by tmvkrpxl0** [comment]
Ah, I found word I was looking for: downsampling.
Yes, changing actual bit rate setting is not desired.

**Comment by violetmage** [comment]
iirc, this type of effect is called "bitcrushing" in the lands of music synthesizers. maybe someone knows of an existing plugin with this feature.

**Comment by wwmm** [comment]
Maybe a plugin like the `Calf Crusher` will do what you want https://calf-studio-gear.org/. But I have never used a bit crusher. So I am not sure.

**Comment by violetmage** [comment]
ok, just reread wikipedias page on bitcrushers to jog the memory, tgen looked at calf crusher's docs. the docs don't seem to line up with the descriptions and images on their website, so not sure which to believe.

However, assuming the image they show is correct, then calf crusher has independent controls for bit depth and sample rate, meaning it can do what OP wants.

**Comment by sadko4u** [comment]
To simulate an effect of low bitrate, just apply brickwall lowpass filter at the nyquist frequency of that system. That means, if the system has 8000 Hz sample rate, the lowpass filter should be applied a bit lower than 4 kHz.

**Comment by wwmm** [comment]
>To simulate an effect of low sample rate, just apply brickwall lowpass filter at the nyquist frequency of that system. That means, if the system has 8000 Hz sample rate, the lowpass filter should be applied a bit lower than 4 kHz.

Something like this @sadko4u ?
![Screenshot from 2024-01-09 11-49-39](https://github.com/wwmm/easyeffects/assets/16225172/e6c28d0c-c605-4fa4-8692-bd21e66f26a0)

**Comment by wwmm** [comment]
>if the system has 8000 Hz sample rate

While testing my system was at `48 kHz` so in order to easily notice changes to the audio I had to go as down as 8 kHz. @tmvkrpxl0 try to do some tests. This LSP filter plugin is already available in EasyEffects.

**Comment by sadko4u** [comment]
> Something like this @sadko4u ?

Yes but flat response below the cut-off frequency is preferred.

**Comment by tmvkrpxl0** [comment]
I have no idea what software or plugins you guys are mentioning. I do have calf, lsp, mda, and zam installed in flatpak but I don't know how to use this in live.

**Comment by tmvkrpxl0** [comment]
I see. I thought I had to somehow connect other studio tools with EasyEffect. Applying Filter worked, thanks, although I didn't see option "low brick pass". Low pass with LRX works best for me.
