### ISSUE TITLE
[Request] make native window for EQ stereo rather than left/right

### ISSUE THREAD

**Issue by TheBestKmanEver** [wwmm/easyeffects#2858]
this would make it easier to EQ in the LSP window. with the LSP window being in left/right mode i can only move one channel at at time unless i use the EasyEffects EQ window in turn making it annoying to use. do have the possibility to have left/right mode if you are using 'split channel' 
i would very much like to use the LSP window over the EasyEffects window for EQing

**Comment by violetmage** [comment]
I don't fully understand what you want.

Can you share a screenshot of the lsp eq window that you like to use?

**Comment by TheBestKmanEver** [comment]
![image](https://github.com/wwmm/easyeffects/assets/35676228/1516d36c-2c1e-4538-9816-49318bf34fe7)
left is the one in left/right mode with some bass added on left channel but in order to get the right channel at that same level i need to also adjust the right 

the one on the right allows bot channels to be moved together

**Comment by wwmm** [comment]
This can not be done without actually using the stereo variant of the LSP plugin. But switching on the fly is also not possible. We would have to wrap the whole stereo LSP EQ in another plugin. It is a lot of effort to have essentially the same functionality we already have.

As some people need to apply different equalization for each channel the least effort approach is to use the left-right plugin. For the people that wnat the same equalization EasyEffects internally copy the data from the left channel to the right one. But the native LSP window is intended for people that will make full use of its flexibility. And we can not change it.

**Comment by TheBestKmanEver** [comment]
what about adding a new EQ effect in EasyEffects and have that one with this funtion and have the current as left/right mode?????

**Comment by wwmm** [comment]
>what about adding a new EQ effect in EasyEffects and have that one with this funtion and have the current as left/right mode?????

Although technically possibly it is hard to justify the huge amount of work involved to add the same functionality we already have. It is not one of the cases where something new that could not be done before becomes possible. The stereo variant of the LSP plugin will do the same  processing the current one already does when copying the left settings to the right. The only real difference is improving a little the workflow of people that want to use the plugin native window.

**Comment by TheBestKmanEver** [comment]
> > what about adding a new EQ effect in EasyEffects and have that one with this funtion and have the current as left/right mode?????
> 
> Although technically possibly it is hard to justify the huge amount of work involved to add the same functionality we already have. It is not one of the cases where something new that could not be done before becomes possible. The stereo variant of the LSP plugin will do the same processing the current one already does when copying the left settings to the right. The only real difference is improving a little the workflow of people that want to use the plugin native window.

how do you go about copying from left to right in the LSP window without having to manually change both sides?

**Comment by wwmm** [comment]
>how do you go about copying from left to right in the LSP window without having to manually change both sides?

IF you close the native plugin window EasyEffects will copy the left parameters to the right channel for you. As long as you do not enable split channels. I tested this now and although it is not the best in terms of usability it is better than manually replicating everything.

**Comment by TheBestKmanEver** [comment]
> > how do you go about copying from left to right in the LSP window without having to manually change both sides?
> 
> If you close the native plugin window EasyEffects will copy the left parameters to the right channel for you. As long as you do not enable split channels. I tested this now and although it is not the best in terms of usability it is better than manually replicating everything.

ok so i could do this but then there's an issue of when closing the native window, the UI freezes up for about 15 seconds before i can reopen the window, opening it has no lag but closing it does

**Comment by wwmm** [comment]
>ok so i could do this but then there's an issue of when closing the native window, the UI freezes up for about 15 seconds before i can reopen the window, opening it has no lag but closing it does

Are you using the Flatpak package? When you close the window EasyEffects saves the current EQ settigns to its database. This is usually very fast when using a native package because GSetings will use a high performance backend. But for reasons I do not know the flatpak packge has to use a very inefficient database backend that is really slow.

**Comment by TheBestKmanEver** [comment]
yea i am stuck using the flatpak version cause the package native to MX Linux is 7.0.0-1

**Comment by TheBestKmanEver** [comment]
asking in MX Linux Forum if they can update EasyEffects to 7.1.3 in their repo

**Comment by wwmm** [comment]
Something else that came to my mind now is that you can keep the native window opened and change the parameters in EasyEffects custom window at the same time. This way you can change both channels at once without having to close the window frequently. Is there a reason to not do this?

**Comment by TheBestKmanEver** [comment]
using my scroll wheel on the eq in the EasyEffects windows moves them too much at once where it doesnt move them so dramatically in the LSP window

**Comment by wwmm** [comment]
>using my scroll wheel on the eq in the EasyEffects window moves them too much at once where it doesnt move them so dramatically in the LSP window

Which parameter?

**Comment by TheBestKmanEver** [comment]
gain, i much rather prefer the finer control of gain in the LSP window when using my scroll wheel, in the Easyeffects window it goes 1dB at a time where in the LSP window it moves in 0.09 (well i guess technically 0.085 cause it goes from 0.09 to 0.17 to 0.26 etc)

**Comment by TheBestKmanEver** [comment]
wait a sec, i just noticed the added 'gain' thinger in the gear menu of each freq thinger and it moves in 0.01 increments with scroll wheel, this is still annoying though cause then i have to click on every individual menu to control it

**Comment by wwmm** [comment]
>this is still annoying though cause then i have to click on every individual menu to control it

It is. But I do not think there will be a better solution. Some people do not like very small steps in the gain slider.  And in a way I agree it would be annoying indeed. Having a spinbutton in the menu is a decent compromise.

**Comment by TheBestKmanEver** [comment]
well darn, at this point MX is unable to update at this point
see following link https://forum.mxlinux.org/viewtopic.php?t=78906

**Comment by wwmm** [comment]
Ok @TheBestKmanEver . 

@vchernin is it possible for the user to force the Flatpak package to use the standard GSettings backend? That ini file based backend really degrades the user experience.

**Comment by violetmage** [comment]
@wwmm afaict the keyfile backend is the only supported sandbox respecting way to use gsettings in a flatpak, as the alternative is to run a completely separate dconf daemon for every running sandbox.

More details here: [https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/](https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/)

**Comment by wwmm** [comment]
>afaict the keyfile backend is the only supported sandbox respecting way to use gsettings in a flatpak, as the alternative is to run a completely separate dconf daemon for every running sandbox.

>More details here: https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

Ok, I totally forgot about this...

**Comment by TheBestKmanEver** [comment]
> More details here: https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

oh yikes this is currently out of my scope of knowledge to do such things, at this point i will use what i have available

**Comment by TheBestKmanEver** [comment]
sorry for a second ping, accidently deleted.
> More details here: https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

oh yikes this is currently out of my scope of knowledge to do such things, at this point i will use what i have available. maybe add 0.10dB steps for changing gain if this is possible instead of 1dB on the sliders or 0.01dB on the gain under the gear menu...
unless i can essentially get a full out walk through with this (holding my hand as i have a lot of challenges learning certain things)

**Comment by violetmage** [comment]
@TheBestKmanEver gtk sliders have an interesting feature where if you click and hold on them without moving the mouse, the slider will visually "balloon" (get bigger), and then the sensitivity will be reduced.

**Comment by TheBestKmanEver** [comment]
> @TheBestKmanEver gtk sliders have an interesting feature where if you click and hold on them without moving the mouse, the slider will visually "balloon" (get bigger), and then the sensitivity will be reduced.

i actually noticed this but there is a slight issue (not anything major), when it does this the slider will move weirdly for about 2 second but is then fine. it doesnt move so dramatically that it causes issues it just has a weird jerky movement for a couple seconds, it's a little annoying but it's not major enough to care. i am able to have the LSP window open while EQing and it changes in realtime to what i do in the EasyEffects window which is awesome cause now i can see what the EQ is doing
