### ISSUE TITLE
Flatpak: "Launch Service at System Startup" and "Shutdown on Window Closing" toggles don't work

### ISSUE THREAD

**Issue by amsyarzero** [wwmm/easyeffects#2869]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Linux

### Describe the bug

I cannot seem to enable _Launch Service_ and disable _Shutdown on Window Closing_, no matter what. This issue is very similar to #2426.

## System specs
```bash
OS: Arch Linux x86_64
Host: HP Pavilion Gaming Laptop 15-dk0xxx
Kernel: 6.7.1-arch1-1
Packages: 688 (pacman), 30 (flatpak)
Shell: bash 5.2.26
WM: LeftWM
CPU: Intel i7-9750H (12) @ 4.500GHz
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
Memory: 4350MiB / 15836MiB
```

## Backends used
- `xdg-desktop-portal`
- `xdg-desktop-portal-gtk`

```
# leftwm-portals.conf
[preferred]
# use gtk for every portal interface
default=gtk
```

## Autostart file
```
[Desktop Entry]
Type=Application
Name=EasyEffects
Comment=EasyEffects background service
Exec=nohup flatpak run --command=easyeffects com.github.wwmm.easyeffects --gapplication-service
X-Flatpak=com.github.wwmm.easyeffects
```

## Fixes tried
| Fixes | Result |
| --- | --- |
| Reinstalling both backends | Problem persists |
| Installing `xdg-desktop-portal-gnome` to provide Background portal in `leftwm-portals.conf` | Problem persists |
| Reinstalling EasyEffects | Problem persists |
| Restarting computer after reinstalling | Problem persists |
| Putting an autostart file | Opens on launch minimized, but re-opening and closing causes problem to come back (as detailed [here](https://github.com/wwmm/easyeffects/issues/1668#issuecomment-1191633604) in #1668) |
| Running `flatpak permission-reset com.github.wwmm.easyeffects` | Problem persists |

### Expected Behavior

- I am able to enable the "Launch Service at System Startup" toggle
- I am able to disable the "Shutdown on Window Closing"

### Debug Log

<details><summary>Debug Log</summary><br/>

```bash
(easyeffects:2): easyeffects-WARNING **: 17:03:58.761:  libportal.cpp:70        Background access has been denied

(easyeffects:2): easyeffects-WARNING **: 17:03:58.762:  libportal.cpp:71        Please allow Easy Effects to ask again with flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 17:03:58.784:  libportal.cpp:84        due to error, setting autostart state and switch to false

(easyeffects:2): easyeffects-WARNING **: 17:04:08.736:  libportal.cpp:70        Background access has been denied

(easyeffects:2): easyeffects-WARNING **: 17:04:08.736:  libportal.cpp:71        Please allow Easy Effects to ask again with flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 17:04:08.755:  libportal.cpp:95        due to error, setting shutdown on window close state and switch to true
```
</details>

### Additional Information

For some reason, when I run `flatpak permission-show` on any app (including EasyEffects), nothing shows up.

**Comment by wwmm** [comment]
Does `flatpak permission-reset com.github.wwmm.easyeffects` change anything?

**Comment by wwmm** [comment]
>I've discovered that this issue may be with my Flatpak setup in general rather than EasyEffects, as trying to enable scheduled backups in Pika Backup (Flatpak) throws a similar error.

I see. @vchernin is this still working on your computer? I wonder if the change in the dbus server recently could be somehow related to  the error messages in the image.

**Comment by violetmage** [comment]
you can use busctl (cli), bustle (flatpak), or dspy (flatpak) to look at what exists / what's happening on your dbus.

My guess is that either the background portal failed to install, or failed to register with your dbus server.

**Comment by violetmage** [comment]
you could also just try the [Door Knocker](https://flathub.org/apps/xyz.tytanium.DoorKnocker) or [ASHPD Demo](https://flathub.org/apps/com.belmoussaoui.ashpd.demo) flatpaks, which are simple test apps for the various portals.

**Comment by amsyarzero** [comment]
> Does `flatpak permission-reset com.github.wwmm.easyeffects` change anything?

@wwmm Nope, the problem still persists. I'll add it to the *Fixes Tried* section in my original post.

**Comment by amsyarzero** [comment]
Thank you for the suggestion, @violetmage .

> you can use busctl (cli), bustle (flatpak), or dspy (flatpak) to look at what exists / what's happening on your dbus.
> 
> My guess is that either the background portal failed to install, or failed to register with your dbus server.

Using Bustle, here's what happens when I try to choose *Launch Service at System Startup* or *Shutdown on Window Closing* in EasyEffects.
![Bustle showing that the Background portal doesn't exist on my setup.](https://github.com/wwmm/easyeffects/assets/81513934/930fe979-e7a7-4c90-b649-729c4d08078c)

Meanwhile, with ASHPD Demo, the Background portal test fails to run.
![ASHPD Demo showing that the Background portal test fails.](https://github.com/wwmm/easyeffects/assets/81513934/e705805b-6ecc-4c9c-bdf8-e948c415887d)

**Comment by jaum20** [comment]
any update on this? I have the same problem

**Comment by FairplexVR** [comment]
> Does `flatpak permission-reset com.github.wwmm.easyeffects` change anything?

Worked for me, but required a reboot to get the permission request again

**Comment by amsyarzero** [comment]
Sorry for the super late reply.

After searching and experimenting about this for months, I found out that this problem is actually not the fault of EasyEffects. Rather, it's because **xdg-desktop-portal-gtk doesn't include the background interface**, unless one does a custom build of it.

With that said, I'll close this issue.
