### ISSUE TITLE
Samplerate of soundcard against USB amplifier

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#2877]
My soundcard suports this samplerates:
```
$ grep -rH rates /proc/asound | cut -d : -f 2- | sort -u
    rates [0x0]:
    rates [0x160]: 44100 48000 96000
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
```
My Amplifier supports more (+) 352800 and 384000, when I use these samplerates, EasyEffects close. The sound continues without EasyEffects.  
Is it a problem with EasyEffects? How can I debug this?

**Comment by servimo** [comment]
Ok I found, it is the latest lines of G_MESSAGES_DEBUG=easyeffects easyeffects:
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.119: 	limiter.cpp:139	soe: limiter latency: 0.005 s
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.119: 	output_level.cpp:37	soe: output_level: PipeWire blocksize: 2048
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.120: 	output_level.cpp:38	soe: output_level: PipeWire sampling rate: 352800
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.138: 	convolver.cpp:282	soe: convolver: irs file: /home/sergio/.config/easyeffects/irs/Tin HiFi T2 minimum phase 48000Hz.irs
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.138: 	convolver.cpp:283	soe: convolver: irs rate: 48000 Hz
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.138: 	convolver.cpp:284	soe: convolver: irs channels: 2
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.138: 	convolver.cpp:285	soe: convolver: irs frames: 4800
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.138: 	convolver.cpp:308	soe: convolver resampling the kernel to 352800
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.150: 	convolver.cpp:324	soe: convolver: kernel initialized
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.159: 	convolver.cpp:442	soe: convolver: zita is ready
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.159: 	effects_base.cpp:265	soe: pipeline latency: 5 ms
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.166: 	convolver.cpp:242	soe: convolver latency: 0 s
(easyeffects:152245): easyeffects-DEBUG: 21:45:06.169: 	effects_base.cpp:265	soe: pipeline latency: 5 ms
Morto

**Comment by violetmage** [comment]
@servimo can you post a full debug log of the crash(?), using G_MESSAGES_DEBUG=easyeffects ?

Also, what do you mean by amplifier? Is it an all-in-one unit, combining a DAC and an amp? Or something else?

**Comment by wwmm** [comment]
>Morto

That sounds like the system killing EasyEffects because the audio processing became too heavy in the realtime thread. Which plugin were enabled? Just the convolver?

In any case not all plugins support such high sampling rate values. Look at https://github.com/wwmm/easyeffects/issues/2069#issuecomment-1664800368 for example. So even if we find a way to avoid your system killing EasyEffects most plugins won't work  properly at the rate you are trying to use.

**Comment by wwmm** [comment]
>In any case not all plugins support such high sampling rate values. Look at https://github.com/wwmm/easyeffects/issues/2069#issuecomment-1664800368 for example. So even if we find a way to avoid your system killing EasyEffects most plugins won't work properly at the rate you are trying to use.

Forget it. I did not pay attention to the fact the rate you are trying to use matches the maximum supported by LSP. So the audio processing being too heavy for the system to handle seems like the more plausible explanation. Either that or some limitation in the `zita-convolver` library.

**Comment by servimo** [comment]
It's a DAC, "Moondrop Dawn Pro", I was just doing some tests on it, I always use rate 196000 and plays nice, I will stay with this. 
The plugin chain is convolver > limiter > level meter, but happen the same if I change convolver to equalizer. 
One thing I noticed is that if I stay with rate 196000 the DAC keeps the blue light on, so I think it's processing full by it's side.

**Comment by servimo** [comment]
Here is the full log:
$ G_MESSAGES_DEBUG=easyeffects easyeffects
(process:342688): easyeffects-DEBUG: 02:59:31.908: 	easyeffects.cpp:35	easyeffects version: 7.1.3
(process:342688): easyeffects-DEBUG: 02:59:31.909: 	easyeffects.cpp:45	locale directory: /usr/share/locale
(easyeffects:342688): easyeffects-DEBUG: 02:59:31.916: 	presets_manager.cpp:162	user presets directory already exists: /home/sergio/.config/easyeffects/
(easyeffects:342688): easyeffects-DEBUG: 02:59:31.916: 	presets_manager.cpp:162	user presets directory already exists: /home/sergio/.config/easyeffects/input
(easyeffects:342688): easyeffects-DEBUG: 02:59:31.916: 	presets_manager.cpp:162	user presets directory already exists: /home/sergio/.config/easyeffects/output
(easyeffects:342688): easyeffects-DEBUG: 02:59:31.916: 	presets_manager.cpp:162	user presets directory already exists: /home/sergio/.config/easyeffects/autoload/input
(easyeffects:342688): easyeffects-DEBUG: 02:59:31.916: 	presets_manager.cpp:162	user presets directory already exists: /home/sergio/.config/easyeffects/autoload/output
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.400: 	pipe_manager.cpp:1481	compiled with PipeWire: 1.0.1
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.400: 	pipe_manager.cpp:1482	linked to PipeWire: 1.0.1
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.408: 	pipe_manager.cpp:1452	core version: 1.0.1
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1453	core name: pipewire-0
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1364	found metadata: settings
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Audio/Sink 33 roc-sink with serial 33 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1364	found metadata: default
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1364	found metadata: route-settings
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1364	found metadata: sm-objects
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Audio/Sink 49 alsa_output.pci-0000_00_1b.0.analog-stereo with serial 49 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Audio/Source 50 alsa_input.pci-0000_00_1b.0.analog-stereo with serial 50 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Stream/Output/Audio 64 foobar2000 Application with serial 238 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Audio/Sink 66 alsa_output.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00.pro-output-0 with serial 3730 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1259	foobar2000 Application port 75 is connected to alsa_output.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00.pro-output-0 port 158
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1259	foobar2000 Application port 67 is connected to alsa_output.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00.pro-output-0 port 85
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Audio/Sink 88 easyeffects_sink with serial 4682 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.409: 	pipe_manager.cpp:1219	Audio/Source/Virtual 89 easyeffects_source with serial 4683 has been added
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.411: 	pipe_manager.cpp:1578	easyeffects_sink node successfully retrieved with id 88 and serial 4682
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.411: 	pipe_manager.cpp:1583	easyeffects_source node successfully retrieved with id 89 and serial 4683
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.411: 	pipe_manager.cpp:955	new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, { "name": "alsa_output.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00.iec958-stereo" }
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.411: 	pipe_manager.cpp:955	new metadata property: 0, default.configured.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_1b.0.analog-stereo"}
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.411: 	pipe_manager.cpp:955	new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00.pro-output-0"}
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.411: 	pipe_manager.cpp:955	new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_1b.0.analog-stereo"}
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.412: 	pipe_manager.cpp:955	new metadata property: 64, target.node, Spa:Id, 128
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.412: 	pipe_manager.cpp:955	new metadata property: 64, target.object, Spa:Id, 4507
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.418: 	plugin_base.cpp:370	soe: output_level successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.420: 	plugin_base.cpp:370	soe: spectrum successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.454: 	lv2_wrapper.cpp:100	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.550: 	lv2_wrapper.cpp:100	http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.594: 	lv2_wrapper.cpp:100	http://lsp-plug.in/plugins/lv2/sc_limiter_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.597: 	plugin_base.cpp:370	soe: delay successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.597: 	pipe_manager.cpp:1259	easyeffects_sink port 65 is connected to ee_soe_delay port 103
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.598: 	pipe_manager.cpp:1259	easyeffects_sink port 177 is connected to ee_soe_delay port 145
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.600: 	plugin_base.cpp:370	soe: equalizer successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.600: 	pipe_manager.cpp:1259	ee_soe_delay port 176 is connected to ee_soe_equalizer port 76
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.600: 	pipe_manager.cpp:1259	ee_soe_delay port 144 is connected to ee_soe_equalizer port 181
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.602: 	plugin_base.cpp:370	soe: limiter successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.602: 	pipe_manager.cpp:1259	ee_soe_equalizer port 125 is connected to ee_soe_limiter port 131
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.603: 	pipe_manager.cpp:1259	ee_soe_equalizer port 83 is connected to ee_soe_limiter port 114
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.605: 	plugin_base.cpp:370	soe: level_meter successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.606: 	pipe_manager.cpp:1259	ee_soe_limiter port 62 is connected to ee_soe_level_meter port 153
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.606: 	pipe_manager.cpp:1259	ee_soe_limiter port 63 is connected to ee_soe_level_meter port 151
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.617: 	plugin_base.cpp:370	sie: output_level successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.621: 	plugin_base.cpp:370	sie: spectrum successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.627: 	stream_output_effects.cpp:328	disconnecting the delay filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.628: 	pipe_manager.cpp:213	 73 ee_soe_delay has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.628: 	stream_output_effects.cpp:328	disconnecting the equalizer filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.629: 	pipe_manager.cpp:213	 134 ee_soe_equalizer has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.630: 	stream_output_effects.cpp:328	disconnecting the level_meter filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.631: 	pipe_manager.cpp:213	 146 ee_soe_level_meter has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.631: 	stream_output_effects.cpp:328	disconnecting the limiter filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.631: 	pipe_manager.cpp:213	 182 ee_soe_limiter has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.635: 	plugin_base.cpp:370	soe: delay successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.635: 	pipe_manager.cpp:1259	easyeffects_sink port 65 is connected to ee_soe_delay port 115
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.636: 	pipe_manager.cpp:1259	easyeffects_sink port 177 is connected to ee_soe_delay port 94
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.638: 	plugin_base.cpp:370	soe: equalizer successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.638: 	pipe_manager.cpp:1259	ee_soe_delay port 92 is connected to ee_soe_equalizer port 81
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.638: 	pipe_manager.cpp:1259	ee_soe_delay port 182 is connected to ee_soe_equalizer port 114
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.641: 	plugin_base.cpp:370	soe: limiter successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.641: 	pipe_manager.cpp:1259	ee_soe_equalizer port 131 is connected to ee_soe_limiter port 108
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.643: 	pipe_manager.cpp:1259	ee_soe_equalizer port 146 is connected to ee_soe_limiter port 151
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.645: 	plugin_base.cpp:370	soe: level_meter successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.645: 	pipe_manager.cpp:1259	ee_soe_limiter port 129 is connected to ee_soe_level_meter port 96
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.646: 	pipe_manager.cpp:1259	ee_soe_limiter port 134 is connected to ee_soe_level_meter port 181
easyeffects-INFO: 02:59:32.656: 	application.cpp:52	disabling global bypass
(easyeffects:342688): easyeffects-DEBUG: 02:59:32.701: 	application_ui.cpp:91	Icon Theme Papirus detected
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.002: 	stream_output_effects.cpp:328	disconnecting the delay filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.004: 	pipe_manager.cpp:213	 117 ee_soe_delay has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.004: 	stream_output_effects.cpp:328	disconnecting the equalizer filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.005: 	pipe_manager.cpp:213	 202 ee_soe_equalizer has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.005: 	stream_output_effects.cpp:328	disconnecting the level_meter filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.007: 	pipe_manager.cpp:213	 125 ee_soe_level_meter has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.007: 	stream_output_effects.cpp:328	disconnecting the limiter filter from PipeWire
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.008: 	pipe_manager.cpp:955	new metadata property: 64, target.node, Spa:Id, 88
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.008: 	pipe_manager.cpp:955	new metadata property: 64, target.object, Spa:Id, 4682
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.008: 	pipe_manager.cpp:1259	foobar2000 Application port 75 is connected to easyeffects_sink port 195
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.008: 	pipe_manager.cpp:1259	foobar2000 Application port 67 is connected to easyeffects_sink port 112
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.008: 	pipe_manager.cpp:213	 167 ee_soe_limiter has been removed
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.013: 	plugin_base.cpp:370	soe: delay successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.014: 	pipe_manager.cpp:1259	easyeffects_sink port 65 is connected to ee_soe_delay port 110
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.015: 	pipe_manager.cpp:1259	easyeffects_sink port 177 is connected to ee_soe_delay port 104
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.016: 	plugin_base.cpp:370	soe: equalizer successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.017: 	pipe_manager.cpp:1259	ee_soe_delay port 103 is connected to ee_soe_equalizer port 91
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.017: 	pipe_manager.cpp:1259	ee_soe_delay port 167 is connected to ee_soe_equalizer port 151
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.027: 	plugin_base.cpp:370	soe: limiter successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.028: 	pipe_manager.cpp:1259	ee_soe_equalizer port 108 is connected to ee_soe_limiter port 176
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.028: 	pipe_manager.cpp:1259	ee_soe_equalizer port 125 is connected to ee_soe_limiter port 181
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.035: 	plugin_base.cpp:370	soe: level_meter successfully connected to PipeWire graph
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.035: 	pipe_manager.cpp:1259	ee_soe_limiter port 144 is connected to ee_soe_level_meter port 83
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.041: 	limiter.cpp:139	soe: limiter latency: 0.005 s
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.042: 	pipe_manager.cpp:1259	ee_soe_limiter port 202 is connected to ee_soe_level_meter port 114
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.044: 	application.cpp:80	new default output device: alsa_output.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00.pro-output-0
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.045: 	application.cpp:88	new default input device: alsa_input.pci-0000_00_1b.0.analog-stereo
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.046: 	application.cpp:100	device alsa_card.pci-0000_00_1b.0 has changed its input route to: analog-input-front-mic
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.046: 	application.cpp:132	device alsa_card.pci-0000_00_1b.0 has changed its output route to: analog-output-headphones
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.046: 	application.cpp:152	output autoloading: the target node name does not match the output device name
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.048: 	application.cpp:132	device alsa_card.usb-MOONDROP_MOONDROP_Dawn_Pro_MOONDROP_Dawn_Pro-00 has changed its output route to: iec958-stereo-output
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.052: 	output_level.cpp:37	soe: output_level: PipeWire blocksize: 2048
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.052: 	output_level.cpp:38	soe: output_level: PipeWire sampling rate: 352800
(easyeffects:342688): easyeffects-DEBUG: 02:59:34.070: 	effects_base.cpp:265	soe: pipeline latency: 5 ms
Dead

**Comment by wwmm** [comment]
>When I use "pw-metadata -n settings 0 clock.force-rate 192000" to force use of 192000 I can enable
"Level Meter", but as soon as I force the use of 384000 EasyEffects close.

Are you using `oversampling` in its configuration or just the default options? Oversampling will probably make it use more cpu.

**Comment by wwmm** [comment]
>I can't see any oversampling in the configuration of "Level Meter". I am just using "Convolver" or "Equalizer" and "Limiter".

Oops... For some bizarre reason I was thinking about the limiter plugin. That is what happens when answering multiple people at the same time :smile: 

Just like the autogain the level meter can be quite heavy on resources because it is based on the `libebur1228` library.

**Comment by wwmm** [comment]
>It's ok to close this thread? Thanks for helping me out to find some explanation and possible solutions.

I thin it is. There isn't much room to improve this plugin performance.

**Comment by servimo** [comment]
I reopen this issue just to clarify that the plugins using _libebur128_ are working nice with just changing in pipewire.conf "default.clock.max-quantum   = 8192"
