### ISSUE TITLE
Unable to import Equalizer presets

### ISSUE THREAD

**Issue by m2thay** [wwmm/easyeffects#2895]
### EasyEffects Version

7.1.3

### What package are you using?

Fedora

### Distribution

Fedora 39

### Describe the bug

Clicking the Equalizer "Import Preset" buttons does nothing. 

### Expected Behavior

It should open a file browser to select the file from which you would want to import an APO/GraphicEQ preset from.

### Additional Information

After reinstalling my system from Arch to now Fedora, the "Import Presets" button stopped working. I have all dependencies listed at https://packages.fedoraproject.org/pkgs/easyeffects/easyeffects/fedora-39-updates.html

I have tried - Removing easyeffects from .config and reinstalling the package.

Launching EasyEffects from the terminal and clicking the button does not show anything in the terminal. 
![2024-02-02_19-59](https://github.com/wwmm/easyeffects/assets/118320217/606cd406-0bd8-4b3d-b277-cad9ca835903)

**Comment by wwmm** [comment]
This sounds like some kind of problem in the gtk4 installation. Kill EasyEffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see if gtk is giving some kind of warning.

**Comment by m2thay** [comment]
`(process:9952): easyeffects-DEBUG: 11:02:39.110: 	easyeffects.cpp:35	easyeffects version: 7.1.3
(process:9952): easyeffects-DEBUG: 11:02:39.110: 	easyeffects.cpp:45	locale directory: /usr/share/locale
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.111: 	presets_manager.cpp:162	user presets directory already exists: /home/arttu/.config/easyeffects/
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.111: 	presets_manager.cpp:162	user presets directory already exists: /home/arttu/.config/easyeffects/input
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.111: 	presets_manager.cpp:162	user presets directory already exists: /home/arttu/.config/easyeffects/output
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.111: 	presets_manager.cpp:162	user presets directory already exists: /home/arttu/.config/easyeffects/autoload/input
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.111: 	presets_manager.cpp:162	user presets directory already exists: /home/arttu/.config/easyeffects/autoload/output
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.229: 	pipe_manager.cpp:1429	compiled with PipeWire: 0.3.84
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.229: 	pipe_manager.cpp:1430	linked to PipeWire: 1.0.1
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1400	core version: 1.0.1
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1401	core name: pipewire-0
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1312	found metadata: settings
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1312	found metadata: default
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1312	found metadata: route-settings
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1312	found metadata: sm-objects
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Sink 69 alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2 with serial 71 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Source 70 alsa_input.usb-046d_HD_Pro_Webcam_C920_223FADDF-02.analog-stereo with serial 72 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Sink 71 alsa_output.usb-Topping_DX3_Pro_-00.analog-stereo with serial 73 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Sink 72 alsa_output.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo with serial 74 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Source 73 alsa_input.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo with serial 75 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Sink 43 easyeffects_sink with serial 1304 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:1167	Audio/Source/Virtual 68 easyeffects_source with serial 1305 has been added
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:900	new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, {"name":"alsa_output.usb-Topping_DX3_Pro_-00.analog-stereo"}
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:900	new metadata property: 0, default.configured.audio.source, Spa:String:JSON, {"name":"alsa_input.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo"}
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:900	new metadata property: 0, default.video.source, Spa:String:JSON, {"name":"v4l2_input.pci-0000_0c_00.3-usb-0_1.2_1.0"}
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:900	new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.usb-Topping_DX3_Pro_-00.analog-stereo"}
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.231: 	pipe_manager.cpp:900	new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo"}
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:319 spa_pod_get_array()
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.232: 	pipe_manager.cpp:1526	easyeffects_sink node successfully retrieved with id 43 and serial 1304
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.232: 	pipe_manager.cpp:1531	easyeffects_source node successfully retrieved with id 68 and serial 1305
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.235: 	plugin_base.cpp:370	soe: output_level successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.236: 	plugin_base.cpp:370	soe: spectrum successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.269: 	lv2_wrapper.cpp:100	http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.277: 	plugin_base.cpp:370	soe: equalizer successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.278: 	pipe_manager.cpp:1207	easyeffects_sink port 67 is connected to ee_soe_equalizer port 107
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.278: 	pipe_manager.cpp:1207	easyeffects_sink port 42 is connected to ee_soe_equalizer port 106
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.281: 	plugin_base.cpp:370	sie: output_level successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.282: 	plugin_base.cpp:370	sie: spectrum successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.284: 	stream_output_effects.cpp:317	disconnecting the equalizer filter from PipeWire
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.284: 	pipe_manager.cpp:213	 103 ee_soe_equalizer has been removed
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.286: 	plugin_base.cpp:370	soe: equalizer successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.286: 	pipe_manager.cpp:1207	easyeffects_sink port 67 is connected to ee_soe_equalizer port 117
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.286: 	pipe_manager.cpp:1207	easyeffects_sink port 42 is connected to ee_soe_equalizer port 116
easyeffects-INFO: 11:02:39.290: 	application.cpp:50	disabling global bypass
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.311: 	application_ui.cpp:86	Icon Theme Adwaita detected
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.419: 	stream_output_effects.cpp:317	disconnecting the equalizer filter from PipeWire
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.420: 	pipe_manager.cpp:213	 118 ee_soe_equalizer has been removed
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.422: 	plugin_base.cpp:370	soe: equalizer successfully connected to PipeWire graph
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.422: 	pipe_manager.cpp:1207	easyeffects_sink port 67 is connected to ee_soe_equalizer port 108
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.422: 	pipe_manager.cpp:1207	easyeffects_sink port 42 is connected to ee_soe_equalizer port 107
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:78	new default output device: alsa_output.usb-Topping_DX3_Pro_-00.analog-stereo
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:86	new default input device: alsa_input.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:130	device alsa_card.pci-0000_0a_00.1 has changed its output route to: hdmi-output-2
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:150	output autoloading: the target node name does not match the output device name
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:98	device alsa_card.usb-046d_HD_Pro_Webcam_C920_223FADDF-02 has changed its input route to: analog-input-mic
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:118	input autoloading: the target node name does not match the input device name
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:130	device alsa_card.usb-Topping_DX3_Pro_-00 has changed its output route to: analog-output
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:98	device alsa_card.usb-Samson_Technologies_Samson_Q2U_Microphone-00 has changed its input route to: analog-input-mic
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:130	device alsa_card.usb-Samson_Technologies_Samson_Q2U_Microphone-00 has changed its output route to: analog-output-speaker
(easyeffects:9952): easyeffects-DEBUG: 11:02:39.425: 	application.cpp:150	output autoloading: the target node name does not match the output device name
(easyeffects:9952): easyeffects-DEBUG: 11:02:50.096: 	stream_output_effects.cpp:159	No app linked to our device wants to play. Unlinking our filters.
(easyeffects:9952): easyeffects-DEBUG: 11:02:50.096: 	stream_output_effects.cpp:317	disconnecting the equalizer filter from PipeWire
(easyeffects:9952): easyeffects-DEBUG: 11:02:50.096: 	pipe_manager.cpp:213	 112 ee_soe_equalizer has been removed
(easyeffects:9952): easyeffects-DEBUG: 11:02:50.097: 	stream_input_effects.cpp:165	No app linked to our device wants to play. Unlinking our filters`


No GTK warning. if I click the "Import Preset" buttons while in debug mode, also nada.

**Comment by wwmm** [comment]
>No GTK warning. if I click the "Import Preset" buttons while in debug mode, also nada.

Very strange. There isn't much done on our side to build the dialog window. It is almost on the level of "Hey gtk show a dialog window for me". So either the button is ignoring mouse clicks. What is very unlikely. Or gtk is failing slently.

Are the other dialog windows working? For example the one to import presets or the one in the convolver to import impulse response files.

**Comment by wwmm** [comment]
Is this happening both on wayland and on xorg?

**Comment by m2thay** [comment]
> Is this happening both on wayland and on xorg?

I installed KDE Plasma to see if X11 is the culprit, as I am on Qtile X11 and I'm having some issues getting the Qtile Wayland frontend to behave as intended.

This does not happen on either, Kwin X11 or Kwin Wayland. Buttons all work as intended. Changing over to Qtile none of the buttons work. Including the convoler import impulse"I'll go ask in the Qtile Discord server for some more information on what could be causing this.

**Comment by wwmm** [comment]
>This does not happen on either, Kwin X11 or Kwin Wayland. Buttons all work as intended. Changing over to Qtile none of the buttons work. Including the convolver "import impulse" button.

I wonder why. Maybe it is related to the `xdg-desktop-portal` package. Ask Qtile X11 developers which one you should install. For gnome there is `xdg-desktop-portal-gnome` and ` xdg-desktop-portal-gtk` and for KDE `xdg-desktop-portal-kde`. Maybe if you install one of these the dialogs work.

**Comment by m2thay** [comment]
Upgraded Qtile from stable to -git and updated all system packages (didn't update for around 5 days), all works now. 

Here is the list of upgraded packages: https://pastebin.com/JdLsVAt8

None with GTK in the name, so I assume it was something else.

Thanks for the help!

**Comment by tfriedel** [comment]
I ran into the same issue with scroll (a swaywm fork). 

Update: installing xdg-desktop-portal-gnome, xdg-desktop-portal-gtk, xdg-desktop-portal-wlr fixed it. I had to log out and back in. 

Update:
hmm now it stopped working again. Not sure why.
