### ISSUE TITLE
Launching Easy Effects (Failed)

### ISSUE THREAD

**Issue by wereretot** [wwmm/easyeffects#2896]
### EasyEffects Version

Cannot Launch

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro

### Describe the bug

Unable to launch Easy Effects at all. Nothing happens and then a few seconds later this error occurs: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken".

### Expected Behavior

I expect the program to launch

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(easyeffects:1371970): Adwaita-WARNING **: 21:24:07.200: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
```
</details>

### Additional Information

I've been unable to use EasyEffects since I migrated from PopOS/ubuntu.

**Comment by wwmm** [comment]
You log is incomplete. Kill EasyEffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`.

**Comment by wereretot** [comment]
> You log is incomplete. Kill EasyEffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`.

 G_MESSAGES_DEBUG=easyeffects easyeffects                                                                                                     ✔ 
(process:193618): easyeffects-DEBUG: 21:52:39.997:      easyeffects.cpp:35      easyeffects version: 7.1.3
(process:193618): easyeffects-DEBUG: 21:52:39.997:      easyeffects.cpp:45      locale directory: /usr/share/locale
(easyeffects:193618): easyeffects-DEBUG: 21:52:39.998:  presets_manager.cpp:162 user presets directory already exists: /home/rexommendation/.config/easyeffects/
(easyeffects:193618): easyeffects-DEBUG: 21:52:39.998:  presets_manager.cpp:162 user presets directory already exists: /home/rexommendation/.config/easyeffects/input
(easyeffects:193618): easyeffects-DEBUG: 21:52:39.998:  presets_manager.cpp:162 user presets directory already exists: /home/rexommendation/.config/easyeffects/output
(easyeffects:193618): easyeffects-DEBUG: 21:52:39.999:  presets_manager.cpp:162 user presets directory already exists: /home/rexommendation/.config/easyeffects/autoload/input
(easyeffects:193618): easyeffects-DEBUG: 21:52:39.999:  presets_manager.cpp:162 user presets directory already exists: /home/rexommendation/.config/easyeffects/autoload/output

(easyeffects:193618): Adwaita-WARNING **: 21:52:40.089: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
(easyeffects:193618): easyeffects-DEBUG: 21:52:40.121:  pipe_manager.cpp:1429   compiled with PipeWire: 0.3.84
(easyeffects:193618): easyeffects-DEBUG: 21:52:40.121:  pipe_manager.cpp:1430   linked to PipeWire: 1.0.0
(easyeffects:193618): easyeffects-DEBUG: 21:52:40.124:  pipe_manager.cpp:1400   core version: 1.0.0
(easyeffects:193618): easyeffects-DEBUG: 21:52:40.124:  pipe_manager.cpp:1401   core name: pipewire-0
(easyeffects:193618): easyeffects-DEBUG: 21:52:40.124:  pipe_manager.cpp:1312   found metadata: settings

**Comment by wwmm** [comment]
>pipe_manager.cpp:1312 found metadata: settings

There should be a `default` metadata too. For reasons that are related to how distribution package pipewire the code that provides this metadata is inside the package `pipewire-pulse`. You probably do not have it installed. What means your system is probably still using Pulseaudio.

**Comment by wereretot** [comment]
> > pipe_manager.cpp:1312 found metadata: settings
> 
> There should be a `default` metadata too. For reasons that are related to how Linux distributions package pipewire the code that provides this metadata is inside the package `pipewire-pulse`. You probably do not have it installed. What means your system is probably still using Pulseaudio.

Yeah, I noticed that when I suspended pulseaudio which was running and audio halted. How do I fix it?

**Comment by wereretot** [comment]
I got it working by completely removing my pulseaudio and related libraries. Thank you.
