### ISSUE TITLE
The software required for the Equalizador effect, "Linux Studio Plugins", is not Installed.

### ISSUE THREAD

**Issue by Luzin7** [wwmm/easyeffects#2897]
### EasyEffects Version

7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

BigLinux based in Manjaro Linux

### Describe the bug

I can't use the equalizer. The app shows me this: 

> The software required for the Equalizador effect, "Linux Studio Plugins", is not Installed. Consider using the Easy Effects Flatpak package or installing the software yourself.

**Comment by vchernin** [comment]
Can you run `flatpak update`? You are running easyeffects 7.1.3 is not the latest version, 7.1.4.

You can restart the app with `flatpak run com.github.wwmm.easyeffects -q`. If the app is restarted and it shows the same issue, please paste the output of `flatpak list | grep -i linuxaudio`

**Comment by Luzin7** [comment]
I've changed my distro. Now I'm using Fedora. Sorry for my disturb.

**Comment by fengints** [comment]
Iam leaving comment here for those who encounters this error

`pamac install lsp-plugins-lv2`

**Comment by progzone122** [comment]
> had this issue now. although EE worked before, so it would be strange for packages to disappear suddenly (see [here](https://github.com/wwmm/easyeffects/issues/1685) also). updated to latest version, killed with `pkill -f easyeffects` and restarted, issue fixed :)

Thank you! Had the same issue and `pkill -f easyeffects` helped!

**Comment by RiceMunchX** [comment]
> Iam leaving comment here for those who encounters this error. It should solve the problem
> 
> `sudo pacman -S lsp-plugins-lv2 fluidsynth mda.lv2`

Absolute legend. Solved for CachyOS.
