### ISSUE TITLE
easyeffects no effects are applied

### ISSUE THREAD

**Issue by checkinindza** [wwmm/easyeffects#2898]
### EasyEffects Version

7.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop_OS! 22.04

### Describe the bug

For example, if I'm playing music on Youtube Music through Firefox, I get no audio, because it defaults to EasyEffects Sink as the default audio device. The only way to fix this is to exclude Firefox in EasyEffects. 

### Expected Behavior

Audio works with effects applied

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

In the EasyEffects settings tab, it says that in GNOME Global settings you shouldn't set EasyEffects Sink as the default output device, so that is what I do. But because of that, no effects apply. What am I doing wrong? I have enabled `Process All Inputs `and `Process All Outputs` in the settings.

**Comment by wwmm** [comment]
>In the EasyEffects settings tab, it says that in GNOME Global settings you shouldn't set EasyEffects Sink as the default output device

That is right. More information in this discussion #1836 

>But because of that, no effects apply. What am I doing wrong? I have enabled Process All Inputs and Process All Outputs in the settings.

Follow step number 3 in this link https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs so we can see the debug output.

**Comment by wwmm** [comment]
>Found this issue post https://github.com/wwmm/easyeffects/issues/2480, so I guess there still isn't a way to solve this?

Unfortunately not. The reason why this happens to some people but not others is still unknown. Aside from the cases where PipeWire dies when resuming from the sleep I have no idea why this could be broken.

As we already have #2480 let's close this issue and keep the discussion there.
