### ISSUE TITLE
Do not open: Linux Mint 21.2 / 21.3 x64 | Intel N100 / Beelink Mini S12 Pro

### ISSUE THREAD

**Issue by deenbee** [wwmm/easyeffects#2911]
My details:

System:
  Kernel: 5.15.0-92-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: AZW product: MINI S v: N/A serial: <superuser required>
  Mobo: AZW model: MINI S v: 10 serial: <superuser required> UEFI: American Megatrends LLC.
    v: ADLNV104 date: 02/06/2023
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard K230 serial: <filter>
    charge: 100% (should be ignored) status: Discharging
CPU:
  Info: quad core model: Intel N100 bits: 64 type: MCP arch: N/A rev: 0 cache: L1: 384 KiB
    L2: 2 MiB L3: 6 MiB
  Speed (MHz): avg: 808 high: 852 min/max: 700/3400 cores: 1: 794 2: 791 3: 852 4: 795
    bogomips: 6451
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel driver: N/A bus-ID: 00:02.0 chip-ID: 8086:46d1
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: vesa unloaded: fbdev,modesetting
    gpu: N/A display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: default res: 1920x1080 size: N/A
  OpenGL: renderer: llvmpipe (LLVM 15.0.7 256 bits) v: 4.5 Mesa 23.0.4-0ubuntu1~22.04.1
    direct render: Yes
Audio:
  Device-1: Intel driver: snd_hda_intel v: kernel bus-ID: 00:1f.3 chip-ID: 8086:54c8
  Sound Server-1: ALSA v: k5.15.0-92-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel driver: N/A port: N/A bus-ID: 00:14.3 chip-ID: 8086:54f0
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 01:00.0 chip-ID: 10ec:8168
  IF: enp1s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel AX201 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 1-10:4 chip-ID: 8087:0026
  Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 588.73 GiB used: 24.34 GiB (4.1%)
  ID-1: /dev/nvme0n1 model: PCIe SSD size: 476.94 GiB speed: 31.6 Gb/s lanes: 4 serial: <filter>
    temp: 40.9 C
  ID-2: /dev/sda vendor: Hikvision model: HS-SSD-C100 120G size: 111.79 GiB speed: 6.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 109.47 GiB used: 24.31 GiB (22.2%) fs: ext4 dev: /dev/sda1
  ID-2: /boot/efi size: 96 MiB used: 32.6 MiB (33.9%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: 55.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2204 apt: 2179 flatpak: 25
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 250 Uptime: 15m Memory: 15.4 GiB used: 2.39 GiB (15.5%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

**Comment by deenbee** [comment]
danubio@danubio-MINI-S:~$ flatpak run com.github.wwmm.easyeffects 
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

**Comment by violetmage** [comment]
Can you share the output of `flatpak info --show-permissions com.github.wwmm.easyeffects` and also `apt list xdg-desktop-portal*`

**Comment by wwmm** [comment]
>flatpak run com.github.wwmm.easyeffects

Run it in debug mode `G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects` so we can see more information.

>libEGL warning: DRI2: failed to authenticate
>MESA: error: ZINK: failed to choose pdev
>libEGL warning: egl: failed to create dri2 screen
>MESA: error: ZINK: failed to choose pdev
>glx: failed to create drisw screen
>failed to load driver: zink

With so many gpu driver errors gtk4 is probably  not going to work. And as a result EasyEffects too.

**Comment by deenbee** [comment]
> G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects

danubio@danubio-MINI-S:~$ G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects
(process:2): easyeffects-DEBUG: 18:53:42.453: 	easyeffects.cpp:35	easyeffects version: 7.1.4
(process:2): easyeffects-DEBUG: 18:53:42.456: 	easyeffects.cpp:45	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 18:53:42.501: 	presets_manager.cpp:162user presets directory already exists: /home/danubio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 18:53:42.501: 	presets_manager.cpp:162user presets directory already exists: /home/danubio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 18:53:42.501: 	presets_manager.cpp:162user presets directory already exists: /home/danubio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 18:53:42.501: 	presets_manager.cpp:162user presets directory already exists: /home/danubio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 18:53:42.501: 	presets_manager.cpp:162user presets directory already exists: /home/danubio/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink
(easyeffects:2): easyeffects-DEBUG: 18:53:43.192: 	pipe_manager.cpp:1481	compiled with PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 18:53:43.192: 	pipe_manager.cpp:1482	linked to PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 18:53:43.208: 	pipe_manager.cpp:1452	core version: 0.3.48
(easyeffects:2): easyeffects-DEBUG: 18:53:43.208: 	pipe_manager.cpp:1453	core name: pipewire-0

**Comment by deenbee** [comment]
> apt list xdg-desktop-portal*

danubio@danubio-MINI-S:~$ apt list xdg-desktop-portal*
Listando... Hecho
xdg-desktop-portal-dev/jammy-updates,jammy-updates 1.14.4-1ubuntu2~22.04.1 all
xdg-desktop-portal-gnome/jammy-updates 42.1-0ubuntu1 amd64
xdg-desktop-portal-gtk/jammy,now 1.14.0-1build1 amd64 [instalado]
xdg-desktop-portal-kde/jammy-updates 5.24.7-0ubuntu0.1 amd64
xdg-desktop-portal-tests/jammy-updates 1.14.4-1ubuntu2~22.04.1 amd64
xdg-desktop-portal-wlr/jammy 0.5.0-3 amd64
xdg-desktop-portal-xapp-dbg/virginia 1.0.3+victoria amd64
xdg-desktop-portal-xapp/virginia,now 1.0.3+victoria amd64 [instalado]
xdg-desktop-portal/jammy-updates,now 1.14.4-1ubuntu2~22.04.1 amd64 [instalado]

**Comment by deenbee** [comment]
> Can you share the output of `flatpak info --show-permissions com.github.wwmm.easyeffects` and also `apt list xdg-desktop-portal*`

![Sin título](https://github.com/wwmm/easyeffects/assets/4615556/a75e7c4f-61c0-4366-b78f-67c940fcd0f9)

**Comment by violetmage** [comment]
[This reddit post](https://www.reddit.com/r/Fedora/comments/18ko4iy/mesa_23_update_broken/?rdt=48907) makes me think that this is a bug affecting ZINK.

The behaviour and error messages are consistent with the reports when the system decides to default to ZINK.

More reading required for a remedy in this particular case.

@deenbee What graphics chip/hardware does your system have?

**Comment by wwmm** [comment]
>pipe_manager.cpp:1452 core version: 0.3.48

Besides the obvious gpu driver problems this pipewire version may be too old for EasyEffects.

**Comment by deenbee** [comment]
> [This reddit post](https://www.reddit.com/r/Fedora/comments/18ko4iy/mesa_23_update_broken/?rdt=48907) makes me think that the issue is a bug in mesa somewhere affecting ZINK.
> 
> The behaviour and error messages are consistent with the reports when the system decides to default to ZINK.
> 
> More reading required for a remedy in this particular case.
> 
> @deenbee What graphics chip/hardware does your system have?

Hardware:
Mini PC Beelink, Mini S12 Pro Intel 12th N100

**Comment by deenbee** [comment]
Solved , only open synaptics and then search for: pipewire, then marc these packs on this pictures, and now easyEffeects open

![Sin título](https://github.com/wwmm/easyeffects/assets/4615556/fc18aacd-9cbb-48ff-90c6-982ae697c55f)
