### ISSUE TITLE
Do not open in: Orange Pi Zero 3 / Ubuntu 22.04 LTS / ARM

### ISSUE THREAD

**Issue by deenbee** [wwmm/easyeffects#2916]
### EasyEffects Version

7.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04 / ARM

### Describe the bug

DO NOT OPEN.

### Expected Behavior

Install but do not open

### Debug Log

orangepi@orangepizero3:~$ G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects
(process:2): easyeffects-DEBUG: 17:43:45.808: 	easyeffects.cpp:35	easyeffects version: 7.1.4
(process:2): easyeffects-DEBUG: 17:43:45.825: 	easyeffects.cpp:45	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 17:43:46.388: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 17:43:46.389: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 17:43:46.390: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 17:43:46.390: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 17:43:46.390: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink
(easyeffects:2): easyeffects-DEBUG: 17:43:51.126: 	pipe_manager.cpp:1481	compiled with PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 17:43:51.126: 	pipe_manager.cpp:1482	linked to PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 17:43:51.227: 	pipe_manager.cpp:1452	core version: 0.3.48
(easyeffects:2): easyeffects-DEBUG: 17:43:51.227: 	pipe_manager.cpp:1453	core name: pipewire-0

### Additional Information

orangepi@orangepizero3:~$ flatpak info --show-permissions com.github.wwmm.easyeffects
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-run/pipewire-0:ro;

[Environment]
LADSPA_PATH=/app/lib/ladspa
LV2_PATH=/app/lib/lv2:/app/extensions/Plugins/lv2

orangepi@orangepizero3:~$ apt list xdg-desktop-portal*
Listando... Hecho
xdg-desktop-portal-dev/jammy-updates,jammy-updates 1.14.4-1ubuntu2~22.04.1 all
xdg-desktop-portal-gnome/jammy-updates 42.1-0ubuntu1 arm64
xdg-desktop-portal-gnome/jammy-updates 42.1-0ubuntu1 armhf
xdg-desktop-portal-gtk/jammy 1.14.0-1build1 arm64
xdg-desktop-portal-gtk/jammy 1.14.0-1build1 armhf
xdg-desktop-portal-kde/jammy-updates 5.24.7-0ubuntu0.1 arm64
xdg-desktop-portal-kde/jammy-updates 5.24.7-0ubuntu0.1 armhf
xdg-desktop-portal-tests/jammy-updates 1.14.4-1ubuntu2~22.04.1 arm64
xdg-desktop-portal-tests/jammy-updates 1.14.4-1ubuntu2~22.04.1 armhf
xdg-desktop-portal-wlr/jammy 0.5.0-3 arm64
xdg-desktop-portal-wlr/jammy 0.5.0-3 armhf
xdg-desktop-portal/jammy-updates 1.14.4-1ubuntu2~22.04.1 arm64
xdg-desktop-portal/jammy-updates 1.14.4-1ubuntu2~22.04.1 armhf

orangepi@orangepizero3:~$ G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects
(process:2): easyeffects-DEBUG: 17:43:45.808: 	easyeffects.cpp:35	easyeffects version: 7.1.4
(process:2): easyeffects-DEBUG: 17:43:45.825: 	easyeffects.cpp:45	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 17:43:46.388: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 17:43:46.389: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 17:43:46.390: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 17:43:46.390: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 17:43:46.390: 	presets_manager.cpp:162	user presets directory already exists: /home/orangepi/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink
(easyeffects:2): easyeffects-DEBUG: 17:43:51.126: 	pipe_manager.cpp:1481	compiled with PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 17:43:51.126: 	pipe_manager.cpp:1482	linked to PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 17:43:51.227: 	pipe_manager.cpp:1452	core version: 0.3.48
(easyeffects:2): easyeffects-DEBUG: 17:43:51.227: 	pipe_manager.cpp:1453	core name: pipewire-0

orangepi@orangepizero3:~$ inxi -F
System:
  Host: orangepizero3 Kernel: 6.1.31-sun50iw9 aarch64 bits: 64
    Desktop: Xfce 4.16.0 Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Machine:
  Type: ARM System: OrangePi Zero3 details: N/A serial: 33802000a6cf6926
CPU:
  Info: quad core model: N/A variant: cortex-a53 bits: 64 type: MCP
  Speed (MHz): avg: 1512 min/max: 480/1512 cores: 1: 1512 2: 1512 3: 1512
    4: 1512
Graphics:
  Device-1: sun50i-h616-dw-hdmi driver: sun8i_dw_hdmi v: N/A
  Device-2: sun50i-h6-display-engine driver: sun4i_drm v: N/A
  Device-3: mali-bifrost driver: N/A
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev gpu: sun8i_dw_hdmi,sun4i_drm resolution: 1920x1080~60Hz
  OpenGL: renderer: llvmpipe (LLVM 15.0.7 128 bits)
    v: 4.5 Mesa 23.0.4-0ubuntu1~22.04.1
Audio:
  Device-1: sunxi-snd-plat-ahub_dam driver: sunxi_snd_plat_ahub_dam
  Device-2: sun50i-h616-dw-hdmi driver: sun8i_dw_hdmi
  Device-3: sunxi-snd-mach driver: sunxi_snd_mach
  Device-4: sunxi-snd-plat-ahub driver: sunxi_snd_plat_ahub
  Device-5: sunxi-snd-mach driver: sunxi_snd_mach
  Sound Server-1: ALSA v: k6.1.31-sun50iw9 running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: sun50i-h616-emac0 driver: dwmac_sun8i
  IF: eth0 state: up speed: 1000 Mbps duplex: full mac: 02:00:a6:cf:69:26
  Device-2: mmc-pwrseq-simple driver: pwrseq_simple
  Device-3: sun50i-h616-emac driver: N/A
  IF: eth0 state: up speed: 1000 Mbps duplex: full mac: 02:00:a6:cf:69:26
  IF-ID-1: wlan0 state: up mac: 7c:7b:39:69:41:6f
Drives:
  Local Storage: total: 235.73 GiB used: 170.61 GiB (72.4%)
  ID-1: /dev/mmcblk0 model: SD128 size: 116.48 GiB
  ID-2: /dev/sda type: USB vendor: SanDisk model: ExtremePro
    size: 119.24 GiB
Partition:
  ID-1: / size: 114.57 GiB used: 80.84 GiB (70.6%) fs: ext4
    dev: /dev/mmcblk0p1
  ID-2: /var/log size: 46.8 MiB used: 8.1 MiB (17.3%) fs: ext4
    dev: /dev/zram1
Swap:
  ID-1: swap-1 type: zram size: 1.92 GiB used: 4.2 MiB (0.2%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 59.1 C mobo: N/A
  Fan Speeds (RPM): N/A
Info:
  Processes: 213 Uptime: 23m Memory: 3.84 GiB used: 1.15 GiB (30.0%)
  Shell: Bash inxi: 3.3.13

**Comment by wwmm** [comment]
>pipe_manager.cpp:1452 core version: 0.3.48

This pipewire version is too old for EasyEffects. Try to install a more recent release.

**Comment by deenbee** [comment]
> > pipe_manager.cpp:1452 core version: 0.3.48
> 
> This pipewire version is too old for EasyEffects. Try to install a more recent release.

how to update ?

**Comment by wwmm** [comment]
>how to update ?

As I use Arch Linux I do not know the step by step by based on some Ubuntu users posts there are PPA repositories providing an updated PipeWire release. The question is if this is also available for the ARM architecture.

**Comment by deenbee** [comment]
> > how to update ?
> 
> As I use Arch Linux I do not know the step by step by based on some Ubuntu users posts there are PPA repositories providing an updated PipeWire release. The question is if this is also available for the ARM architecture.

https://launchpad.net/ubuntu/+source/pipewire

**Comment by deenbee** [comment]
> > how to update ?
> 
> As I use Arch Linux I do not know the step by step by based on some Ubuntu users posts there are PPA repositories providing an updated PipeWire release. The question is if this is also available for the ARM architecture.

the question is , if work with eassyEffects runing on flatpak ? pipewire update like out of flatpak ?

**Comment by wwmm** [comment]
>the question is , if work with eassyEffects runing on flatpak ? pipewire update like out of flatpak ?

It will. Some Ubuntu users have fixed problems through PipeWire updates even using the Flatpak package.

**Comment by violetmage** [comment]
Also, if you are not required to use ubuntu 22.04, it will probably be easier to simply upgrade to 23.10 for now and then 24.04 when it comes out in April.

The newer versions might even have fixed this ZINK/mesa bug...

**Comment by deenbee** [comment]
> Also, if you are not required to use ubuntu 22.04, it will probably be easier to simply upgrade to 23.10 for now and then 24.04 when it comes out in April.
> 
> The newer versions might even have fixed this ZINK/mesa bug...

how to upgrade ? the 23.10 I think is not available for arm devices

**Comment by wwmm** [comment]
>how to upgrade ? the 23.10 I think is not available for arm devices

I have no idea. Is there a forum for Ubuntu ARM users somewhere? If yes it is probably better to ask for help there.

**Comment by deenbee** [comment]
> > how to upgrade ? the 23.10 I think is not available for arm devices
> 
> I have no idea. Is there a forum for Ubuntu ARM users somewhere? If yes it is probably better to ask for help there.

In my another x64 pc with Linux mint 21.3 do not open too 😒😒

**Comment by violetmage** [comment]
Does this happen only for easyeffects, or do you get the same graphics errors for other flatpaks on the gnome-44 runtime?

Also, [ubuntu server for arm page](https://ubuntu.com/download/server/arm)

**Comment by deenbee** [comment]
Solved !! only install these select synaptics pipewires and work, but prefer use pulseEffects the cpu is hot ussing easyeffects

![Captura de pantalla_2024-02-10_20-21-54](https://github.com/wwmm/easyeffects/assets/4615556/110e1108-910c-4356-8136-c9834fd55a68)

**Comment by wwmm** [comment]
>but prefer use pulseEffects the cpu is hot using easyeffects

PipeWire dynamically adjusts the audio latency. But in some systems it may choose that are too low and put more pressure on the CPU. The command `pw-top` helps to see what PipeWire is doing to the latency.
