### ISSUE TITLE
Feature Request: Enable/disable effects per device

### ISSUE THREAD

**Issue by binarynoise** [wwmm/easyeffects#2923]
I have a lot of common stuff (like compressor) and an EQ for each output (sound system, headphones, ...).
Sometimes, I need to tinker around with the common filters, but edits get discarded instead of propagated to the other presets.
The preset feature seems to replace the full set of effects.

What really would help if I could just enable/disable different elements based on which output device is active, like with EqualizerAPO on Windows, and the other elements stay unaffected from the device change.

**Comment by wwmm** [comment]
>What really would help if I could just enable/disable different elements based on which output device is active, like with EqualizerAPO on Windows, and the other elements stay unaffected from the device change.

I can see why you want this but it is hard to justify the amount of work and code change this is going to require. And besides the fact it is not clear if there are many people needing this level of granularity we would also have to keep the current behavior for all the people that probably do not need this.
