### ISSUE TITLE
Text not translated in message dialogs for errors in preset loading

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2934]
As explained in #2932, the text cannot be translated in the message dialogs shown when an error occurs in the preset loading stage.

![Schermata del 2024-02-24 18-45-43](https://github.com/wwmm/easyeffects/assets/25790525/d5ab42fa-0134-407f-b0d0-dde484774382)

![Schermata del 2024-02-24 18-47-51](https://github.com/wwmm/easyeffects/assets/25790525/7047ec94-fcda-4e8e-bd03-5cbdf8caf1bb)

I don't understand why. @wwmm any thoughts?

**Comment by wwmm** [comment]
>I don't understand why. @wwmm any thoughts?

I am suspecting the attempt to concatenate to a `_()`. But I am not 100% sure this is the cause.

**Comment by wwmm** [comment]
Wait... So the whole dialog is not translated? I thought it was only at the place where the following is done

```
preset_load_error.emit(_("Preset Not Loaded Correctly"),
                             plugin_translated + _("One or More Parameters Have a Wrong Format"));
```

**Comment by Digitalone1** [comment]
@wwmm yes, it's not translated at all, also the first string which is not concatenated.

```c++
preset_load_error.emit(_("Preset Not Loaded Correctly"),
                             plugin_translated + _("One or More Parameters Have a Wrong Format"));
```

Meanwhile this is working in `missing_plugin_box`:

```c++
auto format_descr =
        fmt::runtime(_("The software required for the {} effect, \"{}\", is not installed. Consider using the Easy "
                       "Effects Flatpak package or installing the software yourself."));
```

**Comment by wwmm** [comment]
Ok. I've looked at `POTFILES.in` and `presets_manager.cpp` is not there. That is probably the reason.

**Comment by Digitalone1** [comment]
Nice, I'll wait for Weblate to make a PR and test them on my system. This could be closed.
