### ISSUE TITLE
Changing Filter frequency on the fly is broken

### ISSUE THREAD

**Issue by LebedevRI** [wwmm/easyeffects#2936]
### EasyEffects Version

7.1.4

### What package are you using?

Other (specify below)

### Distribution

debian unstable

### Describe the bug

**Warning: disconnect headphones/etc when trying to reproduce!**

1. Make sure EE is not already running
2. Start EE
3. Load some preset that contains a (disabled) Filter (High-pass, LRX x16 @ 100Hz)
4. Start audio playback (play youtube video)
5. Enable Filter
6. **MAKE SURE THAT HEADPHONES ARE DISCONNECTED !!!**
7. Change frequency from 100Hz to 200Hz

What happens for me, is the Filter's right channel as-if gets disconnected:
![image](https://github.com/wwmm/easyeffects/assets/88600/d087e76b-087a-48c6-8362-34889eb9788d)
It's rather reproducible for me, but let me know if it doesn't for you.

Sometimes random loud garbage noise is outputted, too.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by LebedevRI** [comment]
It kinda looks like LSP filter produces garbage, and pipewire disconnects the channel,
because disabling-enabling module does nothing, resetting it does nothing,
only fully killing EE helps. Let me try to get PW graphs...

**Comment by LebedevRI** [comment]
initial playback: [pw-dump.0.json.txt](https://github.com/wwmm/easyeffects/files/14394695/pw-dump.0.json.txt)
enabling filter, all good: [pw-dump.1.json.txt](https://github.com/wwmm/easyeffects/files/14394694/pw-dump.1.json.txt)
just changed frequency, bad: [pw-dump.2.json.txt](https://github.com/wwmm/easyeffects/files/14394693/pw-dump.2.json.txt)
disabled filter: [pw-dump.3.json.txt](https://github.com/wwmm/easyeffects/files/14394692/pw-dump.3.json.txt)
re-enabled filter, bad: [pw-dump.4.json.txt](https://github.com/wwmm/easyeffects/files/14394691/pw-dump.4.json.txt)
Let me know if these aren't the droids you're looking for.

CC @sadko4u

**Comment by wwmm** [comment]
>It's rather reproducible for me, but let me know if it doesn't for you.

Nothing unusual happened here at least when using Firefox to play the youtube video. But the "missing" right channel bug is something that unfortunately is not fixed yet on PipeWire's https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3547

**Comment by wwmm** [comment]
>because disabling-enabling module does nothing, resetting it does nothing,
only fully killing EE helps.

Usually activating and deactivating the global bypass fixes it because all the link are destroyed and recreated.

**Comment by LebedevRI** [comment]
I guess i don't understand why i, very consistently and reproducibly,
see that with Filter's Frequency, but not when changing anything else...

**Comment by LebedevRI** [comment]
> > because disabling-enabling module does nothing, resetting it does nothing,
> > only fully killing EE helps.
> 
> Usually activating and deactivating the global bypass fixes it because all the links are destroyed and recreated.

I just tried, it does not help here.

**Comment by wwmm** [comment]
>I guess i don't understand why i, very consistently and reproducibly,
see that with Filter's Frequency, but not when changing anything else...

I've no idea. From time to time this PipeWire bug randomly happens to me. It does not really matter which plugin I use.

>I just tried, it does not help here.

Run `pw-dot` and use `xdot` to see each link state. Sometimes some of them are stuck in the init or paused state. Other than this there is the test PipeWire's developers suggested to do at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3547.

**Comment by wwmm** [comment]
>I guess i don't understand why i, very consistently and reproducibly,
see that with Filter's Frequency, but not when changing anything else...

Is there any change if you use a different sampling rate? As I do not have a reason to use 192 kHz my system is usually at 48 kHz or 44.1 kHz depending on PipeWire's automatic switching.

**Comment by LebedevRI** [comment]
good: [pw-dot.0.dot.txt](https://github.com/wwmm/easyeffects/files/14394723/pw-dot.0.dot.txt)
changed freq: [pw-dot.1.dot.txt](https://github.com/wwmm/easyeffects/files/14394726/pw-dot.1.dot.txt)
activated global bypass: [pw-dot.2.dot.txt](https://github.com/wwmm/easyeffects/files/14394728/pw-dot.2.dot.txt)
disabled global bypass: [pw-dot.3.dot.txt](https://github.com/wwmm/easyeffects/files/14394730/pw-dot.3.dot.txt)

**Comment by LebedevRI** [comment]
^ in those graphs, it's the first filter, `node_id: 166`, and looks like both channels are connected.

**Comment by LebedevRI** [comment]
@sadko4u hi! might it be possible that the Filter does something weird (race condition?)
when being reconfigured on the fly? I've never seen that happen with any other plugin.

**Comment by wwmm** [comment]
>and looks like both channels are connected.

Yes. But the missing channel bug happens even when all the links report to be in the active state. The are cases when somehow it is so severe that the links ends in a broken state. But having them in the active to not guarantee that the bug won't hit.

**Comment by LebedevRI** [comment]
@wwmm thank you for your time!

**Comment by wwmm** [comment]
>thank you for your time!

No problems. I've done some tests with wav files of different sampling rates including above 48 kHz but so far nothing wrong with the filter plugin. I wonder why it is behaving differently on your side.

**Comment by wwmm** [comment]
>MAKE SURE THAT HEADPHONES ARE DISCONNECTED !!!

What did you mean by this exactly? At this moment I am testing using the optical output from my soundcard.

**Comment by LebedevRI** [comment]
FWIW, here's my complete preset: 
[simple.json.txt](https://github.com/wwmm/easyeffects/files/14394759/simple.json.txt)
Maybe that changes things? (you want the first Filter there)

> What did you mean by this exactly?

It's just an ear damage disclaimer, just muting the sound card output is enough.

**Comment by wwmm** [comment]
>FWIW, here's my complete preset:

I tried with it but still nothing wrong when changing the frequency on the fly. At least not at 44.1 kHz.

**Comment by sadko4u** [comment]
> hi! might it be possible that the Filter does something weird (race condition?)

It is prohibited to do any blocking/synchronization stuff in the run() method of the plugin as it breaks real time compatibility of the plugin. All the plugin can do is to reconfigure the filter settings. Your frequency jump can yield the filter to switch into a transition state where each sample triggers filter re-calulation to make the transition smooth and avoid filter from popping/clipping. This may be the reason if you have not enough CPU time for this.

**Comment by wwmm** [comment]
@LebedevRI before doing the test run in a terminal `pw-top` and pay attention to its error column. It takes into account xrun errors. Usually when the combination `cpu + soundcard + drivers + pipewire` is not processing buffers fast enough the error count increases.

**Comment by LebedevRI** [comment]
![image](https://github.com/wwmm/easyeffects/assets/88600/659a4708-eee7-4f15-b42e-ba07574d643f)
![image](https://github.com/wwmm/easyeffects/assets/88600/60e8056f-80e7-4c89-9c92-f78e51b5090b)
^ Even just enabling Filter caused the issue, with no additional xruns.

**Comment by wwmm** [comment]
>Even just enabling Filter caused the issue, with no additional xruns.

Ok. I still think that you are seeing the same PipeWire bug that I and other people see. Why the Filter plugin reliably triggers it on your computer is what I do not understand. This bug is usually very random.

**Comment by LebedevRI** [comment]
Not sure if useful: (recorded without audio)
https://github.com/wwmm/easyeffects/assets/88600/6ef9ec92-59d5-4e6e-9e93-85d71a38e693

**Comment by wwmm** [comment]
>Not sure if useful: (recorded without audio)

Ok. This behavior is not exactly the same as the one caused by the PipeWire bug. The one from PipeWire is random like I talked about before and the right channel audio is missing from the beginning and does not go away "slowly". And there is no sudden jump in signal level. Something different is happening in your case. But I wonder why I can not see this here on my computer.

**Comment by wwmm** [comment]
Is there any difference if you change the frequency in the native window instead of the gtk widget?

**Comment by wwmm** [comment]
>Is there any difference if you change the frequency in the native window instead of the gtk widget?

If possible record a video of it too.

**Comment by wwmm** [comment]
Did you try to use a smaller sampling rate value?

**Comment by LebedevRI** [comment]
> Is there any difference if you change the frequency in the native window instead of the gtk widget?

Also reproduces.
Also, note how right channel goes away when first going 100hz->200hz, but comes back at 200hz->300hz.

https://github.com/wwmm/easyeffects/assets/88600/c11d23c4-ff58-4021-877c-6506ea6ba792

**Comment by sadko4u** [comment]
What's strange is going on with the filter graph?

**Comment by wwmm** [comment]
>What's strange is going on with the filter frequency response graph?

The frequency response and the level meter. The right channel is disappearing and suddenly coming back super strong before going away for good. In a way it feels like it is happening inside the plugin. But somehow I just can't reproduce this on my computer...

**Comment by LebedevRI** [comment]
> In a way it feels like it is happening inside the plugin.

Ack. As i've said, i really think Filter's implementation does something really wrong, and/or has race conditions.

**Comment by wwmm** [comment]
Does the same bug happens with a different sampling rate? At least when  I tried 192 kHz here on my PC nothing unusual happened. But who knows.

**Comment by LebedevRI** [comment]
Moved to https://github.com/lsp-plugins/lsp-plugins/issues/380.
