### ISSUE TITLE
EasyEffects does not start after restarting PipeWire

### ISSUE THREAD

**Issue by FuzzyExpress** [wwmm/easyeffects#2953]
### EasyEffects Version

7.1.4

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Linux SteamDeck desktop mode.

### Describe the bug

Easy Effects does not start at all after running `systemctl --user restart pipewire-pulse.service`.
It provides an error about it timing out or the app didn't send a response
*Node: this issue was also identical when using the Arch AUR version.

### Expected Behavior

Fires up and starts messing with my live audio as normal.

### Debug Log

I don't have logs as I rebooted the deck to fix the problem.

**Comment by wwmm** [comment]
Long story short it is a known issue that is not simple to fix #1447. There are many objects that have to be finished and reloaded in a specific order to deal with audio server restarts. I am not sure about when this will be possible.
