### ISSUE TITLE
Failed to register: Timeout was reached

### ISSUE THREAD

**Issue by jimnong** [wwmm/easyeffects#2961]
### EasyEffects Version

7.1.4-1

### What package are you using?

Arch (easyeffects)

### Distribution

ArchLinux

### Describe the bug

ArchLinux + Wayland + GNOME + pipewire.

I can't run easyeffects GUI.
So I tried to run in terminal.  
But "Failed to register: Timeout was reached" message was pop up.
  
![스크린샷 2024-03-07 13-52-36](https://github.com/wwmm/easyeffects/assets/22017940/66bf118a-7aea-4e0b-b739-153995f08fdf)  
  
[pacmd_info_and_pw-cli.txt](https://github.com/wwmm/easyeffects/files/14519037/pacmd_info_and_pw-cli.txt)
  
I don't know what to do.  
Anybody can help me?  

Thank you!

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by sephid86** [comment]
nice to meet you.

plz. check your pakages.

![ss24-03-07-184557](https://github.com/wwmm/easyeffects/assets/77107998/db3b2602-cdbf-4241-a51b-81164a00d6b8)

**Comment by jimnong** [comment]
Thank you for help. It is nice answer.

I think I have some mistakes.
I'll try again. I'll close this issue.
