### ISSUE TITLE
Please bring back librubberband!

### ISSUE THREAD

**Issue by Brahvim** [wwmm/easyeffects#3001]
The Pitch effect in EasyEffects is currently implemented using Olli Parviainen's SoundTouch library, it seems. The pitch/tempo/rate shifting tool provided using this library is, at the moment, both [a little] inconvenient, and slow at processing. It also produces artefacts - not the output desired.

PulseEffects made use of librubberband, which provided *just* the output desired, with optimal performance. If it is problematic to have only one, I suggest it'd be great to have both!

Thank you for considering my request!
PS Please do tell me why this decision was taken in the first place. Was it a design limitation?

**Comment by wwmm** [comment]
>Please do tell me why this decision was taken in the first place. Was it a design limitation?

There was an issue a long time ago where an user claimed that SoundTouch had better quality. As I do not use the pitch plugin regularly to judge this and no other user said the contrary after the discussion was opened for many months the move was done.

But there was also another reason. Both on PulseEffects and on EasyEffects some users had random crashes with the rubberband library. The only explantion that made sense at the time was it being too slow to run in a realtime thread. The system was killing our process.

Considering that even one of EasyEffects developers suffered with the bug and a solution to fix whatever was not right when using rubberband was never found it does not make sense to bring it back.
