### ISSUE TITLE
Migration to Adaptive Dialogs

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#3008]
In Libadwaita 1.6 some widgets will be deprecated:

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/migrating-to-adaptive-dialogs.html

>Libadwaita 1.5 introduces [AdwDialog](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.Dialog.html) and replacements for [AdwMessageDialog](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.MessageDialog.html), [AdwPreferencesWindow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.PreferencesWindow.html) and [AdwAboutWindow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.AboutWindow.html) that derive from it.
>
> While the old widgets are not deprecated yet, they will be in the next release.
>
> To use [AdwDialog](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.Dialog.html), your parent window must be an instance of either [AdwWindow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.Window.html) or [AdwApplicationWindow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.ApplicationWindow.html). You should migrate to these widgets if you’re still using [GtkWindow](https://docs.gtk.org/gtk4/class.Window.html) or [GtkApplicationWindow](https://docs.gtk.org/gtk4/class.ApplicationWindow.html), respectively.
>
> Stop using window titlebar, instead, create an [AdwToolbarView](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.ToolbarView.html) and add the titlebar to it as a top bar. Set the window child as the toolbar view content. Set the toolbar view as the [AdwWindow:content](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/property.Window.content.html) property on the window.
>
> If you have [GtkSearchBar](https://docs.gtk.org/gtk4/class.SearchBar.html), [GtkActionBar](https://docs.gtk.org/gtk4/class.ActionBar.html) etc in a [GtkBox](https://docs.gtk.org/gtk4/class.Box.html), move them to the toolbar view as well as top/bottom bars respectively.

**Comment by Digitalone1** [comment]
@wwmm if you start the migration, please do it in another branch, otherwise the merge with community presets will be problematic.

**Comment by wwmm** [comment]
> @wwmm if you start the migration, please do it in another branch, otherwise the merge with community presets will be problematic.

Ok. It is unlikely I will have time to look into this before your PR.

**Comment by Digitalone1** [comment]
@wwmm please, pin this issue.

**Comment by Digitalone1** [comment]
@wwmm Since the app will move to Qt, I think this can be unpinned and closed.
