### ISSUE TITLE
[Feature Request] Effects isolated to individual channels (left, right, rear right, sub..)

### ISSUE THREAD

**Issue by blox11** [wwmm/easyeffects#3027]
I would like the ability to add equalization to certain speakers/channels, as not all of them sound the same. Right now it seems possible to do so for stereo, but not surround sound.

**Comment by violetmage** [comment]
Currently, easyeffects only works with stereo audio. There is no support for surround sound in easyeffects.

**Comment by wwmm** [comment]
We already have open issues about surround. So we can close this one. Long story short EasyEffects evolved for stereo processing and some of thep lugins we use do not even make sense in more channels configurations. So the amount of changes necessary to handle surround is quite big. So big I am not sure it will ever happen.
