### ISSUE TITLE
Equalizer band's settings cannot be updated via text input fields

### ISSUE THREAD

**Issue by asardaes** [wwmm/easyeffects#3033]
### EasyEffects Version

7.1.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I am only using the Equalizer effect. If I click on the cog above one of the bands and try to change frequency or quality with the text input field, it seems the new values are not really applied, the UI doesn't update to show those new values, and if I then try using the `-` or `+` buttons, the setting first goes back to the previous state and then applies the decrement/increment (that is to say, the buttons actually apply changes, only the changes from the input fields are ignored).

I tried looking at the DEBUG logs but nothing is logged for these changes.

This must be somewhat recent since I created a new EQ preset like 2 months ago and everything was working fine at the time. 

### Expected Behavior

Changing the values via text input fields should apply the values.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:2463): easyeffects-DEBUG: 11:15:25.736: 	easyeffects.cpp:46	easyeffects version: 7.1.6
(process:2463): easyeffects-DEBUG: 11:15:25.738: 	easyeffects.cpp:56	locale directory: /usr/share/locale
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.740: 	presets_manager.cpp:212	user presets directory already exists: /home/user/.config/easyeffects/
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.740: 	presets_manager.cpp:212	user presets directory already exists: /home/user/.config/easyeffects/input
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.740: 	presets_manager.cpp:212	user presets directory already exists: /home/user/.config/easyeffects/output
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.740: 	presets_manager.cpp:212	user presets directory already exists: /home/user/.config/easyeffects/autoload/input
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.740: 	presets_manager.cpp:212	user presets directory already exists: /home/user/.config/easyeffects/autoload/output
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.918: 	pipe_manager.cpp:1534	compiled with PipeWire: 1.0.4
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.918: 	pipe_manager.cpp:1535	linked to PipeWire: 1.0.4
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1505	core version: 1.0.4
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1506	core name: pipewire-0
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: settings
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: schema-sm-settings
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: persistent-sm-settings
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: sm-settings
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: sm-objects
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: default
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: filters
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1417	found metadata: route-settings
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1271	Audio/Sink 53 alsa_output.pci-0000_01_00.1.hdmi-stereo with serial 53 has been added
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1271	Audio/Sink 55 alsa_output.pci-0000_00_1f.3.iec958-stereo with serial 55 has been added
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1271	Audio/Source 56 alsa_input.pci-0000_00_1f.3.analog-stereo with serial 56 has been added
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1271	Audio/Sink 54 alsa_output.usb-Topping_E30-00.HiFi__hw_E30_0__sink with serial 65 has been added
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1271	Audio/Sink 77 easyeffects_sink with serial 165 has been added
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1271	Audio/Source/Virtual 85 easyeffects_source with serial 166 has been added
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1007	new metadata property: 0, default.configured.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.3.iec958-stereo"}
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1007	new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.3.iec958-stereo"}
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1007	new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_output.usb-Topping_E30-00.HiFi__hw_E30_0__sink"}
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.923: 	pipe_manager.cpp:1007	new metadata property: 0, default.video.source, Spa:String:JSON, {"name":"v4l2_input.pci-0000_00_14.0-usb-0_3_1.0"}
'spa_pod_is_array(pod)' failed at /usr/include/spa-0.2/spa/pod/iter.h:319 spa_pod_get_array()
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.924: 	pipe_manager.cpp:1633	easyeffects_sink node successfully retrieved with id 77 and serial 165
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.924: 	pipe_manager.cpp:1638	easyeffects_source node successfully retrieved with id 85 and serial 166
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.930: 	plugin_base.cpp:403	soe: output_level successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.932: 	plugin_base.cpp:403	soe: spectrum successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.981: 	lv2_wrapper.cpp:126	http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.994: 	plugin_base.cpp:403	soe: equalizer successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.994: 	pipe_manager.cpp:1311	easyeffects_sink port 84 is connected to ee_soe_equalizer port 113
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.995: 	pipe_manager.cpp:1311	easyeffects_sink port 76 is connected to ee_soe_equalizer port 112
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.996: 	pipe_manager.cpp:1314	No node with id 90 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.996: 	pipe_manager.cpp:1314	No node with id 90 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.997: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.997: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.998: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:25.999: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.001: 	plugin_base.cpp:403	sie: output_level successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.003: 	plugin_base.cpp:403	sie: spectrum successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.004: 	pipe_manager.cpp:1314	No node with id 100 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.005: 	pipe_manager.cpp:1314	No node with id 100 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.005: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.006: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.006: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.007: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.007: 	stream_output_effects.cpp:349	disconnecting the equalizer filter from PipeWire
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.008: 	pipe_manager.cpp:265	 109 ee_soe_equalizer has been removed
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.011: 	plugin_base.cpp:403	soe: equalizer successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.011: 	pipe_manager.cpp:1311	easyeffects_sink port 84 is connected to ee_soe_equalizer port 122
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.012: 	pipe_manager.cpp:1311	easyeffects_sink port 76 is connected to ee_soe_equalizer port 121
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.012: 	pipe_manager.cpp:1314	No node with id 90 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.012: 	pipe_manager.cpp:1314	No node with id 90 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.013: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.013: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.014: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.014: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.016: 	pipe_manager.cpp:1314	No node with id 100 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.017: 	pipe_manager.cpp:1314	No node with id 100 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.017: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.017: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.018: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.018: 	pipe_manager.cpp:1314	No node with id 120 in our node_map
easyeffects-INFO: 11:15:26.018: 	application.cpp:76	disabling global bypass
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.027: 	application_ui.cpp:109	Icon Theme Arc detected
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.266: 	stream_output_effects.cpp:349	disconnecting the equalizer filter from PipeWire
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.267: 	pipe_manager.cpp:265	 123 ee_soe_equalizer has been removed
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.271: 	plugin_base.cpp:403	soe: equalizer successfully connected to PipeWire graph
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.271: 	pipe_manager.cpp:1311	easyeffects_sink port 84 is connected to ee_soe_equalizer port 114
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.272: 	pipe_manager.cpp:1311	easyeffects_sink port 76 is connected to ee_soe_equalizer port 113
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.272: 	pipe_manager.cpp:1314	No node with id 90 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.273: 	pipe_manager.cpp:1314	No node with id 90 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.273: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.273: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.273: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	pipe_manager.cpp:1314	No node with id 81 in our node_map
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:104	new default output device: alsa_output.pci-0000_00_1f.3.iec958-stereo
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:112	new default input device: alsa_output.usb-Topping_E30-00.HiFi__hw_E30_0__sink
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:156	device alsa_card.pci-0000_01_00.1 has changed its output route to: hdmi-output-0
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:176	output autoloading: the target node name does not match the output device name
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:156	device alsa_card.usb-Topping_E30-00 has changed its output route to: [Out] Headphones
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:176	output autoloading: the target node name does not match the output device name
(easyeffects:2463): easyeffects-DEBUG: 11:15:26.275: 	application.cpp:156	device alsa_card.pci-0000_00_1f.3 has changed its output route to: iec958-stereo-output
(easyeffects:2463): easyeffects-DEBUG: 11:15:36.077: 	stream_output_effects.cpp:183	No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2463): easyeffects-DEBUG: 11:15:36.077: 	stream_output_effects.cpp:349	disconnecting the equalizer filter from PipeWire
(easyeffects:2463): easyeffects-DEBUG: 11:15:36.079: 	pipe_manager.cpp:265	 118 ee_soe_equalizer has been removed
(easyeffects:2463): easyeffects-DEBUG: 11:15:36.085: 	stream_input_effects.cpp:189	No app linked to our device wants to play. Unlinking our filters.
```
</details>

**Comment by wwmm** [comment]
I could not reproduce this issue. While something was playing I opened the equalizer native window and changed the parameters in EE window. I could see changes in the frequency response plot done by the native plugin window. And I could also hear the changes in sound.

**Comment by wwmm** [comment]
It may we worth to attach EE debug output here just in case there is some kind of warning related to gtk or gsettings.

**Comment by asardaes** [comment]
I've attached the logs. Also, I'm not sure we're thinking about the same input fields, I mean these:

![Easy Effects_001](https://github.com/wwmm/easyeffects/assets/7768461/2b76b221-e14b-45db-bd55-bb03df4c7bfe)

**Comment by Digitalone1** [comment]
@asardaes Yes, you're right, I can reproduce on my system. Those spinbuttons are not updating.

**Comment by Digitalone1** [comment]
This happens to all the spinbuttons, not only the ones of the Equalizer. the -/+ buttons updates the gsettings key, but writing inside the text and pressing enter does nothing. This is a huge issue.

**Comment by Digitalone1** [comment]
@wwmm doing some tests, the parse spinbutton input util is working as intended, but the value is still not updated. Should it be a GTK bug?

**Comment by Digitalone1** [comment]
@wwmm Maybe this is the culprit? https://docs.gtk.org/gtk4/signal.SpinButton.activate.html

**Comment by wwmm** [comment]
> I've attached the logs. Also, I'm not sure we're thinking about the same input fields, I mean these:
> 
> ![Easy Effects_001](https://private-user-images.githubusercontent.com/7768461/318407474-2b76b221-e14b-45db-bd55-bb03df4c7bfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTMxMTAsIm5iZiI6MTcxMjAxMjgxMCwicGF0aCI6Ii83NzY4NDYxLzMxODQwNzQ3NC0yYjc2YjIyMS1lMTRiLTQ1ZGItYmQ1NS1iYjAzZGY0YzdiZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMjMwNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVlMWMyYWI5MDZlNGIxOGZhZTQ4ZDhiY2RhODljZTIzYWRjM2M4YWMwNmI4OTA1NDM0OWEyYzcxZTBhMGIxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n6x5X5w9bBIHlucle3ABl5Aa_yqchaW_2K-TLcKrK5A)

That is what I tested. But at the time I used the mouse scroll and the up/down arrows. They are fine. But actually typing is indeed broken somehow....

**Comment by wwmm** [comment]
> @wwmm doing some tests, the parse spinbutton input util is working as intended, but the value is still not updated. Should it be a GTK bug?

At first sight it seems a GTK bug. It is not just the equalizer. I've just saw the same bug in the bass enhancer spinbuttons. So unless our wrapper for the spinbutton is now somehow broken it is a but in gtk.

**Comment by wwmm** [comment]
> > @wwmm doing some tests, the parse spinbutton input util is working as intended, but the value is still not updated. Should it be a GTK bug?
> 
> At first sight it seems a GTK bug. It is not just the equalizer. I've just saw the same bug in the bass enhancer spinbuttons. So unless our wrapper for the spinbutton is now somehow broken it is a bug in gtk.

I removed one of the calls to `prepare_spinbuttons` in the bass enhancer code and the bug happens anyway. So it is not our wrapper doing it. And for some weird reason even using the mouse scroll the value does not seem to be properly updated in `dconf-editor`. Really strange.

**Comment by wwmm** [comment]
I do not see how this bug could be on our side. The last gtk4 update probably broken something in the spinbutton...

**Comment by Digitalone1** [comment]
@wwmm I checked the GTK issue page on Gitlab and this is not reported.

I tried to check other GTK4 apps and the spinbutton is working, but later I realized they are using the AdwSpinRow, not the plain GtkSpinButton.

I wanted to replace an AdwSpinRow in EE to test if it was working but it's very hard because all the signals should be replaced changing typed and functions. I got why you didn't switch to AdwSpinRow.

So should be report this issue to GTK? https://gitlab.gnome.org/GNOME/gtk/-/issues

**Comment by Digitalone1** [comment]
I reported it: https://gitlab.gnome.org/GNOME/gtk/-/issues/6599

**Comment by Digitalone1** [comment]
@wwmm gtk4-demos has a working spinbutton.

This is the callback they are using: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/demos/gtk-demo/spinbutton.c?ref_type=heads#L15-30

I don't see nothing very different from [our implementation](https://github.com/wwmm/easyeffects/blob/master/src/ui_helpers.cpp#L155-L186), except `strtol` which is locale dependent like the stringstream we use and initialized with user locale.

I don't know what to think.

**Comment by Digitalone1** [comment]
@wwmm I attacked a test callback to all spinbuttons in prepare util.

```c++
  g_signal_connect(button, "input", G_CALLBACK(+[](GtkSpinButton* button, gdouble* new_value, gpointer user_data) {
                     // TODO: remove
                     util::warning("INPUT CALLBACK");
                     return parse_spinbutton_input(button, new_value, lower_bound);
                   }),
                   nullptr);

  g_signal_connect(button, "activate", G_CALLBACK(+[](GtkSpinButton* button, gpointer user_data) {
                     // TODO: remove
                     util::warning("ACTIVATE CALLBACK");
                   }),
                   nullptr);
```

Adding a warning also in the input callback I can see that whenever I
1. change the text in the input field and 
2. then press ENTER

**The activate callback is never invoked**. Which is likely the activate signal is not emitted.

The only way to emit the signal is after 
1. pressing a button with the mouse and 
2. then pressing the ENTER key

This invokes the input and then the activate callback, which is totally useless in this context because the formatted text is just the same as before.

Please, test and confirm this behavior. The issue on Gtk Gitlab may be reopened.

**Comment by wwmm** [comment]
>Update: the question is also why gtk-demo is working if they are using the input signal the same way as we do.

Whatever it is the source of the problem it has nothing to do with the callbacks to customize the spinbutton text. Look at the spinbutton for `n-points` in the spectrum preferences window. We do no customization to its text. And still the problem happens there. Open dconf-editor while typing a value in its text field and you will see nothing happens unless the mouse scroll or the arrows are used.

But is indeed curious gtk4-demos is working fine... The only difference at first sight is it not using libadwaita.

On a side note I admit I am getting a little tired of these weird problems and sometimes unsolvable bugs that happens on gtk4 sometimes. I'm seriously considering a move to Qt+QML+Kirigami in the far future... In any case let me do more tests before we go back to that closed issue in the gtk page...

**Comment by wwmm** [comment]
I think I've found the problem. After removing the property
><property name="update-policy">if-valid</property>

The spinbutton is now suddenly behaving as expected. This is bizarre. We have been setting it for years and now it is causing this unexpected behavior.

**Comment by Digitalone1** [comment]
> I'm seriously considering a move to Qt+QML+Kirigami in the far future... 

Qt may raise other issues. And Qt integration in Gnome is bad. Some users complain about the GTK integration in non-Gnome environment, but they don't know about Qt under Gnome. Take a look at qBittorrent, it sucks.

**Comment by wwmm** [comment]
>And Qt integration in Gnome is bad.

Because Gnome has never put much effort if any at all in integrating apps developed on another toolkits. The only reason why gtk apps look somewhat decent in KDE is because of the effort that was put into this on KDE's side. Not because of some magical support implement in GTK/GNOME.

>Qt may raise other issues

As everything in life nothing is perfect. If we look at gtk's side the menu bugs have been happening for years. As well as the one in the gtkLevelBar we had to workaround. At least when using QT the amount of C code on our side would be reduced to mostly the one needed to interact with PipeWire. Dealing with the interface in QML is definitely more pleasant than the approach we have now. And the damned systray support so may users ask for would be there naturally...

In any case for now this is only an idea. I am porting another project of mine from gtk4 to qt/qml/kirigami to see how things go and what exactly are the advantages and disadvantages. Only if things are good there I would attempt anything on EE side.

**Comment by Digitalone1** [comment]
There was a Qt theme QtAdwaita, but the project was abandoned. I gave up on app UI integration because that will never happen totally. 

Even if you integrate GTK apps on Plasma, there will be still Electron apps and other toolkits that you feel out of place. In example, Libre Office, I don't feel it integrated, even when I used Plasma 5 in the past. 

For the system tray I agree with Gnome philosophy and, personally, I don't need it. But I understand who wants it.

Honestly I like the look and feel of Libadwaita and switching to another toolkit seems throwing out all the efforts put in the last years to make EE what it is.

Maybe the best approach was to separate the core part of EE from the UI part so that other UI can be developed by other volunteers. Look at transmission, there are multiple UI, GTK and Qt. Or libmpv used by Celluloid and SmPlayer. 

Maybe EE core would be a service that could be started by systemd and the UI will interoperate on top of it. But that needed to be done from the start years ago. At the moment I think it's better to stay as the things are. 

Anyway, I will make a PR to resolve this issue.

**Comment by wwmm** [comment]
>Even if you integrate GTK apps on Plasma, there will be still Electron apps and other toolkits that you feel out of place. In example, Libre Office, I don't feel it integrated, even when I used Plasma 5 in the past.

For better or worse Electron apps always feels like electron apps wherever they are. At the moment vscode is the only one I use and I do not bother about its looks too much. Be it on gnome or kde. 

Nowadays LibreOffice looks decent enough on both desktops.  It was horrible in the past on both of them but this is not the case anymore. 

>Honestly I like the look and feel of Libadwaita and switching to another toolkit seems throwing out all the efforts put in the last years to make EE what it is.

Although I like it just as much as I like the looks of apps on kde my main reason to use LibAdwaita was the convenience and functionality provided by some of the widgets that only exist in LibAdwaita. But in the last years I have seen gtk developers say things that in the end have the same meaning as "LibAdwaita is intended ONLY for gnome apps. If you are using it is because you do not care about other desktops. If things look bizarre or break on other desktops it is your fault for using it instead of pure gtk...". Although I respect their decision it is not like LibAdwaita is only a theme on top of gtk that can be replaced at any time. There are useful widgets that you can only have if you use it. Replicating some of its functionality in pure gtk is a pain. I tried it in the past and eventually I gave up...  The implicit idea that if we use it is because we only care about gnome has been bothering me for a while...

**Comment by Digitalone1** [comment]
@wwmm I understand. Anyway I have to say that it's somewhat similar for KDE apps. In example, I used Kate in the past which is a great text editor, but I gave up using it because if I wanted to install it, I should download half of Plasma Desktop dependencies which I feel useless on my Gnome. Don't know if things have changed now, but that was the case years ago, considering also that Gnome had plenty of working apps on Wayland while KDE apps were defaulting on XWayland and I didn't like that either.

**Comment by wwmm** [comment]
>considering also that Gnome had plenty of working apps on Wayland while KDE apps were defaulting on XWayland and I didn't like that either.

That was true on plasma 5. Wayland is default on plasma 6 and at least on my desktop it is as stable as gnome wayland is on it.

**Comment by Digitalone1** [comment]
@wwmm I was reading r/linuxaudio and discovered [this](https://www.reddit.com/r/linuxaudio/comments/1bx7uyy/easyeffectssystray_a_simple_de_agnostic_system/). Might be worth linking it inside the README.

**Comment by wwmm** [comment]
> @wwmm I was reading r/linuxaudio and discovered [this](https://www.reddit.com/r/linuxaudio/comments/1bx7uyy/easyeffectssystray_a_simple_de_agnostic_system/). Might be worth linking it inside the README.

Or maybe in the wiki like the author of this gnome extension did https://github.com/wwmm/easyeffects/wiki/Preset-Selector-GNOME-Extension. I fear that if we put inside our readme some people may think we are somehow involved in its development or that is something officially supported that should always work.

**Comment by vrnvorona** [comment]
So i have 4.1.6 and buttons don't work on Enter or Tab on Ubuntu 24.04

Is this not merged or another issue?

**Comment by wwmm** [comment]
>So i have 4.1.6

Is this the gtk4 version or EasyEffects version? In any case the fix for this bug was applied to our sources a few months ago.

**Comment by servimo** [comment]
> @wwmm I was reading r/linuxaudio and discovered [this](https://www.reddit.com/r/linuxaudio/comments/1bx7uyy/easyeffectssystray_a_simple_de_agnostic_system/). Might be worth linking it inside the README.

arch Linux and derivates should not use "pip" to install python packages, can be problematic.

**Comment by vrnvorona** [comment]
> > So i have 4.1.6
> 
> Is this the gtk4 version or EasyEffects version? In any case the fix for this bug was applied to our sources a few months ago.

EasyEffects

I am quite new to Linux ecosystem, so IDK what else I need to do other than install from apt. Do I need to update gtk4 as well (somehow)?

**Comment by Digitalone1** [comment]
> ### EasyEffects Version
> 7.1.6

@vrnvorona `7.1.7` version has the fix. Since your distribution may not have the latest update yet, the best thing you can do is to uninstall it and install from Flatpak.

The only issue of the Flatpak version is the Equalizer reset button which takes a while to apply, but apart from that, every thing should work as expected.

**Comment by dsdante** [comment]
Any idea when to expect 7.1.7 in Ubuntu 24.04 repos? I'll probably wait out without Flatpak.

**Comment by moritzderallerechte** [comment]
This is still (or again) an issue
