### ISSUE TITLE
text fields do not work

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [wwmm/easyeffects#3051]
### EasyEffects Version

7.1.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

when trying to use the text input fields (e.g. equalizer frequency), the text is ignored, as the value stays the same and trying to increase or decrease it changes it from the initial value, rather than the one you put in.

### Expected Behavior

The program to use input data when put in the input fields

### Debug Log

_Not applicable_

### Additional Information

_None_

**Comment by wwmm** [comment]
Probably the same as #3033. It is a gtk4 bug that for which a workaround has already been applied to our master branch. Try to install the AUR package. It builds from our master branch. If this does not fix the problem feel free to reopen this issue.
