### ISSUE TITLE
pipe_manager.cpp logs errors

### ISSUE THREAD

**Issue by worldowner** [wwmm/easyeffects#3076]
### EasyEffects Version

7.1.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Errors are logged:
```
Apr 17 12:17:59 abcd easyeffects[1388]: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Apr 17 12:23:55 abcd easyeffects[1388]:         pipe_manager.cpp:1481        Remote error res: No such file or directory
Apr 17 12:23:55 abcd easyeffects[1388]:         pipe_manager.cpp:1482        Remote error message: unknown resource 39 op:2
Apr 17 12:23:55 abcd easyeffects[1388]:         pipe_manager.cpp:1481        Remote error res: No such file or directory
Apr 17 12:23:55 abcd easyeffects[1388]:         pipe_manager.cpp:1482        Remote error message: unknown resource 39 op:2
```

### Expected Behavior

Errors do not occur.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
All these warnings are harmless. It just happens that PipeWire sometimes sends some useless error messages in the same callback that sometimes important error messages can come.

**Comment by worldowner** [comment]
Ok, thank you for information. In fact I'm unable to reproduce it. I only found these errors by accident while looking for something else. Easyeffects seemed to work fine but I wanted to report it in case it matters.
