### ISSUE TITLE
Feature Request: support application allowlist

### ISSUE THREAD

**Issue by emansom** [wwmm/easyeffects#3095]
I'd like EasyEffects to only apply effects to Firefox and Celluloid and ignore all else.

As in current configuration I have to blocklist all games to optimize for latency, which gets rather tedious.

**Comment by wwmm** [comment]
That has been discussed a few times in the past. It is not how the app is designed to be used. If you want effects only for firefox and celluloid what has to be done is disabling `Process All Output Streams` in EasyEffects menu and enabling effects for these two apps manually.

WirePlumber already has restoration logic implemented. As long as you always start these apps when EasyEffects is already running and do not set them to manually other devices WirePlumber will remember they were using EasyEffects sink and restore them. There would be no need to manually set them again in EE window. WirePlumber should be able to move them automatically after the first manual selection.
