### ISSUE TITLE
Running EasyEffects as a service without a desktop environment

### ISSUE THREAD

**Issue by road2react** [wwmm/easyeffects#3132]
### EasyEffects Version

7.1.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I'm trying to run EasyEffects as a systemd service. I have the following service config:

```
[Unit]
Description=EasyEffects
After=pipewire-pulse.service
BindsTo=pipewire-pulse.service
PartOf=pipewire-pulse.service

[Service]
Restart=always
ExecStart=/usr/bin/easyeffects --gapplication-service
StartLimitInterval=0

[Install]
WantedBy=default.target
```

If I log in but the desktop environment has not yet started (environment DISPLAY and WAYLAND_DISPLAY unset), I get this error:

```
systemd[2000]: Started EasyEffects.
easyeffects[2029]: Failed to open display
systemd[2000]: easyeffects.service: Main process exited, code=exited, status=1/FAILURE
```

### Expected Behavior

Ideally it should be possible to run EasyEffects as a service even if there is no desktop environment.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:667400): easyeffects-DEBUG: 00:29:51.229:      easyeffects.cpp:46      easyeffects version: 7.1.6
(process:667400): easyeffects-DEBUG: 00:29:51.229:      easyeffects.cpp:56      locale directory: /usr/share/locale
(easyeffects:667400): easyeffects-DEBUG: 00:29:51.230:  presets_manager.cpp:212 user presets directory already exists: /home/user/.config/easyeffects/
(easyeffects:667400): easyeffects-DEBUG: 00:29:51.230:  presets_manager.cpp:212 user presets directory already exists: /home/user/.config/easyeffects/input
(easyeffects:667400): easyeffects-DEBUG: 00:29:51.230:  presets_manager.cpp:212 user presets directory already exists: /home/user/.config/easyeffects/output
(easyeffects:667400): easyeffects-DEBUG: 00:29:51.230:  presets_manager.cpp:212 user presets directory already exists: /home/user/.config/easyeffects/autoload/input
(easyeffects:667400): easyeffects-DEBUG: 00:29:51.230:  presets_manager.cpp:212 user presets directory already exists: /home/user/.config/easyeffects/autoload/output

(easyeffects:667400): Gtk-WARNING **: 00:29:51.234: Failed to open display
```
</details>

**Comment by wwmm** [comment]
>Ideally it should be possible to run EasyEffects as a service even if there is no desktop environment.

It won't work this way. EasyEffects is a gui app. Our "service mode" means just running with the window closed. It is not service in the usual meaning of the word. Doing that would require a complete redesign and a huge amount of work. 

If you really need to run it in a headless installation something on the lines of https://github.com/wwmm/easyeffects/wiki/Headless-Operation will be necessary.
