### ISSUE TITLE
Maximizer: Ceiling changed to Gain

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#3152]
Related to https://github.com/wwmm/easyeffects/commit/39d8713679a0da29e99a6d1f90361629f0b6b112

Looking to this commit: https://github.com/zamaudio/zam-plugins/commit/d84f69b9ad5a3d2c3d6265a64df0c72b34aaf165

It seems the parameter has not been deleted, bug changed to a new name.

**Comment by Digitalone1** [comment]
And the limits are updated from -20 to +20.

**Comment by Digitalone1** [comment]
It seems just the **input gain**, which we already have. Maybe it's not very useful to expose it. @wwmm do you see it's doing something special into the code which it's worth to expose it?

**Comment by wwmm** [comment]
>It seems the parameter has not been deleted, bug changed to a new name.

It is weird to just be a change in name. I mean from being the maximum output level of the limiter function provided by maximizer to suddenly become an input gain is strange. It seems to me that the old functionality provided by the ceiling parameter is now merged to the threshold.

>Maybe it's not very useful to expose it

I agree. I do not see a reason to expose it.

**Comment by Digitalone1** [comment]
I have to say that now it's more straightf easier to understand. Before it has a weird

**Comment by Digitalone1** [comment]
I have to say that now it's more straightforward to understand. Before it had a weird meaning with those two parameters. I close this.
