### ISSUE TITLE
Delay stopped working this Morning

### ISSUE THREAD

**Issue by zono50** [wwmm/easyeffects#3153]
### EasyEffects Version

7.1.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I was not getting any audio through my easy effects client,  disabled each plugin one by one, and as soon as I disabled the delay plugin, it started pushing audio through again. Been working fine for weeks and haven't changed any settings on the device.

### Expected Behavior

Expected audio to stream with delay enabled

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:9102): easyeffects-DEBUG: 10:14:15.762:        easyeffects.cpp:46      easyeffects version: 7.1.6
(process:9102): easyeffects-DEBUG: 10:14:15.762:        easyeffects.cpp:56      locale directory: /usr/share/locale
(easyeffects:9102): GLib-GIO-DEBUG: 10:14:15.763: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(easyeffects:9102): dconf-DEBUG: 10:14:15.763: watch_fast: "/com/github/wwmm/easyeffects/" (establishing: 0, active: 0)
(easyeffects:9102): dconf-DEBUG: 10:14:15.763: watch_fast: "/com/github/wwmm/easyeffects/" (establishing: 1, active: 0)
(easyeffects:9102): dconf-DEBUG: 10:14:15.763: watch_fast: "/com/github/wwmm/easyeffects/streamoutputs/" (establishing: 0, active: 0)
(easyeffects:9102): dconf-DEBUG: 10:14:15.763: watch_fast: "/com/github/wwmm/easyeffects/streaminputs/" (establishing: 0, active: 0)
(easyeffects:9102): easyeffects-DEBUG: 10:14:15.763:    presets_manager.cpp:212 user presets directory already exists: /home/zono50/.config/easyeffects/
(easyeffects:9102): easyeffects-DEBUG: 10:14:15.763:    presets_manager.cpp:212 user presets directory already exists: /home/zono50/.config/easyeffects/input
(easyeffects:9102): easyeffects-DEBUG: 10:14:15.763:    presets_manager.cpp:212 user presets directory already exists: /home/zono50/.config/easyeffects/outp>
(easyeffects:9102): easyeffects-DEBUG: 10:14:15.763:    presets_manager.cpp:212 user presets directory already exists: /home/zono50/.config/easyeffects/auto>
(easyeffects:9102): easyeffects-DEBUG: 10:14:15.763:    presets_manager.cpp:212 user presets directory already exists: /home/zono50/.config/easyeffects/auto>
(easyeffects:9102): GLib-GIO-DEBUG: 10:14:15.763: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(easyeffects:9102): GLib-GIO-DEBUG: 10:14:15.763: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(easyeffects:9102): dconf-DEBUG: 10:14:15.764: watch_established: "/com/github/wwmm/easyeffects/" (establishing: 2)
(easyeffects:9102): dconf-DEBUG: 10:14:15.764: watch_established: "/com/github/wwmm/easyeffects/streamoutputs/" (establishing: 1)
(easyeffects:9102): dconf-DEBUG: 10:14:15.764: watch_established: "/com/github/wwmm/easyeffects/streaminputs/" (establishing: 1)
(easyeffects:9102): dconf-DEBUG: 10:14:16.311: sync
(easyeffects:9102): easyeffects-DEBUG: 10:14:16.311:    easyeffects.cpp:71      Exitting the main function with status: 1
```
</details>

**Comment by wwmm** [comment]
It is the same thing on my computer. It started after the last update to the LSP package. I wonder if something changed upstream in the delay plugin and some kind of change is needed on my side. The other lsp plugins we use are fine. Any suggestions @sadko4u ?

**Comment by wwmm** [comment]
If I open the plugin native window and use its "bypass" button sound passes through it. It is almost like the plugin is replacing all the buffers by silence.

**Comment by wwmm** [comment]
>Also, is there a reason that we're still on the 1.1.x versions of lsp, instead of the 1.2.x versions?

Oops. My mistake. The version I had in mind was `1.2.16`.

**Comment by violetmage** [comment]
Ok, found this in the [1.2.16 release notes](https://github.com/lsp-plugins/lsp-plugins/commit/cccac562fc9f7761ea962063ee1ecb15dc0d33e4):

> * Implemented Dry/Wet balance knob for the following plugin series:
>  * Artistic Delay;
>  * Beat Breather;
>  * Compensation Delay;
>  * Flanger;
>  * Impulse Responses;
>  * Impulse Reverb;
>  * Room Builder;
>  * Sampler;
>  * Multisampler;
>  * Slap-Back delay.

Maybe the new dry-wet parameters are affecting the audio.

**Comment by sadko4u** [comment]
@wwmm if you bind parameters by the index, then it can be a problem because the parameter was inserted somewhere in the middle. What delay do you use in EasyEffects?

**Comment by zono50** [comment]
I'm using the regular delay that comes with it. I had it right before the second to last plugin

**Comment by wwmm** [comment]
> @wwmm if you bind parameters by the index, then it can be a problem because the parameter was inserted somewhere in the middle. What delay do you use in EasyEffects?

Hello @sadko4u ! We use this one https://lsp-plug.in/?page=manuals&section=comp_delay_x2_stereo. And the port binding is done through their names https://github.com/wwmm/easyeffects/blob/175121010ba271001e7343c759cb8116c271e035/src/delay.cpp#L55 like we do for all the others.

**Comment by violetmage** [comment]
@sadko4u The plugin that easyeffects calls "Delay" is the [lsp-comp-delay 2x stereo](http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo) plugin.

**Comment by wwmm** [comment]
> @wwmm if you bind parameters by the index, then it can be a problem because the parameter was inserted somewhere in the middle. What delay do you use in EasyEffects?

Wait... I think you mean the input and output ports... Let me check them...

**Comment by wwmm** [comment]
> @wwmm if you bind parameters by the index, then it can be a problem because the parameter was inserted somewhere in the middle. What delay do you use in EasyEffects?

Ok. When calling `lilv_instance_connect_port` to set the input and output ports for the audio buffers we do use index https://github.com/wwmm/easyeffects/blob/175121010ba271001e7343c759cb8116c271e035/src/lv2_wrapper.cpp#L299. At the time I implemented this wrapper I saw people doing it this way so I did not put much though about it. Is there a generic way to bind them by name as the control ports?

**Comment by sadko4u** [comment]
The audio port has the same numbering space to the parameters. That means, in LV2 the audio port IS a parameter but points to the chunk of floats instead of one float. I think you can just repeat the same mechanism as with parameters.

**Comment by wwmm** [comment]
> The audio port has the same numbering space to the parameters. That means, in LV2 the audio port IS a parameter but points to the chunk of floats instead of one float. I think you can just repeat the same mechanism as with parameters.

Let me see if I understood. We iterate over the ports here https://github.com/wwmm/easyeffects/blob/175121010ba271001e7343c759cb8116c271e035/src/lv2_wrapper.cpp#L151. And we get ports by index through https://github.com/wwmm/easyeffects/blob/175121010ba271001e7343c759cb8116c271e035/src/lv2_wrapper.cpp#L154C29-L154C58. When saving the ports to our vector I assume https://github.com/wwmm/easyeffects/blob/175121010ba271001e7343c759cb8116c271e035/src/lv2_wrapper.cpp#L158. So what is happening is that this index does not correctly represents the plugin port index anymore? IF I understood what you said it should still work.

**Comment by sadko4u** [comment]
I'll try the plugin in DAW sonn. Maybe I was wrong somewhere.

**Comment by sadko4u** [comment]
Oh, what a shame. This patch fixes the problem with x2 Stereo delay. It seems that I've checked mono and stereo and forgot to test the x2 Stereo.
https://github.com/lsp-plugins/lsp-plugins-comp-delay/commit/3b6cb1ca29a66633bb44ef9b070f185e0ea37a4f

**Comment by zono50** [comment]
As far as a lamen goes, how do i apply that patch to easy effects? Keep getting fatal - unable to read tree

**Comment by sadko4u** [comment]
You can just build `devel` branch of LSP Plugins and all be OK.

**Comment by zono50** [comment]
What version do i need to get? 1.2.16? also when i try to run make,  it gives me an error - easyeffects/lsp-plugins/modules/lsp-plugin-fw: No such file or directory.  Stop.

**Comment by sadko4u** [comment]
Please read [this section of the manual](https://github.com/lsp-plugins/lsp-plugins?tab=readme-ov-file#building).
You need to clone LSP Plugins, checkout `devel` branch and build them using the instructions from the manual.

**Comment by zono50** [comment]
I got it, was doing the build from source and not build from git, doing make fetch fixed my issue. Thank you for everything you do
