### ISSUE TITLE
Can you teach me to achieve an effect similar to ffmpeg's loudnorm filter?

### ISSUE THREAD

**Issue by sommio** [wwmm/easyeffects#3163]
I want to implement `loudnorm:I=-14:LRA=11:TP=-1` in easyeffects but can't get anywhere. 
Can you teach me what I should do? thanks.

If I understand correctly, `Autogain Target = -14.0 dB` and `Limiter Threshold = -1.0 db`
would allow me to achieve `I=-14` and `TP=-1`?

**Comment by violetmage** [comment]
If you mean that you have an Auto Gain with the target set to -14, after which is a Limiter with a threshold of -1, then yes, you will achieve a similar result as with loudnorm.

You may need to increase the Auto Gain maximum history value, otherwise the volume might readjust too often.

**Comment by wwmm** [comment]
> If I understand correctly, `Autogain Target = -14.0 dB` and `Limiter Threshold = -1.0 db`
> would allow me to achieve `I=-14` and `TP=-1`?

You may have to also adjust the `reference` to use only the integrated loudness. Also have in mind that our autogain handles live streams while the ffmpeg plugin probably is making use of the fact it has access to the whole file content and may be doing multiple passes.

**Comment by sommio** [comment]
> You may need to increase the Auto Gain maximum history value, otherwise the volume might readjust too often.

What is a reasonable AutoGain maximum history value?
Also is there a way for me to set the Loudness Range (LRA)?

**Comment by wwmm** [comment]
> What is a reasonable AutoGain maximum history value?

The maximum history directly controls the integrated loudness time window. When you know the size of the audio content you will be processing it would be as long as what you are listening to. On live streams it would not make sense to do this as the time could be "infinity".

> Also is there a way for me to set the Loudness Range (LRA)?

No. Our autogain Just estimates a simple gain correction based on the current estimated loudness.
