### ISSUE TITLE
Pulse Effects Legacy crackles every 50 seconds

### ISSUE THREAD

**Issue by LinuxBeaver** [wwmm/easyeffects#3165]
### EasyEffects Version

PulseEffects4.8.7

### What package are you using?

Other (specify below)

### Distribution

Fedora 38

### Describe the bug

I am on Fedora 38 using source compiled Pulse Effects as well as the Flatpak counterpart -  both 4.87. They work but every 50 seconds or so a stutter happens. It does not happen if Pulse Effects is disabled and the only LPS component I use is the Equalizer I tried increasing the niceness to -19. Any idea how to fix this, maybe an emergency patch - my machine has trouble with pipewire too but that is unrelated.

### Expected Behavior

No crackle every 50 seconds

**Comment by LinuxBeaver** [comment]
Also I tried compiling versions of Pulse Effects before 4.8.6 and it compiles but doesn't launch it complains about this https://github.com/wwmm/easyeffects/issues/1468 . 4.8.6 has the same problem as 4.8.7 btw

**Comment by wwmm** [comment]
>They work but every 50 seconds or so a stutter happens

How are you configuring the equalizer? Is it in a mode different from `IIR` that adds high latency? Maybe the crackle is related to some plugin internal buffer being recreated and using IIR mode will make this less noticeable as its latency is smaller.

>Any idea how to fix this, maybe an emergency patch - my machine has trouble with pipewire too but that is unrelated.

Another possibility is that some change in Pulseaudio is causing this. But the problem will be debugging it. I do not use Pulseaudio anymore in any of my computers.

**Comment by LinuxBeaver** [comment]
In default PulseEffects Equalizer uses IRR mode  and the stutter happens even if LPS plugins are disabled and the package for LPS plugins is removed. It is likely Pulse Audio updated and it may also have to do with my sound card uniquely.

**Comment by wwmm** [comment]
> In default PulseEffects Equalizer uses IRR mode and the stutter happens even if LPS plugins are disabled and the package for LPS plugins is removed. It is likely Pulse Audio updated and it may also have to do with my sound card uniquely.

Without plugins in the pipeline PulseEffects will be in passthrough mode. This shouldn't introduce crackling. So Some change in Pulseaudio or the soundcard drivers seems the most reasonable explanation indeed.

**Comment by LinuxBeaver** [comment]
How can I find what sound card drivers Fedora 38 has?

**Comment by wwmm** [comment]
> How can I find what sound card drivers Fedora 38 has?

The driver is in the kernel. Try to see if you have other kernels packages in your distribution repositories. In some cases changing the kernel version may help to fix crackling.

**Comment by LinuxBeaver** [comment]
I'm on Fedora 39 and the problem appears gone.  I had to source compile PulseEffects as it is no longer in Fedora's repo.

**Comment by LinuxBeaver** [comment]
Wait - it happens when PulseEffects whens as a gapplication-service - but it does not happen when it is running normally, as to shutdown when its window is closed.
