### ISSUE TITLE
EasyEffects unavailable on APT, Linux Mint + EasyEffects unable to differentiate speaker and headphones

### ISSUE THREAD

**Issue by DavidRLTG** [wwmm/easyeffects#3175]
### EasyEffects Version

7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux Mint Virginia

### Describe the bug

1. Doing apt install easyeffects doesn't work, package can't be found, despite my sources being up to date
2. EasyEffects cannot tell when I use my laptop speakers, or when my Headphones are plugged in. this DID work on pulseeffects.
I tried making a default preset for the speakers and one for the headphones, but it will load the preset anyway, as it cant tell when I plug them in, somehow

Also, due to the package only being available on Flatpak (where I ended up installing it from) I am having trouble getting the application to start in the background upon startup.

### Expected Behavior

I expected the package to be available on Linux Mint, and expected EasyEffects to be able to tell when I plug my headphones in, and switch to a different preset,

### Additional Information

I'm on a Thinkpad T480, if that matters.

And here's presets autoloading, if it helps.
![image](https://github.com/wwmm/easyeffects/assets/87834635/70e57395-f4c2-4e09-9d2a-b24c6fc89d4e)
That, is the only device it can detect.

**Comment by violetmage** [comment]
AFAIK Ubuntu 22.04 LTS still uses pulseaudio as the primary sound server; they're using pipewire-pulse to nest a pipewire instance under the pulseaudio server, presumably for flatpak compatibility.

For the sake of completeness, can you share a screenshot of the PipeWire tab in EasyEffects?  This way we can be sure that this isn't a different issue.

**Comment by DavidRLTG** [comment]
Of course.
By the way, just worth mentioning: I installed pipewire + its extras and all went perfectly (In theory!) but audio works and all, and pulseaudio is nowhere to be seen.
![image](https://github.com/wwmm/easyeffects/assets/87834635/281be41b-88af-4fce-8520-ad3f4c742bc2)

**Comment by violetmage** [comment]
Does anything change in pavucontrol when you switch from headphones to speakers?

**Comment by DavidRLTG** [comment]
> Does anything change in pavucontrol when you switch from headphones to speakers?

Speakers:
![image](https://github.com/wwmm/easyeffects/assets/87834635/d794496c-331e-4959-9459-86d076dc78a6)

Headphones:
![image](https://github.com/wwmm/easyeffects/assets/87834635/d22fa79f-d8eb-493a-b60e-395f1c262079)

**Comment by violetmage** [comment]
Almost certainly the same as #3090. The response there from wwmm details the usual solution.

**Comment by DavidRLTG** [comment]
> Almost certainly the same as #3090. The response there from wwmm details the usual solution.

I'll look into it later, as I am currently busy, and mention if it helped.

Thank you for your help!

**Comment by DavidRLTG** [comment]
> Almost certainly the same as #3090. The response there from wwmm details the usual solution.

I tried switching to headphones in pavucontrol, then pressing plus or switching devices in easyeffects, nothing seems to work, it still takes only the speakers. What can I do? or is there something I'm missing?

**Comment by violetmage** [comment]
Instead of using pavucontrol to do the switch, have you tried physically plugging in/unplugging your headphones to prompt the switch?

Just a guess at this point, really.

**Comment by DavidRLTG** [comment]
> Instead of using pavucontrol to do the switch, have you tried physically plugging in/unplugging your headphones to prompt the switch?
> 
> Just a guess at this point, really.

Of course! No help, EasyEffects still only sees one source.

**Comment by DavidRLTG** [comment]
> If you click the plus button after plugging in/unplugging your headphones, does easyeffects allow another preset to be made?
> 
> From what I understand, technically you only have one output device; plugging in headphones just causes it to switch profiles (modes). So you wont see another output device option, since technically you are creating another preset for the same device that happens to be using a different profile.

If I click it, no, it doesn't allow me. It still sees only one device, and considers it the same one.

**Comment by violetmage** [comment]
Unless you find something interesting in the configuration tab of pavucontrol for your output device, I can't think of anything else ATM. I'll have to do some research later today.

**Comment by DavidRLTG** [comment]
> Unless you find something interesting in the configuration tab of pavucontrol for your output device, I can't think of anything else ATM. I'll have to do some research later today.

No worries, thank you for your help. Good luck with your research!!

**Comment by violetmage** [comment]
@wwmm I'm starting to feel a bit lost on this one, would appreciate any thoughts.

AFAICT, from the pavucontrol screenshots, OP's pipewire seems to be properly switching profiles, but somehow easyeffects' behavior is not reflecting this. The only possibility that comes to my mind is another server client version mismatch thing.

Not sure where to proceed with troubleshooting at this point, assuming that the problem really is profile detection or whatever.

**Comment by wwmm** [comment]
I think there are too many things being discussed at once. The lack of package for Ubuntu distribution is something that has to be taken to the respective distribution package maintainers. We do not provide Debian packages nowadays. A few years ago someone used to do this in a third party repository. But I've never participated in the creation of Debian packages.

Based on what has be shown there is only one output device in you system @DavidRLTG. What Pavucontrol is showing as `Speakers` and `Headphones` is just the hardware profile that the `Built-in Audio` device has active. When creating an autoloading profile for headphones in a system like yours you have to make sure that the headphone is plugged before trying to create the profile. The device name will be the same but the profile filed in EasyEffects window will swtch between `analog-uotput-headphones` and the one for speakers.

**Comment by wwmm** [comment]
>When creating an autoloading profile for headphones in a system like yours you have to make sure that the headphone is plugged before trying to create the profile

And when creating for speakers the headphone has to be removed before trying to create the profile. Otherwise the hardware profile won't change. Switching it in Pavucontrol may have the same effect. It will depend on whether PipeWire is broadcasting the change or not.

**Comment by DavidRLTG** [comment]
> I think there are too many things being discussed at once. The lack of package for Ubuntu distribution is something that has to be taken to the respective distribution package maintainers. We do not provide Debian packages nowadays. A few years ago someone used to do this in a third party repository. But I've never participated in the creation of Debian packages.
> 
> Based on what has be shown there is only one output device in you system @DavidRLTG. What Pavucontrol is showing as `Speakers` and `Headphones` is just the hardware profile that the `Built-in Audio` device has active. When creating an autoloading profile for headphones in a system like yours you have to make sure that the headphone is plugged before trying to create the profile. The device name will be the same but the profile filed in EasyEffects window will swtch between `analog-uotput-headphones` and the one for speakers.

I swear, I know this may sound ridiculous, but EasyEffects still shows one device, whether I have speakers, or headphones plugged in. I don't know how.

I'll try deleting the settings, plugging in my headphones, setting the profile there, closing easyeffects, then opening it again with speakers and try creating a profile for them. This should be the final confirmation that something is not right.

**Comment by wwmm** [comment]
> > I think there are too many things being discussed at once. The lack of package for Ubuntu distribution is something that has to be taken to the respective distribution package maintainers. We do not provide Debian packages nowadays. A few years ago someone used to do this in a third party repository. But I've never participated in the creation of Debian packages.
> > Based on what has be shown there is only one output device in you system @DavidRLTG. What Pavucontrol is showing as `Speakers` and `Headphones` is just the hardware profile that the `Built-in Audio` device has active. When creating an autoloading profile for headphones in a system like yours you have to make sure that the headphone is plugged before trying to create the profile. The device name will be the same but the profile filed in EasyEffects window will swtch between `analog-uotput-headphones` and the one for speakers.
> 
> I swear, I know this may sound ridiculous, but EasyEffects still shows one device, whether I have speakers, or headphones plugged in. I don't know how.
> 
> I'll try deleting the settings, plugging in my headphones, setting the profile there, closing easyeffects, then opening it again with speakers and try creating a profile for them. This should be the final confirmation that something is not right.

I think you are just looking at the wrong place. Let me explain using the image you attached before
![image](https://github.com/wwmm/easyeffects/assets/16225172/55c96e01-393a-49e6-a853-e17757265091)

The device available for user selection will be the same. The value in the `Device` and `Name` fields will also be the same. The only one that changes is the `Profile` field. And it only changes after clicking on the "add button".

**Comment by DavidRLTG** [comment]
Doing what I said, has fixed the issue, somehow!
Thank you for your help, guys
Sorry for any disturbance I caused!
