### ISSUE TITLE
KDE Discover Package doesn't install dependencies

### ISSUE THREAD

**Issue by KaptainAhoibrause** [wwmm/easyeffects#3191]
### EasyEffects Version

7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

EndeavourOS

### Describe the bug

Hey guys,

when I installed easy effects via the Discover-App in KDE, it didn't install dependencies like the `Linux Studio Plugin`. It worked fine with installing over the commandline via flathub.

### Expected Behavior

Install dependencies

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
That sounds like a kde discover bug. It is surprising that is possible given kde discover should just be asking flatpak to install the easy effects flatpak package, so maybe flatpak itself is doing something wrong. In any case this is not an issue here.

**Comment by wwmm** [comment]
As this is probably a bug in Flatpak or Discover we can close this issue.

**Comment by KaptainAhoibrause** [comment]
Ok, thank you guys for the rapid support! The Button to report problems in Discover redirected to here, this is why I'm asking.

Installing ist via Flatpak in the Terminal installed everything right, it's definitely a KDE Discover related thing.
