### ISSUE TITLE
app crashes when we uploads APO or reset the eq 

### ISSUE THREAD

**Issue by Ayush583-Aswal** [wwmm/easyeffects#3193]
### EasyEffects Version

7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 24.04 LTS

### Describe the bug

when i upload APO to an Eq the app crashes and force quit/wait option comes. This is also the case for , when we are resetting the eq filters.
this error was coming in terminal: (easyeffects:2): GLib-GIO-WARNING **: 21:46:40.879: g_settings_set_value: value for key 'band9-frequency' in schema 'com.github.wwmm.easyeffects.equalizer.channel' is outside of valid range

 where band9 filter was something like this : 'Filter 9: Off PK Fc 0 Hz Gain 0 dB Q 0'

### Expected Behavior

the app should be able to switch the APO filters and reset the filters without getting force quit alert. like we can change the eq settings easily in wavelet(on android) without getting any error and it should function smoothly

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Attach here on github the preset you tried to load. The last time I tested the APO import it was fine. But i is not a feature I have a reason to use. So maybe there was a regression somewhere.

**Comment by Digitalone1** [comment]
> where band9 filter was something like this : 'Filter 9: Off PK Fc 0 Hz Gain 0 dB Q 0'

Indeed 0 Hz frequency is not valid. But I'd like the app won't crash on out of bounds values. I didn't know gsettinsg does not have an internal check and it crashes directly...

**Comment by wwmm** [comment]
> > where band9 filter was something like this : 'Filter 9: Off PK Fc 0 Hz Gain 0 dB Q 0'
> 
> Indeed 0 Hz frequency is not valid (10 is minimum). But I'd like the app won't crash on out of bounds values. I didn't know gsettinsg does not have an internal check and it crashes directly...

Hum... I wonder if the crash was really inside gsettings. In this bug report there is only a warning coming from it.

**Comment by Digitalone1** [comment]
I think it's in gsettinsg, but it does not provide an easy way to check the key range.

We have an unused util for that, but https://docs.gtk.org/gio/method.SettingsSchemaKey.get_range.html says it's better to not use it in normal programs.

Then there's
https://docs.gtk.org/gio/method.SettingsSchemaKey.range_check.html but dealing with GVariant is very annoying.

Maybe the easiest way is to get the ranges from Gtk widgets. We already do in UI util along with std::clamp().

**Comment by Digitalone1** [comment]
Here we are: https://github.com/wwmm/easyeffects/blob/master/src/ui_helpers.cpp#L159

This is just straightforward. Since the code is in eq UI, it should be easy to access those spinbuttons. And there's no need to make tricky db/linear conversions since we are dealing with frequencies.

**Comment by Ayush583-Aswal** [comment]
> Attach here on github the preset you tried to load. The last time I tested the APO import it was fine. But i is not a feature I have a reason to use. So maybe there was a regression somewhere.

[Truthear-dita.txt](https://github.com/user-attachments/files/15904633/Truthear-dita.txt)
![Screenshot from 2024-06-19 23-49-50](https://github.com/wwmm/easyeffects/assets/115387327/9a1f7a0a-fb31-4971-9c34-55268cb36811)

**Comment by Ayush583-Aswal** [comment]
attached the preset text file too

**Comment by Digitalone1** [comment]
@Ayush583-Aswal Filters from 7 to 10 are just useless/placeholders. You can delete them from the preset file.

**Comment by wwmm** [comment]
> > Attach here on github the preset you tried to load. The last time I tested the APO import it was fine. But i is not a feature I have a reason to use. So maybe there was a regression somewhere.
> 
> [Truthear-dita.txt](https://github.com/user-attachments/files/15904633/Truthear-dita.txt) ![Screenshot from 2024-06-19 23-49-50](https://private-user-images.githubusercontent.com/115387327/341172193-9a1f7a0a-fb31-4971-9c34-55268cb36811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzM5NTksIm5iZiI6MTcxODgzMzY1OSwicGF0aCI6Ii8xMTUzODczMjcvMzQxMTcyMTkzLTlhMWY3YTBhLWZiMzEtNDk3MS05YzM0LTU1MjY4Y2IzNjgxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQyMTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjI0OGNkNTA5OTRiNjk5ODVjNjU4YjcwODFiZWQzOTZjMjRlN2U4ZDBhMTM5YTg5Nzg5NGZjZDI0MWFjNWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4cuzZZBvQK--UMox1-Q07w9T7oYxcL6P98wAw77RLxA)

I tested this APO preset now and although the `outside of valid range` warnings were shown there was no crash or notification window about the process not responding. The equalizer worked. I wonder why in @Ayush583-Aswal  system the window is not responding...

**Comment by Digitalone1** [comment]
> I tested this APO preset now and although the `outside of valid range` warnings were shown there was no crash or notification window about the process not responding. The equalizer worked. I wonder why in @Ayush583-Aswal system the window is not responding...

Same to me, but we are on master branch, many things have changed from the latest release.

Anyway I don't like those warnings and it would be better to handle those range checks from our side. I was looking into it and we can't access spinbuttons/scales from equalizer_ui because they are in the band_box_ui, so I'm afraid we should add GSettingsSchemaKey to make those checks before applying the key values.

Besides, I see there's the new `band_width` control but we don't set it when the APO is imported/exported. Maybe we should do it.

And importing some test APO presets I have on my system, the `BP` type is not applied, but from [APO config documentation](https://sourceforge.net/p/equalizerapo/wiki/Configuration%20reference/#filter) I see it is the Band Pass filter which is present in the LSP equalizer. I suppose we made the import algorithm when Band Pass was not already implemented.

Anyway, the APO import/export feature needs some updates.

**Comment by Digitalone1** [comment]
For the "freeze" during the reset of the Equalizer, this is a know issue on Flatpak. Gsettings engine on Flatpak is not the best and resetting all the Equalizer controls takes a lot of time.

**Comment by wwmm** [comment]
> For the "freeze" during the reset of the Equalizer, this is a know issue on Flatpak. Gsettings engine on Flatpak is not the best and resetting all the Equalizer controls takes a lot of time.

Oh... For some reason I forgot to consider this. It is totally possible.

**Comment by Digitalone1** [comment]
@wwmm Since the range checks have been implemented, this could be closed.
