### ISSUE TITLE
EasyEffects service deactivates when closing the software on Flatpak on Kubuntu 24.04

### ISSUE THREAD

**Issue by andresgarcia0313** [wwmm/easyeffects#3206]
### EasyEffects Version

7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Kubuntu 24.04

### Describe the bug

In the Flatpak package of EasyEffects, there is an issue where, despite activating the service, it deactivates when the software is closed. This prevents the effects and configurations from remaining active after closing the application, which disrupts the user experience.

### Expected Behavior

The expected behavior is for the EasyEffects service to remain active and running even after closing the software interface. This will allow the applied configurations and effects to stay in place without needing to keep the application open.

### Additional Information

I am using Kubuntu 24.04 and have noticed this recurring behavior in the Flatpak package of EasyEffects. If further testing or additional information is required, I am available and willing to assist.

I hope this information helps in resolving the issue. Thank you for your attention and support.

Sincerely,
Andrés Eduardo García Márquez

**Comment by violetmage** [comment]
For the flatpak version, easyeffects must be granted permission to run in the background.

Also, you should check if the option `Settings -> General -> Shutdown on Window Closing` is not checked. If it is checked, easyeffects will not try to run in the background.

**Comment by wwmm** [comment]
As explained by @violetmage the issue is Flatpak's package not being granted permission or not asking for it.

**Comment by andresgarcia0313** [comment]
It's necessary to restart to activate and validate the service, and with this, it works without issues.
