### ISSUE TITLE
Mouse pointer larger than default and system icons not respected.

### ISSUE THREAD

**Issue by MedievalMatt** [wwmm/easyeffects#3209]
### EasyEffects Version

7.1.7

### What package are you using?

Flatpak (Flathub)

### Distribution

KDE Neon (Ubuntu 22.04)

### Describe the bug

The mouse pointer is about twice the size of the default mouse pointer and the icons for close, minimize, and maximize don't respect the expected system icons.

### Expected Behavior

That the look and feel be consistent with the defaults for my system -- ie. the mouse is the default size and the icons for close, minimize, and maximize respect the desktop theme.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>The mouse pointer is about twice the size of the default mouse pointer

EasyEffects does not even try to set configurations for he mouse icon. This is handled by gtk and/or the desktop at a lower level. Unfortunately there is nothing I can do about it.

>and the icons for close, minimize, and maximize don't respect the expected system icons.

This is also handled by gtk through client side decorations. I do no think there is a way to make them look like the icons KDE puts in the title bar.

>That the look and feel be consistent with the defaults for my system -- ie. the mouse is the default size and the icons for close, minimize, and maximize respect the desktop theme.

This is something that will never happen considering the different approaches taken by gtk and Qt/KDE apps. GTk apps do not look fully native on KDE and the same happens when Qt apps are used on GNOME. It is out of our reaches to make this kind of integration happen.

**Comment by violetmage** [comment]
This sounds like a GTK + flatpak sandbox issue.

What is the output of `flatpak --version`?

Also, have you applied any UI scaling in your system display settings?

**Comment by wwmm** [comment]
>This sounds like a GTK + flatpak sandbox issue.

Is Flatpak's sandbox sandbox known to mess with the mouse icon? At this moment the only Flatpak I have installed is the one for `Komikku` and the mouse's icon is fine.

**Comment by MedievalMatt** [comment]
Thanks for responding.

> This sounds like a GTK + flatpak sandbox issue.
> 
> What is the output of `flatpak --version`?
1.12.7

> 
> Also, have you applied any UI scaling in your system display settings?

I have it at 150%, but I reverted it back to 100% to test and the scaling differential persists.

**Comment by MedievalMatt** [comment]
> > The mouse pointer is about twice the size of the default mouse pointer
> 
> EasyEffects does not even try to set configurations for the mouse icon. This is handled by gtk and/or the desktop at a lower level. Unfortunately there is nothing I can do about it.
> 
> > and the icons for close, minimize, and maximize don't respect the expected system icons.
> 
> This is also handled by gtk through client side decorations. I do no think there is a way to make them look like the icons KDE puts in the title bar.
> 
> > That the look and feel be consistent with the defaults for my system -- ie. the mouse is the default size and the icons for close, minimize, and maximize respect the desktop theme.
> 
> This is something that will never happen considering the different approaches taken by gtk and Qt/KDE apps. Gtk apps do not look fully native on KDE and the same happens when Qt apps are used on GNOME. It is out of our reach to make this kind of integration happen.

Bummer. I may try blowing it out and installing from something other than Flatpak, then.

**Comment by violetmage** [comment]
@wwmm My first thought was that there could be some discrepancy between some configuration of the Desktop Environment and what is revealed within the sandbox, but this is not likely.

I think the scaling issue probably has to do with how GTK has only recently [added support for real fractional scaling](https://blog.gtk.org/2024/03/07/on-fractional-scales-fonts-and-hinting/), whereas before it was accomplished with a lot of sleight of hand and pixel doubling.

**Comment by wwmm** [comment]
>I have it at 150%, but I reverted it back to 100% to test and the scaling differential persists.

I also use KDE (100% scaling) and so far no gtk or Qt app makes the mouse icon size or shape change. Including the one I installed through Flatpak. But unfortunately I can't test this on EasyEffects because I use a native package I built from our master branch.

**Comment by wwmm** [comment]
I've just seen the mouse suddenly becoming huge for a fraction of a second while using Firefox. And yersterday it happened also very fast while the mouse was over the KDE panel. This may be a KDE bug @MedievalMatt.

**Comment by wwmm** [comment]
> I've just seen the mouse suddenly becoming huge for a fraction of a second while using Firefox. And yersterday it happened also very fast while the mouse was over the KDE panel. This may be a KDE bug @MedievalMatt.

I just realized that moving the mouse faster makes it bigger and after sometime without moviment it gets smaller. I think this is not a bug but a feature to make it easier to find the mouse pointer :smile:. There is even an animation.
