### ISSUE TITLE
Eassy Effects wont start in linux mint

### ISSUE THREAD

**Issue by Sheepmister** [wwmm/easyeffects#3238]
### EasyEffects Version

latest version

### What package are you using?

Flatpak (Flathub)

### Distribution

Linux mint

### Describe the bug

fail to start

### Expected Behavior

i open easy effect and it wont show

### Debug Log

n/a

### Additional Information

im new to linux and i install fresh linux mint after the installation of easyeffects i click start and it wont load

**Comment by wwmm** [comment]
Run it in debug mode `G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects` so we can see more information. It is also important to know which Mint version you are using because some Ubuntu/Debian users need to configure third party repositories with more recent PipeWire releases.

**Comment by Sheepmister** [comment]
> Run it in debug mode `G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects` so we can see more information. It is also important to know which Mint version you are using because some Ubuntu/Debian users need to configure third party repositories with more recent PipeWire releases.

brudik@brudik-TravelMate-P246M-M:~$ G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects
(process:2): easyeffects-DEBUG: 07:23:24.177: 	easyeffects.cpp:46	easyeffects version: 7.1.7
(process:2): easyeffects-DEBUG: 07:23:24.177: 	easyeffects.cpp:56	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 07:23:24.187: 	presets_manager.cpp:238user presets directory already exists: /home/brudik/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 07:23:24.187: 	presets_manager.cpp:238user presets directory already exists: /home/brudik/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 07:23:24.187: 	presets_manager.cpp:238user presets directory already exists: /home/brudik/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs
(easyeffects:2): easyeffects-DEBUG: 07:23:24.187: 	presets_manager.cpp:238user presets directory already exists: /home/brudik/.var/app/com.github.wwmm.easyeffects/config/easyeffects/rnnoise
(easyeffects:2): easyeffects-DEBUG: 07:23:24.187: 	presets_manager.cpp:238user presets directory already exists: /home/brudik/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 07:23:24.187: 	presets_manager.cpp:238user presets directory already exists: /home/brudik/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
Failed to register: Timeout was reached
(easyeffects:2): easyeffects-DEBUG: 07:23:49.215: 	easyeffects.cpp:71	Exitting the main function with status: 1

im using Linux Mint 21.3 "Virginia" cinnamon edition

**Comment by wwmm** [comment]
This is too short. Assuming there was no instance already running in the background something is broken in one of the system libraries easyeffects has to use. Is your pipewire installation fully functional or do you still have pulseaudio installed?

**Comment by violetmage** [comment]
I think the easiest thing is just to check the output of `pipewire --version`

**Comment by Sheepmister** [comment]
> I think the easiest thing is just to check the output of `pipewire --version`

i fixed it by uninstalling pulse audio and replacing it with pipewire sorry im noob about linux

**Comment by wwmm** [comment]
> > I think the easiest thing is just to check the output of `pipewire --version`
> 
> i fixed it by uninstalling pulse audio and replacing it with pipewire sorry im noob about linux

No problems :-)
