### ISSUE TITLE
[REQUEST] add  ISO 226:2023 Loudness Standard 

### ISSUE THREAD

**Issue by TheBestKmanEver** [wwmm/easyeffects#3253]
i would love to see the ISO 226:2023 Loudness contour added. or is this a question for Linux Studio Plugins????

**Comment by wwmm** [comment]
>is this a question for Linux Studio Plugins????

It is. We just wrap their plugin. Once it is available there it will be here too.

**Comment by TheBestKmanEver** [comment]
LSP 1.2.17 has just released with the addition of ISO 226:2023

**Comment by wwmm** [comment]
> LSP 1.2.17 has just released with the addition of ISO 226:2023

Thanks for letting me know. I will reopen and pin this issue so I do not forget to add the entry on our side.

**Comment by Digitalone1** [comment]
https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.17

@wwmm Maybe also `balance knobs to LSP Slap-back Delay Stereo plugin`.

**Comment by wwmm** [comment]
> https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.17
> 
> @wwmm Maybe also `balance knobs to LSP Slap-back Delay Stereo plugin`.

The slap-back delay is a different plugin https://lsp-plug.in/?page=manuals&section=slap_delay_stereo. So unless the same option was slilently added to the one we use there is nothing we have to do in the delay plugin.

**Comment by wwmm** [comment]
Implemented in EasyEffects 7.1.8
