### ISSUE TITLE
Route changes does not affect preset autoloading anymore

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#3266]
I started to have issues with preset autoloading again.

Maybe its the new PW version since device names are changed. Anyway I reset autoloading entries for speaker and headphones on my laptop and I noticed something weird.

First the system kept setting EE sink as the default device and the autoloading was not working. Then, from Gnome applet, I manually selected the speaker (when the HP jack is not plugged) and the headphone (when the jack is plugged) and it restarted to work again as it should be.

But now I notice that the autoloading it's not happening anymore through route changes, but directly from new default device:

```
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.254: 	pipe_manager.cpp:265	Audio/Sink 100 alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink has been removed
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	pipe_manager.cpp:265	Audio/Source 131 alsa_input.pci-0000_04_00.6.HiFi__Mic2__source has been removed
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	pipe_manager.cpp:265	Audio/Source 56 alsa_input.pci-0000_04_00.6.HiFi__Mic1__source has been removed
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	pipe_manager.cpp:1303	Audio/Sink 56 alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink with serial 4664 has been added
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	pipe_manager.cpp:1303	Audio/Source 137 alsa_input.pci-0000_04_00.6.HiFi__Mic2__source with serial 4665 has been added
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	pipe_manager.cpp:1303	Audio/Source 99 alsa_input.pci-0000_04_00.6.HiFi__Mic1__source with serial 4666 has been added
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	node_info_holder.cpp:104	100, alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	node_info_holder.cpp:104	131, alsa_input.pci-0000_04_00.6.HiFi__Mic2__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.255: 	node_info_holder.cpp:104	131, alsa_input.pci-0000_04_00.6.HiFi__Mic2__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.256: 	node_info_holder.cpp:104	131, alsa_input.pci-0000_04_00.6.HiFi__Mic2__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.256: 	node_info_holder.cpp:104	131, alsa_input.pci-0000_04_00.6.HiFi__Mic2__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.256: 	node_info_holder.cpp:104	131, alsa_input.pci-0000_04_00.6.HiFi__Mic2__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.256: 	node_info_holder.cpp:104	56, alsa_input.pci-0000_04_00.6.HiFi__Mic1__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.256: 	node_info_holder.cpp:104	56, alsa_input.pci-0000_04_00.6.HiFi__Mic1__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.256: 	node_info_holder.cpp:104	56, alsa_input.pci-0000_04_00.6.HiFi__Mic1__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.257: 	node_info_holder.cpp:104	56, alsa_input.pci-0000_04_00.6.HiFi__Mic1__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.257: 	node_info_holder.cpp:104	56, alsa_input.pci-0000_04_00.6.HiFi__Mic1__source finalized
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.261: 	pipe_manager.cpp:1039	new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"easyeffects_sink"}
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.261: 	pipe_manager.cpp:1039	new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"easyeffects_sink"}
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.273: 	pipe_manager.cpp:1346	No node with id 154 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.274: 	pipe_manager.cpp:1346	No node with id 154 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.274: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.275: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.275: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.276: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.278: 	application.cpp:124	input autoloading: device "alsa_card.pci-0000_04_00.6" has changed its input route to "[In] Mic1"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.278: 	application.cpp:133	input autoloading: add "alsa_input.pci-0000_04_00.6.HiFi__Mic2__source" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.278: 	application.cpp:133	input autoloading: add "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.278: 	application.cpp:153	input autoloading: skip "alsa_input.pci-0000_04_00.6.HiFi__Mic2__source" candidate since it does not match "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" input device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.278: 	application.cpp:147	input autoloading: target node "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" matches the input device name
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.278: 	application.cpp:112	new default input device: easyeffects_sink
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.280: 	pipe_manager.cpp:1039	new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink"}
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.280: 	pipe_manager.cpp:1039	new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_04_00.6.HiFi__Mic1__source"}
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.281: 	pipe_manager.cpp:1346	No node with id 154 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.281: 	pipe_manager.cpp:1346	No node with id 154 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.282: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.282: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	pipe_manager.cpp:1346	No node with id 149 in our node_map
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:166	output autoloading: device "alsa_card.pci-0000_04_00.6" has changed its output route to "[Out] Speaker"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:175	output autoloading: add "alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:195	output autoloading: skip "alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink" candidate since it does not match "alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink" output device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:200	output autoloading: no target nodes match the output device name "alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:124	input autoloading: device "alsa_card.pci-0000_04_00.6" has changed its input route to "[In] Mic1"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:133	input autoloading: add "alsa_input.pci-0000_04_00.6.HiFi__Mic2__source" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:133	input autoloading: add "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:153	input autoloading: skip "alsa_input.pci-0000_04_00.6.HiFi__Mic2__source" candidate since it does not match "easyeffects_sink" input device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:153	input autoloading: skip "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" candidate since it does not match "easyeffects_sink" input device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:158	input autoloading: no target nodes match the input device name "easyeffects_sink"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:124	input autoloading: device "alsa_card.pci-0000_04_00.6" has changed its input route to "[In] Mic1"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:133	input autoloading: add "alsa_input.pci-0000_04_00.6.HiFi__Mic2__source" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:133	input autoloading: add "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:153	input autoloading: skip "alsa_input.pci-0000_04_00.6.HiFi__Mic2__source" candidate since it does not match "easyeffects_sink" input device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:153	input autoloading: skip "alsa_input.pci-0000_04_00.6.HiFi__Mic1__source" candidate since it does not match "easyeffects_sink" input device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:158	input autoloading: no target nodes match the input device name "easyeffects_sink"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:104	new default output device: alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	presets_manager.cpp:1055	autoloading local preset LoudnessCrystalEqualizer for device alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink
```

I had to change the debug messages to see what was happening when the autoloading was not working. Even when I fixed the default devices, I kept seeing the preset autoloading to fail in the route changes: 

```
output autoloading: device "alsa_card.pci-0000_04_00.6" has changed its output route to "[Out] Speaker"
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:175	output autoloading: add "alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:195	output autoloading: skip "alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink" candidate since it does not match "alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink" output device
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:200	output autoloading: no target nodes match the output device name "alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink"
``` 

But this seems a bug since I unplugged the HP jack, the route changed to speaker, but the output device is the headphone?

Luckily it makes the autoload from the output device changed signal:

```
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	application.cpp:104	new default output device: alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink
(easyeffects:35124): easyeffects-DEBUG: 11:19:22.283: 	presets_manager.cpp:1055	autoloading local preset LoudnessCrystalEqualizer for device alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink
```

Similarly, it happens the same when I plug the HP jack:

```
(easyeffects:35124): easyeffects-DEBUG: 11:41:37.894: 	application.cpp:166	output autoloading: device "alsa_card.pci-0000_04_00.6" has changed its output route to "[Out] Headphones"
(easyeffects:35124): easyeffects-DEBUG: 11:41:37.894: 	application.cpp:175	output autoloading: add "alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink" as candidate for preset autoloading
(easyeffects:35124): easyeffects-DEBUG: 11:41:37.894: 	application.cpp:195	output autoloading: skip "alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink" candidate since it does not match "alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink" output device
(easyeffects:35124): easyeffects-DEBUG: 11:41:37.894: 	application.cpp:200	output autoloading: no target nodes match the output device name "alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink"
```

```
(easyeffects:35124): easyeffects-DEBUG: 11:41:37.894: 	application.cpp:104	new default output device: alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink
(easyeffects:35124): easyeffects-DEBUG: 11:41:37.895: 	presets_manager.cpp:1055	autoloading local preset LoudnessCrystalEqualizerHP for device alsa_output.pci-0000_04_00.6.HiFi__Headphones__sink
```

Now I wonder if this change happens to everyone of just users having my same device. If this is a new way of PW to handle device changes, we could get rid of the signals associated to route changes, right?

Another thing: when EE sink was set as the system default, its name was saved in gsettings which was triggering functions associated to the key changes. Can we avoid it? I assume we do not want to do things when the EE sink is set as default...

**Comment by wwmm** [comment]
>If this is a new way of PW to handle device changes, we could get rid of the signals associated to route changes, right?

Something seems to have changed on their side. But my bluetooth device still needs the routing information because the device name does not have the routing appended to it.

**Comment by wwmm** [comment]
I have also noticed some inconsistencies in how PipewWire' is generating the name. In my bluetooth output name it used `_` in the bus path that was appended. But in the input name of the same device it used the bus path with `:` instead. As a result the routing filed in EE window was empty...

Maybe we should try to use the node id again as suggested at https://github.com/wwmm/easyeffects/pull/3186. In the past they caused some problems. Maybe if done the way it is there they will be reliable. Although PipeWire developers suggested to use names in he past this isn't that reliable too...

**Comment by wwmm** [comment]
>Another thing: when EE sink was set as the system default, its name was saved in gsettings which was triggering functions associated to the key changes. Can we avoid it? I assume we do not want to do things when the EE sink is set as default...

Unfortunately We can't avoid our virtual devices being set as the system default. WE can try to avoid making use of it as default inside EasyEffects. Where was it saved in gsettings?

**Comment by Digitalone1** [comment]
> I have also noticed some inconsistencies in how PipewWire' is generating the name. In my bluetooth output name it used `_` in the bus path that was appended. But in the input name of the same device it used the bus path with `:` instead. As a result the routing filed in EE window was empty...
> 
> Maybe we should try to use the node id again as suggested at #3186. In the past they caused some problems. Maybe if done the way it is there they will be reliable. Although PipeWire developers suggested to use names in he past this isn't that reliable too...

I don't know, maybe the best thing to do is to report this inconsistency to PW devs. I have the feeling that node id can change just like names are changing now...

**Comment by wwmm** [comment]
>I don't know, maybe the best thing to do is to report this inconsistency to PW devs. I have the feeling that node id can change just like names are changing now...

Let's give it a try and see what happens. For now commit https://github.com/wwmm/easyeffects/commit/5272cadc7c47a3d5afda84f30b270f0e00445517 is working on my bluetooth and on soundcard. If things get bad we can always revert this commit.

**Comment by wwmm** [comment]
The problem iwth PipeWire's names is that they don't really have a standard. PCI devices names are built in a way that is different from usb and bluetooth. And depending on the bluetooth version they have different ways to build the name...

**Comment by Digitalone1** [comment]
> Unfortunately we can't avoid our virtual devices being set as the system default. We can try to avoid making use of it as default inside EasyEffects. Where was it saved in gsettings?

* https://github.com/wwmm/easyeffects/blob/master/src/application.cpp#L107
* https://github.com/wwmm/easyeffects/blob/master/src/application.cpp#L115

There are also
* https://github.com/wwmm/easyeffects/blob/master/src/stream_input_effects.cpp#L53
* https://github.com/wwmm/easyeffects/blob/master/src/stream_output_effects.cpp#L54

But here we check they are not `tags::pipewire::ee_source_name` and `tags::pipewire::ee_sink_name`

**Comment by Digitalone1** [comment]
> The problem with PipeWire's names is that they don't really have a standard. PCI devices names are built in a way that is different from usb and bluetooth. And depending on the bluetooth version they have different ways to build the name...

But we are not even sure the node id are permanent.

**Comment by Digitalone1** [comment]
> For now commit [5272cad](https://github.com/wwmm/easyeffects/commit/5272cadc7c47a3d5afda84f30b270f0e00445517) is working on my bluetooth and on soundcard.

It's working to me too. Let's hope it will last, but I'm pretty sure this will break again in the future...

**Comment by wwmm** [comment]
> > Unfortunately we can't avoid our virtual devices being set as the system default. We can try to avoid making use of it as default inside EasyEffects. Where was it saved in gsettings?
> 
>     * https://github.com/wwmm/easyeffects/blob/master/src/application.cpp#L107
> 
>     * https://github.com/wwmm/easyeffects/blob/master/src/application.cpp#L115
> 
> 
> There are also
> 
>     * https://github.com/wwmm/easyeffects/blob/master/src/stream_input_effects.cpp#L53
> 
>     * https://github.com/wwmm/easyeffects/blob/master/src/stream_output_effects.cpp#L54
> 
> 
> But here we check they are not `tags::pipewire::ee_source_name` and `tags::pipewire::ee_sink_name`

We also do this check before emitting the new default device signal https://github.com/wwmm/easyeffects/blob/9b708d431af1445f1fc89c0a27fe75d9055ea7e8/src/pipe_manager.cpp#L1061.  Strange...

**Comment by Digitalone1** [comment]
> We also do this check before emitting the new default device signal
> https://github.com/wwmm/easyeffects/blob/9b708d431af1445f1fc89c0a27fe75d9055ea7e8/src/pipe_manager.cpp#L1061

Yes, I forgot about this, but I was still seeing `easy-effects-sink` in debug messages. Now that I think about it, that was the route change signal, so when the ee sink is set as default, we still trigger the signal about the route changes.

**Comment by wwmm** [comment]
>Now that I think about it, that was the route change signal, so when the ee sink is set as default, we still trigger the signal about the route changes.

I will have to take a look at the code but shouldn't this signal be ignore eventually because nothing in the autoload profile would match this virtual sink?

**Comment by Digitalone1** [comment]
> I will have to take a look at the code but shouldn't this signal be ignore eventually because nothing in the autoload profile would match this virtual sink?

Well, yes, it could be ignored. So let's hope the node ID it's the final solution. The issue can be closed.
