### ISSUE TITLE
Question: where are the preset files stored?

### ISSUE THREAD

**Issue by proairface** [wwmm/easyeffects#3274]
I just got a new laptop and I am trying to move everything over to a new distro. I am trying to find where Easy Effects stores the preset files that I made. I tried looking through ~/.local/share/flatpak/app/com.github.wwmm.easyeffects to see if I can find anything, but alas.
Is there a way (command line?) to export the presets to a file (e.g. on my desktop)? Mind you, I am running an old version of Easy Effects due to a preference for the older plugins. i am using version 7.0.4. on Pop_OS! and am migrating to OpenSuSe tumbleweed.

Thanks in advance!

**Comment by violetmage** [comment]
For a flatpak install, the user configuration files should be in `~/.var/app/com.github.wwmm.easyeffects/config/`

**Comment by wwmm** [comment]
> For a flatpak install, the user configuration files should be in `~/.var/app/com.github.wwmm.easyeffects/config/`

And if EasyEffects was installed through a native distribution package it should be inside `~/.config/easyeffects/`.

**Comment by proairface** [comment]
Yes! ~/.var/app/com.github.wwmm.easyeffects/config/ did the trick for me! Thanks!
