### ISSUE TITLE
easy effect broke after instaling hyprland

### ISSUE THREAD

**Issue by MrGaMLes** [wwmm/easyeffects#3279]
### EasyEffects Version

7.1.6.r145.ge225bd27a-1 

### What package are you using?

Arch (easyeffects)

### Distribution

EndeavourOS Linux x86_64 

### Describe the bug

easy effect just giving the error:Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken. 
after i instaled hyprland it work on hyprland but not kde

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

i dont know how to lounch whit G_MESSAGES_DEBUG=easyeffects nad its probly sound drivers problem

**Comment by wwmm** [comment]
>i dont know how to lounch whit G_MESSAGES_DEBUG=easyeffects

Make sure there is no EAsyEffects instance running and run in a terminal `G_MESSAGES_DEBUG=easyeffects easyeffects`.

>its probly sound drivers problem

Considering the error message it is either something missing in your PipeWire installation or something became broken in the gtk4 installation after the move to hyprland.

**Comment by MrGaMLes** [comment]
(easyeffects:4895): Gtk-WARNING **: 18:14:24.349: Unknown key gtk-modules in /home/omerfk/.themes/Catppuccin-Mocha/gtk-4.0/settings.ini
its just keep giving mw this non stop

**Comment by MrGaMLes** [comment]
(process:6233): easyeffects-DEBUG: 18:34:22.739:        easyeffects.cpp:46      easyeffects version: 7.1.7
(process:6233): easyeffects-DEBUG: 18:34:22.741:        easyeffects.cpp:56      locale directory: /usr/share/locale
(easyeffects:6233): easyeffects-DEBUG: 18:34:22.743:    presets_manager.cpp:238 user presets directory already exists: /home/omerfk/.config/easyeffects/input
(easyeffects:6233): easyeffects-DEBUG: 18:34:22.743:    presets_manager.cpp:238 user presets directory already exists: /home/omerfk/.config/easyeffects/output
(easyeffects:6233): easyeffects-DEBUG: 18:34:22.744:    presets_manager.cpp:238 user presets directory already exists: /home/omerfk/.config/easyeffects/irs
(easyeffects:6233): easyeffects-DEBUG: 18:34:22.744:    presets_manager.cpp:238 user presets directory already exists: /home/omerfk/.config/easyeffects/rnnoise
(easyeffects:6233): easyeffects-DEBUG: 18:34:22.744:    presets_manager.cpp:238 user presets directory already exists: /home/omerfk/.config/easyeffects/autoload/input
(easyeffects:6233): easyeffects-DEBUG: 18:34:22.744:    presets_manager.cpp:238 user presets directory already exists: /home/omerfk/.config/easyeffects/autoload/output

(easyeffects:6233): Gtk-WARNING **: 18:34:22.782: Unknown key gtk-modules in /home/omerfk/.config/gtk-4.0/settings.ini

**Comment by MrGaMLes** [comment]
this all i can see

**Comment by wwmm** [comment]
Strange. Usually the logs are this short when there is already an EasyEffects instance running in the background.

**Comment by MrGaMLes** [comment]
im 100% its a problem whit the gtk problem can you help me to reinstall it i dont know it
im not fimilar whit gtk4 packages

**Comment by wwmm** [comment]
> im 100% its a problem whit the gtk problem can you help me to reinstall it i dont know it im not fimilar whit gtk4 packages

As I use Arch Linux there may be some differences when compared to EndeavourOS. But my system has only the `gtk4` package when ti comes to gtk4 packages. So in order to reinstall it it should be enough to run the command `sudo pacman -S gtk4` if things are the same on EndeavourOS.

**Comment by MrGaMLes** [comment]
'm try'ng to change the theme maybe that w'll help thanls

**Comment by MrGaMLes** [comment]
ok chaing the theme and delating the btoken theme get rid of the problem thanks you so much for you time
