### ISSUE TITLE
Linking against libpulsecommon-*.so

### ISSUE THREAD

**Issue by mikhailnov** [wwmm/easyeffects#328]
```
$ ldd /usr/bin/pulseeffects | grep pulse
	libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f01acc34000)
	libpulsecommon-12.2.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-12.2.so (0x00007f01a8409000)
```
What will happen if PulseAudio upgrades, so-name changes and pulseeffects is not rebuilt, e.g. when installed from AUR?

**Comment by wwmm** [comment]
At least on Arch Linux when Pulseaudio was upgraded from 11 to 12 it was necessary to recompile PulseEffects.

**Comment by mikhailnov** [comment]
What does `ldd /usr/bin/pulseeffects | grep pulse` show on Arch?

**Comment by wwmm** [comment]
```
libpulse.so.0 => /usr/lib/libpulse.so.0 (0x00007f4e508ec000)
libpulsecommon-12.2.so => /usr/lib/pulseaudio/libpulsecommon-12.2.so (0x00007f4e4d4c2000)
```

**Comment by mikhailnov** [comment]
https://abi-laboratory.pro/index.php?view=timeline&l=pulseaudio 
(maybe it will be interesting)
