### ISSUE TITLE
[Feature Request] Preset Autoloading - Default preset for unconfigured devices

### ISSUE THREAD

**Issue by RaduTek** [wwmm/easyeffects#3286]
I use EasyEffects with one preset for my laptop's speakers and a blank preset for anything else.

The current behaviour is that unless a preset autoload rule is set up for the device, the previous preset remains active. I connect diverse USB and Bluetooth audio devices often enough that opening EasyEffects to load my blank preset and setting up autoload for it is tiring.

There should be an option to create an autoload rule that matches any device that hasn't been explicitly assigned to a preset.

![image](https://github.com/user-attachments/assets/06c8eb54-a71d-4468-8e26-e3f7b0066b24)

This is my current setup. Ideally, we'd have a single "wildcard" rule that would select the Blank preset at the bottom of the list.

**Comment by wwmm** [comment]
We already have an issue that is essentially about this. So this one can be closed. That being said I have no idea about when I will have time to do something about it because at this moment I am working on a Qt port.

**Comment by RaduTek** [comment]
Can you link the issue? I looked for existing ones similar to mine before submitting, but I probably missed it.

Glad to hear you're working on a Qt port, makes a KDE user happy :)

**Comment by wwmm** [comment]
> Can you link the issue? I looked for existing ones similar to mine before submitting, but I probably missed it.
> 
> Glad to hear you're working on a Qt port, makes a KDE user happy :)

Oops. I would link it and somehow I forgot :smile: . Just a moment.

**Comment by wwmm** [comment]
Issue #1359
