### ISSUE TITLE
Reload optional dependencies when reopening the GUI

### ISSUE THREAD

**Issue by LingMan** [wwmm/easyeffects#3292]
### EasyEffects Version

7.1.7

### What package are you using?

Arch (easyeffects)

### Distribution

EndeavourOS

### Describe the bug

E.g the Bass Enhancer needs the optional calf dependency. If that's not installed there's a nice page titled "Bass Enhancer Not Available" explaining the problem. So far so good.

However, if calf now gets installed with the package manager and the GUI reopen, that same "Not Available" page is still shown. The user needs to figure out by themselves that there is still an easyeffects process running and kill it.

### Expected Behavior

Closing and reopening the GUI reloads optional dependencies so the user doesn't have to (manually) kill the still running easyeffects process.

Ideally there would also be a Refresh button on the "Not Available" page so the GUI doesn't have to be restarted at all.

**Comment by violetmage** [comment]
For the sake of simplicity, what's wrong with having a message on the "Not available" page that says something like, "If you've installed the required packages, use the 'Quit' button in the menu to stop easyeffects, then restart easyeffects to use the new package".

**Comment by wwmm** [comment]
> For the sake of simplicity, what's wrong with having a message on the "Not available" page that says something like, "If you've installed the required packages, use the 'Quit' button in the menu to stop easyeffects, then restart easyeffects to use the new package"?

It seems fine to me.

**Comment by violetmage** [comment]
@wwmm Mark as completed?

**Comment by wwmm** [comment]
> @wwmm Mark as completed?

Yes. Specially considering that the qt port is progressing and spending effort in the gtk window widgets do not make much sense now. If this message proves to be not enough in the future we can revisit it.
