### ISSUE TITLE
Alt-Tab doesn't return to EE

### ISSUE THREAD

**Issue by ParticleMon** [wwmm/easyeffects#3295]
### EasyEffects Version

7.1.6

### What package are you using?

Other (specify below)

### Distribution

Linux Mint 22, Cinnamon, X11

### Describe the bug

After Alt-Tabbing away from Easy Effects (EE), pressing Alt-Tab again doesn't return to EE but instead returns to the window that was focused previous to EE.

Replication:
1. Focus EE
2. Alt-Tab
3. Alt-Tab

### Expected Behavior

EE should be focused after pressing (and releasing) Alt-Tab twice (without holding Alt).

### Additional Information

I've not noticed this behavior in any other program, including GTK programs I currently have installed from among these:
https://github.com/valpackett/awesome-gtk

**Comment by wwmm** [comment]
>I've not noticed this behavior in any other program, including GTK programs I currently have installed from among these:

Did you test with gtk4 programs? Even if it does not happen with other apps there is nothing that can be done from the application side about how the window manager is handling alt-tab. This is something that has to be reported to the developers of the window manager used by your desktop.
