### ISSUE TITLE
Input fields do not accept input

### ISSUE THREAD

**Issue by ParticleMon** [wwmm/easyeffects#3297]
### EasyEffects Version

7.1.6

### What package are you using?

Other (specify below)

### Distribution

Linux Mint 22, Cinnamon, X11

### Describe the bug

To change values in input fields, only the +/- buttons work: Entered values are not applied.

Thus, the larger the change, the longer it takes; for instance, adjusting the frequency of a band in Equalizer thousands of Hz (because of the unintuitive/undesired behavior of Calculate Frequencies--a separate issue), can take _minutes_.

### Expected Behavior

Entered values are applied.

### Additional Information

Workaround:
1. Edit the preset .json
2. Reload the preset

**Comment by wwmm** [comment]
Probably the same as #3033. A workaround for the new gtk4 behavior is already available in EasyEffects `7.1.7`. Try to see if the new version is available for your system.
