### ISSUE TITLE
UI value input isn't working

### ISSUE THREAD

**Issue by derVedro** [wwmm/easyeffects#3315]
### EasyEffects Version

7.1.6

### What package are you using?

Other (specify below)

### Distribution

Ubuntu 24.04

### Describe the bug

I've noticed a problem that almost all text input elements that have additional fine tuning buttons don't work for me. Here a [simple demonstration](https://uploadnow.io/f/Gg2L4yq).

### Expected Behavior

Input field with values should act as desired values and should not be ignored.

**Comment by wwmm** [comment]
You are probably seeing #3033. A fix for this is already on our master branch but I do not remember if the last stable release got it.

**Comment by derVedro** [comment]
> You are probably seeing #3033. A fix for this is already on our master branch but I do not remember if the last stable release got it.

yes, that's #3033. Thanks.
