### ISSUE TITLE
French translation only works for French (France) locales

### ISSUE THREAD

**Issue by carmenbianca** [wwmm/easyeffects#3316]
### EasyEffects Version

7.1.7

### What package are you using?

Fedora

### Distribution

Fedora 40

### Describe the bug

When your language is French (Belgium), EasyEffects is not translated.

### Expected Behavior

EasyEffects uses the existing French (France) translation.

### Additional Information

Steps to reproduce:

1. `export LANG="fr_BE.UTF-8"`
2. `unset LANGUAGE` (to be sure)
3. `easyeffects`
4. EasyEffects is not translated.

To solve this issue, the French translation should be `fr.po`, not `fr_FR.po`. A really easy fix. I do not know if this should be changed in Weblate or in a PR to this project. I _think_ it should be changed in Weblate.

**Comment by wwmm** [comment]
>To solve this issue, the French translation should be fr.po, not fr_FR.po

Hum... Searching for `fr_BE.po`on github I see that other projects have this file. Wouldn't it be better to create a second translation file for Belgium? In this case the solution would be to add another language on Weblate. It has the option for FR_BE. Or is the French spoken there really identical?

**Comment by carmenbianca** [comment]
It is identical, barring small pronunciation differences and like a handful of expressions. Easy Effects is the only software on my Fedora installation that uses the `fr_FR` locale instead of `fr`, in `/usr/share/locale/`.

**Comment by wwmm** [comment]
> It is identical, barring small pronunciation differences and like a handful of expressions. Easy Effects is the only software on my Fedora installation that uses the `fr_FR` locale instead of `fr`, in `/usr/share/locale/`.

I see. I wonder if a rename to `fr` will conflict with weblate considering that they have separated entries for French and Belgium in their "add language" menu.

**Comment by carmenbianca** [comment]
It shouldn't, I'm pretty sure. Easy Effects also has `nl` instead of `nl_NL` or `nl_BE`, which works just fine.

**Comment by wwmm** [comment]
> It shouldn't, I'm pretty sure. Easy Effects also has `nl` instead of `nl_NL` or `nl_BE`, which works just fine.

Ok. Let's do it and see what happens. I've released EasyEffects `7.1.8` with the new file name.
