### ISSUE TITLE
Game audio not being processed by easyeffects

### ISSUE THREAD

**Issue by eduardoeae** [wwmm/easyeffects#3320]
### EasyEffects Version

7.1.8

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

When I start 7 Days to Die the audio stream is not being handled by easyeffects 7.1.8. Also once I forced the game to use easyeffects (via pavucontrol or pulsemixer) the game is missing from the easyeffects interface.

### Expected Behavior

easyeffects should automatically process all Output Streams, as I have that option toggled on.

7.1.7 works as expected.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Is this game being played through wine/proton? The games I play through Proton work on EasyEffects without problems. So this game may be doing something unusual. Kill EasyEffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see what is printed when the game starts to play audio.

**Comment by wwmm** [comment]
>7.1.7 works as expected

Make sure the game is not setting a custom target device that is not the one EasyEffects uses as output device. In the latest version we started to respect the custom target set by streams and do not touch the ones that have been configured to use a device that is not the one EasyEffects is set to use.

**Comment by eduardoeae** [comment]
> Make sure the game is not setting a custom target device that is not the one EasyEffects uses as output device. In the latest version we started to respect the custom target set by streams and do not touch the ones that have been configured to use a device that is not the one EasyEffects is set to use.

`pipe_manager.cpp:360  The output stream 7DaysToDie.x86_64 does not have as target the same output device used as EE: alsa_output.pci-0000_00_1b.0.analog-stereo
The user wants it to play to device easyeffects_sink. We will ignore this stream.`

It looks like you are right. Even if the output device is actually the same (there is only one on this computer), looks like the game is causing the problem.
Is there any way to force EE to use previous behavior?

**Comment by wwmm** [comment]
>Is there any way to force EE to use previous behavior?

No. But now that I see your logs I realize that there is a flaw in the logic we use to decide if we should move or not a stream. Having our own virtual devices as target node should not cause a stream to be ignored. I will update our master branch with a fix.

**Comment by wwmm** [comment]
Master branch updated. If possible try to install the AUR package. I think it should work now.

**Comment by eduardoeae** [comment]
Yes! Now it works as expected. Thanks!
