### ISSUE TITLE
Updating LSP plugins from 1.2.12 to 1.2.13 breaks Delay plugin in flatpak

### ISSUE THREAD

**Issue by violetmage** [wwmm/easyeffects#3339]
### EasyEffects Version

7.1.8, 7.1.7, 7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 40

### Describe the bug

The delay plugin complains about a missing host feature, the map function for the URID extension, even though easyeffects implements it:

```
(easyeffects:2): easyeffects-DEBUG: 02:08:01.501: 	lv2_wrapper.cpp:126	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
```

Also, whenever this message is present, the delay plugin is still available, but it just eats any audio going into it. Instead it outputs silence no matter what, as long as it's not bypassed. It seems strange to me that the lv2_wrapper does not report failure to initialize the plugin in this scenario.

Testing out various flatpak configurations, I've narrowed down the appearance of the issue to the update of `org.freedesktop.LinuxAudio.Plugins.LSP/arch/23.08` from version 1.2.12 to 1.2.13. AFAICT the bug is present in all versions after 1.2.12.

Currently not sure if this is a flathub flatpak packaging issue or a LSP issue. Almost certainly not an easyeffects issue, but posting this here to track progress.

### Expected Behavior

The delay does not eat my music for lunch.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(process:2): easyeffects-DEBUG: 02:08:01.077: 	easyeffects.cpp:46	easyeffects version: 7.1.6
(process:2): easyeffects-DEBUG: 02:08:01.078: 	easyeffects.cpp:56	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 02:08:01.111: 	presets_manager.cpp:212	user presets directory already exists: /home/mage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/
(easyeffects:2): easyeffects-DEBUG: 02:08:01.111: 	presets_manager.cpp:212	user presets directory already exists: /home/mage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 02:08:01.111: 	presets_manager.cpp:212	user presets directory already exists: /home/mage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 02:08:01.111: 	presets_manager.cpp:212	user presets directory already exists: /home/mage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 02:08:01.111: 	presets_manager.cpp:212	user presets directory already exists: /home/mage/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 02:08:01.300: 	pipe_manager.cpp:1534	compiled with PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 02:08:01.300: 	pipe_manager.cpp:1535	linked to PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 02:08:01.358: 	pipe_manager.cpp:1505	core version: 1.0.7
(easyeffects:2): easyeffects-DEBUG: 02:08:01.358: 	pipe_manager.cpp:1506	core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 02:08:01.362: 	pipe_manager.cpp:1417	found metadata: settings
(easyeffects:2): easyeffects-DEBUG: 02:08:01.364: 	pipe_manager.cpp:1417	found metadata: schema-sm-settings
(easyeffects:2): easyeffects-DEBUG: 02:08:01.364: 	pipe_manager.cpp:1417	found metadata: persistent-sm-settings
(easyeffects:2): easyeffects-DEBUG: 02:08:01.364: 	pipe_manager.cpp:1417	found metadata: sm-settings
(easyeffects:2): easyeffects-DEBUG: 02:08:01.364: 	pipe_manager.cpp:1417	found metadata: sm-objects
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1417	found metadata: default
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1417	found metadata: filters
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1417	found metadata: route-settings
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1271	Audio/Sink 45 alsa_output.pci-0000_00_1f.4.analog-stereo with serial 45 has been added
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1271	Audio/Source 46 alsa_input.pci-0000_00_1f.4.analog-stereo with serial 46 has been added
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1271	Stream/Output/Audio 130 Firefox with serial 656 has been added
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1311	Firefox port 137 is connected to alsa_output.pci-0000_00_1f.4.analog-stereo port 50
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1311	Firefox port 71 is connected to alsa_output.pci-0000_00_1f.4.analog-stereo port 52
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1271	Audio/Sink 86 easyeffects_sink with serial 682 has been added
(easyeffects:2): easyeffects-DEBUG: 02:08:01.365: 	pipe_manager.cpp:1271	Audio/Source/Virtual 87 easyeffects_source with serial 683 has been added
(easyeffects:2): easyeffects-DEBUG: 02:08:01.367: 	pipe_manager.cpp:1007	new metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.4.analog-stereo"}
(easyeffects:2): easyeffects-DEBUG: 02:08:01.369: 	pipe_manager.cpp:1007	new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.4.analog-stereo"}
(easyeffects:2): easyeffects-DEBUG: 02:08:01.372: 	pipe_manager.cpp:1633	easyeffects_sink node successfully retrieved with id 86 and serial 682
(easyeffects:2): easyeffects-DEBUG: 02:08:01.372: 	pipe_manager.cpp:1638	easyeffects_source node successfully retrieved with id 87 and serial 683
(easyeffects:2): easyeffects-DEBUG: 02:08:01.392: 	plugin_base.cpp:403	soe: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.393: 	plugin_base.cpp:403	soe: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.501: 	lv2_wrapper.cpp:126	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.505: 	plugin_base.cpp:403	soe: level_meter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.506: 	pipe_manager.cpp:1311	easyeffects_sink port 73 is connected to ee_soe_level_meter port 122
(easyeffects:2): easyeffects-DEBUG: 02:08:01.510: 	pipe_manager.cpp:1311	easyeffects_sink port 74 is connected to ee_soe_level_meter port 119
(easyeffects:2): easyeffects-DEBUG: 02:08:01.515: 	plugin_base.cpp:403	soe: delay successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.517: 	pipe_manager.cpp:1311	ee_soe_level_meter port 106 is connected to ee_soe_delay port 102
(easyeffects:2): easyeffects-DEBUG: 02:08:01.521: 	pipe_manager.cpp:1311	ee_soe_level_meter port 120 is connected to ee_soe_delay port 112
(easyeffects:2): easyeffects-DEBUG: 02:08:01.524: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.526: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.531: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.532: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.535: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.537: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.547: 	plugin_base.cpp:403	sie: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.557: 	plugin_base.cpp:403	sie: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.560: 	pipe_manager.cpp:1314	No node with id 89 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.562: 	pipe_manager.cpp:1314	No node with id 89 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.568: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.571: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.578: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.580: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.582: 	stream_output_effects.cpp:349	disconnecting the delay filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:01.591: 	pipe_manager.cpp:265	 107 ee_soe_delay has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:01.592: 	stream_output_effects.cpp:349	disconnecting the level_meter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:01.595: 	pipe_manager.cpp:265	 123 ee_soe_level_meter has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:01.614: 	plugin_base.cpp:403	soe: level_meter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.615: 	pipe_manager.cpp:1311	easyeffects_sink port 73 is connected to ee_soe_level_meter port 97
(easyeffects:2): easyeffects-DEBUG: 02:08:01.617: 	pipe_manager.cpp:1311	easyeffects_sink port 74 is connected to ee_soe_level_meter port 95
(easyeffects:2): easyeffects-DEBUG: 02:08:01.622: 	plugin_base.cpp:403	soe: delay successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:01.625: 	pipe_manager.cpp:1311	ee_soe_level_meter port 90 is connected to ee_soe_delay port 103
(easyeffects:2): easyeffects-DEBUG: 02:08:01.625: 	pipe_manager.cpp:1311	ee_soe_level_meter port 123 is connected to ee_soe_delay port 122
(easyeffects:2): easyeffects-DEBUG: 02:08:01.628: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.630: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.632: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.634: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.636: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.639: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.648: 	pipe_manager.cpp:1314	No node with id 89 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.650: 	pipe_manager.cpp:1314	No node with id 89 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.651: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.653: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.655: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:01.657: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
easyeffects-INFO: 02:08:01.657: 	application.cpp:76	disabling global bypass
(easyeffects:2): easyeffects-DEBUG: 02:08:01.667: 	application_ui.cpp:109	Icon Theme Adwaita detected
(easyeffects:2): easyeffects-DEBUG: 02:08:02.409: 	stream_output_effects.cpp:349	disconnecting the delay filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:02.416: 	pipe_manager.cpp:265	 119 ee_soe_delay has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:02.416: 	stream_output_effects.cpp:349	disconnecting the level_meter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:02.417: 	pipe_manager.cpp:265	 105 ee_soe_level_meter has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:02.424: 	plugin_base.cpp:403	soe: level_meter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:02.424: 	pipe_manager.cpp:1311	easyeffects_sink port 73 is connected to ee_soe_level_meter port 112
(easyeffects:2): easyeffects-DEBUG: 02:08:02.426: 	pipe_manager.cpp:1311	easyeffects_sink port 74 is connected to ee_soe_level_meter port 104
(easyeffects:2): easyeffects-DEBUG: 02:08:02.429: 	plugin_base.cpp:403	soe: delay successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:02.430: 	pipe_manager.cpp:1311	ee_soe_level_meter port 102 is connected to ee_soe_delay port 106
(easyeffects:2): easyeffects-DEBUG: 02:08:02.430: 	pipe_manager.cpp:1311	ee_soe_level_meter port 105 is connected to ee_soe_delay port 97
(easyeffects:2): easyeffects-DEBUG: 02:08:02.431: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.432: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.434: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.435: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.437: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.437: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.439: 	application.cpp:104	new default output device: alsa_output.pci-0000_00_1f.4.analog-stereo
(easyeffects:2): easyeffects-DEBUG: 02:08:02.440: 	pipe_manager.cpp:1007	new metadata property: 130, target.node, Spa:Id, 86
(easyeffects:2): easyeffects-DEBUG: 02:08:02.440: 	pipe_manager.cpp:1007	new metadata property: 130, target.object, Spa:Id, 682
(easyeffects:2): easyeffects-DEBUG: 02:08:02.440: 	stream_output_effects.cpp:349	disconnecting the delay filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:02.441: 	pipe_manager.cpp:265	 95 ee_soe_delay has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:02.441: 	stream_output_effects.cpp:349	disconnecting the level_meter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:02.442: 	pipe_manager.cpp:265	 124 ee_soe_level_meter has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:02.448: 	pipe_manager.cpp:1311	Firefox port 137 is connected to easyeffects_sink port 85
(easyeffects:2): easyeffects-DEBUG: 02:08:02.448: 	pipe_manager.cpp:1311	Firefox port 71 is connected to easyeffects_sink port 79
(easyeffects:2): easyeffects-DEBUG: 02:08:02.449: 	plugin_base.cpp:403	soe: level_meter successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:02.451: 	pipe_manager.cpp:1311	easyeffects_sink port 73 is connected to ee_soe_level_meter port 103
(easyeffects:2): easyeffects-DEBUG: 02:08:02.453: 	pipe_manager.cpp:1311	easyeffects_sink port 74 is connected to ee_soe_level_meter port 99
(easyeffects:2): easyeffects-DEBUG: 02:08:02.456: 	plugin_base.cpp:403	soe: delay successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 02:08:02.457: 	pipe_manager.cpp:1311	ee_soe_level_meter port 98 is connected to ee_soe_delay port 90
(easyeffects:2): easyeffects-DEBUG: 02:08:02.457: 	pipe_manager.cpp:1311	ee_soe_level_meter port 124 is connected to ee_soe_delay port 112
(easyeffects:2): easyeffects-DEBUG: 02:08:02.459: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.460: 	pipe_manager.cpp:1314	No node with id 80 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.461: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.462: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.463: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.465: 	pipe_manager.cpp:1314	No node with id 66 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.468: 	application.cpp:112	new default input device: alsa_output.pci-0000_00_1f.4.analog-stereo
(easyeffects:2): easyeffects-DEBUG: 02:08:02.482: 	pipe_manager.cpp:1314	No node with id 89 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.484: 	pipe_manager.cpp:1314	No node with id 89 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.485: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.486: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.488: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.490: 	pipe_manager.cpp:1314	No node with id 91 in our node_map
(easyeffects:2): easyeffects-DEBUG: 02:08:02.495: 	application.cpp:156	device alsa_card.pci-0000_00_1f.4 has changed its output route to: analog-output-speaker
(easyeffects:2): easyeffects-DEBUG: 02:08:13.157: 	stream_output_effects.cpp:183	No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 02:08:13.157: 	stream_output_effects.cpp:349	disconnecting the delay filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:13.164: 	pipe_manager.cpp:265	 104 ee_soe_delay has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:13.164: 	stream_output_effects.cpp:349	disconnecting the level_meter filter from PipeWire
(easyeffects:2): easyeffects-DEBUG: 02:08:13.166: 	pipe_manager.cpp:265	 122 ee_soe_level_meter has been removed
(easyeffects:2): easyeffects-DEBUG: 02:08:13.180: 	stream_input_effects.cpp:189	No app linked to our device wants to play. Unlinking our filters.
(easyeffects:2): easyeffects-DEBUG: 02:08:17.122: 	application_ui.cpp:262	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.123: 	app_info.cpp:377	Firefox disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.123: 	app_info.cpp:385	Firefox finalized
(easyeffects:2): easyeffects-DEBUG: 02:08:17.123: 	app_info.cpp:63	data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.130: 	presets_menu.cpp:492	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.130: 	presets_menu.cpp:44	data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.130: 	presets_menu.cpp:502	finalized
(easyeffects:2): easyeffects-DEBUG: 02:08:17.130: 	effects_box.cpp:514	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.130: 	chart.cpp:49	data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.130: 	chart.cpp:652	finalized
(easyeffects:2): easyeffects-DEBUG: 02:08:17.131: 	blocklist_menu.cpp:219	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.131: 	blocklist_menu.cpp:52	data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.131: 	blocklist_menu.cpp:229	finalized
(easyeffects:2): easyeffects-DEBUG: 02:08:17.131: 	apps_box.cpp:414	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.131: 	node_info_holder.cpp:106	130, Firefox finalized
(easyeffects:2): easyeffects-DEBUG: 02:08:17.132: 	apps_box.cpp:51	data struct destroyed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.132: 	apps_box.cpp:424	finalized
(easyeffects:2): easyeffects-DEBUG: 02:08:17.132: 	plugins_box.cpp:866	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.132: 	level_meter_ui.cpp:178	disposed
(easyeffects:2): easyeffects-DEBUG: 02:08:17.133: 	level_meter_ui.cpp:44	data struct destroyed
```
</details>

**Comment by Br1tBreaker** [comment]
Right, sounds like a bit of a pickle, doesn't it? Delay plugin's gone AWOL and your tunes are getting swallowed up. Not ideal, mate.

Here's the thing, bruv: it's looking like a compatibility clash between EasyEffects and the latest LSP plugin update. That jump from 1.2.12 to 1.2.13 seems to be the culprit. EasyEffects is clearly implementing the map function, but LSP isn't seeing it.

Now, whether this is a Flathub packaging issue or a deeper LSP problem, that's the million-pound question. Could be something got messed up in the flatpak bundle, or maybe LSP itself has a bug.

Either way, we need to get to the bottom of it. Best bet is to raise a flag on the EasyEffects GitHub page and maybe ping the LSP devs too. The more eyes on this, the better.

In the meantime, you could try rolling back the LSP plugin to 1.2.12. Bit of a faff, but might get your delay back in action while the big brains figure this out.

Chin up, bruv. We'll get your music flowing again.

**Comment by violetmage** [comment]
^ bot

**Comment by violetmage** [comment]
Strangely, org.freedesktop.LinuxAudio.Plugins.LSP 1.2.15 appears to work with easyeffects 7.1.8

**Comment by wwmm** [comment]
>Strangely, org.freedesktop.LinuxAudio.Plugins.LSP 1.2.15 appears to work with easyeffects 7.1.8

LSP `1.2.17` is fine here on Arch Linux. And I do not remember the previous releases having this kind of problem on Arch Linux. It is also curious why only the delay plugin would complain about the map uri not being implemented. All the others use it too.

**Comment by wwmm** [comment]
> It looks like the easyeffects flatpak is building against a newer version of lv2 than the freedesktop runtime is:
> 
> https://github.com/flathub/com.github.wwmm.easyeffects/blob/a0e264164828d76304b9d42e8a058e3acab4aa47/shared-modules/linux-audio/lv2.json#L14
> 
> https://github.com/flathub/shared-modules/blob/096ab6b0be271f07a42a647b5ffc83808a160e59/linux-audio/lv2.json#L13
> 
> Perhaps this could be the problem?

Maybe. But it is strange considering that on is using `lv2-1.18.8` and the other `lv2-1.18.10`. Nowadays LV2 code does not change so much from one minor release to another.

**Comment by vchernin** [comment]
> It looks like the easyeffects flatpak is building against a newer version of lv2 than the freedesktop runtime is:
> 
> https://github.com/flathub/com.github.wwmm.easyeffects/blob/a0e264164828d76304b9d42e8a058e3acab4aa47/shared-modules/linux-audio/lv2.json#L14
> 
> https://github.com/flathub/shared-modules/blob/096ab6b0be271f07a42a647b5ffc83808a160e59/linux-audio/lv2.json#L13
> 
> Perhaps this could be the problem?

`flathub/shared-modules` is not part of a flatpak runtime. It contains files/modules which packages can include as they see fit. 

We are using the same lv2 version `1.18.10` as shared modules, last updated by me a year ago. https://github.com/flathub/shared-modules/blob/d88a9156b91eef64ecf1a313c868f1401c4bb39b/linux-audio/lv2.json

**Comment by violetmage** [comment]
That's just it though, the `org.freedesktop.LinuxAudio.Plugins.LSP` flatpak is building against shared-modules @ `096ab6b`, which is 2 years old and has lv2 at 1.18.8

**Comment by violetmage** [comment]
Confident that this issue is in LV2, LSP, or maybe some weird edge case in the lower levels of easyeffects. I've reproduced this on different versions of the flathub flatpak, and the development version that gets built by the github actions script. I can reproduce this issue consistently on a Fedora 40 VM and a Ubuntu 24.04 VM.

Again, seems to be only the flatpak for some reason.

**Comment by vchernin** [comment]
Without a better understanding of how to debug lv2 and lsp, my suggestion is to try bundle lsp from `org.freedesktop.LinuxAudio.Plugins.LSP` into easyeffects itself. i.e. copy paste the modules from https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP/blob/a5b6c5c2cd542e25015de9ab6d9c37ac10184330/org.freedesktop.LinuxAudio.Plugins.LSP.json into `easyeffects-modules.json` and then build easyeffects. When running easyeffects you'd need to make sure `org.freedesktop.LinuxAudio.Plugins.LSP` is uninstalled.

**Comment by violetmage** [comment]
I just want to confirm, can anyone else reproduce this issue?

I'll definitely try building an easyeffects flatpak with lv2 at 1.18.8 to match the version used by the LSP plugins from flathub, but just wanted to make sure this isn't a fluke on my end.

**Comment by violetmage** [comment]
Changing `util/flatpak/shared-modules/linux-audio/lv2.json` to point to version 1.18.8 and building an easyeffects 7.1.8 flatpak via github actions yields the same behavior.

Starting to think this is an issue in the delay plugin itself, although this is just speculation.

**Comment by wwmm** [comment]
>Starting to think this is an issue in the delay plugin itself, although this is just speculation.

But in this case some kind of problem should be happening outside of Flatpak too.

**Comment by violetmage** [comment]
Maybe it's related to this changelog item in LSP 1.2.17:

> * Fixed regression: improper port bindings for Compensation Delay x2 Stereo plugin.

Can you reproduce with a native package on an earlier version?

**Comment by wwmm** [comment]
> Maybe it's related to this changelog item in LSP 1.2.17:
> 
> > * Fixed regression: improper port bindings for Compensation Delay x2 Stereo plugin.
> 
> Can you reproduce with a native package on an earlier version?

I remember this bug. It was the one causing #3153. The delay plugin was completely unusable at the time. But the error message was not about missing extensions.

**Comment by wwmm** [comment]
>But the error message was not about missing extensions.

I do not think there was even a error message.

**Comment by violetmage** [comment]
The [LSP flatpak](https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP) is still on 1.2.16, so this is the same bug?

**Comment by wwmm** [comment]
> The [LSP flatpak](https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP) is still on 1.2.16, so this is the same bug?

It is suspicious considering that the delay plugin is involved. But also strange because the previous problem was not about missing extensions.

**Comment by violetmage** [comment]
The behavior seems the same as #3153 though. Maybe the changes you made to the lv2_wrapper are allowing the error to come through now when they didn't before.

**Comment by wwmm** [comment]
> The behavior seems the same as #3153 though. Maybe the changes you made to the lv2_wrapper are allowing the error to come through now when they didn't before.

Hum... Maybe.

**Comment by violetmage** [comment]
I'll try building an easyeffects flatpak with the LSP version manually set to 1.2.17

I'm curious though, have you been able to reproduce this, in a flatpak or otherwise?

**Comment by wwmm** [comment]
>I'm curious though, have you been able to reproduce this, in a flatpak or otherwise?

I do not use EasyEffects through Flatpak. The native package I build in my Arch Linux installation is fine. At least with the latest LSP release.

**Comment by violetmage** [comment]
Just tested a native (RPM via dnf) package in my Fedora 40 VM (easyeffects 7.1.7 w/ LSP 1.2.16), and the error message and lack of audio output are both reproducible when the delay plugin is added to the pipeline.

@wwmm can you try downgrading your LSP plugins to 1.2.16? If the problem appears then, that means that this is indeed the issue addressed in the changelog for LSP 1.2.17, and getting the LSP flatpak updated would fix the problem.

**Comment by wwmm** [comment]
> Just tested a native (RPM via dnf) package in my Fedora 40 VM (easyeffects 7.1.7 w/ LSP 1.2.16), and the error message and lack of audio output are both reproducible when the delay plugin is added to the pipeline.
> 
> @wwmm can you try downgrading your LSP plugins to 1.2.16? If the problem appears then, that means that this is indeed the issue addressed in the changelog for LSP 1.2.17, and getting the LSP flatpak updated would fix the problem.

I do not have the old version in pacman's cache anymore. I would have to search each lsp package in Arch's rollback machine. The lack of audio definitely was present in the previous LSP release. I just do not rememer this warning. In any case the Flatpak package will have to upgrade LSP at some point. So it is probably better to just upgrade it.

**Comment by violetmage** [comment]
I commented on an [open pull request in the LSP flatpak repo that updates LSP to 1.2.17](https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP/pull/28), but no response yet. I'm not sure of what else to do to help get the PR merged.

**Comment by violetmage** [comment]
Also, any thoughts on whether this type of error should prevent the plugin from being available in the UI?

Currently, easyeffects seems to know about and log the error, but it doesn't do anything about it. Not sure if this is intended or just an edge case.

**Comment by wwmm** [comment]
>Also, any thoughts on whether this type of error should prevent the plugin from being available in the UI?

I do not think there is any LV2 plugin out there that does not need the URID extension. The same thing on the host side. All of them have to implement this. It is the kind of thing that is supposed to always be implemented.

I think that it is enough to have the warning in our logs. The warning about missing plugins makes sense because it is something that the user can solve without making a bug report on our side. An error message about missing LV2 extension is not something the user will know how to fix. And as a result he/she will open a bug report and show EasyEffects logs anyway.

**Comment by violetmage** [comment]
Is there anything else we can do to help get the LSP plugins flatpak updated?

**Comment by wwmm** [comment]
> Is there anything else we can do to help get the LSP plugins flatpak updated?

Probably just waiting. I do not know how the LSP updates are being managed there.

**Comment by violetmage** [comment]
The LSP plugins flatpak just got updated, will test from flathub tomorrow.

**Comment by violetmage** [comment]
The latest LSP plugins flatpak now correctly works with the easyeffects 7.1.8 flatpak, however the error message still appears whenever the delay plugin gets loaded. Maybe we should ask the LSP developer what they think?

**Comment by wwmm** [comment]
> The latest LSP plugins flatpak now correctly works with the easyeffects 7.1.8 flatpak, however the error message still appears whenever the delay plugin gets loaded. Maybe we should ask the LSP developer what they think?

I looked at our lv2 wrapper code now. Actually it isn't an error message. It is just informing that the plugin needs this extension. It has been so long since I looked at our wrapper code that I forgot this. There is no need to talk to LSP developer. It is fine to see this message.

**Comment by wwmm** [comment]
And as LSP was updated in the Flatpak package we cal close this issue.
