### ISSUE TITLE
[Feature Request] Add ability to customize accentuation color

### ISSUE THREAD

**Issue by JayBeeDe** [wwmm/easyeffects#3357]
Add a setting to customize UI accentuation color with a color picker.
Bonus: add ability to set to auto and it will adapt according system's gnome accentuation theme color

![image](https://github.com/user-attachments/assets/95694940-efe9-4852-b28b-0094b5ce6b18)

**Comment by wwmm** [comment]
Usually toolkits do not offer a straightforward way to customize what the color theme is doing in such detail. It is not on the same level as changing the color of a text. To do what is being shown in this image it is necessary to convince the toolkit to change the color it decided to use to draw the color of a widget section. There is no function call for this.

The last time time I checked it is necessary to somehow to overwrite the theme on the fly. What also involves figuring out how the theme is naming each color. One more thing that isn't really a public API. Or if it is they hide it very well. Honestly, I do not think it is worth the amount of headache.

**Comment by wwmm** [comment]
>There is no function call for this as far as I remember.

In some cases the widget may expose a setting like the `pallet` setting in qt/qml widget. But this isn't overwriting the theme accent or background color. Only that particular widget is changed. So even if gtk has something similar we would have add an individual configuration for all those widgets. Not fun. And then there is the problem about how to make the widget to go back to the theme color. Not necessarily there is an easy reset. And figuring out the color value used by the theme can be problematic like I said before.

**Comment by violetmage** [comment]
@wwmm Close as wontfix?

**Comment by wwmm** [comment]
> @wwmm Close as wontfix?

I think we should. I have been delaying this because it is always possible that someone knows about an easy solution I am not aware of. But this did not happen and I really think we should avoid messing with what themes are doing when they draw the widgets.

**Comment by GeopJr** [comment]
Hello :wave: this is fairly easy to do in the latest stable libadwaita (which uses CSS variables), here's an example:


https://github.com/user-attachments/assets/b52e1591-8dd8-4330-9a6e-c308f2fc304a

<details><summary>Code (in vala)</summary>

```vala
public class ExampleApp : Adw.Application {
	public ExampleApp () {
		Object (application_id: "com.example.App");
	}

	Gtk.CssProvider accent_provider;
	Gtk.ColorDialogButton colordialogbutton;
	Adw.ApplicationWindow win;
	public override void activate () {
		accent_provider = new Gtk.CssProvider ();
		win = new Adw.ApplicationWindow (this);

		var box = new Gtk.Box (Gtk.Orientation.VERTICAL, 6);
		var scale = new Gtk.Scale.with_range (Gtk.Orientation.HORIZONTAL, 0.0, 1.0, 0.1);
		scale.set_value (0.5);
		box.append (scale);

		var colordialog = new Gtk.ColorDialog ();
		colordialogbutton = new Gtk.ColorDialogButton (colordialog);
		colordialogbutton.notify["rgba"].connect (on_accent_change);
		box.append (colordialogbutton);

		var reset_btn = new Gtk.Button.with_label ("Reset");
		reset_btn.clicked.connect (remove_custom_accent);
		box.append (reset_btn);

		win.content = box;
		win.present ();
	}

	void on_accent_change () {
		set_accent_color (colordialogbutton.get_rgba ().to_string ());
		win.get_style_context ().add_provider (accent_provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION);
	}

	void remove_custom_accent () {
		win.get_style_context ().remove_provider (accent_provider);
	}

	void set_accent_color (string color) {
		accent_provider.load_from_string (@":root {--accent-bg-color: $color;}");
	}

	public static int main (string[] args) {
		var app = new ExampleApp ();
		return app.run (args);
	}
}
```

</details>

As shown from the code above, you can set the accent color CSS variable (and other CSS variables) in a CssProvider and remove it when needed.

Custom widgets can use [`AdwStyleManager`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.StyleManager.html) to get the default system accent color and if the user has set a custom color you can use that internally instead.

(The style functions will be deprecated in GTK **5** and AFAIK there's no alternative currently.)
