### ISSUE TITLE
Any way to have a 'default' preset?

### ISSUE THREAD

**Issue by neilbags** [wwmm/easyeffects#3371]
I am using 'PipeWire -> Presets Autoloading' to load a preset for a specific device, however when a different device is connected (e.g. a new Bluetooth device) I want this preset 'unloaded', or an empty preset loaded, or EasyEffects disabled.

Is there a way to achieve this? It seems like a common use-case. I did check the FAQ. Apologies if there is something obvious I have missed

**Comment by wwmm** [comment]
>Is there a way to achieve this? It seems like a common use-case.

It isn't as common as it may seem. But it is something we will have to address in the future. There is a discussion about this #1359.

Assuming you do not have several different devices the current workaround is creating a preset that has no plugin and creating an autoloading for the device that should not have effects applied.

**Comment by wwmm** [comment]
As there is already a discussion about this we can close this issue.
