### ISSUE TITLE
Failure to recognize when Audio Applications are added/removed

### ISSUE THREAD

**Issue by ngraham20** [wwmm/easyeffects#3375]
### EasyEffects Version

7.1.8

### What package are you using?

Flatpak (flathub, user)

### Distribution

Bazzite 40.20240908.0 (Kinoite)

### Describe the bug

With Easy Effects open and `Input` selected, adding or removing an Audio Application does not register within Easy Effects.

Steps to reproduce:
1. Open Easy Effects
2. Select `Input`. There should be an `Empty List`.
3. Start a recording application. I have tried: `Discord` and `Google Meets (Vivaldi)`. Discord is a Flatpak, Vivaldi is a Fedora RPM package.
4. Easy Effects continues to say `Empty List`, and the audio does not connect through (verified with qpwgraph).
5. Restart Easy Effects. The Audio Applications should now be in the list and working (verified again with qpwgraph).
6. Close the recording application (Discord/Google Meets)
7. Easy Effects often (but not always) fails to remove these items from the list.
8. Restar EE again, and the list should now be Empty.

### Expected Behavior

I should not have to restart Easy Effects every time I join a Discord voice channel or start a GMeet.

### Debug Log

[broken.txt](https://github.com/user-attachments/files/16967228/broken.txt)
[working.txt](https://github.com/user-attachments/files/16967223/working.txt)

**Comment by violetmage** [comment]
This looks like #3358

@wwmm Maybe there is a need to get easyeffects 7.1.9 out so that a new flatpak can be made?

**Comment by wwmm** [comment]
>Maybe there is a need to get easyeffects 7.1.9 out so that a new flatpak can be made?

I do not see any problem in doing it. I've just updated the NEWS file. Tomorrow I will make a new release.

**Comment by wwmm** [comment]
>With Easy Effects open and Input selected, adding or removing an Audio Application does not register within Easy Effects.

@ngraham20 Does this happens to other applications besides Discord and Vivald? If yes upgrading to 7.1.9 will probably fix the issue. But as Discord is a known offender and I am not sure if Vivald also isn't the issue may have a different source.

**Comment by violetmage** [comment]
The easyeffects flatpak has been updated to 7.1.9. @ngraham20 can you please check to see if the problem is resolved by the update?

**Comment by ngraham20** [comment]
> > With Easy Effects open and Input selected, adding or removing an Audio Application does not register within Easy Effects.
> 
> @ngraham20 Does this happens to other applications besides Discord and Vivald? If yes upgrading to 7.1.9 will probably fix the issue. But as Discord is a known offender and I am not sure if Vivald also isn't the issue may have a different source.

I didn't get around to testing this , but @violetmage, `7.1.9` fixed the flatpak!
