### ISSUE TITLE
Mono mic results in only left channel being hearable in recordings via Easy Effects

### ISSUE THREAD

**Issue by darkhog** [wwmm/easyeffects#3390]
### EasyEffects Version

7.1.6

### What package are you using?

Flatpak (Flathub)

### Distribution

openSuSE

### Describe the bug

I have a mono USB mic (Krux EDIS 1000). After connecting to Easy Effects, the sound is only heard in the left channel. This makes it impossible to use this software for improving my voice in gameplay recordings of SuperTuxKart.

### Expected Behavior

The sound of a mono mic should be present in both channels (left and right).

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

Proposed solution: If the application detects a mono input or one channel being completely silent while other has a sound in it, it should duplicate the sound so the same waveform is on both channels. Alternatively, a manual override or a effect (that doesn't require Calf) that duplicates one channel onto the other should be added.

**Comment by wwmm** [comment]
This is known limitation #1312 that is easy to fix with the stereo tools plugin. It is just a matter of selecting a stereo matrix that creates a mono signal.

As there is already an issue about this and the problem can be easily fixed with one of the available plugins  this issue can be closed.
