### ISSUE TITLE
disabled plugins still do processing?

### ISSUE THREAD

**Issue by nekopsykose** [wwmm/easyeffects#3401]
### EasyEffects Version

7.1.9

### What package are you using?

Other (specify below)

### Distribution

chimera linux

### Describe the bug

my effects list looks like:

![](https://img.ayaya.dev/3UUBRLF75J4p)

note that the noise reduction effect is 'disabled'

however, looking at pw-top shows:

```
S   ID  QUANT   RATE    WAIT    BUSY   W/Q   B/Q  ERR FORMAT           NAME                                      
S   29      0      0    ---     ---   ---   ---     0                  Dummy-Driver
S   30      0      0    ---     ---   ---   ---     0                  Freewheel-Driver
S   45      0      0    ---     ---   ---   ---     0                  easyeffects_source
S   50      0      0    ---     ---   ---   ---     0                  Midi-Bridge
S   54      0      0    ---     ---   ---   ---     0                  alsa_output.pci-0000_0d_00.4.analog-stereo
S   55      0      0    ---     ---   ---   ---     0                  alsa_input.pci-0000_0d_00.4.analog-stereo
S   56      0      0    ---     ---   ---   ---     0                  bluez_midi.server
I   82      0      0   0.0us   0.0us  ???   ???     0                  ee_sie_output_level
I   87      0      0   0.0us   0.0us  ???   ???     0                  ee_sie_spectrum
R   99    128  48000  39.1us  33.4us  0.01  0.01    0    S24LE 2 48000 bluez_output.14_3F_A6_19_2C_E8.1
R   44      0      0   3.3us   1.2us  0.00  0.00  241     F32P 2 48000  + easyeffects_sink
R   59      0      0   0.6us   0.9us  0.00  0.00    3                   + ee_soe_output_level
R   64      0      0   0.7us   0.7us  0.00  0.00    8                   + ee_soe_spectrum
R  101      0      0   4.2us   1.2us  0.00  0.00  422                   + ee_soe_rnnoise
R  109      0      0   0.7us  14.8us  0.00  0.01   24                   + ee_soe_equalizer
R   94   3600  48000   4.3us   3.7us  0.00  0.00   26    F32LE 2 48000  + Firefox
S  134      0      0    ---     ---   ---   ---     0                  ee_test_signals
```

it looks like `ee_soe_rnnoise` has actual busy time, and also err's accumulated, despite never being enabled. if i remove the effect then that line dissappears.

is it expected that disabled effects still do some 'processing' (that is discarded?), or is this just a quirk of how pw-top displays things?

**Comment by wwmm** [comment]
>is it expected that disabled effects still do some 'processing' (that is discarded?), or is this just a quirk of how pw-top displays things?

Disabled plugins are put in `passthrough mode`. In other words they copy the audio buffers that get to their input ports directly to the output ports without modifying data. All the processing that they usually do is bypassed. What pw-top is showing is just the result of the copy operation.

The only way to avoid the copy would be to remove the plugin from the pipeline. What you are seeing is normal.

**Comment by nekopsykose** [comment]
that makes sense then. thanks!
