### ISSUE TITLE
Feature request: channel volume sliders

### ISSUE THREAD

**Issue by ThatOneOcto** [wwmm/easyeffects#3405]
### EasyEffects Version

7.1.8

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

just volume sliders for left and right channel?

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>just volume sliders for left and right channel?

EasyEffects pipeline uses only 2 channels. Because almost all of the plugins we use are designed for stereo. Why would there be sliders beyond the ones for left and right?

**Comment by ThatOneOcto** [comment]
im asking to add sliders for left and right, i must be stupid if i cannot find them

**Comment by wwmm** [comment]
>im asking to add sliders for left and right

Oh... Although it is possible adding separated input and output gain controls for each channel will require changes to each plugin window as well for each plugin backend... It does not seem like this is going to be useful often enough to justify the effort...

What is the reason why you want these controls? Depending on what it is there may be easier ways to achieve the same result.

**Comment by ThatOneOcto** [comment]
ive got an audio imbalance issue and im trying to fix it temporarily until the company fulfills my warranty

**Comment by wwmm** [comment]
> ive got an audio imbalance issue and im trying to fix it temporarily until the company fulfills my warranty

Ok. There is a way to do this. Put the `Stereo Tools` plugin as the first plugin in the pipeline. This plugin has a balance control that should allow you to do some compensation.

**Comment by ThatOneOcto** [comment]
thank you
