### ISSUE TITLE
EasyEffects refused to launch

### ISSUE THREAD

**Issue by CuongTDSE172527** [wwmm/easyeffects#3406]
### EasyEffects Version

7.1.8-2

### What package are you using?

Arch (easyeffects)

### Distribution

Garuda Linux

### Describe the bug

(easyeffects:30731): Gtk-WARNING **: 15:12:31.800: Unknown key gtk-modules in /home/cuongjackfruit/.config/gtk-4.0/settings.ini

(easyeffects:30731): Adwaita-WARNING **: 15:12:31.868: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(easyeffects:30731): easyeffects-WARNING **: 15:12:31.979:      rnnoise.cpp:366 sie:  empty model name set, using the standard model
MESA-INTEL: warning: ../mesa-24.2.3/src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../mesa-24.2.3/src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 15:12:32.329: Error 71 (Protocol error) dispatching to Wayland display.

App refused to launch when trying to open from both the terminal and app launcher

**Comment by wwmm** [comment]
Definitely the same as #3402. This is a gtk4 bug users have worked around by forcing the opengl backend `GSK_RENDERER=gl easyeffects` instead of  vulkan. Unfortunately there is nothing I can do about it from my side.
