### ISSUE TITLE
Output defaults to EasyEffects sink when monitor is plugged in

### ISSUE THREAD

**Issue by nandor23** [wwmm/easyeffects#3421]
### EasyEffects Version

7.1.8

### What package are you using?

Arch (easyeffects)

### Distribution

EndeavourOS

### Describe the bug

Hello,
I have custom pipewire configuration to disable all HDMI ports, so the output doesn't switch to an external monitor when connected. This works fine, but when a monitor is connected, the output changes to the EasyEffect sink. I tried to disable the easyeffects node like any other HDMI node, but it does not take effect.

![image](https://github.com/user-attachments/assets/01b937e9-4b2e-46cc-80b6-1eb65317e4b6)

The configuration is the following `/etc/wireplumber/wireplumber.conf.d/51-alsa-disable.conf`:
```bash
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink"
      }
    ]
    actions = {
      update-props = {
         device.profile = "HiFi (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)"
      }
    }
  },
  {
    matches = [
      {
        node.name = "easyeffects_sink"
      }
    ]
    actions = {
      update-props = {
         node.disabled = true
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI1__sink"
      }
    ]
    actions = {
      update-props = {
         node.disabled = true
      }
    }
  },
]
```

The `Easy Effects Sink` is active, even though it is disabled.
```bash
❯ wpctl status
...
Audio
 ├─ Devices:
 │      53. sof-hda-dsp                         [alsa]
 │  
 ├─ Sinks:
 │      60. sof-hda-dsp Headphones              [vol: 1.00]
 │  *   75. Easy Effects Sink     
 ```
 
 ```bash
❯ wpctl inspect 75
id 75, type PipeWire:Interface:Node
    application.id = "com.github.wwmm.easyeffects"
    audio.position = "FL,FR"
  * client.id = "74"
    clock.quantum-limit = "8192"
  * factory.id = "19"
    factory.name = "support.null-audio-sink"
    library.name = "audioconvert/libspa-audioconvert"
  * media.class = "Audio/Sink"
    monitor.channel-volumes = "false"
    monitor.passthrough = "true"
  * node.description = "Easy Effects Sink"
    node.driver = "true"
    node.driver-id = "75"
    node.loop.name = "data-loop.0"
  * node.name = "easyeffects_sink"                  <----- this is the node name in the configuration
    node.passive = "out"
    node.virtual = "true"
  * object.serial = "80"
    port.group = "stream.0"
  * priority.session = "0"
 ```

### Expected Behavior

I should be able to disable the easyeffects sink.

**Comment by violetmage** [comment]
Instead of disabling output devices you don't want, you should simply set your preferred output device to have a higher priority, as described in this [issue on the wireplumber gitlab](https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/247)

**Comment by nandor23** [comment]
It already has the highest priority. The HDMI nodes are disabled, because wireplumber switches them automatically, even if they have lower priority sessions. This is why HDMI nodes are disabled.

The priority session of the EasyEffect sink is `0`. For some reason this sink can't be configured like the HDMI ones, the configuration does not apply to it.

**Comment by wwmm** [comment]
This kind of issue has to be reported to WirePlumber developers. All that EasyEffects does is asking PipeWire to load a `null-sink`. That is what our virtual devices are. And EasyEffects does not even ask the server to make our virtual devices the default. WirePlumber is taking this decision on its own. There is nothing we can do about it.

**Comment by nandor23** [comment]
Got it, thank you. I thought the configuration should have affected the EasyEffects sink too.
