### ISSUE TITLE
EasyEffects starts but does nothing: Empty List / No Audio Application available. Error: Unable to get background access

### ISSUE THREAD

**Issue by w-sky** [wwmm/easyeffects#3425]
### EasyEffects Version

7.1.9

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

Hi there, I recently noticed that PulseEffects, installed from Flatpak too, which still is working fine on my system, is long outdated.
But unfortunately EasyEffects doesn't work, it starts but as if no audio is playing, no graphic equalizer, status at bottom screen is "0,0 kHz, 0,0ms -100 -100 db" while music is playing regularly.
In Device Management, EasyEffects is set to "Use Default Output" but when I try to select one, there is none in drop-down selector.

I also tried using `flatpak permission-reset com.github.wwmm.easyeffects` several times, tried Reset Settings, but I am only seeing the error message about background access again when I open preferences, see below.

### Expected Behavior

See the graphic equalizer and being able to use effects.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
flatpak run com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 16:39:11.989: 	libportal.cpp:82	Background access has been denied

(easyeffects:2): easyeffects-WARNING **: 16:39:11.989: 	libportal.cpp:83	Please allow Easy Effects to ask again with Flatpak permission-reset com.github.wwmm.easyeffects

(easyeffects:2): easyeffects-WARNING **: 16:39:12.005: 	libportal.cpp:107	due to error, setting shutdown on window close state and switch to true
```
</details>

### Additional Information

I also checked `sudo apt install xdg-desktop-portal-gnome --no-install-recommends`, but it is already the newest version (42.1-0ubuntu2).

**Comment by w-sky** [comment]
PS: I also checked `sudo apt install xdg-desktop-portal-gnome --no-install-recommends`, but it is already the newest version (42.1-0ubuntu2).

**Comment by wwmm** [comment]
> EasyEffects is set to "Use Default Output" but when I try to select one, there is none in drop-down selector.

This is a sign that PipeWire's installation is not complete. Usually you also have to install a package named like `pipewire-pulse`. It will ask you to remove Pulseaudio. What is normal.

**Comment by violetmage** [comment]
In the normal configuration, ubuntu 22.04 LTS uses pulseaudio by default. Pipewire did not become the default in ubuntu until 22.10.

Now that 24.04 LTS has been released, the best solution is probably to upgrade to that. That way, no configuration will be needed for easyeffects to work.

**Comment by w-sky** [comment]
Well the Ubuntu 24.04 upgrade was imminent anyway, so I didn't try to solve the problem in Ubuntu 22.04. Instead, I just fought my way through the update today, it worked, and Easy Effects now is working perfectly.

I saw the "Background access has been denied" error once, but after applying `flatpak permission-reset com.github.wwmm.easyeffects` once I did not see that again.
