### ISSUE TITLE
Memory Leak with Spectrum "Lines"

### ISSUE THREAD

**Issue by geist01** [wwmm/easyeffects#3428]
### EasyEffects Version

7.1.8

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

As soon as I select spectrum type "lines" and play music (regardless of source) easyeffects begin to consume additional memory (more or less 100MB every 20 seconds). Switching to another type like bars or dots does not show this behavior and memory consumption immediately stops. The memory is not freed until I shut EA down.

### Expected Behavior

Same memory behaviour as the other types

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Are you using the default spectrum configuration and just changed the type to lines or have you selected a different number of points for example? So far I could not reproduce the memory leak.

Which gtk4 and cairo version do you have installed? Maybe you have a bad library version installed. The code used to draw each type is almost the same. The main difference is asking cairo to draw a line https://github.com/wwmm/easyeffects/blob/6472cb1f810dc37ebdba183dbbc38b021325da8e/src/chart.cpp#L558.

**Comment by wwmm** [comment]
And I would expect a leak related to the spectrum drawing to happen continuously. It is strange to happen in jumps.

**Comment by geist01** [comment]
I reset the configuration and changed only the spectrum type - the problem immediately appears. The memory increases constantly - my tool only reports in 100MB jumps.

I am currently using:
cairo 1.18.2-1 and gtk4 1:4.16.1-1 from the arch repositories.

There are slightly newer versions available now - I will update and test again.

**Comment by geist01** [comment]
using the newest version gtk4 1:4.16.1-1 indeed seems to fix this issue - memory consumption is normal again.

sorry for the noise.

**Comment by wwmm** [comment]
> using the newest version gtk4 1:4.16.1-1 indeed seems to fix this issue - memory consumption is normal again.
> 
> sorry for the noise.

Ok. No problems :-).
