### ISSUE TITLE
[feature-request] Unlimited amount of bands in parametric equalizer

### ISSUE THREAD

**Issue by zDEFz** [wwmm/easyeffects#3451]
### EasyEffects Version

easyeffects version: 7.1.8

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

I played around and found that I could 141 Band (oratory1990)
But bands are limited to 32.
Why is that? 

### Expected Behavior

Bands are unlimited

**Comment by zDEFz** [comment]
Opened at https://github.com/lsp-plugins/lsp-plugins-para-equalizer/issues/7

**Comment by wwmm** [comment]
> Opened at [lsp-plugins/lsp-plugins-para-equalizer#7](https://github.com/lsp-plugins/lsp-plugins-para-equalizer/issues/7)

Like explained by sadko an arbitrary number of bands is not a good match to how things are handled in EasyEffects. The problem isn't only the window controls. Our database, our presets infrastructure and the way they are bound to the window controls requires that the maximum number of bands is known.

As cool as an unlimited number of bands could theoretically be as explained by sadko it is hard to see this actually being necessary even no professional use cases. IT is not worth the insane amount of work its implementation requires.
