### ISSUE TITLE
Popup menu does not close when user click whatever opened it in the first place

### ISSUE THREAD

**Issue by herrenP** [wwmm/easyeffects#3462]
### EasyEffects Version

7.1.8

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro Linux 24.1.1

### Describe the bug

1. Open EasyEffects
2. Go to "Effects" tab
3. Add an effect (in my case "Equalizer")
4. Click the cog wheel icon on any of the bands (popup menu appears)
5. Open a list (e.g. click on "Mode")
6. Close the list (i.e. do not choose anything in the list - just click outside it)
7. Click cog wheel icon or click outside EasyEffects entirely

### Expected Behavior

Popup menu closes

### Debug Log

Debug log is silent from step 2 and onwards in this case

### Additional Information

To workaround you can press ESC on keyboard. This issue do not happen if you skip step 6.

**Comment by violetmage** [comment]
This is a known issue, it is an  architectural flaw in gtk.

EasyEffects has implemented a workaround, which can be enabled in the settings menu: [Hide Menus on Outside Clicks](https://wwmm.github.io/easyeffects/general.html)

**Comment by herrenP** [comment]
Ah, thanks for the info. The workaround setting is enabled though. Disabling it makes the issue disappear.

**Comment by wwmm** [comment]
> Ah, thanks for the info. The workaround setting is enabled though. Disabling it makes the issue disappear.

Actually it is the other way around. Enabled in this case means "following gtk's default behavior". But this causes the problem you are seeing. So disabling the feature that allows menus to be closed when clicking somewhere in the window is the workaround. In other words if you are affected by the gtk bug you have to set that preferences setting value to off like you did.

Unfortunately this is a gtk bug that has been around for years. And as we already have an open issue about it we can close this one.
