### ISSUE TITLE
Crystalizer works partially

### ISSUE THREAD

**Issue by pinkyzet366** [wwmm/easyeffects#3466]
### EasyEffects Version

7.17

### What package are you using?

Fedora

### Distribution

Nobara Linux 40

### Describe the bug

Crystalizer option in EasyEffects does work, but when im trying to play with bars and tones, the sound doesn't change. Mute and bypass works perfectly, but i cannot set it up how i want to.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>but when im trying to play with bars and tones

What do you mean by bars and tones? Although the crystalizer window resembles the one from an equalizer it does not work the same way. This plugin applies a simple peak enhancement  algorithm based on the signal second derivative. Each slider controls the enhancement strength for each band. But you are not going to have the same "feeling" as the sliders from an equalizer because it is a totally different algorithm.

**Comment by pinkyzet366** [comment]
> > but when im trying to play with bars and tones
> 
> What do you mean by bars and tones? Although the crystalizer window resembles the one from an equalizer it does not work the same way. This plugin applies a simple peak enhancement algorithm based on the signal second derivative. Each slider controls the enhancement strength for each band. But you are not going to have the same "feeling" as the sliders from an equalizer because it is a totally different algorithm.

Sorry for my bad english. Yeah i meant sliders. As for the feeling, when i was using pulseeffects, i got the same crystalizer tab, where it was working and when i was using the sliders to raise or lower the crystalizer effect on bands i was hearing the difference right away. In easyeffects however, it doesn't work like that, the sliders for me don't do anything to the sound at all

**Comment by wwmm** [comment]
The crystalizer implementation I did on PulseEffects was too aggressive when enhancing the signal and caused too much undesirable distortion in some cases. But in both cases it depends on the kind of signal being used how easy it is to notice the change. Usually it is easier to notice changes to the higher frequencies.

The crystalizer is one of the plugins I use every day. It is working fine. It is just more subtle than the one in PulseEffects. In some songs the effects is morenoticeable than on others.

**Comment by pinkyzet366** [comment]
> The crystalizer implementation I did on PulseEffects was too aggressive when enhancing the signal and caused too much undesirable distortion in some cases. But in both implementations it depends on the kind of signal being used how easy it is to notice the change. Usually it is easier to notice changes to the higher frequencies.
> 
> The crystalizer is one of the plugins I use every day. It is working fine. It is just more subtle than the one in PulseEffects. In some songs the effects is more noticeable than on others.

Oh, I see. I'll give it a try once again. Didn't know pulseeffects and easyeffects use different algorithms in that regard, thought this just didn't work properly. Thanks for the answer m8.
