### ISSUE TITLE
Deep Noise Remover borked

### ISSUE THREAD

**Issue by Milliw** [wwmm/easyeffects#3478]
### EasyEffects Version

7.1.9

### What package are you using?

Flatpak (Flathub)

### Distribution

Nobara 40 Gnome

### Describe the bug

When Deep Noise Remover is enabled, there is no sound output at all anymore.
I am using it on the microphone.

### Expected Behavior

Should work as expected (and before).

### Debug Log

<details><summary>Debug Log</summary><br/>

```
userx@nobara-pc:~$ G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects 
(process:2): easyeffects-DEBUG: 23:37:51.786: 	easyeffects.cpp:46	easyeffects version: 7.1.9
(process:2): easyeffects-DEBUG: 23:37:51.786: 	easyeffects.cpp:56	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 23:37:51.792: 	presets_manager.cpp:238	user presets directory already exists: /home/userx/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 23:37:51.792: 	presets_manager.cpp:238	user presets directory already exists: /home/userx/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 23:37:51.792: 	presets_manager.cpp:238	user presets directory already exists: /home/userx/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs
(easyeffects:2): easyeffects-DEBUG: 23:37:51.792: 	presets_manager.cpp:238	user presets directory already exists: /home/userx/.var/app/com.github.wwmm.easyeffects/config/easyeffects/rnnoise
(easyeffects:2): easyeffects-DEBUG: 23:37:51.792: 	presets_manager.cpp:238	user presets directory already exists: /home/userx/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 23:37:51.792: 	presets_manager.cpp:238	user presets directory already exists: /home/userx/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 23:37:52.074: 	easyeffects.cpp:71	Exitting the main function with status: 1

```
</details>

### Additional Information

Not sure but I think this issue is since yesterday where I enabled that effect also on sound output to Webcord client. I removed every effect but the issue still persists. All other effects I have enabled still work. When selecting and enabling the filter the input bars do pick-up sound though.

PipeWire graph looks normal as before.
![grafik](https://github.com/user-attachments/assets/c894bfb3-ccd1-4d88-814a-1a1abbc8b9a3)

**Comment by wwmm** [comment]
>When Deep Noise Remover is enabled, there is no sound output at all anymore.
I am using it on the microphone.

I can not reproduce this issue. As soon as there is voice in the audio I can here sound. Are you using the Flatpak package from Flathub or the one from Fedora custom repository? Only the one from the Flathub repository has the deep noise remover plugin.

**Comment by Milliw** [comment]
Nevermind... it just works again. I can not explain why because I did not change anything and when the issue was appearing yesterday I already did a system restart which changed nothing. Sorry to bother with that... :-/
