### ISSUE TITLE
Any popup should close when user clicks somewhere else than in the popup

### ISSUE THREAD

**Issue by JayBeeDe** [wwmm/easyeffects#3481]
### EasyEffects Version

7.1.9

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04

### Describe the bug

1. Click "Presets": popup appears
P1. Click somewhere else: popup is still there: user needs to click again "Presets" to remove popup
![image](https://github.com/user-attachments/assets/9af82098-3567-487d-9771-8dcc08a1f743)

2. Click "Add an effect": popup appears
P2. Click somewhere else: popup is still there: user needs to click again "Add an effect" to remove popup
![image](https://github.com/user-attachments/assets/60eb2e0f-0175-4296-883b-391eeabbfcbd)

3. Click "Players" section. Click "Excluded applications": popup appears
P3. Click somewhere else: popup is still there: user needs to click again "Excluded applications" to remove popup
![image](https://github.com/user-attachments/assets/630ebc74-9256-4311-b6d9-1e16bae96773)

### Expected Behavior

When a popup appears , it should disappear when user clicks somewhere else than in the popup.

**Comment by wwmm** [comment]
This is a gtk4 bug #1182 that is already known and that unfortunately has been present for years. I have investigated about it in the past and there was really nothing I could do to properly fix it on my side.

As we already have an issue related to it and the fix has to be done on gtk4 we can close this one.
