### ISSUE TITLE
Icons missing in flatpak install

### ISSUE THREAD

**Issue by danielkinahan** [wwmm/easyeffects#3483]
### EasyEffects Version

7.1.9

### What package are you using?

Flatpak (Flathub)

### Distribution

Endeavour OS (Arch)

### Describe the bug

Icons are missing in the flatpak version
![image](https://github.com/user-attachments/assets/21e3230c-579b-4aa6-b22d-1ec2535aeb85)

### Expected Behavior

Icons appear as they would when installed through pacman

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

This is with KDE Plasma. I'm using Breeze Dark icons. XDG_DATA_DIRS appears to be set correctly. My system is up to date and I've restarted it since installing flatpak and this package.

**Comment by wwmm** [comment]
> This is with KDE Plasma. I'm using Breeze Dark icons. XDG_DATA_DIRS appears to be set correctly. My system is up to date and I've restarted it since installing flatpak and this package.

KDE is not the problem. I use it too but with a native EasyEffects package I build mylself instead of Flatpak and the icons are fine. Maybe some additional package needed by the Flatpak package was not installed. Any thoughts @violetmage ?

**Comment by danielkinahan** [comment]
Yep I installed it with pacman earlier yesterday and the icons were there. It seems to be just the flatpak version.

**Comment by violetmage** [comment]
What is XDG_DATA_DIRS set as for you?

Can you get easyeffects to load icons from adwaita, or the system's default theme?

**Comment by danielkinahan** [comment]
Yeah this is probably an issue on my end. I'll close this now
