### ISSUE TITLE
IRS file not showing up in convolver menu

### ISSUE THREAD

**Issue by fewlesss** [wwmm/easyeffects#3527]
### EasyEffects Version

7.1.9

### What package are you using?

Flatpak (Flathub)

### Distribution

Arch Linux

### Describe the bug

When trying to select an impulse file to import into the convolver, the file does not show up in the file manager. The file I'm importing has the .irs file extension yet the file manager fails to recognize it.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
Are you able to put the irs here on github or providing a link to it so I can test it? BEsides the irs files extension I think we also check if it is a stereo impulse file or not.

**Comment by fewlesss** [comment]
Hello, here is a link to the file I'm trying to import: https://drive.google.com/file/d/1pwxoyOnUBFN4YT-oTHCIsaHrsH45mMP6/view?usp=drive_link

**Comment by fewlesss** [comment]
Also, i figured i might as well add what it looks like when i try to import a file:
![20241128_11h14m45s_grim](https://github.com/user-attachments/assets/bbe470d5-1355-498d-880d-52ff6e0c2ead)

As you can see, pretty much none of the folders on my computer are showing up either

**Comment by wwmm** [comment]
> As you can see, pretty much none of the folders on my computer are showing up either

Your impulse response file is fine. I can import it on my computer without problems. Based on your image it seems to me that Flatpak sandbox is what is getting in the way. I do not use the Flatpak package. I build a package using the AUR pkgbuild.

How is it for you @violetmage ? Is this how this import window is supposed to work in the Flatpak package?

**Comment by violetmage** [comment]
I am afk this week, so I can't double check. However, the screenshot is what I would expect to see if easyeffects tried to render the file picker itself: in this case the home directory inside the easyeffects flatpak sandbox.

Normally, gtk is supposed to realize it's running in a flatpak and invoke the xdg file picker portal, but for some reason that hasn't happened for OP. Could be any number of things, really not sure atm.

**Comment by fewlesss** [comment]
When i enter the file chooser section and hit request, the program crashes. However, i went into the wallpaper section and when i hit select a file, the same file manager popped up: 
![20241128_19h13m12s_grim](https://github.com/user-attachments/assets/3b277ce8-6cc2-41a0-a34c-192b5b8a81ec)

**Comment by violetmage** [comment]
It sounds like something is wrong with your systems xdg-portals.

What DE are you using?

**Comment by fewlesss** [comment]
im using hyprland

**Comment by mastr-ch13f** [comment]
Get **[Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)** and use it to configure your **Flatpak** app read/write/access permissions.

**Comment by violetmage** [comment]
@fewlesss Is `xdg-desktop-portal-gtk` installed?

**Comment by fewlesss** [comment]
no i do not, but i just installed it and i dont see any difference in the problem im having

**Comment by fewlesss** [comment]
> Get **[Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)** and use it to configure your **Flatpak** app read/write/access permissions.
> 
> EDIT: Or another method that might work is to change/rename the `.irs` file extension to `.wav`

yeah neither of those worked unfortunately

**Comment by violetmage** [comment]
To be clear, messing with xdg portals usually requires the system to be restarted for the changes to become effective.

**Comment by fewlesss** [comment]
Yeah i figured it might. I didn't restart right away because I was busy doing something at that moment, but i just restarted now and it seems to be working fine. thanks!
