### ISSUE TITLE
pwvucontrol not excluded

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#3530]
I discovered this new [app](https://flathub.org/apps/com.saivert.pwvucontrol) which is the PW version of pavucontrol.

Unfortunately it's not excluded like the old one. I suppose we don't want to show the following.

![Screenshot From 2024-12-01 09-37-16](https://github.com/user-attachments/assets/e9c85323-556d-4ff8-8916-3b2338fb375e)

I though we excluded sink monitors, but maybe they run those sinks in another way...

**Comment by Digitalone1** [comment]
I wanted to retrieve the app id, but it seems this app does not set it. So the only option is to exclude by the app name.

The weird thing is that `pw-dump` shows `"application.name": "pwvucontrol"` while `pw-cli info` shows `node.name = "pwvucontrol-peak-detect"` (see the following).

```
id: 115
	permissions: rwxm-
	type: PipeWire:Interface:Node/3
*	input ports: 2/65
*	output ports: 2/0
*	state: "running"
*	properties:
*		node.rate = "1/25"
*		node.latency = "1/25"
*		node.name = "pwvucontrol-peak-detect"
*		media.name = "Peak detect"
*		resample.peaks = "true"
*		stream.monitor = "true"
*		stream.is-live = "true"
*		node.want-driver = "true"
*		node.target = "56"
*		node.autoconnect = "true"
*		node.dont-reconnect = "true"
*		media.class = "Stream/Input/Audio"
*		channelmix.normalize = "true"
*		port.ignore-latency = "true"
*		adapt.follower.spa-node = ""
*		object.register = "false"
*		factory.id = "7"
*		clock.quantum-limit = "8192"
*		factory.mode = "merge"
*		audio.adapt.follower = ""
*		library.name = "audioconvert/libspa-audioconvert"
*		client.id = "156"
*		object.id = "115"
*		object.serial = "949"
*		node.driver-id = "56"
*	params: (9)
*	  3 (Spa:Enum:ParamId:EnumFormat) r-
*	  1 (Spa:Enum:ParamId:PropInfo) r-
*	  2 (Spa:Enum:ParamId:Props) rw
*	  4 (Spa:Enum:ParamId:Format) rw
*	  10 (Spa:Enum:ParamId:EnumPortConfig) r-
*	  11 (Spa:Enum:ParamId:PortConfig) rw
*	  15 (Spa:Enum:ParamId:Latency) rw
*	  16 (Spa:Enum:ParamId:ProcessLatency) rw
*	  17 (Spa:Enum:ParamId:Tag) -w
```

Which one should I pick?

**Comment by wwmm** [comment]
>Which one should I pick?

It may be better to use the node name because we do more or less the same thing that pw-cli is doing. It is strange that the application name tag is not shown by pw-cli. This is a sign we won't be able to see it too.
