### ISSUE TITLE
Can't change some parameters in Effects

### ISSUE THREAD

**Issue by Murazaki** [wwmm/easyeffects#3532]
### EasyEffects Version

7.1.9

### What package are you using?

NixOS

### Distribution

NixOS Unstable (25.05)

### Describe the bug

Can´t change Voice Activity Probability for some reason.

Also happens on Gate Sidechain Filters Frequencies. I've been using the native window as a fallback.

[Screencast_20241203_112210.webm](https://github.com/user-attachments/assets/62ee220d-7701-4f72-8bce-32d7096c2850)

### Expected Behavior

Value should be accepted when in range. If not in range or not accepted for another reason, it should be prompted by an error somewhere.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by zaps166** [comment]
I noticed it in some other filters, too. The only way to modify it is to select all together with unit sign (percent in this case) ("Ctrl+A"), write value and press enter key to accept.

**Comment by Murazaki** [comment]
> I noticed it in some other filters, too. The only way to modify it is to select whole text (together with unit sign, percent in this case) - "Ctrl+A", write value and press enter key to accept.

Tested and it does take the input but the value is reset after changing focus. I would guess the issue is on module refresh rather than input change.

**Comment by zaps166** [comment]
> > I noticed it in some other filters, too. The only way to modify it is to select whole text (together with unit sign, percent in this case) - "Ctrl+A", write value and press enter key to accept.
> 
> Tested and it does take the input but the value is reset after changing focus. I would guess the issue is on module refresh rather than input change.

Sorry, I gave wrong steps. Let me correct:

The only way to modify it is to select whole text (together with unit sign, percent in this case) - "Ctrl+A", write value and press tab key to focus-out to accept the new value.

**Comment by Murazaki** [comment]
> > > I noticed it in some other filters, too. The only way to modify it is to select whole text (together with unit sign, percent in this case) - "Ctrl+A", write value and press enter key to accept.
> > 
> > 
> > Tested and it does take the input but the value is reset after changing focus. I would guess the issue is on module refresh rather than input change.
> 
> Sorry, I gave wrong steps. Let me correct:
> 
> The only way to modify it is to select whole text (together with unit sign, percent in this case) - "Ctrl+A", write value and press tab key to focus-out to accept the new value.

Ok this works if you use Tab as a way to not validate the value, and you need to omit the unit. So clicking on Enter triggers a second verification (or a module configuration update ?) that clears out the value.

**Comment by Digitalone1** [comment]
It's weird, I can't reproduce this issue on my system. I can change the Voice Activity Probability values by clicking on +/- buttons or writing the value (even with the `%` sign).

**Comment by zaps166** [comment]
> It's weird, I can't reproduce this issue on my system. I can change the Voice Activity Probability values by clicking on +/- buttons or writing the value (even with the `%` sign).

That's right! However I noticed `LANC=C easyeffects` - works, so it means system localization (maybe comma separator issue?)

**Comment by Murazaki** [comment]
I do have two locales. 

```shell
❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
```

**Comment by Murazaki** [comment]
I think the space character is giving issues, if I write the value without spaces I can validate it.

**Comment by Digitalone1** [comment]
> That's right! However I noticed `LANG=C easyeffects` - works, so it means system localization (maybe comma separator issue?)

It may be. The locale is involved because the input validation is made getting the system locale. But I don't understand why it gives an error with an integer value.

**Comment by wwmm** [comment]
Gtk or one of the other libraries we use must have gone through some kind of change related to locale management. I can't reproduce this issue on my system and I also have mixed locale configuration with most of it in English and numbers in Brazilian Portuguese. I do not understand what is going on in the systems that have to force `LANG=C` or `LANG=en_US.UTF-8` =/.

**Comment by zaps166** [comment]
I have `LANG=pl_PL.utf8`. It requires to enable `pl_PL.UTF-8 UTF-8` in `/etc/locale.gen` and regenerate system locales (`sudo locale-gen`).

Maybe easyeffects could overwrite some locales at app startup which interfere with validator?

**Comment by wwmm** [comment]
>Maybe easyeffects could overwrite some locales at app startup which interfere with validator?

Overwriting a locale means not following the locale the user wants. What is not ideal. Specially when the issue does not happen for everybody. And it is not clear if this is even going to solve the problem. I have seen people that already have the system entirely in English having to export `LANG=en_US.UTF-8`. What does not make any sense. It feels like some kind of bad behavior on lower level libraries.
