### ISSUE TITLE
EasyEffects crashes on startup

### ISSUE THREAD

**Issue by C0D3-M4513R** [wwmm/easyeffects#3537]
### EasyEffects Version

7.1.9

### What package are you using?

NixOS (easyeffects)

### Distribution

NixOS 24.11

### Describe the bug

The Easyeffect service and gui crashes when starting the gui

### Expected Behavior

EasyEffects starts without crashing

### Debug Log

This log was created by `WAYLAND_DEBUG=1 easyeffects --gapplication-service` and then launching the Desktop application.

[output.log](https://github.com/user-attachments/files/18014706/output.log)

### Additional Information

This bug was occurred by a friend of mine (@AssiWelpe) on a laptop with an Optimus Prime chip an nvidia 4060 laptop gpu and AMD 8854HS w/ Radeon 750M Graphics.

Easyeffects was installed via the NixOS option: `services.easyeffects.enable = true;` 

Using flatpak (by installing the app via flatpak, stopping the user service and then running the app with the flatpak run command) the app starts and appears to work (but has many missing icons).

**Comment by wwmm** [comment]
>[4100030.491] {Display Queue} wl_display#1.error(wp_linux_drm_syncobj_manager_v1#66, 0, "surface already exists")
Gdk-Message: 23:03:41.481: Error 71 (Protocol error) dispatching to Wayland display.

Hum... This feel more like a problem between gtk and the GPU driver. I am not sure we can do something about.

**Comment by C0D3-M4513R** [comment]
When starting easyeffects under x11 the application starts (but a monitor doesn't work).
How would I start easyeffects under xwayland? Do I need to run `GDK_BACKEND=x11 easyeffects --gapplication-service` or `GDK_BACKEND=x11 easyeffects` ?

**Comment by C0D3-M4513R** [comment]
Apparently both ways work without issues. Thanks!
