### ISSUE TITLE
Flatpak version no DeepFilterNet plugin

### ISSUE THREAD

**Issue by NikSudo** [wwmm/easyeffects#3549]
### EasyEffects Version

7.19

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 40

### Describe the bug

Deep Noise Remover don't work on native Fedora package and flatpak version too (installed by `flatpak install flathub com.github.wwmm.easyeffects` command not from gnome software). It shows that "DeepFilterNet" is not installed 

Also flatseal shows that the application has the variables: LADSPA_PATH=/app/lib/ladspa. Don't know should it be like that but I can't find the directory on my system. 

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
You probably has installed the Flatpak package from Fedora's custom Flatpak repository. For some reason their package is not fully functional. Install the package from the Flathub repository.

**Comment by NikSudo** [comment]
I already installed it by `flatpak install flathub com.github.wwmm.easyeffects` not from gnome software application (gui)
If fedora still have some kind of redirect to their repository, please, share how to fix it

**Comment by violetmage** [comment]
Try uninstalling easyeffects

`flatpak remove com.github.wwmm.easyeffects`

Then, after making sure all copies of easyeffects are gone, try again with

`flatpak install flathub com.github.wwmm.easyeffects`

**Comment by NikSudo** [comment]
Nope, don't work. Ok, where I should to put the plugin file? I've tried to put it into `/usr/lib/ladspa` and also changed flatpak env var `LADSPA_PATH=/usr/lib/ladspa` - still don't work

**Comment by NikSudo** [comment]
Ok, I've tried to remove all my changed in flatseal, delete the flatpak, clean flatpak cache, and install the package again. This time it's working. Sorry for attention and thanks for help

**Comment by wwmm** [comment]
> Ok, I've tried to remove all my changed in flatseal, delete the flatpak, clean flatpak cache, and install the package again. This time it's working. Sorry for attention and thanks for help

No problems :-). As the problem has been solved we can close this issue.
