### ISSUE TITLE
Easy Effects can't detect any input/output devices

### ISSUE THREAD

**Issue by AzyWng** [wwmm/easyeffects#3585]
### EasyEffects Version

7.2.1

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 22.04.5 LTS

### Describe the bug

Easy Effects doesn't seem to be able to detect any of my input or output devices after I install it from Flatpak.

![image](https://github.com/user-attachments/assets/167d1110-b102-4e6b-bffc-0943182a504e)

### Expected Behavior

I expected EasyEffects to detect my input and output devices.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

My desktop environment is Xfce4.

**Comment by wwmm** [comment]
>Easy Effects doesn't seem to be able to detect any of my input or output devices after I install it from Flatpak.

This is a sign that PipeWire's installation is missing something. Usually a pacakge named like `pipewire-pulse`.

**Comment by AzyWng** [comment]
Even after installing pipewire-pulse, I still get the same issue.

**Comment by wwmm** [comment]
> Even after installing pipewire-pulse, I still get the same issue.

Did you reboot your computer? Kill EasyEffects and restart it in debug mode as explained at https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs. This way we will have more information.

**Comment by AzyWng** [comment]
Even after rebooting I still get the issue. Here's the output of starting EasyEffects in debug mode:
<details>
<summary> Output of debug mode</summary>
G_MESSAGES_DEBUG=easyeffects flatpak run com.github.wwmm.easyeffects
(process:2): easyeffects-DEBUG: 20:16:44.156: 	easyeffects.cpp:46	easyeffects version: 7.2.1
(process:2): easyeffects-DEBUG: 20:16:44.156: 	easyeffects.cpp:56	locale directory: /app/share/locale
(easyeffects:2): easyeffects-DEBUG: 20:16:44.161: 	presets_manager.cpp:238user presets directory already exists: /home/arty/.var/app/com.github.wwmm.easyeffects/config/easyeffects/input
(easyeffects:2): easyeffects-DEBUG: 20:16:44.161: 	presets_manager.cpp:238user presets directory already exists: /home/arty/.var/app/com.github.wwmm.easyeffects/config/easyeffects/output
(easyeffects:2): easyeffects-DEBUG: 20:16:44.161: 	presets_manager.cpp:238user presets directory already exists: /home/arty/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs
(easyeffects:2): easyeffects-DEBUG: 20:16:44.161: 	presets_manager.cpp:238user presets directory already exists: /home/arty/.var/app/com.github.wwmm.easyeffects/config/easyeffects/rnnoise
(easyeffects:2): easyeffects-DEBUG: 20:16:44.161: 	presets_manager.cpp:238user presets directory already exists: /home/arty/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/input
(easyeffects:2): easyeffects-DEBUG: 20:16:44.161: 	presets_manager.cpp:238user presets directory already exists: /home/arty/.var/app/com.github.wwmm.easyeffects/config/easyeffects/autoload/output
(easyeffects:2): easyeffects-DEBUG: 20:16:44.274: 	pipe_manager.cpp:1564	compiled with PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 20:16:44.274: 	pipe_manager.cpp:1565	linked to PipeWire: 0.3.69
(easyeffects:2): easyeffects-DEBUG: 20:16:44.280: 	pipe_manager.cpp:1535	core version: 0.3.48
(easyeffects:2): easyeffects-DEBUG: 20:16:44.280: 	pipe_manager.cpp:1536	core name: pipewire-0
(easyeffects:2): easyeffects-DEBUG: 20:16:44.281: 	pipe_manager.cpp:1447	found metadata: settings
(easyeffects:2): easyeffects-DEBUG: 20:16:44.281: 	pipe_manager.cpp:1301	Audio/Sink 41 auto_null with serial 79 has been added
(easyeffects:2): easyeffects-DEBUG: 20:16:44.281: 	pipe_manager.cpp:1301	Audio/Sink 42 easyeffects_sink with serial 85 has been added
(easyeffects:2): easyeffects-DEBUG: 20:16:44.281: 	pipe_manager.cpp:1301	Audio/Source/Virtual 37 easyeffects_source with serial 86 has been added
(easyeffects:2): easyeffects-DEBUG: 20:16:44.281: 	pipe_manager.cpp:265	Audio/Sink 41 auto_null has been removed
(easyeffects:2): easyeffects-DEBUG: 20:16:44.282: 	pipe_manager.cpp:1663	easyeffects_sink node successfully retrieved with id 42 and serial 85
(easyeffects:2): easyeffects-DEBUG: 20:16:44.282: 	pipe_manager.cpp:1668	easyeffects_source node successfully retrieved with id 37 and serial 86
(easyeffects:2): easyeffects-DEBUG: 20:16:44.297: 	lv2_wrapper.cpp:124	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 20:16:44.299: 	plugin_base.cpp:406	soe: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 20:16:44.300: 	plugin_base.cpp:406	soe: spectrum successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 20:16:44.300: 	stream_output_effects.cpp:179	The output device auto_null is not available. Aborting the link
(easyeffects:2): easyeffects-DEBUG: 20:16:44.314: 	lv2_wrapper.cpp:124	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
(easyeffects:2): easyeffects-DEBUG: 20:16:44.315: 	plugin_base.cpp:406	sie: output_level successfully connected to PipeWire graph
(easyeffects:2): easyeffects-DEBUG: 20:16:44.317: 	plugin_base.cpp:406	sie: spectrum successfully connected to PipeWire graph

(easyeffects:2): easyeffects-WARNING **: 20:16:44.317: 	rnnoise.cpp:366	sie:  empty model name set, using the standard model
(easyeffects:2): easyeffects-DEBUG: 20:16:44.317: 	stream_input_effects.cpp:214	No input device set. Aborting the link
(easyeffects:2): easyeffects-DEBUG: 20:16:44.317: 	stream_output_effects.cpp:179	The output device auto_null is not available. Aborting the link
(easyeffects:2): easyeffects-DEBUG: 20:16:44.317: 	stream_input_effects.cpp:214	No input device set. Aborting the link
easyeffects-INFO: 20:16:44.317: 	application.cpp:76	disabling global bypass
(easyeffects:2): easyeffects-DEBUG: 20:16:44.319: 	output_level.cpp:45	soe: output_level: PipeWire blocksize: 1024
(easyeffects:2): easyeffects-DEBUG: 20:16:44.319: 	output_level.cpp:46	soe: output_level: PipeWire sampling rate: 48000
(easyeffects:2): easyeffects-DEBUG: 20:16:44.319: 	spectrum.cpp:122	soe:  creating instance of comp delay x2 stereo for spectrum A/V sync
(easyeffects:2): easyeffects-DEBUG: 20:16:44.321: 	output_level.cpp:45	sie: output_level: PipeWire blocksize: 1024
(easyeffects:2): easyeffects-DEBUG: 20:16:44.321: 	output_level.cpp:46	sie: output_level: PipeWire sampling rate: 48000
(easyeffects:2): easyeffects-DEBUG: 20:16:44.321: 	spectrum.cpp:122	sie:  creating instance of comp delay x2 stereo for spectrum A/V sync
(easyeffects:2): easyeffects-DEBUG: 20:16:44.345: 	application_ui.cpp:109	Icon Theme HighContrast detected
(easyeffects:2): easyeffects-DEBUG: 20:16:44.514: 	stream_output_effects.cpp:179	The output device auto_null is not available. Aborting the link
(easyeffects:2): easyeffects-DEBUG: 20:16:44.551: 	node_info_holder.cpp:10441, auto_null finalized
</details>

**Comment by AzyWng** [comment]
After some googling, I managed to fix it by following the instructions in an askubuntu question, specifically the instructions to run the commands
`sudo touch /usr/share/pipewire/media-session.d/with-pulseaudio
systemctl --user restart pipewire-session-manager`
in the terminal.

Link here:
https://askubuntu.com/questions/1403665/no-sound-output-devices-listed-after-upgrade-from-21-10-to-22-04
