### ISSUE TITLE
[Question] [GUI] Why can I move applications vertically?

### ISSUE THREAD

**Issue by TZubiri** [wwmm/easyeffects#559]
I'm guessing that the order might matter if multiple applications are applied simultaneously?

**Comment by wwmm** [comment]
Move applications? Are you talking about being able to move the plugins names up and down by dragging the mouse or by using the up and down buttons? If yes your guess is right. Plugins order may be important in some situations.

**Comment by TZubiri** [comment]
Yep, that's it, thank you for clarifying.

FYI, the GUI calls them applications.

![applications pulseffects](https://user-images.githubusercontent.com/8901363/63231068-918eac80-c1ec-11e9-976c-03bc1dc3d49d.png)

**Comment by wwmm** [comment]
It is a little confusing indeed. But word application in this case refers to the audio applications section that is shown by default when PE window is shown. If you click over the name `Applications` you go back to the audio apps section.

**Comment by wwmm** [comment]
But on a second look it feels like a title for the plugins section. This possibility never crossed my mind XD

**Comment by Mlocik97-issues** [comment]
@wwmm when I first time opened app, I thought it same as title... Propably because text is placed in box with smaller height.

**Comment by wwmm** [comment]
Good point. I will try to do that :-)

**Comment by Mlocik97-issues** [comment]
And when we are talking about GUI, I found some ugly things... like in Bass Enhancer in "Amount" I have 2dB... but in Exciter in "Amoun" only number 2 without unit... there are some other similiar things.. For example numbers are in few inputs centered, and in few inputs not... on few places is missing minus before number.

**Comment by wwmm** [comment]
Thanks. I think that the db icon must have been unintentionally removed at some point. I did not notice.  Fixed!

It would be good to have images about the centering problem. Only negative numbers should have minus before them. Sometimes the db value is negative sometimes it isn't. So this doesn't seem to be a problem.

**Comment by Mlocik97-issues** [comment]
https://youtu.be/DEqVsZNXOSQ

video, at start look on "harmonic input value", there are differences about few pixels,... same for differences between same "tools" input(mic) and output(speaker)... etc etc.

**Comment by wwmm** [comment]
When switching between the exciter and the bass enhancer I can notice it. I wonder if there is anything I can do about it. It feels like a GTK decision to do this shift.

The range value is positive. So that is ok. this parameter is related to the audio content dynamic range. Having it red is not a  problem. IT just means that the range is high.

**Comment by wwmm** [comment]
In some places the numbers are not centered because of the unit icon. But I don't know if there is a way to compensate for that. Maybe people more experienced with GTK may know how. At this moment I have no idea XD

**Comment by wwmm** [comment]
Fixed in EasyEffects 6.0.0
