### ISSUE TITLE
Suggest plugins to install when not found

### ISSUE THREAD

**Issue by tannercollin** [wwmm/easyeffects#578]
To avoid the confusion I had in #577, I'd like to suggest giving the user feedback when a plugin isn't found.

A warning / error above the toggle slider would work:

![Screenshot from 2019-09-26 22-06-18](https://user-images.githubusercontent.com/6752449/65741627-fc63bb00-e0a9-11e9-8388-1497ca1a7b59.png)

It should at least tell me which plugin is needed. Bonus points for where I can get it and which type (JACK, lv2, LADSPA, etc). Docs on how to install the plugin would be great too.

Currently the UI makes no distinction between an effect that's "off" and a plugin that's missing.

**Comment by Digitalone1** [comment]
That would be useful, I had issue in the past understanding which package was needed for a specific plugin.

**Comment by wwmm** [comment]
I think that the credits are enough to help the user. Dealing with the way each distribution handles package names would be a nightmare.

**Comment by tannercollin** [comment]
I think something to distinguish between an effect that's off and a plugin that's not installed would be handy. You could also display the plugin name instead of a distro's package name.
