### ISSUE TITLE
[AutoGain Feature Request] Long Term height

### ISSUE THREAD

**Issue by ghost** [wwmm/easyeffects#584]
Hello, we have momentary, short-term, integrated values, but it would be nice to have Long-term value (last 1 minute)... It would help so much with retarded YouTube (why YT hasn't audio normalizer). Thanks.

**Comment by rijnhard** [comment]
for audio engineers, this won't matter much. But for users watching movies this would be great. Just watch a Harry Potter movie and you will understand.

**Comment by X-m7** [comment]
For anyone wanting an option like this the Integrated metric now has a customizable history limit in the Git master branch, so if set to say 60 seconds it essentially becomes a long-term value.

**Comment by wwmm** [comment]
With the work on the current master branch we can close this issue.
