### ISSUE TITLE
[Feature Request] Use static value instead integrated value

### ISSUE THREAD

**Issue by ghost** [wwmm/easyeffects#587]
Feature Request
Module: AutoGain

Hello

It would be fine, if user would have option to switch from using integrated value to using static value. Because when I boot computer, first minutes is integrated value unstable. It can help too, if something is watching film, which is quiter, and then he want listen to music, then integrated value is too low so then it's loud too much. But if I can use static value instead, then it's perfectly how I set.

p.s. for Wellington Wallace, I know I'm asking, and want too much features, but Your project is really really good, and I'm happy if I can give some ideas how to change to even better.

**Comment by wwmm** [comment]
No problems :-)

Are you sure that a static value would be different than a manual volume adjustment? At first sight it seems to me that you would have to find a different static value for each content. In the end this would be the same as manually adjusting the volume.

**Comment by Mlocik97-issues** [comment]
> Are you sure that a static value would be different than a manual volume adjustment? At first sight it seems to me that you would have to find a different static value for each content. In the end this would be the same as manually adjusting the volume.

Momentary, Short-Term and in future Long Term will be used normally, so it's not problem, but this will help a lot of things. For example at start, when Integrated value is unstable, it change volume too fast, even if Your weight is 1-2-5 and You don't want it.
Second thing is that, your Integrated value change to nearly static value, if your PE is running for long long time (6 hours for example), then it does not matter if you use integrated or static. Integrated have advantage if your audio is playing for long time, but not excessively long.
And ofc, if You use static value, You don't need to worry about clipping if You play loud audio after playing something not too loud for long time.

**Comment by Mlocik97-issues** [comment]
And there is one more thing, threshold in other plugins will work more correctly. Because output will be not too variable.

**Comment by wwmm** [comment]
Which threshold? In any case these plugins are probably being more aggressive when controlling the signal amplitude. The problem with this is that the more aggressive you are the more you kill dynamic range. Sometimes this is what you want. Sometimes it isn't.

**Comment by Mlocik97-issues** [comment]
for example compresor or deeser put after autogain. With setting, 1-2-5 weights it depent on integrated value too much, how loud output from autogain is. When integrated is low, output is hight and you need set threshold on hight value too. (-5dB for example), but in opposit situation you need threshold on low value (-20dB). With static value this will be solved as well. (It will not solve it totally, but it will help.)

sry for my bad English, I hope you understand what I mean.

**Comment by wwmm** [comment]
With the way the autogain works now this is probably not necessary anymore.
