### ISSUE TITLE
Switching output results in sound artefacts

### ISSUE THREAD

**Issue by Lailah** [wwmm/easyeffects#682]
**System**:  Fedora 32 KDE Spin 
**Software version**:  4.7.1
**Hardware**: ThinkPad T440s (all Intel), headphones Grundig (3.5mm jack), Bluetooth speakers Comiso. 
**Issue**:  When I switch output, for example plugging my headphones or turning off the speakers, there are some strange noises and then all subsequent sound is muted. 
Example:  I turn my laptop on, start session and after a moment I decide to plugin my headphones.  Then some sound is like it has an echo, or there are some artefacts or noises. If I want to listen to music or watch something all sound will be muted.  After that, the only option is rebooting and not switching outputs. 
At the moment I have my laptop with a dedicated headphone plugged to it at all times to avoid issues.  These happens when I switch between any of my outputs:  internal laptop speakers, headphones and Bluetooth speakers.

**Comment by wwmm** [comment]
It seems that there is a third party tool messing with our audio routing again =/. First kill the current PE instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Let's see what is printed in the terminal.

**Comment by Lailah** [comment]
I did what you asked now it sounds fine. I'm going to restart and try again just in case.  This is the first result.  See file attached. 
[Errors.txt](https://github.com/wwmm/pulseeffects/files/4655432/Errors.txt)

**Comment by wwmm** [comment]
Nothing wrong in the logs. But have in mind that your current Pulseaudio install `13.99.1` is a development release. It may be going through changes that may not have been integrated by Fedora 32 yet. One of them is directly related to KDE `Removed KDE specific routing configuration` https://fossies.org/diffs/pulseaudio/13.0_vs_13.99.1/NEWS-diff.html

**Comment by Lailah** [comment]
> Nothing wrong in the logs. But have in mind that your current Pulseaudio install `13.99.1` is a development release. It may be going through changes that may not have been integrated by Fedora 32 yet. One of them is directly related to KDE `Removed KDE specific routing configuration` https://fossies.org/diffs/pulseaudio/13.0_vs_13.99.1/NEWS-diff.html

I didn't know I had a development release. I installed it via DNF like everything else. 
Okay, thanks for the heads up. So far it's working again.

**Comment by Lailah** [comment]
I still have the issue but it doesn't show up when Pulse Effects window is open, only when it's running on background. If I don't use Pulse Effects at all there are no problems with sound.

**Comment by wwmm** [comment]
Weird. If it were the other way around it could be some kind of higher cpu usage. But PE is less demanding when no window is shown. The sound still goes away or is there only noises?

**Comment by Lailah** [comment]
The sound goes away. That's the first hint. And when I try to raise it or lower it is when the noises start.  This won't change unless I keep the window open or not use PE at all.

**Comment by wwmm** [comment]
Let's try to get logs again but this time running as a service `G_MESSAGES_DEBUG=pulseeffects pulseeffects --gapplication-service`. This way the window will not be shown. Maybe this time we see something useful. Remember to kill PE first.

**Comment by Lailah** [comment]
I hate this. 
Now it works! 
Please, see the output in the text file attached.
[Messages debug.txt](https://github.com/wwmm/pulseeffects/files/4796931/Messages.debug.txt)

**Comment by wwmm** [comment]
Nothing strange in the logs. These kind of problems that come and go randomly are the worst. Does it work only when debug mode is enabled? Or is it working even without debug? In any case I think you will have to keep trying to run it in debug mode until the problem happens.

**Comment by wwmm** [comment]
As things are so different in EasyEffects 6.0.0 it is probably better closing this issue and opening  a new one if similar problems happens with the new version too.
