### ISSUE TITLE
Memory Leaks/Thrashing occuring if PulseEffects (4.7.2-2) is left alone for too long.

### ISSUE THREAD

**Issue by hikikostar** [wwmm/easyeffects#697]
I've encountered several instances where I left my computer (8GB DDR3, Manjaro 20.0.2) on overnight and the next morning I find my computer in an extremely sluggish state. Before I left the PC alone 2GB was occupied by other active processes.I was able to open the Task Monitor to find PulseEffects using 8GB of memory, 2GB of which had spilled into the swapdisk. Can't find a way to intentionally trigger this, just seems to happen randomly when left alone.

**Comment by wwmm** [comment]
I never saw that happening. First let's see if there is something odd in your logs. Kill PE `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

Many months ago we had a memory leak whose source was one of the plugins we used. But that was fixed.
