### ISSUE TITLE
[Feature Request] "preset-only" view

### ISSUE THREAD

**Issue by stuartlangridge** [wwmm/easyeffects#698]
I sometimes use PulseEffects to apply input (microphone) effects dynamically while doing voice work. I've already set up various presets for this, and it's really useful! So, a feature request: it would be very handy if there were a way of switching to a view which only shows the preset switcher; that is, the whole application displays only as a list of already-defined presets and that's it. So it would then be very easy to switch between presets dynamically. (It should, of course, also be very easy to switch back _out_ of this mode and back into "normal" PulseEffects!)

**Comment by wwmm** [comment]
Although the idea is interesting the implementation is not simple and I am not sure it would fit well in the current interface used in EasyEffects. I think it is time to close this.
