### ISSUE TITLE
Would it be possible to run this on MacOS (Catalina)?

### ISSUE THREAD

**Issue by sidbmw** [wwmm/easyeffects#704]
Is it possible to run this on Macos? Been trying to get it set up from source...but is it even possible?

**Comment by wwmm** [comment]
As I do not have a Macos I have no idea. People were able to make it work on FreeBSD. But from FreeBSD and Linux to Macos there is probably a big difference. PulseEffects has a few dependencies but the key ones are Pulseaudio, GTKMM 3 and GStreamer. Assuming you are able to make them work in a Mac PulseEffects should be able to run too.

**Comment by wwmm** [comment]
Before trying to compile PulseEffects I would try to install GStreamer and Pulseaudio first. THen I would try to run this GStreamer command:
`gst-launch-1.0 pulsesrc ! queue ! pulsesink`

If it fails there is no point in trying to compile PulseEffects.

**Comment by sidbmw** [comment]
> Before trying to compile PulseEffects I would try to install GStreamer and Pulseaudio first. Then I would try to run this GStreamer command in a terminal:
> `gst-launch-1.0 pulsesrc ! queue ! pulsesink`
> 
> If it fails there is no point in trying to compile PulseEffects.

I have both GStreamer and Pulseaudio installed through homebrew. I tried running `gst-launch-1.0 pulsesrc ! queue ! pulsesink` and got `WARNING: erroneous pipeline: no element "pulsesrc"`.

Any idea?

**Comment by wwmm** [comment]
The pulsesrc plugin is not installed. Were you able to install `gst-plugins-good`? This is the GStreamer library that should provide `pulsesrc`

**Comment by sidbmw** [comment]
Hmm...`gst-plugins-good` is installed.

**Comment by wwmm** [comment]
On Arch Linux I have this file `/usr/lib/gstreamer-1.0/libgstpulseaudio.so`. Try to see if it exists in your system. If you have this file then the problem must be a missing environmental variable setting the path to search for libraries.

**Comment by sidbmw** [comment]
`libgstpulseaudio.so` doesn't seem to exist for some reason. There is a lot of `libgst....'s' though.

`gst-plugins-good` and `gst-plugins-base` are all 1.16.2 while  `gst-plugins-bad` is 1.16.2_2 if that helps.

**Comment by wwmm** [comment]
I also have GStreamer `1.16.2`. Could it be that the Macos packages are compiled without Pulseaudio support? In a way it makes sense as Macos probably has its own sound server.

**Comment by sidbmw** [comment]
I'm not sure. Would it be possible to compile from source and therefore get `libgstpulseaudio.so`?

**Comment by wwmm** [comment]
It should be. But I never tried.

**Comment by sidbmw** [comment]
Alright, I'll give it a shot

**Comment by austinbutler** [comment]
Note that even a native solution is having plenty of trouble getting a working equalizer on Catalina: https://github.com/bitgapp/eqMac/issues/257

**Comment by Minecon724** [comment]
has anyone had any luck? is this even possible?

**Comment by vchernin** [comment]
For easyeffects gtkmm, gstreamer and pulseaudio are no longer dependencies, but easyeffects is dependent on pipewire. I have no idea if it is possible to run pipewire on macos.

**Comment by Minecon724** [comment]
> For easyeffects gtkmm, gstreamer and pulseaudio are no longer dependencies, but easyeffects is dependent on pipewire. I have no idea if it is possible to run pipewire on macos.

quick googling returned absolutely nothing about pipewire and mac, so for now i assume its not possible.
how about the legacy version using pulse?

**Comment by wwmm** [comment]
>how about the legacy version using pulse?

GStreamer probably works to some extent in macos. The question is if Pulseaudio runs there.

**Comment by Minecon724** [comment]
> > how about the legacy version using pulse?
> 
> GStreamer probably works to some extent in macos. The question is if Pulseaudio runs there.

seems like [pulseaudio is installable](https://formulae.brew.sh/formula/pulseaudio), I'm not sure how it works though, will look into it sometime later
