### ISSUE TITLE
Applications become disabled when changing output source on Solus Budgie

### ISSUE THREAD

**Issue by dan-dr** [wwmm/easyeffects#726]
Hey,
First of all thanks for this amazing application.

I'm having an issue in Solus with Budgie DE. Everything works fine but if I change outputs using Budgie's Raven sidebar, all the applications in PE become disabled and I need to enable them again. If I use `pavucontrol` to change the outputs everything works fine.

When running with `G_MESSAGES_DEBUG=pulseffects pulseeffects` the only difference I see when using Raven vs pavucontrol is 
```
(pulseeffects:890369): pulseeffects-DEBUG: 16:18:34.517: sie: No app wants to play audio. We will pause our pipeline.
(pulseeffects:890369): pulseeffects-DEBUG: 16:18:34.518: sie: PLAYING -> PAUSED -> VOID_PENDING
```

**Comment by wwmm** [comment]
> I'm having an issue in Solus with Budgie DE. Everything works fine but if I change outputs using Budgie's Raven sidebar, all the applications in PE become disabled and I need to enable them again. If I use pavucontrol to change the outputs everything works fine.

This sounds like the same problem we face with Gnome system settings https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/494. `Budgie's Raven sidebar` isn't only changing the devices. It is iterating over all audio applications and asking Pulseaudio to move them to this new default. This will break any custom audio routing.

At least the problem with Gnome will be worked around by Pulseaudio developers when they release `Pulseaudio 14`. But as far as I know this blacklist only has gnome. Pulseaudio developers might not even know that Budgie has also taken this unfortunate decision.

**Comment by wwmm** [comment]
The ideal solution would be that desktops did not break custom routing. Pulseaudio developers should not be forced to blacklist them.
