### ISSUE TITLE
[Request] pulseeffects -l to update the PE UI with the loaded preset

### ISSUE THREAD

**Issue by ParticleMon** [wwmm/easyeffects#749]
It would be helpful if pulseeffects -l would update the PE UI with the loaded preset. Ideally, the PE UI would be updated whether or not it's currently running but at least when the UI is subsequently executed.

If the user wants to adjust plugin settings after a preset has been loaded with pulseeffects -l, the user must load the preset again in the UI, redundantly, so that the UI indicates the expected preset name, plugins, and plugin settings.

**Comment by hashworks** [comment]
Additionally, `--load-preset` always returns Exit Code 1 for me. It applies the preset just fine.

**Comment by wwmm** [comment]
At leastin EasyEffects that is what happens. So we can close this issue.

>Additionally, --load-preset always returns Exit Code 1 for me. It applies the preset just fine.

I am not sure we can do something about this. At  the end of the operation we have to call the Gtk's base class method `return G_APPLICATION_CLASS(application_parent_class)->command_line(gapp, cmdline);`. But besides this there is also the "unique instance" handling that is done by GTK. When `easyeffects -l preset_name` is executed while an EE instance is already running in the background GTK will finish by itself the new instance and pass the information to the one that was already in the background. I think that changing the exit code is out of my reach.
