### ISSUE TITLE
WebRTC produces silent output when Pulseaudio is set to use 96k sample rate

### ISSUE THREAD

**Issue by abelits** [wwmm/easyeffects#754]
Setting "default-sample-rate = 96000" in /etc/pulse/daemon.conf results in silent output when WebRTC plugin is enabled (even if internally everything is off). Everything works when sample rate is set to 48000, and pulseaudio is restarted.

**Comment by wwmm** [comment]
The maximum sampling rate supported by GStreamer's webrtc plugin is 48 kHz https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-webrtcdsp.html. AS I did not write this plugin I do not know the reason why it does not accepts higher rates.

This plugin is part of `gst-plugins-bad`. So its developers might respond to questions in this site https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad

**Comment by abelits** [comment]
Then maybe pulseeffects should do something when such plugin is enabled. Change the sample rate? Disable plugin and show a message?

**Comment by wwmm** [comment]
As EasyEffects does not use GStreamer anymore I had to move to another plugin. This issue can be closed.
