### ISSUE TITLE
System audio skipping every few seconds with pulseeffects enabled

### ISSUE THREAD

**Issue by have-a-boy** [wwmm/easyeffects#764]
#### Background info:  
I'm using pulseffects 4.7.1 on Fedora 32 (from the official repo). The only module I have enabled currently is the equalizer. I'm using the headphone jack on the audio card itself.

#### Specs:  
- Ryzen 1800X
- 16 GB RAM
- Fedora 32 Workstation (Gnome)
- ASUS Xonar Essence STX PCIe sound card

#### Description:  
Every few seconds (sometimes a minute or two) the audio output randomly skips a few dozen milliseconds (more or less), occasionally creating a popping sound as well. It sounds like a buffer underrun. It's most noticeable when listening to music, but it happens with any kind of audio playback from any application that I've tested (Firefox, Rhythmbox and Spotify for example).

Disabling pulseeffects or unchecking the application that I'm listening to in the GUI eliminates the issue reliably. I've listened to at least 10 minutes worth of audio with no issues and re-enabling the application immediately made it reappear. I'll be testing this more though.

The weird thing about this problem is that I've been using pulseeffects with this same exact setup for a few months now, but I am all but certain this issue has only started occurring since a few weeks ago. I can at least remember carefully listening to a few hours worth of glitchless audio, while I was playing with the equalizer initially...

Are there any settings I could try playing around with to see if that solves the issue? Maybe some setting was changed by an update or something.

**Comment by wwmm** [comment]
Although a lot has changed from 4.7.1 to 4.8.0 I do not remember changes that could be related to this. You could try to play a little with the `buffer`, `latency` and `blocksize` values but I am not confident their values are the cause of the problem
![Screenshot from 2020-08-24 19-57-52](https://user-images.githubusercontent.com/16225172/91104507-50717980-e644-11ea-9d0f-df0fc3980a06.png)

You could also try to run in debug mode so we can see if there is anything out of the ordinary happening. Kill pulseeffects with the command `pulseeffects -q` and restart it with `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. But this does not seem like the kind of issue that is shown in the logs...

**Comment by wwmm** [comment]
If possible try to do the test I suggested in this post from another issue https://github.com/wwmm/pulseeffects/issues/744#issuecomment-671408037. If it reproduces the audio skipping then the problem is in GStreamer or Pulseaudio. If it doesn't one of our plugins could be the source.

**Comment by arhuaco** [comment]
I solved this by running pulseaudio as a real-time process. In /etc/pulse/daemon.conf:

     high-priority = yes
     nice-level = -15
     realtime-scheduling = yes
     realtime-priority = 90  

Since most computers are multicore and CPU usage is not big with EQ, this is not an issue for me.
