### ISSUE TITLE
effects grayed out again, plugin was not found (4.8.0 in Ubuntu 20.10)

### ISSUE THREAD

**Issue by arighi** [wwmm/easyeffects#787]
I'm using pulseeffects 4.8.0 in Ubuntu 20.10. I'm experiencing an issue similar to #771 and I get a bunch of "plugin was not found" warnings at startup (see below).

Apparently this problem started to happen when libgstreamer-plugins-bad1.0-0 has been updated from 1.16.2-2.3ubuntu1 to 1.16.2-2.3ubuntu2 (at least looking at the apt logs this is the only related package that seems to have caused the problem).

See also: https://bugs.launchpad.net/bugs/1896191

I've already tried to purge/reinstall the packages, clean up the caches, reboot, but the plugins are still broken. Any help/suggestion is appreciated. Thanks in advance.

$ G_MESSAGES_DEBUG=pulseeffects pulseeffects
(process:136796): pulseeffects-DEBUG: 17:48:46.281: main: locale directory: /usr/share/locale
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: system input presets directory: "/etc/xdg/xdg-awesome/PulseEffects/input"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: system output presets directory: "/etc/xdg/xdg-awesome/PulseEffects/output"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects/input
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects/output
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.293: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects/autoload
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.396: application: PE version: 4.8.0
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.396: pulse_manager: context is connecting
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: context is authorizing
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: context is setting name
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: context is ready
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: protocol version: 33
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: Pulseaudio version: 13.99.1
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: default pulseaudio source: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y70V2JM074A5BA-00.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.397: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.398: pulse_manager: default pulseaudio sink sampling rate: 48000 Hz
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.398: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.398: pulse_manager:  failed to get sink info: PulseEffects_apps
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.403: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.403: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.404: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.404: pulse_manager: default pulseaudio source audio format: s32le
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.404: pulse_manager:  failed to get sink info: PulseEffects_mic
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.410: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.430: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.430: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.430: limiter plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.430: compressor plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.431: filter plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.431: equalizer plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.431: reverb plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.431: bass_enhancer plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.432: exciter plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.432: crossfeed plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.432: maximizer plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.433: multiband_compressor plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.433: loudness plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.433: gate plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.433: pitch plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.433: multiband_gate plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.434: deesser plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.434: stereo_tools plugin was not found!
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.437: sie: convolver is already disabled
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.440: sie: crystalizer is already disabled
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.442: sie: autogain is already disabled

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.443: delay plugin was not found!
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.450: soe: using output device: PulseEffects_mic
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.450: soe: using input device: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y70V2JM074A5BA-00.analog-stereo

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.451: limiter plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.451: compressor plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.451: filter plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.451: equalizer plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.452: reverb plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.452: gate plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.452: deesser plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.452: pitch plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.452: webrtc plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.453: multiband_compressor plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.453: multiband_gate plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.453: stereo_tools plugin was not found!

(pulseeffects:136796): pulseeffects-WARNING **: 17:48:46.453: maximizer plugin was not found!
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: system input presets directory: "/etc/xdg/xdg-awesome/PulseEffects/input"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: system output presets directory: "/etc/xdg/xdg-awesome/PulseEffects/output"; 
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects/input
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects/output
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: user presets directory already exists: /home/righiandr/.config/PulseEffects/autoload
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: presets_manager: destroyed
pulseeffects-INFO: 17:48:46.456: application: disabling global bypass
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: sie: bypass is already disabled
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.456: soe: bypass is already disabled
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:46.929: convolver_ui: irs directory already exists: /home/righiandr/.config/PulseEffects/irs
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:47.478: sie: spectrum enabled
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:47.479: soe: spectrum enabled
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:47.915: sie: total latency: 0 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:47.915: soe: total latency: 0 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.099: sie: sampling rate: 48000 Hz
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.107: soe: sampling rate: 44100 Hz
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.110: sie: using output device: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.110: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.110: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.110: pulse_settings_ui: added sink: alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y70V2JM074A5BA-00.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.110: pulse_settings_ui: added source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.110: pulse_settings_ui: added source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.111: pulse_settings_ui: added source: alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y70V2JM074A5BA-00.analog-stereo.monitor
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.112: pulse_settings_ui: input device changed: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y70V2JM074A5BA-00.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.112: pulse_settings_ui: added source: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y70V2JM074A5BA-00.analog-stereo
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.112: pulse_settings_ui: added source: alsa_input.usb-046d_0825_8184F2D0-02.mono-fallback
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.112: pulse_settings_ui: added source: alsa_input.usb-OmniVision_Technologies__Inc._2000-01.multichannel-input
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.116: peadapter: pulseaudio block size 441 frames
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.116: peadapter: we will read in chunks of 512 frames
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.125: soe: NULL -> READY -> PLAYING
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.127: soe: total latency: 181 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.127: sie: NULL -> READY -> PLAYING
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.131: soe: READY -> PAUSED -> PLAYING
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.135: sie: READY -> PAUSED -> PLAYING
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.136: soe: pulsesrc latency [us]: 10000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.136: soe: pulsesrc buffer [us]: 200000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.137: soe: total latency: 181 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.137: soe: pulsesink latency [us]: 10000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.137: soe: pulsesink buffer [us]: 200000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.137: soe: total latency: 181 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.138: soe: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.138: soe: total latency: 181 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.145: sie: pulsesrc latency [us]: 10000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.145: sie: pulsesrc buffer [us]: 200000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.145: sie: total latency: 0 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.145: sie: pulsesink latency [us]: 10000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.145: sie: pulsesink buffer [us]: 200000
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.145: sie: total latency: 0 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.449: peadapter: pulseaudio block size 480 frames
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.449: peadapter: we will read in chunks of 512 frames
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.459: sie: total latency: 140 ms
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.473: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:136796): pulseeffects-DEBUG: 17:48:48.474: sie: total latency: 140 ms

**Comment by wwmm** [comment]
Sometimes GStreamer's cache is not properly updated. Try to delete it `rm -rf ~/.cache/gstreamer-1.0` and restart PulseEffects. It may help to solve this issue.

**Comment by arighi** [comment]
> Sometimes GStreamer's cache is not properly updated. Try to delete it `rm -rf ~/.cache/gstreamer-1.0` and restart PulseEffects. It may help to solve this issue.

Already tried... unfortunately it didn't solve the problem.

**Comment by Digitalone1** [comment]
I see you work at Canonical. We were talking about releasing 4.8.1 before 20.10 official release so you can make it available to  Ubuntu users since they can only use the old 4.7.2 now.

But I'm afraid you will ship it with 21.04 if you manage to fix 4.8.0 or am I wrong?

**Comment by arighi** [comment]
@Digitalone1 honestly I have no idea... I work in the kernel team. But I can ask around to understand what are the plans about pulseeffects.

**Comment by wwmm** [comment]
>Already tried... unfortunately it didn't solve the problem

Ok. Then let's look at `libgstreamer-plugins-bad` again. As far as I can see all the missing plugins are `LV2` plugins. The GStreamer wrapper for this standard is in `gst-plugins-bad`. As resetting the cache does not work and the plugins are installed this package is probably the source of the issue. The last time I had problems with it on Arch Linux the reason was that a mistake caused this library to be complied without the `lilv` library. Without it `gst-plugins-bad` is not capable of loading `LV2` plugins.

**Comment by wwmm** [comment]
A quick way to test if GStreamer is being able to load LV2 plugins is running the command `gst-inspect-1.0 | grep -i lv2`. If there is no lv2 plugins shown it won't work in PulseEffects too.

**Comment by arighi** [comment]
@wwmm thanks tons!!! That seems to be the problem! In fact `gst-inspect-1.0 | grep -i lv2` returns nothing. On a different system (Ubuntu 20.04) where pulseeffects is working the same command returns all the plugins.

**Comment by wwmm** [comment]
Ok. Check if the package providing the `lilv` library is installed. If it is then `libgstreamer-plugins-bad` has to be recompiled with support for `lilv` enabled.

**Comment by wwmm** [comment]
>But I can ask around to understand what are the plans about pulseeffects.

If you do that tell them I have just release `4.8.1` and that it has some fixes that make it more suitable to be included in a stable repository..

**Comment by arighi** [comment]
> Ok. Check if the package providing the `lilv` library is installed. If it is then `libgstreamer-plugins-bad` has to be recompiled with support for `lilv` enabled.

Apparently liblilv is in the build dependencies and if I try to recompile the package I see this in the configure:

configure: *** checking feature: lv2 ***
configure: *** for plug-ins: lv2 ***
checking for LILV... yes
configure: *** These plugins will be built: lv2

So, there's definitely something that I'm missing. I'll investigate more on this.

**Comment by arighi** [comment]
Additional info:
```
$ ldd /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlv2.so
...
liblilv-0.so.0 => /usr/lib/x86_64-linux-gnu/liblilv-0.so.0 (0x00007f7f0e349000)
...
```
So apparently it is compiled with the `lilv` support enabled...

**Comment by wwmm** [comment]
So clearly there is something else that is needed that I am not aware of. Does the command `GST_DEBUG=4 GST_DEBUG_FILE=gst_log.txt gst-inspect-1.0 | grep -i lv2` shows anything interesting?

**Comment by wwmm** [comment]
You can try higher GStreamer log levels like `GST_DEBUG=5` or `GST_DEBUG=6`. But the log file gets really big in these levels.

**Comment by arighi** [comment]
@wwmm https://kernel.ubuntu.com/~arighi/pulseeffects/gst_log.txt <-- full log with GST_DEBUG=6.

**Comment by arighi** [comment]
Hm... and now for some reasons the plugins are working... :-/

I'll try to cleanup, reinstall the official packages and reproduce the problem.

At least we know that the problem was definitely in `libgstreamer-plugins-bad`.

**Comment by wwmm** [comment]
>Hm... and now for some reasons the plugins are working... :-/

That is what I see in the logs. Somehow now there are tons of calf and lsp plugins being found.

>At least we know that the problem was definitely in libgstreamer-plugins-bad

Yes. Although it is not clear what it was.

**Comment by arighi** [comment]
> > Hm... and now for some reasons the plugins are working... :-/
> 
> That is what I see in the logs. Somehow now there are tons of calf and lsp plugins being found.
> 
> > At least we know that the problem was definitely in libgstreamer-plugins-bad
> 
> Yes. Although it is not clear what it was.

True... I'll do more test and will try to reproduce the problem on a clean environment. If everything works, it means that the problem was in my gstreamer-1.0 cache (even if I removed the files many times). I'll keep you informed. Thanks again for all your help (and I'll try to push to get `4.8.1` in Ubuntu 20.10).

**Comment by arighi** [comment]
I've been able to reproduce the problem! This is what I'm getting in gst_log.txt now:
```
0:00:00.990501000 197705 0x55d6fb5fee00 WARN      GST_PLUGIN_LOADING gstplugin.c:484:gst_plugin_register_func: plugin "/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlv2.so" has incompatible version (plugin: 1.17, gst: 1,16), not loading
```
If I recompile `libgstreamer-plugins-bad1.0-0` manually on my box, install my recompiled debs (cleaning the cache `rm -rf ~/.cache/gstreamer-1.0`) everything works fine!

So I guess there's something wrong with the stock `libgstreamer-plugins-bad1.0-0` shipped in Ubuntu, or something's wrong in my environment (trying to figure out where it finds the version 1.17, apparently all the versions are 1.16).

**Comment by wwmm** [comment]
It seems that the package in the repository was compiled with GStreamer `1.17` sources. Are they downloading the source directly from the git repository? The wrong tag could have been used.

**Comment by DDzwiedziu** [comment]
This is still present in Pop!_OS 21.04 (still the packages are from Ubuntu repos). PE's version is still 4.8 yet `libgstreamer-plugins-bad1.0-0`'s version is shown as 1.18.

**Comment by wwmm** [comment]
As EasyEffects 6.0.0 does not use GStreamer we can close this.
