### ISSUE TITLE
Bode plot and minor improvements for the Equalizer

### ISSUE THREAD

**Issue by polygonalenippel** [wwmm/easyeffects#796]
Some things I would like to see in Equalizer:

1. A horizontal bar in the background striking through (or behind) the centre of all bands, giving you a feel of absolute reference
2. The band's quality factor right beneath the centre frequency
3. A frequency response plot. Considering we have keyboard and mouse control over the bands, maybe we 1/4 of the window height to a plot, the plot similar to how MathAudio has one: https://static.kvraudio.com/i/b/h8.png so you can more intuitively fix frequencies.

Regarding 3, we could use gnuplot or octave. I can help with setting up functions generating Bode plots so we can get an image, though I'd have to brush up my complex analysis theory a little.

Thoughts?

**Comment by wwmm** [comment]
The first point is a good idea. About the second I am not sure. I have no problems with the quality being shown in the middle. But I also have no reason for keeping it there. Any thoughts on this @Digitalone1 ?

The third is impossible to do right now if we want to show the correct frequency response. You can see the reason why in #515.

**Comment by polygonalenippel** [comment]
> The third is impossible to do right now if we want to show the correct frequency response. 

I failed to find the reason why exactly we cannot show the correct frequency response. I assume the LSP folks follow the same mathematical principles of how filters are established? I understand why it may lead to some kind of doubled effort though.

**Comment by wwmm** [comment]
The word impossible may have been a exaggeration in the general sense. But as things are right now it is indeed impossible to get this curve from the plugin. So the only possible approach is the one you seem to be thinking of. Taking the parameters in the user interface and calculating the frequency response from a set of equations. 

The thing is I have my doubts about how doable this approach is. As I have never written an equalizer I can not say for sure. But the amount of work to replicate the frequency response calculation on our side seems big. LSP equalizer has 3 modes of operation: `IIR`, `FIR` and `FFT`. Each of them probably has a different model that needs to be used to calculate the frequency response. But that is not all. Each band has `7` different types. And each type has up to `7 modes`. Each of them will probably require a different set of equations to calculate the frequency response. And on top of that we also have the slope parameter changing things... Doing this calculation on our side feels like developing half of an equalizer...

**Comment by wwmm** [comment]
>I assume the LSP folks follow the same mathematical principles of how filters are established

Probably. But besides knowing which models were used we also have to know if they were customized somehow. Otherwise the response calculated won't be the same.

**Comment by wwmm** [comment]
Another problem is maintaining this over time. What if the LSP developer decides to use an improved model in any of the types?We will have to know exactly what was changed and update the code accordingly on our side.

**Comment by Digitalone1** [comment]
>     1. A horizontal bar in the background striking through (or behind) the centre of all bands, giving you a feel of absolute reference
Don't know how to do this, but maybe a trick can be found in glade.
 
>     2. The band's quality factor right beneath the centre frequency
Can be done, but only for reference. The spinbutton should stay in the band settings (because is too big to be included in the main tab)  while the quality value is showed under the frequency.

**Comment by Digitalone1** [comment]
I tried to do something with glade (the new version of the application has screwed up all the UI adding empty columns and rows).

Only the second point can be done. For the first one I don't see anything to add a line to a widget, neither the scale has an option to grade the bar.

**Comment by polygonalenippel** [comment]
> Each of them will probably require a different set of equations to calculate the frequency response. And on top of that we also have the slope parameter changing things...
> But besides knowing which models were used we also have to know if they were customized somehow.
> Another problem is maintaining this over time.
These are some very valid points for not implementing it in PE.

You mentioned in that other issue that you were in contact with the LSP folks and that doing some kind of linking data through to LSP is off the table, which is understandable too.

We could make another dirty parser which parses the current EQ config into (or from) LSP so you can fiddle with the EQ in there. The LSP config file is actually surprisingly human readable, as all config entries are explained right in there. I am still thinking however how this could benefit PE.

**Comment by polygonalenippel** [comment]
Running LSP in Ardour works really well, but using it as part of your audio stack for casual listening is really tiresome. Using the LSPs in a simple solution as PE would be ideal. I guess it can't be achieved easily.

**Comment by wwmm** [comment]
>but using it as part of your audio stack for casual listening is really tiresome

That is once of the reasons why I started to write PulseEffects. Before Pulseaudio became standard I used a custom Jack routing to apply effects to ALSA apps. Too much work for people not doing music.

**Comment by polygonalenippel** [comment]
So what if we parse it into LSP config format so you can edit it in the parametric eq of LSP, export it, then import again in PE?

**Comment by wwmm** [comment]
>So what if we parse it into LSP config format so you can edit it in the parametric eq of LSP, export it, then import again in PE?

I did not understand exactly what you have in mind. Maybe because I have never used LSP in Ardour. IS the idea to do something similar to the EQ APO preset import that we have? Would The user generate the equalizer configuration in Ardour where it is possible to see the frequency response and then importing the LSP configuration in PulseEffects? It should be possible.

**Comment by polygonalenippel** [comment]
> Would The user generate the equalizer configuration in Ardour where it is possible to see the frequency response and then importing the LSP configuration in PulseEffects?

Yes, this is what I had in mind.

**Comment by wwmm** [comment]
The latest master branch is capable of showing the native equalizer ui. There are lots of rough edges to fix but we can finally see the frequency response curves. This issue can be closed.
