### ISSUE TITLE
Opening GUI creates zombie processes

### ISSUE THREAD

**Issue by rockerbacon** [wwmm/easyeffects#803]
Whenever I open the GUI, two zombie processes show up immediately and never get closed.

I observed this running the Flatpak distribution, version 4.8.2.

**Comment by wwmm** [comment]
Kill Pulseeffects `killall pulseeffects` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects flatpak run com.github.wwmm.pulseeffects` so we can see if errors are happening.
