### ISSUE TITLE
bringing back the old loudness compensation plugin

### ISSUE THREAD

**Issue by Mlocik97** [wwmm/easyeffects#820]
As I mailed with @wwmm , we should bring back old loudness compensation plugin next to new one. New one is really good, but there are situations (mainly, if You have dedicated subwoofer (2.1 audio system)) when old one was better to compensate loudness of bass, because it was applied only on bass frequencies, instead whole spectrum like new one. They also use differend loudness contours (specifically Stevens-Davis equal loudness contours) that is differend from LSP plugin contours. @wwmm suggested to bring it back as another loudness compensator named "Bass Loudness compensation".

**Comment by Mlocik97** [comment]
Can I ask how a lot of work would this require,... bcs. I think, if it already was in PE, it should need to just copy code from old commits,... can I create PR for this? I'm not that good with C++, so I will propably need some help, but I would like to work on this, bcs I really need this feature.

**Comment by wwmm** [comment]
>if it already was in PE, it should need to just copy code from old commits

As the master branch still is using GStreamer it will be enough to do that. For the release based on GTK4 things will be different  
because I decided to move from GStreamer to PipeWire's native filters. At this moment I am doing that to the autogain https://github.com/wwmm/pulseeffects/blob/gtk4/src/autogain.cpp.

In case you want to have a local build in your computer with this plugin available I can help you. But I think that merging this work with the master branch won't be a good idea. It may make things more complicated when merging the GTK4 and the master branch.

For the GTK4 I will probably need to write a wrapper for LADSPA plugins besides the one for LV2 plugins I am already writing https://github.com/wwmm/pulseeffects/blob/gtk4/src/lv2_wrapper.cpp. Depending on the MDA plugin license another possibility would be to port its code to a PipeWire filter like I am doing in the autogain. PipeWire's filters API is very simple to use.

**Comment by Mlocik97** [comment]
I still use 4.7.X, and if implementing it now would be inefficient, because of changes in GTK4 port, that will need to work on it again, then I think, I will just wait for now.  And when it will be ported to GTK4, then I will look on it.

**Comment by Mlocik97** [comment]
Ok, I will try to create fork with old loudness plugin, could You please assist me?

https://github.com/Mlocik97/pulseeffects/issues/1

**Comment by wwmm** [comment]
The new update to the master branch has the MDA loudness plugin
![Screenshot from 2021-07-10 14-19-02](https://user-images.githubusercontent.com/16225172/125171312-fb6e2180-e189-11eb-820f-21eaf5139553.png)

As expected it was easy to do. I mean... The overall process of adding a plugin to EasyEffects is as painful if not more than it was in PulseEffects. But as I have all the steps in my head it was fast. This is something that should be improved in the future but I do not know how. It is way to difficult for new contributors to add plugins. This is not good.

As it happens with all the others plugins in EasyEffects you can use it in both pipelines. It is not restricted to the output effects anymore.

**Comment by wwmm** [comment]
I named it `Bass Loudness` but I am not sure if it is conceptually accurate. The plugins description gives that vibe. But looking at its code it is not obvious if only the low frequencies are being corrected.  I did not understand the algorithm.

**Comment by Mlocik97** [comment]
Thank you so much for adding plugin and all your work... 


I'm not sure about how algorithm work, but because I used that plugin for some time and was playing a lot with it's settings, from what I hear I can say **it affects only low frequencies**. It watch higher frequencies, but doesn't affect them. Mainly when kick happen, it create more "steeper hill" on spectogram in low frequency, but it keeps wide of original bass, so it sounds like the bass has bigger depth and loudness range, but it increase loudness volume as well. I'm not sure of how exactly it works and how it change, but by what I can hear, without this plugin, my subwoofer sound like when you're thrashing the rug, and when it's on, it sound more like when you thrash really big tambour.

**Comment by wwmm** [comment]
I see. In any case we can close this issue.

**Comment by nstommel** [comment]
@wwmm Thank you sooo much for bringing the old MDA Loudness plugin back to EasyEffects (and renaming it something informative). The algorithmic adjustable bass boost is like magic for my various audiophile open-back headphones. It really enhances the listening experience on Linux (I'm using Fedora 35) and it seems to work better than using an equalizer as it performs real-time over-limit/clipping information. I wish something like this existed on Windows, it's truly fantastic!

**Comment by Neo595** [comment]
Hello,
The path to the plugin has changed, so easyeffects is no more able to load it.
(easyeffects:2): easyeffects-WARNING **: 13:03:07.180: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness
Is it possible to point to new link or even point to a local file ?
Thanks in advance

**Comment by wwmm** [comment]
It has not changed. I just tried it now and it works. I think that what is happening is that you do not have the `MDA` plugins package installed.

**Comment by Neo595** [comment]
Hello, Thanks.  It is working.
