### ISSUE TITLE
System volume hotkeys affect mic, not speakers, while pulseeffects running

### ISSUE THREAD

**Issue by myself248** [wwmm/easyeffects#833]
First off, this thing is freakin' awesome. But there's a glitch affecting Ubuntu 18.04.5 LTS on a Thinkpad T560, installed pulseeffects as a flatpak, launching it now with the gnome plugin. Not sure if that affects it.

My system volume keys are Fn+F2 and Fn+F3, which work normally before I start PE. Which is to say, it makes a little "pok" noise for each change, and pops up a little graphic showing a speaker icon and the volume level displayed as a bar.

After launching PE, pressing those keys no longer affects the audio coming out my speakers. The graphic does pop up, but now it says "PulseEffects(mic)" on it. And there's no "pok" noise as I raise or lower the setting. 

Unhelpfully, while writing this issue, I poked around a bit in gnome settings, and closed and reopened PE several times, in the classic "mad bomber" style of troubleshooting. I can both solve this issue, and cause all sorts of new ones where I have no audio at all! Still working on repro steps, but one of the important variables is the "choose a device for sound output" within gnome settings, which one is selected at the moment PE starts or exits. I'll come back and update this if I learn more about the behavior.

**Comment by wwmm** [comment]
Your volume keys are controlling our virtual device as default device. `PulseEffects(apps)` and `PulseEffects(mic)` should never be set as default. But unfortunately there are third party software like that do that. And on old Pulseaudio versions its module `module-switch-on-connect` does that too. As you ubuntu release with very old packages this could be the reason.
