### ISSUE TITLE
Android Virtual Device AVD *(No Sound)

### ISSUE THREAD

**Issue by davidsal** [wwmm/easyeffects#852]
This is a issue that I first see in 20.04. 
Basically if I install PulseEffects from PPA (haven't tried another source) and then proceed to launch the Android Emulator, audio goes off and I need to delete the pulse folder on my home/config, then, do a reboot of the system to get audio back.
I'm on 20.10 currently. If you want to replicate exactly like me, install React Native and use the "react-native run-android" command a few times (maybe in the 3rd time audio will go off). This is somehow related to PulseEffects, because if I uninstall it, I never face this issue when using stock pulse audio.

**Comment by wwmm** [comment]
Kill the current instance `pulseeffects -q` and restart it in de bug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. THis way we will see if anything unusual is happening. But it seems to me that `Android Virtual Device` is one more application that decides to mess with our audio routing.

**Comment by davidsal** [comment]
Ok. I tried this, but nothing showed up after audio going off.
I found something, it's just the audio from the apps on the "Applications" tabs that goes off, not system-wide. If I turn the switch/toggle to off of any app, audio returns for that app only. This happens randomly, maybe 1 time for every 3 AVD runs. 

Debug Mode: I ran the emulator on the minute 37, you can see that there are no logs for that minute.
![Captura de pantalla de 2020-12-21 23-39-22](https://user-images.githubusercontent.com/9061618/102853675-615dac00-43e6-11eb-99d7-6746be7ff3e1.png)

No audio: You can see that the graph doesn't show up
![Captura de pantalla de 2020-12-21 23-40-48](https://user-images.githubusercontent.com/9061618/102854755-ce724100-43e8-11eb-8df3-7375d3a46901.png)

Video:
https://user-images.githubusercontent.com/9061618/102854771-d500b880-43e8-11eb-8c63-8202f4700212.mp4

**Comment by wwmm** [comment]
THe next time this happens open Pavucontrol and take a look at what output device the silenced app was set to. What the switch in our interface does is moving the app to our virtual sink `PulseEffects(apps)`. This is necessary for applying effects to it. My guess is that when AVD runs something is moving the apps to an output device that is neither our virtual sink or the sound card.

**Comment by davidsal** [comment]
Ok, I checked Pavucontrol, I don't see any difference in the before and after the audio loss.

Before:
![Captura de pantalla de 2020-12-24 14-25-41](https://user-images.githubusercontent.com/9061618/103105850-0bf7e980-45f6-11eb-9e5f-c2247c6b7361.png)

After: Only difference is that the System Sound was set to 0%, I moved it back to 100% and nothing changed, still no audio.
![Captura de pantalla de 2020-12-24 14-33-49](https://user-images.githubusercontent.com/9061618/103105857-187c4200-45f6-11eb-9158-dde8692d3609.png)
