### ISSUE TITLE
Can't seem to uninstall

### ISSUE THREAD

**Issue by RKDUDE02** [wwmm/easyeffects#870]
Hello! I am having problems with uninstalling pulseeffects. My Linux distro is Ubuntu 20.04. I have tried uninstalling it using
`sudo apt remove pulseeffects`
but it couldnt find pulseeffects and uninstall it.
I installed it with:
`sudo add-apt-repository ppa:mikhailnov/pulseeffects -y
sudo apt update
sudo apt install pulseeffects pulseaudio --install-recommends`
Is there a solution to this problem?

**Comment by wwmm** [comment]
As I do not use ubuntu I don  know. Any idea @mikhailnov?

**Comment by Mlocik97** [comment]
Try to use `apt list --installed` command, and find PE.

**Comment by RKDUDE02** [comment]
Sorry for the inactivity, I have been busy with other things recently. Are you suggesting that i remove the package "PE" with `sudo apt remove pe` This would make sense as "PE" could stand for PulseEffects.

**Comment by wwmm** [comment]
Probably not. We usually right PE just because it is faster. In the command output search for `pulseeffects`

**Comment by RKDUDE02** [comment]
It returned nothing, i searched the output for pulseeffects and found nothing. At this point i am very confused it is installed and is in my app list and works just fine, i just want it uninstalled. Has it's package name ever changed? I don't know what else it could be.

**Comment by wwmm** [comment]
Ubuntu based distributions unify debian packages with flatpak packages. If there is nothing in `apt` output then your software center must have installed through flatpak. Try to see how to search for and remove this kind of package.
