### ISSUE TITLE
Pipeline sometimes doesn't start on PipeWire version

### ISSUE THREAD

**Issue by halfrafu** [wwmm/easyeffects#898]
On my system I'm facing this, I guess, unusual issue where pipeline sometimes doesn't start which ends up with no audio and frozen ui nearly every time. Killing PulseEffects or disabling effects (if I can) restores audio.

I've been running PulseEffects with debugging messages enabled for quite some time and I've noticed that total latency is never calculated when pipeline doesn't start. For example log looks like that:
`(pulseeffects:384815): pulseeffects-DEBUG: 20:37:36.757: pipe_manager: new metadata property: 83, target.node, Spa:Id, 93`
`(pulseeffects:384815): pulseeffects-DEBUG: 20:37:36.759: pipe_manager: Firefox port 107 is connected to pulseeffects_sink port 98`
`(pulseeffects:384815): pulseeffects-DEBUG: 20:37:36.759: pipe_manager: Firefox port 97 is connected to pulseeffects_sink port 50`
`(pulseeffects:384815): pulseeffects-DEBUG: 20:37:36.789: soe: sampling rate: 48000 Hz`
`(pulseeffects:384815): pulseeffects-DEBUG: 20:37:36.792: soe: NULL -> READY -> PLAYING`
`(pulseeffects:384815): pulseeffects-DEBUG: 20:37:36.793: soe: READY -> PAUSED -> PLAYING`
Sometimes, it stops right after showing sample rate.

If pipeline starts properly log looks like that:
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.232: pipe_manager: new metadata property: 83, target.node, Spa:Id, 105`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.234: pipe_manager: Firefox port 107 is connected to pulseeffects_sink port 33`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.234: pipe_manager: Firefox port 97 is connected to pulseeffects_sink port 93`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.259: soe: sampling rate: 48000 Hz`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.304: soe: total latency: 30 ms`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.306: soe: NULL -> READY -> PLAYING`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.307: soe: READY -> PAUSED -> PLAYING`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.308: soe: PAUSED -> PLAYING -> VOID_PENDING`
`(pulseeffects:384953): pulseeffects-DEBUG: 20:37:58.309: soe: total latency: 30 ms`
I haven't changed latency from default 50ms in PipeWire settings section so I don't know where 30ms delay comes from.

I'm mainly playing audio in Firefox, just mentioning it in case it matters.

### General info
Distro: Arch Linux
PulseEffects: 5.0.0-1
Linux 5.10.12-arch1-1
PipeWire 0.3.21-1

**Comment by wwmm** [comment]
I did not see this happening on my computer yet. But my guess is that there is a thread race somewhere. And these are among the hardest to find... I will investigate.

**Comment by wwmm** [comment]
>I'm mainly playing audio in Firefox, just mentioning it in case it matters.

Unless our interface freezes only when Firefox is used I doubt it matters.

**Comment by wwmm** [comment]
>total latency is never calculated when pipeline doesn't start

Only when the pipeline is running the latency can be queried. If we could not do that then something went wrong. As you have already noticed.

**Comment by wwmm** [comment]
>I haven't changed latency from default 50ms in PipeWire settings section so I don't know where 30ms delay comes from.

`pipewiresrc` does not seem to be updating the latency it reports initially. In the future PipeWire's developer will take a look at this. But as far as I can see this does not have major consequences. The window is freezing for other reasons.

**Comment by halfrafu** [comment]
> But my guess is that there is a thread race somewhere. And these are among the hardest to find... I will investigate.
Yeah, I can imagine these are hard to find... I can reproduce it quite easily on my end so you can tell me some more useful way to debug this if that would be helpful.

Also I've noticed something that might indicate it's a race condition, sometimes soe messages appear in different order even if pipeline starts properly. Right now I got this:
`(pulseeffects:482960): pulseeffects-DEBUG: 01:46:35.952: soe: NULL -> READY -> PLAYING`
`(pulseeffects:482960): pulseeffects-DEBUG: 01:46:35.954: soe: READY -> PAUSED -> PLAYING`
`(pulseeffects:482960): pulseeffects-DEBUG: 01:46:35.964: soe: sampling rate: 48000 Hz`
`(pulseeffects:482960): pulseeffects-DEBUG: 01:46:35.992: soe: total latency: 30 ms`
`(pulseeffects:482960): pulseeffects-DEBUG: 01:46:35.993: soe: PAUSED -> PLAYING -> VOID_PENDING`
`(pulseeffects:482960): pulseeffects-DEBUG: 01:46:35.993: soe: total latency: 30 ms`

**Comment by wwmm** [comment]
I did some changes in the code that updates our pipeline state when an app starts/stops to play. Maybe it has some effect on this. If possible try to use the aur package that builds from the git repository.

**Comment by halfrafu** [comment]
Alright, just installed pulseeffects-git from AUR. So far seems to happen less but still isn't fixed. I'll need to test it for some time to be sure.

**Comment by halfrafu** [comment]
Soo... after testing this version for few days I can say that soe messages never appear out of order and when pipeline doesn't start sampling rate gets printed followed by states after around 5 to 30 seconds (but not every time, more like 95% chance), like this:
`(pulseeffects:704822): pulseeffects-DEBUG: 22:52:37.072: soe: sampling rate: 48000 Hz`
`(pulseeffects:704822): pulseeffects-DEBUG: 22:52:52.060: soe: NULL -> READY -> PLAYING`
`(pulseeffects:704822): pulseeffects-DEBUG: 22:52:52.062: soe: READY -> PAUSED -> PLAYING`
Oh, and gui still freezes too.

I've noticed issues seem to go away when I increase minimum cpu frequency from default 800MHz to 1500MHz. I'll get back to repo version and test if it happens there.
I think it's related to weird behavior of my machine: cpu seems to be, I don't know... slower, after resuming from suspend which causes kwin-lowlatency to stutter unless I increase minimum cpu frequency.

**Comment by wwmm** [comment]
>issues seem to go away when I increase minimum cpu frequency from default 800MHz to 1500MHz

Interesting. But I still think our gui should not freeze because of that. This weekend I will try to do more investigation. Usually does the window freeze when an application is trying to play for the first time or when you are unpausing them?

**Comment by halfrafu** [comment]
It can happen both when application unpauses and starts playing, can't really tell when it tends happen more often. I've tested pausing with vlc (I'm still on aur version) because while looking at logs I've noticed Firefox removes and adds it's audio output when I unpause something so I guess unpausing YouTube video is more like application playing for the first time than unpausing.

Today I've discovered another weird behavior, don't know if it's gonna be helpful or not. I left frozen window open instead of killing the app. It unfroze after some time (like half a minute) and froze again every time I tried to enable or disable effects for application or other application started or stopped playing.

**Comment by wwmm** [comment]
I have been trying to find a way to reproduce these freezes but so far nothing :-(

**Comment by wwmm** [comment]
Even using taskset to force the use of only cpu core so far no freeze when the pipeline is restarted. Which plugins do you have enabled?

**Comment by halfrafu** [comment]
> Which plugins do you have enabled?

I'm only using equalizer.

> I have been trying to find a way to reproduce these freezes but so far nothing :-(

Oh my... maybe it really is specific to my hardware? I'll check my uefi settings because vcore at 0.35V seems to be too low comparing to what I see on the internet (my cpu and mobo are 2nd hand)... maybe that's causing all these issues.

**Comment by halfrafu** [comment]
> my cpu can be unstable with hyperthreading enabled so I'll try to disable it.

Just checked, still happens, and even more often. Maybe you'll be able reproduce these freezes by disabling some cores or lowering max cpu frequency?
I've noticed another thing, sometimes when ui freezes it shows state "creating" or "suspended" and rate 0Hz like here:
![image](https://user-images.githubusercontent.com/12630436/107865140-f370b680-6e63-11eb-8abb-9a7187334945.png)
State changes to "running" and ui shows rest of the information properly when `soe: NULL -> READY -> PLAYING` and `soe: READY -> PAUSED -> PLAYING` appear in log but ui is still frozen. It's also the moment when ui kinda reacts to me clicking on it when it was frozen, for example, I clicked on titlebar and when it happens my mouse goes to where I clicked on the titlebar and I'm moving the window (without holding any mouse button) that is still frozen until I click. Then, after another like 30 seconds, ui unfreezes and stays responsive until something happens that would change information displayed here (like I mentioned earlier).

**Comment by wwmm** [comment]
>Maybe you'll be able to reproduce these freezes by disabling some cores or lowering max cpu frequency?

`taskset -c 0 pulseeffects` forces 1 core to be used. But it was not enough to make the freezes happen. The frequency of my Ryzen 3700X can not be set below 2 GHz. I think I will have to test on another machine. As we are both using Arch Linux library versions problems are not the reason.

**Comment by wwmm** [comment]
When you run pulseeffects as a service are there freezes in the playback? Or effects are applied as expected and the problems start only when the window is shown? You can do that in debug mode running `G_MESSAGES_DEBUG=pulseeffects pulseeffects --gapplication-service`

**Comment by halfrafu** [comment]
Still happens when I run pulseeffects as a service. Ctrl+c behaves in a weird way when it freezes. After I press it nothing happens and after about 5 seconds all these <something> destroyed messages appear and I have to press ctrl+c for the second time to kill the app and get sound back. Normally these <something> destroyed messages appear immediately and app exits after pressing ctrl + c.
The same thing happens with ui but I need to wait longer before something happens after pressing ctrl + c.

**Comment by wwmm** [comment]
>nothing happens and after about 5 seconds

That is interesting. 5 seconds is the default timeout value for stopping our pipeline when no application is playing audio.
![Screenshot from 2021-02-13 23-04-16](https://user-images.githubusercontent.com/16225172/107866443-d03c0c00-6e4f-11eb-8e59-aa47758b1824.png)

If you change the activity timeout does the overall time for the ctrl+c to take effect changes accordingly? If yes the number of places to be investigated will be narrowed down considerably.

**Comment by 6601618158** [comment]
I think I have the same problem, but my CPU definitely does not clock as low as @halfrafu's. I redirected pulseeffects' output to a file, and it actually seems like it worked better than usual (i.e. w/o the debugging), so I had to try a bit harder to make it freeze, but it eventually did after I tried to unpause a YouTube video using Firefox. I (also?) had to C-c twice before pulseeffects was killed, and I'm running pulseeffects 5.0.0-1 on Arch. 

[pulseeffects_log.log](https://github.com/wwmm/pulseeffects/files/5987481/pulseeffects_log.log)
[systeminfo.txt](https://github.com/wwmm/pulseeffects/files/5987483/systeminfo.txt)

**Comment by wwmm** [comment]
@6601618158 so far I did not see anything unusual in your logs. I wonder what your systems have that mine doesn't. Usually thread races that freeze our window are not that hard to reproduce. In PulseEffecs early days we had one that I could easily see on my machine.

**Comment by wwmm** [comment]
I finally had time to do tests on my laptop instead of on my Desktop. Somehow on the laptop reproducing this issue is quite easy while on the desktop it just doesn't happen. I will investigate what is going on.

**Comment by wwmm** [comment]
I have updated the master branch with some changes that seem to have reduced the frequency of the freezes on my laptop. But they are still there. If possible try to do some tests with the AUR package that builds from git

**Comment by wwmm** [comment]
It is still not clear why the GStreamer pipeline sometimes freezes on the laptop while it never does that on my desktop...

**Comment by 6601618158** [comment]
> @6601618158 so far I did not see anything unusual in your logs. I wonder what your systems have that mine doesn't. Usually thread races that freeze our window are not that hard to reproduce. In PulseEffecs early days we had one that I could easily see on my machine.

I just tried it again, and this time pulseeffects froze immediately: I had started a video in Firefox, paused it, opened pulseeffects, unpaused → no audio and pulseeffects frozen. Then I killed pulseeffects (because it was completely unresponsive), did the same thing again, but this time piping the debug log to a text file, and then it worked. Then I closed pulseeffects, and opened it again (this time w/o piping to a file), and it worked again. Same thing w/o debugging. So it seems to be very random in my case (initially I had the feeling that activating G_MESSAGES_DEBUG made a difference for whatever reason, but that doesn't seem to be the case).

Somehow I also have two AudioStreams going at the same time (one always idle, one running, unless paused, both for Firefox), with only one tab loaded (playing a video), toggling either of them off doesn't change anything, changing volume on the idle one doesn't do anything, and changing volume on the running AudioStream actually does something. Checking the "Add to Blocklist" checkbox doesn't change anything, either. When I pause the video, and I see the "No app wants to play audio. We will stop our pipeline." message in the log, both AudioStreams remain, but when I unpause again, the second AudioStream vanishes, and appears again. The first one, that only seems to be there for decoration (😅) doesn't do anything. 

Is this how it's supposed to work? I'm pretty sure this worked differently before with only pulseaudio. 

Could this just be a misconfiguration of pipewire on my end? When I switched from pulseaudio to pipewire, I basically didn't change any settings, until I ran into issues with headphone/mic detection. Then I just deleted my pulseaudio config (which made it a little better), so everything should be "stock settings", so to speak. 

I guess I'll try the AUR version next.

**Comment by wwmm** [comment]
>Is this how it's supposed to work? I'm pretty sure this worked differently before with only pulseaudio.

So far I did not see 2 Firefox streams in the window when only one video is being played. But I've noticed that it recreates its stream under some circumstances. There are some differences between PipeWire and Pulseaudio when it comes to stream notifications but usually when you see a stream in the window the audio application actually created them. Try to take a look at the output of `pw-cli list-objects Node`. If the number of firefox streams in its output matches the amount visible in PulseEffects it is fine.

>Could this just be a misconfiguration of pipewire on my end? 

I doubt this is the case in the situation where the pipeline freezes. I've set the files under `/etc/pipewire` to their default values and I still see the freeze in my laptop. But so far I do not understand why they happen. And why I do not see them in my desktop.

**Comment by wwmm** [comment]
I've noticed some differences in GStreamer's behaviour when comparing my desktop and my laptop. In my laptop it always puts its pipeline in the playing state asynchronously. but in my desktop it never does that asynchronously. I do not know why doing this asynchronously sometimes is leading to a pipeline freeze. OR how GStreamer decides which way to go... But it is curious that it does not use this approach on my desktop and there everything is fine...

**Comment by wwmm** [comment]
After more having done more attempts I saw it doing the state change asynchronously once in my desktop. But it is definitely way less often than in the laptop.

**Comment by halfrafu** [comment]
> If you change the activity timeout does the overall time for the ctrl+c to take effect changes accordingly? If yes the number of places to be investigated will be narrowed down considerably.

Unfortunately no, the time for ctrl + c to take effect is quite random and ranges from 5 seconds to maybe even a minute.

> I've noticed some differences in GStreamer's behaviour when comparing my desktop and my laptop. In my laptop it always puts its pipeline in the playing state asynchronously. but in my desktop it never does that asynchronously. I do not know why doing this asynchronously sometimes is leading to a pipeline freeze. Or how GStreamer decides which way to go... But it is curious that it does not use this approach on my desktop and there everything is fine...

My guess is it may depend on some cpu instruction available. Your Ryzen 3700X is newer than my i3-7100 and @6601618158 's i5-2400. What cpu do you have in your laptop?
Also, can I somehow check if GStreamer changes state synchronously or asynchronously on my end?

**Comment by halfrafu** [comment]
After installing newest version from AUR and testing it for several minutes I've noticed these things:
- when pipeline starts properly, soe messages appear in different but always the same order, like this:
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.873: soe: pipeline state reading was succesfull`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.886: soe: sampling rate: 48000 Hz`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.888: soe: NULL -> READY -> PLAYING`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.889: soe: READY -> PAUSED -> PLAYING`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.925: soe: total latency: 30 ms`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.926: soe: PAUSED -> PLAYING -> VOID_PENDING`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:41.926: soe: total latency: 30 ms`
- when pipeline starts properly and is running there is `soe: pipeline state reading was succesfull` message every time when something changes in PipeWire (in my case pausing and unpausing music in Firefox)
- when pipeline doesn't start properly I get these messages in log:
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:53.470: soe: pipeline state reading was succesfull`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:53.474: soe: NULL -> READY -> PLAYING`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:53.474: soe: READY -> PAUSED -> PLAYING`
`(pulseeffects:506910): pulseeffects-DEBUG: 00:46:53.479: soe: sampling rate: 48000 Hz`
`(pulseeffects:506910): pulseeffects-WARNING **: 00:47:05.513: soe: trying to update the pipeline state during an async change!!`
- when I'm trying to play something after pipeline didn't start properly I'm getting `soe: trying to update the pipeline state during an async change!!` every time ui unfreezes or updates (in this case this message appears twice, after update and unfreeze).
- I guess pipeline is stuck in asynchronous update after it fails to start since `soe: pipeline state reading was succesfull` never appears again
- ui unfreezes way quicker now

**Comment by wwmm** [comment]
>What cpu do you have in your laptop?

In my laptop the cpu is a `i7-7500u`. Another Intel... Curious...

>I guess pipeline is stuck in asynchronous update

That is what is happening. I spent hours looking at gstreamer logs and the pipeline gets stuck at the last stages done to go to the playing state. I added to the latest code in the master branch some loops that wait for the async change to finish. But the freezes still happen. Not waiting for them is not the problem. I am starting to suspect that under some circumstances something is going wrong in `pipewiresrc` or `pipewiresink`. In case you want to see these plugins debug message you can do something like this
```
GST_DEBUG=2,pipewiresrc:5 ./pulseeffects
```
`:5` is the plugin debug level. You can change 5 by 6 but as usual it gets too verbose. In the next days I will try to take a closer look at their logs. I think I saw warnings today that I do not see on my desktop.

**Comment by wwmm** [comment]
If I am not mistaken the GStreamer warning that I see in the laptop but not in the desktop says `can't change flushing state of inactive pool`. I do not remember now if they were shown while looking at `pipewiresrc` or `pipewiresink` logs. But it would be good to know if other systems having freezes are also showing it.

**Comment by wwmm** [comment]
Setting the GStreamer thread to real time seems to have an effect in this bug. It is a lot harder to reproduce it when real time is used. This can be done in PulseEffects menu.

**Comment by halfrafu** [comment]
I'm getting `can't change flushing state of inactive pool` when I enable `pipewiresink` debug messages. It appears twice when pipeline stops. I've noticed when pipeline works properly both `gstpipewiresink.c:625:gst_pipewire_sink_render: push buffer` and `gstpipewiresink.c:462:on_process: signal` messages appear but after pipeline fails to start only `on_process: signal` one appears.

> Setting the GStreamer thread to real time seems to have an effect in this bug. It is a lot harder to reproduce it when real time is used. This can be done in PulseEffects menu.

I'll try it on my end.

**Comment by wwmm** [comment]
>I'm getting can't change flushing state of inactive pool when I enable pipewiresink debug messages. It appears twice when pipeline stops

Same thing in my laptop. And I still do not see them in my desktop. Never. They just do not happen there. I will open an issue in the PipeWire page. `pipewirepool` may be related to these random freezes

**Comment by wwmm** [comment]
>after pipeline fails to start, only on_process: signal one appears.

I have also noticed that. It is strange.

Link to the issue https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/750

**Comment by farmerbobathan** [comment]
I'm having similar issues with pulseeffects freezing and having to kill it and restart it. I'm on arch with an i7-6650u.

**Comment by wwmm** [comment]
@farmerbobathan do you also have the `inactive pool` messages in the pipewire plugins logs?

**Comment by farmerbobathan** [comment]
How would I check that?

**Comment by halfrafu** [comment]
@farmerbobathan Start pulseeffects with `GST_DEBUG=2,pipewiresink:5 pulseeffects` command and look for `can't change flushing state of inactive pool`. It should appear every time pipeline stops.

**Comment by farmerbobathan** [comment]
Thanks, yes I'm getting that after pausing a youtube video in firefox.

**Comment by wwmm** [comment]
After setting async = 0 in pipewiresink to disable its feature `Go asynchronously to PAUSED` I noticed a significant change in the pipeline freeze. When the problem happens the pipeline stays inert and there is not sound. But now the application does not have to be killed. Alternating the audio app between play and pause is enough to bring back sound.

**Comment by halfrafu** [comment]
I've been using GStreamer thread with real time priority for a few days and can confirm that freezes happen way less often.

**Comment by zer0exia** [comment]
I might having this issue as well. Well, maybe sort of. It never occurs if pulseeffects is left running with debug terminal in the foreground. There's no error that I can see in the log. However if I run it normally, closed the UI and let pulseeffects running in the background, sometimes there will be no audio, or the UI freezing when I reopen it. Pulseffects also always won't work after awaking the system from being suspended. Audio is immediately restored when pulseeffects process is killed.

**System Info**
EndeavorOS 
5.11.2-arch1-1
Pulseeffects 5.0.0-1, pipewire 0.3.22-1

**Comment by wwmm** [comment]
@zer0exia if possible try to use a package that builds from the master branch in our git repository. Although a real fix to this issue may require improvements in PipeWire's plugins for Gstreamer things are a little better in the latest version. I also recommend enabling realtime scheduling in PulseEffects menu.

And even after all this time I still can not reproduce this issue in my desktop. Only in my laptop...

**Comment by zer0exia** [comment]
@wwmm I've installed the latest git version from AUR, and also enabled realtime in Pulseeffects menu. The problems still occur occasionally. I have no idea how to produce this bug reliably because the logs didn't show anything significant, even during audio lost.

Here's the logs if it would be any help. Audio was lost twice during this session. Didn't need to kill pulseeffects, just disable and re-enable restores the audio.
[logs.txt](https://github.com/wwmm/pulseeffects/files/6057456/logs.txt)

**Comment by wwmm** [comment]
>I have no idea how to produce this bug reliably because the logs didn't show anything significant

Same thing on my Intel laptop. I can reproduce the issue there but it is random. Which kind of hardware do you have? I still do not have a clear idea about which is the difference between the systems that have and the ones that do not have this problem.

**Comment by zer0exia** [comment]
@wwmm I think this might be more common to Intel-based system.
My spec : 
Intel i3-4160
Asus Z97m-plus
Realtek ALC887 onboard chipset

**Comment by wwmm** [comment]
>I think this might be more common to Intel-based system.

Maybe. My desktop has a Ryzen CPU but we will only know if this is an Intel only issue if we see more people on AMD reporting that they also do not have the problem.

**Comment by farmerbobathan** [comment]
I was able to reproduce the problem with `inactive pool` messages in the logs on an AMD FX-8800P laptop.

**Comment by wwmm** [comment]
Ok. It is not an Intel issue. Now the only difference I see between the systems that have the problem and the ones that do not have are the `inactive pool` messages showed by the PipeWire's plugins pipewiresrc and pipewiresink. I did not have a response yet in the issue I have opened in PipeWire's page.

**Comment by wwmm** [comment]
This issue should not be a problem in the just released EasyEffects `6.0.0`. And even if it still is we are not using GStreamer anymore. So a new issue will be needed anyway.
