### ISSUE TITLE
Will pulseaudio-legacy get releases?

### ISSUE THREAD

**Issue by FFY00** [wwmm/easyeffects#912]
Hi, I understand the pulseaudio-legacy branch is under maintenance mode only, but will it receive 4.x releases as needed?

**Comment by Digitalone1** [comment]
Sure, only patches to fix issues. It works for now, so there's no need to change it. Obviously it will remain on GTK3, the port on GTK4 won't be done.

**Comment by Digitalone1** [comment]
I see you maintain the package on Arch Linux. Please, take in consideration the comment of Morfeo [here](https://bugs.archlinux.org/task/69437?project=5&string=pulseeffects).

A better packaging approach, that split pulseeffects GTK application and pulseeffects gst plugins (for headless scenarios). See [pulseeffects-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pulseeffects-git).

**Comment by wwmm** [comment]
>but will it receive 4.x releases as needed?

Yes. So far there was no change that really justified a new 4.x release. But if necessary they will be done.

**Comment by FFY00** [comment]
Thank you for clarifying. I am considering adding a `pulseeffects-legacy` package to the Arch Linux repos as there are still some missing bits from pipewire, such as pacmd.
