### ISSUE TITLE
Cannot use the automatically preset after upgrade to 5.x.x

### ISSUE THREAD

**Issue by dunghoilyd01** [wwmm/easyeffects#918]
I am using KDE on Gentoo, using pipewire. I create 2 different preset for each device, one for speakers, one for the headset (4 pin combo headphone+mic on laptop). When i plugged in the headset jack, pulseeffects preset is still not changed, even the pavucontrol can detect what device i am using.
This issue will not happen if i use the 4.7.2 with the alsa and the old pulseaudio.

**Comment by wwmm** [comment]
Try to remove the files in the folder `~/.config/PulseEffects/autoload/` and do the autoload association again. I am not sure Pulseaudio and PipeWire name the devices exactly in the same way.

**Comment by Tooniis** [comment]
I have the same issue

> Try to remove the files in the folder ~/.config/PulseEffects/autoload/ and do the autoload association again.

This didn't work.
I noticed that the sink doesn't change when I plug earphones in/out
Launching pulseeffects with earphones plugged in:
```
(pulseeffects:12589): pulseeffects-DEBUG: 11:50:19.056: new default sink: alsa_output.pci-0000_00_1f.3.analog-stereo
(pulseeffects:12589): pulseeffects-DEBUG: 11:50:19.056: new default source: alsa_input.pci-0000_00_1f.3.analog-stereo
(pulseeffects:12589): pulseeffects-DEBUG: 11:50:21.255: presets_manager: autoloading preset Earphones for device alsa_output.pci-0000_00_1f.3.analog-stereo
```
When unplugging earphones I don't get a new default sink message, and when I set autoload to another preset:
```
(pulseeffects:12589): pulseeffects-DEBUG: 11:50:51.960: presets_manager: added autoload preset file: /home/yassine/.config/PulseEffects/autoload/alsa_output.pci-0000_00_1f.3.analog-stereo.json
```
It's still `alsa_output.pci-0000_00_1f.3.analog-stereo`.

**Comment by wwmm** [comment]
>When unplugging earphones I don't get a new default sink message

So in PipeWire we have the same behavior as in Pulseaudio... For some reason there are hardware for which a headphone connection does not lead to a new sink creation by the sound server. Dealing with this in Pulseaudio was far from obvious... I was hoping this kind of thing would not happen in PipeWire... I will have to see what is changed in the PipeWire's device sink when the headphone is connected. Save to a file the output of `pw-dump` with and without the headphones. With luck it will show if there is a property I could use to detect that a headphone was plugged.

**Comment by Tooniis** [comment]
> Save to a file the output of pw-dump with and without the headphones.

**Comment by wwmm** [comment]
This is going to be tough... So far I see no difference in each Node properties. I think I will have to contact PipeWire's developer for guidance on this...

**Comment by dunghoilyd01** [comment]
Today i fall back to the PulseEffects 4.8.4 and realize, with pipewire-pulse.socket, PulseEffects 4.8.4 is working. This old version depend on PulseAudio (mine is 14.2.0) for device detection (i mean Headphone/Speakers). PulseEffects still using the right preset that i create for each device. So, my idea is, can you implement function/method or something to watch what changed on pulseaudio, and the audio processing still do what it should do on pipewire?

**Comment by wwmm** [comment]
I already know what changes in Pulseaudio. Its sound card device has a property named `port`. If its value is not null then a headphone is plugged. This is what PulseEffects is using there. Pipewire's compatibility layer for Pulseaudio is probably simulating this behavior. And that is why it is working even when our Pulseaudio release is used in PipeWire. But as far as I can see PipeWire's sound card node do not have this property.

**Comment by wwmm** [comment]
I've opened an issue in PipeWire's page https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/935.

**Comment by wwmm** [comment]
I reimplemented the preset autoloading feature in our gtk4 branch
![Screenshot from 2021-07-01 13-17-43](https://user-images.githubusercontent.com/16225172/124162804-434bc500-da75-11eb-9111-139e3eea8528.png)

I think that this issue should be fixed now. Are any of you able to test the gtk4 branch? People on Arch Linux have a pkgbuild on AUR that helps with that.

**Comment by Tooniis** [comment]
I still have only 1 sink:
![Screenshot from 2021-07-02 09-06-28](https://user-images.githubusercontent.com/36982494/124223461-d0922680-db14-11eb-9459-2b0bb8f558ec.png)

**Comment by Tooniis** [comment]
I still have 1 device:
![Screenshot from 2021-07-02 09-09-42](https://user-images.githubusercontent.com/36982494/124223703-4ac2ab00-db15-11eb-8732-765b39d20213.png)

**Comment by dunghoilyd01** [comment]
Tested on gentoo linux (KDE), still have only 1 sink. I think the reason on my laptop is that pipewire create only 1 sink per soundcard, means that my headphone and speaker share the same sink. And when the headphone plugged in 3.5 mm jack, it just redirect the analog signal to the headphone.

**Comment by wwmm** [comment]
>I still have 1 device:
>Tested on gentoo linux (KDE), still have only 1 sink.

If the computer has only one sound card only one device will be shown in our dropdown menu. This is fine. But depending on whether the headphone was plugged or not when the blue "Add button" was pressed different `Profile` values should be show in the list.

**Comment by wwmm** [comment]
>And when the headphone plugged in 3.5 mm jack, it just redirect the analog signal to the headphone.

Ok. But even if it just redirects I would expect the hardware to be put in a different profile. And as autoloading now works with a combination of device and hardware profile name things should be working.

**Comment by wwmm** [comment]
Now that EasyEffects 6.0.0 was released it will probably be better to create a new issue if this is still a problem.
