### ISSUE TITLE
Where to find APO presets? And others gstreamer presets?

### ISSUE THREAD

**Issue by servimo** [wwmm/easyeffects#926]
Where to find APO presets? And others gstreamer presets?
Do I need APO Equalizer to generate them?
How to edit gstreamer presets? Equalizer settings are only in the pulseeffects presets?

**Comment by wwmm** [comment]
As I never used APO I can not guide you on where to find presets for it. But if you are willing to enter each band configuration manually you do not have to install APO and generate preset files. Also have in mind that our support for APO presets is limited. 

>And others gstreamer presets?

When I added the presets from GStreamer I did not find others. I think these are all that there is. 

>How to edit gstreamer presets?

They can not be edited. After loading one of them save a custom preset using our presets menu next to the window title.

**Comment by servimo** [comment]
Thanks for the answers. That's what I found and thought, but maybe I was wrong at some point, so I asked. I will search the internet for some more info.

**Comment by grpan** [comment]
If you're a fan of the harman curve, you can try the [AutoEQ](https://github.com/jaakkopasanen/AutoEq) project or use my [list](https://github.com/grpan/Oratory1990-APO-Presets) converted from a preset database from [here](https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets).

**Comment by Ahmed-E-86** [comment]
@grpan That is a pretty big list. I have HP Probook 450 G1 with speaker that produces quite low sounds on Linux, but on Windows there are a few presets to choose from that gives a huge boost to the speakers. Any suggestions for my case?
