### ISSUE TITLE
How are the default devices in the settings menu determined?

### ISSUE THREAD

**Issue by tzx** [wwmm/easyeffects#931]
^

Also looking at the help, it seems like the settings menu section might be outdated. It think it should now be "Pipewire" instead of "Pulseaudio" in both the image and the subsection name.

**Comment by wwmm** [comment]
The devices in the menu are `input` or `output` devices available for use. This list is retrieved from the PipeWire server. We also receive from PipeWire which of these devices is the current default.

>Also looking at the help, it seems like the settings menu section might be outdated

It is and it will be even more outdated once I finished the work in the GTK4 branch. So I recommend anyone reading this to wait for the next big release before starting any work in the documentation.
