### ISSUE TITLE
Apply separate IRS files to Left and Right channels in Convolver?

### ISSUE THREAD

**Issue by taprobane99** [wwmm/easyeffects#937]
I have two .irs files, one for Left and one for Right channel.

When I apply these in convolver it seems to load the R one in both channels, even though I load the L one in the "O" tab, and then switch to the "1" tab before loading the R one.

What am I doing wrong?

**Comment by wwmm** [comment]
Our convolver supports only stereo impulse response files. Those tabs are only showing the graph of each channel data.

What you will have to do is creating one stereo wave file from your mono impulse files. Then import this stereo file and load it.

**Comment by taprobane99** [comment]
ok thanks.

how would i merge the mono files?

**Comment by wwmm** [comment]
>do you know why somebody might create a stereo irs for headphones and label it (L), and another labelled (R)?

That person probably had access to more advanced convolvers that can use multiple impulse files. But we are not there yet... I do not remember if I have ever tried to do something like this but it is possible that a ffmpeg command can combine these mono impulse files into a stereo file.

**Comment by wwmm** [comment]
Maybe this will help to get that in Audacity https://alcornmcbride.zendesk.com/hc/en-us/articles/360016439874-How-to-mix-two-Mono-Files-into-one-Stereo-File-using-Audacity
