### ISSUE TITLE
rnnoise plugin was not found!

### ISSUE THREAD

**Issue by maxorbase** [wwmm/easyeffects#940]
Install pulseaudio from official repository in Kubuntu 21.04 beta and rnnoise plugin was not found! 
Remove pulseaudio, install rnnnoise from git and reinstall pulseaudio rnnoise doesn't work 

`process:80693): pulseeffects-DEBUG: 01:46:11.174: main: locale directory: /usr/share/locale
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system input presets directory: "/etc/xdg/xdg-plasma/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system input presets directory: "/usr/share/kubuntu-default-settings/kf5-settings/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system output presets directory: "/etc/xdg/xdg-plasma/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: system output presets directory: "/usr/share/kubuntu-default-settings/kf5-settings/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/input
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/output
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.200: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/autoload
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.864: application: PE version: 4.8.4
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.865: pulse_manager: context is connecting
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.865: pulse_manager: context is authorizing
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.866: pulse_manager: context is setting name
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: context is ready
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: connected to: /run/user/1000/pulse/native
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: protocol version: 34
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: Pulseaudio version: 14.2
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.867: pulse_manager: loading Pulseeffects applications output sink...
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.868: pulse_manager: default pulseaudio sink sampling rate: 44100 Hz
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.868: pulse_manager: default pulseaudio sink audio format: s16le
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.868: pulse_manager:  failed to get sink info: PulseEffects_apps
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.877: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_apps sink_properties=device.description="PulseEffects(apps)"device.class="sound" norewinds=1
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.878: pulse_manager: changed volume of the sink: PulseEffects_apps
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.879: pulse_manager: loading Pulseeffects microphone output sink...
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.879: pulse_manager: default pulseaudio source sampling rate: 44100 Hz
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.879: pulse_manager: default pulseaudio source audio format: s16le
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.879: pulse_manager:  failed to get sink info: PulseEffects_mic
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.885: pulse_manager: loaded module-null-sink: sink_name=PulseEffects_mic sink_properties=device.description="PulseEffects(mic)"device.class="sound" norewinds=1
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:11.886: pulse_manager: changed volume of the sink: PulseEffects_mic
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:15.839: sie: using input device: PulseEffects_apps.monitor
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:15.839: sie: using output device: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:15.891: sie: limiter is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:15.900: sie: compressor is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:15.905: sie: filter is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.013: sie: equalizer is enabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.017: sie: reverb is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.021: sie: bass_enhancer is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.025: sie: exciter is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.031: sie: crossfeed is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.036: sie: maximizer is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.044: sie: multiband_compressor is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.050: sie: loudness is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.055: sie: gate is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.063: sie: pitch is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.071: sie: multiband_gate is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.075: sie: deesser is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.079: sie: stereo_tools is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.090: sie: convolver is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.096: sie: crystalizer is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.100: sie: autogain is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.107: sie: delay is already disabled

(pulseeffects:80693): pulseeffects-WARNING **: 01:46:16.107: rnnoise plugin was not found!
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.123: soe: using output device: PulseEffects_mic
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.123: soe: using input device: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.125: soe: limiter is enabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.126: soe: compressor is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.127: soe: filter is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.141: soe: equalizer is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.142: soe: reverb is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.144: soe: gate is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.146: soe: deesser is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.148: soe: pitch is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.162: soe: webrtc is enabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.164: soe: multiband_compressor is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.167: soe: multiband_gate is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.168: soe: stereo_tools is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.169: soe: maximizer is already disabled

(pulseeffects:80693): pulseeffects-WARNING **: 01:46:16.170: rnnoise plugin was not found!
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system input presets directory: "/etc/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system input presets directory: "/etc/xdg/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system input presets directory: "/etc/xdg/xdg-plasma/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system input presets directory: "/usr/share/kubuntu-default-settings/kf5-settings/PulseEffects/input"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system output presets directory: "/etc/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system output presets directory: "/etc/xdg/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system output presets directory: "/etc/xdg/xdg-plasma/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: system output presets directory: "/usr/share/kubuntu-default-settings/kf5-settings/PulseEffects/output"; 
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/input
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/output
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: user presets directory already exists: /home/admin/.config/PulseEffects/autoload
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: presets_manager: destroyed
pulseeffects-INFO: 01:46:16.180: application: disabling global bypass
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: sie: bypass is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:16.180: soe: bypass is already disabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:17.196: convolver_ui: irs directory already exists: /home/admin/.config/PulseEffects/irs
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:17.228: rnnoise_ui: model directory already exists: /home/admin/.config/PulseEffects/rnnoise
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:18.330: rnnoise_ui: model directory already exists: /home/admin/.config/PulseEffects/rnnoise
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:18.435: sie: spectrum enabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:18.436: soe: spectrum enabled
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.811: sie: sampling rate: 44100 Hz
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: sie: using output device: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: pulse_settings_ui: output device changed: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: pulse_settings_ui: added sink: alsa_output.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: pulse_settings_ui: added source: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: soe: using input device: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: pulse_settings_ui: input device changed: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.834: pulse_settings_ui: added source: alsa_input.pci-0000_00_1b.0.analog-stereo
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.858: sie: NULL -> READY -> PLAYING
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.860: sie: READY -> PAUSED -> PLAYING
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.861: sie: pulsesrc latency [us]: 10000
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.862: sie: pulsesrc buffer [us]: 200000
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.862: sie: total latency: 0 ms
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.934: sie: total latency: 140 ms
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.993: sie: pulsesink latency [us]: 10000
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.993: sie: pulsesink buffer [us]: 200000
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.994: sie: total latency: 140 ms
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.994: sie: PAUSED -> PLAYING -> VOID_PENDING
(pulseeffects:80693): pulseeffects-DEBUG: 01:46:19.995: sie: total latency: 140 ms
`

**Comment by wwmm** [comment]
The rnnoise plugin is different from the others. The library has to be installed when the PulseEffects package is compiled. This is probably the source of the problem. You need a package that has been compiled with rnnoise support.

**Comment by maxorbase** [comment]
> The rnnoise plugin is different from the others. The library has to be installed when the PulseEffects package is compiled. This is probably the source of the problem. You need a package that has been compiled with rnnoise support.

Are we have a chance plugin corrected in future release ???
Because when I want to compile package this error happen

**Comment by wwmm** [comment]
>Are we have a chance plugin corrected in future release ???

As I do not maintain packages for distributions I do not know. Maybe you can try a flatpak package while the debian package is not updated. But I am not sure if the flatpak package has been updated with rnnoise support.

**Comment by exeqtion** [comment]
I am also having the same problem on Gentoo/Linux, I installed rnnoise from [here](https://github.com/xiph/rnnoise). And while emerging (compiling) pulseeffects I noticed this.
```
Run-time dependency rnnoise found: NO (tried pkgconfig and cmake)
Message: could not find the RNNoise library
```

I did `ls -al | grep -i rnnoise` in `/usr/local/lib`, so I am pretty much sure library is there.
```
-rw-r--r-- 1 root root 307160 Apr 12 18:20 librnnoise.a
-rwxr-xr-x 1 root root    941 Apr 12 18:20 librnnoise.la
lrwxrwxrwx 1 root root     19 Apr 12 18:20 librnnoise.so -> librnnoise.so.0.4.1
lrwxrwxrwx 1 root root     19 Apr 12 18:20 librnnoise.so.0 -> librnnoise.so.0.4.1
-rwxr-xr-x 1 root root 254256 Apr 12 18:20 librnnoise.so.0.4.1
```
And I also installed it from flatpak beta repo but I cannot even run that also. I think flatpak needs its own thread, I will look more into it and will create the thread later in few days.

**Comment by wwmm** [comment]
@exeqtion I just ask Meson to find it https://github.com/wwmm/pulseeffects/blob/e321795c6a8dae22e6a5d01d009edb586694fa24/src/rnnoise/meson.build#L1 like any of the other libraries. Could it be that Meson is having problems with the fact you have the library installed under `/usr/local`?

**Comment by exeqtion** [comment]
Probably, but I am not sure how to confirm it.

**Comment by wwmm** [comment]
Meson uses `pkgconfig` to find libraries. What is the content of `/usr/local//lib/pkgconfig/rnnoise.pc`? Maybe it has the wrong path or pkgconfig is nor considering `/usr/local`

**Comment by exeqtion** [comment]
```
# rnnoise installed pkg-config file

prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: rnnoise
Description: RNN-based noise suppression
Version: unknown
Conflicts:
Libs: -L${libdir} -lrnnoise
Libs.private:
Cflags: -I${includedir}/

```

**Comment by wwmm** [comment]
>Also, I did pkg-config --list-all | grep -i rnn and It returned nothing.

This is the output here on Arch Linux
```
rnnoise                        rnnoise - RNN-based noise suppression
```

But I have rnnoise installed in the traditional path. Not under /usr/local

**Comment by exeqtion** [comment]
That helped! I added path for pkg-config in global environment (/etc/environment) `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`. Now it detects the libs and rnnoise works in pulseeffects.

**Comment by wwmm** [comment]
In EasyEffects 6.0.0 rnnoise is a required library. So this kind of problem should not happen anymore.

**Comment by wwmm** [comment]
>I have EasyEffects 6.3.0 on Ubuntu 22.10 and the problem is still here

For license reasons Deabian cannot have rnnoise in its repositories. So the noise reduction plugin has to be disabled when compiling Debian packages.

**Comment by mattiasghodsian** [comment]
@wwmm I notise that when i went back to Debian, do i need to compile EasyEffects from source to get rnnoise ?

**Comment by wwmm** [comment]
>I notise that when i went back to Debian, do i need to compile EasyEffects from source to get rnnoise ?

Yes. The package in its repository probably still has rnnoise disabled at compilation time. So you will have to build your own. OR use a Flatpak package.

**Comment by maghogrebban** [comment]
> Yes. The package in its repository probably still has rnnoise disabled at compilation time. So you will have to build your own. Or using a Flatpak package.

Debian 12 gnome 44

```
$ flatpak-builder build-dir --user --install util/flatpak/com.github.wwmm.easyeffects.Devel.json --force-clean --ccache

error: org.gnome.Platform/x86_64/44 not installed
Failed to init: Unable to find runtime org.gnome.Platform version 44
```

**Comment by wwmm** [comment]
Did you try the steps at https://github.com/wwmm/easyeffects/wiki/Package-Repositories#flatpak ?

**Comment by wwmm** [comment]
The Flatpak package is already built with rnnoise enabled. So it should not be necessary to compile your won Flatpak package.

**Comment by mattiasghodsian** [comment]
Downloaded tag [v7.0.8](https://github.com/wwmm/easyeffects/releases/tag/v7.0.8) and was able to compile it, for some reason rnnoise don't really filter out the TV that good

**Comment by wwmm** [comment]
>for some reason rnnoise don't really filter out the TV that good

It may happen. RNNoise built-in model was trained by its developers for a few types of noise. If it is a noise that is too different from the ones in the training the filtering is not going to be very good.

The `speex processor` plugin has a more generic noise reduction filter that helps in some of the cases where rnnoise does not work well. It is worth a try.

**Comment by mattiasghodsian** [comment]
Checkout `speex processor` with `rnnoise` but i sound like a robot

**Comment by KaranAhlawat** [comment]
Hey so, I'm on Debian 12. Reading the discussion, I tried installing the flatpak EasyEffects version (7.0.8), which should have been built with RNNoise by default. However, if I add the noise cancellation plugin, it still tells me I do not have the RNNoise library.

Do I need to first have RNNoise under `/usr/local/lib/` and then install the flatpak?

**Comment by mattiasghodsian** [comment]
@KaranAhlawat I have rnnoise under ` /usr/local/lib` still didn't work deb or flatpak version, by building the flatpak from source i got it working.

**Comment by wwmm** [comment]
>I tried installing the flatpak EasyEffects version (7.0.8), which should have been built with RNNoise by default. However, if I add the noise cancellation plugin, it still tells me I do not have the RNNoise library.

Is this how it should be @vchernin ? I thought that the Flatpak package had rnnoise enabled.

**Comment by KaranAhlawat** [comment]
@mattiasghodsian I spent around an hour building from source on deb, and even though the output indicated that rnnoise was found, I'm still running into the same issue.

**Comment by KaranAhlawat** [comment]
Okay, built from Flatpak source, it seems to work now.

**Comment by vchernin** [comment]
> Is this how it should be @vchernin ? I thought that the Flatpak package had rnnoise enabled.

The rnnoise plugin is definitely there in flatpak 7.0.8. @KaranAhlawat are you sure you launched the flatpak build, not the deb build?

```bash
flatpak install flathub com.github.wwmm.easyeffects//stable
flatpak run com.github.wwmm.easyeffects//stable
```

**Comment by KaranAhlawat** [comment]
Huh yeah, that seems to work now. No idea why it's working but I'll take it 😄

**Comment by guss77** [comment]
I've just installed the Flatpak version 7.1.0, which appears to have rnnoise built into it - at least I can see it in the flatpak:

```
$ ll /var/lib/flatpak/app/com.github.wwmm.easyeffects/current/active/files/lib/ | grep noise
lrwxrwxrwx 1 root root   19 Sep 12 20:04 librnnoise.so -> librnnoise.so.0.4.1*
lrwxrwxrwx 1 root root   19 Sep 12 20:04 librnnoise.so.0 -> librnnoise.so.0.4.1*
-rwxr-xr-x 2 root root 127K Jan  1  1970 librnnoise.so.0.4.1*
```

But when I run the flatpak (`flatpak run com.github.wwmm.easyeffects//stable`), it tells me that RNNoise is not installed in the system.

**Comment by guss77** [comment]
Install the flatpak package from the CI build does allow me to use RNNoise.

**Comment by mattiasghodsian** [comment]
@guss77 Build the flatpak from source instead

**Comment by vchernin** [comment]
> But when I run the flatpak (flatpak run com.github.wwmm.easyeffects//stable), it tells me that RNNoise is not installed in the system.

This is not the same behaviour I see. It should not be possible to have a bundled library completely missing from some flatpak installations. Can you confirm no other easyeffects instances are running? Can you try `flatpak repair --user` and `sudo flatpak repair --system`

**Comment by guss77** [comment]
After I installed the devel flatpak, which had RNNoise working for me, removing it and re-installing the flathub flatpak, RNNoise now works there as well :shrug:
