### ISSUE TITLE
No convolver for microphone calibration?

### ISSUE THREAD

**Issue by keantoken** [wwmm/easyeffects#948]
Doesn't it make sense to have a convolver to apply a microphone correction?

**Comment by wwmm** [comment]
>Doesn't it make sense to have a convolver to apply a microphone correction?

Maybe it does. In the gtk4 branch #904 I have already allowed the convolver to be used in both pipelines. I do not know if I will have time to backport this to the other branches...

**Comment by keantoken** [comment]
I could never get Pipewire to work.

**Comment by wwmm** [comment]
It can be done in EasyEffects 6.0.0.
