### ISSUE TITLE
Modules not enabling unless GUI is loaded

### ISSUE THREAD

**Issue by dwijenchawra** [wwmm/easyeffects#952]
Hey there,

I've recently run into an issue with pulseeffects, whenever I try to restart my computer and have it autostart, it starts in the background and creates a headphone and a mic sink, but does not use any of the enabled modules. I have to open the GUI, uncheck the module, and then select it again for the modules to activate. Any pointers on how to fix this issue?

CPU: Quad Core Intel Core i5-8250U (-MT MCP-) speed/max: 1600/1600 MHz Kernel: 5.9.16-1-MANJARO x86_64 Up: 8m 
Mem: 8927.7/15878.1 MiB (56.2%) Storage: 685.61 GiB (9.3% used) Procs: 317 Shell: Zsh inxi: 3.3.03 

manjaro-pulse 20210109-1
pipewire-pulse 1:0.3.23-1
pulseaudio-alsa 1:1.2.2-2
pulseaudio-ctl 1.67-1
pulseaudio-equalizer 14.2-2
pulseaudio-equalizer-ladspa 3.0.2-4
pulseaudio-jack 14.2-2
pulseaudio-lirc 14.2-2
pulseaudio-qt 1.2-2
pulseaudio-rtp 14.2-2
pulseaudio-zeroconf 14.2-2
pulseeffects 5.0.1-1

**Comment by wwmm** [comment]
>but does not use any of the enabled modules

By modules do you mean each audio effects plugin?

>pulseeffects 5.0.1-1

That version has some serious bugs. Specially when dconf `0.40` is installed in the system. So my first suggestion would be to update our package. In any case it may help to see some logs. Kill the current instance `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`.

**Comment by dwijenchawra** [comment]
Hello wwmm,

Thanks for the fast reply. Here are the logs from the version 5.0.1-1

[https://pastebin.com/bQXkhfVd](url)

I will update my system along with the pulseeffects package and let you know what happens after.

**Comment by wwmm** [comment]
The pastebin link is not working. As the contents are probably not big you can save it to a txt file and attach it here.

**Comment by dwijenchawra** [comment]
Hi there, sorry for the delay. Heres the output.
[bQXkhfVd.txt](https://github.com/wwmm/pulseeffects/files/6453252/bQXkhfVd.txt)

**Comment by dwijenchawra** [comment]
This is what I get when I disable the equalizer after startup and re enable it to make it work

`(pulseeffects:5585): pulseeffects-DEBUG: 09:01:49.022: sie: equalizer is already disabled

(pulseeffects:5585): pulseeffects-DEBUG: 09:01:53.857: sie: equalizer is enabled
`

**Comment by genes1122** [comment]
I have the same problem with version 4.8.4-1.6 in openSUSE.  I got around it by starting pulseeffects with a script that loads a preset with the equalizer off, then loads the preset that has the equalizer on.  Here's the shell script:

`> cat /usr/local/bin/pulseeffects-fix 
#!/usr/bin/bash

pulseeffects --gapplication-service &
sleep 1
pulseeffects -l 13-band-off
sleep 1
pulseeffects -l 13-band-perfect
`
I'm not sure in which version this bug first appeared.  With out disabling and enabling the equalizer, the output bars in the pulseeffects gui don't move, and changing the sliders has no effect.

Thanks,
Gene

**Comment by wwmm** [comment]
@genes1122 our Pulseaudio branch also needed an upgrade for systems with `dconf 0.40`. If you have this dconf version in your system you will need PE `4.8.5` instead of `4.8.4`

**Comment by genes1122** [comment]
Thanks, I'll mention that in openSUSE.

Gene

**Comment by wwmm** [comment]
This probably won't be an issue anymore in EasyEffects 6.0.0
