### ISSUE TITLE
Compile in container, install locally?

### ISSUE THREAD

**Issue by DanMan** [wwmm/easyeffects#955]
After successfully compiling v5.0.3 on Fedora in a container/toolbox, I'm now trying to install the generated binary outside of it in my main system.

Running `ninja install` it was complaining about a missing `/usr/lib64/libpipewire-0.3.so` which I solved by installing `pipewire-devel`. Now it's complaining about a missing `/usr/lib64/libglib-2.0.so` …

I might be able to solve that by installing that dev package, too, but the reason I compiled it in a container was so I do `not` have to install all those devel packages in my main system. Is there any way around that? Sorry if this is a dumb question, but I'm pretty clueless when it comes to compiling.

So is there a way to install the compiled binary without having to install all those libs? Can I add those as static dependencies somehow?

P.S.: Building the source as Flatpak came to a halt when it tried to build `zita-convolver` so I abandoned that.

**Comment by wwmm** [comment]
>Running ninja install it was complaining about a missing /usr/lib64/libpipewire-0.3.so which I solved by installing pipewire-devel. Now it's complaining about a missing /usr/lib64/libglib-2.0.so …

If I understood correctly you compiled the source in a container but is trying to call `ninja install` in your system. I am not sure this is going to work. The libraries path exposed by the container may not be the same. It is also strange you had to install a devel package for a library to be found. usually they have only headers. Maybe the `pkg-config` file Meson needs to find the libraries is being provided by the devel package. In that case it makes sense you have to install them.

>Can I add those as static dependencies somehow?

I never tried to do static compilation. But my guess is that it is not going to work because some of the libraries we have to use do not offer a static version. Only dynamic.

**Comment by DanMan** [comment]
Yes, I created a Fedora 33 container, installed all the requirements (including `pipewire-devel` or it wouldn't compile) in there and compiled the source. Then I closed the container and tried to install the compiled binary with `ninja`, and then I got those errors.

I've taken another look and my actual issue is that pulseeffects is looking for `/usr/lib64/libpipewire-0.3.so` but it's actually called `/usr/lib64/libpipewire-0.3.so.0` on my system. Same for all the other shared objects. Any way to fix that on the compilation side or do I have to create lots of symlinks now?

**Comment by wwmm** [comment]
>my actual issue is that pulseeffects is looking for /usr/lib64/libpipewire-0.3.so but it's actually called /usr/lib64/libpipewire-0.3.so.0 on my system

We do not hard code libraries paths in our sources. We ask `Meson` to find the library, compile our code and link everything. My guess is that the `ninja install` phase is redoing or finishing some kind of link and this is done directly with `libpipewire-0.3.so` and not with a link to it. Why it is this way only Meson developers can tell. As far as I remember package maintainers run `ninja install` in the container but with the installation prefix set to a custom path. And after that they adjust things by copying the files to the final package in a way that things are installed where they have to be. I am not a Meson expert but running `ninja install` outside of the environment where the compilation was done is probably not supported.

**Comment by DanMan** [comment]
I can [run it directly on the main system as outlined on the wiki](https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository#run-without-installing), but Ninja for some reason can't install it from there.

I'll cut my losses here for now since I don't want to bother you any longer. Thanks for the help anyway.

**Comment by wwmm** [comment]
Something you can try is setting a custom installation path. It can be done this way `meson _build --prefix=/tmp/pe`
