### ISSUE TITLE
Priority settings seem to have no effect (EndeavourOS)

### ISSUE THREAD

**Issue by magicgoose** [wwmm/easyeffects#967]
Installed from https://archlinux.org/packages/community/x86_64/pulseeffects/ 

I've been trying to find a workaround for the problem where the sound will glitch when the system is under I/O load. (happens only with pulseeffects enabled, so it's likely not a pipewire/driver problem.) I thought I should try raising priority of pulseeffects, it even has settings UI to do this, but apparently it has no effect.

I started some audio playback in an app, then I'm changing priority settings in pulseeffects. When I make a change, there's a short audio glitch (as expected, it probably restarts some stuff), but none of the priority values displayed in `htop` are changed. (I ran `htop` with sudo, so it should see all processes, right?)

Here's a screenshot to illustrate it better.
![image](https://user-images.githubusercontent.com/1442206/118392708-d4d0b600-b632-11eb-8e90-7629acea6c08.png)

Any ideas what can be done to troubleshoot this?

Distro: EndeavourOS
linux-zen kernel
my user is in realtime group (`groups` output contains `realtime`)

**Comment by wwmm** [comment]
As you can see in #950 our current release is having serious problems when trying to enable realtime. I really do not know what has changed in the low level system libraries that could be causing these issues. The part of PulseEffects that changes priorities haven't been modified in months.

In the work I am doing in our gtk4 branch I am reimplementing the effects pipeline with an approach based on native PipeWire filters. In this case PipeWire is the one setting the plugin thread to realtime. So far this is working fine. But there is still a lot to be done before releasing this branch to the general public.

**Comment by wwmm** [comment]
In EasyEffects 6.0.0 priorities are handled by PipeWire. We can close this issue.
