### ISSUE TITLE
Add Switch to temporarily monitor Microphone effects on speaker

### ISSUE THREAD

**Issue by andigandi** [wwmm/easyeffects#970]
One thing I am missing in this great software is a switch to temporarily monitor the microphone effects on speaker. My current workflow to see how the effects affect my voice is to run `pw-jack qjackctl, open the Graph view and draw lines from PulseEffects Source Monitor's capture_FL and capture_FR to my output device.
Please consider adding an option to automate this process. A possible place would be a "Monitor" entry in the applications list for microphone effects.
I think there are many other people who would love to see a feature like this implemented.

**Comment by wwmm** [comment]
I have to think about how much complexity this feature would add. Usually when I need to listen to my mic output I run `gst-launch-1.0 pulsesrc ! queue ! pulsesink` and enable this stream in our mic effects section. So far this has been enough.

Now that our gtk4 branch is based on native PipeWire filters maybe there will be an easy way to add this functionality.

**Comment by wwmm** [comment]
Implemented in our gtk4 branch. Now there is a button for this in the bottom right corner of the window
![Screenshot from 2021-07-05 23-10-56](https://user-images.githubusercontent.com/16225172/124532657-59e07c00-dde7-11eb-847a-044f5405c7de.png)
