### ISSUE TITLE
Use an external source as the compressor's sidechain input

### ISSUE THREAD

**Issue by AlexWayfer** [wwmm/easyeffects#974]
I see sidechain compressors in PulseEffects for output and input, but I don't see a possibility to choke global output volume on input signal as it's possible in OBS, for example.

I'd be great.

Discussion: https://github.com/wwmm/pulseeffects/discussions/973#discussioncomment-783523

**Comment by wwmm** [comment]
I think this can be done with this compressor https://lsp-plug.in/?page=manuals&section=sc_compressor_stereo. It has essentially the same controls as the one we are current using https://lsp-plug.in/?page=manuals&section=compressor_stereo but it allows the sidechain input to be connected to an external source. 

It seems that it will be a lot easier than I initially thought. If at the end of the day all the other controls are shown to be really the same all that is left to be done is actually connecting the sidechain ports to the microphone.

In any case I can already see that it would be impossible to use this plugin in the GStreamer wrapper for LV2 plugins as it only sees the 2 input/output channels. As I had to write a simple wrapper for LV2 plugins while moving to Pipewire filters now I can connect to these extra ports with no problems. Let's see how this goes :-)

**Comment by wwmm** [comment]
For some reason the sidechain plugin is throwing a segmentation fault on my face. This may not be so easy after all XD

**Comment by wwmm** [comment]
The plugin is loading. Now I have to actually try to link its sidechain input to a source.

**Comment by wwmm** [comment]
I was able to make it work
![Screenshot from 2021-07-08 22-00-26](https://user-images.githubusercontent.com/16225172/125008400-cdc59300-e038-11eb-8e07-29a1db2ac2f5.png)
I have already updated the master branch with this. Although I do not have a use case for this at this moment I have to admit it is fun to see we can control the compression talking to the microphone :smile: 

@Digitalone1 I am not sure if you have any use for this feature but as you played with the compression before I am letting you know that this is possible now.

**Comment by Digitalone1** [comment]
That's great!

**Comment by AlexWayfer** [comment]
> Although I do not have any use for this at this moment I have to admit it is fun to see we can control the compression talking to the microphone

I mentioned OBS, the application for streaming (gaming, coding, something else). And the application itself has such feature, and it helps if you want to listen music, sometimes loudly, but also want to speak legibly "through" the music. So, there are many guides on YouTube how to configure this and allow viewers hear your speak and music when you are silent.

I just thought that I want to hear myself too, because when music is too loud — you can start scream to hear yourself. And OBS can low the music, but you'd be look more weird, screaming over silent music. So, this is handy feature, but it's better to be global, to affect streamer/recorder too.

But I'm not sure is it really cool and handy, but someones can appreciate it. I'm glad it was not too hard to implement.
