### ISSUE TITLE
When using `pulseeffects -l "preset_name"` it just returns code 1 instead of 0 even if the operation succeeded.

### ISSUE THREAD

**Issue by ruzito** [wwmm/easyeffects#978]
When using `pulseeffects -l "preset_name"` it just returns code `1` instead of `0` even if the operation succeeded.

**Comment by wwmm** [comment]
In EasyEffects we return `G_APPLICATION_CLASS(application_parent_class)->command_line(gapp, cmdline);`. So even if the problem still applies there isn't much that can be done about it as we have to call the gtk base class method at the end of the operation.
