### ISSUE TITLE
Use PipeWire filter infrastructure

### ISSUE THREAD

**Issue by grigorig** [wwmm/easyeffects#990]
PipeWire now has support for filtering built-in. I wonder whether it makes sense to implement PulseEffects filtering using that instead of virtual sinks and sources, which can be confusing.

**Comment by wwmm** [comment]
In my gtk4 branch I replaced gstreamer by native PipeWire filters `pw_filter`. PipeWire has offered them for a long time. What you are thinking about is a recent feature they added for users that want to use ladspa filters. Just a like pulseaudio can do.

Although I can connect each application directly to the first filter in ou pipeline this will complicate our code for little gain. Remember that in the gtk4 the user can actually remove a plugin from the pipeline. It is way easier to move the apps to our virtual source/sink and let them there. This way the code that adds/removes plugin to/from our pipeline can be simpler.

There are also the cases where the app does not allow us to cut it's connection to the sound card device. In this situation the user has to use the app panel to make it use our virtual device. Imagin now that we just connect it to the first filter in our pipeline. This app will send audio directly to the sound card and to our pipeline. It is bad.

**Comment by wwmm** [comment]
What is confusing about the virtual sources or sinks?

**Comment by grigorig** [comment]
It's mostly confusing that the sound control panel stops making sense (e.g. in GNOME).

**Comment by wwmm** [comment]
>It's mostly confusing that the sound control panel stops making sense (e.g. in GNOME).

I still do not understand how. When the computer has more than one sound card like it happens on mine there will be more entries in the audio manager. I do not see what changes if some of them are virtual.

**Comment by grigorig** [comment]
The fact that PulseEffects uses virtual devices to do its thing is an implementation detail. It's confusing for users, because the regular audio control panel normally controls which physical device sound is directed to, but with PulseEffects, it doesn't do that anymore. If you want to use PulseEffects, all audio must go into the virtual device. Users now need to change the actual output device inside PulseEffects.

IMHO it would be more sensible to transparently inject filtering into individual output (or input) devices on a per-device basis. Not sure if that is actually feasible with PipeWire right now, though.

**Comment by wwmm** [comment]
>If you want to use PulseEffects, all audio must go into the virtual device. Users now need to change the actual output device inside PulseEffects.

That is just the default behavior. You are free to disable `Process All Outputs` or `Process All Inputs` in our settings menu and use the per application switch to decide if an application should have effects or not. You do not have to process everything.

>IMHO it would be more sensible to transparently inject filtering into individual output (or input) devices on a per-device basis, or maybe on per stream basis.

Applying different effects to different streams is way more complicated. And will consume much more cpu time because each stream will have its own instance of each plugin. A complete redesign would be need for that.
