### ISSUE TITLE
Test signals ignore filters?

### ISSUE THREAD

**Issue by DanMan** [wwmm/easyeffects#993]
The EQ doesn't seem to have an effect on the test signals. Is that intentional? Since the EQ can have settings for each channel individually, I was trying to correct my hearing impediment on the left ear by trying to get the same volume level at a test frequency. So it would be nice, if maybe there was a switch in the test settings dialog to either bypass or include the active filters. Or if the existing, global bypass had an effect on the test signals, too.

**Comment by wwmm** [comment]
In the next big release this will be possible. But I think that you can not do what you want in the current stable release.

**Comment by wwmm** [comment]
The work I am doing in my gtk4 branch is almost ready. If you use Arch Linux there is a pkgbuild you can use to test it https://aur.archlinux.org/packages/easyeffects-git/.

**Comment by DanMan** [comment]
Awesome. I guess I could just use an external program to generate the sounds and run that through Pulseeffects, but I thought I mention it since there's already  a tone generator in there.

**Comment by wwmm** [comment]
It is possible to do that in EasyEffects 6.0.0. It still does not have as many signals types as there was before when we used GStreamer. The algorithm for some of them are more complicated than I was expecting. But in the next releases I think I will be able to add more.

**Comment by DanMan** [comment]
Thanks. Sinus wave is all I need.

But I've come to find that the generated tone isn't fixed. After a few seconds it shifts instantly to some slightly other frequency. Should I make a new ticket for that?

Also would be more convenient for my use, if it opened in a popup like the old one.

Just sayin' though. I should also be able to use Audacity for example.

**Comment by wwmm** [comment]
>But I've come to find that the generated tone isn't fixed. After a few seconds it shifts instantly to some slightly other frequency. Should I make a new ticket for that?

For some reason the algorithm I am using is unstable. I have to find a better one. I think it will be better to have a new issue to discuss this.

>Also would be more convenient for my use, if it opened in a popup like the old one.

I thought about that while doing the port. The problem is that the old approach had random crashes when closing the test signals window. And the reason why that happened was never clear. So I decided to keep the signals interface in the same window as all the rest.

**Comment by DanMan** [comment]
I think I'll just use https://onlinetonegenerator.com then. Thanks for all your work.
