### ISSUE TITLE
EasyEffects not building on Fedora 34 

### ISSUE THREAD

**Issue by 7RST1** [wwmm/easyeffects#998]
Since Fedora was mentioned in the, now a bit outdated, [building wiki article](https://github.com/wwmm/easyeffects/wiki/Installation-from-Source), I tried building 6.0 with no luck.
Running `meson build` gives a missing dependency. I've removed them one at a time from src/meson.build in order to see exactly which dependencies I was missing. I tried finding them, but for different reasons could not install them. Here is a list of them:

- glibmm-2.68
  - exists as glibmm24-devel, but at 2.66
- gtkmm-4.0
  - only 3.x pkgs exists
- lv2 (1.18.2)
  - at 1.18.0
- nlohmann_json
  - not found

I don't know what to make of this since I'm pretty new to meson/ninja, building repos and such. Does this means we just have to wait for upstream updates, or are there any build configs I am ignorant to that could help? Any answer could also be included on the article to help future Fedora users wanting to build EasyEffects.

**Comment by wwmm** [comment]
>Since Fedora was mentioned in the, now a bit outdated, building wiki article, 

Our wiki needs a major update. It would be good to have the community help for this. Specially considering I use only Arch Linux. If I am not mistaken any github user can edit our wiki.

**Comment by wwmm** [comment]
>Does this means we just have to wait for upstream updates

Even on Arch Linux that was the easiest thing to do. So it may be better to wait a little more.

**Comment by 7RST1** [comment]
Okay. Guess I can close this issue then, 'cause updating the Wiki seems like a whole other issue in itself.

Waiting eagerly for the easyeffects dnf. Thanks for your work on this amazing project btw!
